[id="con-gcp-backup-process"]

= The Backup Process

A backup enables you to backup your environment by saving the database and the shared file system. 
A new environment is created during the restore using the saved shared file system. 
When the environment is in place, the process can restore the database.

The backup and restore process must use the same version. 
If your backup was done with a prior version, you must use the restore process of the previous version. 
Then, if required, you can run an upgrade.

You must also take a backup before an upgrade. 
For further information, see xref:assembly-gcp-upgrade[Upgrading your deployment]

The backup process involves taking a backup of the Cloud SQL database and filestore instances at a given point in time.
The backup playbook require an active {AAPonGCP} foundation deployment to be running.

The following procedures describe how to backup the {AAPonGCP} deployment.

:context: backup
include::proc-gcp-backup-container-image.adoc[leveloffset=+1]
include::proc-gcp-setup-environment.adoc[leveloffset=+1]
include::proc-gcp-create-data-file.adoc[leveloffset=+1]
include::ref-gcp-populate-backup-file.adoc[leveloffset=+1]
include::proc-gcp-run-backup-playbook.adoc[leveloffset=+1]