[id="con-aap-aws-update-data-file"]

= Updating the data file

You must populate the data file before triggering the backup. 
The following variables are parameters listed in the data file.

* `cloud_credentials_path` is the path to your AWS credentials file. Ex. ~/.aws/credentials
* `deployment_name` is the name of the foundation deployment. This is the same name you used when you deployed the foundation.
* `aws_backup_iam_role_arn` is the _Amazon Resource Name_ (ARN) of the AWS IAM Role that has permissions to perform backup operations.
+
[NOTE]
====
You can use the AWS Backup Default Service Role for this which has the format `arn:aws:iam::<Your AWS Account Number>:role/service-role/AWSBackupDefaultServiceRole`. 
====
* `aws_backup_vault_name` is the name of the backup vault that holds the EFS recovery points.
* `aws_region` is the region the stack was deployed in.
* `aws_s3_bucket` is the name of the S3 bucket where the backup files are stored. 
This creates a new bucket if one does not already exist. 
Only the most recent backup is stored in the bucket. 
Every subsequent backup to the same bucket overwrites the backup files with the latest backup.

When you have populated the data file, it should resemble the following. 
The values in this file are provided as examples - 
----
aws_backup_stack:
  cloud_credentials_path: ~/.aws/credentials
  deployment_name: AnsibleAutomationPlatform
 extra_vars:
    aws_backup_iam_role: arn:aws:iam::<Your AWS Account Number>:role/service-role/AWSBackupDefaultServiceRole
	aws_backup_vault_name: Default
    aws_region: us-east-1
    aws_s3_bucket: AnsibleAutomationPlatform-bucket
----

