[id="con-azure-disaster-recovery_{context}"]

= Disaster Recovery

When you deploy {AAPonAzureNameShort}, you must enable or disable Disaster Recovery in the `Business Continuity` tab of the form.
There is no default setting for Disaster Recovery.

The Disaster Recovery feature incurs additional Azure infrastructure costs.
See xref:con-azure-infrastructure-usage_azure-intro[Azure infrastructure usage] for details of the Service Shape of the Storage account.

If you want to enable Disaster Recovery on an existing instance of {AAPonAzureNameShort}, contact Red Hat customer support.

The Disaster Recovery feature creates a nightly backup of your managed application and stores it in a paired region that is geographically distant to your primary region.
For information about regional pairings, refer to link:https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies[Azure cross-region replication pairings for all geographies] in the Azure reliability documentation.

For information about recovering your application after a service-impacting event, see the link:https://access.redhat.com/articles/7010302[Disaster Recovery for Ansible Automation Platform on Azure] article on the Red Hat customer portal.

