:_mod-docs-content-type: CONCEPT

[id="con-azure-disaster-recovery_{context}"]

= Disaster recovery

[role="_abstract"]
When you deploy {AAPonAzureNameShort}, you must enable or disable disaster recovery in the `Business Continuity` tab of the form.
There is no default setting for disaster recovery.

The disaster recovery feature incurs additional {Azure} infrastructure costs.
See link:{BaseURL}/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_on_microsoft_azure_guide/index#con-azure-infrastructure-usage_azure-intro[{AAPonAzureNameShort} infrastructure usage] for details of the Service Shape of the Storage account.

If you want to enable disaster recovery on an existing instance of {AAPonAzureNameShort}, contact Red Hat customer support.

The disaster recovery feature creates a nightly backup of your managed application and stores it in a paired region that is geographically distant to your primary region.
For information about regional pairings, refer to link:https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies[Azure cross-region replication pairings for all geographies] in the {Azure} reliability documentation.

For information about recovering your application after a service-impacting event, see the link:https://access.redhat.com/articles/7010302[Disaster recovery for {AAPonAzureNameShort}] article on the Red Hat customer portal.

