:_mod-docs-content-type: <CONCEPT> 
[id="con-saas-customer-access"]
= Customer access

You can access the control plane through the {PlatformNameShort} user interfaces and APIs.

When you initially configure an {SaaSonAWSShort} deployment, you receive the URL for your deployment. 
You can also find this information through the Red{nbsp}Hat Hybrid Cloud Console (HCC).

The administrator account's initial password is provided to the HCC user who performed the initial deployment.

[IMPORTANT]
====
You must change this password immediately after your first login to {PlatformNameShort}.
====
If you need help accessing your deployment, submit a support request through the link:https://access.redhat.com/support[Red Hat Customer Portal].

[NOTE]
=====
You can provide a custom URL for your {SaaSonAWSShort} by using a domain name that you own. Refer to the link:https://docs.redhat.com/en/documentation/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_service_on_aws/saas-service-definition#con-saas-custom-domain.adoc[Custom Domain] section for configuration information.
=====
//[Jameria Self] Added a link to the Custom Domain section to the note. To be confirmed after publishing.