[id="con-aws-update-restore-data-file"]

= Updating the restore data file

You must populate the data file before triggering the restore. 
The following variables are parameters listed in the data file.

* `cloud_credentials_path` is the path to your AWS credentials file.
* `deployment_name` is the name of the foundation deployment. This is the same name you used when you deployed the foundation.
* `aws_backup_iam_role_arn` is the _Amazon Resource Name_ (ARN) of the AWS IAM Role that has permissions to perform backup operations.
+
[NOTE]
====
If provided, the playbook defaults to this value over the value of the IAM role referenced in the backup file on S3. For further information, see xref:con-aws-backup-process[Backing up the {PlatformNameShort} deployment]
====
+
* `aws_backup_restore_point_arn` is the optional ARN of the of the EFS recovery point you want to use for restore.
+
[NOTE]
====
If provided, the playbook defaults to this value over the EFS restore point referenced in the backup file on S3. 
See xref:ref-aws-permissions[AWS permissions].
You must also ensure that the provided restore point is from a version of Ansible on Clouds (AoC) that matches the version of the ansible-on-clouds-ops container image running the restore. 
For example, a restore point taken from a deployment on AoC version 2.3.20230221-00 needs to use the `ansible-on-clouds-ops` container image version `2.3.20230221`.
====
+
* `aws_backup_vault_name` is the name of the backup vault that holds the EFS recovery points.
+
[NOTE]
====
If provided, the playbook defaults to this value over the backup vault referenced in the backup file on S3 which was generated when running the backup operation. See xref:ref-aws-permissions[AWS permissions].
You must also ensure that this backup vault matches the one used to backup the deployment.
====
+
* `aws_rds_db_snapshot_arn` is the optional ARN of the RDS snapshot you want to use for restore.
+
[NOTE]
====
If provided, the playbook defaults to this value over the RDS snapshot referenced in the backup file on S3. 
You must also ensure that the provided RDS snapshot is from a version of Ansible on Clouds that matches the version of the `ansible-on-clouds-ops` container image running the restore. 
For example, an RDS snapshot taken from a deployment on AoC version 2.3.20230221-00 needs to use the `ansible-on-clouds-ops` container image version `2.3.20230221`.
====
+
* `aws_region` is the region where the foundation deployment is deployed.
* `aws_restored_stack_name` is the desired name of the restored deployment.
* `aws_s3_bucket` is the name of the S3 bucket where the backup files are stored.
This must be the same bucket used for backup.
+
When you have populated the data file, it should resemble the following. 
The values in this file are provided as examples. 
+
[literal, options="nowrap" subs="+attributes"]
----
aws_restore_stack:
  cloud_credentials_path: ~/.aws/credentials
  deployment_name: AnsibleAutomationPlatform
  extra_vars:
    aws_region: us-east-1
    aws_restored_stack_name:AnsibleAutomationPlatform-restore
    aws_s3_bucket: ansible-automation-platform-bucket
----

