[id="azure_aks-cidr_{context}"]

= AKS CIDR Blocks

You can configure the AKS network CIDR blocks.
Traffic that originates from the AKS cluster will appear to come from the range configured in AKS, not from the VNET.

When you are planning your AKS CIDR block configuration, bear the following in mind:

* Ensure that these network ranges do not overlap with any existing network range in your enterprise network.

* Do not use the following reserved network ranges:
+
[cols="a"]
|===
|AKS Reserved CIDR Blocks

|169.254.0.0/16
|172.30.0.0/16
|172.31.0.0/16
|192.0.2.0/24
|172.17.0.1/26
|===

You can configure the AKS network CIDR blocks in the `Configure AKS networks` area of the `networking` tab.
Do not accept the default values suggested in the Azure user interface.
Instead, use the CIDR blocks that you have planned.
The settings have the following requirements:

[cols="25%,75%"]
|===
|Network |Requirements

|Service CIDR | Requires a /26 block at minimum. A larger block is not necessary.
|DNS Service IP | Must be an IP address in the Service CIDR other than the first IP in that range.
|Pod CIDR | Requires a /20 or larger block.

|===

