[id="con-aap-gcp-network-peering-options"]

= Network peering options

Many networking configurations are possible, but the following configurations have been validated to work with {PlatformNameShort} on GCP by Red Hat.

Private deployments omit access from the public internet. 
This is the default deployment model based on the GCP architecture used by {PlatformNameShort} on GCP.

If you use this approach you must configure VPC peering, a transit network gateway, or similar GCP networking connectivity to access {PlatformNameShort} on GCP.  

When VPC peering and routing are configured, you can access {PlatformNameShort} through a VM on a connected VPC subnet, or directly if your organization has a transit routing setup between GCP and your local networks.

{PlatformNameShort} requires peering and routing for outbound communication to perform automations against devices on your AWS networks and connected on-prem or multi-cloud networks.

[NOTE]
====
While every effort has been made to align with {GCP}’s documentation for this content, there may be a drift in accuracy over time. 
Use {GCP} documentation as the source of information regarding networking topics for GCP.
====

AWS offers different ways to peer private networks together. 
This document focuses on basic network peering and routing models:

[cols="10%,40%",options="header"]
|====
| Peering type | Description
| VPC Peering | VPCs are individually connected to one another with no other routing hops between them. 
This is a simple peering model and is useful when connecting a few networks. 
Complex peering can be configured, but routing can become more complex over time.
| Transit Gateway | A transit gateway is a network transit hub that you can use to interconnect your virtual private clouds (VPCs) and on-premises networks. 
As your cloud infrastructure expands globally, inter-Region peering connects transit gateways together using the GCP Global Infrastructure. 
Your data is automatically encrypted and never travels over the public internet.
|====

[NOTE]
====
There are also ways that AWS directs organizations not to attempt to peer networks in their Invalid network peering document.
====