[id="con-gcp-backup-process"]

= The Backup Process

A backup enables you to backup your environment by saving the database and the shared file system.
A new environment is created during the restore using the saved shared file system.
When the new environment is in place, the process restores the database.

The backup and restore process must use the same version.
If your backup was done with an earlier version, you must use the restore process of that version.
Then, if required, you can run an upgrade.

You must also make a backup before an upgrade.
For further information, see xref:assembly-gcp-upgrade[Upgrading your deployment]

The backup process involves taking a backup of the Cloud SQL database and filestore instances at a given point in time.
The backup playbook requires an active {AAPonGCP} foundation deployment to be running.

A bucket needs to be created in your project as restore information will be stored in that bucket.

Only one backup per version is kept in the bucket, if multiple versions of the backup need to be retain then a new bucket must be created for the new version of the backup.

The following procedures describe how to backup the {AAPonGCP} deployment.

:context: backup
include::proc-gcp-backup-container-image.adoc[leveloffset=+1]
include::proc-gcp-setup-environment.adoc[leveloffset=+1]
include::proc-gcp-create-data-file.adoc[leveloffset=+1]
include::ref-gcp-populate-backup-file.adoc[leveloffset=+1]
include::proc-gcp-run-backup-playbook.adoc[leveloffset=+1]
