:_mod-docs-content-type: CONCEPT

[id="con-saas-how-private-link-works"]

= How {AWSPrivateLink} works

[role="_abstract"]
{AWSPrivateLink} connectivity is supported both into (ingress) and out of (egress) the {PlatformNameShort} control plane.

For more AWS specific information about how {AWSPrivateLink} works, see the link:https://docs.aws.amazon.com/vpc/latest/privatelink/what-is-privatelink.html[Amazon Virtual Private Cloud] documentation.

== AWS PrivateLink connectivity into the {PlatformNameShort} control plane

For {AWSPrivateLink} connectivity into the control plane, an AWS Endpoint Service has automatically provisioned {AWSPrivateLink} connectivity into the control plane in your AWS environment.
You must create an AWS Endpoint to connect to this service in your Virtual Private Cloud (VPC), and enable private DNS resolution of the endpoint service hostname.
With this in place, any traffic originating from your VPC to the control plane API or mesh ingress connects to a private IP address and does not traverse the public internet.
Traffic is stateful, so there is no need to open a private link in the reverse direction for responses to Transmission Control Protocol (TCP) requests that originate from the customer VPC

== {AWSPrivateLink} connectivity out of the {PlatformNameShort} control plane

You can configure {PlatformNameShort} to use external resources such as source code repositories, container registries, and execution nodes. By default, the control plane connects to these resources over the public internet. However, if your resources are not publicly available, you can leverage {AWSPrivateLink} to securely access your private resources without traversing the public internet.

{AWSPrivateLink} connectivity allows the {PlatformNameShort} control plane to connect privately to your resources including, registries, repositories, and execution nodes. Traffic is stateful, eliminating the need to open a private link in the reverse direction for responses to Transmission Control Protocol (TCP) requests that originate from the control plane VPC.

To enable {AWSPrivateLink} connectivity from the control plane to your private resources, create one or more Endpoint Services in your VPC. Then reach out to Red Hat support to create the consuming Endpoints.

[IMPORTANT]
====
When creating the Endpoint Service in your VPC, you must enable the *Private DNS* option. This ensures that the {PlatformNameShort} control plane can resolve and connect to your service using the specified domain over {AWSPrivateLink}.
Private DNS enables DNS queries from {PlatformNameShort} resolve to the private IP addresses of the interface endpoint, facilitating secure and direct communication over PrivateLink.
====

[NOTE]
====
This document does not cover all steps required for PrivateLink connectivity. To complete PrivateLink connectivity, you must work with Red Hat through the Customer Support portal.
====
