[id="con-aap-gcp-service-account"]

= Your service account

You must have a service account to set up {PlatformNameShort} on GCP.  
This account both bootstraps the application and remains associated with the {PlatformNameShort} virtual machines. 
You can use an existing service account with the required roles, or you can permit the {PlatformNameShort} deployment to create one with the required roles on your behalf. 
If you use an existing account, it must have the following roles:

* Editor
* Logs Writer
* Cloud SQL Client
* Cloud SQL Instance User
* Secret Manager Secret Accessor
* Compute Network Admin

See xref:<add one here>[Grant a single role] for steps to add the required roles to your existing service account.

Some of the listed roles are only required to bootstrap the application. 
When installation and configuration are complete, some permissions can be removed from the service account, which remains configured on the {PlatformNameShort} Virtual Machines. 
See XXX (post-deployment next steps, to be written) for the list of permissions.
