[id="proc-aws-deploy-existing-vpc"]

= Deploying an application with an existing VPC

[NOTE]
====
The following procedure assumes that you have a marketplace offer. 
The instructions are a continuation from xref:proc-aws-marketplace[{Market}].
Complete the procedure in that section before continuing with this section.
====

The following procedure uses an existing VPC network to deploy an application.

.Procedure
. For Step 1, at the *Create stack* page, click btn:[Next].
. For Step 2, at the *Specify stack details* page
.. In the *Stack name* field, enter a unique stack name.
.. In the *EC2 KeyPair* field, select your previously created EC2 keypair.
.. In the *Select VPC* field, select *Existing*.
.. Ignore all the parameters for *New network configuration*.
.. In the *For Existing network configuration* field, fill the following fields
** *Which VPC ID should this be deployed to?*: The VpcId of your existing Virtual Private Cloud (VPC). Example: vpc-01234567890abcdef
** *Existing VPC CIDR Range*: The CIDR Range of your existing Virtual Private Cloud (VPC). Example: 192.168.0.0/16
** *Existing Private Subnet 1 ID*: The ID of your first existing private subnet. Example: subnet-077dd9969c32371f7
** *Existing Private Subnet 2 ID*: The ID of your second existing private subnet. Example: subnet-077dd9969c32371f7
+
Note that copying and pasting these from the AWS console introduces hidden characters, and can cause the entries to fail.
+
. Click btn:[Next] to move to Step 3.
. For Step 3, at the *Configure stack options* page, no changes are necessary.
.. All configurations are optional or have the correct default values.
. Click btn:[Next] to move to Step 4.
. For Step 4, at the *Review* page, scroll to the bottom. 
.. In the *Capabilities* section, check to acknowledge that CloudFormation may create IAM resources.
. Click btn:[Submit].
. The application begins provisioning.
.. It can take some time for the infrastructure and application to fully provision.
