[id="proc-aws-marketplace"]

= {Market}

.Public Offer
{AAPonAWS} can be obtained directly from the {Market}.
Follow these steps to purchase and deploy the public offer.

.Procedure

. In the AWS Console, navigate to the *{Market}*.
. Click btn:[Discover Products].
. Search for {PlatformNameShort}.
. Click the listing for *{AAPonAWS}*.
Ensure that you have selected the offer where Red Hat is the publisher.
. Click btn:[Continue to Subscribe].
. Click btn:[Continue to Configuration].
Select the appropriate fulfillment options.
Note that some selectors may have only one option.
. Click btn:[Continue to Launch].

.Private Offer
If you have worked with Red Hat Sales to enable a private offer of {AAPonAWS}, follow these steps to accept your offer and deploy the solution.

.Procedure
. Visit your Private Offer with the URL link provided by your Red Hat Sales representative.
. Click btn:[Accept Terms] to subscribe to the AMI Private Offer named {AAPonAWS}.
. After accepting the offer terms, click btn:[Continue to Configuration].

[NOTE]
====
If you are accepting terms for the {PlatformNameShort} foundation offer, then accept the discount rate for three virtual machines.  All {PlatformNameShort} foundation deployments use three VMs.  

If you are accepting terms for {PlatformNameShort} extension nodes, then assign the number of virtual machines arranged with your Red Hat Sales representative.  The number of VMs will directly correlate to the number of licensed managed active nodes that you have purchased.

After subscribing, the offer is also listed in your {Market} Subscriptions. 
====
