[id="proc-gcp-generate-upgrade-data-file"]

= Generating the data file

The commands in this section create a directory and populate it with an empty data template that, when populated, is used during the upgrade.

.Procedure

. Run the following commands to generate the required data file.
+
[literal, options="nowrap" subs="+attributes"]
----
# Create a folder to hold the configuration files
$ mkdir command_generator_data
----
. Populate the `command_generator_data` folder with the configuration file template.
+
[NOTE]
====
On Linux, any file or directory created by the command generator will be owned by `root:root` by default. To change the ownership of the files and directories, you can run the `sudo chmod` command after the files are created. Check the xref:con-tech-note-linux-files-owned-by-root[technical notes] for more information.
====
+
[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE \
command_generator_vars gcp_upgrade \
--output-data-file /data/extra_vars.yml
----

. After running these commands, a `command_generator_data/extra_vars.yml` template file is created.
This template file resembles the following:
+
[literal, options="nowrap" subs="+attributes"]
----
gcp_upgrade:
  ansible_config_path:
  cloud_credentials_path:
  deployment_name:
  extra_vars:
    gcp_backup_taken:
    gcp_compute_region:
    gcp_compute_zone:
----
