[id="proc-aap-aws-application-upgrade"]

You can upgrade your existing {AAPonAWS} deployment to the newer version. The upgrade process covers upgrading of Automation Hub and Automation Controller. The upgrade process takes roughly the same amount of time as a {AAPonAWS} deployment install. Follow the steps below to ensure a smooth upgrade process.

[NOTE]
=====
{AAPonAWS} supports sequential upgrades. All upgrades should be no more than one minor version behind what you are currently upgrading to. For example, in order to upgrade to {AAPonAWS} to 2.2.20230215, you must be on the first version of {AAPonAWS}.
=====

== Requirements

This upgrade process requires the following:
- Linux or macOS system (where the Upgrader will be run)
- Docker

== Preparing the environment

The upgrade process requires a few volumes to be mounted, so prepare a fresh directory to be used for this process.
+
First, create the directories that will be used to configure the upgrade process.
+
[source,bash]
----
# Secrets directory. Store the AWS credentials and config files.
$ mkdir secrets

# Extra vars directory. All the configuration variables for the upgrade process.
$ mkdir extra_vars
----
+
Create the `secrets/config` file and add the following content to it. Remember to replace the `us-east-1` with your respective region.
+
[source,ini]
----
[default]
region = us-east-1
output = json
----
+
Create the `secrets/credentials` file and add the following content to it. Remember to replace the `aws_access_key_id` and `aws_secret_access_key` with your respective credentials.
+
[source,ini]
----
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
----
+
Create the `extra_vars/extra_vars.yml` file and add the following content to it. See the next session for more details on the variables.
+
[source,yaml]
----
# Main vars
aws_foundation_stack_name: "myDeployment"
aws_region: us-east-1
ansible_aws_ssm_bucket_name: "my-s3-bucket-us-east-1"

# Backup vars
aws_backup_vault_name: Default
aws_backup_iam_role_arn: arn:aws:iam::<YOUR_ACCOUNT_NUMBER>:role/service-role/AWSBackupDefaultServiceRole

# Extension node vars
aws_offer_type: 100
aws_launch_template_name: "myDeployment-lt"
aws_autoscaling_group_name: "myDeployment-asg"
aws_asg_min_size: 2
aws_asg_desired_capacity: 2
----
+
The final result should look like this:
+
[source,bash]
----
$ tree
.
├── extra_vars/
│   └── extra_vars.yml
└── secrets/
    ├── config
    └── credentials
----

== Upgrade Process

The following instructions describe how to run the upgrade playbook.

.Setting up the `extra_vars/extra_vars.yaml` configuration file
. Main variables.
.. *aws_foundation_stack_name*: The name of the foundation deployment. This is the same name you used when you deployed the foundation.
.. *aws_region*: The region where the foundation deployment is located.
.. *ansible_aws_ssm_bucket_name*: The name of the S3 bucket where the configuration files for the AWS SSM are stored.
. The AWS Backup. The upgrade process will create a backup of your existing deployment before the main process starts. It requires the following variables:
.. *aws_backup_vault_name*: The name of the AWS Backup vault to use. The vault must exist in the same region as the deployment.
.. *aws_backup_iam_role_arn*: The ARN of the IAM role to use for the backup. The role must have the `AWSBackupServiceRolePolicyForBackup` policy attached to it. If you want to use the default AWS Backup service role, use the following ARN: `arn:aws:iam::<YOUR_ACCOUNT_NUMBER>:role/service-role/AWSBackupDefaultServiceRole`.
. The extension node variables. (only if you have extension nodes in your deployment)
.. *aws_offer_type*: The offer type of the extension nodes. Must be 100, 200, or 400.
.. *aws_launch_template_name*: The name of the AWS EC2 launch template to create.
.. *aws_autoscaling_group_name*: The name of the AWS AutoScaling Group to create for the extension nodes.
.. *aws_asg_min_size*: The AutoScaling Group minimum capacity. (Max is set by offer_type)
.. *aws_asg_desired_capacity*: The AutoScaling Group desired capacity.
+
. Pull the Docker image for Ansible on Clouds operational container having tag with the version which you want to upgrade to.
+
[NOTE]
=====
The Ansible on Clouds operational image tag must match with the version which you want to upgrade to. For example, if your foundation deployment version is 2.2.0, pull operational image with tag 2.2.20230215 to upgrade to version 2.2.20230215.
=====
+
[source,bash]
----
$ export IMAGE=<image-path>
$ docker pull $IMAGE
----
+
. Running the upgrade playbook as a container.
+
Replace `<deployment-name>` with your foundation deployment name.
+
.. Use the following command to run the playbook.
+
[source,bash]
----
# Export the volume paths
export VOLUME_AWS_CREDENTIALS_DIR=<absolute path to workdir>/secrets
export VOLUME_EXTRA_VARS_DIR=<absolute path to workdir>/extra_vars

$	docker run --rm \
    --env PLATFORM=AWS \
    --env DEPLOYMENT_NAME=<deployment-name> \
    --env GENERATE_INVENTORY=true \
    -v ${VOLUME_AWS_CREDENTIALS_DIR} \
    -v ${VOLUME_EXTRA_VARS_DIR} \
    ${IMAGE} \
      -i /aap-aoc-collections/playbooks/inventory.aws_ec2.yaml \
      redhat.ansible_on_clouds.aws_upgrade \
      -e @/extra_vars/extra_vars.yml
----
+
. After successfully running the playbook, the playbook will return something like this
+
[source,bash]
----
TASK [redhat.ansible_on_clouds.standalone_aws_upgrade : [upgrade] Show aws current version] ***
ok: [localhost] => {
    "msg": "AAP on aws upgrade succeeded to version: 2.2.20230215-00"
}
----
+
Your {AAPonAWS} deployment now should be upgraded to newer version and you should now be able to successfully log in to {PlatformName} {ControllerName} and {HubName} using your deployment credentials.
