[id="proc-gcp-deleting-backups-playbook"]

= Delete backups

There are two possible ways to delete backups:

* Use the `gcp_backup_delete` playbook which deletes a single backup.
* Use the `gcp_backups_delete` playbook which deletes multiple backups at once.

`gcp_backups_delete` takes a array of strings ["backup1","backup2",...], while `gcp_backup_delete` takes only one string, that being the name of a specific backup, "backup1".

The use of `gcp_backups_delete` is described in this section.

.Procedure
. Populate the `command_generator_data` directory with the configuration file template.
+
[literal, options="nowrap" subs="+attributes"]
----
docker run --rm -v $(pwd)/command_generator_data/:/data $IMAGE command_generator_vars gcp_backups_delete --output-data-file /data/backups_delete.yml
----
. After running the command, a `$(pwd)/command_generator_data/backups_delete.yml` template file is created.
This template file resembles the following:
+
[literal, options="nowrap" subs="+attributes"]
----
gcp_backups_delete:
  cloud_credentials_path:
  extra_vars:
    backup_names:
    delete:
    gcp_bucket_backup_name:
----

Parameter *backup_names* MUST specify an array of strings.  For example: ["backup1","backup2"].
Parameter *delete* MUST specify *true* to verify the deletion should occur.  Otherwise the delete will be a dry run
and no actual deletion will occur.  

. To run the delete backups, run the command generator to generate the backups_delete command.
+
[literal, options="nowrap" subs="+attributes"]
----
docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE command_generator gcp_backups_delete --data-file /data/backups_delete.yml
----
+
Resulting in the following ouput:
+
[literal, options="nowrap" subs="+attributes"]
----
-----------------------------------------------
Command to run playbook:

docker run --rm --env PLATFORM=GCP -v </path/to/gcp/service-account.json>:/home/runner/.gcp/credentials:ro \
--env ANSIBLE_CONFIG=../gcp-ansible.cfg  $IMAGE redhat.ansible_on_clouds.gcp_backups_delete \
-e 'gcp_service_account_credentials_json_path=/home/runner/.gcp/credentials  gcp_bucket_backup_name=<bucket> \
backup_names=<backup_names> delete=True'
----
. Run the supplied backup command to trigger the backup.
. When the playbook has finished running, the output resembles the following:
+
[literal, options="nowrap" subs="+attributes"]
----
TASK [redhat.ansible_on_clouds.standalone_gcp_backup_delete : [delete_backup] Dry-run message] ***
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=23   changed=2    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
----
