[id="proc-aap-aws-backup-and-recovery"]

To backup and restore your AAP deployment, it is vital to ensure automatic backups have been set for EFS and that these backups are accessible for restoration. 
When you create an  {PlatformNameShort} deployment, automatic Amazon Elastic File System (EFS) backups are set by default, however it is prudent to check if those backups can be restored before a disaster scenario. 
In addition, it is also extremely important that regular manual snapshots of the Amazon Relational Database Service (RDS) are taken to ensure a deployment can be restored as close as possible to its previous working state. 
Follow the steps below to ensure a smooth backup and recovery process.

== Backup Process

.Procedure
. Gather the following input variables to create an `extra_vars.yaml` file
.. aws_foundation_stack_name: The name of your existing deployment.
.. aws_region: The region the stack was deployed in.
.. aws_backup_vault_name: AWS backup vault name.
.. aws_backup_iam_role_arn: AWS IAM Role that has permissions to perform backup operations.

. Pull the docker image for operational container having the tag with the same version as the foundation deployment
+
[source,bash]
----
$ export IMAGE=<image-path still needs to be determined>
$ docker pull $IMAGE
----
+

[NOTE]
=====  
Operational image tag should match with the version of your foundation deployment. For example, if your foundation deployment version is 2.2.20230215, pull the operational image with tag 2.2.20230215.
=====
. Run the backup playbook as a container

.. Replace `<absolute path of extra vars dir>` with the path to your directory where your `extra_vars.yaml` file exists which you have created in step 1 of the backup process and replace `<Your AWS Access Key ID>` and `<Your AWS Secret Access Key>` with the values for the AWS account you want to run the backup with. For more information on finding your AWS account credentials see link:https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-about[Accessing AWS using your AWS credentials].

.. Run the command to run the playbook.
+
[source,bash]
----
$ docker run --rm --env PLATFORM=AWS \
-v <absolute path of extra vars dir>:/extra_vars:ro \
-e AWS_ACCESS_KEY_ID=<Your AWS Access Key ID>
-e AWS_SECRET_ACCESS_KEY=<Your AWS Secret Access Key>
<image path still needs to be determined>:latest \
redhat.ansible_on_clouds.aws_backup_stack \
-e @/extra_vars/extra_vars.yaml
----

.. Note the output of the playbook.
+
The playbook will return something like this
+
[source, bash]
----
{
    "efs_restore_points": [
        {
            "CreationDate": "2023-02-28T21:54:07.515000+00:00",
            "RecoveryPointArn": "arn:aws:backup:us-east-1:080914983077:recovery-point:967be465-a43e-432a-b536-8b16e6b0452d"
        },
        {
            "CreationDate": "2023-02-28T16:08:08.905000+00:00",
            "RecoveryPointArn": "arn:aws:backup:us-east-1:080914983077:recovery-point:d2058e3a-dca6-4a18-b175-5ef624f513a7"
        }
    ],
    "rds_db_snapshot_arn": "arn:aws:rds:us-east-1:080914983077:snapshot:test-bnr-ops-container-rds169785b9-orm2iuzlfqem-snap-2023-02-28"
}
----
+
Make a note of the *rds_db_snapshot_arn* and the latest *RecoveryPointArn*. These will be needed for the restore playbook.
+


== Recovery Process

.Procedure
. Gather the following input variables to create an `extra_vars.yaml` file
.. aws_foundation_stack_name: The name of your existing deployment.
.. aws_restored_stack_name: The name of your new deployment.
.. aws_region: The region the stack was deployed in.
.. aws_backup_vault_name: The name of the backup vault your EFS backup is stored in.
.. aws_rds_db_snapshot_arn: The ARN of the RDS snapshot you want to use for restore, which can be found from the backup playbook output as *rds_db_snapshot_arn*. 
+
[NOTE]
====
If you have a specific RDS snapshot you want to use, you will have to manually find its ARN in the AWS console.
==== 
.. aws_backup_restore_point_arn: The ARN of the recovery point you want to use for restore, which can be found from the backup playbook output as *RecoveryPointArn*.
+ 
[NOTE]
==== 
If you have automatic backups set up and you have a specific EFS recovery point you want to use, you will have to manually find its ARN in the AWS console.
====
.. aws_backup_iam_role_arn: AWS IAM Role that has permissions to perform backup operations.
.. aws_s3_bucket: AWS S3 bucket name. Used to upload cloudformation template.
.. aws_efs_physical_id: The physical Id of the EFS from the original deployment. Looks something like `fs-06837574544929090`.  
.. aws_cf_keypair_name: The keypair to pass as a parameter when creating the deployment.
+
[NOTE]
====
The keypair used must exist in the aws region you are restoring to.
====

. Pull the docker image for operational container having the tag with the same version as the foundation deployment
+
[source,bash]
----
$ export IMAGE=<image-path still needs to be determined>
$ docker pull $IMAGE
----
+

[NOTE]
=====  
Operational image tag should match with the version of your foundation deployment. For example, if your foundation deployment version is 2.2.20230215, pull the operational image with tag 2.2.20230215.
=====
. Run the restore playbook as a container

.. Replace `<absolute path of extra vars dir>` with the path to your directory where your `extra_vars.yaml` file exists which you have created in step 1 of the backup process and replace `<Your AWS Access Key ID>` and `<Your AWS Secret Access Key>` with the values for the AWS account you want to run the backup with. For more information on finding your AWS account credentials see link:https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-about[Accessing AWS using your AWS credentials].

.. Use the following command to run the playbook.
+
[source,bash]
----
$ docker run --rm --env PLATFORM=AWS \
-v <absolute path of extra vars dir>:/extra_vars:ro \
-e AWS_ACCESS_KEY_ID=<Your AWS Access Key ID>
-e AWS_SECRET_ACCESS_KEY=<Your AWS Secret Access Key>
<image path still needs to be determined>:latest \
redhat.ansible_on_clouds.aws_restore_stack \
-e @/extra_vars/extra_vars.yaml
----

After successfully running the playbook, you should see a new restored deployment in AWS CloudFormation.
+
[NOTE]
====
Access to the restored deployment needs to be configured through either an external load balancer or VPN. When a connection method is configured you can log in to {PlatformName} {ControllerName} and {HubName} using your old deployment credentials. 
In addition, all job history, uploaded collections and other records should be in the same state as the restored deployment.
====