[id="proc-saas-custom-dom-with-awsprivatelink"]

= Setting up a custom domain with {AWSPrivateLink}

If you are planning to either connect to the {PlatformNameShort} UI or use {AutomationMesh} through {AWSPrivateLink}, complete the following steps to configure your DNS.

.Procedure 

. Retrieve the main DNS name of the Amazon Virtual Private Cloud (VPC) endpoint you created to connect to our {AWSPrivateLink} Endpoint Service. 
+

There will be a few entries, make sure that you grab the one that is not {AWSPrivateLink}-dependent (for example, `vpce-xxxx-xxxx.vpce-svc-xxxx.us-east-1.vpce.amazonaws.com`).

. After you have the main DNS name, create CNAME records for your custom domain and point the following hostnames to the retrieved DNS name:
.. platform (for example, `platform.aap._example_.com`) → `vpce-xxxx-xxxx.vpce-svc-xxxx.us-east-1.vpce.amazonaws.com`
.. mesh-ingress-0 platform (for example, `platform.aap._example_.com`) → `vpce-xxxx-xxxx.vpce-svc-xxxx.us-east-1.vpce.amazonaws.com`
.. mesh-ingress-1 (for example, `mesh-ingress-1.aap._example_.com``) → `vpce-xxxx-xxxx.vpce-svc-xxxx.us-east-1.vpce.amazonaws.com`


