[id="proc-aws-deleting-backups-playbook"]

= Deleting backups

There are two playbooks to manage your backups:

* `aws_backup_delete` that delete one backup.
* `aws_backups_delete` that enables you to delete multiple backups. 

'aws_backups_delete takes a array of strings ["backup1","backup2",...], while `aws_backup_delete` takes only one string, that being the name of a specific backup, "backup1"

The use of `aws_backups_delete` is desscribed in this section.

.Procedure

. Populate the `command_generator_data` directory with the configuration file template.
+
[options="nowrap" subs="+attributes"]
----
docker run --rm -v $(pwd)/command_generator_data/:/data $IMAGE command_generator_vars aws_backups_delete --output-data-file /data/backups.yml
----
+
Produces the following output:
+
[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: aws_backups_delete
Description: This playbook delete a specified backup.
-----------------------------------------------
This playbook delete a specified backup

-----------------------------------------------
Command generator template: 

docker run --rm -v <local_data_file_directory>:/data $IMAGE command_generator aws_backups_delete --data-file /data/backups.yml
----
. After running the command, a `/tmp/backups.yml` template file is created. 
This template file resembles the following: 
+
[literal, options="nowrap" subs="+attributes"]
----
aws_backups_delete:
  cloud_credentials_path:
  extra_vars:
    aws_backup_names:
    aws_region:
    aws_s3_bucket:
    delete:
----

With `aws_backup_names` such as "backup1" and "backup2".

. To run the deletion of the backups, run the command generator to generate the deletion backup command.
+
[literal, options="nowrap" subs="+attributes"]
----
docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE command_generator aws_backups_delete --data-file /data/backups.yml
----
+
Resulting in the following ouput:
+
[literal, options="nowrap" subs="+attributes"]
----
Command to run playbook: 

docker run --rm --env PLATFORM=AWS -v ~/.aws/credentials:/home/runner/.aws/credentials:ro \
--env ANSIBLE_CONFIG=../aws-ansible.cfg  $IMAGE redhat.ansible_on_clouds.aws_backups_delete \
-e 'aws_region=<region> aws_s3_bucket=<bucket> aws_backup_names=["mybackup"] delete=True'
===============================================
----
. Run the supplied backup command to trigger the backup deletion.
+
. When the playbook has finished running, the output resembles the following:
+
[literal, options="nowrap" subs="+attributes"]
----
TASK [redhat.ansible_on_clouds.standalone_aws_backup_delete : [delete_backup] Dry-run message] ***
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=21   changed=2    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0    
----
