[id="proc-aws-from-stack-prepare-environment"]

= Preparing the environment

.Procedure
. Ensure the `AWS_CREDS_ABS_PATH` environment variable is defined pointing to your AWS Credentials file.
+
[literal, options="nowrap" subs="+attributes"]
----
export AWS_CREDS_ABS_PATH=/Users/<USER>/.aws/credentials
----
. Create an `extra_vars/vars.yml` file, and ensure the that it contains the following values and that they are customized to match your environment.

* `aws_foundation_stack_name` =  "my-foundation-stack"
* `aws_restored_stack_name` = "my-foundation-stack-restored"
* `aws_region` = us-east-1
* `aws_backup_vault_name` = "Default"
* `aws_rds_db_snapshot_arn` = "arn:aws:rds:us-east-1:123456789012:snapshot:my-foundation-stack-rds169785b9-55rtrqwtj4e6-snap-2023-03-07"
* `aws_backup_restore_point_arn` =  "arn:aws:backup:us-east-1:123456789012:recovery-point:878a542c-0f59-42d7-ad4d-f46848c21757"
* `aws_backup_iam_role_arn` = "arn:aws:iam::123456789012:role/service-role/AWSBackupDefaultServiceRole"
* `aws_s3_bucket` = "my-example-bucket"
* `aws_efs_physical_id` = "fs-05a4f9a1049c00977"
* `aws_cf_keypair_name` = "my-key-pair"
+
where:
+
* `aws_foundation_stack_name` is the name of your existing deployment.
* `aws_restored_stack_name` is the name you want for your new restored deployment.
* `aws_region` is the region the existing stack was deployed in and the region the new restored stack will also be deployed in.
* `aws_backup_vault_name` is the name of the backup vault your EFS backup is stored in.
* `aws_rds_db_snapshot_arn` is the ARN of the RDS snapshot you want to use for restore, which can be found from the backup playbook output as `rds_db_snapshot_arn`.
+
[NOTE]
====
If you have a specific RDS snapshot you want to use, you must manually find its ARN in the AWS console. 
You must also ensure the RDS snapshot is from an Ansible on Clouds deployment with a version matching the version of the `ansible-on-clouds-ops` container you are using to run the restore operation.
====
+
* `aws_backup_restore_point_arn` is the ARN of the recovery point you want to use for restore, which can be found from the backup playbook output as RecoveryPointArn.
+
[NOTE]
====
If you have automatic backups set up and you have a specific EFS recovery point you want to use, you must manually find its ARN in the AWS console. 
You must also ensure the EFS recovery point is a from an Ansible on Clouds deployment with a version matching the version of the ansible-on-clouds-ops container you are using to run the restore operation.
====
+
* `aws_backup_iam_role_arn` is the AWS IAM Role that has permissions to perform backup operations.
+
[NOTE]
====
You can use the AWS Backup Default Service Role for this which has the format `arn:aws:iam::<Your AWS Account Number>:role/service-role/AWSBackupDefaultServiceRole`.
====
+
* `aws_s3_bucket` is the name of an S3 bucket that the playbook can access to upload a CloudFormation Template. 
The  name must not contain upper case letters.
* `aws_efs_physical_id` is the physical Id of the EFS from the original deployment. 
For example, `fs-06837574544929090`.
* `aws_cf_keypair_name` is the keypair to pass as a parameter when creating the new restored deployment.
+
[NOTE]
====
The keypair used must exist in the AWS region you are restoring to.
====