[id="proc-aap-aws-modify-alb-cidr-range"]

= Modify Load Balancers CIDR Range

== Default Load Balancers CIDR Range Configuration on Ansible Automation Platform
The default CIDR range on Load Balancers are set to 0.0.0.0/0, allowing everyone to access the Load Balancers. If you are looking to update these CIDR ranges, you can choose to update them either before or after the deployment. You can follow the steps below to get this done.

=== Procedure - update before the deployment
. In the AWS Console, navigate to *CloudFormation* and click on your Red Hat Ansible Automation Platform deployment.
. Click the *Template* tab and then click the btn:[View in Designer] button.
. In the top left corner, hover over the file symbol to reveal a dropdown and save your template to a local file.
. In your saved template update "controlleralbsecuritygroupEFD044E7" and "hubalbsecuritygroup4C1C53F8" CIDR range to your desired CIDR range
.. Update the Ingress CidrIp ingress of the Controller Load Balancer security group component to your desired CIDR range (searching for "controlleralbsecuritygroupEFD044E7" in quotes should point you to the component)
.. Update the Ingress CidrIp ingress of the Hub Load Balancer security group component to your desired CIDR range (searching for "hubalbsecuritygroup4C1C53F8" in quotes should point you to the component)
. Create a new Red Hat AAP on AWS CloudFormation stack using the modified Load Balancers CIDR range template
.. In the AWS Console, navigate to *CloudFormation* and click on btn:[Create Stack] located near the top right of the screen
.. Select *With new resources (standard)* in the dropdown
.. In the *Specify template* section under *Template source* select btn:[Upload a template file] and select the template you have modified. Click btn:[Next] to go to the next step 
.. Enter a stack name and select an AWSKeyPair to use for the deployment. Click btn:[Next] to go to the *Configure stack options* page
.. Optionally configure stack options and click btn:[Next] to review the stack
.. Press btn:[Submit] to create your new deployment with updated Load Balancers CIDR range

=== Procedure - update after the deployment
. In the AWS Console, under LOAD BALANCING, click *Load Balancers*
. Update Controller load balancer CIDR range
.. Select the Controller load balancer
.. On the Description tab, under Security, click security group *aap/controller/alb-security-group* link
.. Select security group with *aap/controller/alb-security-group* description
.. On Inbound rules tab, click btn:[Edit inbound rules]
.. Update Source CIDR range from "0.0.0.0/0" to to your desired CIDR range
.. Click btn:[Save rules]
. Update Hub load balancer CIDR range
.. Select the Hub load balancer
.. On the Description tab, under Security, click security group *aap/hub/alb-security-group* link
.. Select security group with *aap/hub/alb-security-group* description
.. On Inbound rules tab, click btn:[Edit inbound rules]
.. Update Source CIDR range from "0.0.0.0/0" to to your desired CIDR range
.. Click btn:[Save rules]
