[id="proc-aap-gcp-backup-and-restore"]

To backup and restore your {PlatformNameShort} deployment, it is vital to have your existing {PlatformNameShort} admin secret name and value recorded somewhere safe. In addition, it is also extremely important that regular manual backups of the Cloud SQL database instance and filestore backups are taken to ensure a deployment can be restored as close as possible to its previous working state. The playbooks backup and restore provides backup and restore support for the {AAPonGCP} foundation deployment. 

*Note that the restore process deploys a new {PlatformNameShort} deployment with the filestore and SQL database instance being restored to the specified backup.*

== Backup Process

The backup process involves taking a backup of the Cloud SQL database and filestore instances at a given point in time.
The backup playbook require an active {AAPonGCP} foundation deployment to be running.

The following instructions describe how to run the backup playbook.

.Procedure
. Gather the following input variables to create an `extra_vars.yaml` file.
.. *gcp_service_account_credentials_json_path*: Service account crendential json file path for the google cloud account.
.. *gcp_deployment_name*: Deployment name which you want to backup.
.. *gcp_compute_region*: GCP region where foundation deployment deployed.
.. *gcp_compute_zone*: GCP zone where foundation deployment deployed.
+
[source,bash]
----
gcp_deployment_name: "" 
gcp_compute_region: ""
gcp_compute_zone: ""
gcp_service_account_credentials_json_path: "/secret/<service-account-creds-json-filename>"
----
+
. Pull the docker image for operational container having tag with the version of the foundation deployment.
+
[NOTE]
=====  
The operational image tag must match the version of your foundation deployment. For example, if your foundation deployment version is 2.2.20230215, pull the operational image with tag 2.2.20230215.
=====
+
[source,bash]
----
$ export IMAGE=<image-path>
$ docker pull $IMAGE
----
+
. Running the backup playbook as a container.
+
.. Replace `<absolute path to google application credentials dir>` with your path to the service account credential Json file for google cloud and `<absolute path of extra vars dir>` with the path to your directory where you `extra_vars.yaml` file exists which you have created in step 1 of backup process. 
+
.. Use the following command to run the playbook.
+
[source,bash]
----
$ docker run --rm \
-v <absolute path to google application credentials dir>:/secrets \
-v <absolute path of extra vars dir>:/extra_vars:ro \
quay.io/leena_ibm/ljawale-ansible-on-clouds-ops:latest \
redhat.ansible_on_clouds.gcp_backup_deployment \
-e @/extra_vars/extra_vars.yaml
----
+
. Note the output of the playbook.
+
The playbook will return something like this
+
[source, bash]
----
TASK [redhat.ansible_on_clouds.standalone_gcp_backup : [backup_deployment] Print vars required for restore process] ***
ok: [localhost] => {
    "msg": [
        "AAP on GCP Backup successful. Please note below vars which are required for restore process.",
        "{ gcp_sql_backup_id: 1677552759614 , gcp_sql_backup_db_name: test-bnr-aap-db ,gcp_filestore_backup_name: test-bnr-filestore-iygs }"
    ]
}
----
+
Make a note of the SQL database backup ID, SQL batabase backup name and the filestore backup name. These will be needed for the restore playbook.
+



== Restore Process

The restore process deploys a new deployment, and restores the filestore and SQL database instance to the specified backup.

[NOTE]
=====
The restored filestore instance uses CIDR network range `192.168.244.0/29`, which is different from the default network filestore network range of the backup deployment.
=====

The following instructions describe how to run the restore playbook.

.Procedure
. Gather the following input variables to create an `extra_vars.yaml` file.
.. *gcp_service_account_credentials_json_path*: Service account crendential json file path for google cloud account.
.. *gcp_deployment_name*: Deployment name which you backed up.
.. *gcp_restored_deployment_name*: Deployment name of restored AAP foundation created by playbook
.. *gcp_compute_region*: GCP region where foundation deployment deployed.
.. *gcp_compute_zone*: GCP zone where foundation deployment deployed.
.. *gcp_filestore_backup_name*: The backup name where filestore instance backup will be stored (You will get this after executing backup playbook).
.. *gcp_sql_backup_id*: Backup ID of the Cloud SQL database instance to use when restoring the deployment (You will get this after executing backup playbook).
.. *gcp_sql_backup_db_name*: GCP foundation SQL database name (You will get this after executing backup playbook).
+
[source,bash]
----
gcp_deployment_name: ""
gcp_restored_deployment_name: ""
gcp_compute_region: ""
gcp_compute_zone: ""
gcp_service_account_credentials_json_path: "/secret/<service-account-creds-json-filename>"
gcp_filestore_backup_name: ""
gcp_sql_backup_id: ""
gcp_sql_backup_db_name: ""
----
+
. Pull the docker image for the operational container having tag with the version of the foundation deployment.
+
[NOTE]
=====
The operational image tag should match with the version of your foundation deployment. For example, if your foundation deployment version is 2.2.20230215, pull the operational image with tag 2.2.20230215
=====
+
[source,bash]
----
$ export IMAGE=<image-path>
$ docker pull $IMAGE
----
+
. Running the restore playbook as a container.
+
.. Replace `<absolute path to google application credentials dir>` with your path to the service account credential Json file for google cloud and `<absolute path of extra vars dir>` with the path to your directory where you `extra_vars.yaml` file exists which you have created in step 1 of restore process. 
+
.. Use the following command to run the playbook.
+
[source,bash]
----
$ docker run --rm \
-v <absolute path to google application credentials dir>:/secrets \
-v <absolute path of extra vars dir>:/extra_vars:ro \
quay.io/leena_ibm/ljawale-ansible-on-clouds-ops:latest \
redhat.ansible_on_clouds.gcp_restore_deployment \
-e @/extra_vars/extra_vars.yaml
----
+
. After successfully running the playbook, you should see a new restored deployment in GCP deployment. It can take 5-10 minutes for the deployment to finish and for all the containers to run.
+
[NOTE]
=====
Access to the restored deployment needs to be configured through either an external load balancer or VPN. When a connection method is configured you can log in to {PlatformName} {ControllerName} and {HubName} using your old deployment credentials. In addition, all job history, uploaded collections and other records should be in the same state as the restored deployment.
=====