[id="proc-saas-set-up-private"]

= Subscribing to a {SaaSonAWS} private offer
A private offer has pricing and licensing terms specifically offered to your account.
The offer has a set expiration date, if you do not accept the private offer by the expiration date, you are either automatically moved to the product's public offer or no longer subscribed to the product.

.Procedure
. A Red{nbsp}Hat seller issues you a purchase order and provides it to you by email.
** For manual steps see link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-private-offers.html#buyer-private-offers-subscribing[Viewing and subscribing to a private offer] page on the AWS Marketplace
. Click the link in the email to accept the terms.
. Click btn:[Create contract].
. Click btn:[Click here to set up your account]. This redirects you to {RHSSO} where you need to:
.. Create or sign into your Red{nbsp}Hat account.
.. Link your AWS account to the Red{nbsp}Hat account.
. This then redirects you to the *Provision environment* page on the Red{nbsp}Hat Hybrid Cloud Console. Here you can start configuring your environment. 
. Enter your AWS account ID.
+
This account ID must be the account ID that purchased the offer from the AWS marketplace. The system will not recognize associated or nested accounts.
. Once your AWS ID is validated click btn:[Next].
. Select your desired region.
. Click btn:[Provision].

This redirects you to the *Instances* page which displays all the details of the instance you created. From here you can confirm if your instance is *Assigned* or still in a *Pending* state.
 
