[id="proc-gcp-marketplace"]

= {GCPMarket}

.Public Offer
{PlatformName} from {GCPMarket} can be obtained directly from the {GCPMarket}.
Follow these steps to purchase and deploy the public offer.

.Procedure

. In the Google Cloud Console, navigate to the *Marketplace*.
. Click btn:[Discover Products].
. Search for {PlatformNameShort}.
. Click the listing for *{PlatformName} from {GCPMarket}*.
Ensure that you have selected the offer where Red Hat is the publisher.
//. Click btn:[Continue to Subscribe].
//. Click btn:[Continue to Configuration].
Select the appropriate fulfillment options.
Note that some selectors may have only one option.
. Click btn:[Continue to Launch].

.Private Offer
If you have worked with Red Hat Sales to enable a private offer of {PlatformName} from {GCPMarket}, follow these steps to accept your offer and deploy the solution.

.Procedure
. Visit your Private Offer with the URL link provided by your Red Hat Sales representative.
. Click btn:[Accept Terms] to subscribe to the AMI Private Offer named {PlatformNameShort} from {GCPMarket}.
. After accepting the offer terms, click btn:[Continue to Configuration].
[Note]
====
After subscribing, the offer is also listed in your {GCPMarket} Subscriptions. 
====