[id="proc-aap-aws-extension-nodes"]

[IMPORTANT]
====
This is a Techical Preview feature. Technology Preview features are not supported with Red Hat production service-level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.
====

The {PlatformNameShort} platform upgrade process is an automated process that upgrades the {PlatformNameShort} platform to the next one.

By default, the foundation stack is deployed with two {ControllerName} nodes and one {HubName} node. You can add execution nodes to scale out {AAPonAWS}.

The upgrade process is performed by running the `upgrade` automation using the `ansible-on-clouds-ops` container image.

It's recommended to create a backup of the {PlatformNameShort} deployment before upgrading it.

Follow these steps to add execution nodes into your {AAPonAWS} environment.

.Prerequisites
* Linux or macOS system (where the `ansible-on-clouds-ops` container image will run)
* Docker

.Procedure
. Decide the offer type for the extension nodes.
. Create the prepare the environment and the configuration files.
. Run the `ansible-on-clouds-ops` container to create the extension nodes.
. Run the `ansible-on-clouds-ops` container to remove the extension nodes.

== Deciding the offer type

The following table lists the offer types and the corresponding AWS instance types. Depending on the workload needs, you can choose a more suitable offer type for the extension nodes.


.Offer types:

[options="header",width="60%",cols="^s,<"]
|=============================
|Offer Type |AWS Instance Type
|100        |m5.large
|200        |m5.xlarge
|400        |m5.2xlarge
|=============================

== Preparing the environment

The upgrade process requires a few volumes to be mounted, so *prepare a fresh directory* to be used for this process.

First, create the directories that will be used to configure the upgrade process.

[source,bash]
----
# Secrets directory. Store the AWS credentials and config files.
$ mkdir secrets
# Extra vars directory. All the configuration variables for the upgrade process.
$ mkdir extra_vars
----

Create the `secrets/config` file and add the following content to it. Remember to replace the `us-east-1` with your respective region.

[source,ini]
----
[default]
region = us-east-1
output = json
----

Create the `secrets/credentials` file and add the following content to it. Remember to replace the `aws_access_key_id` and `aws_secret_access_key` with your respective credentials.

[NOTE]
=====
To create the AWS credentials, see https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-methods[Configuring the AWS CLI].
=====

[source,ini]
----
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
----

Create the `extra_vars/extra_vars.yml` file and add the following content to it.

[NOTE]
=====
See the next session for more details on the variables.
=====

[source,yaml]
----
# Main vars
aws_foundation_stack_name: "myDeployment"
aws_region: us-east-1

# Extension node vars
aws_offer_type: "100"
aws_launch_template_name: "myDeployment-lt"
aws_autoscaling_group_name: "myDeployment-asg"
aws_asg_min_size: 2
aws_asg_desired_capacity: 2
----


Variables description:

.Setting up the `extra_vars/extra_vars.yaml` configuration file
* Main variables
** *aws_foundation_stack_name*: The name of the foundation deployment. This is the same name you used when you deployed the foundation.
** *aws_region*: The region where the foundation deployment is located.
* The extension node variables.
** *aws_offer_type*: The offer type of the extension nodes. Must be *100*, *200*, or *400*.
** *aws_launch_template_name*: The name of the AWS EC2 launch template to create.
** *aws_autoscaling_group_name*: The name of the AWS AutoScaling Group to create for the extension nodes.
** *aws_asg_min_size*: The AutoScaling Group minimum capacity. (Max is set by offer_type)
** *aws_asg_desired_capacity*: The AutoScaling Group desired capacity.

The final result should look like this:

[source,bash]
----
$ tree
.
├── extra_vars/
│   └── extra_vars.yml
└── secrets/
    ├── config
    └── credentials
----

== Creating the extension nodes

The following instructions describe how to run the playbook to create the extension nodes.

Pull the Docker image for `ansible-on-clouds-ops` container image having tag with the version you're currently using.

[NOTE]
=====
The `ansible-on-clouds-ops` container image tag must match the current installed version of {AAPonAWS}
=====

[source,bash]
----
$ export IMAGE=<image-path>
$ docker pull $IMAGE
----

Running the upgrade playbook as a container. Replace `<deployment-name>` with your foundation deployment name. Use the following command to run the playbook.

[source,bash]
----
# Export the volume paths
$ export VOLUME_AWS_CREDENTIALS_DIR=<absolute path to workdir>/secrets
$ export VOLUME_EXTRA_VARS_DIR=<absolute path to workdir>/extra_vars

# Run the playbook
$ docker run --rm \
    --env PLATFORM=AWS \
    --env DEPLOYMENT_NAME=<deployment-name> \
    -v ${VOLUME_AWS_CREDENTIALS_DIR}:/home/runner/.aws/:rw \
    -v ${VOLUME_EXTRA_VARS_DIR}:/extra_vars:ro \
    ${IMAGE} \
      redhat.ansible_on_clouds.aws_add_extension_nodes \
      -e @/extra_vars/extra_vars.yml
----
