[id="proc-aap-gcp-deploy-with-existing-vpc"]

= Deploying an application with an existing VPC

The following procedure uses an existing VPC network to deploy an application.

.Procedure
. In the *Deployment* page, select the *Service Usage API* link below the *Confirm Service Usage API is enabled* checkbox.
. In the *API/Service Details* tab, ensure that the API is enabled, then return to the *Deployment* page.
. Check the *Confirm Service Usage API* is enabled checkbox.
. Select or create a *Service Account*.
For further information, see xref:???[Your service account].
. In the *Region* field, select the region where you want the application deployed.
. In the *Zone* field, select the zone where you want the Filestore deployed. 
The zone must be in the Region you selected.
. In the *Observability* section, you can enable logging and metrics to be sent to Cloud Logging and Cloud Monitoring. See link:https://cloud.google.com/stackdriver/pricing[Operations Suite Pricing] for the financial cost of enabling these services. See xref:???[Monitoring and logging] for more information on configuring this feature.
. In the *Network Selection* section, select *Existing network*. 
. In the *Existing Network* section, provide your existing VPC network name, existing subnet name and existing proxy subnet name. 
Select *cloud NAT router* to create a *NAT router* in your VPC network. 
. The *Networking section* provides defaults for all of the network ranges used in the deployment. 
Provide these values based on your existing network configuration. 
If you want to modify these values, see xref:???[Networking Options] 
. Click btn:[DEPLOY].
. The *Deployment Manager* displays the running deployment.
. The application begins provisioning. 
It can take some time for the infrastructure and application to fully provision.
+
[NOTE]
====
You will see a warning on the deployment.
----
This deployment has resources from the Runtime Configurator service, which is in Beta.
----
This warning is expected and is not a cause for concern.
====