[id="proc-saas-custom-dom-with-awsprivatelink"]

= Setting up a custom domain without {AWSPrivateLink}

If you are planning to either connect to the AAP UI or use Automation Mesh through AWS PrivateLink, follow the steps below in order to configure your DNS.

[NOTE]
====
You must create two support tickets for bi-directional connectivity: one support case for enabling {AWSPrivateLink} connectivity into the control plane and another one for enabling {AWSPrivateLink} connectivity out of the control plane. 
====

.Procedure 

. Retrieve the main DNS name of the VPC Endpoint you created to connect to our PrivateLink Endpoint Service. 
+
[NOTE]
====
There will be a few entries, make sure that you grab the one that is not {AWSPrivateLink}-dependent (for example, `vpce-xxxx-xxxx.vpce-svc-xxxx.us-east-1.vpce.amazonaws.com`
====
. After you retrieve the main DNS name, create the DNS CNAME records for your custom domain using the following hostnames pointing to the DNS names identified in the previous step:
.. platform (for example, platform.aap.yourdomain.com) → `vpce-xxxx-xxxx.vpce-svc-xxxx.us-east-1.vpce.amazonaws.com`
.. mesh-ingress-0 platform (for example, platform.aap.example.com) → `vpce-xxxx-xxxx.vpce-svc-xxxx.us-east-1.vpce.amazonaws.com`
.. mesh-ingress-1 (for example, mesh-ingress-1.aap.example.com)  → `vpce-xxxx-xxxx.vpce-svc-xxxx.us-east-1.vpce.amazonaws.com`


