[id="proc-aws-vpc-peering"]

= VPC peering

VPC Peering offers the ability to directly connect different networks within your AWS infrastructure. 
When two or more networks are peered, the peering only establishes the connection between the networks. 
You must also update routing tables to direct the networks to send traffic over the appropriate networking peer.

.Prerequisites
Before using VPC peering to connect any VPC, you must ensure that there is no network address space overlap between the networks that you intend to route traffic between your VPCs and {PlatformNameShort} from GCP Marketplace’s VPC address space. 
Google should prevent peering if this is attempted.

The following procedure lets you configure VPC peering with {PlatformNameShort}.

.Procedure
. In the GCP Portal, navigate to menu:VPC[].
. In the *VPC menu*, click btn:[VPC Network Peering].
. Click btn:[Create peering connection].
. In the *Name* field, enter the name of the peering connection as you need.
. In the *Your VPC Network* field, select the first VPC that you plan to peer. 
. In the *Peered VPC Network* field, select the second VPC to peer. 
This can be the {PlatformNameShort} from {GCPMarket} VPC.
.. Subnet routes between these two networks are created by default.
Therefore, access to {PlatformNameShort} can occur from VMs that reside on the peered VPC.
However, if you have more complex routing, such as a hub-and-spoke network model, then other route must be created.
.. Select *Exchange custom routes* and *Exchange subnet routes with public IP* carefully. 
Google provides explanations what each fields does. 
Your selection impact how traffic flows through your VPCs. 
Under the proper conditions, these checkboxes configure routing between the newly peered networks and other networks through the route table exchange enabling network traffic to traverse multiple networks (transit routing).
. Click btn:[Create].

For additional information on routing tables, firewalls and other networking components, see [here]
