:_mod-docs-content-type: PROCEDURE

[id="prod-create-credentials-cmd-generator"]

= Create credentials for the Command Generator

[role="_abstract"]
You must have an AWS credentials file for all day-2 operations, such as adding and removing Extension Nodes.

The file must follow the format of the AWS credentials file for "Long-term credentials", which includes the `aws_access_key_id` and `aws_secret_access_key` variables. For further information, read link:https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html[AWS Command Line Interface User Guide] in the AWS documentation.

[NOTE]
====
You must use the `default` profile name in the credentials file. The Command generator does not recognize any other name. For more information, read the xref:con-tech-note-cmd-generator-aws-credentials[Command generator - AWS Credentials File] technical note.
====

An example of the credentials file format is:

[literal, options="nowrap" subs="+attributes"]
----
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
----

After the credentials file is created, you can use it in the command generator by passing the file path to the `-c` option, for example:

* `/home/user/project/extra_vars.yaml`

[literal, options="nowrap" subs="+attributes"]
----
[default]
aws_remove_extension_nodes:
  cloud_credentials_path: ./my_credentials
  deployment_name:
  extra_vars:
    aws_autoscaling_group_name:
    aws_launch_template_name:
    aws_offer_type:
    aws_region:
    aws_ssm_bucket_name:
----

* `/home/user/project/my_credentials`

[literal, options="nowrap" subs="+attributes"]
----
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
----

Command:

[literal, options="nowrap" subs="+attributes"]
----
docker run --rm \
        -v /home/user/project:/data:ro \
        $IMAGE \
        command_generator \
        --data-file /data/extra_vars.yml
----
