[id="proc-aws-application-deploy"]

= Application deployment

Now that you have subscribed to an offer, you can begin configuration before launching the CloudFormation Stack.

.Procedure

. In the *Fulfillment option* field, select *{PlatformNameShort} CloudFormation*.
. In the *Software version* field, confirm the latest version available in the list is selected.
. In the *Region* field, select the region with your EC2 key pair. 
The CloudFormation Stack deploys in the same region. 
. Click btn:[Continue to Launch].
. On the following screen, click btn:[Launch]. 
This launches the AWS CloudFormation Console in a new browser tab.
. For Step 1, *Specify template*, click btn:[Next].
. For Step 2, *Specify stack details* 
.. In the *Stack name* field, enter a unique stack name.
.. For *awsKeyPair* select your previously created EC2 keypair.  
. Click btn:[Next] to move to Step 3.
. For Step 3, *Configure stack options*.  
No changes are necessary. 
All configurations are optional or have the correct default values.
. Click btn:[Next] to move to Step 4, *Review*.
. For Step 4, *Review*.
Scroll to the bottom. 
In the *Capabilities section*, check to acknowledge that CloudFormation may create IAM resources.  
. Click btn:[Create stack].

The application begins provisioning.  
It can take some time for the infrastructure and application to fully provision.

To retrieve the admin password:

. Select the main menu from the top left.
. Select *Security*. If you do not see *Security*, then select *View All Products*.
. Select *Secret Manager*.
. Filter with the name of the deployment as the secret name format is <DeploymentName>-aap-admin
. Click on the secret name of the deployment
. Click on the 3 vertical dots on the line of the deployment.
. Select *View secret value*, the admin password will be displayed.
