[id="proc-saas-set-up-private"]

= Private offer
A private offer includes specific pricing and licensing terms for your account and has an expiration date. If you do not accept the offer by that date, you will either be moved to the public offer for the product or no longer subscribed to it.

.Prerequisites
* An AWS Account

.Procedure
. A Red{nbsp}Hat seller issues you a purchase order and provides it to you by email.
** For manual steps see link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-private-offers.html#buyer-private-offers-subscribing[Viewing and subscribing to a private offer] page on the AWS Marketplace
. Click the link in the email to accept the terms.
. Log in to your AWS account.
. Navigate to the AWS Marketplace.
. Go to the *Private Offers* page. 
+
[NOTE]
====
If you have already accepted your offer you can find it in the *Manage subscriptions* page.
====
+
. Click the URL under the *Offer ID* column. This redirects you to the *Offer Selection* page. 
. Click btn:[Create contract].
. Click btn:[Click Set up your account]. This redirects you to {RHSSO} where you must:
.. Create or sign into your Red{nbsp}Hat account.
.. Connect your AWS account to the Red{nbsp}Hat account.
... If this is your first time connecting your accounts you must accept the terms and conditions and click btn:[Connect accounts].
. This then redirects you to the *Provision environment* page on the Red{nbsp}Hat Hybrid Cloud Console. Here you can start configuring your environment. 
. Enter your AWS account ID and click btn:[Verify].
+
This account ID must be the account ID that purchased the offer from the AWS marketplace. The system does not recognize associated or nested accounts.
. After your AWS ID is validated click btn:[Next].
. Select your desired region and click btn:[Next].
. Click btn:[Provision].

This redirects you to the *Environment details* page of the *Instances*, where you can see all the details of your created instance.
Here you can check whether your instance is *Ready* or still in a *Provision in progress* state.
 
