[id="proc-aws-update-data-file"]

= Update the data file

You must populate the data file before triggering the operation. 
The variables listed in the data file are defined below.

* `cloud_credentials_path` is the path to your AWS credentials file.
For example, `~/.aws/credentials`
* `deployment_name` is the name of the foundation deployment. 
This is the same name you used when you deployed the foundation.
* `aws_asg_desired_capacity` is the AutoScaling Group desired capacity.
* `aws_asg_min_size` is the AutoScaling group minimum capacity. The maximum is set by `aws_offer_type`.
* `aws_autoscaling_group_name` is the name of the AWS AutoScaling Group to create for the extension nodes.
* `aws_launch_template_name` is the name of the AWS EC2 launch template to create.
* `aws_offer_type` is the offer type of the extension nodes. This must be `100`, `200`, or `400`.
* `aws_region` is the region where the foundation deployment is located.

After populating the data file, it resembles the following:

The values are provided as examples.

[literal, options="nowrap" subs="+attributes"]
----
aws_add_extension_nodes:
  cloud_credentials_path: ~/.aws/credentials
  deployment_name: AnsibleAutomationPlatform
  extra_vars:
    aws_asg_desired_capacity: "1"
    aws_asg_min_size: "1"
    aws_autoscaling_group_name: AnsibleAutomationPlatform-ext-asg1-100
    aws_launch_template_name: AnsibleAutomationPlatform-ext-lt1-100
    aws_offer_type: "100"
    aws_region: us-east-1
----