[id="proc-aap-aws-modify-cidr-ranges"]

= Modify Deployment CIDR Range

.Default CIDR Range Configuration on Ansible Automation Platform
If you would like to modify your CIDR range, you must modify your CIDR range before installation.

This CIDR block is further divided into 4 subnets (2 private and 2 public, which have the following CIDR ranges:

.Private
192.168.0.0/24
192.168.1.0/24

.Public
192.168.2.0/24
192.168.3.0/24

[IMPORTANT]
====
These CIDR ranges cannot be changed following deployment.
====
If you want to update your CIDR ranges, the current deployment must be deleted and the Red Hat {PlatformName} on AWS Cloud Formation template must be updated with your new CIDR ranges.

The following procedure describes how to do this:

.Procedure
. In the AWS Console, navigate to *CloudFormation* and click on your Red Hat Ansible Automation Platform deployment.
. Click the *Template* tab and then click the btn:[View in Designer] button.
. In the top left corner, hover over the file symbol to reveal a dropdown and save your template to a local file.
. In your saved template update the CIDR block of the network VPC component to your desired CIDR range
. Update the CIDR blocks of the 4 subnet components. (searching for *"AWS::EC2::Subnet"* with quotes should point you to the subnet components in the template) It is crucial to ensure the CIDR ranges provided for your subnets are within your VPC CIDR range and do not overlap with each other to avoid CIDR collisions. *Note.* You can look at the default subnet CIDR ranges as a point of reference. 
. Update the CidrIp ingress of the RDS security group component to match the VPC CIDR range (searching for *"aap/rds/security_group"* in quotes should point you to the component)
. Update the CidrIp ingress of the storage security group component to match the VPC CIDR range (searching for *"aap/storage/security-group"* in quotes should point you to the component).
. Create a new Red Hat AAP on AWS CloudFormation stack using the modified CIDR range template
.. In the AWS Console, navigate to *CloudFormation* and click on btn:[Create Stack] located near the top right of the screen
.. Select *With new resources (standard)* in the dropdown
.. In the *Specify template* section under *Template source* select btn:[Upload a template file] and select the template you have modified. Click btn:[Next] to go to the next step 
.. Enter a stack name and select an AWSKeyPair to use for the deployment. Click btn:[Next] to go to the *Configure stack options* page
.. Optionally configure stack options and click btn:[Next] to review the stack
.. Press btn[Submit] to create your new deployment with updated CIDR ranges.


