[id="proc-aws-marketplace"]

= {Market}

.Public Offer
{AAPonAWS} can be obtained directly from the {Market}.
Follow these steps to purchase and deploy the public offer.

.Procedure

. In the AWS Console, navigate to menu:AWS Marketplace Subscriptions[].
. Click btn:[Discover Products].

. Click the listing for *{PlatformName}2 - Up to 110 Managed Nodes*.
. Click btn:[Continue to Subscribe].
. Click btn:[Continue to Configuration].
Select the appropriate fulfillment options.
Note that some selectors may have only one option.
. In the *Fulfillment option* field, ensure *{PlatformNameShort} CloudFormations Topology* is selected.
. In the *Software version* field, select the latest available version from the list.
. In the *Region* field, select the region with your EC2 key pair. 
The CloudFormation stack deploys in the same region.
. Click btn:[Continue to Launch].
. In the *Choose Action* filed, select *Launch CloudFormation*.
. Click btn:[Launch].
. In the *Specify Templates* section, select *View in Designer*.
. Hover over the file symbol to reveal a dropdown.
. Click btn:[Save].
. Select *Local File* and supply a name.
. In your saved template locate the `controlleralbsecuritygroupEFD044E7` and `hubalbsecuritygroup4C1C53F8` CIDR ranges. 
In *SecurityGroupIngress* change the CidlrIP to your desired CIDR range.
. Create a new {AAPonAWS} CloudFormation stack using the modified CIDR range template for the load balancers.
.. In the AWS Console, navigate to menu:CloudFormation[].
.. Click btn:[Create Stack].
.. Select *With new resources (standard)* from the dropdown.
.. In the *Specify template* section under *Template source* click btn:[Upload a template file] and select the template you have modified.
..Click btn:[Next] to go to the next step.
.. Enter a stack name and select an EC2 KeyPair to use for the deployment.
.. For *Select VPC*, select *New* or *Existing*. For more information, see xref:con-gcp-application-deploy[Application deployment].
.. Click btn:[Next] to go to the *Configure stack options* page.
.. Optional: Configure stack options.
.. Click btn:[Next] to review the stack.
.. Click btn:[Submit] to create your new deployment with the updated CIDR range for the load balancers.

<<<<<<< HEAD



=======
>>>>>>> 5b660aa4 (More corrections to AWS procedures)
.Private Offer
If you have worked with Red Hat Sales to enable a private offer of {AAPonAWS}, follow these steps to accept your offer and deploy the solution.

.Procedure
. Visit your Private Offer with the URL link provided by your Red Hat Sales representative.
. Click btn:[Accept Terms] to subscribe to the AMI Private Offer named {AAPonAWS}.
. After accepting the offer terms, click btn:[Continue to Configuration].

[NOTE]
====
If you are accepting terms for the {PlatformNameShort} foundation offer, then accept the discount rate for three virtual machines.  All {PlatformNameShort} foundation deployments use three VMs.  

If you are accepting terms for {PlatformNameShort} extension nodes, then assign the number of virtual machines arranged with your Red Hat Sales representative.  The number of VMs will directly correlate to the number of licensed managed active nodes that you have purchased.

After subscribing, the offer is also listed in your {Market} Subscriptions. 
====
