[id="proc-gcp-listing-backups-playbook"]

= List backups
This playbook allows you to list the existing backups in a specific buckets

.Procedure
. Populate the `command_generator_data` directory with the configuration file template.
+
[source,bash]
----
docker run --rm -v $(pwd)/command_generator_data/:/data $IMAGE command_generator_vars gcp_backup_list --output-data-file /data/backups_list.yml
----
+
Produces the following output:
+
[literal, options="nowrap" subs="attributes"]
----
Playbook: gcp_backup_list
Description: This playbook list the backups in a given bucket.
-----------------------------------------------
This playbook list the backups in a given bucket.

-----------------------------------------------
Command generator template: 

docker run --rm -v <local_data_file_directory>:/data $IMAGE command_generator gcp_backup_list --data-file /data/backups_list.yml
----
. After running the command, a `/tmp/backups_list.yml` template file is created. 
This template file resembles the following: 
+
[literal, options="nowrap" subs="+quotes,attributes"]
----
gcp_backup_list:
  cloud_credentials_path:
  extra_vars:
    gcp_bucket_backup_name:
----

. To run the backup, run the command generator to generate the backup command.
+
[literal, options="nowrap" subs="+quotes,attributes"]
----
docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE command_generator gcp_backup_list --data-file /data/backups_list.yml
----
+
Resulting in the following ouput:
+
[literal, options="nowrap" subs="attributes"]
----
-----------------------------------------------
Command to run playbook: 

docker run --rm --env PLATFORM=GCP -v </path/to/gcp/service-account.json>:/home/runner/.gcp/credentials:ro \
--env ANSIBLE_CONFIG=../gcp-ansible.cfg  $IMAGE redhat.ansible_on_clouds.gcp_backups_delete \
-e 'gcp_service_account_credentials_json_path=/home/runner/.gcp/credentials  gcp_bucket_backup_name=<bucket> \
backup_names=<backup_names> delete=True'
----
. Run the supplied backup command to trigger the list of backups.
+
. When the playbook has finished running, the output resembles the following:
+
[literal, options="nowrap" subs="attributes"]
----
TASK [redhat.ansible_on_clouds.standalone_gcp_backup_list : [list_backup] Display list of backups] ***
ok: [localhost] => {
    "msg": [
        "aoc-backup-deployment1-20230614T203926",
        "aoc-backup-deployment1-20230616T114134",
        "aoc-backup-deployment1-20230616T134002",
        "aoc-backup-deployment2-20230613T124127"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
----
