[id="proc-aap-aws-modify-cidr-ranges"]

= Modifying the application CIDR range before deployment

If you access {PlatformNameShort} through VPC peering, this enables your private network to look into and communicate with other private networks.
Because these private networks can overlap, they have CIDR configurations which need to be validated before deployment so as to avoid IP conflicts in the network.

The default CIDR block for the VPC is divided into 4 subnets (2 private and 2 public), which have the following CIDR ranges:

.Private
192.168.0.0/24

192.168.1.0/24

.Public
192.168.2.0/24

192.168.3.0/24

If you want to modify your CIDR ranges before deployment, your current deployment must be deleted, then follow the instructions in xref:proc-aap-aws-deploy-new-vpc[Deploying an application with a new VPC].

[IMPORTANT]
====
These CIDR ranges cannot be changed following deployment.
====

To delete your current deployment, follow the directions in xref:assembly-aap-aws-uninstall[Uninstalling {AAPonAWS}]

To update the Red Hat {PlatformName} on AWS Cloud Formation template, use the following procedure

.Procedure
. In the AWS Console, navigate to menu:CloudFormation[]. 
. Select your {PlatformName} deployment.
. Click the *Template* tab and then click btn:[View in Designer].
. In the top left corner, hover over the file symbol to reveal a dropdown.
. Save your template to a local file.
. In your saved template update the CIDR block of the network VPC component to the desired CIDR range.
. Update the CIDR blocks of the 4 subnet components.
 (A search for *"AWS::EC2::Subnet"* with quotes points you to the subnet components in the template.) 
+
[IMPORTANT]
====
It is crucial to ensure the CIDR ranges provided for your subnets are within your VPC CIDR range and do not overlap with each other to avoid CIDR collisions.
 
You can look at the default subnet CIDR ranges as a point of reference.
====
. Update the CidrIp ingress of the RDS security group component to match the VPC CIDR range. 
(A search for *"aap/rds/security_group"* in quotes should point you to the component).
. Update the CidrIp ingress of the storage security group component to match the VPC CIDR range. 
(A search for *"aap/storage/security-group"* in quotes should point you to the component).
. Create a new Red Hat {PlatformNameShort} on the AWS CloudFormation stack using the modified CIDR range template.
.. In the AWS Console, navigate to menu:CloudFormation[].
.. Click btn:[Create Stack] located near the top right of the screen.
.. Select *With new resources (standard)* from the dropdown.
.. In the *Specify template* section under *Template source*, click btn:[Upload a template file] and select the template you have modified. 
.. Click btn:[Next]. 
.. Enter a stack name and select an `AWSKeyPair` to use for the deployment. 
.. Click btn:[Next] to go to the *Configure stack options* page.
.. Optionally configure stack options and click btn:[Next] to review the stack
.. Click btn:[Submit] to create your new deployment with updated CIDR ranges.

