[id="ref-aap-aws-additional-configs-update-admin-password"]

= Changing the default {PlatformNameShort} Administrator password

The default Administrator password for {PlatformNameShort} is generated randomly when {PlatformNameShort} from {Market} is deployed. 
Follow these steps to change the Administrator password for both {ControllerName} and {HubName}:

. Locate the correct secret for the CloudFormation Stack by opening the AWS Secrets Manager console and selecting the secret with the name _<stack_name>-aap-admin-secret_.
. Select *Retrieve secret value* to view the secret value.
. Select *Edit* and provide an updated password value.
. Click btn:[Save].
. Replace the running {PlatformNameShort} EC2 instances to use the new Administrator password.
.. Navigate to the AWS EC2 Instances console.
.. Identify and Terminate one {ControllerName} instance and one {HubName} instance for the CloudFormation Stack.
.. Wait for the {ControllerName} Auto Scale group and the {HubName} Auto Scaling group to create new EC2 instances.
. The new Administrator can be used when the new {ControllerName} and {HubName} EC2 instances reach a _Running_ instance state.
