[id="ref-aap-gcp-additional-configs-update-admin-password"]

= Changing the default {PlatformNameShort} administrator password

The default administrator password for {PlatformNameShort} is generated randomly when {AAPonGCP} is deployed. 
Follow these steps to change the administrator password for both {ControllerName} and {HubName}.

.Procedure
. Locate the correct secret for the {PlatformNameShort} deployment by opening the GCP Secrets Manager console and selecting the secret with the name _<deployment_name>-aap-admin_.
. Select *NEW VERSION* to add a new version.
. Enter a password secret value.
. Check *Disable all past versions*
. Click btn:[ADD NEW VERSION]
. Replace the running {PlatformNameShort} VM instances to use the new administrator password.
.. Navigate to the *GCP VM Instances* console.
.. Identify and delete one {ControllerName} VM instance and one {HubName} VM instance for the {PlatfromNameShort} deployment.
.. Wait for the {ControllerName} Auto Scale group and the {HubName} Auto Scaling group to create new VM instances.
. The new administrator can be used when the new {ControllerName} and {HubName} VM instances reach a _Running_ Instance State.