[id="ref-gcp-populate-restore-file"]

= Parameters of the restore.yml file

You can only restore into a new VPC network.

.For a new VPC

If you want to restore using a new VPC set the following parameters:

* `gcp_existing_vpc` must be set to `false`.

The following parameters must be removed:

* `gcp_filestore_ip_range`
* `gcp_cloud_sql_peering_network`
* `gcp_controller_internal_ip_address`
* `gcp_hub_internal_ip_address`

Provide values for the following parameters:

* `gcp_existing_vpc` must be set to `false`.
* `cloud_credentials_path` is the path for your Google Cloud service account credentials file.
* `gcp_deployment_name` is the name of the AAP deployment manager deployment you want to back up.
* `gcp_restored_deployment_name` is the name under which the deployment must be restored. A new deployment will be created with this name. A deployment must not already exist with this name.
* `gcp_bucket_backup_name` is the bucket name you used for the backup.
* `gcp_compute_region` is the region where the backup was taken.
This can be retrieved by checking the Deployments config in Deployment Manager.
* `gcp_compute_zone` is the zone where the backup was taken.
This can be retrieved by checking the Deployments config in Deployment Manager.