[id="ref-aws-update-upgrade-data-file_{context}"]

= Updating the data file

You must populate the data file before triggering the upgrade. Each parameter is required unless it is noted as optional. If the parameter is noted as optional, both its key and value can be removed from the data file.

The following variables are parameters listed in the data file:

* `ansible_config_path` (Optional) Only use if overriding with a custom `ansible_config`.
* `cloud_credentials_path` is the path to your AWS credentials file.
* `deployment_name` is the name of the foundation deployment. 
** This is the same name you used when you deployed the foundation.
* `aws_backup_taken` is the verification that a manual backup of the current deployment was recently created prior to running this upgrade.
* `aws_region` is the AWS region where the foundation deployment is located.
* `aws_ssm_bucket_name` is the name of the S3 bucket where temporary configuration files for the AWS SSM are stored. You can use an existing bucket or create a new one. 
The bucket name must not contain uppper case letters.
* `seller_name` (Optional) is used to designate the AWS Marketplace Seller. The default value is `redhatinc`. If you are based in EMEA and purchased this offering through the `redhatlimited` AWS Marketplace seller, ensure that this value is set to `redhatlimited`. 

After populating the data file, it should resemble the following. 

The following values are provided as examples:
[literal, options="nowrap" subs="+attributes"]
---- 
aws_upgrade:
  ansible_config_path:
  cloud_credentials_path: ~/.aws/credentials
  deployment_name: AnsibleAutomationPlatform
  extra_vars:
    aws_backup_taken: true
    aws_region: us-east-1
    aws_ssm_bucket_name: aap-ssm-bucket
    seller_name: redhatinc
----