:_mod-docs-content-type: REFERENCE

[id="ref-azure-nw-private-deploy_{context}"]

= Private deployments

[role="_abstract"]
If you choose private access during the deployment of {AAPonAzureNameShort}, the DNS record for the application points to a private address within the selected CIDR block.

To access this private address, you must configure network peering and establish connectivity.
The method for connecting to the {PlatformNameShort} depends on your organization's Azure infrastructure management practices.
Azure administrators must determine the most suitable model and configure the setup accordingly.

Common access options include:


* link:{BaseURL}/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_on_microsoft_azure_guide/index#proc-azure-nw-private-deploy-az-hosted-vm_azure-connecting-to-aap[Azure hosted virtual machine]
* link:{BaseURL}/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_on_microsoft_azure_guide/index#proc-azure-nw-private-deploy-vpn_azure-connecting-to-aap[VPN]


