[id="ref-aap-aws-additional-configs-update-rds-password"]

= Changing the default RDS database password

The default RDS database password for {PlatformNameShort} is generated randomly when {PlatformNameShort} on AWS is deployed. 
Follow these steps to change the RDS password:

. Locate the correct secret for the CloudFormation Stack by opening the AWS Secrets Manager console and selecting the secret with the name _<stack_name>-aap-rds-secret_.
. View the secret value by selecting *Retrieve secret value*.
. Select *Edit* and provide an updated password value, then select *Save*.
. Update the {HubName} EC2 instance with the new RDS password.
.. Navigate to the AWS EC2 Instances console
.. Identify and connect to the {HubName} instance for the CloudFormation Stack.
.. Install the `postgresql` package with `sudo dnf install postgresql`.
... View the database settings from the following file - `/etc/pulp/settings.py`.

. Replace the running {PlatformNameShort} EC2 instances to use the new Administrator password.
.. Navigate to the AWS EC2 Instances console.
.. Identify and Terminate one {ControllerName} instance and one {HubName} instance for the CloudFormation Stack.
.. Wait for the {ControllerName} Auto Scale group and the {HubName} Auto Scaling group to create new EC2 instances.
.. The new RDS can be used when the new {ControllerName} and {HubName} EC2 instances reach a _Running_ Instance State.
.. To validate the RDS password has been changed -
... Identify and connect to the {HubName} instance for the CloudFormation Stack.
... View the updated database settings from the following file - `/etc/pulp/settings.py`.
... Attempt to connect via the following sample connection string. Variable definitions can be found in the settings file - 
+
[source,bash]
----
psql postgresql://<DB_USER>:<DB_PASSWORD>@<DB_HOST>:<DB_PORT>/<DB_NAME>
----
