[id="ref-aap-aws-additional-configs-update-rds-password"]

= Changing the default RDS database password

The default RDS database password for {PlatformNameShort} is generated randomly when {PlatformNameShort} on AWS is deployed. 
Follow these steps to change the RDS password:

. Locate the correct secret for the CloudFormation Stack by opening the AWS Secrets Manager console and selecting the secret with the name _<stack_name>-aap-rds-secret_.
. View the secret value by selecting *Retrieve secret value*.
. Select *Edit* and provide an updated password value, then select *Save*.
. Update the {HubName} EC2 instance with the new RDS password.
.. Navigate to the AWS EC2 Instances console
.. Identify and connect to the {HubName} instance for the CloudFormation Stack.
.. Install the ` `postgresql` ` package with ` `sudo dnf install postgresql` `.
.. View and remember the ` `DATABASE.HOST` ` and ` `DATABASE.PASSWORD` ` attributes from the settings file  ` `/etc/pulp/settings.py` `.



..sudo dnf install postgresql

. Replace the running {PlatformNameShort} EC2 instances to use the new Administrator password.
.. Navigate to the AWS EC2 Instances console.
.. Identify and Terminate one {ControllerName} instance and one {HubName} instance for the CloudFormation Stack.
.. Wait for the {ControllerName} Auto Scale group and the {HubName} Auto Scaling group to create new EC2 instances.
.. The new Administrator can be used when the new {ControllerName} and {HubName} EC2 instances reach a _Running_ Instance State.


https://redhat.service-now.com/nav_to.do?uri=%2Fasmt_assessment_instance_list.do%3Fsysparm_userpref_module%3D63c153c59f23120030581471367fcf54%26sysparm_view%3DGRC_Attestation%26sysparm_query%3DuserDYNAMIC90d1921e5f510100a9ad2572f2b477fe%255EstateNOT%2BINcomplete%252Ccanceled%255Emetric_type.evaluation_method%253Dattestation_v2%255Esn_grc_itemISNOTEMPTY%255Esn_grc_parentISEMPTY%255EEQ%26%26sysparm_order%3Dsys_created_on%26sysparm_order_direction%3Ddesc%26sysparm_clear_stack%3Dtrue