[id="ref-aws-update-upgrade-data-file_{context}"]

= Updating the data file

You must populate the data file before triggering the upgrade. 
The following variables are parameters listed in the data file.

* `ansible_config_path` (Optional) Only use if overriding with a custom `ansible_config`.
* `cloud_credentials_path` is the path to your AWS credentials file.
* `deployment_name` is the name of the foundation deployment. 
This is the same name you used when you deployed the foundation.
* `aws_region` is the region where the foundation deployment is located.
* `aws_ssm_bucket_name` is the name of the S3 bucket where the configuration files for the AWS SSM are stored. You can use an existing bucket or create a new one. 
The bucket name must not contain uppper case letters.

After populating the data file, it should resemble the following. 

The following values are provided as examples:
[literal, options="nowrap" subs="+attributes"]
---- 
aws_upgrade:
  ansible_config_path:
  cloud_credentials_path: ~/.aws/credentials
  deployment_name: AnsibleAutomationPlatform
  extra_vars:
    aws_region: us-east-1
    aws_ssm_bucket_name: ansibleautomationplatform-bucket
----