[id="ref-aap-aws-install-prerequisites"]

= Prerequisites

Before you can install and register {PlatformNameShort}, you must be familiar with AWS including how services operate, how data is stored, and any privacy implications that may exist by using these services. 
You must also set up an account with {AWS} (AWS).

You must have a working knowledge of the following aspects of Amazon Web Services:

* Deploying solutions from the AWS Marketplace
* _Elastic Compute Cloud_ (EC2) instances
* _Elastic Block Store_ (EBS) volumes
* _Elastic File Storage_ (EFS)
* AWS _Virtual Private Clouds_ (VPCs)
** Subnets
** Route Tables
** Security Groups
** Load Balancers
* Network Design
* Hub-and-spoke networking designs
* VPC Peering
* _Class Inter-Domain Routing_ (CIDR) blocks
* Transit routing
* AWS Lambda
* AWS CloudWatch
* SSH

For more information about {AWS} and terminology, see the link:https://aws.amazon.com/[AWS product documentation].

Your AWS account must have _Identity and Access Management_ (IAM) permissions to create and manage AWS Marketplace deployments as well as the resources described in xref:con-aws-application-architecture[Application architecture]. 
The application can fail to deploy if your IAM policies restrict deployment and management of these resources.

[Note]
=====
{AutomationMeshStart} is not available on {PlatformNameShort} on {AWS} at this time and is currently planned for a later release.
=====
