[id="tech-note-aws-backup-restore"]

= Backup and Restore

. The `aws_rds_db_snapshot_arn` optional parameter which allowed customers to specify a specific AWS RDS Snapshot to use for restoring their deployment is no longer supported. The restore process no longer uses AWS RDS Snapshots to restore a deployment and instead relies on the backup files generated by the Ansible on Clouds Ops Container backup playbook. The Ansible on Clouds Ops Container restore playbook does not use any provided RDS snapshot passed as a parameter.

. A restored {AAPonAWS} deployment will not maintain all secrets from the original {AAPonAWS} deployment. If using your own certificates, they will need to be reset after a restore.

+
.Secrets that will be maintained:

* `<stack_name>-aap-admin-secret`
* `<stack_name>-aap-secret-key`
+

//

+
.Secrets that will NOT be maintained:

* `<stack_name>-aap-rds-secret`
* `<stack_name>-database_fields_symmetric_key`
* `<stack_name>-container_auth_private_key_pem`
* `<stack_name>-container_auth_public_key_pem`
* `<stack_name>-pulp_cert`
* `<stack_name>-pulp_key`
