:imagesdir: images
:numbered:
:toclevels: 4
:experimental:
:context: aap-self-service-using

include::attributes/attributes.adoc[]

// Book Title
= Using self-service automation portal

Thank you for your interest in {PlatformName}. {PlatformNameShort} is a commercial offering that helps teams manage complex multi-tier deployments by adding control, knowledge, and delegation to Ansible-powered environments.

This guide describes how to add templates to your {SelfService} instance,
and how to launch them to run automation jobs.
It also describes how to configure role-based access control (RBAC) so that you can restrict the teams and users who can run the jobs.

This document has been updated to include information for the latest release of {PlatformNameShort}.

include::{Boilerplate}[]

include::devtools/assembly-self-service-using-overview.adoc[leveloffset=+1]

include::devtools/assembly-self-service-login.adoc[leveloffset=+1]

include::devtools/assembly-self-service-working-templates.adoc[leveloffset=+1]

include::devtools/assembly-self-service-rbac.adoc[leveloffset=+1]

include::devtools/assembly-backstage-software-templates.adoc[leveloffset=+1]

//[gmurray] commenting out until ready for tect preview which is scheduled for Jan 25, 2026
//include::devtools/assembly-self-service-create-ee-definitions.adoc[leveloffset=+1]

include::devtools/assembly-self-service-feedback.adoc[leveloffset=+1]