ifdef::context[:parent-context: {context}]

[id='aap-command-generator']


= The Command Generator

The Command Generator is used to generate commands for launching operational playbooks provided by the Ansible-on-clouds operational playbook collection.

The process involves five steps:

. Pulling the ansible-on-clouds-ops container image.
. Listing the available playbooks.
. Using a command generator to generate a data file and the next command to run.
. Populating the data file and launching the previous generated command. 
This then generates the final command with all parameters.
+
[NOTE]
====
When this step is complete, you can save the generated command and run the playbook when it is required. 
====
+
. Running the final command.

`command_generator_vars` and the command_generator are implemented as part of a docker container and are launched using the docker command line interface..

The docker image is available at:

.Prerequisites
* Docker
ifdef:: AWS
* An AWS credentials file.
endif::[]
ifdef:: GCP
* A GCP credentials file.
endif::[]
* An internet connection to Google Cloud

include::proc-aap-pull-command-container-image.adoc[leveloffset=+1]
include::proc-aap-list-available-playbooks.adoc[leveloffset=+1]
include::proc-aap-generate-command-data-file.adoc[leveloffset=+1]
include::proc-aap-populate-command-data-file.adoc[leveloffset=+1]
include::proc-aap-run-generated-command.adoc[leveloffset=+1]



