- name: Synchronize Controller docs
  hosts: localhost
  vars:
    source_repo: git@github.com:ansible/product-docs.git
    source_branch: release_4.3.0
    source_dir: ../sync/product-docs/
    target_dir: ../sync/controller-docs/
  tasks:
   - name: clone source repository
     ansible.builtin.git:
       repo: "{{ source_repo }}"
       dest: "{{ source_dir }}"
       version: "{{ source_branch }}"
       key_file: ~/.ssh/id_rsa
   - name: wipe target directory
     ansible.builtin.file:
       path: "{{ target_dir }}*"
       state: absent
   - name: synchronize content
     ansible.posix.synchronize:
       src: "{{ source_dir }}"
       dest: "{{ target_dir }}"
       delete: yes
       recursive: yes
       rsync_opts:
         - "--exclude='Makefile'"
         - "--exclude='Dockerfile'"
         - "--exclude='VERSION'"
         - "--exclude='Jenkinsfile'"
         - "--exclude='*.sh'"
         - "--exclude='*.md'"
         - "--exclude='.gitignore'"
         - "--exclude='.github'"
         - "--exclude='**/*.html'"
         - "--exclude='**/*.css'"
         - "--exclude='**/*.md'"
         - "--exclude='**/*.js'"
         - "--exclude='**/*.json'"
         - "--exclude='**/*.yaml'"
         - "--exclude='**/*.yml'"
         - "--exclude='**/*.xml'"
         - "--exclude='**/*.svg'"
         - "--exclude='**/*.ttf'"
         - "--exclude='**/*.woff'"
         - "--exclude='**/*.py'"
         - "--exclude='**/*.eot'"
         - "--exclude='**/*.po'"
         - "--exclude='**/*.ico'"
         - "--exclude='**/*.map'"
         - "--exclude='**/*.txt'"
         - "--exclude='**/*.conf'"
         - "--exclude='_*/*'"
         - "--exclude='**/_*/*'"
         - "--exclude='**/locale/*'"
         - "--exclude='contrib/*'"
   - name: copy example service account yml file
     ansible.builtin.copy:
       src: "{{ source_dir }}common/source/containergroup-sa.yml"
       dest: "{{ target_dir }}common/source/"
       mode: 0644
   - name: remove source directory
     ansible.builtin.file:
       path: "{{ source_dir }}"
       state: absent
   - name: find rst files
     ansible.builtin.find:
       paths: "{{ target_dir }}"
       patterns: "*.rst"
       recurse: true
       file_type: file
     register: rst_files
   - name: modify rst
     ansible.builtin.include_tasks: modify_controller_rst.yaml
   - name: variable expansion
     ansible.builtin.script:
      cmd: replace-controller-variables.sh
   - name: convert rst to adoc
     ansible.builtin.include_tasks: convert_rst.yaml
   - name: modify adoc
     ansible.builtin.include_tasks: modify_controller_adoc.yaml
   - name: build controller xrefs
     ansible.builtin.include_tasks: build_controller_xrefs.yaml
   - name: fix cross references
     ansible.builtin.script:
      cmd: replace-controller-xrefs.sh
   - name: copy common adoc
     ansible.builtin.include_tasks: copy_controller_common_adoc.yaml
