# Shared tasks that convert Markdown to Asciidoc.
# Ensure the target_dir variable is set in the playbook that imports this.
- name: convert markdown to adoc
  ansible.builtin.shell:
    cmd: while read i; do kramdoc "$i" -o "${i%.*}.adoc"; done
    stdin: "{{ item.path }}"
  loop: "{{ md_files.files }}"
- name: rm converted markdown files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ md_files.files }}"
