- name: Synchronize Ansible lint docs
  hosts: localhost
  vars:
    source_repo: git@github.com:ansible/ansible-lint.git
    source_branch: main
    source_dir: ../sync/ansible-lint/
    source_docs_dir: ../sync/ansible-lint/docs/
    source_rules_dir: ../sync/ansible-lint/src/ansiblelint/rules/
    target_dir: ../sync/lint-docs/
    target_rules_dir: ../sync/lint-docs/rules/
  tasks:
   - name: Clone the source repository
     ansible.builtin.git:
       repo: "{{ source_repo }}"
       dest: "{{ source_dir }}"
       version: "{{ source_branch }}"
       key_file: ~/.ssh/id_rsa
   - name: Remove the target directory
     ansible.builtin.file:
       path: "{{ target_dir }}"
       state: "{{ item }}"
       mode: 0755
     with_items:
       - absent
       - directory
   - name: Find and register lint source files
     ansible.builtin.find:
       paths: "{{ source_docs_dir }}"
       patterns: "*.md"
       recurse: true
       file_type: file
     register: lint_doc_files
   - name: Find and register lint rule source files
     ansible.builtin.find:
       paths: "{{ source_rules_dir }}"
       patterns: "*.md"
       recurse: true
       file_type: file
     register: lint_rule_files
   - name: Copy the source files to the target directory
     ansible.builtin.copy:
       src: "{{ item.path }}"
       dest: "{{ target_dir }}"
       mode: 0755
     with_items: "{{ lint_doc_files.files }}"
   - name: Copy the lint rule source files to the target directory
     ansible.builtin.copy:
       src: "{{ item.path }}"
       dest: "{{ target_rules_dir }}"
       mode: 0755
     with_items: "{{ lint_rule_files.files }}"
   - name: Remove the source directory
     ansible.builtin.file:
       path: "{{ source_dir }}"
       state: absent
   - name: Find and register all markdown files
     ansible.builtin.find:
       paths: "{{ target_dir }}"
       patterns: "*.md"
       recurse: true
       file_type: file
     register: md_files
   - name: Convert markdown files to asciidoc files
     ansible.builtin.include_tasks: convert_md.yaml
   - name: Modify asciidoc files after converstion
     ansible.builtin.include_tasks: modify_lint_adoc.yaml