- name: Synchronize Ansible-lint docs
  hosts: localhost
  vars:
    source_repo: git@github.com:ansible/ansible-lint.git
    source_branch: main
    source_dir: ../sync/ansible-lint/
    source_docs_dir: ../sync/ansible-lint/docs/
    source_rules_dir: ../sync/ansible-lint/src/ansiblelint/rules/
    target_dir: ../sync/lint-docs/
    target_rules_dir: ../sync/lint-docs/rules/
  tasks:
   - name: clone source repository
     ansible.builtin.git:
       repo: "{{ source_repo }}"
       dest: "{{ source_dir }}"
       version: "{{ source_branch }}"
       key_file: ~/.ssh/id_rsa
   - name: clean target directory
     ansible.builtin.file:
       path: "{{ target_dir }}"
       state: "{{ item }}"
       mode: 0755
     with_items:
       - absent
       - directory
   - name: find doc source files
     ansible.builtin.find:
       paths: "{{ source_docs_dir }}"
       patterns: "*.md"
       recurse: true
       file_type: file
     register: lint_doc_files
   - name: find rule source files
     ansible.builtin.find:
       paths: "{{ source_rules_dir }}"
       patterns: "*.md"
       recurse: true
       file_type: file
     register: lint_rule_files
   - name: copy doc source to target
     ansible.builtin.copy:
       src: "{{ item.path }}"
       dest: "{{ target_dir }}"
       mode: 0755
     with_items: "{{ lint_doc_files.files }}"
   - name: copy rule source to target
     ansible.builtin.copy:
       src: "{{ item.path }}"
       dest: "{{ target_rules_dir }}"
       mode: 0755
     with_items: "{{ lint_rule_files.files }}"
   - name: remove source directory
     ansible.builtin.file:
       path: "{{ source_dir }}"
       state: absent
   - name: find markdown files
     ansible.builtin.find:
       paths: "{{ target_dir }}"
       patterns: "*.md"
       recurse: true
       file_type: file
     register: md_files
   - name: convert markdown to adoc
     ansible.builtin.include_tasks: convert_md.yaml
   - name: modify lint adoc
     ansible.builtin.include_tasks: modify_lint_adoc.yaml