- name: Synchronize Ansible lint docs
  hosts: localhost
  vars:
    source_root_dir: ../ansible-lint/
    source_dir: ../ansible-lint/docs/
    target_dir: ../sync/lint-docs/
  tasks:
    - name: Remove the target directory
      ansible.builtin.file:
        path: "{{ target_dir }}*"
        state: absent
    - name: Synchronize the source and target
      ansible.posix.synchronize:
        src: "{{ source_dir }}"
        dest: "{{ target_dir }}"
        delete: true
        recursive: true
        rsync_opts:
          - "--exclude='__pycache__'"
          - "--exclude='_static'"
          - "--exclude='licenses'"
          - "--exclude='pkg'"
          - "--exclude='.gitignore'"
          - "--exclude='.nojekyll'"
          - "--exclude='conf.py'"
          - "--exclude='redirects.yml'"
    - name: Copy the Ansible lint configuration file
      ansible.builtin.copy:
        src: "{{ source_root_dir }}.ansible-lint"
        dest: "{{ target_dir }}ansible-lint-config.txt"
        mode: 0644
    - name: Find and register all markdown files
      ansible.builtin.find:
        paths: "{{ target_dir }}"
        patterns: "*.md"
        recurse: true
        file_type: file
      register: md_files
    - name: Convert markdown files to asciidoc files
      ansible.builtin.include_tasks: convert_md.yaml
    - name: Modify asciidoc files after converstion
      ansible.builtin.include_tasks: modify_lint_adoc.yaml
