# Pre conversion modification of RST files.
# Ensure the target_dir variable is set in the playbook that imports this.
- name: Remove single metadata tags
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: 'single:(.+)$'
  with_items: "{{ rst_files.files }}"
- name: Remove pair metadata tags
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: 'pair:(.+)$'
  with_items: "{{ rst_files.files }}"
- name: Remove local metadata tags
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: '.. contents:: :local:'
  with_items: "{{ rst_files.files }}"
- name: Change include directive for common content
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: '.. include:: ../../common/source/'
    replace: 'include::'
  with_items: "{{ rst_files.files }}"
