:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: self-service-install-rhel

[id="self-service-install-rhel_{context}"]

= Installing {SelfService} on RHEL

[role="_abstract"]

Build and deploy bootable disk images for the {SelfService} using RHEL `bootc` image mode.
[NOTE]
====
Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.
For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
== Prerequisites
=== System Requirements
* *Operating System:* {RHEL} (RHEL) 9.6 or later, Fedora, or a compatible Linux distribution.
* *Hardware:* An x86_64 (Intel/AMD) based system.
+
[NOTE]
====
Note: MacOS and ARM-based systems (for example, Apple M-series chips) are *not currently supported* due to QEMU emulation limitations.
====

=== Software Requirements
* *Ansible Core:* 2.15 or later
* *Python:* 3.9 or later
* *Podman:* 5.4.1 or later
* *Container Image:* `bootc-image-builder` (downloaded automatically during the build)

=== Access and Permissions
* You have a valid subscription to {PlatformName}.
* You have the URL for your {PlatformNameShort} instance.
* You have configured an OAuth application in {PlatformNameShort} and retrieved the Client ID and Client Secret.
* You have generated an admin token for {PlatformNameShort} authentication
* *Root Access:* You must have `sudo` privileges to run the builder container, which requires privileged mode.
* *Registry Access:* You must have access to `registry.redhat.io` and any private registries hosting your base images.

include::devtools/con-self-service-bootc-image.adoc[leveloffset=+1]

include::devtools/proc-self-service-build-environment.adoc[leveloffset=+1]

include::devtools/proc-self-service-build-qcow2.adoc[leveloffset=+1]

include::devtools/proc-self-service-launch-qcow2.adoc[leveloffset=+1]

include::devtools/ref-self-services-variable-image.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]