ifdef::context[:parent-context: {context}]
:_mod-docs-content-type: ASSEMBLY
[id="rhdh-using_{context}"]

= Using the Ansible plug-ins

:context: rhdh-using
[role="_abstract"]
You can use {AAPRHDH} (RHDH) to learn about Ansible, create automation projects, and access opinionated workflows and tools to develop and test your automation code.
From the {RHDH} UI, you can navigate to your {PlatformNameShort} instance, where you can configure and run automation jobs. 

This document describes how to use the {AAPRHDH}.
It presents a worked example of developing a playbook project for automating updates to your firewall configuration on RHEL systems.

== Optional requirement

The {AAPRHDH} link to Learning Paths on the Red{nbsp}Hat developer portal,
link:https://developers.redhat.com/learn[developers.redhat.com/learn].

To access the Learning Paths, you must have a Red{nbsp}Hat account and you must be able to log in to link:https://developers.redhat.com[developers.redhat.com].

include::modules/ref-rhdh-dashboard.adoc[leveloffset=+1]

include::modules/ref-rhdh-learning.adoc[leveloffset=+1]

include::modules/ref-rhdh-discover-collections.adoc[leveloffset=+1]

include::modules/proc-rhdh-create.adoc[leveloffset=+1]

include::modules/proc-rhdh-view.adoc[leveloffset=+1]

include::modules/proc-rhdh-develop-projects.adoc[leveloffset=+1]

include::modules/proc-rhdh-develop-projects-devspaces.adoc[leveloffset=+2]

include::modules/proc-rhdh-execute-automation-devspaces.adoc[leveloffset=+2]

include::modules/proc-rhdh-set-up-controller-project.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

