:_newdoc-version: 2.18.5
:_template-generated: 2026-01-17
:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context-of-mcp-server-aap-vscode-extension: {context}]

ifndef::context[]
[id="mcp-server-aap-vscode-extension"]
endif::[]
ifdef::context[]
[id="mcp-server-aap-vscode-extension_{context}"]
endif::[]
= Enabling AI with the MCP server in the Ansible VS Code extension 

:context: mcp-server-aap-vscode-extension

This paragraph is the assembly introduction. It explains what the user will accomplish by working through the modules in the assembly and sets the context for the user story the assembly is based on.

== Prerequisites

* A bulleted list of conditions that must be satisfied before the user starts following this assembly.
* You can also link to other modules or assemblies the user must follow before starting this assembly.
* Delete the section title and bullets if the assembly has no prerequisites.
* X is installed. For information about installing X, see <link>.
* You can log in to X with administrator privileges.

Modules will be: 
Setting up your dev environment
Configuring the Ansible VS Code extension
Managing your Ansible dev environment
Scaffolding an Ansible project with the AI assistant
Validating and debugging with the AI assistant
Creating and validating an execution environment with the AI assistant
Running playbooks with ansible-navigator using the AI assistant


[role="_additional-resources"]
== Additional resources

* link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide]
* xref:some-module_{context}[]

ifdef::parent-context-of-mcp-server-aap-vscode-extension[:context: {parent-context-of-mcp-server-aap-vscode-extension}]
ifndef::parent-context-of-mcp-server-aap-vscode-extension[:!context:]

