ifdef::context[:parent-context-of-rhdh-telemetry-capturing: {context}]
:_mod-docs-content-type: ASSEMBLY
[id="rhdh-configure-telemetry_{context}"]

= {RHDH} data telemetry capturing

[role="_abstract"]
{RHDH} (RHDH) sends telemetry data to Red Hat using the `backstage-plugin-analytics-provider-segment` plug-in, which is enabled by default.
This includes telemetry data from the {AAPRHDHShort}.

Red Hat collects and analyzes the following data to improve your experience with {RHDH}:

* Events of page visits and clicks on links or buttons.
* System-related information, for example, locale, timezone, user agent including browser and OS details.
* Page-related information, for example, title, category, extension name, URL, path, referrer, and search parameters.
* Anonymized IP addresses, recorded as 0.0.0.0.
* Anonymized username hashes, which are unique identifiers used solely to identify the number of unique users of the RHDH application.
* Feedback and sentiment submitted through the {AAPRHDHShort} feedback form, including a 1-5 star rating and feedback text. Users must acknowledge that they share the feedback with Red Hat before submitting. The feedback form is disabled by default.

With {RHDH}, you can disable or customize the telemetry data collection feature.
For more information, refer to the
link:{BaseURL}/red_hat_developer_hub/{RHDHVers}/html/telemetry_data_collection_and_analysis/index[_Telemetry data collection and analysis_]
guide in the {RHDH} documentation.

include::devtools/proc-rhdh-enable-feedback-form.adoc[leveloffset=+1]

ifdef::parent-context-of-rhdh-telemetry-capturing[:context: {parent-context-of-rhdh-telemetry-capturing}]
ifndef::parent-context-of-rhdh-telemetry-capturing[:!context:]
