[[ag_start]]
== Automation Controller Administration Guide 4.3.0

Thank you for your interest in Red Hat Ansible Automation Platform
controller. The automation controller is a commercial offering that
helps teams manage complex multi-tier deployments by adding control,
knowledge, and delegation to Ansible-powered environments.

The Automation Controller Administration Guide documents the
administration of automation controller through custom scripts,
management jobs, and more. Written for DevOps engineers and
administrators, the Automation Controller Administration Guide assumes a
basic understanding of the systems requiring management with the
controller’s easy-to-use graphical interface. This document has been
updated to include information for the latest release of .

*We Need Feedback!*

If you spot a typo in this documentation, or if you have thought of a
way to make this manual better, we would love to hear from you! Please
send an email to: docs@ansible.com

If you have a suggestion, try to be as specific as possible when
describing it. If you have found an error, please include the manual's
title, chapter number/section number, and some of the surrounding text
so we can find it easily. We may not be able to respond to every message
sent to us, but you can be sure that we will be reading them all!

Automation Controller Version 4.3.0; ; https://access.redhat.com/

self license-support init_script custom_inventory_script scm-inv-source
multi-creds-assignment management_jobs clustering
containers_instance_groups topology_viewer logfiles logging metrics
secret_handling security_best_practices tower-manage
configure_tower_in_tower isolation_variables oauth2_token_auth
social_auth ent_auth ldap_auth authentication_timeout kerberos_auth
session_limits backup_restore custom_rebranding
usability_data_collection troubleshooting tipsandtricks postface

=== Index

____________
* `genindex`
____________
