:_mod-docs-content-type: ASSEMBLY

[id="assembly-edge-manager-intro"]

= {RedHatEdge} overview

[role="_abstract"]

The {RedHatEdge} provides streamlined management of edge devices and applications through a declarative approach. 
By defining the required state of your edge devices, which includes your operating system versions, host configurations, and application deployments, the {RedHatEdge} automatically implements and maintains these configurations across your entire device fleet.

The {RedHatEdge} on {PlatformNameShort} offers elevated integration with your automations.
You can then focus more on orchestrating the environment without worrying about updating the operating system. 

See the following topics to learn more about using {RedHatEdge} on {PlatformNameShort}:

* xref:assembly-edge-manager-architecture[{RedHatEdge} architecture]

* xref:assembly-edge-manager-install[Installing the {RedHatEdge}]

* xref:assembly-edge-manager-images[Operating system images for using with the {RedHatEdge}]

* xref:edge-manager-provisioning-devices[Provision devices]

* xref:assembly-edge-manager-manage-devices[Manage devices]

* xref:assembly-edge-manager-device-fleets[Device fleets]

//include::platform/con-edge-manager-core-capabilities.adoc[leveloffset=+1]
