:_newdoc-version: 2.18.3
:_template-generated: 2024-07-12

ifdef::context[:parent-context-of-metrics-utility: {context}]

:_mod-docs-content-type: ASSEMBLY

[id="metrics-utility"]

:context: metrics-utility

= Usage reporting with metrics-utility 

The {PlatformNameShort} metrics utility tool (`metrics-utility`) is a command-line utility that is installed on a system containing an instance of {ControllerName}. 

When installed and configured, `metrics-utility` gathers billing-related metrics from your system and creates a consumption-based billing report. The metrics-utility tool is especially suited for users who have multiple managed hosts and want to use consumption-based billing. Once a report is generated, it is deposited in a target location that you specify in the configuration file. 

`metrics-utility` collects two types of data from your system: configuration data and reporting data. 

The configuration data includes the following information:

* Version information for {ControllerName} and for the operating system 
* Subscription information
* The base URL

The reporting data includes the following information:

* Job name and ID
* Host name
* Inventory name 
* Organization name 
* Project name 
* Success or failure information
* Report date and time

To ensure that `metrics-utility` continues to work as configured, clear your report directories of outdated reports regularly. 


include::platform/proc-configuring-the-metrics-utility.adoc[leveloffset=+1]
include::platform/proc-configure-a-config-map.adoc[leveloffset=+3]
include::platform/proc-deploy-controller.adoc[leveloffset=+3]
include::platform/ref-fetching-a-monthly-report.adoc[leveloffset=+1]
include::platform/proc-modifying-the-run-schedule.adoc[leveloffset=+1]
include::platform/ref-supported-storage.adoc[leveloffset=+1]
include::platform/ref-report-types.adoc[leveloffset=+1]
include::platform/ref-renewal-guidance.adoc[leveloffset=+1]
include::platform/ref-storage-invocation.adoc[leveloffset=+3]
include::platform/ref-show-ephemeral-use.adoc[leveloffset=+3]
include::platform/ref-select-a-date-range.adoc[leveloffset=+3]
include::platform/ref-ccsp.adoc[leveloffset=+2]



-



ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

