:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="assembly-aap-activate"]
= Activating {PlatformName}

:context: activate-aap

[role="_abstract"]
{PlatformName} uses available subscriptions or a subscription manifest to authorize the use of {PlatformNameShort}. To obtain a subscription, you can do either of the following:

. Use your Red Hat username and password, service account credentials, or Satellite credentials when you launch {PlatformNameShort}.
. Upload a subscriptions manifest file either using the {PlatformName} interface or manually in an Ansible Playbook.

ifndef::operationG[]
include::platform/proc-aap-activate-with-credentials.adoc[leveloffset=+1]

include::platform/proc-aap-activate-with-manifest.adoc[leveloffset=+1]
endif::operationG[]

ifdef::operationG[]
To activate {PlatformNameShort} using credentials, see link:{URLContainerizedInstall}/assembly-gateway-licensing#proc-aap-activate-with-credentials[Activate with credentials].

To activate {PlatformNameShort} with a manifest file, see link:{URLContainerizedInstall}/assembly-gateway-licensing#proc-aap-activate-with-manifest[Activate with a manifest file].
endif::operationG[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]