ifdef::context[:parent-context: {context}]

[id="configure-aap-operator_{context}"]

:context: configure-aap-operator

= Configuring the Red Hat {OperatorPlatform} on {OCP}

The platform gateway for {PlatformNameShort} enables you to manage the following {PlatformNameShort} components to form a single user interface:

* {ControllerNameStart}
* {HubNameStart}
* {EDAName}
* {LightspeedShortName} (This feature is disabled by default, you must opt in to use it.)

Before you can deploy the platform gateway you must have {OperatorPlatform} installed in a namespace. 
If you have not installed {OperatorPlatform} see <<Installing the Red Hat Ansible Automation Platform operator on Red Hat OpenShift Container Platform>>.

NOTE: Platform gateway is only available under {OperatorPlatform} version 2.5. Every component deployed under {OperatorPlatform} 2.5 will also default to version 2.5.

If you have the {OperatorPlatform} and some or all of the {PlatformNameShort} components installed see <<Deploying the platform gateway with existing {PlatformNameShort} components>> for how to proceed. 

include::platform/proc-operator-link-components.adoc[leveloffset=+1]
include::platform/proc-operator-access-aap.adoc[leveloffset=+1]
include::platform/proc-operator-deploy-central-config.adoc[leveloffset=+1]
include::platform/proc-operator-aap-faq.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]