:_mod-docs-content-type: ASSEMBLY

[id="HA-redis_{context}"]

= Caching and queueing system

[role="_abstract"]
Understand how link:https://redis.io/[Redis] provides centralized caching and queueing for {PlatformNameShort} {PlatformVers} components. Learn how this in-memory system stores event queues, session data, and tokens to deliver improved performance, reliability, and data security.  

In {PlatformNameShort} {PlatformVers}, link:https://redis.io/[Redis (REmote DIctionary Server)] is used as the caching and queueing 
system. 
Redis is an open source, in-memory, NoSQL key/value store that is used primarily as an application cache, quick-response database 
and lightweight message broker.  

Centralized Redis is provided for the {Gateway} and {EDAName} and shared between those components. 
{ControllerNameStart} and {HubName} have their own instances of Redis. 

This cache and queue system stores data in memory, rather than on a disk or solid-state drive (SSD), which helps deliver speed, reliability, and performance. In {PlatformNameShort}, the system caches the following types of data for the various services in {PlatformNameShort}:

.Data types cached by Centralized Redis
[options="header"]
|====
| {ControllerNameStart} | {EDAName} server | {HubNameStart} | {GatewayStart} 
| N/A {ControllerName} does not use shared Redis in {PlatformNameShort} {PlatformVers} | Event queues | N/A {HubName} does not use shared Redis in {PlatformNameShort} {PlatformVers} | Settings, Session Information, JSON Web Tokens
|====

This data can contain sensitive Personal Identifiable Information (PII). Your data is protected through secure communication with the cache and queue system through both Transport Layer Security (TLS) encryption and authentication.  

[NOTE]
====
The data in Redis from both the {Gateway} and {EDAName} are partitioned; therefore, neither service can access the other’s data.
====

include::platform/con-gw-centralized-redis.adoc[leveloffset=+1]
include::platform/con-gw-clustered-redis.adoc[leveloffset=+1]
include::platform/con-gw-single-node-redis.adoc[leveloffset=+1]
