:_mod-docs-content-type: ASSEMBLY


ifdef::context[:parent-context: {context}]

[id="design-patterns"]
= Design patterns for mesh

:context: design-patterns

[role="_abstract"]
The automation mesh topologies in this section provide examples you can use to design a mesh deployment in your environment. Examples range from a simple, hydrid node deployment to a complex pattern that deploys numerous {ControllerName} instances, employing several execution and hop nodes.

[IMPORTANT]
====
If you are creating a mesh similar to the following in a containerized environment:

* Replace the `node_type` variable with `receptor_type`
* Replace the `peers` variable with `receptor_peers`
* Replace inventory group names with explicit comma-separated lists of hostnames

The value of `receptor_peers` must be a comma-separated list of hostnames. Do not use inventory group names. For more information, see link:{URLContainerizedInstall}/advanced-configuration-containerized#adding-execution-nodes[Adding execution nodes].
====

*Prerequisites*

* You reviewed conceptual information on node types and relationships.

[NOTE]
====
The following examples include images that illustrate the mesh topology.
The arrows in the images indicate the direction of peering.
After peering is established, the connection between the nodes allows bidirectional communication.
====

include::platform/ref-multiple-hybrid-nodes.adoc[leveloffset=+1]

include::platform/ref-single-node-control-plane-single-execution-node.adoc[leveloffset=+2]

include::platform/ref-mesh-minimum-resilient-config.adoc[leveloffset=+1]

include::platform/ref-mesh-segregated-execution_nodes.adoc[leveloffset=+1]

include::platform/ref-mesh-multi-hop-execution.adoc[leveloffset=+2]

include::platform/ref-mesh-one-way-communication.adoc[leveloffset=+2]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
