ifdef::context[:parent-context: {context}]

:_mod-docs-content-type: ASSEMBLY

[id="assembly-controller-teams_{context}"]

= Teams

:context: controller-teams

A team is a subdivision of an organization with associated users and resources. Teams provide a means to implement role-based access control schemes and delegate responsibilities across organizations. For instance, you can grant permissions to a team rather than each user on the team.
You can create as many teams as needed for your organization. Teams can only be assigned to one organization while an organization can be made up of multiple teams. Each team can be assigned roles, the same way roles are assigned for users. With teams you can assign credential ownership at scale, preventing the need to click through multiple interfaces to assign the same credentials to each individual user.

include::proc-controller-creating-a-team.adoc[leveloffset=+1]

include::proc-gw-team-list-view.adoc[leveloffset=+1]

include::proc-gw-team-add-user.adoc[leveloffset=+1]

include::proc-gw-team-remove-user.adoc[leveloffset=+1]

include::proc-gw-add-admin-team.adoc[leveloffset=+1]

include::proc-controller-user-permissions.adoc[leveloffset=+1]

include::proc-gw-remove-roles-team.adoc[leveloffset=+1]

include::proc-gw-delete-team.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]