:_mod-docs-content-type: ASSEMBLY

[id="assembly-edge-manager-device-fleets"]

= Manage a large number of devices with device fleets

[role="_abstract"]

The {RedHatEdge} simplifies the management of a large number of devices and workloads through _device fleets_. 
A fleet is a resource that defines a group of devices governed by a common device template and management policies.

When you make a change to the device template, all devices in the fleet receive the changes when the {RedHatEdge} agent detects the new target specification.

Device monitoring in a fleet is also simplified because you can check the status summary of the whole fleet.

Fleet-level management offers the following advantages:

* Scales your operations because you perform operations only once for each fleet instead of once for each device.
* Minimizes the risk of configuration mistakes and configuration drift.
* Automatically applies the target configuration when you add devices to the fleet or replace devices in the fleet.
The fleet specification consists of the following features:

Label selector:: Determines which devices are part of the fleet.
Device template:: Defines the configuration that the {RedHatEdge} enforces on devices in the fleet.
Policies:: Governs how devices are managed, for example, how changes to the device template are rolled out to the devices.

You can have both individually managed and fleet-managed devices at the same time.

When you select a device into a fleet, the {RedHatEdge} creates the device specification for the new device based on the device template.
If you update the device template for a fleet or a new device joins the fleet, the {RedHatEdge} enforces the new specification in the fleet.

If a device is not selected into any fleets, the device is considered user-managed or unmanaged.
For user-managed devices, you must update the device specification either manually or through an external automation.

[IMPORTANT]
====
A device cannot be a member of more than one fleet at the same time.
====

For more information, see xref:edge-manager-labels[Labels and label selectors].

include::platform/ref-edge-manager-device-selection.adoc[leveloffset=+1]

include::platform/ref-edge-manager-device-templates.adoc[leveloffset=+1]

include::platform/proc-edge-manager-add-devices-ui.adoc[leveloffset=+1]

include::platform/proc-edge-manager-add-devices-cli.adoc[leveloffset=+1]

include::platform/con-edge-manager-rollout-device-selection.adoc[leveloffset=+1]

include::platform/con-edge-manager-device-targeting.adoc[leveloffset=+2]

include::platform/con-edge-manager-device-selection-strat.adoc[leveloffset=+2]

include::platform/con-edge-manager-limit-device.adoc[leveloffset=+2]

include::platform/ref-edge-manager-success-threshold.adoc[leveloffset=+2]

include::platform/con-edge-manager-rollout-disruption.adoc[leveloffset=+1]

include::platform/ref-edge-manager-disruption-parameters.adoc[leveloffset=+2]
