:_mod-docs-content-type: ASSEMBLY

[id="assembly-controller-ee-setup-reference"]

= Execution environment setup reference

[role="_abstract"]
Review this reference information to better understand the definition of an {ExecEnvShort}.
You define the content of your {ExecEnvShort} in a YAML file. 
By default, this file is called `execution_environment.yml`. 
This file tells {Builder} how to create the build instruction file (Containerfile for Podman, Dockerfile for Docker) and build context for your container image.

[NOTE]
====
The definition schema for {Builder} 3.x is documented here. 
If you are running an older version of {Builder}, you need an older schema version. 
For more information, see older versions of link:https://ansible.readthedocs.io/projects/builder/en/latest/[this] documentation. 
We recommend using version 3, which offers substantially more configurable options and functionality than previous versions.
====

include::platform/ref-controller-ee-definition.adoc[leveloffset=+1]

include::platform/ref-controller-ee-configuration-options.adoc[leveloffset=+1]

include::platform/ref-controller-additional-build-files.adoc[leveloffset=+2]

include::platform/ref-controller-additional-build-steps.adoc[leveloffset=2]

include::platform/ref-controller-build-arg-defaults.adoc[leveloffset=+2]

include::platform/ref-controller-dependencies.adoc[leveloffset=+2]

include::platform/ref-controller-images.adoc[leveloffset=+2]

include::platform/ref-controller-image-verification.adoc[leveloffset=+2]

include::platform/ref-controller-config-options.adoc[leveloffset=+2]

include::platform/ref-controller-config-version.adoc[leveloffset=+2]

include::platform/ref-controller-awx-default-ee.adoc[leveloffset=+1]




