:_mod-docs-content-type: ASSEMBLY

[id="controller-backup-and-restore"]

= Backup and restore

[role="_abstract"]
You can protect your {PlatformNameShort} environment by backing up the database, configuration files, and keys. Use the `./setup.sh` script or playbooks to create compressed artifacts. This ensures a recovery path for single nodes or clusters, including restores to secondary instances. 

[NOTE]
====
When backing up {PlatformNameShort}, use the installation program that matches your currently installed version of {PlatformNameShort}.

When restoring {PlatformNameShort}, use the latest installation program available at the time of the restore. For example, if you are restoring a backup taken from version `2.6`, use the latest `2.6` installation program available at the time of the restore.

Backup and restore functionality only works with the PostgreSQL versions supported by your current {PlatformNameShort} version. 
For more information, see link:{URLPlanningGuide}/platform-system-requirements[System requirements] in _{TitlePlanningGuide}_.
====

//include::platform/con-controller-backup-restore-playbooks.adoc[leveloffset=+1]

include::platform/ref-controller-backup-restore-considerations.adoc[leveloffset=+1]

include::platform/con-controller-backup-aap.adoc[leveloffset=+1]

include::platform/con-controller-backup-playbook.adoc[leveloffset=+2]

include::platform/proc-backup-using-automation-installer.adoc[leveloffset=+2]

include::platform/con-controller-restore-aap.adoc[leveloffset=+1]

include::platform/con-controller-restore-playbook.adoc[leveloffset=+2]

include::platform/proc-restore-aap.adoc[leveloffset=+2]

//include::platform/ref-controller-backup-restore-clustered-environments.adoc[leveloffset=+1]

//include::platform/con-controller-restore-different-cluster.adoc[leveloffset=+2]
