:_newdoc-version: 2.18.4
:_template-generated: 2025-05-08
:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context-of-controller-pac: {context}]

ifndef::context[]
[id="controller-pac"]
endif::[]
ifdef::context[]
[id="controller-pac_{context}"]
endif::[]
= Implementing policy enforcement

:context: controller-pac

[role="_abstract"]
Policy enforcement at automation runtime is a feature that uses encoded rules to define, manage, and enforce policies that govern how your users interact with your {PlatformNameShort} instance. Policy enforcement automates policy management, improving security, compliance, and efficiency. 

OPA, or link:https://www.openpolicyagent.org/docs/latest/[Open Policy Agent], is a policy engine that offloads policy decisions from your Ansible instance. When it is triggered, the policy enforcement feature connects to OPA to retrieve policies specified in your configuration, and applies policy rules to your automation content. If OPA detects a policy violation, it will stop the action and give your user information about the policy violation.

*Prerequisites*

Before you can implement policy enforcement in your {PlatformNameShort} instance, you must have: 

// * An {PlatformNameShort} 2.5 deployment with the `FEATURE_POLICY_AS_CODE_ENABLED` feature flag set to `TRUE`.
* Access to an OPA server that is reachable from your {PlatformNameShort} deployment.
* Configured {PlatformNameShort} with settings required for authenticating to your OPA server.
* Some familiarity with OPA and the Rego language, which is the language policies are written in.

For policy enforcement to work correctly, you must both configure the OPA server in your policy settings, and associate a specific policy with a particular resource.
For example, a particular organization, inventory, or job template. 

[NOTE]
====
OPA API V1 is the only version currently supported in {PlatformNameShort}.
====

// include::platform/proc-enable-pac.adoc[leveloffset=+1]

include::platform/proc-configure-pac-settings.adoc[leveloffset=+1]

include::platform/con-pac-policies-rules.adoc[leveloffset=+1]

include::platform/proc-configure-pac-enforcement.adoc[leveloffset=+1]

include::platform/proc-pac-add-policy-to-org.adoc[leveloffset=+2]

include::platform/proc-pac-add-policy-to-inventory.adoc[leveloffset=+2]

include::platform/proc-pac-add-policy-to-template.adoc[leveloffset=+2]

include::platform/ref-pac-inputs-outputs.adoc[leveloffset=+1]
