:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="changing-ssl-certs-keys"]
= Renewing and changing the SSL/TLS certificates

:context: renewing-changing-ssl-certs-keys

[role="_abstract"]
If your current SSL/TLS certificates have expired or will expire soon, you can either renew or replace the SSL/TLS certificates used by {PlatformNameShort}.

You must renew the SSL/TLS certificates if you need to regenerate them with new information such as new hosts.

You must replace the SSL/TLS certificates if you want to use certificates signed by an internal certificate authority.

== Container-based installations

You can change the TLS certificates and keys for your container-based {PlatformNameShort} installation. This process involves a preparation step, either providing new custom certificates or deleting or moving the old certificates, followed by running the installation program.

include::platform/proc-change-tls-certs-installer.adoc[leveloffset=+2]

== Operator-based installations

include::platform/proc-change-ssl-controller-ocp.adoc[leveloffset=+2]

include::platform/proc-change-ssl-hub-ocp.adoc[leveloffset=+2]

== RPM-based installations

To renew or change SSL/TLS certificates for RPM-based installations, you can edit the inventory file and run the installation program.
The installation program verifies that all {PlatformNameShort} components are working. 

Alternatively, you can change the SSL/TLS certificates manually. 
This is quicker, but there is no automatic verification.

Red Hat recommends that you use the installation program to make changes to your {PlatformNameShort} deployment.

include::platform/proc-renew-ssl-cert.adoc[leveloffset=+2]

include::platform/proc-change-ssl-installer.adoc[leveloffset=+2]

include::platform/proc-change-ssl-manual-rpm.adoc[leveloffset=+2]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
