:_mod-docs-content-type: ASSEMBLY

[id="setting-up-a-customer-provided-external-database"]

= Configure an external (customer provided) PostgreSQL database

[role="_abstract"]
Set up an external (customer provided) PostgreSQL database for containerized {PlatformNameShort} to use your own database infrastructure.

There are two possible scenarios for setting up an external database:

. An external database with PostgreSQL admin credentials
. An external database without PostgreSQL admin credentials

[IMPORTANT]
====
* When using an external database with {PlatformNameShort}, you must create and support that database. Ensure that you clear your external database when uninstalling {PlatformNameShort}.

* {PlatformName} requires customer provided (external) database to have ICU support.

* During configuration of an external database, you must check the external database coverage. For more information, see link:https://access.redhat.com/articles/4010491[{PlatformName} Database Scope of Coverage].

* The `[database]` group in your inventory file defines the {PlatformNameShort} managed database. When using an externally managed database, do not include the `[database]` group in your inventory file.
====

include::platform/proc-setup-ext-db-with-admin-creds.adoc[leveloffset=+1]

include::platform/proc-setup-ext-db-without-admin-creds.adoc[leveloffset=+1]

include::platform/proc-enable-hstore-extension.adoc[leveloffset=+1]

include::platform/proc-configure-ext-db-mtls.adoc[leveloffset=+1]
