ifdef::context[:parent-context: {context}]

:_mod-docs-content-type: ASSEMBLY

[id="assembly-controller-organizations_{context}"]

= Organizations

:context: access-mgmt-orgs

An organization is a grouping of resources such as projects, inventories, and credentials. You can define granular access to the resources wihtin an organization by first assigning users and teams to the organization, and then assigning those users and teams defined roles within the organization.

As an administrator you can use organizations to organize groups of resources. 
Assigning a team or user to the organization gives the team or user access to the resources within the organization.
This way, administrators no longer have to grant individual teams and resources access to new resources as they become available; teams and users gain access to new resources when they are added to the organization.

After you have created an organization, {PlatformNameShort} displays the organization details. You can then manage resources such as access and execution environments for the organization.

{PlatformNameShort} automatically creates a default organization. If you have a Self-support level license, you have only the default organization available and must not delete it.

// [ddacosta] Removed this statement because I think it was relevant when this content was upstream but in the downstream docs, it’s implied that you have a license.
//[NOTE]
//====
//Only Enterprise or Premium licenses can add new organizations.
//====
//Enterprise and Premium license users who want to add a new organization should refer to the xref:proc-controller-create-organization[Creating an organization].

include::platform/proc-controller-review-organizations.adoc[leveloffset=+1]

include::platform/proc-controller-create-organization.adoc[leveloffset=+1]

include::platform/con-controller-access-organizations.adoc[leveloffset=+1]

include::platform/proc-controller-add-organization-user.adoc[leveloffset=+2]

include::platform/proc-gw-add-admin-organization.adoc[leveloffset=+2]

include::platform/proc-gw-add-team-organization.adoc[leveloffset=+2]

include::platform/proc-gw-delete-organization.adoc[leveloffset=+2]

include::platform/proc-controller-organization-notifications.adoc[leveloffset=+1] 

include::platform/proc-gw-organizations-exec-env.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
