:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="changing-ssl-certs-keys"]
= Renewing and changing the SSL/TLS certificates

:context: renewing-changing-ssl-certs-keys

[role="_abstract"]
If your current SSL/TLS certificate has expired or will expire soon, you can either renew or replace the SSL/TLS certificate used by {PlatformNameShort}.

You must renew the SSL/TLS certificate if you need to regenerate the SSL/TLS certificate with new information such as new hosts.

You must replace the SSL/TLS certificate if you want to use an SSL/TLS certificate signed by an internal certificate authority.

== Operator-based installations

include::platform/proc-change-ssl-controller-ocp.adoc[leveloffset=+2]

include::platform/proc-change-ssl-hub-ocp.adoc[leveloffset=+2]

== RPM-based installations

To renew or change the SSL certificate for RPM-based installations, you can edit the inventory file and run the installation program.
The installation program verifies that all {PlatformNameShort} components are working. 
The installation program can take a long time to run.

Alternatively, you can change the SSL certificates manually. 
This is quicker, but there is no automatic verification.

Red Hat recommends that you use the installation program to make changes to your {PlatformNameShort} instance.

include::platform/proc-renew-ssl-cert.adoc[leveloffset=+2]

include::platform/proc-change-ssl-installer.adoc[leveloffset=+2]

include::platform/proc-change-ssl-controller.adoc[leveloffset=+2]

include::platform/proc-change-ssl-eda-controller.adoc[leveloffset=+2]

include::platform/proc-change-ssl-hub.adoc[leveloffset=+2]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
