:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="assembly-controller-users_{context}"]
= View, create, or assign roles to users

:context: access-mgmt-users

[role="_abstract"]
A user is an individual or entity that can log in to the platform and perform tasks. Users are fundamental units to which roles can be assigned, either directly by an administrator or indirectly through a team.

[NOTE] 
====
{PlatformNameShort} automatically creates a default system admin user so they can log in and set up {PlatformNameShort} for their organization. This user cannot be deleted or modified. 

====
You can sort or search the User list by *Username*, *First name*, *Last name*, or *Email*. Click the arrows in the header to toggle your sorting preference.
You can view *User type* and *Email* beside the user name on the Users page.

include::platform/proc-gw-users-list-view.adoc[leveloffset=+1]

include::platform/proc-controller-creating-a-user.adoc[leveloffset=+1]

include::platform/proc-gw-editing-a-user.adoc[leveloffset=+1]

include::platform/proc-controller-deleting-a-user.adoc[leveloffset=+1]

include::platform/proc-controller-user-roles.adoc[leveloffset=+1]

include::platform/proc-gw-remove-roles-user.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
