ifdef::context[:parent-context: {context}]

[id="aap-post-upgrade"]
= {PlatformNameShort} post-upgrade steps

:context: aap-post-upgrade

[role="_abstract"]

After a successful upgrade to {PlatformNameShort} 2.5, the next crucial step is migrating your users to the latest version of the platform. 

User data and legacy authentication settings from automation controller and private automation hub are carried over during the upgrade process and allow seamless initial access to the platform after upgrade. Customers can login without additional action.

However, to fully transition authentication to use all of the features and capabilities of the 2.5 platform gateway, a manual process is required post-upgrade to leverage the new authentication framework. In the context of upgrading to Ansible Automation Platform 2.5, this manual process is referred to as migration. 

There are important notes and considerations for each type of user migration, including the following:

* Admin users
* Normal users
* SAML users

Be sure to read through the important notes highlighted for each user type to help make the migration process as smooth as possible.

include::platform/proc-aap-migrate-admin-users.adoc[leveloffset=+1]
include::platform/con-aap-migrate-normal-users.adoc[leveloffset=+1]
include::platform/proc-account-linking.adoc[leveloffset=+2]
include::platform/proc-aap-migrate-SAML-users.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:] 
