:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="install-aap-gateway_{context}"]

:context: install-aap-gateway

= Deploy {PlatformNameShort} 

[role="_abstract"]

As a namespace administrator, you can use {PlatformNameShort} gateway to manage new {PlatformNameShort} components in your OpenShift environment.

The {PlatformNameShort} gateway uses the {PlatformNameShort} custom resource to manage and integrate the following {PlatformNameShort} components into a unified user interface:

* {ControllerNameStart}
* {HubNameStart}
* {EDAName}
* {LightspeedShortName} (This feature is disabled by default, you must opt in to use it.)

Before you can deploy the {Gateway} you must have {OperatorPlatformNameShort} installed in a namespace. 
If you have not installed {OperatorPlatformNameShort} see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#install-aap-operator_operator-platform-doc[Installing the {OperatorPlatformName} on {OCP}].

[NOTE] 
====
{GatewayStart} is only available under {OperatorPlatformNameShort} version {PlatformVers}. Every component deployed under {OperatorPlatformNameShort} {PlatformVers} defaults to version {PlatformVers}.
====

If you have the {OperatorPlatformNameShort} and some or all of the {PlatformNameShort} components installed see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#operator-deploy-central-config_install-aap-gateway[Deploying the {Gateway} with existing {PlatformNameShort} components] for how to proceed. 

include::platform/proc-operator-link-components.adoc[leveloffset=+1]

include::platform/proc-operator-deploy-central-config.adoc[leveloffset=+1]

include::platform/proc-operator-access-aap.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]