ifdef::context[:parent-context: {context}]

:_mod-docs-content-type: ASSEMBLY

[id="assembly-controller-organizations_{context}"]

= Structure groups and resources with organizations

:context: access-mgmt-orgs


[role="_abstract"]
As an administrator, you can use organizations to organize groups of resources. 
Assigning a team or user to the organization gives the team or user access to the resources within the organization.
This way, administrators no longer have to grant individual teams and users access to new resources as they become available; teams and users gain access to new resources when they are added to the organization.

After you have created an organization, {PlatformNameShort} displays the organization details. You can then manage resources such as access and execution environments for the organization.

{PlatformNameShort} automatically creates a default organization. If you have a self-support level license, you have only the default organization available and must not delete it.

include::platform/proc-controller-review-organizations.adoc[leveloffset=+1]

include::platform/proc-controller-create-organization.adoc[leveloffset=+1]

include::platform/con-controller-access-organizations.adoc[leveloffset=+1]

include::platform/proc-controller-add-organization-user.adoc[leveloffset=+2]

include::platform/proc-gw-add-admin-organization.adoc[leveloffset=+2]

include::platform/proc-gw-add-team-organization.adoc[leveloffset=+2]

include::platform/proc-gw-delete-organization.adoc[leveloffset=+2]

include::platform/proc-controller-organization-notifications.adoc[leveloffset=+1] 

include::platform/proc-gw-organizations-exec-env.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
