// This assembly is part of the AAP Planning Guide
[id='aap_architecture']
= {PlatformName} Architecture

As a modular platform, {PlatformNameShort} provides the flexibility to easily integrate components and customize your deployment to best meet your automation requirements. 

Red Hat recommends that customers always deploy all components of {PlatformNameShort} so that all features and capabilities are available for use without the need to take further action.

Red Hat tests and recommends installing {PlatformNameShort} {PlatformVers} based on a defined set of infrastructure topologies or reference architectures. Enterprise organizations should use one of the enterprise topologies for production deployments to ensure the highest level of uptime, performance, and continued scalability. Organizations or deployments that are resource constrained can use a "growth" topology.

The following section provides a comprehensive architectural example of an {PlatformNameShort} deployment.

include::platform/con-aap-example-architecture.adoc[leveloffset=+1]
include::platform/ref-example-CONT-architecture.adoc[leveloffset=+1]
include::platform/ref-example-OCP-architecture.adoc[leveloffset=+1]