:_mod-docs-content-type: ASSEMBLY

[id="aap-containerized-installation"]

= {PlatformNameShort} containerized installation

[role="_abstract"]
{PlatformNameShort} is a commercial offering that helps teams manage complex multitiered deployments by adding control, knowledge, and delegation to Ansible-powered environments.

This guide helps you to understand the installation requirements and processes behind the containerized version of {PlatformNameShort}. 

== {TitleTopologies}

Red Hat tests {PlatformNameShort} {PlatformVers} with a defined set of topologies to give you opinionated deployment options. The supported topologies include infrastructure topology diagrams, tested system configurations, example inventory files, and network ports information.

For containerized {PlatformNameShort}, there are two infrastructure topology shapes:

. Growth - (All-in-one) Intended for organizations that are getting started with {PlatformNameShort}. This topology allows for smaller footprint deployments.

. Enterprise - Intended for organizations that require {PlatformNameShort} deployments to have redundancy or higher compute for large volumes of automation. This is a more future-proofed scaled out architecture.

For more information about the tested deployment topologies for containerized {PlatformNameShort}, see link:{URLTopologies}/container-topologies[Container topologies] in _{TitleTopologies}_.

include::platform/ref-cont-aap-system-requirements.adoc[leveloffset=+1]

include::platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc[leveloffset=+1]

include::platform/proc-preparing-the-managed-nodes-for-containerized-installation.adoc[leveloffset=+1]

include::platform/proc-downloading-containerized-aap.adoc[leveloffset=+1]

include::platform/ref-configuring-inventory-file.adoc[leveloffset=+1]

include::platform/proc-set-registry-username-password.adoc[leveloffset=+2]

== Advanced configuration options
Advanced configuration options, such as external database set up and the use of custom TLS certs, are available for more complex deployments of containerized {PlatformNameShort}. 

If you are not using these advanced configuration options, go to link:{URLContainerizedInstall}/aap-containerized-installation#installing-containerized-aap[Installing containerized {PlatformNameShort}] to continue with your installation.

include::platform/proc-add-eda-safe-plugin-var.adoc[leveloffset=+2]

include::platform/ref-adding-execution-nodes.adoc[leveloffset=+2]

include::assembly-configure-hub-storage.adoc[leveloffset=+2]

include::platform/proc-configure-haproxy-load-balancer.adoc[leveloffset=+2]

include::platform/proc-enabling-automation-hub-collection-and-container-signing.adoc[leveloffset=+2]

include::assembly-setup-postgresql-ext-database.adoc[leveloffset=+2]

include::assembly-using-custom-tls-certificates.adoc[leveloffset=+2]

include::platform/ref-using-custom-receptor-signing-keys.adoc[leveloffset=+2]

include::assembly-deploying-lightspeed-containerized-install.adoc[leveloffset=+2]

include::platform/proc-installing-containerized-aap.adoc[leveloffset=+1]

//Michelle: Postinstall not currently functioning so commented out
//include::platform/proc-using-postinstall.adoc[leveloffset=+1]

include::platform/proc-update-aap-container.adoc[leveloffset=+1]

include::platform/proc-backup-aap-container.adoc[leveloffset=+1]

include::platform/proc-restore-aap-container.adoc[leveloffset=+1]

include::platform/proc-uninstalling-containerized-aap.adoc[leveloffset=+1]

include::platform/proc-reinstalling-containerized-aap.adoc[leveloffset=+1]
