:_mod-docs-content-type: ASSEMBLY

[id="controller-setting-up-insights"]

= Setting up {RHLightspeed} Remediations

{ControllerNameStart} supports integration with {RHLightspeed}. 

When a host is registered with {RHLightspeed}, it is scanned continually for vulnerabilities and known configuration conflicts.
Each problem identified can have an associated fix in the form of an Ansible Playbook. 

{RHLightspeed} users create a maintenance plan to group the fixes and can create a playbook to mitigate the problems. 
{ControllerNameStart} tracks the maintenance plan playbooks through a {RHLightspeed} project.

Authentication to {RHLightspeed} through Basic Authorization is backed by a special credential, which must first be established in {ControllerName}.

To run a {RHLightspeed} maintenance plan, you need a {RHLightspeed} project and inventory.

include::platform/proc-controller-create-insights-credential.adoc[leveloffset=+1]

include::platform/proc-controller-create-insights-project.adoc[leveloffset=+1]

include::platform/con-controller-create-insights-inventory.adoc[leveloffset=+1]

include::platform/proc-controller-remediate-insights-inventory.adoc[leveloffset=+1]
