[[releasenotes_start]]
== Automation Controller Release Notes 4.3.0

Thank you for your interest in Red Hat Ansible Automation Platform
controller. automation controller is a commercial offering that helps
teams manage complex multi-tier deployments by adding control,
knowledge, and delegation to Ansible-powered environments.

The Automation Controller Release Notes provides release notes, known
issues, and related reference materials. This document has been updated
to include information for the latest release of .

*We Need Feedback!*

If you spot a typo in this documentation, or if you have thought of a
way to make this manual better, we would love to hear from you! Please
send an email to: docs@ansible.com

If you have a suggestion, try to be as specific as possible when
describing it. If you have found an error, please include the manual's
title, chapter number/section number, and some of the surrounding text
so we can find it easily. We may not be able to respond to every message
sent to us, but you can be sure that we will be reading them all! 

Automation Controller Version 4.3.0; ; https://access.redhat.com/

self relnotes known_issues supported_locales

=== Index

____________
* `genindex`
____________

include::copyright.adoc[]
