ifdef::context[:parent-context: {context}]

:_content-type: ASSEMBLY

[id="assigning-seat-licenses_{context}"]

= Assigning and removing seat licenses

:context: assigning-seat-licenses

[role="_abstract"]
After connecting {LightspeedShortName} to an {ibmwatsonxcodeassistant} instance, Red Hat Customer Portal organization administrators can assign seat licenses to users in their organization. The seat assignment feature enables select Ansible users in your organization to access and use {LightspeedShortName}. 

Your {PlatformName} subscription includes a specific number of Ansible Lightspeed named seats depending on the number of {PlatformNameShort} subscriptions your organization has purchased. {LightspeedShortName} authenticates users by using Red Hat Single Sign-On (RH-SSO) and verifies that they have an assigned seat license.

include::modules/proc_assign-seat-licenses.adoc[leveloffset=+1]
include::modules/proc_remove-seat-licenses.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

