ifdef::context[:parent-context: {context}]

:_content-type: ASSEMBLY

[id="configuring-with-code-assistant_{context}"]

= Installing and configuring the Ansible VScode extension

:context: configuring-with-code-assistant

[role="_abstract"]
{LightspeedFullName} is integrated with the Ansible Visual Studio (VS) Code extension in VS Code. The Ansible VS Code extension, with {LightspeedFullName} features enabled, automatically collects recommendations, usage telemetry, and Ansible YAML file state through automated events. 

To access {LightspeedShortName}, all Ansible users must install and configure the Ansible VS Code extension in their VS Code. The Ansible VS Code extension uses the Ansible-specific IBM watsonx Granite model configured in the Ansible Lightspeed administrator portal as the default mode for all users that have been assigned an Ansible Lightspeed seat. However, Ansible users can use the *model-override* setting in the Ansible VS Code extension settings to specify a different model ID. 

include::modules/proc_install-vscode-extension.adoc[leveloffset=+1]
include::modules/proc_configure-vscode-extension.adoc[leveloffset=+1]



ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

