ifdef::context[:parent-context: {context}]

:_content-type: ASSEMBLY

[id="configuring-custom-models_{context}"]

= Configuring custom models

:context: configuring-custom-models

[role="_abstract"]

== Overview 
As an organization administrator, you can create and use fine-tuned, custom models that are trained on your organization's existing Ansible content. This capability enables you to improve the code recommendation experience and tune the models to your organization's automation patterns. For example, you can use intellectual property information or private collections of Ansible data that are not open source to train a custom model. As a result, the code recommendations are tailored to your business requirements and processes.

You can configure multiple custom models for your organization. For example, you can create a custom model for your corporate IT automation team and a different one for your engineering team's infrastructure. You can also configure a custom model to make it available for all Ansible users or select Ansible users in your organization. 

== Process

To configure a custom model, perform the following tasks: 

. Create a custom model training data set by using the Ansible content parser (URL)

. Create and deploy a custom model by using {ibmwatsonxcodeassistant} (URL)

. Configure {LightspeedshortName} to use the newly-created custom model (URL)

include::modules/proc_create-custom-models-content-parser.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

