ifdef::context[:parent-context: {context}]

:_content-type: ASSEMBLY

[id="using-code-bot-for-suggestions_{context}"]

= Installing and configuring Ansible code bot

:context: using-code-bot-for-suggestions

[role="_abstract"]

The {AnsibleCodeBot} scans existing content collections, roles, and playbooks hosted in GitHub repositories, and proactively creates pull requests whenever best practices or quality improvement recommendations are available. The bot automatically submits pull requests to the repository, which proactively alerts the repository owner to a recommended change to their content . You can configure {AnsibleCodeBot} to scan your existing Git repositories (both public and private). Your organization must have a valid {LightspeedFullName} subscription to use Ansible code bot. 

{AnsibleCodeBot} uses Ansible lint to recommend code quality improvements. {AnsibleCodeBot} is intended to promote proven practices, patterns, and behaviors while avoiding common errors that can easily lead to bugs or make code harder to maintain. {AnsibleCodeBot} scans your content based on the configured rules, to ensure that your content adheres to Ansible best practices.

[NOTE]
====
* {LightspeedShortName} provides {AnsibleCodeBot} in Service Preview, that you can deploy to your GitHub account. 
* {AnsibleCodeBot} is supported on the following GitHub versions:
** GitHub.com
** GitHub Enterprise Cloud
====

The following examples are code recommendations that the {AnsibleCodeBot} can suggest:

* Available alternatives for deprecated legacy syntax or implementation patterns
* Module version changes and updates, such as:
** Adding any new required parameters
** Flagging deprecated parameters
** Removing unused parameters
* Applying YAML best practices
* Adding comment blocks
* Fixing casing issues in name fields

include::modules/proc_install-code-bot.adoc[leveloffset=+1]
include::modules/proc_configure-repo-scan.adoc[leveloffset=+1]
include::modules/proc_manually-scan-repo.adoc[leveloffset=+1]

[[ansible-code-bot-duplicate-pr]]
== How {AnsibleCodeBot} handles duplicate pull requests

* If {AnsibleCodeBot} has created a pull request on the latest commit default branch, it does not scan the repository. The bot skips scanning the repository because the pull request was committed on the latest default branch, and no new commit was made after that pull request. 

* If there is an existing pull request that is not on the latest commit default branch, Ansible code bot does a pull request difference to compare the changes in both the branches. The following scenarios are possible:
** *There is no difference in the existing and new scan results*: Ansible code bot does not push the scan results as a new pull request. 
** *There are differences found in the existing and the new scan results*: {AnsibleCodeBot} creates a new pull request. The newly-created pull request does not close the existing pull request, against which the pull request difference was noted. This behavior makes it easier for the repository administrator to review only the latest pull request created by the {AnsibleCodeBot}, and the administrator can avoid reviewing the older pull requests created by the bot. If required, the administrator can close the older pull requests.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

