ifdef::context[:parent-context: {context}]

:_content-type: ASSEMBLY

[id="installing-ansible-vscode-extension_{context}"]
= Install and configure the Ansible VS Code extension

:context: installing-ansible-vscode-extension

[role="_abstract"]
{LightspeedFullName} is integrated with the Ansible Visual Studio (VS) Code extension in VS Code. The Ansible VS Code extension, with {LightspeedShortName} features enabled, automatically collects recommendations, usage telemetry, and Ansible YAML file state through automated events. 

To access {LightspeedShortName}, all Ansible users must install and configure the Ansible VS Code extension in their VS Code. The Ansible VS Code extension uses the Ansible-specific IBM watsonx Granite model configured in the {LightspeedShortName} administrator portal as the default mode for all users in your organization. 

== Connectivity requirements
To generate code recommendations, the Ansible Lightspeed service in Visual Studio (VS) Code editor requires access to the following outbound domain:

* https://c.ai.ansible.redhat.com

The outbound connections are encrypted on TCP protocol port 443.

include::modules/proc_install-vscode-extension.adoc[leveloffset=+1]
include::modules/proc_configure-vscode-extension.adoc[leveloffset=+1]
include::modules/proc_login-vscode-extension.adoc[leveloffset=+1]
include::modules/proc_log-out-of-portal.adoc[leveloffset=+1]
