ifdef::context[:parent-context: {context}]

:_content-type: ASSEMBLY

[id="logging-in-out-portal_{context}"]

= Logging in and out of the Ansible Lightspeed portal

:context: logging-in-out-lightspeed-portal

[role="_abstract"]

By default, all Ansible users within an organization that has a trial or paid subscription to both {PlatformNameShort} and {ibmwatsonxcodeassistant} can access {LightspeedShortName}.

You can access Ansible Lightspeed through the link:https://c.ai.ansible.redhat.com/[Ansible Lightspeed portal]. After you enter your {RHSSO} ({RHSSOshort}) account credentials, your account is authenticated and access is granted. Your assigned user role is displayed on the login screen of Ansible Lightspeed portal. 

.User login scenarios
[cols="50%,50%",options="header"]
|====
| *Scenario* | *Result*
|You are a {RHSSOshort} user. +
NOTE: This is the typical scenario for accessing as {LightspeedShortName} as an Ansible user.| You are routed to the {LightspeedShortName} paid commercial offering.
|You are a {RHSSOshort} user, but your organization administrator has not configured {LightspeedShortName} to connect with {ibmwatsonxcodeassistant}.| You are routed to the {LightspeedShortName} paid commercial offering with a message that your organization administrator has not configured a model for your organization.
|You are a {RHSSOshort} user but your organization does not have a trial or paid subscription to either {PlatformNameShort} or {ibmwatsonxcodeassistant}.|<AWAITING INFO. ABOUT RESULT>.
|====

include::modules/proc_log-into-portal.adoc[leveloffset=+1]
include::modules/proc_log-out-of-portal.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

