ifdef::context[:parent-context: {context}]

:_content-type: ASSEMBLY

[id="requesting-task-recommendations_{context}"]

= Requesting Task Recommendations

:context: requesting-task-recommendations

[role="_abstract"]
Ansible Lightspeed is integrated into Visual Studio (VS) Code through an Ansible VS Code extension. You can access Ansible Lightspeed through the Ansible VS Code extension, and get code recommendations for your existing Ansible content. 

The Ansible code bot scans existing content collections, roles, and playbooks in Git repositories, and proactively creates pull requests whenever best practices or quality improvement recommendations are available. The bot automatically submits pull requests to the repository, which proactively alerts the repository owner to a recommended change to their content. You can configure Ansible code bot to scan your existing Git repositories (both public and private), as well as repositories from {Galaxy}. 

Your organization must have a valid {LightspeedFullName} subscription to use Ansible code bot. 

include::modules/con_overview-and-best-practices.adoc[leveloffset=+1]
include::modules/proc_single-task-recs.adoc[leveloffset=+1]
include::modules/proc_multi-task-recs.adoc[leveloffset=+1]
include::modules/proc_view-training-matches.adoc[leveloffset=+1]
include::modules/proc_provide-feedback.adoc[leveloffset=+1]



ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

