:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: lightspeed-intro

[id="getting-started-lightspeed_{context}"]

= Quick start for administrators

:context: getting-started-lightspeed

[role="_abstract"]

This section shows how to get started with {LightspeedShortName} as an administrator.

Administrators can leverage {LightspeedShortName}'s powerful automation capabilities to streamline system management tasks, reduce human error, and maintain consistency across complex environments. {LightspeedShortName} helps administrators and enables developers to work more efficiently, improving productivity and the overall quality of their work.

As an organization administrator, perform the following tasks to set up and manage {LightspeedShortName} for your organization:

. Choose and configure your deployment
. Administer the Ansible Lightspeed service

== Choose and configure your deployment

As an organization administrator, you can set up a {LightspeedShortName} cloud service, as an on-premise deployment, or as a hybrid deployment. 

Configure the {LightspeedShortName} cloud service or on-premise deployment and connect it to your {ibmwatsonxcodeassistant} instance. You can also set up a hybrid deployment, wherein {LightspeedShortName} is an on-premise deployment, while {ibmwatsonxcodeassistant} model is a cloud deployment.

You must have a trial or paid subscription to both {PlatformName} and {ibmwatsonxcodeassistant}.

[role="_additional-resources"]
.Additional resources

* xref:configure-lightspeed-cloud-service_set-up-lightspeed[Setting up the cloud service] 
* xref:configuring-lightspeed-onpremise_lightspeed-user-guide[Setting up an on-premise or hybrid deployment]

== Administer the Ansible Lightspeed Service

As an organization administrator, you can manage the Ansible Lightspeed service after deploying {LightspeedShortName} cloud service or on-premise deployment.

Perform one of the following tasks:

* Log in to the Ansible Lightspeed admin portal
+
Use the Ansible Lightspeed admin portal to access and manage the Ansible Lightspeed service.

* View and manage the Admin dashboard telemetry data
+
View the operational telemetry and Admin dashboard telemetry data from the Ansible Lightspeed Admin dashboard. If you no longer want to collect the telemetry data for your organization, you can disable the Admin dashboard telemetry.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
