[allowlist]
  description = "Documentation contains example secrets and passwords"
  paths = [
    "titles/controller/administration/administration.html"
    "titles/controller/controllerapi/controllerapi.html"
    "titles/controller/quickstart/quickstart.html"
    "titles/controller/release-note/release-note.html"
    "titles/controller/upgrade-migration/upgrade-migration.html"
    "titles/controller/user-guide/user-guide.html"
  ]