= Red Hat Ansible Lightspeed with IBM watsonx Code Assistant Documentation

`lightspeed-latest` is the branch for Lightspeed documentation.

== Contributing to Lightspeed documentation

. Checkout a new topic branch from the `lightspeed-latest` branch:

  git fetch upstream
  git checkout -b aap-123

. Make the required modifications in your topic branch.
. Stage and commit your topic branch:

  git add filename.adoc
  git commit -m "Commit message for aap-123"

. Push your local topic branch to your fork:

  git push origin HEAD

. Create a PR to the upstream `lightspeed-latest` branch from the topic branch on your fork.
. Add the Lightspeed label to your PR.
. If you wish to make further changes, add the Draft label to your PR.
. When your PR is ready for review, remove the Draft label and add the `Ready for review` label
. Request a review from SMEs and the AAP docs team.
. Implement the changes suggested in the reviews. Add the `Peer review done` label.
. Request a merge from the AAP docs team.
. After your PR is merged, delete your topic branch from your fork.
. Delete your local topic branch:

  git checkout <another-branch>
  git branch -D aap-123

== Repository Organization

----
├── aap-common
│   ├── assembly-aap-common.adoc
│   ├── external-site-disclaimer.adoc
│   ├── making-open-source-more-inclusive.adoc
│   └── providing-direct-documentation-feedback.adoc
├── archive
│   ├── archived-assemblies
│   │   └── archived-assemblies.adoc
│   ├── archived-images
│   │   └── archived-images.adoc
│   ├── archived-modules
│   │   └── archived-modules.adoc
│   └── archived-titles
│       └── archived-titles.adoc
├── assemblies
│   ├── assembly-lightspeed-intro.adoc
│   └── modules -> ../modules
├── attributes
│   └── attributes.adoc
├── images
│   ├── copy.png
│   ├── magnify.png
│   └── search-icon.png
├── modules
│   └── con-lightspeed-about.adoc
├── snippets
│   └── assembly-rn-template.adoc
└── titles
    ├── lightspeed-release-notes
    │   ├── aap-common -> ../../aap-common
    │   ├── assemblies -> ../../assemblies
    │   ├── attributes -> ../../attributes
    │   ├── docinfo.xml
    │   ├── images -> ../../images
    │   └── master.adoc
    └── lightspeed-user-guide
        ├── aap-common -> ../../aap-common
        ├── assemblies -> ../../assemblies
        ├── attributes -> ../../attributes
        ├── docinfo.xml
        ├── images -> ../../images
        └── master.adoc
----


== Setting up your repository

Prerequisites:

* You must have a GitHub account.
* You must have link:https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account[set up an SSH key for your GitHub account].

Procedure:

. Fork the repository.

   From the main page of the link:https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation[GitHub repository], click btn[Fork] in the upper right corner.

. Clone the forked repository locally.

-----
$ git clone git@github.com:<username>/red-hat-ansible-automation-platform-documentation.git
-----

   If this command fails, be sure that you have link:https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account[set up an SSH key for GitHub].

. Navigate to the `red-hat-ansible-automation-platform-documentation` directory.

. Set the upstream remote repository.

 -----
 $ git remote add -f upstream git@github.com:RedHatInsights/red-hat-ansible-automation-platform-documentation.git
 -----


== Documentation style

=== Authoring modularly structured documentation

the documentation follows a link:https://redhat-documentation.github.io/modular-docs/[modular-based content model], providing a structure for writing and presenting user-story-based documentation. User-story-based documentation attempts to address the reader's needs more than focusing on feature-based documentation. This is accomplished using a set of templates for concepts, references, procedures and assemblies. Templates can be found link:https://github.com/redhat-documentation/modular-docs/tree/master/modular-docs-manual/files[here].

=== Red Hat Documentation Asciidoc Mark-up Conventions

Red Hat Ansible Automation Platform documentation is written in Asciidoc. See link:https://redhat-documentation.github.io/asciidoc-markup-conventions/[Red Hat Documentation Asciidoc Mark-up Conventions] to learn more about implementing Asciidoc in your writing.

=== Red Hat product documentation style conventions

The Red Hat Customer Content Services team uses the link:https://redhat-documentation.github.io/supplementary-style-guide/[Red Hat supplementary style guide for product documentation] and The IBM Style Guide as its primary sources for technical writing conventions and style guidelines. Refer first to the Red Hat supplementary style guide for product documentation for style guidance and conventions. If a topic is not included there, it means we follow the convention as established in the IBM Style Guide.

