[id="eda-custom-credential-types"]

= Custom credential types

As a system administrator, you can define a custom credential type in a standard format by using a YAML or JSON-like definition. You can define a custom credential type that works in ways similar to existing credential types. For example, a custom credential type can inject an API token for a third-party web service into an environment variable, for your rulebook or custom inventory script to consume.

Each credential type displays its own unique configurations in the Input Configuration field and the Injector Configuration field, if applicable. Custom credentials support the following ways of injecting their authentication information:

* Environment variables
* Ansible extra variables
* File-based templating, which means generating .ini or .conf files that contain credential values

You can attach one SSH and multiple cloud credentials to a job template. Each cloud credential must be of a different type. Only one of each type of credential is permitted. Vault credentials and machine credentials are separate entities.

[NOTE]
====
* When creating a new credential type, you must avoid collisions in the `extra_vars`, `env``, and file namespaces.
* Environment variable or extra variable names must not start with *ANSIBLE_* because they are reserved.
* You must have System administrator (superuser) permissions to be able to create and edit a credential type and to be able to view the *Injector configuration* field.
====

When you customize your own credential types, they will display on the Credential Types page along with a list of built-in credential types.

Each credential type displays its own unique configurations in the Input Configuration and the Injector Configuration fields, if applicable. Both YAML and JSON formats are supported in the configuration fields.
//Note from J. Self: REVIEWERS, please confirm the Note above along with the paragraph about attachning one SSH and multiple clouds to a job template. I copied this from automation controller content, but not entirely sure it's relevant to EDA.

[discrete]
== Input Configuration

The Input configuration has two attributes:

* fields - a collection of properties for a credential type.
* required - a list of required fields.

Fields can have multiple properties, depending on the credential type you select.

.Credential Types Field Properties
[cols="a,a,a"]
|===
| Fields | Description | Mandatory (Y/N)

h| id | Unique id of the field; must be a string type and stores the variable name | Yes

h| type | Can be string or boolean type | No, default is string

h| label | Used by the UI when rendering the UI element | Yes

h| secret | Will be encrypted | No, default false

h| multiline | If the field contains data from a file the multiline can be set to True | No, default false

h| help_text | The help text associated with this field | No

|===

[discrete]
== Injector Configuration

You can use the Injector configuration field to take the fields from input configuration field and map them into `extra_vars` that can be sent to ansible-rulebook when running the activation. The Injector currently only supports `extra_vars`. 

Injectors enable you to tailor the fields so that they can be injected into a rulebook as `extra_vars`, which cannot have duplicate keys at the top level. If you have two sources in a rulebook that both require a parameter called username and password, the injectors, along with the rulebook, help you tailor the arguments for each source.
