:_mod-docs-content-type: CONCEPT

:_mod-docs-content-type: <CONCEPT>
[id="eda-custom-credential-types"]

= Create custom credentials for {EDAName}

[role="_abstract"]
Create custom credential types (via JSON/YAML) to define unique security fields and logic, enabling support for proprietary event sources or specialized authentication. 

Each credential type displays its own unique configurations in the *Input Configuration* and the *Injector Configuration* fields, if applicable. Both YAML and JSON formats are supported in the configuration fields. 

Custom credentials support Ansible extra variables as a means of injecting their authentication information. 

You can attach one or more cloud, vault, and {PlatformName} credential types to a rulebook activation. 

[NOTE]
====
* When creating a new credential type, you must avoid collisions in the `extra_vars`.
* Extra variable names must not start with *EDA_* because they are reserved.
* You must have System administrator (superuser) permissions to be able to create and edit a credential type and to be able to view the *Injector configuration* field.
====

When you customize your own credential types, they display on the Credential Types page along with a list of built-in credential types.

