
:_mod-docs-content-type: CONCEPT
[id="event-streams"]

= Event streams

[role="_abstract"]
Event streams can send events from remote systems to {EDAcontroller}. In a typical set-up, a server sends data to an event stream over the internet to an {EDAName} event stream receiver. When the data comes over the internet, the request must be authenticated. Depending on the webhook vendor or remote system, the authentication method could differ.

{EDAcontroller} supports six different event stream types.
 
.Event Stream Types
[cols="a,a,a"]
|===
| Type | Description | Vendors

h| HMAC | Hashed Message Authentication Code (HMAC). Uses a shared secret between {EDAcontroller} and the vendors webhook server. This guarantees message integrity. | Github

h| Basic Authentication | Uses HTTP basic authentication. | Datadog, Dynatrace

h| Token Authentication | Uses Token Authentication. Usually the HTTP Header is *Authorization* but some vendors like Gitlab use *X-Gitlab-Token*. | Gitlab, ServiceNow

h| OAuth2 | Uses Machine-to-Machine (M2M) mode with a grant type called *client credentials*. The token is opaque. | Dynatrace

h| OAuth2 with JWT | Uses M2M mode with a grant type called *client credentials*. The token is JSON Web Token (JWT). | Datadog

h| ECDSA | Elliptic Curve Digital Signature Algorithm | SendGrid, Twilio

h| Mutual TLS | Requires the vendor's CA certificate to be loaded into the Envoy proxy, which can be delivered via {EDAName} credentials at runtime. This supports non-repudiation. | PagerDuty
|===

{EDAcontroller} also supports four other specialized event streams that are based on the six basic event stream types: 

* GitLab Event Stream
* GitHub Event Stream
* ServiceNow Event Stream
* Dynatrace Event Stream

These specialized types limit the parameters you use by adding default values. For example, the GitHub Event Stream is a specialization of the HMAC Event Stream with many of the fields already populated. After the GitHub Event Stream credential has been saved, the recommended defaults for the GitHub Event Stream are displayed.