:_mod-docs-content-type: PROCEDURE
[id="eda-build-a-custom-decision-environment"]

= Building a custom decision environment for {EDAName}

[role="_abstract"]
Customize a decision environment container image to ensure your rulebook activations run with the precise, custom-maintained collections and dependencies they require.

.Prerequisites

* {PlatformNameShort} > = 2.5
* {EDAName}
* {Builder} > = 3.0

[IMPORTANT]
====
* Use the correct {EDAcontroller} decision environment in {PlatformNameShort} to prevent rulebook activation failure.

** If you want to connect {EDAcontroller} to {PlatformNameShort} 2.4, you must use `registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel9:latest`
** If you want to connect {EDAcontroller} to {PlatformNameShort} {PlatformVers}, you must use `registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel9:latest`
====

.Procedure

. Use `de-minimal` as the base image with {Builder} to build your custom decision environments. 
This image is built from a base image provided by Red Hat at link:https://catalog.redhat.com/software/containers/ansible-automation-platform-25/de-minimal-rhel9/650a5672a370728c710acaab[{PlatformNameShort} minimal decision environment].  
+
The following is an example of the {Builder} definition file that uses `de-minimal` as a base image to build a custom decision environment with the ansible.eda collection:
+

----
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel9:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
  python_interpreter:
    package_system: "python39"

options:
  package_manager_path: /usr/bin/microdnf
----

. Optional: If you need other Python packages or RPMs, add the following to a single definition file:
+

----
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel9:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
  python:
    - six
    - psutil
  system:
    - iputils [platform:rpm]
  python_interpreter:
    package_system: "python39"

options:
  package_manager_path: /usr/bin/microdnf
----
