:_mod-docs-content-type: PROCEDURE
[id="eda-example-replace-sources-attach-event-streams"]

= Replace sources and attach event streams to activations

Attaching an event stream to a rulebook activation links your incoming GitHub data to specific automation rules. This process involves selecting a project and updating the event source to subscribe to the previously configured event stream.

.Prerequisites
* Ensure that your Projects have been set up properly. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html-single/using_automation_decisions/index#eda-set-up-new-project[Setting up a new project].

.Procedure

. From the {PlatformNameShort} navigation panel, select {MenuADRulebookActivations}.
. Click btn:[Create rulebook activation] to create a rulebook for events on an application repository for Linux servers.
. In the *Name* field, enter the name of your rulebook (for example, <_Your_rulebook_activation_>).
. For your *Organization*, select *Default* from the list.
. From the *Project* list, select the project with access to your rulebooks.
. In the *Rulebook* field, select the )rulebook associated with your project (for example, <_Your-rulebook.yml_>).
. In the *Event streams* field, click the gear icon to select which event stream the rulebook needs to subscribe to. The Event streams window is displayed.
. In the required *Rulebook source* field, replace an `ansible.builtin.webhook` or compatible custom source with the desired event stream. This modifies the activation only, while leaving your filters intact.
. Select <_Your_event_stream_> from the list of event streams that you created.
. Click *Save* to save your event stream.
. Next to the *Credential* field, click the *Search* icon to access {ControllerName} and connect with job templates and workflows. The *Select credential* message is displayed.
. Select the *AAP* credential and click *Confirm*.
. Select the appropriate *Decision Environment* from the list.
. Click *Create rulebook activation*. The activation status is displayed (if successful, the *Running* status displays).
. Repeat the following steps to create an additional rulebook activation using the same process as your first activation: 
.. In the *Event streams* field, click the gear icon to select which event stream the rulebook needs to subscribe to.
.. Select the *Repo Event Stream* from the list of event streams that you created.
.. Click *Save* to save your event stream.
.. Click *Create rulebook activation* to save the configuration and start the rulebook. 

.Results
Now, there are two rulebook activations running and you can commit some code to one of your repositories. An event has been received and routed to your rulebooks.


