:_mod-docs-content-type: PROCEDURE
[id="eda-create-event-stream-credential"] 

= Create an event stream credential

[role="_abstract"]
Create a credential to establish the authentication mechanism (like basic auth or HMAC) required for external systems to securely send events to an event stream.

.Prerequisites

* Each event stream must have exactly one credential.

.Procedure

. Log in to the {PlatformNameShort} Dashboard.
. From the navigation panel, select {MenuADCredentials}.
. Click btn:[Create credential].
. Insert the following:
+
Name:: Insert the name.
Description:: This field is optional.
Organization:: Click the list to select an organization or select *Default*.
Credential type:: Click the list to select your Credential type.
+
[NOTE]
====
When you select the credential type, the *Type Details* section is displayed with fields that are applicable for the credential type you selected. 
==== 

Type Details:: Add the requested information for the credential type you selected. For example, if you selected the GitHub Event Stream credential type, you are required to add an HMAC Secret (symmetrical shared secret) between {EDAcontroller} and the remote server.

. Click btn:[Create credential].

.Results
The Details page is displayed. From there or the *Credentials* list view, you can edit or delete it.
