:_mod-docs-content-type: PROCEDURE
[id="eda-example-github-eventstream-cred"]

= Create a GitHub event stream credential

[role="_abstract"]
Creating a GitHub event stream credential establishes the necessary authentication for the {PlatformName} controller to securely access your event source. This credential ensures that only authorized webhook payloads trigger your rulebook activations. 

.Procedure

. Log in to {PlatformNameShort}.
. Select {MenuADCredentials}.
. Click btn:[Create credential].
. Insert the following:
+
Name:: Enter the name (for example, [_Your_GitHub_Credential_Name_]).
Description:: This field is optional, but for this user scenario, enter a description (for example, [_GitHub credential_]).
Organization:: Select *Default* from the list.
Credential type:: From the list, select *GitHub Event Stream*.
Type Details / HMAC Secret:: Enter a secret value and store for future use when you link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/{PlatformVers}/html/using_automation_decisions/simplified-event-routing#eda-config-remote-sys-to-events[configure a GitHub webhook].
+
. Click *Create credential* to save your credential.