[id="eda-copy-rulebook-activation"]

= Copying a rulebook activation

When setting up a new rulebook activation with field inputs that are similar to one of your existing rulebook activations, you can use the *Copy rulebook activation* feature instead of manually entering input into each field. While setting up rulebook activations can be a lengthy process, the ability to copy the required fields from an existing activation saves time and, in some cases, reduces the possibility of human error.

.Procedure

. On the Rulebook Activations page, click the *More Actions* icon *{MoreActionsIcon}* on the row of the activation you want to copy. The More Actions list is displayed with three options:
** *Restart rulebook activation*
** *Copy rulebook activation*
** *Delete rulebook activation*
. Select btn:[Copy rulebook activation]. 
+
A message is displayed: "<Name of rulebook activation 1> copied." Initially, the newly copied activation is displayed as disabled on the Rulebook Activations page with the same name as the original activation followed by a time stamp in 24-hour format (for example, <Name of rulebook activation 1> @ 18:43:27).
+
[IMPORTANT]
====
The original rulebook activation continues to run after you have copied it. If you try to enable the copied activation without editing the fields (including the Name field) to distinguish it from the original, a message is displayed reminding you that the rulebook activation was copied from an original, and enabling it might fail or result in duplicate jobs and other complications.
====
 
. Before you run the copied rulebook activation, edit the fields by completing the following: 
.. Next to the copied rulebook activation, click the *Edit* icon. This takes you to the Edit form. 
.. Edit the desired fields.
+
[NOTE]
====
Ensure that you have given your newly copied activation a meaningful *Name* that distinguishes it from the original activation.
====
. Toggle the btn:[Enable rulebook activation] button to the on position. 
. After confirming all of your edits are complete, click btn:[Save rulebook activation].
+
This initiates the rulebook activation, and if it runs successfully, the status changes to *Running* or *Completed*.
