:_mod-docs-content-type: PROCEDURE
[id="eda-example-configure-remote-sys"]

= Configuring your remote system to send events

Complete the following procedure to configure your remote system to send events by setting up a webhook in your GitHub repository.

.Procedure

. Go to your GitHub account to configure your event source.
. Click *Your profile name → Your repositories* and select the repository you want to configure.
. Navigate to *Settings* in the tool bar.
. In the left *General* navigation pane, select *Webhooks*, then click btn:[Add webhook] to create a webhook in your GitHub repository that will send events to your event stream.*
. In the *Payload URL* field, paste the event stream URL that is displayed in the details of your event stream.
. In the *Content type* field, change the content type to *application/json* for your payload.
. In the *Secret* field, add your secret from your event stream credential you created earlier.
+
[NOTE]
====
If you are using a test environment or SSL certifications, under SSL verification, select the *Disable* option to ensure your webhook connects successfully.  
====
. Click *Add webhook* to save your configuration.
. Now that the webhook has been created, return to {PlatformNameShort}.
