[id="eda-duplicate-credential"]

= Duplicating a credential

When setting up a new credential that requires similar field inputs as your existing credentials, you can use the Duplicate credential feature in the Details tab to copy required field selections and input. While setting up credentials can be a lengthy process, the ability to duplicate those required fields helps save time and eliminate the possibility of errors in some cases.

.Procedure

. Select a credential from the Credentials list page.
. Click btn:[Duplicate credential] button at the top of the Details tab. A message is displayed confirming that your selected credential has been copied: "<Name of credential> copied."
. Click the btn:[Back to credentials] tab and select the duplicate of the credential you just copied. 
The duplicate credential is displayed with the same name as the credential you copied along with a time stamp in a 24-hour format. 
. Edit the appropriate details to distinguish the new credential.
. After updating the new credential, click btn:[Save credential].
