:_mod-docs-content-type: PROCEDURE
[id="eda-set-up-new-decision-environment"]

= Setting up a new decision environment

[role="_abstract"]
You can import a decision environment into your {EDAcontroller} using a default or custom decision environment. 

.Prerequisites

* You have set up a credential, if necessary.
For more information, see the link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credentials#eda-set-up-credential[Setting up credentials] section.
* You have pushed a decision environment image to an image repository or you chose to use the `de-minimal` image located in link:http://registry.redhat.io/[registry.redhat.io].

.Procedure

. Log in to {PlatformNameShort}.
. Navigate to {MenuADDecisionEnvironments}.
. Click btn:[Create decision environment].
. Insert the following:
+
Name:: Insert the name.
Description:: This field is optional.
Organization:: Select an organization to associate with the decision environment.
Image:: This is the full image location, including the container registry, image name, and version tag.
Credential:: This field is optional. This is the credential needed to use the decision environment image.
. Select btn:[Create decision environment].

.Results
Your decision environment is now created and can be managed on the *Decision Environments* page.

After saving the new decision environment, the decision environment's details page is displayed.
From there or the *Decision Environments* list view, you can edit or delete it.
