:_mod-docs-content-type: PROCEDURE
[id="eda-duplicate-credential"]

= Duplicate a credential

[role="_abstract"]
Use the *Duplicate credential* feature to rapidly generate a new credential based on an existing one, saving configuration time and reducing potential errors.

.Procedure

. On the Credentials list page, click the name of the credential that you want to duplicate. This takes you to the *Details* tab of the credential.
. Click btn:[Duplicate credential] in the top right of the Details tab. 
+
[NOTE]
====
You can also click the btn:[Duplicate credential] icon next to the desired credential on the Credentials list page.
====
A message is displayed confirming that your selected credential has been duplicated: "<Name of credential> duplicated." 
. Click the btn:[Back to credentials] tab to view the credential you just duplicated. 
+
The duplicated credential is displayed with the same name as the original credential followed by a time stamp in 24-hour format (for example, *<Name of credential> @ 17:26:30*). 
. Edit the details you prefer for your duplicated credential.
. Click btn:[Save credential].