[id="eda-build-a-custom-decision-environment"]

= Building a custom decision environment for {EDAName}

Decision Environments are {ExecEnvShort}s tailored towards running Ansible Rulebooks.

Similar to {ExecEnvShort}s that run Ansible rulebooks for {ControllerName}, decision environments are designed to run rulebooks for {EDAcontroller}.

You can create a custom decision environment for {EDAName} that provides a custom maintained or third-party event source plugin that is not available in the default decision environment.

.Prerequisites

* {PlatformNameShort} > = 2.5
* {EDAName}
* {Builder} > = 3.0

.Procedure

* Add the `de-supported` decision environment. 
This image is built from a base image provided by Red Hat called `de-minimal` at link:https://catalog.redhat.com/software/containers/ansible-automation-platform-24/de-supported-rhel9/6449642e3993031ccdf4cf19[{PlatformNameShort} supported decision environment].

+
[NOTE]
====
Use `de-minimal` as the base image with {Builder} to build your custom decision environments.
====

[IMPORTANT]
====
* Use the correct {EDAcontroller} decision environment in {PlatformNameShort} {PlatformVers} to prevent rulebook activation failure.

** If you want to connect {EDAcontroller} to {PlatformNameShort} 2.4, you must use link:https://catalog.redhat.com/software/containers/ansible-automation-platform-24/de-supported-rhel9/6449642e3993031ccdf4cf19[Ansible Automation Platform supported decision environment]
** If you want to connect {EDAcontroller} to {PlatformNameShort} {PlatformVers}, you must use link:https://catalog.redhat.com/software/containers/ansible-automation-platform-25/de-supported-rhel9/650a5674ad524b664b693729[Ansible Automation Platform supported execution environment]
====

The following is an example of the {Builder} definition file that uses `de-minimal` as a base image to build a custom decision environment with the ansible.eda collection:
-----
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel8:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
  python_interpreter:
    package_system: "python39"

options:
  package_manager_path: /usr/bin/microdnf
-----

Additionally, if you need other Python packages or RPMs, you can add the following to a single definition file:
-----
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel8:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
  python:
    - six
    - psutil
  system:
    - iputils [platform:rpm]
  python_interpreter:
    package_system: "python39"

options:
  package_manager_path: /usr/bin/microdnf
-----
