:_mod-docs-content-type: PROCEDURE
[id="eda-edit-rulebook-activation"]

= Editing a rulebook activation

[role="_abstract"]
You can edit a rulebook activation after you have created or run it to correct input for fields (log levels, Restart policy, turn auditing off or on, and the like) or  help mitigate issues caused by failure.

.Procedure

. On the Rulebook Activations page, next to the activation you want to edit, toggle the btn:[Rulebook Activation enabled] button to the off position first to disable the activation.
+
The *Disable rulebook activations* message is displayed asking you to confirm that you want to disable the activation.
. Select the *Yes, I confirm that I want to disable these <1> rulebook activations* checkbox and click btn:[Disable rulebook activations]. 
. Next to the rulebook activation, click the *Edit* icon. This takes you to the Edit form.
+
[NOTE]
====
You can also access the *Edit* feature by clicking the rulebook activation on the Rulebook Activations page, toggling the btn:[Rulebook activation enabled] button to the off position, confirming that you want to disable the activation, and clicking the btn:[Edit rulebook activation] button on the top right of the page to access the Edit form.
====
. Edit the desired fields.
+
[NOTE]
====
If you prefer to run your activation immediately, you can toggle the btn:[Rulebook activation enabled] button to the on position, and then save your changes.
====
. Click btn:[Save rulebook activation].

.Results
This takes you back to the Rulebook Activations page.
