:_mod-docs-content-type: PROCEDURE

[id="troubleshoot-job-resolve-module"]
= Issue - Jobs are failing with “ERROR! couldn’t resolve module/action” error message

[role="_abstract"]
Jobs are failing with the error message “ERROR! couldn't resolve module/action 'module name'. This often indicates a misspelling, missing collection, or incorrect module path”.

This error can happen when the collection associated with the module is missing from the {ExecEnvShort}.

The recommended resolution is to create a custom {ExecEnvShort} and add the required collections inside of that {ExecEnvShort}. For more information about creating an {ExecEnvShort}, see link:{URLBuilder}/assembly-using-builder[Using {Builder}] in _{TitleBuilder}_.

Alternatively, you can complete these steps:

.Procedure

. Create a `collections` folder inside of the project repository.

. Add a `requirements.yml` file inside of the `collections` folder and add the collection:
+
[subs="+quotes"]
----
collections: 
- <collection_name>
----
