:_mod-docs-content-type: PROCEDURE

[id="troubleshoot-upgrade-issues"]
= Issue - {ControllerName} API connection fails after upgrade with load balancer

[role="_abstract"]
When upgrading from {PlatformNameShort} 2.4 to {PlatformVers}, the upgrade completes successfully. 
However, connections to the {Gateway} URL fail if you are using {ControllerName} behind a load balancer. 

You see this error message in the logs: 

`Error connecting to Controller API`

.Procedure

. To resolve this issue, perform the following tasks for all controller hosts:

.. For each controller host, add the {Gateway} URL as a trusted source in the `CSRF_TRUSTED_ORIGIN` setting in the *settings.py* file.
+
For example, if you configured the {Gateway} URL as `\https://www.example.com`, you must add that URL in the *settings.py* file too as shown:
+
----
CSRF_TRUSTED_ORIGINS = ['https://appX.example.com:8443','https://www.example.com']
----

.. Restart each controller host by using the `automation-controller-service restart` command so that the URL changes are implemented. For the procedure, see link:{URLControllerAdminGuide}/controller-start-stop-controller[Start, stop, and restart {ControllerName}] in _{TitleControllerAdminGuide}_. 
