:_mod-docs-content-type: PROCEDURE

[id="troubleshoot-job-timeout"]
= Issue - Jobs failing with timeout waiting for privilege escalation prompt

[role="_abstract"]
This error can happen when the timeout value is too small, causing the job to stop before completion. The default timeout value for connection plugins is `10`. 

To resolve the issue, increase the timeout value by completing one of the following methods. 

[NOTE]
====
The following changes will affect all of the jobs in {ControllerName}. To use a timeout value for a specific project, add an `ansible.cfg` file in the root of the project directory and add the `timeout` parameter value to that `ansible.cfg` file.
====

.Procedure

* Increase the timeout value by using one of the following methods:

** *Add ANSIBLE_TIMEOUT as an environment variable in the {ControllerName} UI:*
+
... Go to {ControllerName}.
... From the navigation panel, select menu:Settings[Jobs settings].
... Under *Extra Environment Variables* add the following:
+
----
{ 
"ANSIBLE_TIMEOUT": 60 
}
----
+

** *Add a timeout value in the [defaults] section of the ansible.cfg file:*
+
... Edit the `/etc/ansible/ansible.cfg` file and add the following:
+
----
[defaults]
timeout = 60
----
+

** *Run ad hoc commands with a timeout:*
+
... To run an ad hoc playbook in the command line, add the `--timeout` flag to the `ansible-playbook` command, for example:
+
[subs="+quotes"]
----
# ansible-playbook --timeout=60 <your_playbook.yml>
----
+

//Commenting out as no downstream alternative [AAP-57435]
//[role="_additional-resources"]
//Additional resources
//
//* link:https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-timeout[DEFAULT_TIMEOUT]
