// Module file name: con-motivations-for-migrating-to-enterprise-topology.adoc
:_mod-docs-content-type: CONCEPT
[id="motivations-for-migrating-to-enterprise-topology_{context}"]
= Motivations for migrating to an {EnterpriseTopology}

[role="_abstract"]
Growth topologies model a minimal {PlatformNameShort} installation.
Growth topologies are suited to proof-of-concept deployments, small-scale environments, or preliminary evaluations. Using a {GrowthTopology} simplifies initial setup for your {PlatformNameShort} deployment, but they have inherent limitations. 

== Inherent limitations of {GrowthTopologyPlural}

Growth topologies include single points of failure, such as a single {Gateway} , and other critical components, such as the control plane, execution plane, and web services.
These components often share resources on the same node, resulting in resource contention under increasing load.
As workloads grow, specific services, such as job processing or API responsiveness, can become bottlenecks due to colocation or single node capacity limits.
Consequently, {GrowthTopologyPlural} generally do not offer robust, high-availability capabilities.
For {VMBase} and containerized deployments of {PlatformNameShort}, you can marginally increase possible workloads by vertically scaling the virtual machines or physical hosts within the growth deployment.
However, vertical scaling capabilities within a {GrowthTopology} are limited.

== Use cases for migrating to an {EnterpriseTopology}

To scale beyond the limitations within {GrowthTopologyPlural}, you can migrate to an {EnterpriseTopology}.
Migrating to an {EnterpriseTopology} might be relevant in the following use cases:

* Vertically scaling a {GrowthTopology} becomes impractical due to cost or availability.
* The {GrowthTopology} cannot satisfy high availability and disaster recovery requirements.
* You must scale {PlatformNameShort} services independently, such as API handling, job execution, and database capacity.
* Workload demands consistently overwhelm the capacity of vertically scaled {GrowthTopologyPlural}.
* You require more complex network architectures, such as segmented networks.

== Recommended {EnterpriseTopology}

To maximize flexibility, resilience, and scalability, migrate to the {OCPShort}-based {EnterpriseTopology}.
This migration includes integration with an externally managed, enterprise-grade PostgreSQL database.
{OperatorBase} offers greater flexibility to scale individual services and adapt the deployment to specific requirements.
They also enhance the ability to scale the deployment up and down with reduced downtime and customize workload placement with labels, taints, tolerations, and topology constraints.
{OperatorBase} also benefits from resilience features, such as automatic service recreation if underlying worker nodes experience failure or resource exhaustion.