:_mod-docs-content-type: CONCEPT

[id="introduction"]

= Introduction

[role="_abstract"]

Users can integrate {Terraform} and {Vault} with {PlatformNameShort} to gain consistent configuration, accelerate deployment, and manage complex workflows.

== {Terraform}
The integration of {PlatformNameShort} and {Terraform} addresses common challenges such as managing disparate automation tools, ensuring consistent configuration across hybrid cloud environments and accelerating deployment cycles. While {Terraform} excels at Infrastructure as Code (IaC) for provisioning and de-provisioning cloud resources, {PlatformNameShort} is a versatile, all-purpose automation solution ideal for configuration management, application deployment, orchestrating complex IT workflows, and providing ongoing health checks, incident response, patching, and infrastructure optimization.

== {Vault}
{Vault} lets you centrally store and manage secrets securely. The {PlatformNameShort} certified `hashicorp.vault`` collection provides fully automated Key/Value V2 (KV2) secret lifecycle management for {Vault}. You can create, update, and delete secrets through playbooks.

[NOTE]
====
Although the `hashicorp.vault` and `hashicorp.terraform` collections work independently of each other and are designed for different tasks, you can use them together in advanced workflows.
====


