:_mod-docs-content-type: CONCEPT

[id="ansible-initiated-workflows"]

= Ansible-initiated workflows

[role="_abstract"]
After you set up authentication with {PlatformNameShort}, there are many possible Ansible-initiated workflows and many patterns can apply.

Some workflows to consider include:

* **Performing traditional infrastructure set up.** In this case, configure something in {PlatformNameShort} that {Terraform} cannot manage. For example, {PlatformNameShort} can set up the state backend for an initial run. Or use {PlatformNameShort} to set up initial cloud credentials or users to interact with a cloud provider's API. Then perform `terraform apply`.

* **Modifying infrastructure with {Terraform}.** First, turn off Ansible monitoring for the infrastructure that you are modifying. Then perform `terraform apply` with your changes. Finally, turn monitoring back on.

* **Automating `terraform apply` based on an event.** For example, you might want to trigger an event when a ServiceNow ticket is opened or a service catalog order is placed. Set up a webhook in the {PlatformNameShort} UI so that {Terraform} is able to receive the event.