:_mod-docs-content-type: PROCEDURE

[id="creating-custom-credential-type"]

= Creating a custom credential type

[role="_abstract"]

Administrators set up a custom credential type to facilitate authentication between {PlatformNameShort} and {Terraform}. This preparation helps ensure that credentials are provided automatically to the execution environment, eliminating the need to update playbooks manually.

Additionally, you can configure a custom credential for {Vault} to leverage the advanced features of both {Terraform} and {Vault} with {PlatformNameShort}. For information about using {Vault}, see Configuring {Vault} and Ansible.

.Prerequisites
* You must have a {Terraform} API token (TF_TOKEN) set up.
* Install the certified `hashi.terraform` collection from automation hub. (You need an Ansible subscription to access and download collections on Ansible automation hub.)

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select **{MenuAECredentialType}**.
. Click btn:[Create a credential type]. The **Create Credential Type** page opens and displays the **Details** tab.
. For the **Credential Type**, enter a name.
. In the **Input configuration** field, enter the following parameters and values:
+
----
fields:
   - id: token
   type: string
   label: token
   secret: true
----

. In the **Injector configuration** field, enter the TF token:
+
----
env:
TF_TOKEN:  ‘{{ token }}’
----

. To save your configuration, click **Create Credential Type** again. The new credential type is created.

.Next step

Creating a credential