:_mod-docs-content-type: PROCEDURE

[id="creating-custom-credential-type"]

= Create a custom credential type

[role="_abstract"]

Administrators set up a custom credential type to facilitate authentication between {PlatformNameShort} and {TerraformEnterpriseShortName} or {TerraformCloudShortName}. 

This preparation helps ensure that credentials are provided automatically to the execution environment, eliminating the need to update playbooks manually.

Additionally, you can configure a custom credential for {Vault} to leverage the advanced features of {TerraformEnterpriseShortName} or {TerraformCloudShortName} and {Vault} with {PlatformNameShort}.

.Prerequisites
* You must have a link:https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens#user-api-tokens[{Terraform} API token].
* Install the certified link:https://console.redhat.com/ansible/automation-hub/repo/published/hashicorp/terraform/[`hashicorp.terraform`] collection from {HubName}. (You need an Ansible subscription to access and download collections on {HubName}.)

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select **{MenuAECredentialType}**.
. Click btn:[Create credential type]. The **Create Credential Type** page opens and displays the **Details** tab.
. For the **Name** field, enter a credential type name.
. In the **Input configuration** field, enter the following parameters and values:
+
----
fields:
  - id: token
    type: string
    label: token
    secret: true
----

. In the **Injector configuration** field, enter the following configuration:
+
----
env:
  TF_TOKEN:  ‘{{ token }}’
----

. To save your configuration, click **Create Credential Type** again. The new credential type is created.

.Next step

link:{URLHashiGuide}/terraform-product#terraform-creating-credential[Creating a credential]