:_mod-docs-content-type: PROCEDURE

[id="configuring-config-version-module"]

= Configuring the `hashicorp.terraform.configuration_version` module

[role="_abstract"]

To migrate to the `hashicorp.terraform` collection, you must configure the `hashicorp.terraform.configuration_version` module. This module manages configuration versions in {TerraformEnterpriseShortName} or {TerraformCloudShortName}.

.Prerequisites

* Install the {PlatformNameShort} certified link:https://console.redhat.com/ansible/automation-hub/repo/published/hashicorp/terraform/[`hashicorp.terraform`] collection.
* Verify that a valid organization and workspace are correctly set up in {TerraformEnterpriseShortName} or {TerraformCloudShortName}.

.Procedure

. Replicate your automation tasks from the `cloud.terraform` modules.
+
**Example**
+
----
- name: Create configuration version with auto_queue_runs to false
  hashicorp.terraform.configuration_version:
   workspace_id: ws-1234
   configuration_files_path: "/usr/home/tf"
   auto_queue_runs: false
   tf_validate_certs: true
   poll_interval: 3
   poll_timeout: 15
   state: present
----

. Configure the following required parameters:
* **`workspace_id` or `workspace` + `organization`:** The workspace ID or the workspace name and organization where the configuration version will be created and the file will be uploaded (for `state: present`).

* **`configuration_files_path`:** The path where the required {TerraformEnterpriseShortName} or {TerraformCloudShortName} files will be uploaded to create a configuration version (for `state: present`). The module accepts two file types for `configuration_files_path`:
+
** **Directory:** Any folder containing {TerraformEnterpriseShortName} or {TerraformCloudShortName} files. The module auto-creates the .tar.gz file from all contents recursively.
+
** **.tar.gz Archive:** Pre-compressed gzip tarball. The module validates TAR format and gzip compression.

* **`configuration_version_id`:** The configuration version ID that will be archived (`state: archived`). This action deletes the associated uploaded .tar.gz file. Note the following:
+
** Only uploaded versions that were created using the API or CLI, have no active runs, and are not the current version for any workspace can be archived.
+
** When the `configuration_version_id` is unspecified, {TerraformEnterpriseShortName} or {TerraformCloudShortName} selects the latest approved `configuration_version_id` in the workspace.

* **auto_queue_runs:** Determines if {TerraformEnterpriseShortName} or {TerraformCloudShortName} automatically starts a run after the configuration upload (`true` by default) or requires manual initiation (`false`).

. Set additional link:https://console.redhat.com/ansible/automation-hub/repo/published/hashicorp/terraform/content/module/configuration_version/[optional parameters] as needed.

.Additional resources
* link:{URLHashiGuide}/terraform-product#terraform-migration-examples[Migration examples for `hashicorp.terraform` modules]
