:imagesdir: images
:numbered:
:toclevels: 1

:experimental:

include::attributes/attributes.adoc[]


// Book Title
= Using Event-Driven Ansible 2.5 with Ansible Automation Platform 2.4 

You can configure a new installation of {EDAcontroller} 1.1 with {ControllerName} 4.4 or 4.5, which is considered a general availability release fully supported by Red Hat. 
{ControllerNameStart} 4.4 and 4.5 were released as part of {PlatformNameShort} 2.4.

Upgrading to {EDAcontroller} 1.1 from an earlier release is unsupported at this time.

This means that you can install a new {EDAcontroller} 2.5 server and configure rulebook activations to execute job templates on an {PlatformNameShort} 2.4 {ControllerName}. 
With this interoperability support you can retain your existing {PlatformNameShort} 2.4 clusters and add {EDAcontroller} 2.5 to them. 
This gives you the option to upgrade your {PlatformNameShort} 2.4 cluster to {PlatformNameShort} 2.5 at a date that suits you, whilst giving you all the benefits of {EDAName} 2.5.

The installs are still two separate installs, in that you manage the {PlatformNameShort} 2.4 cluster with the {PlatformNameShort} 2.4 installer.
The {EDAName} 2.5 server is managed with the {PlatformNameShort} 2.5 installer.

This guide shows you how to install and configure {EDAName} 1.1 to work with {ControllerName} 4.4 or 4.5 for a Red Hat Package Manager (PM)-based installation. 

include::{Boilerplate}[]

//include::platform/assembly-container-based-install.adoc[leveloffset=+1]
//include::platform/assembly-operator-eda-controller-install.adoc[leveloffset=+1]
include::platform/assembly-RPM-eda-controller-install.adoc[leveloffset=+1]
include::platform/assembly-eda-controller-post-install.adoc[leveloffset=+1]
