:_mod-docs-content-type: CONCEPT

[id="out-of-scope"]
= Out of scope

[role="_abstract"]
Understand which {PlatformNameShort} components and configurations require manual recreation in the target environment and are not covered by the migration process.

The {TitleMigration} guide focuses on the core components of {PlatformNameShort}. The following items are currently out of scope for this migration process:

* {EDAName}: Configuration and content for {EDAName} must be manually recreated in the target environment.
* Instance groups: Instance group configurations must be manually recreated after migration.
* Hub content: Content hosted in {HubName} must be manually reimported or reconfigured.
* Custom Certificate Authority (CA) for receptor mesh: Custom CA configurations for receptor mesh must be manually reconfigured.
* Disconnected environments: The migration processes for disconnected environments is not covered in this guide.
* Execution environments (other than the default one): Custom execution environments must be rebuilt or reimported manually.

As of the date of writing this guide, the content and configuration for these items are expected to be re-created, imported, or configured manually in the target environment. These out-of-scope items might be added as supported components in future updates to this migration guide.
