:_mod-docs-content-type: PROCEDURE

[id="managed-target-migration"]
= Migrate to Managed {PlatformNameShort}

[role="_abstract"]
Submit a support ticket on the Red Hat Customer Portal to request a migration to Managed {PlatformNameShort}.

.Prerequisites
* You have a migration artifact from your source environment.

.Procedure

. Submit a link:https://access.redhat.com/support/cases/#/case/new/get-support?caseCreate=true[support ticket] on the Red Hat Customer Portal requesting a migration to Managed {PlatformNameShort}.
+
The support ticket should include:
+
** Source installation type (RPM, Containerized, OpenShift)
** Managed {PlatformNameShort} URL or deployment name
** Source version (installer or Operator version)
. The Ansible Site Reliability Engineering (SRE) team provides instructions in the support ticket on how to upload the resulting migration artifact to secure storage for processing.
. The Ansible SRE team imports the migration artifact into the identified target instance and notifies the customer through the support ticket.
. The Ansible SRE team notifies customers of successful migration.
