:_mod-docs-content-type: PROCEDURE

[id="managed-post-import"]
= Reconciling the target environment post-migration

[role="_abstract"]
Update necessary configurations after migrating to Managed {PlatformNameShort}.

.Procedure
. Log in to the Managed {PlatformNameShort} instance by using the local administrator account to confirm that data was imported.
. Perform the following actions based on the configuration of the source deployment:
.. Reconfigure Single Sign-On (SSO) authenticators and mappings to reflect the new URLs.
.. Update {PrivateHubName} content to reflect the new URLs.
... Run the following command to update the {HubName} repositories: 
+
----
curl -d '{\"verify_checksums\": true }' -X POST -k https://<platform url>/api/galaxy/pulp/api/v3/repair/ -u <admin_user>:<admin_password>
----
... Perform a sync on any repositories configured in {HubName}.
... Push any custom execution environments from the source {HubName} to the target {HubName}.
.. Reconfigure {AutomationMesh}.
. After migration, you can request standard Site Reliability Engineering (SRE) tasks through support tickets, such as configuration of custom certificates, a custom domain, or connectivity through private endpoints.
