[[qs_start]]
== Automation Controller Quick Setup Guide

Thank you for your interest in . is a commercial offering that helps
teams manage complex multi-tier deployments by adding control,
knowledge, and delegation to Ansible-powered environments.

The covers basic steps for using and running your first playbook. This
document has been updated to include information for the latest release
of .

*We Need Feedback!*

If you spot a typo in this documentation, or if you have thought of a
way to make this manual better, we would love to hear from you! Please
send an email to: docs@ansible.com

If you have a suggestion, try to be as specific as possible when
describing it. If you have found an error, please include the manual's
title, chapter number/section number, and some of the surrounding text
so we can find it easily. We may not be able to respond to every message
sent to us, but you can be sure that we will be reading them all!

; ; https://access.redhat.com/

self quick_start login_superuser import_license examine_dashboard setup
create_organization create_user create_inventory create_credential
create_project create_job launch

=== Index

____________
* `genindex`
____________
