
[id="pushing-container-images-from-your-local"]

= Pushing container images from your local

Use the following procedure to sign images on a local system and push those signed images to the {HubName} registry. 

.Procedure
. From a terminal, log into podman, or any container client currently in use.
+
----
> podman pull <container-name>
----
+
. After the image is pulled, add tags (for example: latest, rc, beta, or version numbers, such as 1.0; 2.3, and so on):
+
----
> podman tag <container-name> <server-address>/<container-name>:<tag name>
----
+
. Sign the image after changes have been made, and push it back up to the {HubName} registry:
+
----
> podman push <server-address>/<container-name>:<tag name> --tls-verify=false --sign-by <reference to the gpg key on your local>
----
+
If the image is not signed, it can only be pushed with any current signature embedded. Alternatively, you can use the following script to push the image without signing it:
+
----
> podman push <server-address>/<container-name>:<tag name> --tls-verify=false
----
+
. Once the image has been pushed, navigate to your {HubName}.

. Click the "Refresh" icon to refresh the page to show the new execution
environment.

. Click the name of the image  to view your pushed image.

In the details page, below the image name, will be displayed whether or not the
image has been signed. In this case, it displays "Unsigned."

The details page in {HubName} indicates whether or not an image has been signed. If the details page indicates that an image is *Unsigned*, you can sign the image from {HubName}  using the following steps: 				

. Click the image name to navigate to the details page.

. Click the three dots in the upper right hand corner of the details page.
Three options are available:
* Use in Controller
* Delete
* Sign

. Click sign from the drop-down menu.

The signing service signs the image. Once the image is signed, the status changes to "signed".
