:_mod-docs-content-type: ASSEMBLY

[id="migrate-containerized-to-ocp"]
= Migrating from a containerized deployment to an {OCPShort} deployment

Use this information to migrate your containerized deployment to an {OCPShort} deployment.

include::aap-migration/con-containerized-to-ocp-prerequisites.adoc[leveloffset=+1]

== Preparing and assessing the source environment

To prepare and assess your source containerized deployment, follow the instructions in link:{URLMigration}/source-containerized#containerized-environment-source-prep[Preparing and assessing the source environment].

== Exporting the source environment

To export your source containerized environment, follow the instructions in link:{URLMigration}/source-containerized#containerized-source-environment-export[Exporting the source environment].

== Creating and verifying the migration artifact

To create and verify the migration artifact, follow the instructions in link:{URLMigration}/migration-artifact-creation[Migration artifact structure and verification].

include::aap-migration/proc-cont-ocp-target-prep.adoc[leveloffset=+1]

include::aap-migration/proc-cont-ocp-target-import.adoc[leveloffset=+1]

include::aap-migration/proc-cont-ocp-post-import.adoc[leveloffset=+1]

include::aap-migration/proc-cont-ocp-validation.adoc[leveloffset=+1]
