:_mod-docs-content-type: ASSEMBLY
[id="eda-set-up-rhaap-credential-type"]

= {PlatformName} credential

[role="_abstract"]
When {EDAcontroller} is deployed on {PlatformNameShort} {PlatformVers}, you can create a {PlatformName} credential to connect to {ControllerName} through the use of an {ControllerName} URL and a username and password. After it has been created, you can attach the {PlatformName} credential to a rulebook and use it to run rulebook activations. These credentials provide a simple way to configure communication between {ControllerName} and {EDAcontroller}, enabling your rulebook activations to launch job templates.

[NOTE]
====
If you deployed {EDAcontroller} with {PlatformNameShort} 2.4, you probably used controller tokens to connect {ControllerName} and {EDAcontroller}. These controller tokens have been deprecated in {PlatformNameShort} {PlatformVers}. To delete deprecated controller tokens and the rulebook activations associated with them, complete the following procedures starting with link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-set-up-rhaap-credential-type#replacing-controller-tokens[Replacing controller tokens in {PlatformNameShort} {PlatformVers}] before proceeding with link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-set-up-rhaap-credential-type#eda-set-up-rhaap-credential[Setting up a {PlatformName} credential].
====

include::eda/con-replacing-controller-tokens.adoc[leveloffset=+1]

include::eda/proc-eda-delete-rulebook-activations-with-cont-tokens.adoc[leveloffset=+2]

include::eda/proc-eda-delete-controller-token.adoc[leveloffset=+2]

include::eda/proc-eda-set-up-rhaap-credential.adoc[leveloffset=+1]