[id="eda-credential-types"]

= Credential types

Five built-in credential types are supported for {EDAcontroller}:

Source Control:: Used to sync projects from private/protected source control repositories. This credential type is used primarily for projects.
Container Registry:: Used to fetch decision environments from your private/protected container registries. This credential type is used primarily with decision environments.
GNU Privacy Guard (GPG) Public Key:: GNU Privacy Guard can be used to confirm GIT commits are signed by a specific user. Used in Project Sync with or without Source Control. This credential type is used primarily for projects.
Red Hat Ansible Automation Platform:: Used to connect to a controller, the user can provide username/password/url for the {PlatformNameSho} or a token/url. This credential type can be attached to a rulebook activation.
Vault:: Used to run rulebooks that have vaulted strings in them. To decrypt the vaulted string, you must provide a Vault Password to avoid failure during rulebook activation. This credential type can be attached to a rulebook activation.

These built-in credential types are not editable. So if you want credential types that support authentication with other systems, you must create your own credential types that can be used in your source plugins. Each credential type contains an input configuration and an injector configuration that can be passed to an Ansible rulebook to configure your sources.

In addition to the five built-in credential types, you can customize your own credential types. For more information, see Custom credential types.
//[J. Self] Will add the cross-reference/link later. 


include::eda/con-custom-credential-types.adoc[leveloffset=+1]
include::eda/proc-eda-set-up-credential-types.adoc[leveloffset=+1]
//nclude::eda/proc-eda-edit-credential.adoc[leveloffset=+1]
//include::eda/proc-eda-delete-credential.adoc[leveloffset=+1]
