:_mod-docs-content-type: ASSEMBLY
[id="eda-credentials"]

= Credentials

[role="_abstract"]
You can use credentials to store secrets that can be used for authentication purposes with resources, such as decision environments, rulebook activations and projects for {EDAcontroller}, and projects for {ControllerName}.

Credentials authenticate users when launching jobs against machines and importing project content from a version control system.

You can grant users and teams the ability to use these credentials without exposing the credential to the user. If a user moves to a different team or leaves the organization, you do not have to rekey all of your systems just because that credential was previously available.

[NOTE]
====
In the context of {ControllerName} and {EDAcontroller}, you can use both `extra_vars` and credentials to store a variety of information. However, credentials are the preferred method of storing sensitive information such as passwords or API keys because they offer better security and centralized management, whereas `extra_vars` are more suitable for passing dynamic, non-sensitive data.
====

include::eda/con-credentials-list-view.adoc[leveloffset=+1]

include::eda/proc-eda-set-up-credential.adoc[leveloffset=+1]

include::eda/proc-eda-edit-credential.adoc[leveloffset=+1]

include::eda/proc-eda-duplicate-credential.adoc[leveloffset=+1]

include::eda/proc-eda-delete-credential.adoc[leveloffset=+1]
