:_mod-docs-content-type: ASSEMBLY
[id="eda-user-guide-overview"]

= Trigger automation from events with {EDAName}

[role="_abstract"]
{EDAName} is a highly scalable, flexible automation capability. It works with external event sources (like software vendors' monitoring tools) to identify IT events and automatically implement the defined changes or responses within a rulebook.

Learn how to configure and manage the end-to-end lifecycle of event-driven automation within the {PlatformName}. {EDAName} provides you the ability to perform the following actions: 

* Manage projects for rulebook storage
* Build and restore decision environments for execution
* Define credentials for secure authentication
* Create event streams for centralized routing
* Manage rulebook activations to main persistent, scalable listeners that monitor infrastructure and trigger automated workflows in real time


[NOTE]

====
* API documentation for {EDAcontroller} is available at \https://<gateway-host>/api/eda/v1/docs
* To meet high availability demands, {EDAcontroller} shares centralized link:https://redis.io/[Redis (REmote DIctionary Server)] with the {PlatformNameShort} UI. When Redis is unavailable, you will not be able to create or sync projects, or enable rulebook activations.
====

[IMPORTANT]

====
In new installations of {PlatformNameShort} {PlatformVers}, using {EDAcontroller}'s API to manage organizations, teams, or users requires an automated sync of up to 15 minutes to propagate changes to the rest of the {PlatformNameShort} components. To avoid potential errors and ensure immediate access, use the {Gateway} API instead, or the unified UI.
====

[role="_additional-resources"]
.Additional resources
* link:{URLCentralAuth}/index[Access management and authentication guide]
* link:{URLCentralAuth}/gw-managing-access#ref-controller-user-roles[Adding roles for a user]
* link:{URLCentralAuth}/assembly-gw-roles[Roles]
* link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/using_event-driven_ansible_2.5_with_ansible_automation_platform_2.4/index[Using Event-Driven Ansible 2.5 with Ansible Automation Platform 2.4]
//Verify whether the link "Using Event-Driven Ansible 2.5 with Ansible Automation Platform 2.4" is useful anymore