:_mod-docs-content-type: ASSEMBLY

:_mod-docs-content-type: <ASSEMBLY>
[id="eda-credential-types"]

= Credential types

{EDAcontroller} comes with several built-in credential types that you can use for syncing projects, running rulebook activations, executing job templates through {MenuTopAE} ({ControllerName}), fetching images from container registries, and processing data through event streams. 

These built-in credential types are not editable. So if you want credential types that support authentication with other systems, you can create your own credential types that can be used in your source plugins. Each credential type contains an input configuration and an injector configuration that can be passed to an Ansible rulebook to configure your sources. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credential-types#eda-custom-credential-types[Custom credential types].

If you will be executing job templates through {ControllerName}, you can retrieve credential values from external secret management systems listed in link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-credential-types#eda-external-credential-types[External secret management credential types].


include::eda/con-external-credential-types.adoc[leveloffset=+1]

include::eda/con-custom-credential-types.adoc[leveloffset=+1]

include::eda/con-credential-types-input-config.adoc[leveloffset=+2]

include::eda/con-credential-types-injector-config.adoc[leveloffset=+2]

include::eda/proc-eda-set-up-credential-types.adoc[leveloffset=+1]

