:_mod-docs-content-type: ASSEMBLY
[id="eda-rulebook-activations"]

= Define rules that trigger automation from events

[role="_abstract"]

A rulebook is a set of conditional rules that {EDAName} uses to perform IT actions in an event-driven automation model. 
Rulebooks are the means by which users tell {EDAName} which source to check for an event and when that event occurs what to do when certain conditions are met.

A rulebook specifies actions to be performed when a rule is triggered. 
A rule gets triggered when the events match the conditions for the rules. 
The following actions are currently supported:

* `run_playbook` (only supported with ansible-rulebook CLI)
* `run_module`
* `run_job_template`
* `run_workflow_template`
* `set_fact`
* `post_event`
* `retract_fact`
* `print_event`
* `shutdown`
* `debug`
* `none`

To view further details, see link:https://ansible.readthedocs.io/projects/rulebook/en/latest/actions.html[Actions]. 

A rulebook activation is a process running in the background defined by a decision environment executing a specific rulebook. You can set up your rulebook activation by following link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/{PlatformVers}/html/using_automation_decisions/eda-rulebook-activations#eda-set-up-rulebook-activation[Setting up a rulebook activation].

[WARNING]
====
Red Hat does not recommend the use of a non-supported source plugin with 1 postgres database. 
This can pose a potential risk to your use of {PlatformNameShort}. 
====

[IMPORTANT]
====
To meet high availability demands, {EDAcontroller} shares centralized link:https://redis.io/[Redis (REmote DIctionary Server)] with the {PlatformNameShort} UI. When Redis is unavailable, the following functions will not be available:

* Creating an activation, if `is_enabled` is True
* Deleting an activation
* Enabling an activation, if not already enabled
* Disabling an activation, if not already disabled
* Restarting an activation
====

include::eda/con-eda-rulebook-supported-event-sources.adoc[leveloffset=+1]

include::eda/proc-eda-set-up-rulebook-activation.adoc[leveloffset=+1]

include::eda/con-eda-rulebook-activation-list-view.adoc[leveloffset=+1]

include::eda/proc-eda-view-activation-output.adoc[leveloffset=+2]

//include::eda/proc-eda-activate-webhook.adoc[leveloffset=+1]

//include::eda/proc-eda-test-with-K8s.adoc[leveloffset=+1]
