[id="lightspeed-about_{context}"]

= About {LightspeedShortName}

[role="_abstract"]

{LightspeedFullName} is a generative AI service that helps automation teams create, adopt, and maintain Ansible content more efficiently. 

{LightspeedShortName} uses natural language prompts to generate code recommendations for automation tasks based on Ansible best practices. {LightspeedShortName} also proactively creates pull requests with code improvement recommendations for you to review, test, and apply in your Ansible content. 

{LightspeedShortName} uses {ibmwatsonxcodeassistant} models trained on subject matter expertise across the Ansible ecosystem, which includes {Galaxy}, GitHub, and Ansible Certified and Validated content.

{LightspeedShortName} is integrated with your existing Ansible developer workflows. You can use your existing Git repositories (both public and private) to train your single-tenant {ibmwatsonxcodeassistant} model. You can access {LightspeedShortName} content suggestions in Visual Studio Code (VS Code) by using the Ansible VS Code extension. 

== Benefits of using {LightspeedShortName}
{LightspeedFullName} offers the following benefits: 

* *Reduces the onboarding learning period for Ansible developers*
+
With just a basic understanding of YAML syntax, Ansible developers can use natural language prompts to describe the automation goal. {LightspeedShortName} then offers Ansible code recommendations to help achieve the automation goal more efficiently. This combination of content and best practice suggestions reduces the learning curve and offers a smoother onboarding experience for new Ansible users. 
+
For example, to get a multitask code recommendation, you can enter the prompt `Install postgresql-server & run postgresql-setup command`. The Ansible Lightspeed service reads the text, interacts with {ibmwatsonxcodeassistant}, and generates code recommendations to automate a multitask that installs a PostgreSQL server and sets up a PostgreSQL database. You can then view and accept the code recommendations to create tasks in an Ansible YAML file. 

* *Increases productivity with quality content creation*
+
{LightspeedShortName} offers automation code recommendations that adhere to Ansible best practices, and {ibmwatsonxcodeassistant} provides model fine-tuning features to improve the accuracy of suggested content based on your organization's existing Ansible content. Therefore, the AI-generated code recommendations are more accurate, more reliable, and integrated with your existing automation development workflows. 

* *Extends trust with AI-generated code recommendations*
+
The AI-generated code recommendations enable you to extend trust, with an automation code base that adheres to accepted Ansible best practices and significant data safeguards. 
