:_mod-docs-content-type: CONCEPT

[id="lightspeed-about_{context}"]

= About {LightspeedShortName}

[role="_abstract"]
{LightspeedFullName} is a generative AI service that helps automation teams create, adopt, and maintain Ansible content more efficiently. It uses natural language prompts to generate code recommendations for automation tasks based on Ansible best practices. 

{LightspeedShortName} is the cloud service that enables integration of generative AI into Ansible Automation Platform. This document specifically describes the integration of {LightspeedFullName}.

{LightspeedShortName} uses {ibmwatsonxcodeassistant} models trained on subject matter expertise across the Ansible ecosystem, which includes Galaxy, GitHub, and Ansible certified and validated content. For ease of use, {LightspeedShortName} is integrated with your existing Ansible developer workflows. For example, you can use your existing Git repositories (both public and private) to train your {ibmwatsonxcodeassistant} models. You can also access Lightspeed content suggestions in VS Code through the Ansible VS code extension.

== Access {LightspeedFullName}

This section contains information about accessing both {LightspeedShortName} cloud service and on-premise deployment. 

* *{LightspeedShortName} cloud service*
+
To use the {LightspeedShortName} cloud service, you must meet *one* of the following requirements:

** Your organization has a trial or paid subscription to both the {PlatformName} and {ibmwatsonxcodeassistant}.
** Your organization has a trial or paid subscription to the {PlatformName}, and you have a {LightspeedShortName} trial account.
+
[NOTE]
====
A {LightspeedShortName} trial account does not require an {ibmwatsonxcodeassistant} subscription.
====

* *{LightspeedShortName} on-premise deployment*
+
To use an on-premise deployment of {LightspeedShortName}, your organization must have the following subscriptions:

** A trial or paid subscription to the {PlatformName} 

** An installation of {ibmwatsonxcodeassistant} for {LightspeedshortName} on Cloud Pak for Data

== Benefits of using {LightspeedShortName}
{LightspeedFullName} offers the following benefits: 

* *Reduces the onboarding learning period for Ansible developers*
+
With just a basic understanding of YAML syntax, Ansible developers can use natural language prompts in English language to describe the automation goal. {LightspeedShortName} then offers Ansible code recommendations to help achieve the automation goal more efficiently. This combination of content and best practice suggestions reduces the learning curve and offers a smoother onboarding experience for new Ansible users. 
+
For example, to get a multitask code recommendation, you can enter the prompt `Install postgresql-server & run postgresql-setup command`. The Ansible Lightspeed service reads the text, interacts with {ibmwatsonxcodeassistant}, and generates code recommendations to automate a multitask that installs a PostgreSQL server and sets up a PostgreSQL database. You can then view and accept the code recommendations to create tasks in an Ansible YAML file. 

* *Increases productivity with quality content creation*
+
{LightspeedShortName} offers automation code recommendations that adhere to Ansible best practices, and {ibmwatsonxcodeassistant} provides model fine-tuning features to improve the accuracy of suggested content based on your organization's existing Ansible content. Therefore, the AI-generated code recommendations are more accurate, more reliable, and integrated with your existing automation development workflows. 

* *Extends trust with AI-generated code recommendations*
+
The AI-generated code recommendations enable you to extend trust, with an automation code base that adheres to accepted Ansible best practices and significant data safeguards. 
