:_content-type: CONCEPT

[id="training-data_{context}"]

= Data gathered to train the {ibmwatsonxcodeassistant} models

== Models

{LightspeedFullName} uses Ansible-specific IBM watsonx Granite models unique to your organization. These models are provided, managed, and maintained by IBM. You can use the Ansible-specific IBM watsonx Granite model as the default model for {LightspeedShortName}, so that all Ansible Lightspeed users in your organization can use the fine-tuned model. 

You can use the following types of IBM watsonx Granite models with {LightspeedShortName}:

* Base model
+
A default model that enables all users in your organization to use generative AI with {LightspeedShortName}.

* Custom or fine-tuned model
+
Custom models that are fine-tuned on your organizational automation data to improve the code recommendation experience. You can configure the fine-tuned models for select Ansible users or for all users in your organization. For more information, see xref:configuring-custom-models_configuring-custom-models[Configuring custom models]. 

== Data sources

{ibmwatsonxcodeassistant} models are trained on Ansible content from {Galaxy}, data from public Git repositories, and Red Hat Ansible subject matter expert examples. 

If you publish content to {Galaxy} and want to restrict your {Galaxy} content from being used to train the models, you can opt out of sharing your {Galaxy} data in the {Galaxy} namespace configuration. 

== Data telemetry

The Ansible VS Code extension, with {LightspeedFullName} features enabled, automatically collects recommendations, usage telemetry, and playbook state through automated events. This data is eventually shared with {LightspeedShortName} and {ibmwatsonxcodeassistant} to generate code recommendations. 

The following table lists the data that the Ansible VS Code extension collects. 

.Data collected by the Ansible VS Code extension
[cols="30%,70%",options="header"]
|====
| *Metric* | *Description*
| Recommendation accepted | An indicator that a code recommendation was accepted by an Ansible user and included in the Ansible playbook.
| Recommendation rejected | An indicator that a code recommendation was rejected by an Ansible user and excluded from the Ansible playbook.
| Anonymized document URI | The string that helps to determine the document type (playbook, role, or task).
| Request and response timestamps | The request and response times captured in UTC format.
| Anonymized user ID | A random anonymous user ID that is stored locally on `~/.redhat/anonymousid`.
| Anonymized suggestion ID | A random auto-generated session ID associated with the suggestion request.
|{ibmwatsonxcodeassistant} metadata | Contextual information about the suggestion returned from the {ibmwatsonxcodeassistant} model such as the recommended Ansible module, recommended parameter keys, and length of the suggestion.
|====