:_content-type: CONCEPT

[id="configure-custom-models_{context}"]

= Configuring custom models

[role="_abstract"]
As an organization administrator, you can create and use fine-tuned, custom models that are trained on your organization's existing Ansible content. With this capability, you can tune the models to your organization's automation patterns and improve the code recommendation experience.

After you create a custom model, you can specify one of the following access types:

* Enable access for all users in your organization
+
You can configure the custom model as the default model for your organization. All users in your organization can use the custom model.

* Enable access for select Ansible users in your organization
+
Using the *model-override* setting in the Ansible VS Code extension, select Ansible users can tune their Ansible Lightspeed service to use a custom model instead of the default model. 

== Process for configuring custom models

To configure a custom model, perform the following tasks: 

. xref:ansible-content-parser_administering-ansible-lightspeed[Create a training data set by using the {AnsibleContentParser}]

. xref:create-deploy-custom-model-ibm_administering-ansible-lightspeed[Create and deploy a custom model by using {ibmwatsonxcodeassistant}]

. xref:configure-custom-models-lightspeed_administering-ansible-lightspeed[Configure {LightspeedshortName} to use the custom model]
