:_content-type: CONCEPT

[id="training-data_{context}"]

= Data gathered to train the {ibmwatsonxcodeassistant} models

[role="_abstract"]
This topic provides information about the data that is collected to train the {ibmwatsonxcodeassistant} models.

== Models

{LightspeedFullName} uses Ansible-specific IBM watsonx Granite models unique to your organization. These models are provided, managed, and maintained by IBM.

== Data sources

{ibmwatsonxcodeassistant} models are trained on Ansible content from {Galaxy}, data from public Git repositories, and Red Hat Ansible subject matter expert examples. 

If you publish content to {Galaxy} and want to restrict your {Galaxy} content from being used to train the models, you can opt out of sharing your {Galaxy} data in the {Galaxy} namespace configuration. 

== Data telemetry

{LightspeedshortName} collects the following telemetry data by default:

* Operational telemetry data
* Admin dashboard telemetry data

[NOTE]
====
No telemetry data is collected in an {LightspeedShortName} on-premise deployment.
====
