:_content-type: CONCEPT

[id="lightspeed-key-features_{context}"]
= Key Features

{LightspeedShortName} offers the following key features: 

* Ansible-specific foundation models
+
{LightspeedFullName} leverages a specially trained, Ansible-specific IBM watsonx Granite model provided, managed, and maintained by IBM. IBM's watsonx Granite model offers the these benefits:

** More accurate recommendations.
** A more sustainable approach, 

* Single tasks and multitask generation
+
Using natural language prompts, you can generate single task or multiple task recommendations for Ansible task files and playbooks. To request multitask code recommendations, you can enter a sequence of natural language task prompts separated by ampersand (&) symbols.

* Content source matching
+
For each generated code recommendation, {LightspeedShortName} lists content source matches, including details like potential source, content author, and relevant licenses. You can use this data to gain insight into potential training data sources used to generate the code recommendations.

* Post-processing capabilities
+
{LightspeedShortName} offers post-processing capabilities that augment the IBM watsonx Code foundation model, and improve the quality and accuracy of code recommendations. Ansible developers can provide feedback on whether the generated code recommendations matched their task intent. This user feedback is used to fine-tune the IBM watsonx Code foundation model.
+
The Ansible code bot scans existing content collections, roles, and playbooks through git repositories, and proactively creates pull requests whenever best practices or quality improvement recommendations are available. The bot automatically submits pull requests to the repository, which proactively alerts the repository owner of a recommended change to their content. {LightspeedShortName} also integrates with ansible-lint to recommend code quality improvements. 




