:_content-type: CONCEPT

[id="con-gs-develop-ansible-content_{context}"]
= Develop Ansible content

After the organization administrators have set up {LightspeedShortName}, automation developers can use the Ansible Lightspeed service to develop and use custom automation content.

Perform the following tasks to develop Ansible content: 

. Install and configure the Ansible VS Code extension
. Develop Ansible content

== Installing and configuring Ansible VS Code extension
To access {LightspeedShortName}, all Ansible users must install and configure the Ansible VS Code extension in their VS Code editor. For the procedure, see xref:con-configure-vs-code-extension_developing-ansible-content[Install and configure the Ansible VS Code extension]. 

== Developing Ansible content
After installing and configuring the Ansible VS Code extension, automation developers can create custom Ansible content. 

You can perform the following tasks:

* Log in to the Ansible Lightspeed service as an automation developer
+
Once configured, you can xref:log-into-portal-auto-dev_developing-ansible-content[use the Ansible VS Code extension to access the Ansible Lightspeed service]. 

* Create single or multitask recommendations
+
You can xref:con-task-recommendations_developing-ansible-content[generate single-task or multitask code recommendations] for your task intent using the Ansible VS Code extension.

* Create an Ansible playbook and view playbook explanations
+
You can xref:playbook-generation_developing-ansible-content[create Ansible playbooks and view explanations for new or existing playbooks] by using the Ansible VS Code extension.

* Provide feedback on the Ansible Lightspeed service
+
You can xref:provide-feedback_developing-ansible-content[submit feedback on the quality of the code recommendations] to further improve the Ansible Lightspeed service. 

* Log out of the Ansible Lightspeed service
+
To xref:logging-into-portal-auto-dev_developing-ansible-content[log out of the Ansible Lightspeed service], you must log out of both the Ansible Lightspeed VS Code extension and the Ansible Lightspeed portal.