:_content-type: CONCEPT

[id="view-manage-admin-dashboard-telemetry_{context}"]

= Viewing and managing the Admin dashboard telemetry

[role="_abstract"]
{LightspeedshortName} collects the following telemetry data by default:

* *Operational telemetry data*
+
This is the data that is required to operate and troubleshoot the Ansible Lightspeed service. For more information, refer the Enterprise Agreement. You cannot disable the collection of operational telemetry data. 
+
This includes the following data:

** Organization you are logged into (Organization ID, account number)
** Large language model (or models) that you are connected to 

* *Admin dashboard telemetry data*
+
This is the data that provides insight into how your organization users are using the Ansible Lightspeed service, and the metrics are displayed on the Admin dashboard. 
+
This includes the following data:

** Prompts and content suggestions, including accept or reject of the content suggestions
** User sentiment feedback
+
You can also disable the Admin dashboard telemetry if you no longer want to collect and monitor the telemetry data. 

[NOTE]
====
Viewing telemetry data on the Admin dashboard is not yet supported on {LightspeedShortName} on-premise deployments.
====

== Prerequisites
To view and manage the Admin dashboard telemetry data, ensure that you have the following:

* You have organization administrator privileges to a Red Hat Customer Portal organization with a valid Red Hat Ansible Automation Platform subscription.

* You have installed the Ansible VS Code extension v2.13.148 that is required to collect Admin dashboard telemetry. 

[IMPORTANT]
====
{LightspeedShortName} does not collect users' personal information, such as usernames or passwords. If any personal information is inadvertently received, the data is deleted. For more information about {LightspeedShortName}'s privacy practices, see the xref:telemetry-data-collection-notice_lightspeed-intro[Telemetry Data Collection Notice for the Admin dashboard].
====

== What telemetry data is collected?
Following is the list of telemetry data that {LightspeedShortName} collects:

* Details of the organization that you are logged into, such as organization ID and account number
* Large language models that you are connected to 
* Inline suggestions that were accepted, rejected, or ignored by your organization users
* User sentiment feedback
* Top 10 modules returned in code recommendations
