:_content-type: CONCEPT

[id="lightspeed-key-features_{context}"]
= Key features of {LightspeedShortName}

{LightspeedShortName} offers the following key features: 

* *Ansible-specific {ibmwatsonxcodeassistant} models*
+
{LightspeedFullName} uses Ansible-specific IBM watsonx Granite models unique to your organization, which are provided, managed, and maintained by IBM.

* *Single tasks and multitask generation*
+
Using natural language prompts, you can generate single task or multiple task recommendations for Ansible task files and playbooks. To request multitask code recommendations, you can enter a sequence of natural language task prompts in a YAML file comment separated by ampersand (*&*) symbols.
+
Currently, {LightspeedShortName} supports user prompts in English language only. However, there could be instances where the training data that was used to train the {ibmwatsonxcodeassistant} models included non-English language. In such scenarios, the model can generate code recommendations for prompts made in the same non-English language, but the generated code recommendations might or might not be accurate.

* *Content source matching*
+
For each generated code recommendation, {LightspeedShortName} lists content source matches, including details such as potential source, content author, and relevant licenses. You can use this data to gain insight into potential training data sources used to generate the code recommendations.

* *Post-processing capabilities*
+
{LightspeedShortName} offers post-processing capabilities that augment {ibmwatsonxcodeassistant} and improve the quality and accuracy of code recommendations. 

* *Content maintenance and modernization*
+
The {AnsibleCodeBot} scans existing content collections, roles, and playbooks through Git repositories, and proactively creates pull requests whenever best practices or quality improvement recommendations are available. The bot automatically submits pull requests to the repository, which proactively alerts the repository owner to a recommended change to their content. 
