:_content-type: CONCEPT

[id="training-data_{context}"]

= Data gathered to train the {ibmwatsonxcodeassistant} models

== Models

{LightspeedFullName} uses Ansible-specific IBM watsonx Granite models unique to your organization. These models are provided, managed, and maintained by IBM. You can use the Ansible-specific IBM watsonx Granite model as the default model for {LightspeedShortName}, so that all Ansible Lightspeed users in your organization can use the fine-tuned model. 

You can configure {LightspeedShortName} to use one of the following models:

* *Base model*: A default model that enables all users in your organization to use generative AI with {LightspeedShortName}.

* *Custom model*: A custom model that is fine-tuned on your organizational automation data to improve the code recommendation experience. You can configure custom models for select Ansible users or for all users in your organization. For more information, see xref:configuring-custom-models_lightspeed-user-guide[Configuring custom models]. 

== Data sources

{ibmwatsonxcodeassistant} models are trained on Ansible content from {Galaxy}, data from public Git repositories, and Red Hat Ansible subject matter expert examples. 

If you publish content to {Galaxy} and want to restrict your {Galaxy} content from being used to train the models, you can opt out of sharing your {Galaxy} data in the {Galaxy} namespace configuration. 

== Data telemetry

{LightspeedshortName} collects the following telemetry data by default:

* *Operational telemetry data*
+
This is the data that is required to operate and troubleshoot the Ansible Lightspeed service. For more information, refer the Enterprise Agreement. You cannot disable the collection of operational telemetry data. 

* *Admin dashboard telemetry data*
+
This is the data that provides insight into how your organization users are using the Ansible Lightspeed service, and the metrics are displayed on the Admin dashboard. You can also disable the Admin dashboard telemetry if you no longer want to collect and monitor the telemetry data.

== What telemetry data is collected?
Following is the list of telemetry data that Red Hat Ansible Lightspeed collects:

* Details of the organization that you are logged into, such as organization ID and account number
* Large language models that you are connected to 
* Inline suggestions that were accepted, rejected, or ignored by your organization users
* User sentiment feedback
* Top 10 modules returned in code recommendations

For more information about Admin dashboard telemetry, see xref:managing-admin-dashboard-telemetry_lightspeed-user-guide[Viewing and managing Admin dashboard telemetry]. 