:_content-type: CONCEPT

[id="ansible-content-parser_{context}"]

= Configuring custom models

:context: configuring-custom-models

[role="_abstract"]

As an organization administrator, you can create and use fine-tuned, custom models that are trained on your organization's existing Ansible content. With this capability, you can tune the models to your organization's automation patterns and improve the code recommendation experience.

After you create a custom model, you can specify one of the following access types:

* Enable access for all users in your organization
+
You can configure the custom model as the default model for your organization. All users in your organization can use the custom model.

* Enable access for select Ansible users in your organization
+
Using the *model-override* setting in the Ansible VS Code extension, select Ansible users can tune their Ansible Lightspeed service to use a custom model instead of the default model. 

== Process for configuring custom models

To configure a custom model, perform the following tasks: 

. xref:ansible-content-parser_configuring-custom-models[Create a training data set by using the {AnsibleContentParser}]

. xref:create-deploy-custom-model-ibm_configuring-custom-models[Create and deploy a custom model by using {ibmwatsonxcodeassistant}]

. xref:configure-custom-models-lightspeed_configuring-custom-models[Configure {LightspeedshortName} to use the custom model]

== Creating a training data set by using the {AnsibleContentParser}

Use the {AnsibleContentParser}, a command-line interface (CLI) tool, to scan your existing Ansible files and generate a custom model training data set. The training data set includes a list of Ansible files and their paths relative to the project root. You can then upload this data set to {ibmwatsonxcodeassistant}, and use it to create a custom model that is trained on your organization's existing Ansible content. 

=== Methods of creating training data sets
You can generate a training data set by using one of the following methods:  

* *With ansible-lint preprocessing* 
+
By default, the {AnsibleContentParser} generates training data sets by using ansible-lint preprocessing. The {AnsibleContentParser} uses ansible-lint rules to scan your Ansible files and ensure that the content adheres to Ansible best practices. If rule violations are found, the {AnsibleContentParser} excludes these files from the generated output. In such scenarios, you must resolve the rule violations, and run the {AnsibleContentParser} once again so that the generated output includes all your Ansible files. 

* *Without ansible-lint preprocessing*
+
You can generate a training data set without ansible-lint preprocessing. In this method, the {AnsibleContentParser} does not scan your Ansible files for ansible-lint rule violations; therefore, the training data set includes all files. Although the training data set includes all files, it might not adhere to Ansible best practices and could affect the quality of your code recommendation experience. 

== Supported data sources 

The {AnsibleContentParser} scans the following directories and file formats:

* Local directories
* Archived files, such as `.zip`, `.tar`, `.tar.gz`, `.tar.bz2`, and `.tar.xz` files
* Git repository URLs (includes both private and public repositories)

== Process of creating a training data set
To create a custom model training data set, perform the following tasks:

. xref:install-content-parser_configuring-custom-models[Install the {AnsibleContentParser} on your computer]

. xref:generate-training-data-set_configuring-custom-models[Generate a custom model training data set]

. xref:view-content-parser-output_configuring-custom-models[View the generated training data set]

. (Optional: If you generated a training data set with ansible-lint preprocessing and detected ansible-lint rule violations) xref:resolve-ansible-lint-rule-violations_configuring-custom-models[Resolve ansible-lint rule violations]

. (Optional: If you generated multiple training data sets) xref:merge-multiple-jsonl-files_configuring-custom-models[Merge multiple training data sets into a single JSONL file]
