:_content-type: CONCEPT

[id="con-gs-system-requirements_{context}"]
= Licensing requirements

Check the licensing requirements for your {LightspeedShortName} deployment. 

[discrete]
== Trial account
To start a free 90-day trial for existing Ansible users:

* You need a trial or paid subscription to the {PlatformName}. 

* You do not need a trial or paid subscription to {ibmwatsonxcodeassistant}.

[discrete]
== Cloud service
To use the {LightspeedShortName} cloud service, you must meet one of the following requirements:

* Your organization has a trial or paid subscription to both the {PlatformName} and IBM watsonx Code Assistant.

* Your organization has a trial or paid subscription to the {PlatformName}, and you have a Red Hat Ansible Lightspeed trial account.

[discrete]
== On-premise deployment
To use an on-premise deployment of {LightspeedShortName}, your organization must have the following subscriptions:

* A trial or paid subscription to the Red Hat Ansible Automation Platform

* An installation of {ibmwatsonxcodeassistant} for {LightspeedShortName} on Cloud Pak for Data

For a complete list of requirements (licenses, components, connectivity needs), see the xref:lightspeed-process_lightspeed-intro[Prerequisites] for {LightspeedShortName}. 