:_content-type: PROCEDURE

[id="configure-repo-scan_{context}"]

= Configuring the {AnsibleCodeBot} to scan your repository at regular intervals

You can schedule the {AnsibleCodeBot} to scan your repositories at daily, weekly, or monthly intervals. To specify a scan schedule for your repository, create a configuration file `ansible-code-bot.yml` within your repository and specify your scan schedule in the `.yml` file. 

You can specify one of following interval cadence to scan your Git repositories:

* Daily: Runs every day from Monday to Sunday.
* Weekly: Runs once a week. By default, this is on Monday. 
* Monthly: Runs on the first day of the month, once each month.

For each interval cadence, {AnsibleCodeBot} starts scanning your Git repositories at 9 AM UTC.

.Procedure

. In GitHub, navigate to the repository that you want to scan.
. Create a `.yml` configuration file named `ansible-code-bot.yml` in your repository `.github` folder. For example, `.github/ansible-code-bot.yml`.
. In the configuration file, specify the `interval` parameter. You can specify the `interval` parameter as *daily*, *weekly*, or *monthly*. For example:
+
----
schedule:
  interval: "<daily | weekly | monthly>"
----
+
. Commit your changes. 

The {AnsibleCodeBot} starts scanning your repository per the schedule you configured at 9 AM UTC time. 



