:_content-type: PROCEDURE

[id="login-vscode-extension_{context}"]
= Logging in to Ansible Lightspeed through the Ansible VS Code extension

After installing and configuring the VS Code extension, you can log in to the Ansible Lightspeed service.

.Procedure

. Open the VS Code application.
. Use one of the following ways to connect to the Ansible Lightspeed service. 
** Using the *Connect* button:
.. From the navigation menu, click the *Ansible* icon. 
.. Under Ansible Lightspeed Login, click *Connect*.
** Using the *Accounts* button:
.. From the navigation menu, click the *Accounts* icon and select *Sign in with Ansible Lightspeed*.
+
[NOTE]
+
====
This option is displayed when the VS Code extension is in an active state. The extension is activated after you open the Ansible side panel or after you open an Ansible file in the VS Code editor. If you do not see this option, use the *Connect* button to link to the Ansible Lightspeed service.
====

. When prompted, click *Allow* to sign in. 
. In the *Authorize Ansible Lightspeed for VS Code* window, click *Authorize*.
. In the *Do you want Code to open the external website?* window, click *Open*. The link:https://c.ai.ansible.redhat.com/[Ansible Lightspeed portal login page] is displayed.
. Click menu:Log in[Log in with Red Hat].
. Enter your Red Hat account username and password. 
+
On successful authentication, the login screen is displayed along with your username and your assigned user role. The VS code extension is now connected with Ansible Lightspeed service. 
