:_content-type: PROCEDURE

[id="remove-seat-licenses_{context}"]

= Removing seat licenses

[role="_abstract"]
Remove users who no longer need to access {LightspeedShortName}, which makes licenses available for others to use. When you remove a user, the Ansible user's {LightspeedShortName} seat license only is removed; it does not remove the user from your Red Hat Customer Portal organization. 

[IMPORTANT]
====
To prevent deactivated RH-SSO users from accessing {LightspeedShortName}, you must remove their {LightspeedShortName} seat licenses. When RH-SSO users are deactivated, their {LightspeedShortName} seat licenses are not removed automatically. These users can continue accessing accessing {LightspeedShortName} until the next time they are forced to reauthenticate with RH-SSO.

====

.Procedure

. Go to link:https://console.redhat.com/ansible/seats-administration[{PlatformNameShort} on the Red Hat Hybrid Cloud Console].
. From the navigation panel, select menu:Ansible Lightspeed with IBM watsonx Code Assistant[Seat Management].
. Click *Remove users*.
. Select the username of the user whose license you want to remove. 
. Click *Remove*, and on the verification message, click *Ok* to confirm. 
 
