:_content-type: PROCEDURE

[id="log-in-administrator-portal_{context}"]
= Logging in to the Ansible Lightspeed administrator portal

Use the Ansible Lightspeed administrator portal to connect {LightspeedShortName} to {ibmwatsonxcodeassistant}.

.Prerequisites

* You have organization administrator privileges to a Red Hat Customer Portal organization with a valid {PlatformName} subscription.
+
[NOTE]
====
If your organization recently subscribed to the {PlatformName}, it might take a few hours for {LightspeedShortName} to detect the new subscription. In VS Code, use the *Refresh* button in the Ansible extension from the Activity bar to check again.
====

.Procedure

. Log in to the link:https://c.ai.ansible.redhat.com/[Ansible Lightspeed portal] as an organization administrator.
. Click menu:Log in[Log in with Red Hat].
. Enter your Red Hat account username and password. The Ansible Lightspeed Service uses {RHSSO} ({RHSSOshort}) for authentication. 
+
As part of the authentication process, the Ansible Lightspeed Service checks whether your organization has an active {PlatformNameShort} subscription. On successful authentication, the login screen is displayed along with your username and your assigned user role.
. From the login screen, click *Admin Portal*.
+
You are redirected to the {LightspeedFullName} administrator portal where you can connect {LightspeedShortName} to your {ibmwatsonxcodeassistant} instance.


