:_content-type: PROCEDURE

[id="login-vscode-extension_{context}"]
= Log in to Ansible Lightspeed through the Ansible VS Code extension

[role="_abstract"]
After installing and configuring the VS Code extension, you can log in to the Ansible Lightspeed service.

{LightspeedShortName} provides different sign-in methods depending on whether you are using the cloud service or the on-premise deployment.

* *Ansible Lightspeed on-premise deployments*
+
Users are authenticated using your {PlatformName} login. 
+
To sign in, you can use the *Connect* button in the Ansible Lightspeed view, or the *Sign in with Ansible Lightspeed to use Ansible* option in the menu:Accounts[] menu. Once prompted in the browser, select *Log in with Ansible Automation Platform*, and log in with the authorization mechanism that your automation controller is configured with. 

* *Ansible Lightspeed cloud service*
+
Users are authenticated using {RHSSO} ({RHSSOshort}).
+
To sign in from VS Code, you can use the *Connect* button in the Ansible Lightspeed view, or the *Sign in with Ansible Lightspeed to use Ansible* option in the menu:Accounts[] menu. Follow the on-screen prompts to log in and access the Ansible Lightspeed service using your {RHSSOshort}.

+
[NOTE]
+
====
If you are using a cloud development environment at a domain unknown by Ansible Lightspeed, such as on-premise Red Hat OpenShift Dev Spaces, your menu:Accounts[] sign-in menu provides the option *Sign-in with Red Hat to use Ansible*. 

This option uses a device code flow to successfully complete the sign-in process and requires the Red Hat Authentication extension v0.2.0 or later. If you require this authentication flow but don't see the *Sign-in with Red Hat to use Ansible* option, ensure you are using the Ansible VS Code extension v24.5.2 or later.
====

.Procedure

. Open the VS Code application.
. Sign in using either the *Connect* button in the Ansible Lightspeed view or the menu:Accounts[] menu.

* *Sign in using the Connect button*:
.. From the VS Code activity bar, click the *Ansible* icon.
.. In the *Ansible Lightspeed* view, click *Connect*.
.. Follow the on-screen prompts to sign in to Ansible Lightspeed. 

* *Sign in using the menu:Accounts[] menu*:
.. From the VS Code activity bar, click the menu:Accounts[] menu.
.. Sign in with Ansible Lightspeed to use Ansible or sign in with Red Hat to use Ansible, depending on the sign-in option you are presented with.
+
[NOTE]
====
* The sign-in options are displayed when the VS Code extension is in an active state. The extension is activated after you open the Ansible side panel or after you open an Ansible file in the VS Code editor. If you do not see this option, use the *Connect* button to link to the Ansible Lightspeed service.
* If you are using a cloud development environment at a domain unknown by Ansible Lightspeed, such as on-premise Red Hat OpenShift Dev Spaces, your menu:Accounts[] sign-in menu provides the option *Sign-in with Red Hat to use Ansible*. This option uses a device code flow to successfully complete the sign-in process and requires the Red Hat Authentication extension v0.2.0 or later. If you require this authentication flow but don't see the *Sign-in with Red Hat to use Ansible* option, ensure you are using the Ansible VS Code extension v24.5.2 or later.
====

.. Follow the on-screen prompts to sign in to {LightspeedShortName}. 

+
On successful authentication, the login screen is displayed along with your username and your assigned user role. 

