:_content-type: PROCEDURE

[id="troubleshooting-vscode_{context}"]
= Troubleshooting Ansible Visual Studio Code extension errors

== Cannot view the generated code recommendations using the Ansible VS Code extension

The following scenarios are possible: 

* You receive a `403 error` message.
+
To resolve this error, ensure that:

** Your organization administrator has configured {LightspeedShortName} for your organization. 
** You have a valid {LightspeedShortName} seat license. 
* You have not configured the required Ansible VS code extension settings.
** To resolve this error, ensure that you have enabled the *Lightspeed:Enabled* and menu:Lightspeed[Suggestions:Enabled] settings. For more information, see xref:configure-vscode-extension_configuring-with-code-assistant[Configure the Ansible VS Code extension].

* You receive a `Failure on completion requests` error when you make inference requests in VS Code.
+
If you have an assigned seat license for {LightspeedShortName} but your organization administrator has not configured an {ibmwatsonxcodeassistant} model for your organization, you will encounter a `Failure on completion requests` error when you make inference requests in VS Code. 

* You are logged in using an account that does not have a valid {LightspeedShortName} seat license. 
+
If you logged in using an account that does not have an assigned seat license, you must log out and log in again. In VS Code, click the *Accounts* icon and sign in using your Red Hat account with an assigned seat license. 

* Your VS Code Workspace settings override user settings.
+
If your Workspace settings are configured, they can override our user settings even if you have configured the Ansible VS Code extension correctly. The Workspace settings can disable your VS Code extension settings, and therefore you cannot access the Ansible Lightspeed service. 
+
To resolve this error, ensure that there are no Workspace settings configured in VS Code. For more information, see link:https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings[Workspace settings] in the VS Code documentation. 

* You entered a multitask prompt, but code recommendations were not generated.
+
To resolve this error, log out of VS Code and log in again using your Red Hat account. 

* You clicked a different location or window; therefore, the populated code recommendations disappeared. 
+
Ansible Lightspeed service takes around 5 seconds per task to populate the code recommendations. If you are using a multitask prompt, the Ansible Lightspeed service takes a bit longer (number of tasks times 5 seconds) to populate the results. Do not move your cursor or press any key while the code recommendation is being generated. If you change the cursor location or press any key, Ansible VS Code extension cancels the request and the Ansible Lightspeed service does not process your request. In such scenario, you must get the cursor back to it's original position and repopulate the results.  

