:_content-type: PROCEDURE

[id="add-remove-repo-from-scans_{context}"]

= Add or remove repositories from the {AnsibleCodeBot}

[role="_abstract"]
You can enable the {AnsibleCodeBot} for a repository, or remove repositories that you no longer want to manage. 

.Procedure

. Log in to the link:https://bot.ai.ansible.redhat.com/console[{AnsibleCodeBot} dashboard]. 
. Click *Manage Code Bot on GitHub*.
. In GitHub, click your profile photo > *Settings*.  
. Under *Integrations*, click *Applications*.
. From the *Repository access* area, perform one of the following tasks:
* *Add a new repository*: From the *Select repositories* list, select the repository that you want to add. The newly-added repository is displayed on the {AnsibleCodeBot} dashboard. 
* *Remove an existing repository*: From the *Select repositories* list, click the *Cross* icon beside the repository that you want to delete. The deleted repository details are no longer visible on the {AnsibleCodeBot} dashboard. 
. Click *Save*.



