:_content-type: PROCEDURE

[id="obtain-config-wca-and-model-id_{context}"]
= Configure {LightspeedShortName} cloud service

[role="_abstract"]
Use this procedure to configure the {LightspeedShortName} cloud service.

.Prerequisites

* You have obtained an API key and a model ID from {ibmwatsonxcodeassistant} that you want to use in {LightspeedShortName}.
+
For information about how to obtain an API key and model ID from {ibmwatsonxcodeassistant}, see the link:https://cloud.ibm.com/docs/watsonx-code-assistant[{ibmwatsonxcodeassistant} documentation].

.Procedure

. Log in to the link:https://c.ai.ansible.redhat.com/[Ansible Lightspeed portal] as an organization administrator.
. From the login screen, click *Admin Portal*.
. Specify the API key of your {ibmwatsonxcodeassistant} instance:
.. Under *IBM Cloud API Key*, click *Add API key*. A screen to enter the *API Key* is displayed. 
.. Enter the API Key.
.. Optional: Click *Test* to validate the API key.
.. Click *Save*.
. Specify the model ID of the model that you want to use:
.. Click *Model Settings*. 
.. Under *Model ID*, click *Add Model ID*. A screen to enter the *Model Id* is displayed.
.. Enter the *Model ID* that you obtained in the previous procedure as the default model for your organization.
.. Optional: Click *Test model ID* to validate the model ID.
.. Click *Save*.
+
When the API key and model ID is successfully validated, {LightspeedShortName} is connected to your {ibmwatsonxcodeassistant} instance.

[role="_additional-resources"]
.Additional resources
* xref:troubleshooting-lightspeed-configuration-errors[Troubleshooting {LightspeedShortName} configuration errors]
