:_content-type: PROCEDURE

[id="install-vscode-extension_{context}"]

= Install the Ansible VS Code extension

[role="_abstract"]
Use the following procedure to install the Ansible Lightspeed extension in VS Code. 

.Prerequisites

* VS Code version 1.70.1 or later. 

[NOTE]
====
You can also install VScode derivatives, such as VScode Insider or VS Codium. 
====

.Procedure

. Open the VS Code application.
. From the navigation menu, click the *Extensions* icon. 
. In the *Search* field, enter *Ansible*. 
. Select *Ansible* to choose the Ansible language support extension published by Red Hat.
. Click *Install*. 
. After installation is complete, verify your VSCode installation:
.. Create a new YAML file using the `.yml` or `.yaml` file extension.
.. From the *Status* toolbar, click the language indicator and select *Ansible* to associate the Ansible language type with the new YAML file. 
.. Start writing a test playbook. Contextual aids are displayed as you start creating your content. 



