:_content-type: PROCEDURE

[id="start-lightspeed-trial_{context}"]

= Starting a trial of {LightspeedShortName}

[role="_abstract"]
To start a free trial, you need a trial or paid subscription to the {PlatformName}, but you do not need a trial or paid subscription to {ibmwatsonxcodeassistant}. This means that you do not need to configure the API key or model ID when setting up a trial account. 

Using the trial account, you can create single-task and multitask recommendations, generate playbooks, and view playbook explanations. 

.Prerequisites
* You must have a trial or paid subscription to the {PlatformName}.
* You must have installed the Ansible VS Code extension. For the steps, see xref:install-vscode-extension_developing-ansible-content[Installing the Ansible VS Code extension].
* You must have configured the Ansible VS Code extension to enable {LightspeedShortName}. For the steps, see xref:configure-vscode-extension_developing-ansible-content[Configuring the Ansible VS Code extension].

.Procedure
. Open the VS Code application.
. From the VS Code activity bar, click the *Ansible* icon to open the left panel.
. Ensure that you have configured the Ansible VS Code extension to enable {LightspeedShortName}. For the steps, see xref:configure-vscode-extension_developing-ansible-content[Configuring the Ansible VS Code extension].
. In the *Ansible Lightspeed* view, click *Connect*.
. Enter your Red Hat account username and password. 
. In the Ansible Lightspeed view, click *Start trial*. The link:https://c.ai.ansible.redhat.com/[Ansible Lightspeed portal login page] opens. 
. On the Ansible Lightspeed Portal, select the checkbox to accept the IBM terms and conditions before proceeding. 
+
You can also select to receive notifications about Red Hat products, services, and events. You can unsubscribe anytime if you no longer wish to receive the marketing emails. 

. Click *Start trial*. Your {LightspeedShortName} trial has started.
. View the time remaining on your trial account:
.. From the VS Code activity bar, click the *Ansible* icon.
.. In the *Ansible Lightspeed* view, verify that you are logged in using your trial account and view the expiration date of your trial account. 
