:_content-type: PROCEDURE

[id="connect-to-different-ibm-wca-model_{context}"]

= Connecting to a different {ibmwatsonxcodeassistant} model

[role="_abstract"]
After you have set up the {LightspeedShortName} on-premise deployment successfully, you can modify the deployment if you want to connect to another {ibmwatsonxcodeassistant} model. 

For example, you connected to the default {ibmwatsonxcodeassistant} model but now want to connect to a custom model instead. To connect to another {ibmwatsonxcodeassistant} model, you must create new connection secrets, and then update the connection secrets and parameters on an existing {PlatformNameShort} operator.

.Prerequisites
* You have set up a {LightspeedShortName} on-premise deployment. 
* You have obtained an API key and a model ID of the {ibmwatsonxcodeassistant} model you want to connect to. 
* You have created a new model configuration secret for the {ibmwatsonxcodeassistant} model that you want to connect to. For information about creating a model configuration secrets, see xref:create-connection-secrets_configuring-lightspeed-onpremise[Creating a model configuration secret].

.Procedure
. Go to the {OCP}. 
. Select menu:Operators[Installed Operators].
. From the list of installed operators, select the *{PlatformNameShort}* operator.
. Locate and select the *{PlatformNameShort}* custom resource, and then click the required app.
. Select the *YAML* tab.
. Scroll the text to find the `spec` section under `Lightspeed` category. For example:
+
----
spec:
  lightspeed:
    disabled: false
    model_config_secret_name: <Name of the model configuration secret that you recently created.>
----
. Replace the `model_config_secret_name` value with the name of the {ibmwatsonxcodeassistant} that you want to connect to.
. Click *Save*. 
+
The new Ansible Lightspeed pods are created. After the new pods are running successfully, the old Ansible Lightspeed pods are terminated.


