:_content-type: PROCEDURE

[id="configure-repo-scan_{context}"]

= Configure the {AnsibleCodeBot} to scan your repository

[role="_abstract"]
You can specify one of following interval cadence to scan your Git repositories:

* Daily: Runs every day from Monday to Sunday.
* Weekly: Runs once a week on Monday. Per the initial configuration PR, the {AnsibleCodeBot} is set to scan your repositories weekly until you change the schedule to daily or monthly. 
* Monthly: Runs on the first day of the month, once each month.

For each interval cadence, {AnsibleCodeBot} starts scanning your Git repositories at 9 AM UTC.

.Procedure

. In GitHub, navigate to the repository that you want to scan.
. Create a `.yml` configuration file named `ansible-code-bot.yml` in your repository `.github` folder. For example, `.github/ansible-code-bot.yml`.
. In the configuration file, specify the scan schedule in the `interval` parameter. You can specify the `interval` parameter as `*daily*`, `*weekly*`, or `*monthly*`. For example:
+
----
schedule:
  interval: daily
----
+
. Commit your changes. 
+
The {AnsibleCodeBot} starts scanning your repository per the schedule you configured at 9 AM UTC time. 



