:_content-type: PROCEDURE

[id="update-redirect-uri_{context}"]

= Updating the Redirect URIs

[role="_abstract"]
When Ansible users log in or log out of Ansible Lightspeed service, the {PlatformName} redirects the user's browser to a specified URL. You must configure the redirect URLs so that users can log in and log out of the application successfully.  

.Prerequisites
* You have created and deployed a {LightspeedShortName} instance to your namespace.

.Procedure
. In {OCP}, select menu:Networking[Routes] and locate the {LightspeedShortName} instance that you created. This is the URL of the Ansible Lightspeed instance.
. Update the *login* redirect URI:
.. In the automation controller, go to menu:Administration[Applications].
.. Select the Lightspeed Oauth application that you created.
.. In the *Redirect URIs* field of the Oauth application, enter the URL in the following format:
+
`\https://<lightspeed_route>/complete/aap/`
+
An example of the URL is `\https://lightspeed-on-prem-web-service.com/complete/aap/`.
+
[IMPORTANT]
====
The Redirect URL must include the following information:

* The prefix `https://`
* The `<lightspeed_route>` URL, which is the URL of the {LightspeedShortName} instance that you copied earlier
* The suffix `/complete/aap/` that includes a backslash sign (*/*) at the end
====
.. Click *Save*. 

. Update the *logout* redirect URI based on your setup:
+
--
* *Procedure when both the {LightspeedShortName} instance and automation controller are installed using {PlatformNameShort} operator*:

.. Log in to the cluster on which the {PlatformNameShort} instance is running. 
.. Identify the *AutomationController* custom resource.
.. Select *[YAML view]*. 
.. Add the following entry to the YAML file:
+
----
```yaml
  spec:
  ...
  extra_settings:
    - setting: LOGOUT_ALLOWED_HOSTS
      value: "'<lightspeed_route-HostName>'"
```
----

[IMPORTANT]
====
Ensure the following while specifying the `value:` parameter:
====

* Specify the hostname without the network protocol, such as `https://`.
+
For example, the correct hostname would be `my-aiconnect-instance.somewhere.com`, and not `\https://my-aiconnect-instance.somewhere.com`.

* Use the single and double quotes exactly as specified in the codeblock.
+
If you change the single quotes to double quotes and vice versa, you will encounter errors when logging out. 

* Use a comma to specify multiple instances of {LightspeedShortName} deployment.
+
If you are running multiple instances of {LightspeedShortName} application with a single {PlatformName} deployment, add a comma (,) and then add the other hostname values. For example, you can add multiple hostnames, such as `"'my-lightspeed-instance1.somewhere.com','my-lightspeed-instance2.somewhere.com'"`

.. Apply the revised YAML. This task restarts the automation controller pods.

* *Procedure when the {PlatformNameShort} operator is run on a virtual machine*:

.. Log in to the virtual machine with the {PlatformNameShort} controller.
.. In the */etc/tower/conf.d/custom.py* file, add the following parameter: 
+
`LOGOUT_ALLOWED_HOSTS = "<lightspeed_route-HostName>"`
+
[IMPORTANT]
====
* If the */etc/tower/conf.d/custom.py* file does not exist, create it.

* Specify the hostname without the network protocol, such as `https://`.
+
For example, the correct hostname would be `my-aiconnect-instance.somewhere.com`, and not `https://my-aiconnect-instance.somewhere.com`.

* Use the single and double quotes in pairs; do not mix single quotes with double quotes.
====

.. Restart the automation controller by executing the following command: 
+
`$ automation-controller-service restart`

* *Procedure when the platform gateway is run on a virtual machine*:

.. Log in to the virtual machine with the platform gateway.
.. Add the following parameter in either the *gateway/settings.py* file or in the *ansible-automation-platform/gateway/settings.py* file: 
+
`LOGOUT_ALLOWED_HOSTS = "<lightspeed_route-HostName>"`
+
[IMPORTANT]
====
* Specify the hostname without the network protocol, such as `https://`.
+
For example, the correct hostname would be `my-aiconnect-instance.somewhere.com`, and not `https://my-aiconnect-instance.somewhere.com`.

* Use double quotes exactly as specified in the codeblock.
====

[role="_additional-resources"]
.Additional resources
* xref:troubleshooting-onpremise-deployment-errorsd[Troubleshooting {LightspeedShortName} on-premise deployment errors]