[[aap-25-3-28-oct]]

= {PlatformNameShort} patch release October 28, 2024

The following enhancements and bug fixes have been implemented in this release of {PlatformNameShort}.

== Enhancements

=== {PlatformNameShort}

* With this update, upgrades from {PlatformNameShort} 2.4 to 2.5 are supported for RPM and Operator-based deployments. For more information on how to upgrade, see link:{URLUpgrade}[{TitleUpgrade}]. (ANSTRAT-809)
** Upgrades from 2.4 Containerized {PlatformNameShort} Tech Preview to 2.5 Containerized {PlatformNameShort} are unsupported. 
** Upgrades for {EDAName} are unsupported from {PlatformNameShort} 2.4 to {PlatformNameShort} 2.5.

=== {OperatorPlatformNameShort}

* An informative redirect page is now shown when you go to the {HubName} URL root. (AAP-30915)

=== Container-based {PlatformNameShort}

* The TLS Certificate Authority private key can now use a passphrase. (AAP-33594)

* {HubNameStart} is populated with container images (decision and execution environments) and Ansible collections. (AAP-33759)

* The {ControllerName}, {EDAName}, and {HubName} legacy UIs now display a redirect page to the Platform UI rather than a blank page. (AAP-33794)

=== RPM-based {PlatformNameShort}

* Added platform Redis to RPM-based {PlatformNameShort}. This allows a 6 node cluster for a Redis high availability (HA) deployment. Removed the variable `aap_caching_mtls` and replaced it with `redis_disable_tls` and `redis_disable_mtls` which are boolean flags that disable Redis server TLS and Redis client certificate authentication. (AAP-33773)

* An informative redirect page is now shown when going to {ControllerName}, {EDAName}, or {HubName} URL. (AAP-33827)

== Bug fixes

=== {PlatformNameShort}

* Removed the *Legacy external password* option from the *Authentication Type* list. (AAP-31506)

* {Galaxy}'s `sessionauth` class is now always the first in the list of authentication classes so that the platform UI can successfully authenticate. (AAP-32146)

* link:https://access.redhat.com/security/cve/CVE-2024-10033[CVE-2024-10033] - `automation-gateway`: Fixed a Cross-site Scripting (XSS) vulnerability on the `automation-gateway` component that allowed a malicious user to perform actions that impact users.

* link:https://access.redhat.com/security/cve/CVE-2024-22189[CVE-2024-22189] - `receptor`: Resolved an issue in `quic-go` that would allow an attacker to trigger a denial of service by sending a large number of `NEW_CONNECTION_ID` frames that retire old connection IDs.

=== {ControllerNameStart}

* link:https://access.redhat.com/security/cve/CVE-2024-41989[CVE-2024-41989] - `automation-controller`: Before this update, in Django, if `floatformat` received a string representation of a number in scientific notation with a large exponent, it could lead to significant memory consumption. With this update, decimals with more than 200 digits are now returned as is.

* link:https://access.redhat.com/security/cve/CVE-2024-45230[CVE-2024-45230] - `automation-controller`: Resolved an issue in Python's Django `urlize()` and `urlizetrunc()` functions where excessive input with a specific sequence of characters would lead to denial of service.

=== {HubNameStart}

* Refactored the `dynaconf` hooks to preserve the necessary authentication classes for {PlatformNameShort} {PlatformVers} deployments. (AAP-31680)

* During role migrations, model permissions are now re-added to roles to preserve ownership. (AAP-31417)

=== {OperatorPlatformNameShort}

* The port is now correctly set when configuring the {Gateway} cache `redis_host` setting when using an external Redis cache. (AAP-33279)

* Added checksums to the {HubName} deployments so that pods are cycled to pick up changes to the PostgreSQL configuration and galaxy server settings Kubernetes secrets. (AAP-33518)

=== Container-based {PlatformNameShort}

* Fixed the uninstall playbook execution when the environment was already uninstalled. (AAP-32981)

// Commenting this out for now as the advisories are not yet published to the Errata tab on the downloads page: https://access.redhat.com/downloads/content/480/ver=2.5/rhel---9/2.5/x86_64/product-errata

// == Advisories
// The following errata advisories are included in this release:

// * link:https://access.redhat.com/errata/[]

// * link:https://access.redhat.com/errata/[]

// * link:https://access.redhat.com/errata/[]

// * link:https://access.redhat.com/errata/[]
