[[aap-25-20250827]]

= {PlatformNameShort} patch release August 27, 2025

This release includes the following components and versions:

[cols="1a,3a", options="header"]
|===
| Release date | Component versions

| August 27, 2025| 
* {ControllerNameStart} 4.6.19
* {HubNameStart} 4.10.7
* {EDAName} 1.1.13
* Container-based installer {PlatformNameShort} (bundle) 2.5-18
* Container-based installer {PlatformNameShort} (online) 2.5-18
* Receptor 1.5.7
* RPM-based installer {PlatformNameShort} (bundle) 2.5-17
* RPM-based installer {PlatformNameShort} (online) 2.5-17

|===

CSV Versions in this release:

* Namespace-scoped Bundle: aap-operator.v2.5.0-0.1755835086

* Cluster-scoped Bundle: aap-operator.v2.5.0-0.1755835623




== General

* The `ansible.controller` collection has been updated to 4.6.19.(AAP-51863)

* The `ansible.eda` collection has been updated to 2.9.0.(AAP-51859)



== CVE

With this update, the following CVEs have been addressed:

* link:https://access.redhat.com/security/cve/CVE-2025-48432[CVE-2025-48432] `python3.11-django`: Django Path Injection Vulnerability.(AAP-50994)

* link:https://access.redhat.com/security/cve/CVE-2025-47273[CVE-2025-47273] `automation-controller`: Path Traversal Vulnerability in setuptools `PackageIndex`.(AAP-47384)




== {PlatformNameShort}

=== Features

* Added a new field on *Azure AD* authenticator called `Field to use as username` which allows you to use an arbitrary field from the assertion as the username in {PlatformNameShort}.(AAP-49481)


=== Enhancements

* Enhanced Support for Streaming Chat Responses in {PlatformNameShort}. New settings added:

** `stream_idle_timeout`: Controls timeout for idle streaming connections.
** `max_stream_duration`: Sets maximum duration for streaming connections. +
    (AAP-51756)

* Allow for HTTP headers to be passed through *envoy* when https is offloaded by another device in front of *envoy*. This introduces two new settings:

** `SECURE_PROXY_SSL_HEADER` indicating which headers should be allowed through. The defaults are `HTTP_X_FORWARDED_PROTO`, `https`.

** `XDS_XFF_NUM_TRUSTED_HOPS` which says how many entries in the headers should be trusted. The default is 0 if there is only one device in front of *envoy*. Set to 1 if there are more, or increase as needed. These settings can only be changed in the `/etc/ansible-automation-platform/gateway/settings.py` file. +
(AAP-51347)




=== Bug fixes

* Fixed an issue where the *OpenAPI* spec did not reflect all query parameters available.(AAP-49824)

* Fixed an issue where the `LOGIN_REDIRECT_OVERRIDE` was not being respected.(AAP-49726)

* Fixed an issue where the breadcrumb in a launch template sent users to the wrong URL.(AAP-44194)

* Fixed an issue where legacy users were not properly migrated to {Gateway} in some scenarios that were previously leaving the users in a partly migrated state.(AAP-43251)

* Fixed an issue where the LDAP filter splitter/validator did not handle some valid filters.(AAP-51591)

* Fixed an issue that removes the `required` label from the organization field for galaxy credentials in {ControllerName} credential create and edit forms.(AAP-51587)

* Fixed an issue where subscription entitlement window displayed again after {PlatformNameShort} had been entitled when running in a load-balanced environment with multiple controller web pods.(AAP-43883)

* Fixed an issue that did not allow all users to see the notifiers tab.(AAP-41342)

* Fixed an issue where there was no limit field on the job details page.(AAP-36118)



== {OperatorPlatformNameShort}

== Bug fixes

* Fixed an issue in the *PostgreSQL* password encryption when upgrading from PG13 to PG15 on FIPS.(AAP-50443)

* Fixed an issue where requests time out at client or proxy, but work continues long past the timeout.(AAP-50311)

* Fixed an issue to align *NGINX* and web server timeouts to avoid issues where requests time out but work continues on already timed out requests.(AAP-50310)

* Fixed an issue to align *envoy*, *NGINX*, web server, and `jwt` token timeouts to avoid issues where requests time out but work continues or tokens expire before they are used.(AAP-50309)

* Fixed an issue to align web server timeouts to avoid issues where requests time out at client or proxy, but work continues long past the timeout.(AAP-50308)

* Fixed backup and restores for deployments with external databases and refactored the tasks for managed database restores to be a separate code path.(AAP-50299)

* Fixed an issue where the {Gateway} operator `client_request_timeout` was not the same as `haproxy` timeout in {OCPShort}.(AAP-51749)



== {ControllerNameStart}

=== Bug Fixes

* Fixed regression in `ansible.controller` collection where the argument `controller_oauthtoken` was wrongfully removed.

** Fixed newly added `aap_token` to function the same as `controller_oauthtoken`.

** Fixed the `ansible.controller.controller_api` lookup plugin. +
    (AAP-51289)

* Fixed an issue where the {Galaxy} credentials could not be created and edited without specifying an organization.(AAP-51614)

* Fixed an issue where the subscription is attached before subscription credentials have been set, returned a *400 Bad Request*.(AAP-50322)



== Container-based {PlatformNameShort}

=== Enhancements

* Implemented *PostgreSQL* extra settings parameter on the installer.(AAP-51533)


=== Bug Fixes

* Fixed an issue where the *PostgreSQL* version failed during preflight with a customer provided CA certificate.(AAP-50884)

* Fixed `pcp` data permissions by migrating the data to a *Podman* volume instead of a bind mount.(AAP-50807)

* Fixed an issue where the backup script incorrectly Included `.snapshot` directories in the {HubName} backup.(AAP-50784)

* Fixed a bug where the *Redis* hostname fails to be set in a disconnected environment.(AAP-51532)

* Fixed an issue where there was no exclusion parameter for containerized backup, that allowed users to specify snapshot paths to be excluded from the backup process.(AAP-46767)


== {EDAName}

=== Bug Fixes

* Fixed an issue where `MQ_TLS` did not accept a boolean value.(AAP-51012)

* Fixed an issue where project import state may become stuck at pending or running.(AAP-51643)

* Fixed an issue where `%20` is not permitted in project git URL.(AAP-51642)

* Fix an issue where a user who belongs to a team with an {EDAName} organization project admin role could not see the organization.(AAP-50921)


== RPM-based {PlatformNameShort}

=== Enhancements

* Added `postgres_extra_settings` for `postgresql.conf` customization for managed database installations.(AAP-51462)

=== Bug Fixes

* Fixed an issue where {ControllerName} nodes set to a deprovision state were not removed from the {Gateway} registry.(AAP-51461)

* Fixed an issue where the missing RPM dependency for *PostgreSQL* client which resulted in container images missing `psql` binary.(AAP-50941)

* Fixed an issue where disabling `https` for {Gateway} and/or {Gateway} proxy (*envoy*) caused installation failures.(AAP-48606)
