[[aap-25-20250129]]

= {PlatformNameShort} patch release January 29, 2025

The following enhancements and bug fixes have been implemented in this release of {PlatformNameShort}.

== Enhancements

=== {PlatformNameShort}

* Using PostgreSQL TLS certificate authentication with an external database is now available.(AAP-38400)


=== {EDAName}

* The `ansible.eda` collection has been updated to 2.3.1.(AAP-39057)
* Users are now able to create a new {EDAName} credential by copying an existing one.(AAP-39249)
* Added support for *file* and *env* injectors for credentials.(AAP-39091)


=== RPM-based {PlatformNameShort}

* Implemented certificate authentication support (mTLS) for external databases.
** Postgresql TLS certificate authentication is available for external databases.
** Postgresql TLS certificate authentication can be turned on/off (off by default for backward compatibility).
** Each component, {ControllerName}, {EDAName}, {Gateway}, and {HubName}, now provides off the shelf (OTS) TLS certificate and key files (mandatory).(AAP-38400)


== Bug fixes

=== CVE

With this update, the following CVEs have been addressed:

* link:https://access.redhat.com/security/cve/cve-2024-56326[CVE-2024-56326] `python-jinja2`: Jinja has a sandbox breakout through indirect reference to format method.(AAP-38852)

* CVE-2024-56374 `ansible-lightspeed-container`: Potential denial-of-service vulnerability in IPv6 validation.(AAP-38647)

* CVE-2024-56374 `python-django`: potential denial-of-service vulnerability in IPv6 validation.(AAP-38630)

* link:https://access.redhat.com/security/cve/cve-2024-53907[CVE-2024-53907] `python3.11-django`: Potential denial-of-service in django.utils.html.strip_tags().(AAP-38486)

* link:https://access.redhat.com/security/cve/cve-2024-56201[CVE-2024-56201] `python3.11-jinja2`: Jinja has a sandbox breakout through malicious filenames.(AAP-38331)

* CVE-2024-56374 `automation-controller`: Potential denial-of-service vulnerability in IPv6 validation.(AAP-38648)

* link:https://access.redhat.com/security/cve/cve-2024-56201[CVE-2024-56201] `automation-controller`: Jinja has a sandbox breakout through malicious filenames.(AAP-38081)

* link:https://access.redhat.com/security/cve/cve-2024-56326[CVE-2024-56326] `automation-controller`: Jinja has a sandbox breakout through indirect reference to format method.(AAP-38058)



=== {ControllerNameStart}

* Fixed an issue where the order of source inventories was not respected by the collection `ansible.controller`.(AAP-38524)

* Fixed an issue where an actively running job on an execution node may have had its folder deleted by a system task. This fix addresses some *Failed to JSON parse a line from worker stream* type errors.(AAP-38137)

* Fixed an issue where deprecation errors on CI checks in {ControllerName} were not ignored.(AAP-36522)

* Fixed an issue where sanity tests were failing on the latest version {ControllerName}.(AAP-36516)



=== Container-based {PlatformNameShort}

* The inventory file variable *postgresql_admin_username* is no longer required when using an external database. If you do not have database administrator credentials, you can supply the database credentials for each component in the inventory file instead.(AAP-39077)


=== {EDAName}

* Fixed an issue where the application version in the *openapi* spec was incorrectly set.(AAP-38392)

* Fixed an issue where activations were not properly updated in some scenarios with a high load of the system. (AAP-38374)

* Fixed an issue where users were unable to filter *Rule Audits* by rulebook activation name.(AAP-39253)

* Fixed an issue where the input field of the injector configuration could not be empty.(AAP-39086)


=== RPM-based {PlatformNameShort}

* Fixed an issue where setting `automationedacontroller_max_running_activations` could cause the installer to fail. (AAP-38708)

* Fixed an issue where the {Gateway} services are not restarted when a dependency changes.(AAP-38918)

* Fixed an issue where the {Gateway} could not be setup with custom SSL certificates.(AAP-38985)

