[[aap-25-20250507]]

= {PlatformNameShort} patch release May 7, 2025

This release includes the following components and versions:

[cols="1a,3a", options="header"]
|===
| Release date | Component versions

| May 7, 2025 | 
* {ControllerNameStart} 4.6.12
* {HubNameStart} 4.10.4
* {EDAName} 1.1.8
* Container-based installer {PlatformNameShort} (bundle) 2.5-13
* Container-based installer {PlatformNameShort} (online) 2.5-13
* Receptor 1.5.5
* RPM-based installer {PlatformNameShort} (bundle) 2.5-12
* RPM-based installer {PlatformNameShort} (online) 2.5-12

|===

CSV Versions in this release:

* Namespace-scoped Bundle: aap-operator.v2.5.0-0.1746137767

* Cluster-scoped Bundle: aap-operator.v2.5.0-0.1746138413


== General

* Implemented GitHub application credential type.(AAP-38589)

* The `ansible.platform` collection has been updated to 2.5.20250507.(AAP-44992)

* The `ansible.controller` collection has been updated to 4.6.12.

* The `ansible.eda` collection has been updated to 2.7.0.


== Technology Preview

=== Policy as Code

Policy enforcement is available in tech preview, behind a feature flag. See the link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/configuring_automation_execution/controller-pac#enable-pac_controller-pac[product documentation] and the Knowledgebase article link:https://access.redhat.com/articles/7109282[How to set feature flags for {PlatformName}] for information on working with feature flags.

== Features

=== {PlatformNameShort}

* Added an enhanced log viewer for rulebook activation instances similar to the job output logger.(AAP-43337)

=== Container-based {PlatformNameShort}

* Implemented a playbook to collect sos reports using the inventory file.(AAP-42606)


=== {EDAName}

* {EDAName} now submits analytics data.(AAP-40881)

* Enabled {EDAName} analytics data to be uploaded to the cloud. This feature is guarded by a feature flag.(AAP-42468)

* Added a log tracking id to each log message labelled as `[tid: uuid-pattern]`.(AAP-42270)

* Improved the user experience of managing rulebook activations in {EDAName} by introducing an edit capability.(AAP-33067)

* The following datapoints {EDAName} now collects for analytics for MVP:

** Eventsources used in {EDAName}.

** Eventstreams used in {EDAName}.

** Version of {EDAName} installed.

** Installation type (container/OCP/VM).

** Platform organizations in {EDAName}.

** Which {ControllerName} job template was launched from a rulebook activation.(AAP-31458)

* {EDAName} `gather_analytics` command now runs on schedule as an internal task.(AAP-30063)

* {EDAName} now writes analytics data collector that sends payloads to *console.redhat.com*.(AAP-30055)

* Add `x-request-id` to each log message labelled as `[rid:uuid-pattern]`.(AAP-42269)


== Enhancements


=== {PlatformNameShort}

* Updated {Gateway} to adopt selected standard component for settings mechanism.(AAP-34939)

* Refactored the `authenticate()` method inside the `AuthenticatorPlugin` class in `legacy_password.py` and `legacy_sso.py` to their common parent `LegacyMixin`. Added comments to classes and their methods for code clarity.(AAP-44460)


=== {OperatorPlatformNameShort}

* Fixed an issue where the Lightspeed Operator would not use the `ANSIBLE_AI_MODEL_MESH_CONFIG`.(AAP-41335)

* Extended CCSP and renewal guidance reports to include inventory scope and node/host details.(AAP-38802)


=== {ControllerNameStart}

* Updated the pinned version of `receptorctl` in {ControllerName} to 1.5.5.(AAP-44823)

* Updated the pinned version for `ansible-runner` in {ControllerName}.(AAP-43357)


=== Container-based {PlatformNameShort}

* Added new variable `use_archive_compression` with default `value: true`. Added new variable component `Name_use_archive_compression` for each component with the default `value: true`.(AAP-41242)


=== {EDAName}

* {EDAName} collection standardization enhancements.(AAP-41402)

* Relevant settings and versions are emitted in logs when the ansible-rulebook starts in worker mode.(AAP-40781)

* Added log entries with settings and version at startup.(AAP-40781)

* Enhanced the {PlatformNameShort} injectors for `eda-server` to include common platform variables as `extra_vars` or environment variables if they are specified.(AAP-43029)

* {EDAName} decision environment validation errors now display under the decision environment text box in the decision environment UI page.(AAP-42147)

* Added a {ControllerName} URL check for the CLI.(AAP-41575)

* If a source plugin terminates you are now able to see the stack trace with the source file name, the function name, and line number.(AAP-41774)


=== RPM-based {PlatformNameShort}

* Added compression for archive and database artifacts used in backup/restore

** Updated database filename used for {ControllerName} `pg_dump` from tower to {ControllerName} while maintaining backward compatibility for backups using `tower.db` filename.(AAP-42055)


== Bug fixes

With this update, the following CVEs have been addressed:

link:https://access.redhat.com/security/cve/cve-2025-26699[CVE-2025-26699] `automation-controller`: Potential denial-of-service vulnerability in `django.utils.text.wrap()`.(AAP-41139)


=== {PlatformNameShort}

* Fixed an issue where In AAP 2.5, the user needed to press Ctrl+Enter to start a new line.(AAP-43499)

* Fixed an issue where the change anchor tag on API html view violated semantic rules.  (AAP-43802)

* LDAP Authenticator field `USER_SEARCH` field now properly supports LDAP Unions. Previously you could only define one search term in the field like:

----
[
  "ou=users,dc=example,dc=com",
  "SCOPE_SUBTREE",
  "uid=%(user)s"
]

[
    "ou=users,dc=example,dc=com",
    "SCOPE_SUBTREE",
    "uid=%(user)s"
  ],
   [
    "ou=users,dc=example,dc=com",
    "SCOPE_SUBTREE",
    "uid=%(user)s"
  ]
]
----

* `USER_DN_TEMPLATE` will still take precedence over the `USER_SEARCH` field. If non-unique users are found when performing multiple searches, those users will be unable to login to {PlatformNameShort}.(AAP-42883)

* Fixed an issue where there was a file not found error with Dynaconf.(AP-43144)

* Fixed an issue where dynaconf mishandled the openapi schema.(AAP-43143)

* Fixed an issue when editing an authenticator with a large number of Organization/Team mappings in platform-gateway would affect the loading time of the web page, potentially making the page unresponsive.(AAP-40963)

* Fixed an issue where unreachable hosts were not being filtered out of CCSP reports usage.(AAP-38735)

* Fixed an issue where the `X-DAB-JW-TOKEN` header message would flood logs.(AAP-38169)

* Fixed an issue where after upgrading to {PlatformNameShort} 2.5 managed on Azure, the ability to see job output while the job was running was lost. (AAP-43894)

* Fixed an issue where customers were not allowed to view output details for filtered job outputs.(AAP-38925)

* Fixed an issue where unreachable hosts from CCSP usage reports were not excluded.(AAP-38735)

* Fixed an issue where indirect hosts were being counted in the first tab as quantity.(AAP-44676)

* Fixed an issue where the platform-gateway could not be installed with a different name for the admin user.(AAP-44180)

* Fixed an issue where an {PlatformNameShort} UI session was being logged out even if the user is actively working.(AAP-43622)

* Fixed an issue where exceptions handled on SSO login were not allowing for error messages to be properly captured.(AAP-43369)

* Fixed an issue where the job output was slow and making it hard to read due to missing parts of the output.(AAP-41434)

* Fixed an issue where the user was unable to edit an existing rulebook activation.(AAP-37299)



=== {OperatorPlatformNameShort}

* Fixed an issue where the pod affinity/anti-affinity was not configurable for the aap-gateway-operator to allow for pod placement on unique nodes.(AAP-42983)

* Fixed an issue where {LightspeedShortName} was incorrectly passing DAB settings.(AAP-43542)

* Fixed an issue where the Lightspeed Operator WCA configuration was not optional.(AAP-42370)

* Fixed an issue where `status.conditions` validation would not allow auto-reporting errors on CR statuses.(AAP-44081)

* Fixed an issue where the {PlatformNameShort} gateway had the incorrect Lightspeed deployment name.(AAP-43837)

* Fixed an issue where Lightspeed devel CRD was incompatible with 2.5 CRD.(AAP-43657)

* Fixed an issue where `status.conditions` validation was not allowing auto-reporting errors on the CR statuses.(AAP-44083)

* If the user is migrating between {OCPShort} Operator on AAP 2.5 fails because of a postgres permission issue. The {ControllerName} operator now grants permission to the {ControllerName} user to avoid permissions errors when migrating the data.(AAP-44846)

* Fixed an issue where there was an Intermittent *502 Bad Gateway* error on {PlatformNameShort} 2.5 operator deployment.(AAP-44176)



=== {ControllerNameStart}

* Fixed usage of Django password validator `UserAttributeSimilarityValidator`.(AAP-43046)

* Fixed an issue where there was no lookup credential without user Inputs, and where the credential defaults were not passing between awx-plugins and AWX.(AAP-38589)

* Fixed an issue where there was an incorrect deprecation warning for `awx.awx.schedule_rrule`.(AAP-43474)

* Fixed an issue where facts were unintentionally deleted when an inventory is modified during a job execution.(AAP-39365)



=== Container based {PlatformNameShort}

* Fixed an issue where the paths to expose isolated jobs' settings did not work.(AAP-37599)

The ansible.gateway_configuration collection was replaced by ansible.platform.(AAP-44230)

* Fixed an issue where the automation hub would fail to upload collections due to a missing worker temporary directory.(AAP-44166)



=== {EDAName}

* Fixed an issue where the log messages were not using the correct log level.(AAP-43607)

* Fixed an issue where the *ansible-rulebook* logs were not logged into the activation-worker log.(AAP-43549)

* Fixed an issue where the container was not always deleted correctly, or it missed the last output entries in VM based installations.(AAP-42935)

* Fixed an issue where {EDAName} logging did not allow searching.(AAP-43338)

* Fixed an issue where the rulebook activations and event streams would not remain due to a cascading delete after the user who created them was deleted.(AAP-41769)

* Fixed an issue where the decision environment was not using the image to authenticate and pull successfully when using an image registry with a custom port.(AAP-41281)

* Fixed an issue where timestamps were not formatted to the local timezone of the user.(AAP-38396)

* Fixed an issue where the activation failed with the message *It will attempt to restart (1/5) in 60 seconds according to the restart policy always*, but it does not restart.(AAP-43969)

* Fixed an issue where a race condition would occur while cleaning up activation in {OCPShort}, causing unexpected behavior.(AAP-44108)

* Fixed an issue where the {EDAName} logs showed no information about an internal server error.(AAP-42271)

* Fixed an issue where there was a duplicate error message in the CLI.(AAP-41745)

* Fixed an issue where Envoy was stripping the `Authorization` header from client requests.(AAP-44700)

* Fixed an issue where {EDAName} had not selected a standard component for settings mechanism.(AAP-41684)

* Fixed an issue where documentation was missing for {EDAName} source plugins.(AAP-8630)

* Fixed an issue where there was a memory leak in {EDAName} using the *ansible-rulebook* `sqs` plugin.(AAP-42623)

* Fixed an issue where rulebook activations were not editable or copyable either through the UI or API.(AAP-37294)

* Fixed an issue where the rule engine used in *ansible-rulebook* was keeping events that do not match in memory for the `default_events_ttl` of two hours causing a memory leak.(AAP-44899)

* Fixed an issue where there was a memory leak in {EDAName} using *ansible-rulebook* `sqs` plugin.(AAP-44899)

* Fixed an issue where the rulebook activation module in the {EDAName} collection lacked support for restarting the activation.(AAP-42542)

* Fixed an issue where AAP aliases were unable to be used to specify {EDAName} collection variables.(AAP-42280)



=== {LightspeedShortName} Operator

* Fixed an issue where the `auth_config_secret_name` configuration in Lightspeed Operator was not optional in the {ControllerName}.(AAP-44203)


=== Receptor

* Fixed an issue where the kube API would lock up on every call by moving `kubeAPIWapperInstance` inside each `kubeUnit` and removing `kubeAPIWapperlocks`.(AAP-43111)


=== RPM-based {PlatformNameShort}

* Fixed an issue where {Gateway} services were not aligned after restore with the target environment.

** Fixed an issue where old instance nodes were still registered in {ControllerName} post restore.

** Fixed an issue where *nginx* would attempt to reload before the configuration was finalized.(AAP-44231)




