[[aap-25-20250305]]

= {PlatformNameShort} patch release March 01, 2025

This release includes the following components and versions:

[cols="1a,3a", options="header"]
|===
| Release date | Component versions

| March 01, 2025  | 
* {ControllerNameStart} 4.6.8
* {HubNameStart} 4.10.1
* {EDAName} 1.1.4
* Container-based installer {PlatformNameShort} (bundle) 2.5-10.2
* Container-based installer {PlatformNameShort} (online) 2.5-10
* Receptor 1.5.1
* RPM-based installer {PlatformNameShort} (bundle) 2.5-8.3
* RPM-based installer {PlatformNameShort} (online) 2.5-8

|===

CSV versions in this release:

* Namespace-scoped bundle: `aap-operator.v2.5.0-0.1740773472`

* Cluster-scoped bundle: `aap-operator.v2.5.0-0.1740774104`

[IMPORTANT]
====
An issue was found in affected versions of {PlatformNameShort} that enabled a lesser privileged user (even unauthenticated) promotion to a greater privileged user. All {PlatformNameShort} {PlatformVers} customers should upgrade their environments to the latest version as soon as possible to resolve this issue. 
{AAPonAzureNameShort} and {SaaSonAWSShort} environments are already patched by Red Hat.
====

The following bug fixes have been implemented in this release of {PlatformNameShort}:

== Bug fixes

=== CVE

With this update, the following CVE has been addressed:

* link:https://access.redhat.com/security/cve/CVE-2025-1801[CVE-2025-1801] `automation-gateway`: `aap-gateway` privilege escalation. (AAP-41180)

=== {GatewayStart}

* Fixed an issue that caused the API to randomly return 401 errors. (AAP-41054)
