[[aap-25-20250609]]

= {PlatformNameShort} patch release June 9, 2025

This release includes the following components and versions:

[cols="1a,3a", options="header"]
|===
| Release date | Component versions

| June 9, 2025| 
* {ControllerNameStart} 4.6.14
* {HubNameStart} 4.10.4
* {EDAName} 1.1.9
* Container-based installer {PlatformNameShort} (bundle) 2.5-15
* Container-based installer {PlatformNameShort} (online) 2.5-15
* Receptor 1.5.5
* RPM-based installer {PlatformNameShort} (bundle) 2.5-14
* RPM-based installer {PlatformNameShort} (online) 2.5-14

|===

CSV Versions in this release:

* Namespace-scoped Bundle: aap-operator.v2.5.0-0.1749074128

* Cluster-scoped Bundle: aap-operator.v2.5.0-0.1749074612


== General

* The `ansible.controller` collection has been updated to 4.6.14 (AAP-46562)

* The `ansible.platform` collection has been updated to 2.5.20250604 (AAP-46552)


== {PlatformNameShort}

=== Features

* Adds `ansible_base.lib.utils.address.classify_address` providing common recognition and parsing of machine addressing hostname, IPv4 and IPv6 with and without an appended `:<port>`.(AAP-45910)


=== Enhancements

* LDAP filter validation improved such that all filters that meet LDAP standards including and/or should be properly validated.(AAP-46249)

* Completely updated interface for managing authentication methods and mappings.(AAP-45750)

* Default validity period for *Oauth* tokens reduced from 1000 years to 1 year. Existing tokens will NOT be updated. If you wish to reduce the validity period of existing tokens, please remove and re-issue them. The default validity period for *Oauth* tokens can be modified via the django setting `ACCESS_TOKEN_EXPIRE_SECONDS in OAUTH2_PROVIDER`.(AAP-46187)


=== Bug fixes

* Fixed an issue where there was a degraded logging performance notice removed on the job output page. Polling fallback functionality still exists.(AAP-46120)

* Fixed an issue where the gateway proxy was not properly ejecting nodes failing health checks.(AAP-43931)

* Fixed an issue where installations with {LightspeedShortName} enabled were not handled properly during upgrade.(AAP-46154)


== {ControllerNameStart}


=== Enhancements

* Updated license mechanism to allow users to provide username and password when fetching subscriptions via the API and {PlatformNameShort} user interface.(AAP-46797)


=== Bug Fixes

* Fixed an issue where the idle dispatch workers were not recycled based upon age, or after completing the last task. Default maximum age is 4 hours, controlled by `WORKER_MAX_LIFETIME_SECONDS` setting. Set to None to disable worker recycling.(AAP-45947)

* Fixed an analytics collector failure to clean up temporary files after failed upload to Hybrid Cloud console.(AAP-45574)

* Fixed an issue where inventory variables pulled in by update from a source with the option *Overwrite Variables* checked, were not deleted on subsequent updates from the same source when the source no longer contained the variable.(AAP-45571)


== Container-based {PlatformNameShort}


=== Enhancements

* Allow users to skip {ControllerName} demo data creation.(AAP-46482)

* Validating the {HubNameStart} NFS share path format during the preflight role execution.(AAP-46306)


=== Bug Fixes

* Fixed an issue where the custom Certificate Authority (CA) TLS certificate was not passed to the external database validation during the preflight role execution.(AAP-46480)

* Fixed a log redirection error for the {HubNameMain}, {EDAName}, and Unified UI containers.(AAP-46478)

* Fixed an issue where `~/.local/bin` path was not added to the user $`PATH` environment variable during PostgreSQL database dump and restore.(AAP-46209)

* Fixed the order of operations for handling service nodes to ensure only valid nodes are configured.(AAP-45551)


== {EDAName}

=== Enhancements

* Rename env `EDA_OIDC_TOKEN_URL` to  `DA_AUTOMATION_ANALYTICS_OIDC_TOKEN_URL`.(AAP-44862)


=== Bug Fixes

* Fixed an issue where the activation containers were not removed after a node goes offline.(AAP-45831)

* Fixed an issue where the error reminding user to remap source with event stream should be under key source_mapping in the API return.(AAP-45105)

* Fixed an issue where special characters such as `[]` were not allowed in the activation name on OCP deployment.(AAP-44691)


== RPM-based {PlatformNameShort}

=== Enhancements

* Setup will now retry automation gateway data migration attempts in case services take longer than expected to start.(AAP-46208)


=== Bug Fixes

* Fixed an issue Event stream worker would not restart like other workers when running setup.sh.(AAP-46205)

* Fixed an issue where setup would not restart the podman socket whenever podman was reset.(AAP-46191)
