[[aap-25-20250213]]

= {PlatformNameShort} patch release February 13, 2025

This release includes the following components and versions:

[cols="1a,3a", options="header"]
|===
| Release Date | Component versions

| February 13, 2025  | 
* {ControllerNameStart} 4.6.8
* {HubNameStart} 4.10.1
* {EDAName} 1.1.4
* Container-based installer {PlatformNameShort} (bundle) 2.5-10
* Container-based installer {PlatformNameShort} (online) 2.5-10
* Receptor 1.5.1
* RPM-based installer {PlatformNameShort} (bundle) 2.5-8.1
* RPM-based installer {PlatformNameShort} (online) 2.5-8

|===

CSV Versions in this release:

* Namespace-scoped Bundle: `aap-operator.v2.5.0-0.1738808953`

* Cluster-scoped Bundle: `aap-operator.v2.5.0-0.1738809624`

The following enhancements and bug fixes have been implemented in this release of {PlatformNameShort}.


== New Features

=== {PlatformNameShort}

Keycloak now allows for the configuration of the claim key/name for the field containing a user's group membership returned in the ID token and/or user info data. This can be configured by setting the `GROUPS_CLAIM` configuration value on a per-authenticator plugin basis as was done for the OIDC plugin.(AAP-38720)

== Enhancements

=== General

* The `ansible.controller` collection has been updated to 4.6.8.(AAP-39848)

* `ansible.platform` collection has been updated to 2.5.20250213.(AAP-39740)

=== {PlatformNameShort}

* It is now possible to configure {HubName} without Redis PVC.(AAP-39600)


=== {ControllerNameStart}

* This release sees the addition of `client_id` and `client_secret` fields to the Insights credential to support service accounts via console.redhat.com.(AAP-36565)

* You are now able to specify the input for the `client_id` and `client_secret` for the insights credential via the `awx.awx.credential_type` module.(AAP-37441)

* Updated `awxkit` by adding service account support for Insights credential type, specifically adding the fields `client_id` and `client_secret` to `credential_input_fields`.(AAP-39352)

=== {ExecEnvNameStart}

* The *file* command has been added to *ee-minimal* and *ee-supported* container images.(AAP-40009)

== Bug fixes

=== Migration

* Fixed an issue where after upgrading {PlatformNameShort} from 2.4 to 2.5, many of the surveys that had multiple choice options displayed a blank space in the drop down menu.(AAP-35093)

=== {PlatformNameShort}

* Fixed a bug in the collections token module where it was unable to find an application if multiple organizations had the same application name.(AAP-38625)

* Fixed an issue where upgrading {PlatformNameShort} 2.5 caused an occasional internal server error for all users with {EDAName} and {HubNameStart} post upgrade.(AAP-39293)

* Fixed an issue where the administrator was not allowed to configure auto migration of legacy authenticators.(AAP-39949)

* Fixed an issue where there were two launch/relaunch icons displayed from the jobs list for failed jobs.(AAP-38483)

* Fixed an issue where the *Schedules Add* wizard returned a `RequestError` *Not Found*.(AAP-37909)

* Fixed an issue where the *EC2 Inventory Source* type required credentials, which is not necessary when using IAM instance profiles.(AAP-37346)

* Fixed an issue when attempting to assign the *Automation Decisions - Organization Admin* role to a user in an organization resulted in the error, *Not managed locally, use the resource server instead*. Administrators can now be added by using the *Organization -> Administrators* tab.(AAP-37106)

* Fixed an issue where when updating a workflow node, the Job Tags were lost and Skip Tags were not saved.(AAP-35956)

* Fixed an issue where new users who logged in with legacy authentication were not merged when switching to Gateway authentication.(AAP-40120)

* Fixed an issue where the user was unable to link legacy SSO accounts to Gateway.(AAP-40050)

* Fixed an issue where updating {PlatformNameShort} to 2.5 caused an Internal Service Error for all users with {EDAName} and {HubNameStart} post upgrade. The migration process will now detect and fix users who were created in services via JWT auth and improperly linked to the service instead of the {Gateway}.(AAP-39914)


=== {OperatorPlatformNameShort}

* Fixed an issue where `AnsibleWorkflow` custom resources would not parse and utilize `extra_vars` if specified.(AAP-39005)

=== {ControllerNameStart}

* Fixed an issue where when an Azure credential was created using `awxkit`, the creation failed because the parameter `client_id` was added to the input fields while the API was not expecting it.(AAP-39846)

* Fixed an issue where the job schedules were running at incorrect times when that schedule's start time fell within a Daylight Saving Time period.(AAP-39826)


=== {HubNameStart}

* Fixed an issue where the use of empty usernames and passwords when creating a remote registry was not allowed.(AAP-26462)


=== Container-based {PlatformNameShort}

* Fixed an issue where the containerized installer had no preflight check for the Postgres version of an external database.(AAP-39727)

* Fixed an issue where the containerized installer could not register other peers in the database.(AAP-39470)

* Fixed an issue where there was a missing installation user UID check.(AAP-39393)

* Fixed an issue where Postgresql connection errors would be hidden during its configuration.(AAP-39389)

* Fixed an issue in the preflight check regression when the TLS private key provided is not an RSA type.(AAP-39816)
 

=== {EDAName}

* Fixed an issue where the btn:[Generate extra vars] button did not handle file/env injected credentials.(AAP-36003)

=== Known Issues

* In the {Gateway}, the tooltip for *Projects -> Create Project - Project Base Path* is undefined.(AAP-27631)

* Deploying the {Gateway} on FIPS enabled RHEL 9 is currently not supported.(AAP-39146)
