:_mod-docs-content-type: CONCEPT

[id="con-aws-update-restore-data-file"]

= Updating the restore data file

You must populate the data file before triggering the restore. 
The following variables are parameters listed in the data file.

* `ansible_config_path` (Optional) Only use if overriding with a custom `ansible_config`.
* `cloud_credentials_path` is the path to your AWS credentials file.
* `deployment_name` is the name you want for your restored deployment
* `aws_backup_iam_role_arn` (Optional) is the _Amazon Resource Name_ (ARN) of the AWS IAM Role that has permissions to perform backup operations.
+
[NOTE]
====
If provided, the playbook defaults to this value over the value of the IAM role referenced in the backup file on S3. For further information, see xref:con-aws-backup-process[Backing up the {PlatformNameShort} deployment]
====
+
* `aws_backup_name` is the name of the backup folder stored on S3. This value was outputted after running the backup playbook. 
* `aws_backup_restore_point_arn` (Optional) is the ARN of the of the EFS recovery point you want to use for restore.
+
[NOTE]
====
If provided, the playbook defaults to this value over the EFS restore point referenced in the backup file on S3. 
See xref:ref-aws-permissions[AWS permissions].

You must also ensure that the provided restore point is from a version of Ansible on Clouds (AoC) that matches the version of the ansible-on-clouds-ops container image running the restore. 
For example, a restore point taken from a deployment on AoC version {ImageRef}-00 needs to use the `ansible-on-clouds-ops` container image version `{ImageRef}`.
====
+
* `aws_backup_vault_name` (Optional) is the name of the backup vault that holds the EFS recovery points.
+
[NOTE]
====
If provided, the playbook defaults to this value over the backup vault referenced in the backup file on S3 which was generated when running the backup operation. See xref:ref-aws-permissions[AWS permissions].
You must also ensure that this backup vault matches the one used to backup the deployment.
====
+
* `aws_rds_db_snapshot_arn` (Optional) is the ARN of the RDS snapshot you want to use for restore.
+
[NOTE]
====
If provided, the playbook defaults to this value over the RDS snapshot referenced in the backup file on S3. 
You must also ensure that the provided RDS snapshot is from a version of Ansible on Clouds that matches the version of the `ansible-on-clouds-ops` container image running the restore. 
For example, an RDS snapshot taken from a deployment on AoC version {ImageRef}-00 needs to use the `ansible-on-clouds-ops` container image version `{ImageRef}`.
====
+
* `aws_region` is the region where the foundation deployment is deployed.
* `aws_s3_bucket` is the name of the S3 bucket where the backup files are stored.
This must be the same bucket used for backup.
* `aws_ssm_bucket_name` is the name of the S3 bucket where temporary configuration files for the AWS SSM are stored. You can use an existing bucket or create a new one.
+
[NOTE]
====
The `aws_ssm_bucket_name` parameter is ONLY used to store temporary config files. It does NOT need to be saved for use in other playbooks. Any valid existing bucket can be used. For more information on creating S3 buckets, read link:https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-overview.html[AWS Creating A Bucket] in the AWS documentation.
====
+
When you have populated the data file, it should resemble the following. 
The values in this file are provided as examples. 
+
[NOTE]
====
The optional values in this data file example have been removed. If you do not wish to use these optional values and want to use the default values for these variables, you 'must' also remove them for your data file like it was done in the example below. If you wish to use these optional variables, they 'must' be included in the data file and be assigned a value. 
====
+
[literal, options="nowrap" subs="+attributes"]
----
aws_restore_stack:
  cloud_credentials_path: ~/.aws/credentials
  deployment_name: AnsibleAutomationPlatform
  extra_vars:
    aws_backup_name: ansible-automation-platform-bucket-20230706T163309
    aws_region: us-east-1
    aws_s3_bucket: ansible-automation-platform-bucket
    aws_ssm_bucket_name: aap-ssm-bucket
----

