:_mod-docs-content-type: CONCEPT

[id="con-gcp-application-deploy"]

= Application deployment

To launch your offer on the Google Cloud Console, navigate to the marketplace and search for *Red Hat Ansible Automation Platform 2 - Up to 100 Managed Nodes*. After selecting this offer click btn:[Launch].

There are four virtual machines included in this product listing.  
Three n2-standard-2 virtual machines make up the permanent compute components of the solution.  
Additionally, a single ephemeral e2-medium instance is used to run {PlatformName} and Google Cloud deployment workloads. 
This virtual machine is only used during deployment and then is permanently removed from the solution.  
The infrastructure cost for the ephemeral VM is charged at the hourly rate during the periiod that the VM exists, usually less than an hour.

[IMPORTANT]
====
A temporary yet necessary constraint has been placed on the length of deployment names.
This is due to GCP's naming scheme for internal components that make up an {PlatformNameShort} deployment.
Component names based on this naming scheme can get too long and often break naming constraints imposed by other services, creating deployment errors.

The length of the name of your deployment, plus the length of your GCP project name must be less than 35 characters and the length of the deployment name must be less than 30 characters.

The calculation below will help you find the maximum length of the name of an {PlatformNameShort} deployment in your project.

length of deployment name < = (minimum between 30 and 35) - length(gcp project name)
====

There are two methods for deploying the application:

include::proc-gcp-deploy-with-new-vpc.adoc[leveloffset=+1]
include::proc-gcp-deploy-with-existing-vpc.adoc[leveloffset=+1]
