:_mod-docs-content-type: PROCEDURE

[id="proc-gcp-generate-variables"]

= Generating data files by running the ansible-on-clouds-ops container

The following commands generate the required data file.
These commands create a directory, and  an empty data template that, when populated, is used to generate the playbook.

.Procedure
. Create a folder to hold the configuration files.
+
[options="nowrap" subs="+attributes"]
----
$ mkdir command_generator_data
----
. Populate the `command_generator_data` folder with the configuration file template.
+
[NOTE]
====
On Linux, any file or directory created by the command generator is owned by `root:root` by default. To change the ownership of the files and directories, you can run the `sudo chmod` command after the files are created. For more information, read xref:con-tech-note-linux-files-owned-by-root[Command generator - Linux files owned by root].
====
+
[options="nowrap" subs="+attributes"]
----
$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE \
command_generator_vars gcp_setup_logging_monitoring \
--output-data-file /data/logging-monitoring.yml
----


. When you have run these commands, a `command_generator_data/logging-monitoring.yml` template file is created.

+
[NOTE]
====
In the following example file, `ansible_config_path` is optional.
====
+
This template file resembles the following:-
+
[literal, options="nowrap" subs="+attributes"]
----
gcp_setup_logging_monitoring:
  ansible_config_path:
  cloud_credentials_path:
  deployment_name:
  extra_vars:
    components:
    default_collector_interval:
    logging_enabled:
    monitoring_enabled:
----
