:_mod-docs-content-type: PROCEDURE

[id="proc-aws-deploying-extension-nodes"]

= Deploying the extension nodes

.Procedure
. To deploy the extension nodes, run the command generator to generate the CLI command.
+
[literal, options="nowrap" subs="+attributes"]
---- 
$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE command_generator --data-file /data/extra_vars.yml
----
+
Provides the following command:
+
[literal, options="nowrap" subs="+attributes"]
----
-----------------------------------------------
docker run --rm --env PLATFORM=AWS -v ~/.aws/credentials:/home/runner/.aws/credentials:ro \
--env ANSIBLE_CONFIG=../aws-ansible.cfg --env DEPLOYMENT_NAME=AnsibleAutomationPlatform \
--env GENERATE_INVENTORY=true  $IMAGE redhat.ansible_on_clouds.aws_add_extension_nodes \
-e 'aws_foundation_stack_name=AnsibleAutomationPlatform aws_region=us-east-1 \ 
aws_launch_template_name=AnsibleAutomationPlatform-ext-lt1-100 \
aws_autoscaling_group_name=AnsibleAutomationPlatform-ext-asg1-100 \
aws_extension_node_subscription=True aws_offer_type=100 \
aws_ssm_bucket_name=aap-ssm-bucket'
===============================================
----

. Run the supplied command to add the extension nodes.
+
[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm --env PLATFORM=AWS -v ~/.aws/credentials:/home/runner/.aws/credentials:ro \
--env ANSIBLE_CONFIG=../aws-ansible.cfg --env DEPLOYMENT_NAME=AnsibleAutomationPlatform \
--env GENERATE_INVENTORY=true  $IMAGE redhat.ansible_on_clouds.aws_add_extension_nodes \
-e 'aws_foundation_stack_name=AnsibleAutomationPlatform aws_region=us-east-1 \ 
aws_launch_template_name=AnsibleAutomationPlatform-ext-lt1-100 \
aws_autoscaling_group_name=AnsibleAutomationPlatform-ext-asg1-100 \
aws_extension_node_subscription=True aws_offer_type=100 \
aws_ssm_bucket_name=aap-ssm-bucket'
----