:_mod-docs-content-type: PROCEDURE

[id="proc-gcp-additional-configs-replace-tls-certificate"]

= Replacing {ControllerName} and {HubName} VM instances SSL/TLS certificate and key

By default, VM instances are secured with a self-signed SSL/TLS certificate with a validity period of ten years.
When the certificate expires or you want VM instances to use your own certificate, you are required to replace the SSL/TLS certificate and key.

.Procedure
. Navigate to the GCP Secrets Manager Console.
.. Locate and open the secret for the {PlatformNameShort} deployment with the name `*<deployment_name>*-pulp_cert`.
.. Select *NEW VERSION* to add a new version.
.. Enter new SSL/TLS certificate value.
.. Check *Disable all past versions* checkbox.
.. Click btn:[ADD NEW VERSION].
. Navigate to the GCP Secrets Manager Console.
.. Locate and open the secret for the {PlatformNameShort} deployment with the name `*<deployment_name>*-pulp_key`.
.. Select *NEW VERSION* to add a new version.
.. Enter new SSL/TLS key value.
.. Check *Disable all past versions* checkbox.
.. Click btn:[ADD NEW VERSION].
. Change the running {PlatformNameShort} VM instances to use the new SSL/TLS certificate and key.
.. Navigate to the *GCP VM Instances* console.
.. Identify and delete all {ControllerName} and {HubName} VM instances for the {PlatformNameShort} deployment.
.. Wait for the {ControllerName} and {HubName} Instance groups to create new VM instances.
. The new certificate is in use when the new {ControllerName} and {HubName} VM instances reach a _Running_ Instance State.
