:_mod-docs-content-type: PROCEDURE

[id="proc-aws-running-upgrade"]

= Running the upgrade playbook

[NOTE]
=====
{PlatformNameShort} upgrade to {ImageRef} updates the listeners on its internal load balancers. If a resource dependancy was added after installation, this must be temporarily removed to allow the upgrade to succeed. See xref:tech-note-aws-upgrade[technical note] for more detail.
=====


. To run the upgrade, run the command generator to generate the upgrade CLI command:
+
[literal, options="nowrap" subs="+attributes"]
---- 
$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE command_generator --data-file /data/extra_vars.yml
----
+
This generates the following upgrade command:
+
[literal, options="nowrap" subs="+attributes"]
----
-----------------------------------------------
docker run --rm --env PLATFORM=AWS -v ~/.aws/credentials:/home/runner/.aws/credentials:ro --env ANSIBLE_CONFIG=../aws-ansible.cfg --env DEPLOYMENT_NAME=AnsibleAutomationPlatform --env GENERATE_INVENTORY=true  $IMAGE redhat.ansible_on_clouds.aws_upgrade -e 'aws_foundation_stack_name=AnsibleAutomationPlatform aws_region=us-east-1 aws_ssm_bucket_name=aap-ssm-bucket aws_backup_taken=True seller_name=redhatinc'
===============================================
----
. Run the given upgrade command to trigger the upgrade.
+
[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm --env PLATFORM=AWS -v ~/.aws/credentials:/home/runner/.aws/credentials:ro --env ANSIBLE_CONFIG=../aws-ansible.cfg --env DEPLOYMENT_NAME=AnsibleAutomationPlatform --env GENERATE_INVENTORY=true  $IMAGE redhat.ansible_on_clouds.aws_upgrade -e 'aws_foundation_stack_name=AnsibleAutomationPlatform aws_region=us-east-1 aws_ssm_bucket_name=aap-ssm-bucket aws_backup_taken=True seller_name=redhatinc'
----
. The upgrade can take some time to complete, but can take longer depending on the number of extension nodes on the system. 
A successful upgrade is marked by the log below.
+
[literal, options="nowrap" subs="+attributes"]
----
TASK [redhat.ansible_on_clouds.standalone_aws_upgrade : [upgrade] [LOG] upgrade version] ***
ok: [localhost] => {
    "msg": "Successfully upgraded from '2.3.20230221-00' -> '{ImageRef}-00'."
}
----
. Your {AAPonAWS} deployment is now upgraded to a newer version and you can log in to {PlatformName} {ControllerName} and {HubName} using your deployment credentials.


