:_mod-docs-content-type: PROCEDURE

[id="proc-aws-uninstall-postupgrade-rm-launchconfig"]

= Removing the launch configurations

Use the following procedure to remove the old launch configurations.

.Procedure
. In the AWS UI, navigate to the link:https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#LaunchConfigurations[Launch configurations page]. 
Ensure you are in the same region as your stack.
.. Click `View launch configurations` in the popup that appears.
. Identify the *Launch Configuration* corresponding to your {PlatformNameShort} deployment.
.. Search for your deployment name.
These are named `<deployment_name>-hubautoscalegroup-<sufix>` for the hub autoscalegroup launch configuration and `<deployment_name>-controllerautoscalegroup-<sufix>` for the controller autoscalegroup launch configuration.
. Delete the resources.
.. Select the checkbox next to the Launch Configurations.
.. Click btn:[Actions].
.. Click btn:[Delete launch configurations].
.. Confirm the deletion.

