:_mod-docs-content-type: PROCEDURE

[id="proc-gcp-additional-configs-update-admin-password"]

= Changing the default administrator password

The default administrator password for {PlatformNameShort} is generated randomly when {AAPonGCP} is deployed. 
Follow these steps to change the administrator password for both {ControllerName} and {HubName}.

.Procedure
. Navigate to the GCP Secrets Manager Console.
.. Locate and open the secret for the {PlatformNameShort} deployment with the name `*<deployment_name>*-aap-admin`.
.. Select *NEW VERSION* to add a new version.
.. Enter a password secret value.
.. Check *Disable all past versions* checkbox.
.. Click btn:[ADD NEW VERSION].
. Change the running {PlatformNameShort} VM instances to use the new administrator password.
.. Navigate to the *GCP VM Instances* console.
.. Identify and delete one {ControllerName} VM instance and one {HubName} VM instance for the {PlatformNameShort} deployment.
.. Wait for the {ControllerName} and {HubName} Instance groups to create new VM instances.
. The new administrator password can be used when the new {ControllerName} and {HubName} VM instances reach a _Running_ Instance State.