:_mod-docs-content-type: PROCEDURE

[id="proc-gcp-running-upgrade"]

= Running the upgrade playbook

[NOTE]
=====
{PlatformNameShort} upgrade to {ImageRef} updates the protocol of its internal load balancers. If additional networking configurations were added after installation, they can also require updating to ensure connectivity. For more information, read the xref:tech-note-gcp-upgrade[Upgrade note].
=====

. To run the upgrade, run the command generator to generate the upgrade CLI command:
+
[literal, options="nowrap" subs="+attributes"]
---- 
$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE command_generator --data-file /data/extra_vars.yml
----
+
This generates the following command:
+
[literal, options="nowrap" subs="+attributes"]
----
-----------------------------------------------
docker run --rm --env PLATFORM=GCP -v ~/secrets/GCP-secrets.json:/home/runner/.gcp/credentials:ro 
--env ANSIBLE_CONFIG=../gcp-ansible.cfg 
--env DEPLOYMENT_NAME=AnsibleAutomationPlatform 
--env GENERATE_INVENTORY=true  $IMAGE redhat.ansible_on_clouds.gcp_upgrade \
-e 'gcp_deployment_name=AnsibleAutomationPlatform \
gcp_service_account_credentials_json_path=/home/runner/.gcp/credentials \
gcp_compute_region=us-east1 gcp_compute_zone=us-east1-b gcp_backup_taken=True'
===============================================
----
. Run the given upgrade command to trigger the upgrade.
+
[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm --env PLATFORM=GCP -v ~/secrets/GCP-secrets.json:/home/runner/.gcp/credentials:ro \
--env ANSIBLE_CONFIG=../gcp-ansible.cfg \
--env DEPLOYMENT_NAME=AnsibleAutomationPlatform \
--env GENERATE_INVENTORY=true  $IMAGE redhat.ansible_on_clouds.gcp_upgrade \
-e 'gcp_deployment_name=AnsibleAutomationPlatform \
gcp_service_account_credentials_json_path=/home/runner/.gcp/credentials \
gcp_compute_region=us-east1 gcp_compute_zone=us-east1-b gcp_backup_taken=True'
----
. The upgrade can take some time to complete, but can take longer depending on the number of extension nodes on the system. 
A successful upgrade is marked by the log below.
+
[literal, options="nowrap" subs="+attributes"]
----
TASK [redhat.ansible_on_clouds.standalone_gcp_upgrade : [upgrade] Show GCP current version] ***
ok: [localhost] => {
    "msg": "gcp_current_version: {PrevImageRef}-00"
}
----
. Your {AAPonGCP} deployment is now upgraded to a newer version and you can log in to Red Hat Ansible Automation Platform automation controller and automation hub using your deployment credentials.
