:_mod-docs-content-type: REFERENCE

[id="ref-aap-using-playbooks"]

= Using the playbooks

Some, but not all of the playbooks are described in this document.
Here, those which are used either to retrieve information from the Ansible on Clouds deployment or to check it are described. These playbooks do not modify the deployment.

ifdef::product_GCP[]

[discrete]
== gcp_aap_health_check

This playbook checks if the Ansible application is healthy.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars gcp_aap_health_check
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: gcp_aap_health_check
Description: This playbook checks if the deployment is healthy using the Ansible health service.
-----------------------------------------------
The health check consists of checking the {AAPonGCP} environemnt to verify it is healthy.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator gcp_aap_health_check [--ansible-config ansible_config_path>] -d <deployment_name> -c <cloud_credentials_path> --extra-vars 'gcp_compute_region=<gcp_compute_region> gcp_compute_zone=<gcp_compute_zone>'
===============================================
----

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
PLAY RECAP *********************************************************************
localhost                  : ok=29   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
----

A _failed_ not equal zero indicates an issue with Ansible on Cloud deployment.

[discrete]
== gcp_add_labels

This playbook adds labels to the deployment.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars gcp_add_labels
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: gcp_add_labels
Description: This playbook adds labels to the deployment
-----------------------------------------------
Add labels to the {AAPonGCP} deployment

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator gcp_add_labels -d <deployment_name> -c <cloud_credentials_path> --extra-vars 'gcp_compute_region=<gcp_compute_region> gcp_compute_zone=<gcp_compute_zone> gcp_labels=<gcp_labels>'
===============================================
----
The parameter `gcp_labels` is a comma separated list of `key=value` pairs to add or update. For example: key1=value1,key2=value2

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
PLAY RECAP *********************************************************************
localhost                  : ok=22   changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
----


[discrete]
== gcp_remove_labels

This playbook removes labels from the deployment.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars gcp_remove_labels
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: gcp_remove_labels
Description: This playbook removes labels from the deployment.
-----------------------------------------------
Remove labels from the {AAPonGCP} deployment.

-----------------------------------------------
Command generator template:
docker run --rm $IMAGE command_generator gcp_remove_labels -d <deployment_name> -c <cloud_credentials_path> --extra-vars 'gcp_compute_region=<gcp_compute_region> gcp_compute_zone=<gcp_compute_zone> gcp_labels=<gcp_labels>'
===============================================
----

The parameter `gcp_labels` is a comma separated list of keys to remove. For example: key1,key2

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
PLAY RECAP *********************************************************************
localhost                  : ok=22   changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
----

[discrete]
== gcp_check_aoc_version

This playbook checks if the Ansible on Cloud version is the same as the command generator container.
The check is done each time a playbook is called.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars gcp_check_aoc_version
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: gcp_check_aoc_version
Description: Check the operational container version matches the Ansible on Clouds version.
-----------------------------------------------
Check the operational container version matches the Ansible on Clouds version.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator gcp_check_aoc_version [--ansible-config ansible_config_path>] -c <cloud_credentials_path> -d <deployment_name>
===============================================
----

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
TASK [redhat.ansible_on_clouds.standalone_check_aoc_version : Verify operational playbook and Ansible on Clouds deployment versions] ***
ok: [localhost] => {
    "changed": false,
    "msg": "This operation playbook version and the Ansible on Clouds deployment version are identical: 2.4.20230606-00"
}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

----

A _failed_ not equal zero means the Ansible on Clouds deployment version does not match the `command_generator` container and a different version is required for the command generator to manage that deployment.

[discrete]
== gcp_get_aoc_version

This playbook retrieves the version of the Ansible on Clouds deployment.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars gcp_get_aoc_version
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: gcp_get_aoc_version
Description: Get the current Ansible on Clouds version.
-----------------------------------------------
Get the current Ansible on Clouds version.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator gcp_get_aoc_version [--ansible-config ansible_config_path>] -c <cloud_credentials_path> -d <deployment_name>
===============================================
----

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
TASK [Print version] ***********************************************************
ok: [localhost] => {
    "msg": "The AOC version is 2.4.20230606-00"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
----


[discrete]
== gcp_health_check

This playbook checks if the nodes and Ansible application are healthy.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars gcp_health_check
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: gcp_health_check
Description: This playbook checks if the {AAPonGCP} deployment is healthy.
-----------------------------------------------
The health check consists of checking the {AAPonGCP} heatlh checks
and the health of the monitoring exporter.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator gcp_health_check [--ansible-config ansible_config_path>] -c <cloud_credentials_path> -d <deployment_name> --extra-vars 'gcp_compute_region=<gcp_compute_region> gcp_compute_zone=<gcp_compute_zone>'
===============================================
----
Launching this command by replacing the parameters will generate a new command to launch and will output:
[literal, options="nowrap" subs="+attributes"]
----
...
PLAY RECAP *********************************************************************
localhost                  : ok=47   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

----

A _failed_ not equal zero indicates an issue with nodes or the Ansible on Cloud deployment.

[discrete]
== gcp_list_deployments

This playbook list the deployments, the region and zone are optional.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars gcp_list_deployments
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: gcp_list_deployments
Description: This playbook generates a list of available {AAPonGCP} deployments.
-----------------------------------------------
This playbook is used to generate a list of available {AAPonGCP} deployments.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator gcp_list_deployments -c <cloud_credentials_path> --extra-vars '[gcp_compute_region=<gcp_compute_region>] [gcp_compute_zone=<gcp_compute_zone>]'
===============================================
----

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
TASK [Show deployment list] ****************************************************
ok: [localhost] => {
    "msg": [
        "Deployment list: ['dep1', 'dep2', 'dep3']"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
----


[discrete]
== gcp_nodes_health_check

This playbook checks if the nodes are healthy.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars gcp_nodes_health_check
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: gcp_nodes_health_check
Description: This role runs a health check on a group of nodes in the {AAPonGCP} deployment
-----------------------------------------------
The playbook checks if the {AAPonGCP} monitoring exporter is up and running.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator gcp_nodes_health_check [--ansible-config ansible_config_path>] -d <deployment_name> -c <cloud_credentials_path> --extra-vars 'check_monitoring=True'
===============================================
----

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
PLAY RECAP *********************************************************************
localhost                  : ok=47   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

----

A _failed_ not equal zero indicates an issue with nodes in the deployment.


endif::product_GCP[]
ifdef::product_AWS[]

[discrete]
== aws_add_labels

This playbook adds labels to the deployment.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars aws_add_labels
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: aws_add_labels
Description: This playbook adds labels to the deployment.
-----------------------------------------------
Add labels to the {AAPonAWS} deployment.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator aws_add_labels -d <deployment_name> -c <cloud_credentials_path> --extra-vars 'aws_region=<aws_region> aws_labels=<aws_labels>'
===============================================
----

The parameter `aws_labels` is a comma separated list of `key=value` pairs to add or update. For example: key1=value1,key2=value2

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
PLAY RECAP *********************************************************************
localhost                  : ok=22   changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
----

[discrete]
== aws_check_aoc_version

This playbook checks whether the Ansible on Cloud version is the same as the command generator container.
The check is done each time a playbook is called.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars aws_check_aoc_version
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: aws_check_aoc_version
Description: Check the operational container version matches the Ansible on Clouds version.
-----------------------------------------------
Check the operational container version matches the Ansible on Clouds version.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator aws_check_aoc_version [--ansible-config ansible_config_path>] -d <deployment_name> -c <cloud_credentials_path> --extra-vars 'aws_region=<aws_region> aws_ssm_bucket_name=<aws_ssm_bucket_name>'
===============================================
----

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
TASK [redhat.ansible_on_clouds.standalone_check_aoc_version : Verify operational playbook and Ansible on Clouds deployment versions] ***
fatal: [localhost]: FAILED! => {
    "assertion": "ops_version == aoc_version",
    "changed": false,
    "evaluated_to": false,
    "msg": "This operation playbook version 2.4.20230606-00 is not valid for the Ansible on Clouds deployment version 2.4.20230531-00"
}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
----

A _failed_ not equal zero indicates that the Ansible on Clouds deployment version does not match the `command_generator` container and a different version is required for the command generator to manage that deployment.

[discrete]
== aws_get_aoc_version

This playbook retrieves the version of the Ansible on Clouds deployment.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars aws_get_aoc_version
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: aws_get_aoc_version
Description: Get the current Ansible on Clouds version.
-----------------------------------------------
Get the current Ansible on Clouds version.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator aws_get_aoc_version [--ansible-config ansible_config_path>] -d <deployment_name> -c <cloud_credentials_path> --extra-vars 'aws_region=<aws_region> aws_ssm_bucket_name=<aws_ssm_bucket_name>'
===============================================
----

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
TASK [Print version] ***********************************************************
ok: [localhost] => {
    "msg": "The AOC version is 2.4.20230531-00"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
----

[discrete]
== aws_remove_labels

This playbook removes labels from the deployment.

[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm $IMAGE command_generator_vars aws_remove_labels
----

Which generates the following output:

[literal, options="nowrap" subs="+attributes"]
----
===============================================
Playbook: aws_remove_labels
Description: This playbook removes labels from the deployment.
-----------------------------------------------
Remove labels from the {AAPonAWS} deployment.

-----------------------------------------------
Command generator template:

docker run --rm $IMAGE command_generator aws_remove_labels -d <deployment_name> -c <cloud_credentials_path> --extra-vars 'aws_region=<aws_region> aws_labels=<aws_labels>'
===============================================
----

The parameter `aws_labels` is a single key to remove. For example, `key1`. To remove multiple keys, run the command multiple times.

Launching this command by replacing the parameters generates a new command to launch and outputs:

[literal, options="nowrap" subs="+attributes"]
----
...
PLAY RECAP *********************************************************************
localhost                  : ok=22   changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
----

endif::product_AWS[]
