:_mod-docs-content-type: REFERENCE

[id="ref-gcp-automation-performance"]

= Automation performance

Automating against your licensed managed node allocation in the offer is provided with the following operational expectations. 
Automating outside of the boundaries of these criteria is not supported, but can still function depending on your automation.

[cols="30%,30%",options="header"]
|====
| Metric | Threshold
| Concurrent Jobs | 10
| Forks per job | 10
|====

[NOTE]
====
{AAPonGCP} is driven using three n2-standard-2 instances, two of which run {ControllerName} and one which runs {HubName}. 
The {ControllerName} instances collectively support a standard workload for 100 managed active nodes. 
Red Hat has tested this and proved that there is support for up to 10 forks each.  
This operating criteria has been set and tested using output-intensive, “chatty” workloads that produce 2 messages 7 seconds apart on both {ControllerName} nodes. 
Workloads that are more I/O intensive might not work inside the boundaries of these conditions and can require the use of extension nodes to scale the deployment to support such automation.
====
