[id="tech-note-aws-backup-restore"]

= Backup and Restore

. The `aws_rds_db_snapshot_arn` optional parameter which allowed customers to specify a specific AWS RDS Snapshot to use for restoring their deployment is no longer supported. The restore process no longer uses AWS RDS Snapshots to restore a deployment and instead relies on the backup files generated by the Ansible on Clouds Ops Container backup playbook. The Ansible on Clouds Ops Container restore playbook does not use any provided RDS snapshot passed as a parameter.

. A restored {AAPonAWS} deployment does not maintain all secrets from the original {AAPonAWS} deployment. If using your own certificates, they must be reset after a restore.

+
.Secrets that are maintained:

* `<stack_name>-aap-admin-secret`
* `<stack_name>-aap-secret-key`

+
.Secrets that are NOT maintained:

* `<stack_name>-aap-rds-secret`
* `<stack_name>-database_fields_symmetric_key`
* `<stack_name>-container_auth_private_key_pem`
* `<stack_name>-container_auth_public_key_pem`
* `<stack_name>-pulp_cert`
* `<stack_name>-pulp_key`

. The Ansible on Clouds Ops Container restore playbook fails when attempting to restore a secret starting with `-`. If the restore operation is failing, on your deployment please ensure the secret `<stack_name>-database_fields_symmetric_key` does not start with a `-`. Follow the steps below to check for this case and update the secret appropriately.
.. Find the backup you are passing to the restore playbook on S3.
... The `aws_backup_name` parameter you passed to the restore playbook is the backup we are trying to locate and it should be a folder inside of an S3 bucket
... The `aws_s3_bucket` parameter you passed to the restore playbook should be the bucket which contains the backup we are trying to locate
.. After locating the backup, navigate inside of the backup folder and download the `secrets.json` file.
.. In your downloaded `secrets.json` file, find the value of `<stack_name>-database_fields_symmetric_key`. If `<stack_name>-database_fields_symmetric_key` does not begin with a `-`, you do not need to do anything else; your restore operation is not failing due to this issue. If `<stack_name>-database_fields_symmetric_key` does begin with a `-`, edit the downloaded `secrets.json` file and replace the `-` with any alphanumeric character.
.. After replacing the `-` with an alphanumeric character, navigate back to backup folder in the S3 console and click btn:[Upload].
.. Drag and drop the updated `secrets.json` file into the file upload box on the S3 console webpage and click btn:[Upload].
.. You have successfully updated the `secrets.json` file for a backup. Using this backup for a restore operation should now allow you to successfully create a restored deployment.

. Cross-region backup and restore operations are not supported in this release. This means that a backed up deployment in one region can only be restored in to that same region.

. If a deployment is created inside of an existing VPC, this VPC must exist for backup and restore operations to function. A backed up deployment cannot be restored if the VPC containing this deployment is deleted.  
