:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="assembly-gcp-support"]
= Support

:context: gcp-support

{AAPonGCP} is a self-managed deployment. 
When the application is deployed into your GCP infrastructure, customers are responsible for the maintenance of the GCP infrastructure, OS patching, and {PlatformNameShort} patching. 

Red Hat does not support changes to the infrastructure resources deployed as part of the solution unless there is documentation by Red Hat describing the process, such as in route table configuration for networking or documented upgrade processes. 
Adding additional compute resources outside of extension nodes voids Red Hat support for {AAPonGCP} deployment.

Upgrades to {AAPonGCP} are performed differently from self-installed {PlatformNameShort}. 
Upgrading individual packages on virtual machines using `dnf` or other means is also not supported. 
Instructions will be provided in the upgrade section of this documentation with relevant content for each version, as they become available.

include::topics/ref-gcp-supported-changes.adoc[leveloffset=+1]
include::topics/ref-gcp-vm-image-packages.adoc[leveloffset=+1]
