:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="assembly-gcp-upgrade"]

:context: gcp-upgrade

= Upgrading

You can upgrade your existing {PlatformNameShort} deployment to the newer version. 
The upgrade process covers upgrading the {HubName}, {ControllerName}, and extension nodes.
The upgrade process takes roughly the same amount of time as a {PlatformNameShort} deployment install. 
You are required to create a backup before running the upgrade.

[NOTE]
=====
{AAPonGCP} supports sequential upgrades. 
All upgrades should be no more than one major version behind the version you are currently upgrading to. 
For example, to upgrade {PlatformNameShort} to {ImageRef}, you must be on version {PrevImageRef}.

Logging and monitoring must be disabled before running the upgrade. 
Follow these link:{BaseURL}/ansible_on_clouds/2.3/html/red_hat_ansible_automation_platform_from_gcp_marketplace_guide/assembly-gcp-monitoring-logging#con-gcp-setup-after-deployment[instructions] to toggle off monitoring and logging for your current version before beginning the upgrade.

When the upgrade has completed, logging and monitoring can be reenabled by following these xref:con-gcp-setup-after-deployment[instructions].
=====

.Prerequisites
* Docker must be installed to run the upgrade playbook.
* A Linux or macOS system, where the `ansible-on-clouds-ops` container image will run.
* The upgrade process requires several volumes to be mounted. Prepare a fresh directory to be used for this process.

The following procedures form the upgrade process:

. Backup your {PlatformNameShort} stack.
* Follow the xref:con-gcp-backup-process[Ansible on Clouds backup instructions].

. Upgrade {PlatformNameShort}
.. Pull the next sequential ansible-on-clouds-ops version container image
.. Ensure minimum required permissions are met
.. Generate the data file
.. Update the data file
.. Begin upgrading {PlatformNameShort} by running the operational container

. (Optional) Restore the stack from a backup. 
* Follow the xref:#con-gcp-restore-process[Ansible on Clouds restore instructions].

//context labels are here in case modules need to be reused within these container files.
:context: backup
include::topics/con-gcp-upgrade-backup-process.adoc[leveloffset=+1]
:context: upgrade
include::topics/con-gcp-upgrade-upgrading.adoc[leveloffset=+1]
:context: restore
include::topics/con-gcp-upgrade-restore-from-stack.adoc[leveloffset=+1]
