:_mod-docs-content-type: PROCEDURE

[id="vault-configuring-kv1-secret-info"]

= Configure the `hashicorp.vault.kv1_secret_info` module

[role="_abstract"]

The `hashicorp.vault.kv1_secret_info` module reads KV1 secrets.

The corresponding community.hashi_vault modules are:

* **`community.hashi_vault.vault_kv1_get`:** Retrieves secrets from the HashiCorp Vault KV version 1 secret store.
* **`community.hashi_vault.vault_kv1_get lookup`:** Retrieves secrets from the HashiCorp Vault KV version 1 secret store.

.Procedure

. Replicate the `community.hashi_vault modules` to the following `hashicorp.vault.kv1_secret_secret_info` parameters.
+
----
  engine_mount_point:
    description: KV secrets engine mount point.
    default: secret
    type: str
    aliases: [secret_mount_path]
  path:
    description:
      - Specifies the path of the secret.
    required: true
    type: str
    aliases: [secret_path]
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
----

. (Required) Configure the `path` parameter. This is 
the path to the secret in the `community.hashi_vault.hashi_vault` modules. *Alias:* `secret_path`
. If needed, configure the link:https://console.redhat.com/ansible/automation-hub/repo/published/hashicorp/vault/docs/[optional parameters].

.Next step

* link:{URLHashiGuide}/vault-product#vault-configuring-kv1-secret-get-lookup[Configuring the `hashicorp.vault.kv1_secret_get` lookup plugin].

[role="_additional-resources"]
.Additional resources

* link:{URLHashiGuide}/vault-product#vault-migration-examples-kv1-secret-info[Migration examples for the `hashicorp.vault.kv1_secret_info` module]
