:_mod-docs-content-type: PROCEDURE

[id="vault-creating-credential-type"]

= Creating a custom credential type

[role="_abstract"]

As an admin, you create a secure credential type in {PlatformNameShort}, which is used to authenticate to {Vault}.

You can configure role-based (appRole) authentication or allow users to directly provide a token.

.Prerequisite

* Install the {PlatformNameShort} certified `hashicorp.vault` collection.
* If you are a `community.hashi_vault` collection user, migrate from `community.hashi_vault`.

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select **Automation Execution > Infrastructure > Credential Types**.
. Click **Create a credential type**. The **Create Credential Type** page opens.
. Enter a name and a description in the corresponding fields.
. If you want to configure token authentication for individual users:
.. For **Input configuration**, enter:
+
----
fields:
 - id: vault_token
   type: string
   label: Hashicorp Vault Token
   secret: true
----

.. For **Injector configuration**, enter:
+
----
env:
   VAULT_TOKEN: '{{ vault_token }}'
----

. If you want to configure appRole authentication using `role_id` and `secret_id`:

.. For **Input configuration**, enter:
+
----
fields:
  - id: vault_approle_role_id
    type: string
    label: Hashicorp Vault appRole Role ID
    secret: true
  - id: vault_approle_secret_id
    type: string
    label: Hashicorp Vault appRole Secret ID
    secret: true
----
.. For **Injector configuration**, enter:
+
----
env:
    VAULT_APPROLE_ROLE_ID: '{{ vault_approle_role_id }}'
    VAULT_APPROLE_SECRET_ID: '{{ vault_approle_secret_id }}'
----

. Click **Create credential type**.

.Next step

* _Creating a custom credential_

.Additional resources

* link:https://developer.hashicorp.com/vault/api-docs[{Vault} API documentation]