:_mod-docs-content-type: PROCEDURE

[id="vault-configuring-kv2-secret-info"]

= Configuring the `hashicorp.vault.kv2_secret_info` module

[role="_abstract"]

The `hashicorp.vault.kv2_secret_info` module reads KV2 secrets.

The corresponding `community.hashi_vault` module is:

* **`community.hashi_vault.vault_kv2_get`:** Gets secrets from the HashiCorp Vault KV version 2 secret store.


.Procedure

. Replicate the `community.hashi_vault` modules to the following `hashicorp.vault.kv2_secret_info` parameters.
+
----
  engine_mount_point:
    description: KV secrets engine mount point.
    default: secret
    type: str
    aliases: [secret_mount_path]
  path:
    description: Path to the secret.
    required: true
    type: str
    aliases: [secret_path]
  version:
    description: The version to retrieve.
    type: int
extends_documentation_fragment:
  - hashicorp.vault.vault_auth.modules
----

. Configure the required parameters:

* **`path`:** The path where the secret is located in the community.`hashi_vault.hashi_vault` modules. *Alias:* `secret_path`
* **`url`:** Maps to `url` in the `community.hashi_vault.hashi_vault` modules. Uses the same aliases as `vault_address`.

. If needed, configure the link:https://console.redhat.com/ansible/automation-hub/repo/published/hashicorp/vault/content/module/kv2_secret_info/[optional parameters].

.Next step
* link:{URLHashiGuide}/vault-product#vault-configuring-kv2-secret-get-lookup[Configuring the `hashicorp.vault.kv2_secret_get` lookup plugin].

[role="_additional-resources"]
.Additional resources

* link:{URLHashiGuide}/vault-product#vault-migration-examples-kv2-secret-info[Migration examples for the `hashicorp.vault.kv2_secret_info` module]