:_mod-docs-content-type: PROCEDURE

[id="vault-configuring-kv2-secret-get-lookup"]

= Configuring the `hashicorp.vault.kv2_secret_get` lookup plugin

[role="_abstract"]

The `hashicorp.vault.kv2_secret_get` lookup plugin module reads KV2 secrets.

The corresponding `community.hashi_vault` modules are:

* **`community.hashi_vault.hashi_vault`:** Retrieves secrets from HashiCorp Vault.
* **`community.hashi_vault.vault_kv2_get` lookup:** Gets secrets from the HashiCorp Vault KV version 2 secret store.

.Procedure

. Replicate the `community.hashi_vault` modules to the following `hashicorp.vault.kv2_secret_get` parameters. For examples, see _Migration examples for the `hashicorp.vault.kv2_secret_get` lookup plugin_.
+
----
auth_method:
 description: Authentication method to use
 type: str
 choices: [token]
 default: token
 required: false

mount_point:
 description: Vault mount point
 type: str
 required: false
 aliases: [secret_mount_path]

namespace:
 description: Vault namespace where secrets reside.
 type: str
 default: admin
 aliases: [vault_namespace]
secret:
 description: Vault path to the secret being requested in the format path[:field]
 type: str
 required: true
 aliases: [secret_path]

url:
 description: URL of the Vault service
 type: str
 aliases: [vault_address]
 required: true

version:
 description: Specifies the version to return. If not set the latest is returned.
 type: int
 required: false
----

. Use the following guidance to configure the `hashicorp.vault.kv2_secret_get` parameters:

* **`auth_method`:** Maps identically to `auth_method` in the `community.hashi_vault.hashi_vault` modules.

* **`mount_point`:** Maps to `mount_point` in the `community.hashi_vault.hashi_vault` modules. **Alias:** `secret_mount_path`.

* **`namespace`:** Maps to `namespace` in the `community.hashi_vault.hashi_vault` modules. **Alias:** `vault_namespace`.

* **`secret`:** Maps to `secret` in the `community.hashi_vault.hashi_vault` modules.

* **`url`:** Maps to `url` in the `community.hashi_vault.hashi_vault` modules. Uses the same aliases as `vault_address`.

* **`version`:** Maps identically to `version` in the `community.hashi_vault.hashi_vault` modules.

.Next step
* _Creating a credential type_
