:_mod-docs-content-type: PROCEDURE

[id="vault-creating-credential-type"]

= Creating a custom credential type

[role="_abstract"]

As an admin, you create a secure credential type in {PlatformNameShort} to authenticate to Vault. In turn, the {Vault} credentials are provided as environment variables to {PlatformNameShort} job templates.

.Prerequisite

* Install the {PlatformNameShort} certified `hashicorp.vault` collection.
* If you are a community-edition {Vault} user, migrate from {VaultCommunityName}.

.Procedure

. Log in to {PlatformShortName}.
. From the navigation panel, select **Automation Execution > Infrastructure > Credential Types**.
. Click **Create a credential type**. The **Create Credential Type** page opens.
. Enter a name and a description in the corresponding fields.
. To configure token authentication for individual users:
.. For **Input configuration**, enter:
+
----
fields:
 - id: vault_token
   type: string
   label: Hashicorp Vault Token
   secret: true
----
+
.. For **Injector configuration**, enter:
+
----
env:
   VAULT_TOKEN: '{{ vault_token }}'
----
+
Click **Create credential type**.

.Next step

* Creating a custom credential

.Additional resources

* link:https://developer.hashicorp.com/vault/api-docs[Vault API documentation]