version: 2
outputDir: build
apisToHide: []
apiMap:
- name: aap.ansible.com
  resources:
  - kind: AnsibleAutomationPlatform
    group: aap.ansible.com
    version: v1alpha1
  - kind: AnsibleAutomationPlatformBackup
    group: aap.ansible.com
    version: v1alpha1
  - kind: AnsibleAutomationPlatformRestore
    group: aap.ansible.com
    version: v1alpha1
- name: automationcontroller.ansible.com
  resources:
  - kind: AutomationControllerMeshIngress
    group: automationcontroller.ansible.com
    version: v1alpha1
  - kind: AutomationController
    group: automationcontroller.ansible.com
    version: v1beta1
  - kind: AutomationControllerBackup
    group: automationcontroller.ansible.com
    version: v1beta1
  - kind: AutomationControllerRestore
    group: automationcontroller.ansible.com
    version: v1beta1
- name: automationhub.ansible.com
  resources:
  - kind: AutomationHub
    group: automationhub.ansible.com
    version: v1beta1
  - kind: AutomationHubBackup
    group: automationhub.ansible.com
    version: v1beta1
  - kind: AutomationHubRestore
    group: automationhub.ansible.com
    version: v1beta1
- name: eda.ansible.com
  resources:
  - kind: EDA
    group: eda.ansible.com
    version: v1alpha1
  - kind: EDABackup
    group: eda.ansible.com
    version: v1alpha1
  - kind: EDARestore
    group: eda.ansible.com
    version: v1alpha1
- name: lightspeed.ansible.com
  resources:
  - kind: AnsibleLightspeed
    group: lightspeed.ansible.com
    version: v1alpha1
- name: tower.ansible.com
  resources:
  - kind: AnsibleCredential
    group: tower.ansible.com
    version: v1alpha1
  - kind: AnsibleInstanceGroup
    group: tower.ansible.com
    version: v1alpha1
  - kind: AnsibleInventory
    group: tower.ansible.com
    version: v1alpha1
  - kind: AnsibleJob
    group: tower.ansible.com
    version: v1alpha1
  - kind: AnsibleProject
    group: tower.ansible.com
    version: v1alpha1
  - kind: AnsibleSchedule
    group: tower.ansible.com
    version: v1alpha1
  - kind: AnsibleWorkflow
    group: tower.ansible.com
    version: v1alpha1
  - kind: JobTemplate
    group: tower.ansible.com
    version: v1alpha1
  - kind: WorkflowTemplate
    group: tower.ansible.com
    version: v1alpha1