:_mod-docs-content-type: ASSEMBLY

[id="assembly-intro-to-builder"]

= Introduction to {ExecEnvName}

[role="_abstract"]
Using Ansible content that depends on non-default dependencies can be complicated because the packages must be installed on each node, interact with other software installed on the host system, and be kept in sync.

You must use the same environment during development, testing and in production. 
Red Hat provides {ExecEnvShort}s for this purpose.

{ExecEnvNameStart} help simplify this process and you can easily create them with {Builder}.

*Builder* 
Builder is a command line tool that makes it easy to build, test, and publish container images for use as Ansible {ExecEnvShort}s.

Ansible provides an link:https://github.com/redhat-cop/ee_utilities[Execution Environment Utilities Collection], `infra.ee_utilities`. 
Red Hat provides {ExecEnvShort}s for this purpose.
This is a collection of roles for creating and managing images, or migrating from the older Tower virtualenvs to {ExecEnvShort}. 
Using this collection, you can automate the preparation and maintenance of Ansible {ExecEnvShort}s.

include::builder/con-about-ee.adoc[leveloffset=+1]

include::builder/con-why-ee.adoc[leveloffset=+2]

