metadata:
  name: getting started with Ansible Automation Platform
  # you can add additional metadata here
  instructional: true
spec:
  displayName: Getting started with Ansible Automation Platform
  durationMinutes: 20
  # Optional type section, will display as a tile on the card
  type:
    text: Automation operator
    # 'blue' | 'cyan' | 'green' | 'orange' | 'purple' | 'red' | 'grey'
    color: grey
  # - The icon defined as a base64 value. Example flow:
  # 1. Find an .svg you want to use, like from here: https://www.patternfly.org/v4/guidelines/icons/#all-icons
  # 2. Upload the file here and encode it (output format - plain text): https://base64.guru/converter/encode/image
  # 3. compose - `icon: data:image/svg+xml;base64,<base64 string from step 2>`
  # - If empty string (icon: ''), will use a default rocket icon
  # - If set to null (icon: ~) will not show an icon
  icon: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIGlkPSJ1dWlkLWFlMzcyZWFiLWE3YjktNDU4ZC04MzkwLWI5OWZiNzhmYzFlNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3Qm94PSIwIDAgMzggMzgiPjxwYXRoIGQ9Im0yOCwxSDEwQzUuMDI5NDIsMSwxLDUuMDI5NDIsMSwxMHYxOGMwLDQuOTcwNTgsNC4wMjk0Miw5LDksOWgxOGM0Ljk3MDU4LDAsOS00LjAyOTQyLDktOVYxMGMwLTQuOTcwNTgtNC4wMjk0Mi05LTktOVptNy43NSwyN2MwLDQuMjczMzgtMy40NzY2OCw3Ljc1LTcuNzUsNy43NUgxMGMtNC4yNzMzMiwwLTcuNzUtMy40NzY2Mi03Ljc1LTcuNzVWMTBjMC00LjI3MzM4LDMuNDc2NjgtNy43NSw3Ljc1LTcuNzVoMThjNC4yNzMzMiwwLDcuNzUsMy40NzY2Miw3Ljc1LDcuNzV2MThaIi8+PHBhdGggZD0ibTE0LDEwLjQ3NTU5aC0zYy0uMzQ0NzMsMC0uNjI1LjI4MDI3LS42MjUuNjI1djNjMCwuMzQ0NzMuMjgwMjcuNjI1LjYyNS42MjVoM2MuMzQ0NzMsMCwuNjI1LS4yODAyNy42MjUtLjYyNXYtM2MwLS4zNDQ3My0uMjgwMjctLjYyNS0uNjI1LS42MjVabS0uNjI1LDNoLTEuNzV2LTEuNzVoMS43NXYxLjc1WiIvPjxwYXRoIGQ9Im0yNywxMC40NzU1OWgtM2MtLjM0NDczLDAtLjYyNS4yODAyNy0uNjI1LjYyNXYzYzAsLjM0NDczLjI4MDI3LjYyNS42MjUuNjI1aDNjLjM0NDczLDAsLjYyNS0uMjgwMjcuNjI1LS42MjV2LTNjMC0uMzQ0NzMtLjI4MDI3LS42MjUtLjYyNS0uNjI1Wm0tLjYyNSwzaC0xLjc1di0xLjc1aDEuNzV2MS43NVoiLz48cGF0aCBkPSJtMjcsMjMuNDc1NTloLTNjLS4zNDQ3MywwLS42MjUuMjgwMjctLjYyNS42MjV2M2MwLC4zNDQ3My4yODAyNy42MjUuNjI1LjYyNWgzYy4zNDQ3MywwLC42MjUtLjI4MDI3LjYyNS0uNjI1di0zYzAtLjM0NDczLS4yODAyNy0uNjI1LS42MjUtLjYyNVptLS42MjUsM2gtMS43NXYtMS43NWgxLjc1djEuNzVaIi8+PHBhdGggZD0ibTE0LDIzLjQ3NTU5aC0zYy0uMzQ0NzMsMC0uNjI1LjI4MDI3LS42MjUuNjI1djNjMCwuMzQ0NzMuMjgwMjcuNjI1LjYyNS42MjVoM2MuMzQ0NzMsMCwuNjI1LS4yODAyNy42MjUtLjYyNXYtM2MwLS4zNDQ3My0uMjgwMjctLjYyNS0uNjI1LS42MjVabS0uNjI1LDNoLTEuNzV2LTEuNzVoMS43NXYxLjc1WiIvPjxwYXRoIGQ9Im0yMS4xNTUyNywxMC43NDcwN2MtMS40MDQzLS4zNTkzOC0yLjkwNjI1LS4zNTkzOC00LjMxMDU1LDAtLjMzMzk4LjA4NTk0LS41MzYxMy40MjY3Ni0uNDUwMi43NjA3NC4wODQ5Ni4zMzMwMS40MjI4NS41MzkwNi43NjA3NC40NTAyLDEuMjAzMTItLjMwODU5LDIuNDg2MzMtLjMwODU5LDMuNjg5NDUsMCwuMDUxNzYuMDEzNjcuMTA0NDkuMDE5NTMuMTU1MjcuMDE5NTMuMjc5MywwLC41MzMyLS4xODc1LjYwNTQ3LS40Njk3My4wODU5NC0uMzMzOTgtLjExNjIxLS42NzQ4LS40NTAyLS43NjA3NFoiLz48cGF0aCBkPSJtMTEuNDA3MjMsMTYuNDk1MTJjLS4zMzY5MS0uMDg5ODQtLjY3NDguMTE3MTktLjc2MDc0LjQ1MDItLjE3OTY5LjcwMTE3LS4yNzE0OCwxLjQyNjc2LS4yNzE0OCwyLjE1NTI3LDAsLjcyNzU0LjA5MTgsMS40NTMxMi4yNzE0OCwyLjE1NTI3LjA3MjI3LjI4MjIzLjMyNjE3LjQ2OTczLjYwNTQ3LjQ2OTczLjA1MDc4LDAsLjEwMzUyLS4wMDU4Ni4xNTUyNy0uMDE5NTMuMzMzOTgtLjA4NTk0LjUzNjEzLS40MjY3Ni40NTAyLS43NjA3NC0uMTU0My0uNjAxNTYtLjIzMjQyLTEuMjIxNjgtLjIzMjQyLTEuODQ0NzMsMC0uNjI0MDIuMDc4MTItMS4yNDQxNC4yMzI0Mi0xLjg0NDczLjA4NTk0LS4zMzM5OC0uMTE1MjMtLjY3NDgtLjQ1MDItLjc2MDc0WiIvPjxwYXRoIGQ9Im0yMC44NDQ3MywyNi4yNDMxNmMtMS4yMDMxMi4zMDg1OS0yLjQ4NjMzLjMwODU5LTMuNjg5NDUsMC0uMzM2OTEtLjA4Nzg5LS42NzQ4LjExNjIxLS43NjA3NC40NTAycy4xMTYyMS42NzQ4LjQ1MDIuNzYwNzRjLjcwMjE1LjE3OTY5LDEuNDI3NzMuMjcxNDgsMi4xNTUyNy4yNzE0OHMxLjQ1MzEyLS4wOTE4LDIuMTU1MjctLjI3MTQ4Yy4zMzM5OC0uMDg1OTQuNTM2MTMtLjQyNjc2LjQ1MDItLjc2MDc0LS4wODQ5Ni0uMzMzOTgtLjQyMzgzLS41MzkwNi0uNzYwNzQtLjQ1MDJaIi8+PHBhdGggZD0ibTI2LjU5Mjc3LDE2LjQ5NTEyYy0uMzM0OTYuMDg1OTQtLjUzNjEzLjQyNjc2LS40NTAyLjc2MDc0LjE1NDMuNjAwNTkuMjMyNDIsMS4yMjA3LjIzMjQyLDEuODQ0NzMsMCwuNjIzMDUtLjA3ODEyLDEuMjQzMTYtLjIzMjQyLDEuODQ0NzMtLjA4NTk0LjMzMzk4LjExNjIxLjY3NDguNDUwMi43NjA3NC4wNTE3Ni4wMTM2Ny4xMDQ0OS4wMTk1My4xNTUyNy4wMTk1My4yNzkzLDAsLjUzMzItLjE4NzUuNjA1NDctLjQ2OTczLjE3OTY5LS43MDIxNS4yNzE0OC0xLjQyNzczLjI3MTQ4LTIuMTU1MjcsMC0uNzI4NTItLjA5MTgtMS40NTQxLS4yNzE0OC0yLjE1NTI3LS4wODU5NC0uMzMzMDEtLjQyMzgzLS41NDEwMi0uNzYwNzQtLjQ1MDJaIi8+PHBhdGggZD0ibTIwLjkxMTEzLDE3LjM4NTc0YzAtMS4wNTM3MS0uODU3NDItMS45MTAxNi0xLjkxMTEzLTEuOTEwMTZzLTEuOTExMTMuODU2NDUtMS45MTExMywxLjkxMDE2YzAsLjYyNzc1LjMwODM1LDEuMTgxMDMuNzc3MjIsMS41Mjk2NmwtLjc1ODY3LDMuMDMzODFjLS4wNDY4OC4xODY1Mi0uMDA0ODguMzg0NzcuMTE0MjYuNTM2MTMuMTE4MTYuMTUxMzcuMjk5OC4yNDAyMy40OTIxOS4yNDAyM2gyLjU3MjI3Yy4xOTIzOCwwLC4zNzQwMi0uMDg4ODcuNDkyMTktLjI0MDIzLjExOTE0LS4xNTEzNy4xNjExMy0uMzQ5NjEuMTE0MjYtLjUzNjEzbC0uNzU4NjctMy4wMzM4MWMuNDY4ODctLjM0ODYzLjc3NzIyLS45MDE5Mi43NzcyMi0xLjUyOTY2Wm0tMi4zOTY0OCw0LjA4OTg0bC40ODUzNS0xLjk0MTQxLjQ4NTM1LDEuOTQxNDFoLS45NzA3Wm0uNDg1MzUtMy40Mjg3MWMtLjM2NDI2LDAtLjY2MTEzLS4yOTY4OC0uNjYxMTMtLjY2MTEzcy4yOTY4OC0uNjYwMTYuNjYxMTMtLjY2MDE2LjY2MTEzLjI5NTkuNjYxMTMuNjYwMTYtLjI5Njg4LjY2MTEzLS42NjExMy42NjExM1oiLz48L3N2Zz4=
  prerequisites:
    - You have a valid Ansible Automation Platform subscription.
  description: |-
   Learn how to get started with Ansible Automation Platform.
  introduction: |-
   Get started with Ansible Automation Platform as an automation operator.
  
  tasks:

    - title: Get started with playbooks
      description: |-
        ##To get started with playbooks:

        A playbook runs in order from top to bottom. 
        Within each play, tasks also run in order from top to bottom. 
        Playbooks with multiple "plays" can orchestrate multi-machine deployments, running one play on your webservers, then another play on your database servers, then a third play on your network infrastructure.

        For more information, see [Playbook execution](https://docs.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.5/html-single/getting_started_with_playbooks/index#ref-playbook-execution).

    - title: Write a playbook
      description: |-
        ##To write a playbook:

         Create a playbook that pings your hosts and prints a "Hello world" message:

         1. Create a file named `playbook.yaml` in your `ansible_quickstart` directory, with the following content:

         ```
          name: My first play
           hosts: myhosts
           tasks:
             name: Ping my hosts
            ansible.builtin.ping:

            name: Print message
            ansible.builtin.debug:
             msg: Hello world

         ```

         2. Run your playbook:

         ```
         ansible-playbook -i inventory.ini playbook.yaml
         ```

            - Ansible returns the following output:
         ```
         PLAY [My first play] ****************************************************************************

         TASK [Gathering Facts] **************************************************************************
         ok: [192.0.2.50]
         ok: [192.0.2.51]
         ok: [192.0.2.52]

         TASK [Ping my hosts] ****************************************************************************
         ok: [192.0.2.50]
         ok: [192.0.2.51]
         ok: [192.0.2.52]

         TASK [Print message] ****************************************************************************
         ok: [192.0.2.50] => {
            "msg": "Hello world"
         }
         ok: [192.0.2.51] => {
            "msg": "Hello world"
         }
         ok: [192.0.2.52] => {
            "msg": "Hello world"
         }

         PLAY RECAP **************************************************************************************
          192.0.2.50: ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
          192.0.2.51: ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
          192.0.2.52: ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
          ```

          For more information about playbooks, see [Getting started with Ansible Playbooks.](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/getting_started_with_ansible_playbooks/index#doc-wrapper)
          If you need help writing a playbook, see [Ansible Lightspeed.](https://developers.redhat.com/products/ansible/lightspeed?source=sso)
      review:
        instructions: |-
          #### To verify that you've written a playbook:
          Did your playbook execute correctly?
        failedTaskHelp: Try the steps again or read more about this topic at [Run Your First Command and Playbook](https://docs.ansible.com/projects/ansible/latest/network/getting_started/first_playbook.html).    
      summary:
        success: You have viewed the details of your playbook!
        failed: 

    - title: Roles
      description: |-
        ##To learn about roles:

        Roles are units of organization in the Ansible Automation Platform. 
        When you assign a role to a team or user, you are granting access to use, read, or write credentials. 
        Because of the file structure associated with a role, roles become redistributable units that enable you to share behavior among resources, or with other users. All access that is granted to use, read, or write credentials is handled through roles, and roles are defined for a resource.

        Roles are separated out by service through automation controller, Event-Driven Ansible, and automation hub. 

    - title: Create a plugin (optional)
      description: |-
        ##To create a plugin:

        Inventory updates use dynamically-generated YAML files which are parsed by their inventory plugin. 
        In automation controller v4.4, you can give the inventory plugin configuration directly to automation controller using the inventory source `source_vars`.

        For more information about creating inventory plugins, see [Inventory Plugins](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/automation_controller_user_guide/index#ref-controller-inventory-plugins).
   
    - title: Publish a collection
      description: |-
        ##To publish to a collection:

         As a content creator, you can use namespaces in automation hub to curate and manage collections for the following purposes:

          - Create groups with permissions to curate namespaces and upload collections to private automation hub.
          - Add information and resources to the namespace to help end users of the collection in their automation tasks.
          - Upload collections to the namespace.
          - Review the namespace import logs to determine the success or failure of uploading the collection and its current approval status.

        For more information about collections, see [Managing collections](https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/managing_content_in_automation_hub/managing-collections-hub) in automation hub.

    - title: Upload a collection to automation hub
      description: |-
        ##To upload a collection to automation hub:

        You can upload the collection by using either the automation hub user interface or the `ansible-galaxy` client.

        ###Prerequisites

        - You have configured the `ansible-galaxy` client for automation hub.
        - You have at least one namespace.
        - You have run all content through ansible-test sanity.
        - You are a Red Hat Connect Partner. Learn more at [Red Hat Partner Connect](https://connect.redhat.com/).

        ###Procedure

        1. From the navigation panel, select **Automation Content**.
        2. From the automation hub navigation panel, select **Collections** > **Namespaces**.
        3. On the **My namespaces** tab, locate the namespace to which you want to upload a collection.
        4. Click **View collections** and click **Upload collection**.
        5. In the **New collection modal**, click **Select file**. Locate the file on your system.
        6. Click **Upload**.
        7. Using the ansible-galaxy client, enter the following command:

          ```
          ansible-galaxy collection publish path/to/my_namespace-my_collection-1.0.0.tar.gz --api-key=SECRET
          ```

      review:
        instructions: |-
          #### To verify that you've uploaded a collection:
          Does the collection appear in the **Collections** list?
        failedTaskHelp: This task is not verified yet. Try the task again.    
      summary:
        success: You have viewed the details of your collection!
        failed: Try the steps again.
  
  conclusion: You successfully completed the getting started steps for Ansible Automation Platform! If you
    want to learn how to find content, take the **Finding content in ansible automation platform** quick start.

  nextQuickStart: [finding-content-in-ansible-automation-platform]
          