//This file is the master assembly that defines the table of contents.
//Sourced in the ansible/aap-docs repository.

include::userguide/overview.adoc[leveloffset=0]
include::userguide/license-support.adoc[leveloffset=0]
include::userguide/logging_in.adoc[leveloffset=0]
include::userguide/import_license.adoc[leveloffset=0]
include::userguide/main_menu.adoc[leveloffset=0]
include::userguide/search_sort.adoc[leveloffset=0]
include::userguide/organizations.adoc[leveloffset=0]
include::userguide/users.adoc[leveloffset=0]
include::userguide/teams.adoc[leveloffset=0]
include::userguide/credentials.adoc[leveloffset=0]
include::userguide/credential_types.adoc[leveloffset=0]
include::userguide/credential_plugins.adoc[leveloffset=0]
include::userguide/applications_auth.adoc[leveloffset=0]
include::userguide/execution_environments.adoc[leveloffset=0]
include::userguide/ee_reference.adoc[leveloffset=0]
include::userguide/projects.adoc[leveloffset=0]
include::userguide/inventories.adoc[leveloffset=0]
include::userguide/inventory_plugins_templates.adoc[leveloffset=0]
include::userguide/job_templates.adoc[leveloffset=0]
include::userguide/job_slices.adoc[leveloffset=0]
include::userguide/workflows.adoc[leveloffset=0]
include::userguide/workflow_templates.adoc[leveloffset=0]
include::userguide/instance_groups.adoc[leveloffset=0]
include::userguide/jobs.adoc[leveloffset=0]
include::userguide/webhooks.adoc[leveloffset=0]
include::userguide/notifications.adoc[leveloffset=0]
include::userguide/notification_parameters_supported.adoc[leveloffset=0]
include::userguide/scheduling.adoc[leveloffset=0]
include::userguide/insights.adoc[leveloffset=0]
include::userguide/best_practices.adoc[leveloffset=0]
include::userguide/security.adoc[leveloffset=0]