[id="con-building-definition-file"]

= Building a definition file

After you install {Builder}, you can create a definition file that {Builder} uses to create your {ExecEnvNameSing} image. {Builder} makes an {ExecEnvNameSing} image by reading and validating your definition file, then creating a `Containerfile`, and finally passing the `Containerfile` to Podman, which then packages and creates your {ExecEnvNameSing} image. The definition file that you create must be in `yaml` format and contain different sections. The default definition filename, if not provided, is `execution-environment.yml`.

The following is an example of a version 3 definition file. Each definition file must specify the major version number of the Ansible Builder feature set it uses. If not specified, {Builder} defaults to version 1, making most new features and definition keywords unavailable.

// ddacosta - there is a Ansible Builder version 3 Porting Guide in progress that discusses the changes from v1/2 to v3. A link should be included to that document once its published.

.Definition file example
====
----
version: 3

build_arg_defaults: <1>
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies: <2>
  galaxy: requirements.yml
  python:
    - six
    - psutil
  system: bindep.txt

images: <3>
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

# Custom package manager path for the RHEL based images
 options: <4>
 package_manager_path: /usr/bin/microdnf

additional_build_steps: <5>
  prepend_base:
    - RUN echo This is a prepend base command!

  prepend_galaxy:
      # Environment variables used for Galaxy client configurations
    - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://console.redhat.com/api/automation-hub/content/xxxxxxx-synclist/
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    # define a custom build arg env passthru - we still also have to pass
    # `--build-arg ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN` to get it to pick it up from the env
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN

  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
----
====

<1> Lists default values for build arguments.
<2> Specifies the location of various requirements files.
<3> Specifies the base image to be used. Red Hat support is only provided for the redhat.registry.io base image.
<4> Specifies options that can affect builder runtime functionality.
<5> Commands for additional custom build steps.

[role="_additional-resources"]
.Additional resources
* For more information about the definition file content, see xref:assembly-definition-file-breakdown[Breakdown of definition file content].
