:_mod-docs-content-type: CONCEPT

[id="con-ee-precedence"]

= {ExecEnvNameStart} precedence

[role="_abstract"]
Identify and control the exact automation execution environment applied to your jobs by tracing the precedence hierarchy, ensuring you can troubleshoot environment mismatches or configure accurate defaults across your templates, projects, and organizations.

Project updates always use the control plane {ExecEnvNameSing}s by default.

However, jobs use the first available {ExecEnvName} as follows:

. The `execution_environment` defined on the template (job template or inventory source) that created the job.
. The `default_environment` defined on the project that the job uses.
. The `default_environment` defined on the organization of the job.
. The `default_environment` defined on the organization of the inventory the job uses.
. The current `DEFAULT_EXECUTION_ENVIRONMENT` setting (configurable at `api/v2/settings/system/`)
. Any image from the `GLOBAL_JOB_EXECUTION_ENVIRONMENTS` setting.
. Any other global {ExecEnvShort}.

[NOTE]
====
* Where an {ExecEnvShort} is not available, the Default {ExecEnvShort} can be used. However, you must select this, as the system does not automatically provide a default environment.
* If more than one {ExecEnvShort} fits a criteria (applies for 6 and 7), the most recently created one is used.
====
