:_mod-docs-content-type: PROCEDURE

[id="proc-customize-ee-image"]

= Customizing an existing {ExecEnvName} image

[role="_abstract"]
Ansible Controller includes the following default execution environments:

* `Minimal` -  `ansible-automation-platform-25` Includes the latest Ansible-core 2.16 release along with Ansible Runner, but does not include collections or other content.  Ansible-automation-platform-24 Includes the Ansible-core 2.15 release along with {Runner}, but does not include collections or other content.
+
While supported {ExecEnvShort}s cover many automation prerequisites, minimal execution-environments are the recommended basis for your own custom images, to keep full control over dependencies and their versions.
* `EE Supported` - Minimal, plus all Red Hat-supported collections and dependencies

While these environments cover many automation use cases, you can add additional items to customize these containers for your specific needs. The following procedure adds the `kubernetes.core` collection to the `ee-minimal` default image:

.Procedure
. Log in to `registry.redhat.io` using Podman:
+
----
$ podman login -u="[username]" -p="[token/hash]" registry.redhat.io
----
. Ensure that you can pull the required {ExecEnvNameSing} base image:
+
-----
podman pull registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
-----
+
. Configure your {Builder} files to specify the required base image and any additional content to add to the new {ExecEnvShort} image.
.. For example, to add the link:https://galaxy.ansible.com/kubernetes/core[Kubernetes Core Collection from Galaxy] to the image, use the Galaxy entry:
+
----
collections:
  - kubernetes.core
----

.. For more information about definition files and their content, see the xref:con-definition-file-breakdown[Breakdown of definition file content] section.
. In the {ExecEnvShort} definition file, specify the original `ee-minimal` container's URL and tag in the `EE_BASE_IMAGE` field. 
In doing so, your final `execution-environment.yml` file appears similar to the following:
+
----
version: 3

images:
  base_image: 
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest'

dependencies:
  galaxy:
    collections:
      - kubernetes.core
----
+
[NOTE]
====
Since this example uses the community version of `kubernetes.core` and not a certified collection from {HubName}, we do not need to create an `ansible.cfg` file or reference that in our definition file.
====
. Build the new {ExecEnvShort} image by using the following command:
+
[subs=+quotes]
----
$ ansible-builder build -t _[username]_/_new-ee_
----
where `[username]` specifies your username, and `new-ee` specifies the name of your new container image.
+
[NOTE]
====
If you do not use `-t` with `build`, an image called `ansible-execution-env` is created and loaded into the local container registry.
====
+
* Use the `podman images` command to confirm that your new container image is in that list:
+
The following shows the output of a 'podman images' command with the image `new-ee`.
+
----
REPOSITORY          TAG     IMAGE ID      CREATED        SIZE
localhost/new-ee    latest  f5509587efbb  3 minutes ago  769 MB
----

. Verify that the collection is installed:
+
-----
$ podman run [username]/new-ee ansible-doc -l kubernetes.core
-----
+
. Tag the image for use in your {HubName}:
+
-----
$ podman tag [username]/new-ee [automation-hub-IP-address]/[username]/new-ee
-----
+
. Log in to your {HubName} using Podman:
+
[NOTE]
=====
You must have `admin` or appropriate container repository permissions for {HubName} to push a container. For more information, see link:{URLHubManagingContent}/index#managing-containers-hub[Manage containers in private automation hub].
=====
+
-----
$ podman login -u="[username]" -p="[token/hash]" [automation-hub-IP-address]
-----
+
. Push your image to the container registry in {HubName}:
+
----
$ podman push [automation-hub-IP-address]/[username]/new-ee
----
+
. Pull your new image into your {ControllerName} instance:
.. Go to {ControllerName}.
.. From the navigation panel, select {MenuInfrastructureExecEnvironments}.
.. Click btn:[Add].
.. Enter the appropriate information then click btn:[Save] to pull in the new image.
+
[NOTE]
====
If your instance of {HubName} is password or token protected, ensure that you have the appropriate container registry credential set up.
====
