:_mod-docs-content-type: CONCEPT

[id="con-saas-privatelink-config-types"]

= PrivateLink configuration types

[role="_abstract"]

The PrivateLink configuration offers both ingress, for UI/API access to the {PlatformNameShort} control plane, and egress, for the control plane to connect to your private resources. 
For more information, see section 7.2.1. link:{BaseURL}/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_service_on_aws/saas-private-link#aws_privatelink_connectivity_into_the_ansible_automation_platform_control_plane[AWS PrivateLink connectivity into the Ansible Automation Platform control plane].

* *Ingress PrivateLink:* Connects your VPC to the {PlatformNameShort} control plane (for UI/API access). 
Requires a support ticket providing your AWS Account ID and Region.
* *Egress PrivateLink:* Connects the {PlatformNameShort} control plane to your private resources (for example, {PrivateHubName}). 
This requires a separate support ticket to authorize the connection to your Endpoint Service.

