:_mod-docs-content-type: CONCEPT

[id="con-saas-connectivity"]

= Connectivity

[role="_abstract"]
The execution plane can communicate with the control plane under the following conditions:

* Polling (mesh-ingress): Execution nodes must route stateful egress traffic to the {PlatformNameShort} deployment domain over port 443.
* Push: A configurable firewall port must be open in the customer’s remote networks to allow {PlatformNameShort} to push information to execution nodes.

You can configure automation mesh nodes behind firewalls, proxy servers, and similar services. 
These services route or proxy traffic originating from {PlatformNameShort} without altering headers, payload, or other information that would affect functionality of the automation mesh.

You can restrict access to the control plane by providing CIDR blocks to the Red Hat support team through a link:https://access.redhat.com/support/cases/#/case/new/get-support?caseCreate=true[Customer support request]. 
This controls the inbound access to the control plane limiting it to the IP ranges you provide for traffic over the public internet.
The application of these rules do not apply to traffic over PrivateLink. 
These restrictions do not affect outbound traffic that originates from the control plane.

[IMPORTANT]
====
Customers *must* allowlist the following wildcard domain in their local firewalls to permit the SRE team's maintenance and monitoring:

* `*.redhat.com`
====
