:_mod-docs-content-type: CONCEPT

[id="ref-saas-config-aws-privatelink"]
= Configure {AWSPrivateLink}

[role="_abstract"]
{AWSPrivateLink} establishes secure connectivity between your VPC and the Red Hat managed control plane without traversing the public internet.

{AWSPrivateLink} connectivity is supported both into (ingress) and out of (egress) the {PlatformNameShort} control plane. 
Customers must work with the Red Hat SRE Team to set up the following {AWSPrivateLink} connectivity directions: 

* From customer VPC to Red Hat managed control Plane 
* From Red Hat managed control plane to customer VPC

To configure bi-directional connectivity, complete the following steps:

. Submit {CustomerSupport} cases to Red Hat to begin this process. 
.. A separate ticket must be created for ingress and egress 
. The Redhat SRE team will work together with the customer and enable {AWSPrivateLink} Connectivity via the support case. 

To begin this process see link:{BaseURL}/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_service_on_aws/saas-private-link#proc-saas-enabling-aws-privatelink[Enabling AWS PrivateLink connectivity].
