:_mod-docs-content-type: CONCEPT

[id="con-azure-disaster-recovery_{context}"]

= Disaster recovery

[role="_abstract"]
When you deploy {AAPonAzureNameShort}, you must enable or disable disaster recovery in the `Business Continuity` tab of the form.
There is no default setting for disaster recovery.

The disaster recovery feature incurs additional {Azure} infrastructure costs.
See link:{BaseURL}/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_on_microsoft_azure_guide/index#con-azure-infrastructure-usage_azure-intro[{AAPonAzureNameShort} infrastructure usage] for details of the Service Shape of the Storage account.

If you want to enable disaster recovery on an existing instance of {AAPonAzureNameShort}, contact Red Hat customer support.

The disaster recovery feature creates a nightly backup of your managed application and stores it in a business continuity region that is geographically distant to your primary region.
For information about regional pairings, refer to link:https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies[Azure cross-region replication pairings for all geographies] in the {Azure} reliability documentation.

For information about recovering your application after a service-impacting event, see the link:https://access.redhat.com/articles/7010302[Disaster recovery for {AAPonAzureNameShort}] article on the Red Hat customer portal.

== Primary and business continuity regions

{PlatformNameShort} on {Azure} uses Azure regional pairs to ensure data residency and compliance within the same geography. The following table lists primary regions and their corresponding business continuity (secondary) regions.


[.scrollable-table]
--
[cols="1,1", options="header"]
|===
| Primary Region | Business continuity region

| Australia East, Col 1 | Australia Southeast, Col 2

| Austria East, Col 1 | N/A, Col 2

| Belgium Central, Col 1 | N/A, Col 2

| Brazil South, Col 1 | South Central US, Col 2

| Canada Central, Col 1 | Canada East, Col 2

| Central India, Col 1 | South India, Col 2

| Central US, Col 1 | East US 2, Col 2

| Chile Central, Col 1 | N/A, Col 2

| Denmark East, Col 1 | N/A, Col 2

| East Asia, Col 1 | Southeast Asia, Col 2

| East US, Col 1 | West US, Col 2

| East US 2, Col 1 | Central US, Col 2

| France Central, Col 1 | France South, Col 2

| Germany West Central, Col 1 | Germany North, Col 2

| Indonesia Central, Col 1 | N/A, Col 2

| Israel Central, Col 1 | N/A, Col 2

| Italy North, Col 1 | N/A, Col 2

| Japan East, Col 1 | Japan West, Col 2

| Japan West, Col 1 | Japan East, Col 2

| Korea Central, Col 1 | Korea South, Col 2

| Malaysia West, Col 1 | N/A, Col 2

| Mexico Central, Col 1 | N/A, Col 2

| New Zealand North, Col 1 | N/A, Col 2

| North Europe, Col 1 | West Europe, Col 2

| Norway East, Col 1 | Norway West, Col 2

| Poland Central, Col 1 | N/A, Col 2

| Qatar Central, Col 1 | N/A, Col 2

| South Africa North, Col 1 | South Africa West, Col 2

| South Central US, Col 1 | North Central US, Col 2

| Southeast Asia, Col 1 | East Asia, Col 2

| Sweden Central, Col 1 | Sweden South, Col 2

| Switzerland North, Col 1 | Switzerland West, Col 2

| UAE North, Col 1 | UAE Central, Col 2

| UK South, Col 1 | UK West, Col 2

| West Europe, Col 1 | North Europe, Col 2

| West US 2, Col 1 | West Central US, Col 2

| West US 3, Col 1 | East US, Col 2
|===
--
