:_mod-docs-content-type: CONCEPT

[id="azure_aks-cidr_{context}"]

= AKS CIDR Blocks

[role="_abstract"]
You can configure the AKS network CIDR blocks.
Traffic that originates from the AKS cluster appears to come from the range configured in AKS, not from the VNET.

When you are planning your AKS CIDR block configuration, bear the following in mind:

* Ensure that these network ranges do not overlap with any existing network range in your enterprise network.

* Do not use the following reserved network ranges:
+
[cols="a"]
|===
|AKS Reserved CIDR Blocks

|169.254.0.0/16
|172.30.0.0/16
|172.31.0.0/16
|192.0.2.0/24
|172.17.0.1/26
|===

You can configure the AKS network CIDR blocks in the `Configure AKS networks` area of the `networking` tab.
Do not accept the default values suggested in the Azure user interface.
Instead, use the CIDR blocks that you have planned.
The settings have the following requirements:

[cols="20%,40%,40%"]
|===
|Network | Description | Requirements
| Service CIDR | A CIDR notation IP range from which to assign service cluster IPs.

It must not overlap with any Subnet IP ranges. |  Requires a /24 block at minimum. A larger block is not necessary.

This CIDR block must not intersect with the CIDR of the Pod CIDR block.

This CIDR block also must not intersect with the CIDR of the VNET CIDR block.
| DNS Service IP | An IP address assigned to the Kubernetes DNS service.

It must be within the Kubernetes service address range specified in `serviceCidr`. |  Must be an IP address in the Service CIDR other than the first IP in that range.

Red Hat recommends using the first `.10` IP address within the Service CIDR block.
| Pod CIDR | A CIDR notation IP range from which to assign pod IPs when kubenet is used. |  Requires a /19 or larger block.

This CIDR block must not intersect with the CIDR of the Service CIDR block.

|===

