:_mod-docs-content-type: CONCEPT

[id="con-saas-limited-support-status"]
= Limited support status

[role="_abstract"]
When a deployment transitions to "Limited Support" status, Red Hat will no longer troubleshoot execution plane issues.

The SLA is no longer applicable and credits requested against the SLA are denied. 
However, this does not mean you lose all product support. A deployment can return to full support if you address the issues that caused the limited status. 

A deployment might move to a Limited Support status for several reasons, including:

Lack of an execution plane:: A customer execution plane is required for automation. 
If you have not configured one or if it's in a degraded state, you must fix these issues before receiving automation support.
Unsupported Execution Plane Dependencies:: 
Both Red{nbsp}Hat Enterprise Linux (RHEL) and OpenShift-based execution planes need regular maintenance and upgrades to meet minimum supported versions for {PlatformNameShort} dependencies.
You can upgrade these resources using various methods, such as Ansible for patching, Red Hat Satellite, or DNF automatic updates.
Keeping your OS, cluster, and receptor resources updated with supported {PlatformNameShort} helps reduce support issues.
