:_mod-docs-content-type: CONCEPT

[id="con-azure-disaster-recovery_{context}"]

= Disaster recovery

[role="_abstract"]
When you deploy {AAPonAzureNameShort}, you must enable or disable disaster recovery in the `Business Continuity` tab of the form.
There is no default setting for disaster recovery.

The disaster recovery feature incurs additional {Azure} infrastructure costs.
See link:{BaseURL}/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_on_microsoft_azure_guide/index#con-azure-infrastructure-usage_azure-intro[{AAPonAzureNameShort} infrastructure usage] for details of the Service Shape of the Storage account.

If you want to enable disaster recovery on an existing instance of {AAPonAzureNameShort}, contact Red Hat customer support.

The disaster recovery feature creates a nightly backup of your managed application and stores it in a business continuity region that is geographically distant to your primary region.
For information about regional pairings, refer to link:https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies[Azure cross-region replication pairings for all geographies] in the {Azure} reliability documentation.

For information about recovering your application after a service-impacting event, see the link:https://access.redhat.com/articles/7010302[Disaster recovery for {AAPonAzureNameShort}] article on the Red Hat customer portal.

== Primary and business continuity regions

{PlatformNameShort} on {Azure} uses Azure regional pairs to ensure data residency and compliance within the same geography. The following table lists primary regions and their corresponding business continuity (secondary) regions.


[.scrollable-table]
--
[cols="1,1", options="header"]
|===
| Primary Region | Business continuity region

| Australia East | Australia Southeast

| Austria East | N/A

| Belgium Central | N/A

| Brazil South | South Central US

| Canada Central | Canada East

| Central India | South India

| Central US | East US 2

| Chile Central | N/A

| Denmark East | N/A

| East Asia | Southeast Asia

| East US | West US

| East US 2 | Central US

| France Central | France South

| Germany West Central | Germany North

| Indonesia Central | N/A

| Israel Central | N/A

| Italy North | N/A

| Japan East | Japan West

| Japan West | Japan East

| Korea Central | Korea South

| Malaysia West | N/A

| Mexico Central | N/A

| New Zealand North | N/A

| North Europe | West Europe

| Norway East | Norway West

| Poland Central | N/A

| Qatar Central | N/A

| South Africa North | South Africa West

| South Central US | North Central US

| Southeast Asia | East Asia

| Sweden Central | Sweden South

| Switzerland North | Switzerland West

| UAE North | UAE Central

| UK South | UK West

| West Europe | North Europe

| West US 2 | West Central US

| West US 3 | East US
|===
--
