:_mod-docs-content-type: PROCEDURE

[id="azure-monitor-deployment-engine_{context}"]

= Monitoring deployments on the {PlatformNameShort} Deployment Engine

[role="_abstract"]

The deployment engine displays information about your {AAPonAzureNameShort} deployment.
You can monitor the progress of the deployment, restart failed deployment steps, and cancel the deployment.

When you begin deploying {AAPonAzureNameShort}, the Azure interface displays the *Overview* page for the deployment.
The *Overview* page displays the deployment status.

.Procedure

. When the status in the *Overview* page shows "Your deployment is complete", navigate to the deployed managed application.
. Click *Parameters and Outputs* in the *Settings* menu for the deployed managed application.
* *Note:* Approximately 10 minutes into the deployment process, the *Outputs* section of the *Parameters and Outputs* page displays a link to the *`deploymentEngineUrl`*.
. Copy the link and paste it in another browser tab to open the login page for the deployment engine.
. Login to the deployment using the following credentials:
  * *Username*: _admin_
  * *Password*: Use the _Administrator Password_ that you chose when configuring your deployment.
. The deployment driver displays a message indicating that your deployment is underway.
Click btn:[Log in with Red Hat account]. The **Red Hat login** page opens.
. In the **Red Hat login** page, enter your credentials if you already have a Red Hat account.
.. If you do not have a Red Hat account, click btn:[Register for a Red Hat account] to create one.

.Verification 

After logging in with your Red Hat account, the {PlatformNameShort} Deployment Engine page opens.
