:_mod-docs-content-type: PROCEDURE

[id="azure-cancel-deployment_{context}"]

= Cancel {AAPonAzureNameShort} deployments

[role="_abstract"]
You can gracefully cancel a {AAPonAzureNameShort} deployment. 

.Procedure

. Login to the deployment engine to display the progress of the deployment steps in the *Ansible Automation Platform Deployment Engine* page.
Refer to
link:{BaseURL}/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_on_microsoft_azure_guide/index#azure-monitor-deployment-engine_azure-deploy[Monitoring deployments on the {PlatformNameShort} Deployment Engine]
for information on accessing and logging into the *Ansible Automation Platform Deployment Engine* page.
. To cancel the deployment, click btn:[Cancel Deployment] and confirm.

.Verification

* To confirm you cancelled the deployment processes on Azure, navigate to the *Overview* page for the managed resource group in which you deployed {PlatformNameShort} and select *Deployments*.

[IMPORTANT]
====
Canceling the deployment does not delete the managed application from your Azure subscription.
To avoid incurring costs for the managed application and other resources that are still running, you must delete them.

To delete Azure resources, navigate to the resource group for your deployment in the Azure portal. Select the resources you want to delete and click btn:[Delete].
For more information about deleting resources, refer to link:https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resources-portal[Manage Azure resources by using the Azure portal] in the Microsoft Azure documentation.
====

