:_mod-docs-content-type: PROCEDURE

[id="proc-saas-set-up-public"]

= Accept a public offer

[role="_abstract"]
To set up {SaaSonAWS} you must link your {AWS} (AWS) and Red{nbsp}Hat accounts through the AWS marketplace.

When you link your accounts you can provision and configure your cluster through the Red{nbsp}Hat Hybrid Cloud Console.  

.Prerequisites
* An AWS Account

.Procedure
. Log in to your AWS account.
. Navigate to the *Discover products* page of the AWS Marketplace. If you have already accepted your offer you can find it in the *Manage subscriptions* page.
. In the search field search for "{SaaSonAWS}". 
** Depending on your region select one of the following: 
*** For EMEA, select *Red{nbsp}Hat Limited*.
*** For the rest of the world, select *Red{nbsp}Hat*.
. Click btn:[View purchase options].
. Select your desired contract duration.
. If you would like your contract to auto renew, click btn:[auto renewal settings].
. Select the contract options.
. Optional: Add a purchase order number.
. Click btn:[Create contract].
. Click btn:[Click here to set up your account]. This redirects you to {RHSSO} where you must:
.. Create or sign into your Red{nbsp}Hat account.
.. Connect your AWS account to the Red{nbsp}Hat account. This redirects you to the *Provision environment* page on the Red{nbsp}Hat Hybrid Cloud Console. Here you can start configuring your environment.
. Enter your AWS account ID and click btn:[Verify].
* This account ID must be the account ID that purchased the offer from the AWS Marketplace. 
The system does not recognize associated or nested accounts.
. After your AWS ID is validated click btn:[Next].
. Select your required region.
. Click btn:[Provision].

.Verification 

This redirects you to the *Environment details* page of the *Instances*, where you can see all the details of your created instance.
Here you can check whether your instance is *Ready* or still in a *Provision in progress* state.

Provisioning your environment can take up to two hours.
When it is ready, you will receive a confirmation email at the address linked to your account. 

[IMPORTANT]
====
Update your password as soon as possible.
The confirmation email includes a link to your admin password, which you will use to log in and change your password.
This link is one-time use, so be prepared before clicking it.
====

If you did not receive the email or the initial admin password has expired, you must to submit a link:https://access.redhat.com/support[support ticket] and the Red{nbsp}Hat team will assist you with next steps.