:_mod-docs-content-type: PROCEDURE
[id="proc-saas-customizing-your-domain"]

= Plan your custom domain

[role="_abstract"]
To set up a custom domain for your deployment, you must complete several preparatory steps, including domain identification and TLS certificate creation.
This procedure outlines the necessary planning activities to ensure a successful custom URL configuration with Red Hat SRE assistance.


.Prerequisites
* Ensure that you have management over the domain or subdomain you intend to use in order to add multiple records.
* Ensure the DNS servers that you use to resolve the record must be accessible wherever you intend to use the domain.
* Ensure that you use the same domain for all URLs in the deployment (for example, use `exampledomain.com` for custom URLs). 


.Procedure

. Identify the domain or subdomain that you intend to use.
. Create the TLS certificate. 
.. To ensure the validity of a TLS certificate for a custom domain, you must confirm that the certificate is generated for the platform record and all mesh-ingress records are included in the Subject Alternative Name (SAN) parameter. Alternatively, you can opt to generate a wildcard certificate to cover the subdomains of your primary custom domain.
.. Bundle the certificate, private key, and any optional intermediary certificates into a zip.
+
[IMPORTANT]
====
TLS Certificate requirements for custom domains:

* *Private Key:* The private key must be unencrypted and cannot have a passphrase or be password protected.
* *Expiration:* Initial certificates must be valid for at least one year.
* *Renewal:* You must initiate a support ticket to renew the certificate at least 14 days before the expiration date. When renewing you must use one of the following formats for the certificate's Subject Alternative Names (SANs):
** *Explicit SANs:* List the required subdomains: `platform`, `mesh-ingress-0`, and `mesh-ingress-1`.
** *Wildcard certificate:* Use a wildcard to cover all subdomains (for example, `*.exampledomain.com`).

====
+
. Open a link:https://access.redhat.com/support/cases/#/case/new/get-support?caseCreate=true[support ticket] with Red Hat requesting a custom URL configuration to your deployment and supply the following information:
* Company Name
* Deployment information (for example, `cus-xxxx`)
* Custom domain (for example, `exampledomain.com`)
* Provide the zip file containing the certificates, or request a presigned URL for secure upload.
. Allow the SRE team to apply the configuration to your deployment, verify the functionality, and collaborate with you on follow-up steps via the support ticket.
. After your configuration is complete, apply the custom domain to your deployment.
+
[NOTE]
====
New mesh-ingresses using the custom domain replace the original ones. 
====
+
. Reconfigure your execution nodes if you configured them previously with the old domain.

