:_mod-docs-content-type: PROCEDURE

[id="proc-azure-outbound-route_{context}"]

= Route outbound traffic through virtual appliances

[role="_abstract"]
If your organization uses Azure firewall services or third-party firewall appliances through a Virtual Appliance connection, you must configure outbound connectivity from the managed application, to enable Red Hat to maintain your application and to enable automation against external resources.

The easiest way to implement this is to create a firewall rule that allows all outbound traffic from port 443.

If you choose not to allow all outbound traffic from  port 443, you must configure routes.

.Procedure

. For Red Hat to manage and upgrade {AAPonAzureNameShort} and execute security patching, any machine in the Azure Kubernetes service (AKS) cluster must be allowed to submit a request to pull updates for containers used by {PlatformNameShort}.
.. Add routes in the {PlatformNameShort} route table for outbound traffic from the full CIDR range of the {AAPonAzureNameShort} managed application to the domains listed in the link:https://access.redhat.com/articles/6972355[Azure Virtual Appliance Routing with Ansible Automation Platform on Azure] article on the Red Hat Customer Portal.
. You must also allow traffic from your firewall to any other external domain or IP address that you want {PlatformNameShort} to run automation jobs against.
Otherwise, your firewall blocks connectivity between {PlatformNameShort} and destinations for automation.
. {PlatformNameShort} requires a public DNS zone to provide SSL certificates.
This public DNS zone is in the managed resource group of the deployment.
The platform must be able to communicate via DNS queries with the servers listed in the DNS zone to complete certificate challenges with our upstream provider.
Blocking this communication prevents successful certificate renewal.

.Additional resources

* link:https://docs.microsoft.com/en-us/azure/virtual-network/manage-route-table#create-a-route[Create a route]