:_mod-docs-content-type: PROCEDURE

[id="proc-azure-create-service-principal_{context}"]

= Creating a service principal for automating Azure resources

[role="_abstract"]
To enable the {PlatformNameShort} application to access and manage Azure resources, you must provide authorization credentials after deployment.
The Microsoft Azure collection supports service principal authentication.

To create a service principal, you must have administrator privileges with tenancy-wide permissions on your Azure tenant.
Your {AAPonAzureNameShort} deployment provisions in the same Subscription ID as the service principal created in this step.

.Procedure

. Navigate to the Azure portal
. Click the link:https://docs.microsoft.com/en-us/azure/cloud-shell/overview[Cloud Shell] icon to open a bash Cloud Shell in your browser.
. Set the Azure CLI to use the subscription that you intend to use for automating Azure services. Run the following command from the shell:
+
-----
az account set --subscription <your_subscription_id>
-----
. Run the following command using the Azure CLI to create a privileged service principal in {MSEntraID}:
+
-----
az ad sp create-for-rbac --name ansible --role Contributor
-----
+
The output displays the _appID_ and _tenant_ keys for the service principal:
+
-----
{
  "appId": "xxxxxxx-xxx-xxxx",
  "displayName": "ansible",
  "name": "xxxxxxx-xxx-xxxx",
  "password": "xxxxxxx-xxx-xxxx",
  "tenant": "xxxxxxx-xxx-xxxx"
}
-----
. Store the service principal details securely, as they are displayed only when you create the secret.


