:_mod-docs-content-type: REFERENCE

[id="ref-azure-resource-quotas_{context}"]

= Plan for resource quotas and infrastructure limits

[role="_abstract"]
Microsoft imposes resource limits within each Azure region. 
The CPU limit is the most likely to impact {AAPonAzureName}.

Before you install {AAPonAzureNameShort}, ensure that you have capacity to deploy the managed application into your desired region.
Refer to link:{BaseURL}/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_on_microsoft_azure_guide/index#con-azure-infrastructure-usage_azure-intro[Ansible Automation Platform on Microsoft Azure infrastructure usage] for infrastructure requirements.

== Regional vCPU limits

The Azure resources used during the deployment of the managed application temporarily exceed the resource requirements in link:{BaseURL}/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_on_microsoft_azure_guide/index#con-azure-infrastructure-usage_azure-intro[Ansible Automation Platform on Microsoft Azure infrastructure usage].
The `Total Regional vCPUs` quota is temporarily consumed when deploying the managed application.

Every Azure region has a separate `Total Regional vCPUs` quota.
To prevent installation failure, ensure that you have at least 80 DDSv5 and 8 DSV3 vCPUs available in the Azure region where you want to deploy the managed application.

You can view the resource quotas for your subscription from the Azure console. 
Open the *My Quotas* page and select the region where you wish to deploy the managed application to view your allocation and usage metrics for that region.
Ensure that you have selected a single region. 
Viewing all regions at once does not show the limitations of a single Azure region.

== Regional StandardCore limits

The `StandardCore` limit is a compute metric for the resources that are temporarily consumed when deploying the managed application.

It is possible that the {AAPonAzureNameShort} can deploy without hitting the `StandardCore` limit.
When a deployment fails because the consumed resources hit the `StandardCore` limit, the error message includes `container group quota 'StandardCores' exceeded`:

----
code: DeploymentFailed
message:
  At least one resource deployment operation failed. Please list deployment operations for details.
  Please see https://aka.ms/DeployOperations for usage details.
details:
  - code: DeploymentScriptContainerGroupInvalidSettings
    message:
      Resource type 'Microsoft.ContainerInstance/containerGroups'
      container group quota 'StandardCores' exceeded in region 'eastus'.
      Limit: '10', Usage: '10' Requested: '1'.
----

== Request StandardCore limit increase

The `StandardCore` metric is not displayed in the *My Quotas* page in the Azure console. To request the value of your regional limit, contact Microsoft directly.

If your deployments fail because the consumed resources reach this limit, you must submit a resource increase request for `StandardCore` to Microsoft.
Only submit a quota increase request if you encounter a deployment failure due to this issue.

Use the following information to respond to questions from Microsoft support:

Will the container groups be run in Linux or Windows?:: Linux	
What will the core and memory be in your Container Group instance?:: Red Hat recommends 20 cores, 16 GB	
When will you create all the Container Group Instances?:: During managed application deployment of {AAPonAzureName}
How frequent will you create/delete the container groups?:: Only during managed application deployment of {AAPonAzureName}

