:_mod-docs-content-type: REFERENCE

[id="performance-metrics-eda-aap-aws_{context}"]

= Performance guidelines for {EDAName} on {SaaSonAWSShort}

[role="_abstract"]
Use this information to plan and configure link:{baseUrl}/red_hat_ansible_automation_platform/{PlatformVers}/html/using_automation_decisions/index[{EDAName}] on {SaaSonAWSShort}.
All customer workloads differ, and performance results may vary. 
Red Hat recommends monitoring *Subscription Watch* for {PlatformNameShort} Service on AWS meters and creating cost alerts in AWS.

The following table reflects the observed performance and resource utilization for the tested configuration.

*Observed performance and resource utilization*
[cols="3,3,2", options="header"]
|===
|Category |Metric |Value

.3+|Tested configuration
|Rulebook Activations |5
|Events published per second |120
|Actions per second |20

.2+|Derived metrics
|Actions per activation (20 events/sec x 30 sec) |600
|Total actions across all activations |3,000

.1+|Infrastructure
|vCPUs |12

.4+|Observed performance
|Total Events Sent |3,000
|Job Events |600
|Failed Iterations |0
|Event Processing Time |77.07 seconds
|===

[NOTE]
====
Performance metrics change as the control plane scales (up or down) based on the running workload.
====


