:_content-type: REFERENCE

[id="azure-limited-support-status_{context}"]
= Limited support status

[role="_abstract"]
Customers may implement Azure infrastructure changes or policies that negatively affect the functionality of the service and Red Hat’s ability to monitor and service it.
In such scenarios, the deployment can transition into a limited support status.
A deployment may move to a limited support status for many reasons, including the following scenarios:

Inactive Ansible subscriptions::
Red Hat issues subscription entitlements through the application deployment process.  The entitlement expires one year after it is issued.  Customers are emailed prior to expiration to renew the entitlement.  This process issues a new entitlement for the next year and can be imported into {PlatformNameShort}.
Failure to renew:::
When an entitlement expires, customers can continue to use {AAPonAzureNameShort}. However, Red Hat support requires a valid entitlement before assisting with support issues.
Changes to customized policies::
{AAPonAzureNameShort} runs on infrastructure within a customer’s Azure tenant.  This means that customer Azure policies can affect the deployment and function of the platform.  Given the flexibility of Azure policy definitions, it is impossible to list all policies that can cause infrastructure or operational issues with the platform.  When those events happen, the Red Hat SRE team can help identify the policy causing the issue, and suggested remediation.  That remediation may require customer policy changes in order for the managed application to function correctly.
Failure to remediate:::
When a policy conflict arises, the Red Hat team reaches out to the customer to remediate. Some of these changes are time sensitive and can impact the platform’s operational function. The Red Hat Site Reliability Engineering (SRE) team will pause maintenance and upgrades until the customer resolves the policy issues.
Changes to firewall and network configurations::
When configuring egress routes from {AAPonAzureNameShort}, customers are required to route traffic to a set of domains on the public internet used for the deployment, monitoring and maintenance of the platform.
Failure to set up:::
The {PlatformNameShort} on Managed Azure will be in a state where it cannot be monitored or serviced by the Red Hat SRE team.
Changes to quota limits::
A prerequisite for {AAPonAzureNameShort} requires adequate capacity to deploy the managed application in the selected region. Microsoft imposes restrictions on limits (CPU) in each region. It is expected that the customers set up their infrastructure with the specifications as listed in the Product Documentation.
Failure to remediate:::
As the Red Hat SRE team perform regular maintenance and improvements, the quota limitations in the region could prevent them to manage the deployment consistently and can eventually result in an inability to manage the offering.
Incorrect CIDR ranges::
During initial deployment, customers can configure networking address range (CIDR block) for the VNet the {PlatformNameShort} uses. After configuration, when you have created the network, you cannot change CIDR blocks. To male a change you must redeploy the managed {PlatformNameShort} application with the configurations specified in the documentation.
Failure to remediate:::
While the Azure user experiences allow customers to set CIDR blocks of choice, the use of the smaller CIDR ranges smaller than our guidelines can create the circumstance that your deployment is in limited supported state where the platform is unable to scale for both automation and management workloads.
