:_mod-docs-content-type: REFERENCE

[id="ref-azure-responsibilities"]
= Overview of responsibilities for {AAPonAzureNameShort}

[role="_abstract"]
Red Hat is your primary contact for support for {AAPonAzureName}.
For support issues, contact Red Hat customer support.
Red Hat engages Microsoft support for infrastructure and platform issues.
For account questions, contact your Red Hat account executive.

The following table describes who is responsible for support and change management across {AAPonAzureNameShort} resources.

.{AAPonAzureNameShort} responsibility matrix
[cols="3,1,1",options="header"]
|===
| Resource | Support | Change management

| Customer data
| Customer
| Customer

| Identity and access management
| Customer
| Customer

| Post-deployment network configuration and routing
| Customer
| Customer

| Infrastructure monitoring and operations
| Red Hat and Microsoft
| Microsoft

| {PlatformNameShort} monitoring
| Red Hat
| Red Hat

| Logging
| Red Hat
| Red Hat

| Upgrades
| Red Hat
| Red Hat

| Capacity management
| Red Hat
| Red Hat

| Physical infrastructure security
| Microsoft
| Microsoft
|===

[id="ref-azure-security-compliance"]
== Security and regulation compliance

{AAPonAzureNameShort} is not currently certified for any compliance standard.
Red Hat maintains compliance responsibility for the offering where required by law, Red Hat, or Microsoft policies.

[id="ref-azure-customer-responsibilities"]
== Customer responsibilities

You are responsible for all configuration and use of {PlatformNameShort}.
This includes the following areas:

* Application settings for {ControllerName} and {PrivateHubName}
* All customer-facing functions of these applications, such as managing projects, templates, and {ExecEnvName}
* Single sign-on (SSO) configuration

[role="_additional-resources"]
.Additional resources

* xref:con-azure-lifecycle_azure-intro[{AAPonAzureNameShort} lifecycle]
