
[id="con-top-overview-usage"]

= Summary of top and overview usage

[role="_abstract"]
{AutomationDashboardName} displays a summary of the top and overview usage for your selected report. This includes the following data:

* **Total number of successful jobs**: The number of automation jobs completed successfully. 
* **Total number of failed jobs**: The number of automation jobs that encountered errors. Analyzing these failures can help improve efficiency. 
* **Total number of unique hosts automated**: This is the number of Controller inventory records you have automated. 
* **Total hours of automation**: The cumulative time that {PlatformNameShort} spent running jobs. 
* **Number of times jobs were run**: The total number of individual job executions.
* **Number of hosts jobs are running on**: The total number of hosts that jobs are executed upon. 
* **Top 5 projects**: The top five automation projects based on the number of running jobs. 
* **Top 5 users**: The top five users of {PlatformNameShort}, with a breakdown of the total number of jobs run by each user.
+
[NOTE] 
====
Scheduled jobs can affect these results, because they do not represent a real, logged-in user.
====
