// Module included in the following assemblies:
// assembly-view-key-metrics

[id="con-filter-automation-data_{context}"]

= Filter and save automation data

Automation Dashboard provides filtering options for analyzing your Ansible Automation Platform automation runs. You can select one or more filtering options, choose a time period and a currency, and save your report to the dashboard.

== Filters

You can select one or more of the following options to customize your report:

* **Template:** Select one or more Job Templates.
* **Organization:** Select one or more Organizations.
* **Project:** Select one or more Projects.
* **Label:** Select one or more automations by label. Labels must be preconfigured and assigned to Ansible Automation Platform before they display in Automation Dashboard. For more on configuring labels, see the _Creating a job template_ procedure.

== Time period and currency

After you select your filters, choose a time period for analysis and a currency to demonstrate automation savings.

* A shorter time period is useful for specific automation use cases.
* A longer time period is useful for overall platform usage and automation growth.

Changing from one currency to another does not convert the value. You must manually change the manual and automation cost figures to reflect the currency you select.

== Save a report

Use *Save as report* to save this report to your Automation Dashboard. You can retrieve it at any time by using *Select a report*.