:_newdoc-version: 2.18.3
:_template-generated: 2025-05-05
:_mod-docs-content-type: PROCEDURE

[id="self-service-add-scm-credentials-aap_{context}"]
= Adding Source Control Credentials for GitHub or Gitlab in {PlatformNameShort}

.Prerequisite
Ensure that the user who needs access to the repository has the appropriate permissions.

.Procedure
. Sign in to {PlatformNameShort} as an administrator.
. Navigate to {MenuAECredentials}.
. On the *Credentials* page, click btn:[Create credential].
. Add the following details:
** *Name*: Credential name.
** *Organization*: The name of the organization with which the credential is associated.
The default is *Default*.
+
[NOTE]
====
Credentials in {PlatformNameShort} are always created under a specific organization.
====
** *Credential type*: Source Control.
** *Username*: Your Github username or the Gitlab group name under which the repository is hosted.
+
[NOTE]
====
{SelfServiceShortStart} does not support creating or modifying Gitlab repositories under personal user accounts. You must use a Gitlab Group instead.
====

