:_mod-docs-content-type: CONCEPT

[id="con-devspaces-intro-adoc_{context}"]
= Introduction to {AnsibleWorkspaces}

[role="_abstract"]
{AnsibleWorkspaces} offer centralized management and policy enforcement.
Administrators gain improved control, trust, and governance over the consistent, secure environments used to develop automation.
Developers do not need to install applications on their workstations, which is useful for locked down environments.

{ToolsName} and runtimes are pre-configured in {AnsibleWorkspaces}.
Developers can start creating projects for automation content quickly by logging in to {AnsibleWorkspaces} in a browser. 

The development tools in {AnsibleWorkspaces} are based on Ansible recommended practices, which improves the quality and reliability of your automation content.
As a component of your Red Hat {PlatformNameShort} subscription, {AnsibleWorkspaces} are fully supported.

To ensure that your automation content files persist when you quit {AnsibleWorkspaces}, you push your projects to a git repository in a source control manager (SCM) that is linked to your workspace.

