:_mod-docs-content-type: CONCEPT

[id="rhdh-install-ocp-prereqs_{context}"]
= Prerequisites

[role="_abstract"]
To proceed, you must have {RHDH} installed on {OCP} (OCP) and a valid subscription to {PlatformName}.

* {RHDH} installed on {OCP}.
** For Helm installation, follow the steps in the 
https://docs.redhat.com/en/documentation/red_hat_developer_hub/{RHDHVers}/html/installing_red_hat_developer_hub_on_openshift_container_platform/index#assembly-install-rhdh-ocp-helm[Installing Red Hat Developer Hub on OpenShift Container Platform with the Helm chart]
section of _Installing Red Hat Developer Hub on OpenShift Container Platform_.
** For Operator installation, follow the steps in the 
https://docs.redhat.com/en/documentation/red_hat_developer_hub/{RHDHVers}/html/installing_red_hat_developer_hub_on_openshift_container_platform/index#assembly-install-rhdh-ocp-operator[Installing Red Hat Developer Hub on OpenShift Container Platform with the Operator]
section of _Installing Red Hat Developer Hub on OpenShift Container Platform_.
* A valid subscription to {PlatformName}.
* An {OCPShort} instance with the appropriate permissions within your project to create an application.
* The {RHDH} instance can query the automation controller API.
* Optional: To use the integrated learning paths, you must have outbound access to developers.redhat.com.

