:_mod-docs-content-type: CONCEPT

[id="self-service-installation-prereqs_{context}"]
= Prerequisites

* You have a valid subscription to {PlatformName}.
* You have access to an instance of {PlatformName} {PlatformVers} with the appropriate permissions to create an OAuth application.
* You have access to an {OCPShort} instance (Version 4.12 or newer) with the appropriate permissions within your project to create an application.
* You have installed `oc`, the OpenShift command-line interface (CLI) tool, on your local machine.
You can use `oc` commands in your terminal to interact with your OpenShift cluster. 
+
For information on installing `oc`, see the
link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/cli_tools/openshift-cli-oc#cli-getting-started[Getting started with the OpenShift CLI]
chapter of the _Understanding OpenShift Container Platform_ guide.
* You have installed Helm 3.10 or newer. Helm is a package manager for applications on {OCPShort}.
See the link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/building_applications/working-with-helm-charts#installing-helm[Installing Helm]
chapter of the _OpenShift Container Platform Building applications_ guide.

