:_newdoc-version: 2.18.3
:_template-generated: 2025-05-05
:_mod-docs-content-type: PROCEDURE

[id="self-service-telemetry-disable_{context}"]
= Disabling telemetry data collection

You can disable and enable the telemetry data collection feature for {SelfServiceShort} by updating the Helm chart for your {OCPShort} project.

.Procedure

. Log in to the {OCPShort} console and open the project for {SelfServiceShort} in the *Developer* perspective.
. Navigate to *Helm*.
. Click the *More actions {MoreActionsIcon}* icon for your {SelfServiceShort} Helm chart and select *Upgrade*.
. Select *YAML view*.
. Locate the `redhat-developer-hub.global.dynamic.plugins` section of the Helm chart.
. To disable telemetry data collection, add the following lines to the `redhat-developer-hub.global.dynamic.plugins` section.
+
----
redhat-developer-hub:
  global:
    ....
    dynamic:
      plugins:
        - disabled: true
          package: >-
            ./dynamic-plugins/dist/backstage-community-plugin-analytics-provider-segment
----
+
To re-enable telemetry data collection, delete these lines.
. Click btn:[Upgrade] to apply the changes to the Helm chart and restart the pod.

