:_mod-docs-content-type: PROCEDURE

[id="rhdh-update-plugins-operator-version-numbers_{context}"]
= Updating the Ansible plug-ins version numbers for an Operator installation

[role="_abstract"]
To upgrade the Ansible plug-ins, you must edit the `rhaap-dynamic-plugins-config` ConfigMap to reference the new OCI image tag.

.Procedure

. Log in to your {OCPShort} instance.
. Navigate to ConfigMaps and select the `rhaap-dynamic-plugins-config` map.
. Select the YAML tab to edit the file.
. In the `plugins` list, update the version tag at the end of the `package` URL for both the frontend and backend plugins.

// For example, use the `.integrity` value from `ansible-plugin-backstage-rhaap-dynamic-x.y.z.tgz` for the `ansible-plugin-backstage-rhaap-dynamic-x.y.z.tgz.integrity` key.
+
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: rhaap-dynamic-plugins-config
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      # FRONTEND PLUGIN
      - disabled: false
        # UPDATE the version tag at the end of the URL (e.g., :2.1)
        package: 'oci:registry.redhat.io/ansible-automation-platform/automation-portal:2.1'
        pluginConfig:
          dynamicPlugins:
            frontend:
              ansible.plugin-backstage-rhaap:
                appIcons:
                  - importName: AnsibleLogo
                    name: AnsibleLogo
                dynamicRoutes:
                  - importName: AnsiblePage
                    menuItem:
                      icon: AnsibleLogo
                      text: Ansible
                    path: /ansible

      # BACKEND PLUGIN
      - disabled: false
        # UPDATE the version tag at the end of the URL (e.g., :2.1)
        package: 'oci:registry.redhat.io/ansible-automation-platform/automation-portal:2.1'
        pluginConfig:
          dynamicPlugins:
            backend:
              ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
----
. Click btn:[Save].
+
The Red Hat Developer Hub detects the configuration change and reload the plug-ins automatically.


.Verification

. In the OpenShift UI, click *Topology*.
. Make sure that the {RHDH} instance is available.

