:_mod-docs-content-type: PROCEDURE

[id="rhdh-uninstall-ocp-helm_{context}"]
= Uninstalling a Helm chart installation

[role="_abstract"]
To uninstall the Ansible plug-ins from a Helm chart installation, you remove templates using the ansible:content:create action first. Then, you delete the plug-in configuration from the Helm chart YAML, remove the extraContainers section, delete the Ansible block from the custom ConfigMap, and restart the deployment.

.Procedure

. In {RHDH}, remove any software templates that use the `ansible:content:create` action.
. In the OpenShift Developer UI, navigate to menu:Helm[developer-hub > Actions > Upgrade > Yaml view].
. Remove the Ansible plug-ins configuration under the `plugins` section.
+
----
...
global:
  ...
  # REMOVE the lines below:
  pluginMode: oci
  imageTagInfo: "2.1"

  dynamic:
    plugins: []
    pluginConfig:
      dynamicPlugins:
        frontend:
          ansible.plugin-backstage-rhaap:
            appIcons:
              - importName: AnsibleLogo
                name: AnsibleLogo
            dynamicRoutes:
              - importName: AnsiblePage
                menuItem:
                  icon: AnsibleLogo
                  text: Ansible
                path: /ansible
        backend:
          ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
----

. Remove the `extraContainers` section.
+
----
upstream:
  backstage: |
    ...
    extraContainers:
      - command:
          - adt
          - server
        image: >-
          registry.redhat.io/ansible-automation-platform-26/ansible-dev-tools-rhel9:latest
        imagePullPolicy: IfNotPresent
        name: ansible-devtools-server
        ports:
          - containerPort: 8000
    image:  
      pullPolicy: Always
      pullSecrets:
        - ...
        - rhdh-secret-registry
    ...
----
. Click btn:[Upgrade].
. Edit your custom {RHDH} config map, for example `app-config-rhdh`.
. Remove the `ansible` section.
+
----
data:
  app-config-rhdh.yaml: |
    ...
    ansible:
      analytics:
        enabled: true
      devSpaces:
        baseUrl: '<https://MyOwnDevSpacesUrl/>'
      creatorService:
        baseUrl: '127.0.0.1'
        port: '8000'
      rhaap:
        baseUrl: '<https://MyAapSubcriptionUrl>'
        token: '<TopSecretAAPToken>'
        checkSSL: true
      automationHub:
        baseUrl: '<https://MyOwnPAHUrl/>'

----
. Restart the {RHDH} deployment.
