:_mod-docs-content-type: PROCEDURE

[id="rhdh-add-plugin-config_{context}"]
= Adding the Ansible plug-ins configuration

[role="_abstract"]
Modify the Red Hat Developer Hub Helm chart to add the Ansible plug-ins. The configuration depends on the plug-in delivery method you chose earlier.

.Procedure
. In the OpenShift Developer UI, navigate to menu:Helm[developer-hub > Actions > Upgrade > Yaml view].
. Update the Helm chart configuration to add the dynamic plug-ins in the {RHDH} instance.
Under the `plugins` section in the YAML file, add the dynamic plug-ins that you want to enable. Choose the configuration that matches your delivery method.
+
** OCI container delivery (recommended):
+
----
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - disabled: false
        package: 'oci://registry.redhat.io/ansible-automation-platform/automation-portal:21!ansible-plugin-backstage-rhaap'
        pluginConfig:
          dynamicPlugins:
            frontend:
              ansible.plugin-backstage-rhaap:
                appIcons:
                  - importName: AnsibleLogo
                    name: AnsibleLogo
                dynamicRoutes:
                  - importName: AnsiblePage
                    menuItem:
                      icon: AnsibleLogo
                      text: Ansible
                    path: /ansible
      - disabled: false
        package: 'oci://registry.redhat.io/ansible-automation-platform/automation-portal:2.1!ansible-plugin-scaffolder-backend-module-backstage-rhaap'
        pluginConfig:
          dynamicPlugins:
            backend:
              ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
----
+
Replace `x.y.z` with the Ansible plug-ins version.
+
[NOTE]
====
OCI delivery does not require the `integrity` hash values. The OCI registry handles integrity verification.
====


** HTTP plug-in registry:
+
----
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - disabled: false
        integrity: <SHA512 value>
        package: 'http://plugin-registry:8080/ansible-plugin-backstage-rhaap-dynamic-x.y.z.tgz'
        pluginConfig:
          dynamicPlugins:
            frontend:
              ansible.plugin-backstage-rhaap:
                appIcons:
                  - importName: AnsibleLogo
                    name: AnsibleLogo
                dynamicRoutes:
                  - importName: AnsiblePage
                    menuItem:
                      icon: AnsibleLogo
                      text: Ansible
                    path: /ansible
      - disabled: false
        integrity: <SHA512 value>
        package: >-
          http://plugin-registry:8080/ansible-plugin-scaffolder-backend-module-backstage-rhaap-dynamic-x.y.z.tgz
        pluginConfig:
          dynamicPlugins:
            backend:
              ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
----
+
Replace `x.y.z` with the correct plug-in version numbers and update the `integrity` values using the corresponding `.integrity` file content.


. Click btn:[Upgrade].
+
The {RHDH} pods restart and the plug-ins are installed.

.Verification

To verify that the plug-ins have been installed, open the `install-dynamic-plugin` container logs:

. Open the Developer perspective for the {RHDH} application in the OpenShift Web console.
. Select the *Topology* view.
. Select the {RHDH} deployment pod to open an information pane.
. Select the *Resources* tab of the information pane.
. In the *Pods* section, click *View logs* to open the *Pod details* page.
. In the *Pod details* page, select the *Logs* tab.
. Select `install-dynamic-plugins` from the drop-down list of containers to view the container log.
+
** For OCI delivery, a successful installation displays:
+
-----
=> Successfully installed dynamic plugin oci:registry.redhat.io/ansible-automation-platform/ansible-plugin-backstage-rhaap-dynamic:x.y.z
-----

** For HTTP plug-in registry, a successful installation displays:
+
-----
=> Successfully installed dynamic plugin http://plugin-registry:8080/ansible-plugin-backstage-rhaap-dynamic-x.y.z.tgz
-----

