[id="create-aap-job_{context}"]
:_mod-docs-content-type: PROCEDURE

= Running your playbook in {PlatformNameShort}

[role="_abstract"]
To run your playbook in {PlatformNameShort}, you must create a project in {ControllerName} for the repository where you stored your playbook project.
You can then create a job template for each playbook from the project.

.Procedure

. In a browser, log in to {controllername}.
. Configure a Source Control credential type for your source control system if necessary. See the
link:{URLControllerUserGuide}/controller-credentials#controller-create-credential[Creating new credentials]
section of _{TitleControllerUserGuide}_ for more details.
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_execution/controller-credentials#controller-create-credential
. In {controllername}, create a project for the GitHub repository where you stored your playbook project. Refer to the
link:{URLControllerUserGuide}/controller-projects[Projects]
chapter of _{TitleControllerUserGuide}_.
. Create a job template that uses a playbook from the project that you created. Refer to the
link:{URLControllerUserGuide}/controller-job-templates[Job Templates]
chapter of _{TitleControllerUserGuide}_.
. Run your playbook from {ControllerName} by launching the job template. Refer to the
link:{URLControllerUserGuide}/controller-job-templates#controller-launch-job-template[Launching a job template]
section of _{TitleControllerUserGuide}_.

