:_mod-docs-content-type: PROCEDURE

[id="rhdh-uninstall-ocp-helm_{context}"]
= Uninstalling a Helm chart installation

[role="_abstract"]
To uninstall the Ansible plug-ins from a Helm chart installation, you remove templates using the ansible:content:create action first. Then, you delete the plug-in configuration from the Helm chart YAML, remove the extraContainers section, and delete the Ansible block from the custom ConfigMap. Finally, you restart the deployment.

.Procedure

. In {RHDH}, remove any software templates that use the `ansible:content:create` action.


. In the OpenShift Developer UI, navigate to menu:Helm[developer-hub > Actions > Upgrade > Yaml view].


. Remove the Ansible plug-ins configuration under the `plugins` section.
+
----
global:
  dynamic:
    plugins:
      - disabled: false
        package: 'oci://registry.redhat.io/ansible-automation-platform/automation-portal:2.1!ansible-plugin-backstage-rhaap'
        pluginConfig:
          ...
      - disabled: false
        package: 'oci://registry.redhat.io/ansible-automation-platform/automation-portal:2.1!ansible-plugin-scaffolder-backend-module-backstage-rhaap'
        pluginConfig:
          ...
----
+
For HTTP plug-in registry, remove the `http://plugin-registry:8080/\...` entries instead.


. Remove the `extraContainers` section.
+
----
upstream:
  backstage:
    ...
    extraContainers:
      - command:
          - adt
          - server
        image: >-
          registry.redhat.io/ansible-automation-platform-26/ansible-dev-tools-rhel9:latest
        imagePullPolicy: IfNotPresent
        name: ansible-devtools-server
        ports:
          - containerPort: 8000
----


. Click btn:[Upgrade].


. Edit your custom {RHDH} config map, for example `app-config-rhdh`.


. Remove the `ansible` section.


. Restart the {RHDH} deployment.


. If you used OCI delivery, delete the registry auth secret:
+
[literal,subs="+quotes"]
----
oc delete secret <deployment-name>-dynamic-plugins-registry-auth
----


. If you used the HTTP plug-in registry method, remove the plug-in registry application:
+
[literal,subs="+quotes"]
----
oc delete all -l app=plugin-registry
----