:_mod-docs-content-type: PROCEDURE

[id="self-service-add-deployment-url-oauth-app_{context}"]
= Adding the deployment URL to the OAuth Application

When you set up your OAuth application in {PlatformNameShort} before deploying {SelfServiceShort},
you added placeholder text for the `Redirect URL` value.

You must update this value using the URL from the deployed application so that you can run automation on {SelfServiceShort} from {SelfServiceShort}.


. Determine the `Redirect URL` from your OpenShift deployment:
.. Open the URL for the deployment from the OpenShift console to display the sign-in page for {SelfServiceShort}.
.. Copy the URL.
.. To determine the `Redirect URL` value, append `/api/auth/rhaap/handler/frame` to the end of the deployment URL.
+
For example, if the URL for the deployment is `\https://my-aap-self-service-technical-preview-backstage-myproject.mycluster.com`, 
then the `Redirect URL` value is `\https://my-aap-self-service-technical-preview-backstage-myproject.mycluster.com/api/auth/rhaap/handler/frame`.
. Update the `Redirect URL` in the OAuth application in {PlatformNameShort}:
.. In a browser, open your instance of {PlatformNameShort}.
.. Navigate to {MenuAMAdminOauthApps}.
.. In the list view, click the OAuth application you created.
.. Replace the placeholder text in the `Redirect URL` field with the value you determined from your OpenShift deployment.
.. Click `Save` to apply the changes.

