[id="devtools-install-podman-desktop-wsl_{context}"]
:_mod-docs-content-type: PROCEDURE

= Requirements for {ToolsName} on Windows

[role="_abstract"]
If you are installing {ToolsName} on a container in {VSCode} on Windows, there are extra requirements:

* Windows Subsystem for Linux(WSL2)
* Podman Desktop

.Procedure

. Install WSL2 without a distribution:
+
----
$ wsl --install --no-distribution
----
. Use `cgroupsv2` by disabling `cgroupsv1` for WSL2:
+
Edit the `%USERPROFILE%/wsl.conf` file and add the following lines to force `cgroupv2` usage:
+
----
[wsl2]
kernelCommandLine = cgroup_no_v1="all"
----
. Install Podman Desktop. Follow the instructions in
link:https://podman-desktop.io/docs/installation/windows-install[Installing Podman Desktop and Podman on Windows]
in the Podman Desktop documentation.
+
You do not need to change the default settings in the set-up wizard.
. Ensure the podman machine is using `cgroupsv2`:
+
----
$ podman info | findstr cgroup
----
. Test Podman Desktop:
+
----
$ podman run hello
----
. Configure the settings for Podman Desktop.
Add a `%USERPROFILE%\bin\docker.bat` file with the following content:
+
----
@echo off
podman %*
----
+
This avoids having to install Docker as required by the {VSCode} `Dev Container` extension.
. Add the `%USERPROFILE%\bin` directory to the `PATH`:
.. Select *Settings* and search for "Edit environment variables for your account" to display all of the user environment variables.
.. Highlight "Path" in the top user variables box, click btn:[Edit] and add the path.
.. Click btn:[Save] to set the path for any new console that you open.


