:_mod-docs-content-type: PROCEDURE

[id="rhdh-firewall-example-discover_{context}"]
= Discover existing Ansible content for RHEL system roles

[role="_abstract"]
Red Hat recommends that you use trusted automation content that has been tested and approved by Red Hat or your organization. 

{HubNameStart} is a central repository for discovering, downloading, and managing trusted content collections from Red Hat and its partners.
{PrivateHubNameStart} provides an on-premise solution for managing content collections.

.Procedure

. Click on the Ansible `A` icon in the {RHDH} navigation panel.
. Click *Discover existing collections*.
. Click *Go to Automation Hub*. 
+
--
** If {PrivateHubName} has been configured in the Ansible plug-ins, you are redirected to your *PrivateHubName* instance.
** If {PrivateHubName} has not been configured in the Ansible plug-ins installation configuration,
you will be redirected to the Red Hat Hybrid Console (RHCC) automation hub.
--
In this example, you are redirected to the RHCC automation hub.
. If you are prompted to log in, provide your Red Hat Customer Portal credentials.
. Filter the collections with the `rhel firewall` keywords.
+
The search returns the `rhel_system_roles` collection.
+
The RHEL System Roles collection contains certified Ansible content that you can reuse to configure your firewall.

