:_newdoc-version: 2.18.3
:_template-generated: 2025-05-05
:_mod-docs-content-type: PROCEDURE

[id="self-service-share-credentials-aap_{context}"]
= Sharing credential access with uses and teams in {PlatformNameShort}

You can grant users access to credentials based on their team membership.
When you add a user as a member of a team,
they inherit access to the credentials assigned to that team.

. In a browser, navigate to your {PlatformNameShort} instance.
. Navigate to {MenuAECredentials}.
. On the *Credentials* page, click btn:[Create credential].
. Open the credential you created for Gitlab or GitHub.
. Select users or teams from the same organization:
** Select the *Team Access* tab if you want to provide access to the credential for a team.
** Select the *User Access* tab if you want to provide access to the credential for a user.
. Click btn:[Add roles].
. Click the checkbox beside the team or user you want to share the credentials with, and click btn:[Next].
. Select the roles you want applied to the team or user and click btn:[Next].
. Review the settings and click btn:[Finish].
+
The *Add roles* dialog indicates whether the role assignments were successfully applied.
. You can remove access to a role for a team by selecting the *Remove role* icon next to the team.
This launches a confirmation dialog, asking you to confirm the removal.

