:_mod-docs-content-type: PROCEDURE

[id="rhdh-add-pull-secret-helm_{context}"]
= Add a pull secret to the {RHDH} Helm configuration

[role="_abstract"]
You must add a pull secret to the {RHDH} Helm configuration to enable the dynamic plug-ins to pull container images from authenticated registries.

.Prerequisite

* You have a Red Hat Customer Portal account and Red Hat Service Registry account.

.Procedure

. Create a new link:https://access.redhat.com/terms-based-registry/[Red Hat Registry Service account], if required.
. Click the token name under the *Account name* column.
. Select the *OpenShift Secret* tab and follow the instructions to add the pull secret to your {RHDH} OpenShift project.
. Add the new secret to the {RHDH} Helm configuration, replacing `<your-redhat-registry-pull-secret>` with the name of the secret you generated on the Red Hat Registry Service Account website:
+
----
upstream:
  backstage:
    ...
    image:
      ...
      pullSecrets:
        - <your-redhat-registry-pull-secret>
    ...

----

[role="_additional-resources"]
.Additional resources
* link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry documentation]

