:_mod-docs-content-type: PROCEDURE

[id="self-service-create-scm-secrets_{context}"]
= Creating GitHub and Gitlab secrets

[role="_abstract"]
Create an OpenShift secret to hold Personal Access Tokens for your external Source Control Management systems, such as GitHub or GitLab. This helps securely manage access credentials.

This procedure establishes the required `secrets-scm` Key/Value secret within your {OCPShort} project to securely store the GitHub and/or GitLab Personal Access Tokens (PATs).

.Prerequisites

* You have logged in to your {OCPShort} cluster.
* You have access to the OpenShift project where you will install {SelfServiceShort}.

.Procedure

Create the `secrets-scm` secret using the `oc` CLI or the OpenShift web console. If you use only one SCM provider, include only that provider's token.

[NOTE]
====
The secret must use the exact name `secrets-scm` with the exact key names specified below.
====

*CLI*

* To create the secret with both GitHub and GitLab tokens:
+
----
$ oc create secret generic secrets-scm \
  --from-literal=github-token="<github_pat>" \
  --from-literal=gitlab-token="<gitlab_pat>" \
  -n <project_name>
----

* To create the secret with only a GitHub token:
+
----
$ oc create secret generic secrets-scm \
  --from-literal=github-token="<github_pat>" \
  -n <project_name>
----

* To create the secret with only a GitLab token:
+
----
$ oc create secret generic secrets-scm \
  --from-literal=gitlab-token="<gitlab_pat>" \
  -n <project_name>
----

*OpenShift web console*

. In the *Administrator* view, click *Workloads* -> *Secrets*.
. Click *Create* -> *Key/value secret*.
. Set the secret name to `secrets-scm`.
. Add key-value pairs for your SCM providers:
+
** Key: `github-token`, Value: GitHub Personal Access Token (PAT)
** Key: `gitlab-token`, Value: GitLab Personal Access Token (PAT)
. Click *Create*.

