:_mod-docs-content-type: PROCEDURE

[id="rhdh-set-up-controller-project_{context}"]
= Connect your project to {PlatformNameShort}

[role="_abstract"]
Access {PlatformNameShort}through the {RHDH} to create a project in {ControllerNameShort} for your playbook repository and then set up a job template that uses the playbook. You can navigate directly to your {ControllerNameShort} instance if it was not configured during the plug-in installation.

.Procedure

. The Ansible plug-ins provide a link to {PlatformNameShort}.
. Log in to your {RHDH} UI.
. Click the Ansible `A` icon in the {RHDH} navigation panel.
. Click *Operate* to display a link to your {PlatformNameShort} instance.
+
If {ControllerName} was not included in your plug-in installation, a link to the product feature page is displayed.
. Click *Go to {PlatformNameShort}* to open your platform instance in a new browser tab.
+
Alternatively, if your platform instance was not configured during the Ansible plug-in installation, navigate to your {ControllerName} instance in a browser and log in.
. Log in to {ControllerName}.
. Create a project in {PlatformNameShort} for the GitHub repository where you stored your playbook project.
Refer to the
link:{URLControllerUserGuide}/controller-projects[Projects]
chapter of _TitleControllerUserGuide_.
. Create a job template that uses a playbook from the project that you created.
Refer to the
link:{URLControllerUserGuide}/controller-workflow-job-templates[Workflow job templates]
chapter of _TitleControllerUserGuide_.

