:_mod-docs-content-type: PROCEDURE

[id="self-service-install-disconnected-access-ocp_{context}"]
= Access the disconnected OpenShift environment

[role="_abstract"]
Ensure your disconnected OpenShift cluster is configured to trust the private registry containing the mirrored container images. This step is crucial for successful image pulling during installation.

.Prerequisites

* You have the necessary kubeconfig and permissions. For example `cluster-admin`, for setting up image pull secrets or insecure registries.

.Procedure
. In a terminal, log in to your disconnected OpenShift cluster using the `oc` CLI.
+
----
oc login --token=<your_token> --server=<your_openshift_api_url>
----
+
Use the following command if you have a kubeconfig:
+
----
export KUBECONFIG=/path/to/your/kubeconfig
oc login
----
. Ensure that your OpenShift cluster is configured to trust your disconnected registry:
.. Use `ImageContentSourcePolicy` for mirroring.
.. Use `additionalTrustedCA` in `image.config.openshift.io/cluster` for self-signed certificates.
.. Use  `insecure-registries` for plain HTTP.

