:_mod-docs-content-type: PROCEDURE

[id="self-service-install-disconnected-define-parameters_{context}"]
= Configure plug-in delivery for disconnected environments

[role="_abstract"]
Complete one of the plug-in delivery methods from the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_self-service_automation_portal/index#self-service-create-ocp-registry_self-service-preinstall-config[Choose a plug-in delivery method] section:


.Procedure

* For OCI delivery: Create the `<release-name>-dynamic-plugins-registry-auth` secret with credentials for your disconnected registry that hosts the mirrored Ansible plug-ins OCI artifacts.
* For HTTP plug-in registry: Deploy the plug-in registry in your disconnected OpenShift project following the _HTTP plug-in registry_ procedure outlined in the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_self-service_automation_portal/index#self-service-create-ocp-registry_self-service-preinstall-config[Choose a plug-in delivery method] section.

