:_mod-docs-content-type: PROCEDURE

[id="self-service-install-disconnected-installing-chart_{context}"]
= Install the Helm chart

[role="_abstract"]
Install {SelfServiceShort} by using the `helm install` command. You must reference the local Helm chart file and include the required configuration using a values file (`-f`) or `--set` flags.

.Procedure

. On the machine within your disconnected environment, navigate to the directory where you placed the transferred Helm chart `.tgz` file:
+
----
$ cd /path/to/your/transferred/charts/
----
. Define your namespace and cluster router base as environment variables:
+
----
$ export MY_NAMESPACE="<your_namespace_name>"
$ export MY_CLUSTER_ROUTER_BASE="<your_cluster_router_base>"
----
. If the namespace does not exist, create it:
+
----
$ oc new-project "${MY_NAMESPACE}"
----
. Create a custom values file and reuse it for install and upgrade. Choose the example that matches your plug-in delivery method.
+
*OCI delivery* (`values-oci.yaml`):
+
----
redhat-developer-hub:
  global:
    clusterRouterBase: <your_cluster_router_base>
    pluginMode: oci
    imageTagInfo: "<plugin-version>"
    # Replaces registry.redhat.io for the images.
    imageRegistry: <disconnected_registry_url>/<your_namespace>
  upstream:
    # To override the PostgreSQL image tag, uncomment the following lines:
    # postgresql:
    #   image:
    #     repository: rhel9/postgresql-15
    #     tag: <tag>
    backstage:
      appConfig:
        ansible:
          rhaap:
            # checkSSL: false  # Uncomment and set to false if using self-signed certificates.
        catalog:
          providers:
            rhaap:
              '{{- include "catalog.providers.env" . }}':
                orgs: <your-aap-organization-name>
----
+
*HTTP plug-in registry delivery* (`values-tarball.yaml`):
+
----
redhat-developer-hub:
  global:
    clusterRouterBase: <your_cluster_router_base>
    pluginMode: tarball
    # Replaces registry.redhat.io for the images
    imageRegistry: <disconnected_registry_url>/<your_namespace>
  upstream:
    # To override the PostgreSQL image tag, uncomment the following lines:
    # postgresql:
    #   image:
    #     repository: rhel9/postgresql-15
    #     tag: <tag>
    backstage:
      appConfig:
        ansible:
          rhaap:
            # checkSSL: false  # Uncomment and set to false if using self-signed certificates.
        catalog:
          providers:
            rhaap:
              '{{- include "catalog.providers.env" . }}':
                orgs: <your-aap-organization-name>
----
. Install the chart using the `helm install` command:
+
----
$ helm install redhat-rhaap-portal \
  redhat-rhaap-portal-x.y.z.tgz \
  --namespace "${MY_NAMESPACE}" \
  -f /path/to/values-oci.yaml
----
+
To apply changes after deployment, upgrade the Helm release. If you install from the OpenShift web console, use Developer -> Helm -> select the release -> Actions -> Upgrade -> YAML view.
+
To upgrade from the command line:
+
----
$ helm upgrade redhat-rhaap-portal \
  redhat-rhaap-portal-x.y.z.tgz \
  --namespace "${MY_NAMESPACE}" \
  -f /path/to/values-oci.yaml
----
+
Alternatively, you can pass values using `--set` flags.
+
*OCI delivery:*
+
----
$ helm install redhat-rhaap-portal \
  redhat-rhaap-portal-x.y.z.tgz \
  --namespace "${MY_NAMESPACE}" \
  --set redhat-developer-hub.global.clusterRouterBase="${MY_CLUSTER_ROUTER_BASE}" \
  --set redhat-developer-hub.global.imageRegistry=<disconnected_registry_url>/<your_namespace> \
  --set redhat-developer-hub.global.pluginMode=oci
----
+
*HTTP plug-in registry delivery:*
+
----
$ helm install redhat-rhaap-portal \
  redhat-rhaap-portal-x.y.z.tgz \
  --namespace "${MY_NAMESPACE}" \
  --set redhat-developer-hub.global.clusterRouterBase="${MY_CLUSTER_ROUTER_BASE}" \
  --set redhat-developer-hub.global.imageRegistry=<disconnected_registry_url>/<your_namespace> \
  --set redhat-developer-hub.global.pluginMode=tarball
----




