:_mod-docs-content-type: PROCEDURE

[id="rhdh-install-dynamic-plugins-operator_{context}"]
= Installing the dynamic plug-ins

[role="_abstract"]
To install the dynamic plugins, add them to your ConfigMap for your {RHDHShort} plugin settings (for example, `rhaap-dynamic-plugins-config`).

If you have not already created a ConfigMap file for your {RHDHShort} plugin settings,
create one by following the procedure in the
link:{BaseURL}/openshift_container_platform/{OCPLatest}/html-single/nodes/index#configmaps[Creating and using config maps] section of the {OCPShort} _Nodes_ guide.

.Procedure

. Select *ConfigMaps* in the navigation pane of the OpenShift console.
. Select the `rhaap-dynamic-plugins-config` ConfigMap from the list.
. Select the *YAML* tab to edit the `rhaap-dynamic-plugins-config` ConfigMap.
. Add the Ansible plug-ins. Choose the configuration that matches your delivery method.
+
** OCI container delivery method (recommended):
+
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: rhaap-dynamic-plugins-config
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - disabled: false
        package: 'oci://registry.redhat.io/ansible-automation-platform/automation-portal:2.1!ansible-plugin-backstage-rhaap'
        pluginConfig:
          dynamicPlugins:
            frontend:
              ansible.plugin-backstage-rhaap:
                appIcons:
                  - importName: AnsibleLogo
                    name: AnsibleLogo
                dynamicRoutes:
                  - importName: AnsiblePage
                    menuItem:
                      icon: AnsibleLogo
                      text: Ansible
                    path: /ansible
      - disabled: false
        package: 'oci://registry.redhat.io/ansible-automation-platform/automation-portal:2.1!ansible-plugin-scaffolder-backend-module-backstage-rhaap'
        pluginConfig:
          dynamicPlugins:
            backend:
              ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
----
+
Replace `x.y.z` with the Ansible plug-ins version.


** HTTP plug-in registry method:
+
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: rhaap-dynamic-plugins-config
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - disabled: false
        package: 'http://plugin-registry:8080/ansible-plugin-backstage-rhaap-dynamic-x.y.z.tgz'
        integrity: <SHA512 value>
        pluginConfig:
          dynamicPlugins:
            frontend:
              ansible.plugin-backstage-rhaap:
                appIcons:
                  - importName: AnsibleLogo
                    name: AnsibleLogo
                dynamicRoutes:
                  - importName: AnsiblePage
                    menuItem:
                      icon: AnsibleLogo
                      text: Ansible
                    path: /ansible
      - disabled: false
        package: >-
          http://plugin-registry:8080/ansible-plugin-scaffolder-backend-module-backstage-rhaap-dynamic-x.y.z.tgz
        integrity: <SHA512 value>
        pluginConfig:
          dynamicPlugins:
            backend:
              ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
----

. Click btn:[Save].



.Verification

. In the OpenShift console, select the *Topology* view.
. Click the *Open URL* icon on the deployment pod to open your {RHDH} instance in a browser window.

The Ansible plug-in is present in the navigation pane. If you select *Administration*, you can see the installed plug-ins in the *Plugins* tab.