:_mod-docs-content-type: PROCEDURE

[id="devspaces-create-repo_{context}"]
= Create a Git repository for an {AnsibleWorkspaceSing}

[role="_abstract"]
To launch an {AnsibleWorkspaceSing}, you must provide a link to a Git repository that defines the development environment.
The repository also stores the automation content you create in {AnsibleDevSpaces}.


.Procedure

. If your administrator provides an example repository for your team, fork the repository to create your own copy.
. If you do not have access to an example repository, you must create your own repository.
.. Create a directory for your new repository and use `git init` to initialize it as a Git repository.
.. Add a `devfile.yaml` file to the repository to define the {AnsibleDevSpaces} image that you want to use for your {AnsibleWorkspaceSing}.
See Creating a devfile for {AnsibleWorkspaces}.
.. Add a `.code-workspace` file to the repository to specify the {VSCode} extensions for your {AnsibleWorkspaceSing}.
See Creating a `.code-workspace` file for {AnsibleWorkspaces}.



