[id="test-playbook_{context}"]
:_mod-docs-content-type: PROCEDURE

= Testing your playbooks

[role="_abstract"]

To test your playbooks in your project, run them in a non-production environment such as a lab setup or a virtual machine. 

{NavigatorStart} (`ansible-navigator`) is a text-based user interface (TUI) for developing and troubleshooting Ansible content with execution environments.

Running a playbook using `ansible-navigator` generates verbose output that you can inspect to check whether the playbook is running the way you expected. 
You can specify the execution environment that you want to run your playbooks on, so that your tests replicate the production setup on {PlatformNameShort}:

.Procedure

* To run a playbook on an execution environment, run the following command from the terminal in {VsCode}:
+
----
$ ansible-navigator run <playbook_name.yml> -eei <execution_environment_name>
----
For example, to execute a playbook called `site.yml` on the {PlatformNameShort} RHEL 9 minimum execution environment, run the following command from the terminal in VS Code.
+
----
ansible-navigator run site.yml --eei ee-minimal-rhel8
----

.Verification
The output is displayed in the terminal.
You can inspect the results and step into each play and task that was executed.

[role="_additional-resources"]
.Additional resources

* link:{URLNavigatorGuide}/assembly-execute-playbooks-navigator_ansible-navigator[Running Ansible playbooks with automation content navigator]

