:_mod-docs-content-type: PROCEDURE

[id="rhdh-download-plugins_{context}"]
= Downloading the Ansible plug-ins files

[role="_abstract"]
Download the {AAPRHDH} *Setup Bundle* from the {PlatformName} Product Software downloads page.

.Procedure

. In a browser, navigate to the link:{PlatformDownloadUrl}[Red Hat Ansible Automation Platform Product Software downloads page] and select the *Product Software* tab.
. Click *Download now* next to *Ansible plug-ins for Red Hat Developer Hub Setup Bundle* to download the latest version of the plug-ins.
+
The format of the filename is `ansible-rhdh-plugins-x.y.z.tar.gz`. 
Substitute the Ansible plug-ins release version, for example `2.0.0`, for `x.y.z`.
. Create a directory on your local machine to store the `.tar` files.
+
----
$ mkdir /path/to/<ansible-backstage-plugins-local-dir-changeme>
----
. Set an environment variable (`$DYNAMIC_PLUGIN_ROOT_DIR`) to represent the directory path.
+
----
$ export DYNAMIC_PLUGIN_ROOT_DIR=/path/to/<ansible-backstage-plugins-local-dir-changeme>
----
. Extract the `ansible-rhdh-plugins-<version-number>.tar.gz` contents to `$DYNAMIC_PLUGIN_ROOT_DIR`.
+
----
$ tar --exclude='*code*' -xzf ansible-rhdh-plugins-x.y.z.tar.gz -C $DYNAMIC_PLUGIN_ROOT_DIR
----
+
Substitute the Ansible plug-ins release version, for example `2.0.0`, for `x.y.z`.

.Verification

Run `ls` to verify that the extracted files are in the `$DYNAMIC_PLUGIN_ROOT_DIR` directory:

----
$ ls $DYNAMIC_PLUGIN_ROOT_DIR
ansible-plugin-backstage-rhaap-dynamic-x.y.z.tgz
ansible-plugin-backstage-rhaap-dynamic-x.y.z.tgz.integrity
ansible-plugin-scaffolder-backend-module-backstage-rhaap-dynamic-x.y.z.tgz
ansible-plugin-scaffolder-backend-module-backstage-rhaap-dynamic-x.y.z.tgz.integrity

----

The files with the `.integrity` file type contain the plugin SHA value.
The SHA value is used during the plug-in configuration.

