:_mod-docs-content-type: PROCEDURE

[id="self-service-install-helm-from-catalog_{context}"]
= Install the Helm chart

[role="_abstract"]
Deploy the {SelfServiceShort} Helm chart from the OpenShift catalog by configuring the base URL and organization name in the YAML view. This launches the self-service automation portal installation.

.Prerequisites
* You have created a project for {SelfServiceShort} in {OCPShort}.
* You have created a plugin registry in your project.
* You have set up secrets for {PlatformNameShort} authentication and SCM authentication.

.Procedure
. In a browser, navigate to your OpenShift project for {SelfServiceShort} that you created earlier.
. Select the *Developer* view.
. Click the *Helm* option in the OpenShift sidebar.  
. In the *Helm* page, click btn:[Create] and select *Helm Release*. 
. Search for `Portal` in the Helm Charts filter,
and select the `Automation Portal` chart. 
. In the modal dialog on the chart page, click btn:[Create].
. Select the *YAML view* in the *Create Helm Release* page.
. Locate the `clusterRouterBase` key in the YAML file and replace the placeholder value with the base URL of your OpenShift instance.
+
The base URL is the URL portion of your OpenShift URL that follows `\https://console-openshift-console`,
for example `apps.example.com`:
+
----
  redhat-developer-hub
    global:
      clusterRouterBase: apps.example.com
----
. The Helm chart is set up for the Default {PlatformNameShort} organization.
+
To update the Helm chart to use a different organization,
update the value for the `catalog.providers.rhaap.orgs` key from `Default` to your {PlatformNameShort} organization name. 
+
----
  catalog:
    providers:
      rhaap:
        production:
        # Replace 'Default' with the name of the organization you created
          orgs: '<your-org-name>'
----
. Click btn:[Create] to launch the deployment.

