:_mod-docs-content-type: REFERENCE

[id="devtools-workflow_{context}"]

= Workflow

[role="_abstract"]
The workflow for developing automation content involves three key stages: Create, Test, and Deploy.

== Create

In the create  stage, you create a new playbook project locally, using {VSCode}. The following is a typical workflow:

. Install and run the Ansible extension in {VSCode}.
. Scaffold a playbook project from {VSCode}.
. Add playbook files to your project and edit them in {VSCode}.

== Test

. Debug your playbook with the help of `ansible-lint`.
. Select or create an {ExecEnvNameSing} so that your local environment replicates the environment on {PlatformNameShort}.
. Run your playbooks from {VSCode}, using `ansible-playbook` or using `ansible-navigator` with an {ExecEnvShort}.
. Test your playbooks by running them on an {ExecEnvShort} that replicates your production environment.

== Deploy

. Push your playbooks project to a source control repository.
. Set up credentials on {PlatformNameShort} to pull from your source control repository and create a project for your playbook repository.
. If you have created an {ExecEnvShort}, push it to {PrivateHubName}.
. Create a job template on {PlatformNameShort} that runs a playbook from your project, and specify the {ExecEnvShort} that you want to use.

