:_mod-docs-content-type: ASSEMBLY

[id="assembly-managed-node-configuration"]

= Managed Node Configuration

[role="_abstract"]
{PlatformNameShort} is an agentless technology that relies on making a remote connection to the devices it manages, called managed nodes, to run automation tasks. 

This chapter provides recommendations on improving the security posture of the managed nodes automated by {PlatformNameShort}, including the remote connections between {PlatformNameShort} and the managed nodes.  

Note that managed node configuration can vary significantly based on factors such as operating system, compliance profiles, configuration, and organizational policies. 

Any recommendations on managed node configuration presented here must be thoroughly tested and reviewed before implementation to ensure that they meet organizational policies and requirements.

include::aap-hardening/con-rhel-node-configuration.adoc[leveloffset=+1]

include::aap-hardening/con-create-dedicated-service-account.adoc[leveloffset=+2]

include::aap-hardening/proc-configure-sudo-for-service-account.adoc[leveloffset=+3]

include::aap-hardening/proc-ssh-auth-for-service-account.adoc[leveloffset=+3]

include::aap-hardening/proc-pam-access-for-service-accounts.adoc[leveloffset=+3]

include::aap-hardening/con-more_compliance-profile-considerations.adoc[leveloffset=+2]

include::aap-hardening/ref-fapolicyd-on-rhel.adoc[leveloffset=+3]

include::aap-hardening/proc-fapolicyd-permissive-mode.adoc[leveloffset=+3]

include::aap-hardening/proc-create-fapolicyd-rules.adoc[leveloffset=+3]