:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="assembly-intro-to-aap-hardening"]

:context: introduction

= Introduction to hardening {PlatformNameShort}

[role="_abstract"]

This guidance improves the security posture (referred to as “hardening”) of your {PlatformName} deployment on {RHEL}.

This does not currently cover the following areas:

* Other deployment targets for {PlatformNameShort}, such as OpenShift.
* {PlatformNameShort} managed services available through cloud service provider marketplaces.

Hardening your {PlatformNameShort} security posture, by starting with the planning and architecture phase of deployment, then covering installation, initial configuration, and Day 2 operations. 
While the information supplied specifically covers {PlatformNameShort} running on {RHEL}, hardening guidance for {RHEL} is covered where it affects the automation platform components. 
Additional considerations with regards to the DISA STIGs for {RHEL} are provided for those organizations that integrate the DISA STIGs as a part of their overall security strategy.

[NOTE]
====
These recommendations do not guarantee security or compliance of your deployment of {PlatformNameShort}. 
You must assess security from the unique requirements of your organization to address specific threats and risks and balance these against implementation factors.
====

include::aap-hardening/con-hardening-guide-audience.adoc[leveloffset=+1]

include::aap-hardening/con-product-overview.adoc[leveloffset=+1]

include::aap-hardening/con-deployment-methods.adoc[leveloffset=+2]

include::aap-hardening/con-platform-components.adoc[leveloffset=+2]