:_mod-docs-content-type: ASSEMBLY
[id="assembly-creating-tokens-in-automation-hub"]
= Configuring remote repositories for content syncing

:context: cloud-sync

[role="_abstract"]
Use remote configurations to configure your {PrivateHubName} to synchronize with {CertifiedName} hosted on `{Console}` or with your collections in {Galaxy}.

Each remote configuration in {MenuACAdminRemotes} provides information for both the *community* and *rh-certified* repository about when the repository was *last updated*.
You can add new content to {HubNameMain} at any time by using the *Edit* and *Sync* features included on the {MenuACAdminRepositories} page.

*Understanding the difference between {Galaxy} and {HubNameMain} collections*

Collections published to {Galaxy} are the latest content published by the Ansible community and have no joint support claims associated with them. 
{Galaxy} is the recommended front end directory for the Ansible community to access content.

Collections published to {HubNameMain} are targeted to joint customers of Red Hat and selected partners. 
Customers need an Ansible subscription to access and download collections on {HubNameMain}. 
A certified collection means that Red Hat and partners have a strategic relationship in place and are ready to support joint customers. Collections may also have had additional testing and validation done against them.

*Requesting a namespace on {Galaxy}*

To request a namespace through an {Galaxy} GitHub issue, send an email request to ansiblepartners@redhat.com that includes the GitHub username used to sign up on {Galaxy}.

You must have logged in at least once for the system to validate.

After users are added as administrators of the namespace, you can use the self-serve process to add more administrators.

*{Galaxy} namespace naming guidelines*

Collection namespaces must follow Python module name convention. 
This means collections should have short, all lowercase names. 
You can use underscores in the collection name if it improves readability.

// [hherbly: there's only a couple of sentences in this concept module, and they make more sense at the beginning of this assembly. Moving this content to line 15] include::hub/con-remote-repos.adoc[leveloffset=+1]

// [hherbly: replacing this with the 4 modules below from the Getting started with hub guide include::hub/proc-obtaining-org-collection-url.adoc[leveloffset=+1]

include::hub/con-token-management-hub.adoc[leveloffset=+1]

include::hub/proc-create-api-token.adoc[leveloffset=+1]

include::hub/proc-create-api-token-pah.adoc[leveloffset=+1]

include::hub/proc-offline-token-active.adoc[leveloffset=+1]

include::hub/proc-set-rhcertified-remote.adoc[leveloffset=+1]

include::hub/proc-set-community-remote.adoc[leveloffset=+1]

include::hub/proc-configure-proxy-remote.adoc[leveloffset=+1]

include::hub/proc-create-requirements-file.adoc[leveloffset=+1]