:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="populate-container-registry"]
= Populating your {PrivateHubName} container registry

:context: populate-container-registry

[role="_abstract"]
You must follow a specific workflow to populate your {PrivateHubName} remote registry:

* Pull {ExecEnvName} from the Red Hat Ecosystem Catalog (`registry.redhat.io`)
* Tag them
* Push them to your {PrivateHubName} remote registry

[IMPORTANT]
====
As of *April 1st, 2025*, `quay.io` is adding three additional endpoints. As a result, you must adjust the allow/block lists within your firewall systems lists to include the following endpoints:

* `cdn04.quay.io`
* `cdn05.quay.io`
* `cdn06.quay.io`

To avoid problems pulling container images, customers must allow outbound TCP connections (ports 80 and 443) to the following hostnames:

* `cdn.quay.io`
* `cdn01.quay.io`
* `cdn02.quay.io`
* `cdn03.quay.io`
* `cdn04.quay.io`
* `cdn05.quay.io`
* `cdn06.quay.io`

This change should be made to any firewall configuration that specifically enables outbound connections to `registry.redhat.io` or `registry.access.redhat.com`.

Use the hostnames instead of IP addresses when configuring firewall rules.

After making this change, you can continue to pull images from `registry.redhat.io` or `registry.access.redhat.com`. You do not require a `quay.io` login, or need to interact with the `quay.io` registry directly in any way to continue pulling Red Hat container images.

For more information, see link:https://access.redhat.com/articles/7084334[Firewall changes for container image pulls 2024/2025].

Ensure that the link:{URLPlanningGuide}/ref-network-ports-protocols_planning[Network ports and protocols] listed in _Table 6.4. Execution Environments (EE)_ are available to avoid problems pulling container images.

====

include::hub/proc-obtain-images.adoc[leveloffset=+1]

include::hub/proc-tag-pulled-image.adoc[leveloffset=+1]

include::hub/proc-push-container.adoc[leveloffset=+1]



ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
