ifdef::context[:parent-context: {context}]

:_content-type: ASSEMBLY

[id="ppah-installation_{context}"]

= Private Partner Ansible Automation Hub Installation Guide

:context: ppah-installation

Red Hat Ansible private partner automation hub enables Red Hat partners to curate, host, and serve their own Ansible content to their consultants, customers, or users. Private partner automation hub gives partners the ability to serve content to multiple different parties simultaneously using comprehensive role-based access controls. This offering is designed to help partners expedite their solutions using Ansible's proven automation technology.

This guide contains a collection of Ansible playbooks that install a containerized private partner automation hub. You can choose from two types of installation based on your organization's needs:

* a xref:ppah-install-dev[development option]
* a xref:ppah-install-ha[production option]


include::hub/proc_ppah-download-aap.adoc[leveloffset=+1]
include::hub/proc_ppah-prepare-rhel-host.adoc[leveloffset=+1]
include::hub/proc-ppah-install-ansible-core.adoc[leveloffset=+1]
include::hub/proc_ppah-online-offline-install.adoc[leveloffset=+1]
include::hub/proc_ppah-install-dev.adoc[leveloffset=+1]
include::hub/proc_ppah-install-ha.adoc[leveloffset=+1]
//include::hub/ref_ppah-config.adoc[leveloffset=+1]
include::hub/ref_ppah-access.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]

