ifdef::context[:parent-context: {context}]

[id="managing-cert-valid-content"]
= Red Hat Certified, validated, and Ansible Galaxy content in automation hub

:context: managing-cert-validated-content

[role="_abstract"]
{CertifiedColl} is included in your subscription to {PlatformName}. Red Hat Ansible content inclues two types of content: {CertifiedName} and {Valid}.
Using {HubNameMain}, you can access and curate a unique set of collections from all forms of Ansible content.

Red Hat Ansible content contains two types of content:

* {CertifiedName}
* {Valid} collections

Ansible validated collections are available in your {PrivateHubName} through the Platform Installer.
When you download {PlatformName} with the bundled installer, validated content is pre-populated into the {PrivateHubName} by default, but only if you enable the {PrivateHubName} as part of the inventory.

If you are not using the bundle installer, you can use a Red Hat supplied Ansible playbook to install validated content.
For further information, see xref:assembly-validated-content[{Valid}]

You can update these collections manually by downloading their packages.

[discrete]
== Why certify Ansible collections?

The Ansible certification program enables a shared statement of support for {CertifiedCon} between Red Hat and the ecosystem partner. 
An end customer, experiencing trouble with Ansible and certified partner content, can open a support ticket, for example, a request for information, or a problem with Red Hat, and expect the ticket to be resolved by Red Hat and the ecosystem partner. 

Red Hat offers go-to-market benefits for Certified Partners to grow market awareness, generate demand, and sell collaboratively.

Red Hat {CertifiedName} are distributed through {HubNameMain} (subscription required), a centralized repository for jointly supported Ansible Content. 
As a certified partner, publishing collections to {HubNameMain} provides end customers the power to manage how trusted automation content is used in their production environment with a well-known support life cycle.

For more information about getting started with certifying a solution, see link:https://connect.redhat.com/en/partner-with-us/red-hat-ansible-automation-certification[Red Hat Partner Connect].

[discrete]
== How do I get a collection certified?

For instructions on certifying your collection, see the Ansible certification policy guide on link:http://www.ansible.com/partners[Red Hat Partner Connect].


include::assembly-synclists.adoc[leveloffset=+1]
include::assembly-syncing-to-cloud-repo.adoc[leveloffset=+1]
include::assembly-collections-and-content-signing-in-pah.adoc[leveloffset=+1]
include::assembly-faq.adoc[leveloffset=+1]
include::assembly-validated-content.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
