ifdef::context[:parent-context: {context}]

[id="hub-overview"]
= Overview of {HubName} and {PrivateHubName}

:context: hub-overview

[role="_abstract"]
Two versions of {HubName} are provided with {PlatformName}; {HubName} and {PrivateHubName}. Both versions provide a central location where automation content can be located, downloaded, and integrated into your Ansible automation.

Ansible content can be broken up into three main categories:

* Community content found in {Galaxy}
* Red Hat certified and supported content found in {HubName} on the link:https://console.redhat.com/ansible/automation-hub[Red Hat Hybrid Cloud Console]
* Private content created and curated by an organization and shared locally

The distinction between {HubName} and {PrivateHubName} is that {HubName} allows you to access only Red Hat supported or certified content, and {PrivateHubName}, as a self-hosted content management system, allows you to access and manage of all three types of content, choosing which Ansible content collections and versions are made available to your automation consumers.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
