:_mod-docs-content-type: CONCEPT

[id="gw-pluggable-authentication"]

[role="_abstract"]

= Pluggable authentication

Authentication is the process of verifying a user's identity to the {PlatformNameShort}, that is, to establish that a user is who they say they are. 
This can be done in several ways and is traditionally associated with a `username` and `password`.
Configuring external authentication sources such as LDAP, SAML, and OIDC enables a Single Sign-On (SSO) experience. 
SSO allows users to access {Gateway} by using the same credentials from other enterprise services.

[NOTE]
====
When you log out of {PlatformNameShort}, only your session with the platform ends. 
Your session with the external Single Sign-On (SSO) provider stays active. 
To switch to a different account with the same provider, you must log out of the SSO provider's website directly. 
This ensures that you can successfully sign in with a new account.
====

{PlatformNameShort} {PlatformVers} uses a pluggable authentication system with a configuration wizard that provides a common, simplified method of configuring different types of authenticators such as LDAP and SAML. The pluggable system also allows you to configure multiple authenticators of the same type.  

In the pluggable system we have a couple of concepts:

Authenticator Plugin:: A plugin allows {PlatformNameShort} to connect to a source system, such as, LDAP, or SAML. {PlatformNameShort} includes a variety of authenticator plugins. Authenticator plugins are similar to Ansible collections, in that all of the required code is in a package and can be versioned independently if needed. 

Authenticator:: An authenticator is an instantiation of an authenticator plugin and allows users from the specified source to log in. For example, the LDAP authenticator plugin defines a required LDAP server setting. When you instantiate an authenticator from the LDAP authentication plugin, you must provide the authenticator the LDAP server URL it needs to connect to.

Authenticator Map:: Authenticator maps are applied to authenticators and tell {PlatformNameShort} what permissions to give a user logging into the system.