:_mod-docs-content-type: CONCEPT

[id="controller-api-sso-auth"]

= Single sign-on authentication

[role="_abstract"]
Single sign-on (SSO) authentication methods are different from other methods because the authentication of the user happens external to {ControllerName}, such as Google SSO, {Azure} SSO, SAML, or GitHub. 

You can configure SSO authentication by using {ControllerName} inside a large organization with a central Identity Provider. 
Once you have configured an SSO method in {ControllerName}, an option for that SSO is available on the login screen. 
If you click that option, it redirects you to the Identity Provider, in this case GitHub, where you present your credentials. If the Identity Provider verifies you successfully, {ControllerName} makes a user linked to your GitHub user (if this is your first time logging in with this SSO method), and logs you in.

[role="_additional-resources"]
.Additional resources

* link:{URLCentralAuth}/gw-configure-authentication#gw-config-authentication-type[Configuring an authentication type]
