:_mod-docs-content-type: CONCEPT

[id="con-about-platform-gateway_{context}"]

= {GatewayStart}

[role="_abstract"]
// content taken from snippets/snip-gateway-component-description.adoc and con-gw-activity-stream.adoc 
{GatewayStart} is the service that handles authentication and authorization for the {PlatformNameShort}.
It provides a single entry into the {PlatformNameShort} and serves the platform user interface so you can authenticate and access all of the {PlatformNameShort} services from a single location.

The {Gateway} includes an activity stream that captures changes to gateway resources, such as the creation or modification of organizations, users, and service clusters, among others.
For each change, the activity stream collects information about the time of the change, the user that initiated the change, the action performed, and the actual changes made to the object, when possible.
The information gathered varies depending on the type of change.

You can access the details captured by the activity stream from the API:

[source]
----
/api/gateway/v1/activitystream/
----

For more information about the services available in the {PlatformNameShort}, refer to link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/getting_started_with_ansible_automation_platform/index#assembly-gs-key-functionality[Key functionality and concepts] in _{TitleGettingStarted}_.
