:_mod-docs-content-type: CONCEPT

[id="con-gs-manage-RBAC"]

= Manage user access with role-based access control

[role="_abstract"]
Role-based access control (RBAC) restricts user access based on the user's role within the organization they are assigned to in {PlatformNameShort}. The roles in RBAC refer to the levels of access that users have to {PlatformNameShort} components and resources. 

Use RBAC to control what users can do with the components of {PlatformNameShort} at a broad or granular level. You can choose whether the user is a system administrator or normal user, and align roles and access permissions with their positions within the organization. 

You can define roles with multiple permissions that can then be assigned to resources, teams, and users. 
The permissions that make up a role govern what the assigned role allows. 
Permissions are allocated with only the access needed for a user to perform the tasks appropriate for their role.

The following procedures show how to get started with RBAC by creating a team, and a user to assign to the team. For the complete workflow related to using RBAC to manage access, see the {TitleCentralAuth} guide, particularly the sections on link:{URLCentralAuth}/gw-managing-access[Managing access with role-based access control] and link:{URLCentralAuth}/assembly-gw-roles[Roles].

[IMPORTANT]

====

When managing users, teams, and organizations, use the Unified UI or the {Gateway} API to ensure real-time synchronization across all platform components, including {EDAcontroller}. If you use the legacy {ControllerName} API, changes can take up to 15 minutes to propagate to {EDAcontroller}, which can result in authentication errors for new users or teams.

====
// [this concept module is duplicated from the intro to assembly-gw-managing-access in the auth management guide - hherbly]