:_mod-docs-content-type: CONCEPT

[id="con-soft-deletion_{context}"]

= Soft deletion

[role="_abstract"]
{ControllerNameStart} provides a soft deletion feature that allows you to mark hosts as deleted without permanently removing them from the database. 
This feature is useful for managing hosts that are no longer in use but need to be retained for historical or auditing purposes.

When a host is soft deleted, it is marked as deleted in the database but remains accessible for reporting and auditing.

Additionally, the following host types can also be deleted: 

* Ephemeral, uniquely provisioned hosts, such as those used for CI-CD, or testing only.
* Bench provisioning or temporary hosts.
* Older hosts that have been decommissioned and are never automated against.

Soft deletion is intended for legitimate use case scenarios only. 
It must not be used to violate subscription counting, for example, for the purposes of node recycling. 
For more information, see link:https://access.redhat.com/articles/3331481[How are "managed nodes" defined as part of the {PlatformName} offering]?
