[id="edge-manager-manage-os-config"]

= Manage the operating system configuration

Including operating system-level host configuration in the operating system image provides maximum consistency and repeatability.
//reusability of the image? Or repeatability of what?
To update a configuration, you must create a new operating system image and update devices with the new image.

However, this can be impractical in the following cases:

* The configuration is missing in the image.
* The configuration needs to be specific to a device.
* The configuration needs to be updateable at runtime without updating the operating system image and rebooting.
For these cases, you can declare a set of configuration files that can be present on the file system of the device.

Conceptually, the set of configuration files is an additional, dynamic layer on top of the layers of the operating system image.
The {RedHatEdge} agent applies updates to this layer while the agent ensures that either all files are successfully updated in the file system, or the files are returned to their pre-update state.
If the user updates both an operating system and configuration set of a device at the same time, the {RedHatEdge} agent updates the operating system first.
Then applies the specified configuration set on top the update operating system.

You can also specify a list of configurations sets that the {RedHatEdge} agent applies in sequence.
In case of a conflict, the last applied configuration set is valid.

[IMPORTANT]
====
After the {RedHatEdge} agent updated the configuration on the disk, the configuration still must be activated.
Running services need to reload the new configuration into memory for the configuration to become effective.
If the update involves a reboot, `systemd` automatically restarts the applications with the new configuration and in the correct order.
If the update does not involve a reboot, many application can detect changes to their configuration files and automatically reload them.
When a service does not support change detection, you can use device lifecycle hooks to run scripts or commands if certain conditions are met.
For more information about device lifecycle hooks and the default rules used by the {RedHatEdge} agent, see xref:edge-manager-device-lifecycle[Device lifecycle hooks].
====

You can provide configuration from many sources, called configuration providers in {RedHatEdge}.
The {RedHatEdge} currently supports the following configuration providers:

Git Config Provider:: Fetches device configuration files from a Git repository.
Kubernetes Secret Provider:: Fetches a secret from a Kubernetes cluster and writes its content to the file system of the device.
HTTP Config Provider:: Fetches device configuration files from an HTTP(S) endpoint.
Inline Config Provider:: Allows specifying device configuration files inline in the device manifest without querying external systems.

Read more about the configuration providers in the following sections:

* <<config-git,Getting configuration from a Git repository>>
* <<config-k8s-secret,Getting secrets from a Kubernetes cluster>>
* <<config-http,Getting configuration from an HTTP server>>
* <<config-inline,Specifying configuration inline in the device specification>>
