:_mod-docs-content-type: CONCEPT

[id="con-containerized-topologies"]

= {TitleTopologies}

[role="_abstract"]
Red Hat tests {PlatformNameShort} {PlatformVers} with a defined set of topologies to give you opinionated deployment options. The supported topologies include infrastructure topology diagrams, tested system configurations, example inventory files, and network ports information.

For containerized {PlatformNameShort}, there are two infrastructure topology shapes:

. Growth - (All-in-one) Intended for organizations that are getting started with {PlatformNameShort}. This topology allows for smaller footprint deployments.

. Enterprise - Intended for organizations that require {PlatformNameShort} deployments to have redundancy or higher compute for large volumes of automation. This is a more future-proofed scaled out architecture.

For more information about the tested deployment topologies for containerized {PlatformNameShort}, see link:{URLTopologies}/container-topologies[Container topologies] in _{TitleTopologies}_.
