[id="con-gs-automation-content"]

= Automation content

{HubNameStart} is the central location for your {PlatformNameShort} content. 
In {HubName} you can also find content collections that you can download and integrate into your automation environment. 

An Ansible Content Collection is a ready-to-use toolkit for automation and can include multiple types of content, including playbooks, roles, modules, and plugins all in one place.  

You can access {HubName} in one of two ways: 

* On the Red Hat-hosted link:https://console.redhat.com/[Hybrid Cloud Console], where you can find Red Hat validated or certified content that you can sync to your platform environment. 
* On a self-hosted, on-premise private {HubName}, where you can curate content for your automation users and manage access to collections. 

Depending on the way you access {HubName}, you might have access to different types of content collections.

There are two types of Red Hat Ansible content:

* Ansible Certified Content Collections, which Red Hat builds, supports, and maintains. 
Certified collections are included in your subscription to {PlatformName} and you can find in {HubName}.

== Ansible playbooks

Ansible Content Collections often include playbooks. 
Playbooks are YAML files that contain specific sets of human-readable instructions, or “plays”, that you send to run on a single target or groups of targets.  
Ansible playbooks are repeatable, reusable, configuration management tools designed to deploy complex applications. 

You can use playbooks to manage configurations of and deployments to remote machines, and sequence multitiered rollouts involving rolling updates. 
Use playbooks to delegate actions to other hosts, interacting with monitoring servers and load balancers along the way.

Once written, you can use and re-use playbooks for automation across your enterprise. 
For example, if you need to run a task more than once, write a playbook and put it under source control. 
Then you can use the playbook to push out new configuration or confirm the configuration of remote systems. 

Ansible playbooks can declare configurations, orchestrate steps of any manually ordered process on many machines in a defined order, or start tasks synchronously or asynchronously. 

.Additional resources

See link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/html-single/getting_started_with_playbooks/index[Getting started with Ansible Playbooks] for more information. 

== Ansible roles

Similar to a playbook, use Ansible roles to create reusable automation content that helps teams to work more efficiently and avoid duplicate efforts. 
With roles, you can group together a broader range of existing automation content. 
This includes playbooks, configuration files, templates, tasks, and handlers to create customized automation content that can be reused and shared with others. 

You can also make roles configurable by exposing variables that users can set when calling the role, allowing them to configure their system according to their organization's requirements.
