:_mod-docs-content-type: CONCEPT

[id="con-known-proxies_{context}"]

= Known proxies

[role="_abstract"]

When {ControllerName} is configured with `REMOTE_HOST_HEADERS = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'REMOTE_HOST']`, it assumes that the value of `X-Forwarded-For` has originated from the load balancer sitting in front of {ControllerName}.
If {ControllerName} is reachable without use of the load balancer, or if the proxy does not validate the header, it is possible to falsify the value of `X-Forwarded-For` to fake the originating IP addresses.

Using `HTTP_X_FORWARDED_FOR` in the `REMOTE_HOST_HEADERS` setting poses a vulnerability.

To avoid this, you can configure a list of the allowed known proxies.

* From the navigation panel, select {MenuSetSystem}.
* Enter a list of proxy IP addresses from which the service should trust custom remote header values in the *Proxy IP Allowed List* field.
+
[NOTE]
====
Load balancers and hosts that are not on the known proxies list result in a rejected request.
====

//.Example vulnerabilities:
//
//* The host config key for a job template
//* The hostname or ansible_(ssh_)host of a host in the job template's linked inventory
//* The URL of the job template's provisioning callback
