

[id="con-aap-installation-on-disconnected-rhel_{context}"]


= {PlatformNameShort} installation on disconnected RHEL

[role="_abstract"]
Install {PlatformNameShort} {ControllerName} and a private automation hub, with an installer-managed database located on the {ControllerName} without an Internet connection.

== Prerequisites

To install {PlatformNameShort} on a disconnected network, complete the following prerequisites:

* Create a subscription manifest.
* Download the {PlatformNameShort} setup bundle.
* Create DNS records for the automation controller and private automation hub servers.

NOTE: The setup bundle includes additional components that make installing AAP easier in a disconnected environment. These include the {PlatformNameShort} RPMs and the default execution environment (EE) images.

== System Requirements

Hardware requirements are documented in the Automation Platform Installation Guide. Reference the "Red Hat Ansible Automation Platform Installation Guide" in the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform[Ansible Automation Platform Product Documentation] for your version of {PlatformNameShort}.


== RPM Source

RPM dependencies for {PlatformNameShort} that come from the BaseOS and AppStream repositories are not included in the setup bundle. To add these dependencies, you must obtain access to BaseOS and AppStream repositories.

* link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.14/html/installing_satellite_server_in_a_disconnected_network_environment/index[Satellite] is the recommended method from Red Hat to synchronize repositories
* reposync - Makes full copies of the required RPM repositories and hosts them on the disconnected network
* RHEL Binary DVD - Use the RPMs available on the RHEL 8 Binary DVD

NOTE: The RHEL Binary DVD method requires the DVD for supported versions of RHEL 8.4 or higher. See link:https://access.redhat.com/support/policy/updates/errata[Red Hat Enterprise Linux Life Cycle] for information on which versions of RHEL are currently supported.
