:_mod-docs-content-type: CONCEPT

[id="con-upgrade-controller-hub-eda-unified-ui_{context}"]
= Automation controller and automation hub 2.4 and Event-Driven Ansible 2.5 with unified UI upgrades

{PlatformNameShort} 2.5 supports upgrades from {PlatformNameShort} 2.4 environments for all components, with the exception of {EDAName}. You can also configure a mixed environment with {EDAName} from 2.5 connected to a legacy 2.4 cluster. Combining install methods (OCP, RPM, Containerized) within such a topology is not supported by {PlatformNameShort}.

[NOTE]
====
If you are running the 2.4 version of {EDAName} in production, before you upgrade, contact Red Hat support or your account representative for more information on how to move to {PlatformNameShort} 2.5.
====

Supported topologies described in this document assume that:

* 2.4 services will only include {ControllerName} and {HubName}.
* {PlatformVers} parts will always include {EDAName} and the unified UI ({Gateway}).
* Combining installation methods for these topologies is not supported.

== Upgrade considerations

* You must have two inventory files as a starting point: one for the 2.4 services and one for the {PlatformVers} services.
* Before running the upgrade, you must merge the 2.4 inventory into the {PlatformVers} inventory. The {Gateway} host must be included in the inventory for the installation program to run successfully.
* Run the upgrade on the merged {PlatformVers} inventory file only.
* You must be using an external database for both the 2.4 inventory and {PlatformVers} inventory.
* Customers using managed database instances for either 2.4 or {PlatformVers} inventory must migrate to an external database first, before upgrading.
