[id="con-controller-job-scheduling-improvements"]

= Job scheduling improvements

When jobs are created either using a schedule, a workflow, the UI or theAPI, they are first created in Pending state. 
To determine when and where to run this job, a background task called the *Task Manager* collects all pending and running jobs and determines where capacity is available to run the job. 
In previous versions of the controller, scheduling slowed as the number of pending and running jobs increased, and the Task Manager was vulnerable to timing out without making any progress. 
This resulted in a situation where thousands of jobs were pending, despite available capacity, but no jobs were starting.

Optimizations in the job scheduler have made scheduling faster, as well as safeguards to better ensure the scheduler commits its progress even if it is nearing time out. 
Additionally, work that previously occurred in the Task Manager that blocked its progress has been decoupled into separate, non-blocking work units executed by the Dispatcher.


