:_mod-docs-content-type: CONCEPT

[id="con-controller-overview-rbac_{context}"]

= Simplified role-based access control and auditing

[role="_abstract"]
With {ControllerName} you can:

* Grant permissions to perform a specific task to different teams or explicit users through _role-based access control_ (RBAC).
Example tasks include viewing, creating, or modifying a file.
* Keep some projects private, while enabling some users to edit inventories, and others to run playbooks against certain systems, either in check (dry run) or live mode.
* Enable certain users to use credentials without exposing the credentials to them.

{ControllerNameStart} records the history of operations and who made them, including objects edited and jobs launched.

If you want to give any user or team permissions to use a job template, you can assign permissions directly on the job template. Credentials are full objects in the {ControllerName} RBAC system, and can be assigned to many users or teams for use.

{ControllerNameStart} includes an _auditor_ type. A system-level auditor can see all aspects of the systems automation, but does not have permission to run or change automation.
An auditor is useful for a service account that scrapes automation information from the REST API.

.Additional resources
* link:{URLCentralAuth}/gw-managing-access[Managing access with role based access control].
