[id="controller-minimize-administrative-accounts"]

= Minimize administrative accounts

Minimizing the access to system administrative accounts is crucial for maintaining a secure system. 
A system administrator or root user can access, edit, and disrupt any system application. 
Keep the number of people or accounts with root access to as small of a group as possible. 
Do not give out sudo to root or awx (the {ControllerName} user) to untrusted users. 
Note that when restricting administrative access through mechanisms like sudo, that restricting to a certain set of commands can still give a wide range of access. 
Any command that allows for execution of a shell or arbitrary shell commands, or any command that can change files on the system, is fundamentally equivalent to full root access.

With {ControllerName}, any {ControllerName} "system administrator" or "superuser" account can edit, change, and update any inventory or automation definition in {ControllerName}. 
Restrict this to the minimum set of users possible for low-level controller configuration and disaster recovery only.

= Minimize local system access

When you use {ControllerName} with best practices, it does not require local user access except for administrative purposes. 
Non-administrator users do not have access to the {ControllerName} system.
