[id="ocp-supported-install_{context}"]

= Supported installation scenarios for {OCP}


You can use the OperatorHub on the {OCP} web console to install {OperatorPlatformNameShort}.

Alternatively, you can install {OperatorPlatformNameShort} from the {OCPShort} command-line interface (CLI), `oc`. See xref:installing-aap-operator-cli_operator-platform-doc[Installing {OperatorPlatformName} from the {OCPShort} CLI] for help with this. 

After you have installed {OperatorPlatformNameShort} you must create an *{PlatformNameShort}* custom resource (CR). This enables you to manage {PlatformNameShort} components from a single unified interface known as the platform gateway. As of version 2.5, you must create an {PlatformNameShort} CR, even if you have an existing {ControllerName},  {HubName}, or {EDAName}, components.

If existing components have already been deployed, you must specify these components on the {PlatformNameShort} CR. You must create the custom resource in the same namespace as the existing components.

[cols=2*a,options="header"]
|===
| *Supported scenarios* | *Supported scenarios with existing components*
|
* {PlatformNameShort} CR for blank slate install with {ControllerName}, {HubName}, and {EDAName} enabled

* {PlatformNameShort} CR with just {ControllerName} enabled

* {PlatformNameShort} CR with just {ControllerName}, {HubName} enabled

* {PlatformNameShort} CR with just {ControllerName}, {EDAName} enabled
 |
 * {PlatformNameShort} CR created in the same namespace as an existing {ControllerName} CR with the {ControllerName} name specified on the {PlatformNameShort} CR spec

* Same with {ControllerName} and {HubName}

* Same with {ControllerName}, {HubName}, and {EDAName}

* Same with {ControllerName} and {EDAName}
|===

== Modifying the number of simultaneous rulebook activations during or after {EDAcontroller} installation

* If you plan to install {EDAcontroller} and run at least 12 simultaneous rulebook activations, you must add the `EDA_MAX_RUNNING_ACTIVATIONS` variable to the inventory file. See the example in appendix link:{LinkOperatorInstallation}/index#eda_max_running_activations[EDA_MAX_RUNNING_ACTIVATIONS].

//Commenting out as upgrade is not included in EA [gmurray]
//[NOTE]
//====
//The stand-alone EDA user interface will not work upon upgrade. After you configure {PlatformNameShort}, other stand-alone user interfaces will not work.
//====
