:_mod-docs-content-type: CONCEPT

[id="controller-api-basic-auth"]

= Basic authentication

Basic authentication is stateless, therefore, you must send the base64-encoded username and password along with each request through the Authorization header.
You can use this for API calls from curl requests, python scripts, or individual requests to the API.
We recommend OAuth 2 Token Authentication for accessing the API when at all possible.

The following is an example of Basic authentication with curl:

[literal, options="nowrap" subs="+attributes"]
----
# the --user flag adds this Authorization header for us
curl -X GET --user 'user:password' https://<controller-host>/api/gateway/v1/tokens/ -k -L
----

.Additional resources
For more information about Basic authentication, see link:https://datatracker.ietf.org/doc/html/rfc7617[The 'Basic' HTTP Authentication Scheme].

== Disabling Basic authentication

You can disable Basic authentication for security purposes.

.Procedure

. From the navigation panel, select {MenuSetGateway}.
. Click btn:[Edit {Gateway} settings].
. Disable the option *Gateway basic auth enabled*.
. Click btn:[Save platform gateway settings].
