:_mod-docs-content-type: CONCEPT

[id="con-install-scenario-recommendations"]

= Guidelines for configuring your inventory file

[role="_abstract"]
Inventory file recommendations define critical variables and configuration rules for installing {PlatformNameShort} in various scenarios. 
Reviewing these guidelines ensures that hosts are properly identified (using a reachable IP address or FQDN) and that credential variables meet required standards, thereby streamlining the installation process and preventing setup failures.

* Provide a reachable IP address or fully qualified domain name (FQDN) for hosts to ensure users can sync and install content from {HubName} from a different node.
+
The FQDN must not contain either the `-` or the `_` symbols, as it will not be processed correctly. 
+
Do not use `localhost`.
* The `[database]` group in the inventory file defines an {PlatformNameShort} managed database. When using an externally managed database, do not include the `[database]` group in your inventory file. For more information, see link:{URLInstallationGuide}/platform-system-requirements#proc-setup-postgresql-ext-database_licensing-gw[Setting up an external database].
* `admin` is the default user ID for the initial log in to {PlatformNameShort} and cannot be changed in the inventory file.
* Use of special characters for `pg_password` is limited. The `!`, `#`, `0` and `@` characters are supported. Use of other special characters can cause the setup to fail.
* Enter your Red Hat Registry Service Account credentials in `registry_username` and `registry_password` to link to the Red Hat container registry.
* The inventory file variables `registry_username` and `registry_password` are only required if a non-bundle installer is used.
