:_mod-docs-content-type: CONCEPT

[id="controller-api-sso-auth"]

= Single sign-on authentication

[role="_abstract"]
Single sign-on (SSO) authentication methods are different from other methods because the authentication of the user happens external to {Gateway}, such as Google SSO, {Azure} SSO, SAML, or GitHub. 

You can configure SSO authentication through {Gateway} to integrate with a central identity provider in your organization. 
Once you have configured an SSO method, an option for that SSO is available on the login screen. 
If you select that option, the platform redirects you to the identity provider, for example GitHub, where you present your credentials. 
If the identity provider verifies you successfully, {Gateway} creates a user linked to your GitHub user (if this is your first time logging in with this SSO method) and logs you in.

[role="_additional-resources"]
.Additional resources

* link:{URLCentralAuth}/gw-configure-authentication#gw-config-authentication-type[Configuring an authentication type]
