:_mod-docs-content-type: CONCEPT

[id="operator-upgrade-prereq_{context}"]

= Prerequisites

[role="_abstract"]

To upgrade to a newer version of {OperatorPlatformNameShort}, you must:

* Ensure your system meets the system requirements detailed in the link:{URLTopologies}/ocp-topologies[Operator topologies] section of the _{TitleTopologies}_ guide.
* Create AutomationControllerBackup and AutomationHubBackup objects.
For help with this see link:{URLOperatorBackup}[{TitleOperatorBackup}]
* Review the link:{URLReleaseNotes}[{TitleReleaseNotes}] for the new {PlatformNameShort} version to which you are upgrading and any intermediate versions.
* Determine the type of upgrade you want to perform.
See the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#operator-channel-upgrade_operator-upgrade[Channel Upgrades] section for more information.
+
[NOTE]
====
If you are upgrading from AAP 2.4, you are recommended to take a backup of the API call output and save it to a file. For example:
curl -k https://<CONTROLLER_FQDN>/api/v2/settings/all/ -u admin:password >> aap24_old_settings_all
====