:_mod-docs-content-type: CONCEPT


[id="con-aap-installation-on-disconnected-rhel_{context}"]

= {PlatformNameShort} installation on disconnected RHEL

[role="_abstract"]
You can install {PlatformNameShort} without an internet connection by using the installer-managed database located on the {ControllerName}. The setup bundle is recommended for disconnected installation because it includes additional components that make installing {PlatformNameShort} easier in a disconnected environment. These include the {PlatformNameShort} Red Hat package managers (RPMs) and the default {ExecEnvShort} (EE) images.

[role="_additional-resources"]
.Additional resources
* link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/appendix-inventory-files-vars[Inventory file variables]


== System requirements for disconnected installation

Ensure that your system has all the hardware requirements before performing a disconnected installation of {PlatformNameShort}. You can find these in xref:platform-system-requirements[system requirements].

<<<<<<< HEAD
=======
Before installing {PlatformNameShort} on a disconnected network, you must meet the following prerequisites:

* A subscription manifest that you can upload to the platform. 

For more information, see link:{URLContainerizedInstall}/assembly-gateway-licensing#assembly-aap-obtain-manifest-files[Obtaining a manifest file].

* The {PlatformNameShort} setup bundle at link:{PlatformDownloadUrl}[Customer Portal] is downloaded.

* The link:https://docs.ansible.com/ansible/latest/collections/community/general/nsupdate_module.html[DNS records] for the {ControllerName} and {PrivateHubName} servers are created.

>>>>>>> fab238283... AAP-66251: Broken links (#5642)
== RPM Source

RPM dependencies for {PlatformNameShort} that come from the BaseOS and AppStream repositories are not included in the setup bundle. To add these dependencies, you must first obtain access to BaseOS and AppStream repositories. Use Satellite to sync repositories and add dependencies. If you prefer an alternative tool, you can choose between the following options:

* Reposync
* The RHEL Binary DVD

[NOTE]

====
The RHEL Binary DVD method requires the DVD for supported versions of RHEL. See link:https://access.redhat.com/support/policy/updates/errata[Red Hat Enterprise Linux Life Cycle] for information on which versions of RHEL are currently supported.
====

[role="_additional-resources"]
.Additional resources
* link:https://docs.redhat.com/en/documentation/red_hat_satellite/6.16/html/installing_satellite_server_in_a_disconnected_network_environment[Installing Satellite Server in a disconnected network environment]


