[id="con-gs-learn-about-collections_{context}"]

= Learn about content collections 

Ansible content collections are assemblages of automation content. 

You can find Ansible Certified Collections in {HubName}.

== Browse content

If you are not using the bundle installer, you can use a Red Hat-supplied Ansible Playbook to install validated content. For further information, see Ansible validated content.

You can update validated collections manually by downloading their updated packages in {HubName}.

== Downloading content 

After collections are finalized, you can import them to a location where they can be distributed to others across your organization.

.Procedure

. Log in to {PlatformName}.
. From the navigation panel, select *Full Experience*. 
The {HubName} UI is displayed.
. From the navigation panel, select {MenuACCollections}. 
The *Collections* page displays all collections across all repositories. 
You can search for a specific collection.
. Select the collection that you want to export. 
The collection details page opens.
. From the *Install* tab, select *Download tarball*. 
The .tar file is downloaded to your default browser downloads folder. 
You can now import it to the location of your choosing.

