:_mod-docs-content-type: CONCEPT

[id="edge-manager-config-providers"]

= Configuration providers

[role="_abstract"]

You can provide configuration from many sources, called configuration providers, in {RedHatEdge}.
The {RedHatEdge} currently supports the following configuration providers:

Git Config Provider:: Fetches device configuration files from a Git repository.
Kubernetes Secret Provider:: Fetches a secret from a Kubernetes cluster and writes the content to the file system of the device.
HTTP Config Provider:: Fetches device configuration files from an HTTP(S) endpoint.
Inline Config Provider:: Allows specifying device configuration files inline in the device manifest without querying external systems.

Read more about the configuration providers in the following sections:

* xref:edge-manager-config-git-repo[Configuration from a Git repository]
* xref:edge-manager-k8s-cluster[Secrets from a Kubernetes cluster]
* xref:edge-manager-config-http[Configuration from an HTTP server]
* xref:edge-manager-config-inline[Configuration inline in the device specification]
