[id="con-gs-learn-about-collections_{context}"]

= About content collections 

Ansible content collections are assemblages of automation content. There are two types of Ansible collections:

* *{CertifiedName}*, which contain fully-supported roles and modules that are enterprise- and production-ready for use in your environments.
* *{Valid} collections*, which provide you with a trusted, expert-guided approach for performing foundational operations and tasks in your product. 

Both types of content collections can be found in {HubName} through the link:{Console}[Hybrid Cloud Console].

== Downloading content 

After collections are finalized, you can import them to a location where they can be distributed to others across your organization.

.Procedure

. Log in to {PlatformName}.
. From the navigation panel, select {MenuACCollections}. 
The *Collections* page displays all collections across all repositories. 
You can search for a specific collection.
. Select the collection that you want to export. 
The collection details page opens.
. From the *Install* tab, select *Download tarball*. 
The .tar file is downloaded to your default browser downloads folder. 
You can now import it to the location of your choosing.

