:_mod-docs-content-type: CONCEPT

[id="gw-oauth2-app-and-token-migration"]

= OAuth2 application and token migration (2.4 to 2.6)

[role="_abstract"]

During the upgrade from {PlatformNameShort} 2.4 to 2.6, there are important changes to how OAuth2 applications and tokens are managed. 
{PlatformNameShort} now uses {Gateway} OAuth applications and deprecates {ControllerName} OAuth applications.

* *{ControllerNameStart} OAuth applications*: You can view and edit existing {ControllerName} applications, but new ones can no longer be created. 
These legacy applications continue to function, but they might be removed in a future release. 
Plan to migrate to {Gateway} OAuth applications.
* *{ControllerNameStart} tokens*: {ControllerNameStart} personal access tokens (PATs), are also deprecated. 
Guide users to move to {Gateway} PATs.
* *{GatewayStart} OAuth applications and tokens*: Platform applications and tokens offer an updated interface and are the standard for future use. 
Move to these applications and tokens.
