:_mod-docs-content-type: CONCEPT

[id="con-gs-ansible-lightspeed"]

= {LightspeedShortName}

[role="_abstract"]

[NOTE]

====

{AAPchatbot} (ALIA), included as a Technology Preview in {PlatformName} 2.5, is deprecated. ALIA in AAP 2.5 is no longer receiving new builds or ongoing security remediation.
If you require supported intelligent assistant functionality, upgrade to link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/upgrade-con_aap_upgrade_overview[Ansible Automation Platform] 2.6 or later.
For more information about the support scope of Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview[Technology preview] in the {PlatformName} documentation.
====

{LightspeedFullName} is a generative AI service designed by and for Ansible platform engineers and developers. 
It accepts natural-language prompts entered by a user and then interacts with IBM watsonx foundation models to produce code recommendations built on Ansible best practices.

{LightspeedFullName} helps automation teams learn, create, and maintain {PlatformName} content more efficiently.
