:_mod-docs-content-type: CONCEPT

[id="certs-per-service-considerations"]
= Considerations for certificates provided per service

When providing custom TLS certificates for each individual service, consider the following:

* It is possible to provide unique certificates per host. This requires defining the specific `_tls_cert` and `_tls_key` variables in your inventory file as shown in the earlier inventory file example.
* For services deployed across many nodes (for example, when following the enterprise topology), the provided certificate for that service must include the FQDN of all associated nodes in its Subject Alternative Name (SAN) field.
* If an external-facing service (such as {ControllerName} or {Gateway}) is deployed behind a load balancer that performs SSL/TLS offloading, the service's certificate must include the load balancer's FQDN in its SAN field, in addition to the FQDNs of the individual service nodes.

[role="_additional-resources"]
.Additional resources
* link:{BaseURL}/red_hat_enterprise_linux/9/html/securing_networks/index[Securing networks]
