:_mod-docs-content-type: CONCEPT

[id="con-gs-final-set-up"]

= Using this guide

[role="_abstract"]
After you have installed {PlatformNameShort} {PlatformVers} and have become familiar with the dashboard, use this document to explore further options for setup and daily use. 
This guide is structured so that you can select the path that is most appropriate to you and your role within your organization. 
We also encourage you to explore the other paths outlined in this guide to learn how Ansible empowers users with various roles and objectives to build and customize automation tasks.

Select one of the following paths to continue getting started: 

* If you are a systems administrator configuring authentication and setting up teams and organizations, see xref:assembly-gs-platform-admin[Getting started as a platform administrator].
* If you are a developer setting up development environments, creating playbooks, rulebooks, roles, or projects, see xref:assembly-gs-auto-dev[Getting started as an automation developer].
* If you are an operator using playbooks, publishing custom content, creating projects, and creating and using inventories, see xref:assembly-gs-auto-op[Getting started as an automation operator].
