[id="con-operator-csrf-management_{context}"]

= {OperatorPlatformNameShort} CSRF management

In {PlatformNameShort} version {PlatformVers} the {OperatorPlatformNameShort} on {OCPShort} creates OpenShift Routes and configures your Cross-site request forgery (CSRF) settings automatically. When using external ingress, you must configure your CSRF on the ingress, for help with this see Configuring your CSRF settings for your {Gateway} operator ingress.

[IMPORTANT]
====
In previous versions CSRF was configurable through the {controllerName} user interface, in version {PlatformVers} {controllerName} settings are still present but have no impact on CSRF settings for the {Gateway}.
====

The following table helps to clarify which settings are applicable for which component. 

[cols=2*a,options="header"]
|===
| *UI setting* | *Applicable for*
|
Subscription
|
{ControllerName}
|
{Gateway}
|
{Gateway}
|
User Preferences
|
User interface
|
System
|
{ControllerNameStart}
|
Job
|
{ControllerNameStart}
|
Logging
|
{ControllerNameStart}
|
Troubleshooting
|
{ControllerNameStart}
|===