[id="con-gs-automation-execution"]

= Automation execution

The centerpiece of {PlatformNameShort} is its automation execution command and control center, where you can deploy, define, operate, scale and delegate automation across your enterprise. 
With this functionality, you can perform a variety of tasks, such as the ability to run playbooks using a simple, straightforward web UI, dashboards, and centralized logging to manage and track job execution from a single location. 

In the automation execution environment, you can use {ControllerName} tasks to build job templates, which standardize how automation is deployed, initiated, and delegated, making it more reusable and consistent.

== Inventory files

An inventory file is a single file with a list of hosts and groups that can be acted on using Ansible commands and playbooks. 
You can use an inventory file to specify your installation scenario and describe host deployments to Ansible. 
You can also use an inventory file to organize managed nodes in centralized files that give Ansible with system information and network locations. 

Depending on the inventory plugins, you can use many formats for your inventory files, but the most common formats are INI and YAML. 
The location of your inventory file depends on the installation program you use. 

.Additional resources
For more details on inventory files, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/planning_your_installation/index#about_the_installer_inventory_file[About the installer inventory] in the _Red Hat Ansible Automation Platform planning guide_. 
