:_mod-docs-content-type: PROCEDURE

[id="change-ssl-hub-ocp_{context}"]

= Changing the SSL/TLS certificate and key for {HubName} on {OCPShort}

[role="_abstract"]
The following procedure describes how to change the SSL/TLS certificate and key for {HubName} running on {OCPShort}.

.Procedure

. Copy the signed SSL/TLS certificate and key to a secure location.
. Create a TLS secret within OpenShift:
+
----
oc create secret tls hub-certs-$(date +%F) --cert=/path/to/ssl.crt --key=/path/to/ssl.key -n <namespace>
----
+
. Edit the {PlatformNameShort} custom resource to add `route_tls_secret` under the `hub` section:
+
----
oc edit ansibleautomationplatform <aap-instance-name> -n <namespace>
----
+
. Add or update the `route_tls_secret` parameter under `spec.hub`:
+
[source,yaml]
----
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: myaap
  namespace: ansible-automation-platform
spec:
  hub:
    route_tls_secret: hub-certs-2024-03-24
----
+
[NOTE]
====
The name of the TLS secret is arbitrary.
In this example, it is timestamped with the date that the secret is created, to differentiate it from other TLS secrets applied to the {HubName} instance.

The operator automatically applies this configuration to the {HubName} instance managed by this {PlatformNameShort} deployment.
====
. Wait a few minutes for the changes to be applied.
. Verify that new SSL/TLS certificate and key have been installed:
+
----
true | openssl s_client -showcerts -connect ${HUB_FQDN}:443
----

