
[id="proc-aap-activate-with-credentials"]

= Activate with credentials

When {PlatformNameShort} launches for the first time, the {PlatformNameShort} Subscription screen automatically displays. You can use your Red Hat service account to retrieve and import your subscription directly into {PlatformNameShort}.

[NOTE]
====
You are opted in for {Analytics} by default when you activate the platform on first time log in. This helps Red Hat improve the product by delivering you a much better user experience. You can opt out, after activating {PlatformNameShort}, by doing the following: 

. From the navigation panel, select {MenuSetSystem}.
. Clear the *Gather data for {Analytics}* option.
. Click btn:[Save].
====

.Procedure
. Log in to {PlatformName}.
. Select *Service Account / Red Hat Satellite*.
. Enter your *Client ID / Satellite username* and *Client secret / Satellite password*.
. Select your subscription from the *Subscription* list.
+
[NOTE]
====
You can also use your Satellite username and password if your cluster nodes are registered to Satellite through Subscription Manager.
====
+
. Review the End User License Agreement and select *I agree to the End User License Agreement*.
. Click btn:[Finish].

.Verification
After your subscription has been accepted, subscription details are displayed. A status of _Compliant_ indicates your subscription is in compliance with the number of hosts you have automated within your subscription count. Otherwise, your status will show as _Out of Compliance_, indicating you have exceeded the number of hosts in your subscription.
Other important information displayed include the following:

Hosts automated:: Host count automated by the job, which consumes the license count
Hosts imported:: Host count considering all inventory sources (does not impact hosts remaining)
Hosts remaining:: Total host count minus hosts automated
 