:_mod-docs-content-type: PROCEDURE

[id="proc-gs-add-ee-to-job-template_{context}"]

= Adding an {ExecEnvShort} to a job template

[role="_abstract"]
After you have built an {ExecEnvShort}, use it to run jobs. To do so, first associate the {ExecEnvShort} with a job template.

Use the following procedure to add an {ExecEnvShort} to a job template.

.Prerequisites

* An {ExecEnvShort} created using `ansible-builder` as described in link:{URLBuilder}/assembly-using-builder[Using {Builder}]. 
* Organization administrator privileges (if the {ExecEnvShort} is associated with an organization). 
* A credential with a username, host, and password (if assigned to the {ExecEnvShort}).

.Procedure

. From the navigation panel, select {MenuInfrastructureExecEnvironments}.
. Click btn:[Create execution environment] to create an {ExecEnvShort}.
. Enter the appropriate details into the following fields: 
.. *Name* (required): Enter a name for the {ExecEnvShort}.
.. *Image* (required): Enter the image name. The image name requires its full location (repository), the registry, image name, and version tag, as in the following example: `quay.io/ansible/awx-ee:latestrepo/project/image-name:tag`
.. Optional: *Pull*: Choose the type of pull when running jobs: 
... *Always pull container before running*: Pulls the latest image file for the container.
... *Only pull the image if not present before running*: Only pulls the latest image if none are specified.
... *Never pull container before running*: Never pull the latest version of the container image.
+
NOTE: If you do not set a type for pull, the value defaults to *Only pull the image if not present before running*.
+
.. Optional: *Description*: Enter an optional description.
.. Optional: *Organization*: Assign the organization to specifically use this {ExecEnvShort}. To make the {ExecEnvShort} available for use across multiple organizations, leave this field blank.
.. *Registry credential*: If the image has a protected container registry, provide the credential to access it.
. Click btn:[Create {ExecEnvShort}]. Your newly added {ExecEnvShort} is ready to be used in a job template.
. To add an {ExecEnvShort} to a job template, navigate to {MenuAETemplates} and select your template.
.. Click btn:[Edit template] and specify your {ExecEnvShort} in the field labeled *{ExecEnvShort}*.

.Verification
After you add an {ExecEnvShort} to a job template, the template is listed in the *Templates* tab in your {ExecEnvShort} details.
// [this module drawn from platform/proc-controller-use-an-exec-env.adoc -hherbly]