:_mod-docs-content-type: PROCEDURE

[id="aap-platform-ext-DB-restore_{context}"]

= Restore from an external database

[role="_abstract"]
You can restore an external database on {OCP} using the Operator. Use the following procedure to restore from an external database.

[IMPORTANT]
====
Restoring from an external database force drops the database, which overrides your existing external database.
====

.Prerequisites

* You have an external database. 
* You have installed the {OperatorPlatformNameShort} on {OCPShort}.

.Procedure 

. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Go to your *All Instances* tab, and click btn:[Create New].
. Select *{PlatformNameShort} Restore* from the list.
. For *Name* enter the name for the recovery deployment. 
. For *New {PlatformNameShort} Name* enter the new name for your {PlatformNameShort} instance. 
* If restoring to the same name {PlatformNameShort} then you must add `force_drop_db: true` to drop the database on restore.
. *Backup Source* defaults to *CR*.
. For *Backup name* enter the name you chose when creating the backup. 
Under *YAML view* paste in the following example:
+
----
---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatformRestore
metadata:
  name: aaprestore
spec:
  deployment_name: aap
  backup_name: aapbackup
  controller:
    force_drop_db: true
----
+
. Click btn:[Create].

.Verification

Your backups starts restoring under the *AnsibleAutomationPlatformRestores* tab.

[NOTE]
====
The recovery is not complete until all the resources are successfully restored. Depending on the size of your database this this can take some time.
====

To verify that your recovery was successful you can:

. Go to menu:Workloads[Pods].
. Confirm that all pods are in a *Running* or *Completed* state.

[role="_additional-resources"]
.Additional resources

* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index[Installing on OpenShift Container Platform]
