:_newdoc-version: 2.18.3
:_template-generated: 2024-07-15
:_mod-docs-content-type: PROCEDURE

[id="modifying-the-run-schedule_{context}"]
= modifying-the-run-schedule


You can configure metrics-utility to run at specified times and intervals. Run frequency is expressed in cronjobs; see link:https://www.redhat.com/sysadmin/linux-cron-command[How to schedule jobs using the Linux ‘Cron’ utility] for more information. 

== On RHEL
=== *Procedure*
 
. From the command line, run: 
+
[source, ]
----
crontab -e 
----
+
. After the code editor has opened, update the gather and build parameters using cron syntax as shown below: 
+
[source, ]
----
*/2 * * * *     metrics-utility gather_automation_controller_billing_data --ship --until=10m
*/5 * * * *     metrics-utili
ty build_report
----
+
. Save and close the file.

== On Openshift Container Platform from the AAP operator 
=== *Procedure*

. From the navigation panel, select *Workloads > Deployments*.
. On the next screen, click *automation-controller-operator-controller-manager*.
. Beneath the heading *Deployment Details*, click the down arrow button to change the number of pods to zero. This will pause the deployment so you can update the running schedule. 
. From the navigation panel, click *Installed Operators*. From the list of installed operators, select Ansible Automation Platform. 
. On the next screen, select the Automation Controller tab. 
. From the list that appears, click your controller instance. 
. On the next screen, select the YAML tab. 
. In the YAML file, find the following parameters and enter a variable representing how often metrics-utility should gather data and how often it should produce a report: 
+
[source, ]
----
metrics_utility_cronjob_gather_schedule:
metrics_utility_cronjob_report_schedule: 
----
+
. Click *Save*.
. From the navigation menu, select *Deployments* and click automation-controller-operator-controller-manager.
. Increase the number of pods to 1.
. To verify that you have changed the utility-metrics running schedule successfully, return to the YAML file and ensure that the parameters described above reflect the correct variables. OR From the navigation menu, select *Workloads > Cronjobs* and ensure that your cronjobs show the updated schedule. 
