:_mod-docs-content-type: PROCEDURE

[id="proc-gs-auto-dev-create-automation-execution-proj"]

= Creating an automation execution project

[role="_abstract"]
A project is a logical collection of playbooks. 
Projects are useful as a way to group your automation content according to the organizing principle of your choice. 

You can set up an automation execution project in the platform UI. 

.Procedure

. From the navigation panel, select {MenuAEProjects}.
. On the *Projects* page, click btn:[Create project] to launch the *Create Project* window.
. Enter the appropriate details into the following required fields:

* *Name* (required)
* Optional: *Description*
* *Organization* (required): A project must have at least one organization. Select one organization now to create the project. When the project is created you can add additional organizations.
* Optional: *Execution Environment*: Enter the name of the {ExecEnvShort} or search from a list of existing ones to run this project.
* *Source Control Type* (required): Select an SCM type associated with this project from the menu.
Options in the following sections become available depending on the type chosen.
For more information, see link:{URLControllerUserGuide}/controller-projects#proc-controller-adding-a-project[Managing playbooks manually] or link:{URLControllerUserGuide}/controller-projects#ref-projects-manage-playbooks-with-source-control[Managing playbooks using source control].
* Optional: *Content Signature Validation Credential*: Use this field to enable content verification.
Specify the GPG key to use for validating content signature during project synchronization.
If the content has been tampered with, the job will not run.
For more information, see link:{URLControllerUserGuide}/assembly-controller-project-signing[Project signing and verification].
+
. Click btn:[Create project].

