
[id="proc-add-insights-plugin-eda-variable"]

= Displaying port mappings for Red Hat Instights source plugin

When {PlatformNameShort} launches for the first time, the {PlatformNameShort} Subscription screen automatically displays. You can use your Red Hat credentials to retrieve and import your subscription directly into {PlatformNameShort}.

.Procedures
. Select *Username / password*.
. Enter your Red Hat username and password.
. Select your subscription from the *Subscription* list.
+
[NOTE]
====
You can also use your Satellite username and password if your cluster nodes are registered to Satellite through Subscription Manager.
====
+
. The Automation Analytics option is checked by default. These selections help Red Hat improve the product by delivering you a much better user experience. You can opt out by deselecting the options.
. Review the End User License Agreement and select *I agree to the End User License Agreement*.
. Click btn:[Finish].
. After your subscription has been accepted, the license screen displays and navigates you to the Dashboard of the {PlatformNameShort} interface. You can return to the license screen by selecting {MenuSetSubscription} from the navigation panel and clicking btn:[Edit subscription]..
