[id="edge-manager-k8s-auth"]

= Authorizing with Kubernetes

To authorize resources with Kubernetes while using the {RedHatEdge}, you need to set variables in your Helm `values.yaml` file that fit your environment.

.Procedure

. Set the following variables in the `values.yaml` file:

[source,yaml]
----
global:
  target: "standalone" <1>
  baseDomain: ""
  baseDomainTls:
    cert: ""
    key: ""
  storageClassName: ""
  imagePullSecretName: ""
  apiUrl: "" <2>
  auth:
    type: "k8s" <3>
    caCert: "" <4>
    insecureSkipTlsVerify: false <4>
    k8s:
      apiUrl: https://kubernetes.default.svc <5>
      externalOpenShiftApiUrl: "" <6>
      externalApiToken: "" <7>
      rbacNs: ""
    [...]
----
<1> You can set the `global.target` field to `standalone` or `acm`. If the field is set to `acm`, the Kubernetes authorization values are automatically calculated.
<2> Optional. If deploying on RHACM, set the `global.apiUrl` to enable interactive login for the CLI.
<3> Set the `global.auth.type` field to `k8s`.
<4> Optional. Set the `global.auth.caCert` and `global.auth.insecureSkipTlsVerify` fields.
<5> Optional. If you want to use a different cluster as `auth` authority, set the `global.auth.k8s.apiUrl` field to the API URL of the external Kubernetes cluster.
<6> Optional. If the external Kubernetes cluster is an OpenShift cluster, set the `global.auth.k8s.externalOpenShiftApiUrl` field to enable interactive login for the CLI.
<7> Optional. If you want to use a different cluster as `auth` authority, set the `global.auth.k8s.externalApiToken` field to a token which has permission to create the `authentication.k8s.io/tokenreview` resource in the external Kubernetes cluster.

// Not relevant for AAP:
// If deploying on ACM (by global.target: acm), the k8s auth values are automatically calculated.
