:_mod-docs-content-type: PROCEDURE

[id="proc-operator-external-db-gateway"]

= Configure an external database for {Gateway} on {OperatorPlatformName}

[role="_abstract"]

There are two scenarios for deploying {PlatformNameShort} with an external database:

[cols="a,a"]
|===
| Scenario | Action required
| Fresh install        | You must specify a single external database instance for the platform to use for the following:

* {GatewayStart}
* {ControllerNameStart}
* {HubNameStart}
* {EDAName}
* {LightspeedShortName} (If enabled)

See the _aap-configuring-external-db-all-default-components.yml_ example in the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#operator-crs[14.1. Custom resources] section for help with this.

If using {LightspeedShortName}, use the _aap-configuring-external-db-with-lightspeed-enabled.yml_ example.

| Existing external database in 2.4       | Your existing external database remains the same after upgrading but you must specify the `external-postgres-configuration-gateway` (spec.database.database_secret) on the {PlatformNameShort} custom resource.
|===


To deploy {PlatformNameShort} with an external database, you must first create a Kubernetes secret with credentials for connecting to the database.

By default, the {OperatorPlatformNameShort} automatically creates and configures a managed PostgreSQL pod in the same namespace as your {PlatformNameShort} deployment. You can deploy {PlatformNameShort} with an external database instead of the managed PostgreSQL pod that the {OperatorPlatformNameShort} automatically creates.

Using an external database lets you share and reuse resources and manually manage backups, upgrades, and performance optimizations.

[NOTE]
====
The same external database (PostgreSQL instance) can be used for both {HubName}, {ControllerName}, and {Gateway} as long as the database names are different. In other words, you can have multiple databases with different names inside a single PostgreSQL instance.
====

The following section outlines the steps to configure an external database for your {Gateway} on a {OperatorPlatformNameShort}.

.Prerequisite
The external database must be a PostgreSQL database that is the version supported by the current release of {PlatformNameShort}. The external postgres instance credentials and connection information must be stored in a secret, which is then set on the {Gateway} spec.

[NOTE]
====
{PlatformNameShort} {PlatformVers} supports {PostgresVers} for its managed databases and additionally supports PostgreSQL 15, 16, and 17 for external databases.

If you choose to use an externally managed database with version 16 or 17 you must also rely on external backup and restore processes.
====

.Procedure

. Create a `postgres_configuration_secret` YAML file, following the template below:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: external-postgres-configuration
  namespace: <target_namespace> <1>
stringData:
  host: "<external_ip_or_url_resolvable_by_the_cluster>" <2>
  port: "<external_port>" <3>
  database: "<desired_database_name>"
  username: "<username_to_connect_as>"
  password: "<password_to_connect_with>" <4>
  type: "unmanaged"
type: Opaque
----
.. Namespace to create the secret in. This should be the same namespace you want to deploy to.
.. The resolvable hostname for your database node.
.. External port defaults to `5432`.
.. Value for variable `password` should not contain single or double quotes (', ") or backslashes (\) to avoid any issues during deployment, backup or restoration.
// [Christian Adams] We can roll out a fix for it 3/12, then next async release for everything.  It may be good to exclude step 5 for ssl mode here.  We'll need to track added that in once the fix is in for the operator. - Removing point 5 here until a fix is implemented.
// <5> The variable `sslmode` is valid for `external` databases only. The allowed values are: `*prefer*`, `*disable*`, `*allow*`, `*require*`, `*verify-ca*`, and `*verify-full*`.
. Apply `external-postgres-configuration-secret.yml` to your cluster using the `oc create` command.
+
----
$ oc create -f external-postgres-configuration-secret.yml
----
+
[NOTE]
====
The following example is for a {Gateway} deployment.
To configure an external database for all components, use the _aap-configuring-external-db-all-default-components.yml_ example in the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#operator-crs[14.1. Custom resources] section.
====
+
. When creating your `AnsibleAutomationPlatform` custom resource object, specify the secret on your spec, following the example below:
+
----
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: example-aap
  Namespace: aap
spec:
  database:
     database_secret: automation-platform-postgres-configuration 
----
