:_mod-docs-content-type: PROCEDURE

[id="proc-set-up-virtual-machines"]

= Setting up Virtual Machines for use in an {AutomationMesh}

[role="_abstract"]
Prepare {RHEL} virtual machines by setting up SSH access and enabling repositories. 
Deploying these VMs as nodes helps expand the execution capacity of your {AutomationMesh}. 

.Procedure

. SSH into each of the RHEL instances and perform the following steps. 
Depending on your network access and controls, SSH proxies or other access models might be required. 
+
Use the following command:
+
----
ssh [username]@[host_ip_address]
----
+
For example, for an {PlatformNameShort} instance running on {AWS}.
+
----
ssh ec2-user@10.0.0.6
----

. Create or copy an SSH key that can be used to connect from the hop node to the execution node in later steps. 
This can be a temporary key used just for the automation mesh configuration, or a long-lived key. 
The SSH user and key are used in later steps.

. Enable your RHEL subscription with `baseos` and `appstream` repositories. 
{PlatformNameShort} RPM repositories are only available through subscription-manager, not the _Red Hat Update Infrastructure_ (RHUI).  
If you attempt to use any other Linux footprint, including RHEL with RHUI, this causes errors. 
+
----
sudo subscription-manager register --auto-attach
----
+
If Simple Content Access is enabled for your account, use:
+
----
sudo subscription-manager register
----
+
For more information about Simple Content Access, see link:{BaseURL}/subscription_central/1-latest/html/getting_started_with_simple_content_access/index[Getting started with simple content access].

. Enable {PlatformNameShort} subscriptions and the proper {PlatformName} channel:
+
For RHEL 8
+
----
# subscription-manager repos --enable ansible-automation-platform-2.5-for-rhel-8-x86_64-rpms
----
+
For RHEL 9
+
----
# subscription-manager repos --enable ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms
----
+
For ARM
+
----
# subscription-manager repos --enable ansible-automation-platform-2.5-for-rhel-aarch64-rpms
----
+
. Ensure the packages are up to date:
+
---- 
sudo dnf upgrade -y
----

. Install the ansible-core packages on the machine where the downloaded bundle is to run:
+
----
sudo dnf install -y ansible-core
----
+
[NOTE]
====
Ansible core is required on the machine that runs the {AutomationMesh} configuration bundle playbooks. This document assumes that happens on the execution node. 
However, this step can be omitted if you run the playbook from a different machine. 
You cannot run directly from the control node, this is not currently supported, but future support expects that the control node has direct connectivity to the execution node.
====

