:_mod-docs-content-type: PROCEDURE

[id="controller-set-up-azure"]

= Configure {MSEntraID} authentication

[role="_abstract"]
To set up enterprise authentication for {MSEntraID}, formerly known as {Azure} Active Directory (AD), follow these steps:

. *Configure your {PlatformNameShort}* to use {MSEntraID} authentication using the steps in this procedure.
. *Register {PlatformNameShort}* in {MSEntraID} by following the link:https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app[Quickstart: Register an application with the Microsoft identity platform]. This process provides you with an Application (client) ID and Application secret.
. *Add the redirect URL in {MSEntraID}*. After completing the configuration wizard for {MSEntraID} authentication in your platform, copy the URL displayed in the *Azure AD OAuth2 Callback URL* field. Then, go to your registered enterprise application in Azure and add this URL as a *Redirect URL* (also referred to as a *Callback URL* in {PlatformNameShort}) as described in link:https://learn.microsoft.com/en-us/entra/identity-platform/how-to-add-redirect-uri[How to add a redirect URI to your application]. This step is required for the login flow to work correctly.

The attributes provided by {MSEntraID} are not set in the {PlatformNameShort} configuration for this authentication type. Instead, the link:https://github.com/python-social-auth/social-core/blob/master/social_core/backends/azuread.py#L85-L98[social_core azuread backend] provides the translation of claims provided by {MSEntraID}. The user attributes that allow {PlatformNameShort} to correctly identify the user and assign the proper attributes such as given name, surname, email, and username include the following: 

[cols="2*",options="header"]
|===
| {PlatformNameShort} attribute | {MSEntraID} parameter
| authenticator_uid | upn
| Username | name
| First Name | given_name
| Last Name | family_name
| Email | email (falling back to upn)
|===

endif::[]
ifdef::controller-AG[]
To set up enterprise authentication for {Azure} Active Directory (AD), you need to obtain an OAuth2 key and secret by registering your organization-owned application from Azure at: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app[Quickstart: Register an application with the Microsoft identity platform].
endif::[]

Each key and secret must belong to a unique application and cannot be shared or reused between different authentication backends. To register the application, you must supply it with your webpage URL, which is the Callback URL shown in the Authenticator details for your authenticator configuration. 
ifndef::Controller-AG[]
See xref:gw-display-auth-details[Displaying authenticator details] for instructions on accessing this information.  
endif::[]

.Procedure

ifndef::controller-AG[]
. From the navigation panel, select {MenuAMAuthentication}.
. Click btn:[Create authentication].
. Enter a *Name* for this authentication configuration. 
. Select *Azuread* from the *Authentication type* list. The *Authentication details* section automatically updates to show the fields relevant to the selected authentication type.
+
//include::snippets/snip-gw-authentication-auto-migrate.adoc[]
+
. Click btn:[Edit], copy and paste Microsoft's *Application (Client) ID* to the *OIDC Key* field.
. If your {MSEntraID} is configured to provide user group information within a groups claim, ensure that the platform is configured with a *Groups Claim* name that matches your {MSEntraID} configuration. This allows the platform to correctly identify and associate groups for users logging in through {MSEntraID}.
+ 
[NOTE]
====
Groups coming from {MSEntraID} can be identified using either unique IDs or group names. 
When creating group mappings for a {MSEntraID} authenticator, you can use either the unique ID or the group name.

By default, {MSEntraID} uses groups as the default group claim name. So, be sure to either set the value to the default or to any custom override you have set in your IdP. The current default is set to preserve the existing behavior unless explicitly changed.
====
+
. Following instructions for link:https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app[registering your application with the Microsoft identity platform], supply the key (shown at one time only) to the client for authentication. 
+
. Copy and paste the secret key created for your {MSEntraID}/{Azure} AD application to the *OIDC Secret* field.
. Optional: By default, the name attribute from {MSEntraID} is used as the username field within {PlatformNameShort}. 
If you want to override that default value and use another attribute from {MSEntraID}, enter that attribute in the username field.
+
include::snippets/snip-gw-authentication-additional-auth-fields.adoc[]
+
include::snippets/snip-gw-authentication-common-checkboxes.adoc[]
+
. Click btn:[Create Authentication Method].

.Verification
include::snippets/snip-gw-authentication-verification.adoc[]

.Next steps
include::snippets/snip-gw-authentication-next-steps.adoc[]

.Additional resources
* link:https://learn.microsoft.com/en-us/entra/identity-platform/v2-overview[What is the Microsoft identity platform?]
