:_mod-docs-content-type: PROCEDURE

[id="proc-gs-use-base-execution-env_{context}"]

= Use the base {ExecEnvNameSing}

[role="_abstract"]
{PlatformNameShort} provides access to some base {ExecEnvName}. You can use a base {ExecEnvShort} as a starting point for creating a customized {ExecEnvShort}.

{PlatformNameShort} includes the following execution environments:

* `Minimal` - Includes the latest Ansible-core 2.15 release along with Ansible Runner, but does not include collections or other content
* `EE Supported` - Minimal, plus all Red Hat-supported collections and dependencies

Base images included with {PlatformNameShort} are hosted on the Red Hat Ecosystem Catalog (`registry.redhat.io`).

.Prerequisites 

* You have a valid {PlatformName} subscription. 

.Procedure 

. Log in to `registry.redhat.io`.
+
[source,bash]
----
$ podman login registry.redhat.io
----
+
. Pull the base images from the registry: 
[source,bash]
----
$ podman pull registry.redhat.io/aap/<image name>
----

[role="_additional-resources"]
.Additional resources
* link:{URLBuilder}/assembly-publishing-exec-env#proc-customize-ee-image[Customizing an existing automation {ExecEnvShort} image] 
 