:_mod-docs-content-type: PROCEDURE

[id="edge-manager-install-CLI"]

= Installing the {RedHatEdge} CLI

[role="_abstract"]

To install the {RedHatEdge} CLI, complete the following steps:

.Procedure 

. Enable the subscription manager for the repository appropriate for your system by running the following command:
+
[source,bash]
----
sudo subscription-manager repos --enable ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms
----
+
For a full list of available repositories for the {RedHatEdge}, see the link:{URLEdgeManager}/assembly-edge-manager-images#edge-manager-additional-resources-images[_Additional resources_] section.

. Install the `flightctl` CLI with your package manager by running the following command:

+
[source,bash]
----
sudo dnf install flightctl
----
+
If you link:{URLEdgeManager}/assembly-edge-manager-install#edge-manager-oauth-manually[set up the OAuth application manually], you also need to make sure that one utility `xdg-open`, `x-www-browser`, or `www-browser` is available, for example, by installing `xdg-utils`.
