:_mod-docs-content-type: PROCEDURE

[id="proc-controller-inv-source-terraform"]

= Source an inventory from Terraform State

[role="_abstract"]
Use the following procedure to create a Terraform State inventory source.

This inventory source uses the terraform_state inventory plugin from the link:https://console.redhat.com/ansible/automation-hub/repo/published/cloud/terraform/content/inventory/terraform_state/[cloud.terraform] collection. 
The plugin parses a terraform state file and add hosts for AWS EC2, GCE, and {Azure} instances.

.Procedure

. From the navigation panel, select {MenuAEProjects}.
. On the *Projects* page, click btn:[Create project] to start the *Create project* window.
** Enter the appropriate details according to the steps in xref:proc-controller-adding-a-project[Adding a new project].
. From the navigational panel, select {MenuInfrastructureInventories}.
. Select the inventory that you want to add a source to.
. In the *Sources* tab, click btn:[Create source].
. From the menu:Source[] menu, select *Terraform State*.
* The *Create source* window expands with the optional *Credential* field. 
+
Choose an existing Terraform backend configuration credential. For more information, see xref:ref-controller-credential-terraform[Terraform backend configuration].
. Enable the options to *Overwrite* and *Update on launch*.
. Use the *Source variables* field to override variables used by the `terraform_state` inventory plugin. 
Enter variables by using either JSON or YAML syntax. 
Use the radio button to toggle between the two. 
For more information about these variables, see the link:https://console.redhat.com/ansible/automation-hub/repo/published/cloud/terraform/content/inventory/terraform_state/[terraform_state] file.
+
The `backend_type` variable is required by the Terraform State inventory plugin. 
This should match the remote backend configured in the *Terraform backend credential*.
The following is an example Amazon S3 backend:
+
----
backend_type: s3
----
+
. Select an *Execution environment* that has a Terraform binary. 
This is required for the inventory plugin to run the Terraform commands that read inventory data from the Terraform state file.
+
[IMPORTANT]
====
Terraform provider for {PlatformNameShort} inventories are managed by Terraform and you must not edit them in {PlatformNameShort} as it can introduce drift to the Terraform deployment.
====

.Additional resources

* link:https://github.com/ansible-cloud/terraform_ee[Terraform EE] 
* link:https://registry.terraform.io/providers/ansible/aap/latest/docs[Red Hat Ansible Automation Platform provider]  
