:_mod-docs-content-type: PROCEDURE

[id="downloading-containerized-aap"]

= Downloading {PlatformNameShort}

Choose the installation program you need based on your {RHEL} environment internet connectivity and download the installation program to your {RHEL} host.

.Procedure

. Download the latest installer .tar file from the link:{PlatformDownloadUrl}[{PlatformNameShort} download page]. 
.. For online installations: *{PlatformNameShort} {PlatformVers} Containerized Setup*
.. For offline or bundled installations: *{PlatformNameShort} {PlatformVers} Containerized Setup Bundle*

. Copy the installation program .tar file and the optional manifest .zip file onto your {RHEL} host.

. Decide where you want the installation program to reside on the file system. Installation related files are created under this location and require at least 10 GB for the initial installation.

. Unpack the installation program .tar file into your installation directory, and go to the unpacked directory. 
+
.. To unpack the online installer:
+
----
$ tar xfvz ansible-automation-platform-containerized-setup-<version>.tar.gz
----
+
.. To unpack the offline or bundled installer:
+
----
$ tar xfvz ansible-automation-platform-containerized-setup-bundle-<version>-<arch_name>.tar.gz
----

