:_mod-docs-content-type: PROCEDURE

[id="proc-gw-create-roles"]

= Creating a role

[role="_abstract"]

{PlatformNameShort} services provide a set of predefined roles with permissions enough for standard automation tasks. It is also possible to configure custom roles that define access permissions to a resource.

If the default predefined roles for a resource type do not give the necessary permissions, you can create custom roles for an organization. 
Creating a custom role reduces complexity by consolidating all required permissions into a single assignment per resource or resource type, eliminating the need to assign multiple roles to a user or team.

.Procedure

. From the navigation panel, select {MenuAMRoles}.
. Click btn:[Create role].
. Provide a *Name* and a short *Description* for the role. The name and description should be unique and specific to the role's intended use and permissions to give context when assigning the role.
. Select a *Resource Type*. Ensure that you are selecting the required resource in the correct component context, because resources such as projects and credentials can be associated with both Automation Execution and Automation Decisions.
. Select the *Permissions* you want assigned to this role from the drop-down menu.
. Click btn:[Create role] to create your new role.
