[id="controller-find-subscription"]

= Finding your subscription with service account credentials

When you log in to {PlatformNameShort} for the first time, you must add your subscription information. 

If you have already added your subscription, you can update your subscription details in the platform by going to {MenuSetSubscription} → btn:[Edit subscription].

.Procedure

. Enter your service account credentials to find the subscription associated with your profile:
.. To find your subscription, click the tab labeled *Service Account / Red Hat Satellite*.
.. In the *Client ID / Satellite username* field enter the client ID you received when you created your service account.
.. In the *Client secret / Satellite password* field enter the client secret you received when you created your service account.
Your subscription appears in the list menu labeled *Subscription*. 
Select your subscription.

. After you have added your subscription, click btn:[Next].
. Check the box indicating that you agree to the *End User License Agreement*.
. Review your information and click *Finish*.

.Troubleshooting

If you enter your client ID and client secret but are unable to locate your subscription, you may not have the correct permissions set on your service account. 
To remediate this issue, you have two options:

* If you know who your organization administrator is, contact them with a request for access. 
* If you do not know who your organization administrator is, message the Virtual Assistant on link:https://console.redhat.com/[console.redhat.com] with the prompt "Who is my Org Admin" and then follow the subsequent prompts. 
You can find the Virtual Assistant by clicking the red VA icon at the bottom right of your screen on any part of the Hybrid Cloud Console. 
The Virtual Assistant then communicates with your organization administrator. 

When requesting access, be prepared to give the following information so that your organization administrator can evaluate your request and make a determination:

* Your account number/org ID, if known.
* A clear description of the tasks you need to perform. 
In this case, using your service account to find your subscription.
* The specific permissions you believe are required. 
In this case, subscription viewer permission.
