:_mod-docs-content-type: PROCEDURE

[id="proc-editing-installer-inventory-file_{context}"]


= Editing the {PlatformName} installer inventory file

[role="_abstract"]
You can use the {PlatformName} installer inventory file to specify your installation scenario.

.Procedure

*For an RPM installation*
* [RPM installed package]
+
-----
$ cd /opt/ansible-automation-platform/installer/
-----
+
* [bundled installer]
+
-----
$ cd ansible-automation-platform-setup-bundle-<latest-version>
-----
+
* [online installer]
+
-----
$ cd ansible-automation-platform-setup-<latest-version>
-----
ifdef::mesh-VM[]
*For a containerized installation*
* [Containerized installer]
+
----
cd <path-to-source-file>/ansible-automation-platform-containerized-setup-<version_number>
----

* [Bundled containerized installer]
+
----
cd <path-to-source-file/ansible-automation-platform-containerized-setup-bundle-<version_number>-<arch_name>
----
endif::mesh-VM[]
. Open the `inventory` file with a text editor.
. Edit the `inventory` file parameters to specify your installation scenario. 
+
For containerized installation, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/containerized_installation/aap-containerized-installation#configuring-inventory-file[Configuring the inventory file]
ifdef::mesh-VM[]
For further information, see link:{URLInstallationGuide}/assembly-platform-install-scenario#proc-editing-installer-inventory-file_platform-install-scenario[Editing the {PlatformName} installer inventory file]
endif::mesh-VM[]
ifdef::aap-install[]
You can use one of the supported xref:con-install-scenario-examples[Installation scenario examples] as the basis for your `inventory` file.

[role="_additional-resources"]
.Additional resources
* For a comprehensive list of pre-defined variables used in Ansible installation inventory files, see xref:appendix-inventory-files-vars[Inventory file variables].
endif::aap-install[]

