:_mod-docs-content-type: PROCEDURE

[id="proc-controller-ingress-options_{context}"]

= Configuring the ingress type for your {ControllerName} operator

[role="_abstract"]

The {OperatorPlatformNameShort} installation form allows you to further configure your {ControllerName} operator ingress under *Advanced configuration*.

.Procedure

. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *Ansible Automation Platform* tab.
. Click the {MoreActionsIcon} icon next to your {PlatformNameShort} instance and select btn:[Edit AnsibleAutomationPlatform].
. Click btn:[YAML view] and locate the `spec.controller:` section.
. Configure the ingress options under the `controller:` section:
+
[source,yaml]
----
spec:
  controller:
    ingress_type: Ingress
    ingress_annotations: |
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    ingress_tls_secret: controller-ingress-tls-secret
----
+
. Click btn:[Save].
+
[NOTE]
====
These ingress settings apply to the {ControllerName} component managed by this {PlatformNameShort} instance. The operator automatically updates the ingress configuration for the controller.

For more examples of {PlatformNameShort} custom resources, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#appendix-operator-crs_operator-platform-doc[Appendix: {PlatformName} custom resources].
====

.Verification

After you have configured your {ControllerName} ingress settings, {OCP} updates the pods. This may take a few minutes.

You can view the progress by navigating to menu:Workloads[Pods] and locating the newly created instance.

Verify that the following operator pods provided by the {PlatformNameShort} Operator installation from {ControllerName} are running:
[cols="a,a,a,a", options="header", subs=+attributes]
|===
| Operator manager controllers | {ControllerNameStart} |{HubNameStart} |{EDAName} (EDA)

| The operator manager controllers for each of the three operators, include the following:

* automation-controller-operator-controller-manager
* automation-hub-operator-controller-manager
* resource-operator-controller-manager
* aap-gateway-operator-controller-manager 
* ansible-lightspeed-operator-controller-manager
* eda-server-operator-controller-manager

| After deploying {ControllerName}, you can see the addition of the following pods:

* controller
* controller-postgres
* controller-web
* controller-task

| After deploying {HubName}, you can see the addition of the following pods:

* hub-api
* hub-content
* hub-postgres
* hub-redis
* hub-worker

| After deploying EDA, you can see the addition of the following pods:

* eda-activation-worker
* da-api
* eda-default-worker
* eda-event-stream
* eda-scheduler

|===

[NOTE]
====
A missing pod can indicate the need for a pull secret. Pull secrets are required for protected or private image registries. See link:https://docs.openshift.com/container-platform/4.11/openshift_images/managing_images/using-image-pull-secrets.html[Using image pull secrets] for more information. You can diagnose this issue further by running `oc describe pod <pod-name>` to see if there is an ImagePullBackOff error on that pod.
====
