:_mod-docs-content-type: PROCEDURE

[id="proc-controller-create-organization"]

= Creating an organization

{PlatformNameShort} automatically creates a default organization. If you have a self-support level license, you have only the default organization available and can not delete it. 
You can use the default organization as it is initially set up and edit it later.

.Procedure
. From the navigation panel, select {MenuAMOrganizations}.
. Click btn:[Create organization].
. Enter the *Name* and optionally provide a *Description* for your organization.
+
[NOTE]
====
If {ControllerName} is enabled on the platform, continue with Step 4. Otherwise, proceed to Step 7.
====
+
. Enter the name of the *Instance Groups* on which to run this organization. 
. Select the name of the *Default execution environment* or search for one that exists on which to run this organization. 
. Optional: Enter the *Galaxy credentials* or search from a list of existing ones.
. Click btn:[Next]. 
. You can manage the instance group order by dragging and dropping the instance group up or down in the list. 
+
[NOTE]
====
The execution precedence is determined by the order in which the instance groups are listed. 
====
+
. Click btn:[Next] and verify the organization settings.
. Click btn:[Finish].
