

[id="proc-migrate-SAML-users_{context}"]

= Migrating Single Sign-On (SSO) users
 
[role="_abstract"]

When upgrading from {PlatformNameShort} 2.4 to 2.5, you must migrate your Single Sign-On (SSO) user accounts if you want to continue using SSO capabilities after the upgrade. Follow the steps in this procedure to ensure a smooth SSO user migration. 

== Key considerations

*SSO configurations are not migrated automatically during upgrade to 2.5:* SSO configurations must be manually migrated over to {PlatformNameShort} 2.5 after a successful upgrade. 


*SSO migration is not currently supported in the UI:* While migration of SSO accounts is supported in 2.5,  the configuration is not supported through the platform UI and must be done through the API `/api/gateway/v1/authenticators/`.

*Migration of SSO must happen before users log in and start account linking:* You must enable the *Auto migrate users* to setting _after_ configuring SSO in 2.5 and _before_ any users log in.

.Prerequisistes

You have configured a SSO authentication method in the {Gateway} following the steps in link:{URLCentralAuth}/gw-configure-authentication#gw-config-authentication-type[Configuring an authentication type]. This will be the configuration that you will migrate your previous SSO users to. 

[NOTE]
====
{PlatformNameShort} 2.4 SSO configurations are renamed during the upgrade process and are displayed in the *Authentication Methods* list view prefixed to indicate that it is a legacy configuration, for example,  `legacy_sso-saml-<entity id>`. The *Authentication type* is also listed as *legacy sso*. These configurations can not be modified.
====

.Procedure

. Log in to the {Gateway} API.
. Go to `/api/gateway/v1/authenticators/`, locate the legacy authenticator and click the link. 
. This opens the HTML form for that authenticator. 
. Select the new {Gateway} authenticator from the *Auto migrate users to* list. 
. Click btn:[PUT]. 

Once you set up the auto migrate functionality, you should be able to login with SSO in the {Gateway} and it will automatically link any matching accounts from the legacy SSO authenticator.
