:_mod-docs-content-type: PROCEDURE

[id="controller-ee-mount-execution-node"]

= Mounting the directory in the execution node to the {ExecEnvShort} container

[role="_abstract"]
Learn how to configure paths exposed to isolated jobs, allowing volumes to be mounted from execution or hybrid nodes to job containers.

.Procedure

. From the navigation panel, select {MenuSetJob}.
. Edit the *Paths to expose to isolated jobs* field:
** Enter a list of paths that volumes are mounted from the execution node or the hybrid node to the container.
** Enter one path per line.
** The supported format is `HOST-DIR[:CONTAINER-DIR[:OPTIONS]`.
The allowed paths are `z`, `O`, `ro`, and `rw`.
+
*Example*
----
[
  "/var/lib/awx/.ssh:/root/.ssh:O"
]
----
+
** For the `rw` option, configure the SELinux label correctly.
For example, to mount the `/foo` directory, complete the following commands:
+
----
sudo su
----
+
----
mkdir /foo
----
+
----
chmod 777 /foo
----
+
----
semanage fcontext -a -t container_file_t "/foo(/.*)?"
----
+
----
restorecon -vvFR /foo
----
+
The `awx` user must be permitted to read or write in this directory at least.
Set the permissions as `777` at this time.

[role="_additional-resources"]
.Additional resources
* link:https://docs.podman.io/en/stable/markdown/podman-run.1.html#volume-v-source-volume-host-dir-container-dir-options[--volume option of the podman-run(1)]
