:_mod-docs-content-type: PROCEDURE


[id="proc-operator-external-db-controller"]

= Configuring an external database for {ControllerName} on {OperatorPlatformName}

[role="_abstract"]

For users who prefer to deploy {PlatformNameShort} with an external database, they can do so by configuring a secret with instance credentials and connection information, then applying it to their cluster using the `oc create` command.

By default, the {OperatorPlatformNameShort} automatically creates and configures a managed PostgreSQL pod in the same namespace as your {PlatformNameShort} deployment. You can deploy {PlatformNameShort} with an external database instead of the managed PostgreSQL pod that the {OperatorPlatformNameShort} automatically creates.

Using an external database lets you share and reuse resources and manually manage backups, upgrades, and performance optimizations.

[NOTE]
====
The same external database (PostgreSQL instance) can be used for both {HubName}, {ControllerName}, and {Gateway} as long as the database names are different. In other words, you can have multiple databases with different names inside a single PostgreSQL instance.
====

The following section outlines the steps to configure an external database for your {ControllerName} on a {OperatorPlatformNameShort}.

.Prerequisite
The external database must be a PostgreSQL database that is the version supported by the current release of {PlatformNameShort}. The external postgres instance credentials and connection information must be stored in a secret, which is then set on the {ControllerName} spec.

[NOTE]
====
{PlatformNameShort} {PlatformVers} supports {PostgresVers}.
====

.Procedure

. Create a `postgres_configuration_secret` YAML file, following the template below:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: external-postgres-configuration
  namespace: <target_namespace> <1>
stringData:
  host: "<external_ip_or_url_resolvable_by_the_cluster>" <2>
  port: "<external_port>" <3>
  database: "<desired_database_name>"
  username: "<username_to_connect_as>"
  password: "<password_to_connect_with>" <4>
  sslmode: "prefer" <5>
  type: "unmanaged"
type: Opaque
----
.. Namespace to create the secret in. This should be the same namespace you want to deploy to.
.. The resolvable hostname for your database node.
.. External port defaults to `5432`.
.. Value for variable `password` should not contain single or double quotes (', ") or backslashes (\) to avoid any issues during deployment, backup or restoration.
.. The variable `sslmode` is valid for `external` databases only. The allowed values are: `*prefer*`, `*disable*`, `*allow*`, `*require*`, `*verify-ca*`, and `*verify-full*`.
. Apply `external-postgres-configuration-secret.yml` to your cluster using the `oc create` command.
+
----
$ oc create -f external-postgres-configuration-secret.yml
----
. When creating your `AutomationController` custom resource object, specify the secret on your spec, following the example below:
+
----
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: controller-dev
spec:
  postgres_configuration_secret: external-postgres-configuration
----
