:_mod-docs-content-type: PROCEDURE

[id="uninstalling-containerized-aap_{context}"]
= Uninstalling containerized {PlatformNameShort}

[role="_abstract"]

When performing a reinstall following an uninstall that preserves the databases, you must use the previously generated {PlatformNameShort} secret key values to access the preserved databases.

Before running the uninstall, collect the existing secret keys by running the following command:
----
$ podman secret inspect --showsecret <secret_key_variable> | jq -r .[].SecretData
----
For example:
----
$ podman secret inspect --showsecret controller_secret_key | jq -r .[].SecretData
----

For more information about the `*_secret_key` variables, see link:{URLContainerizedInstall}/appendix-inventory-files-vars[Inventory file variables].

To uninstall a containerized deployment, run the `uninstall.yml` playbook:
----
$ ansible-playbook -i inventory ansible.containerized_installer.uninstall
----

This stops all systemd units and containers and then deletes all resources used by the containerized installer such as:

* configuration and data directories and files
* systemd unit files
* Podman containers and images
* RPM packages

To keep container images, set the `container_keep_images` variable to `true`.
----
$ ansible-playbook -i inventory ansible.containerized_installer.uninstall -e container_keep_images=true
----

To keep PostgreSQL databases, set the `postgresql_keep_databases` variable to `true`.
----
$ ansible-playbook -i inventory ansible.containerized_installer.uninstall -e postgresql_keep_databases=true
----


