:_mod-docs-content-type: PROCEDURE

[id="provision-ocp-storage-azure-blob_{context}"]

= Configuring object storage on Azure Blob

[role="_abstract"]

Red Hat supports Azure Blob Storage for {HubName}.
You can configure it when deploying the `AnsibleAutomationPlatform` custom resource (CR), or you can configure it for an existing instance.

.Prerequisites

* Create an Azure Storage blob container to store the objects.
* Note the name of the blob container.

.Procedure

. Create a Kubernetes secret containing the credentials and connection details for your Azure account, and the name of your Azure Storage blob container.
The following example creates a secret called `test-azure`: 
+
[source,yaml]
----
$ oc -n $HUB_NAMESPACE apply -f- <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: 'test-azure'
stringData:
  azure-account-name: $AZURE_ACCOUNT_NAME
  azure-account-key: $AZURE_ACCOUNT_KEY
  azure-container: $AZURE_CONTAINER
  azure-container-path: $AZURE_CONTAINER_PATH
  azure-connection-string: $AZURE_CONNECTION_STRING
EOF
----
+
. Add the secret to the {PlatformNameShort} custom resource (CR) under the `hub` section in the `spec`:
+
[source,yaml]
----
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: myaap
spec:
  hub:
    storage_type: azure
    object_storage_azure_secret: test-azure
----
+
[NOTE]
====
If you have an existing {HubName} instance, specify its name using `hub.name: existing-hub-name` to apply these settings to the existing instance.

For more examples of {PlatformNameShort} custom resources, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#appendix-operator-crs_operator-platform-doc[Appendix: {PlatformName} custom resources].
====
+
. If you are applying this secret to an existing instance, restart the API pods for the change to take effect.
`<hub-name>` is the name of your hub instance.
+
[source,bash]
----
$ oc -n $HUB_NAMESPACE delete pod -l app.kubernetes.io/name=<hub-name>-api
----

