:_mod-docs-content-type: PROCEDURE

[id="operator-deploy-redis"]

= Configure Redis 

[role="_abstract"]

When you create an {PlatformNameShort} instance through the {OperatorPlatformNameShort}, standalone Redis is assigned by default. 
If you would prefer to deploy clustered Redis, you can use the following procedure.

For more information about Redis, refer to Caching and queueing system in the _Planning your installation_ guide.

[IMPORTANT]
====
Switching Redis modes on an existing instance is not supported and can lead to unexpected consequences, including data loss. 
To change the Redis mode, you must deploy a new instance.
====

.Prerequisites

* You have installed an {OperatorPlatformNameShort} deployment.

.Procedure

. Log in to {OCP}. 
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *Details* tab. 
. On the *{PlatformNameShort}* tile click btn:[Create instance].
.. For existing instances, you can edit the YAML view by clicking the {MoreActionsIcon} icon and then btn:[Edit AnsibleAutomationPlatform].
.. Change the *redis_mode* value to "cluster".
.. Click btn:[Reload], then btn:[Save].
. Click to expand *Advanced configuration*.
. For the *Redis Mode* list, select *Cluster*.
. Configure the rest of your instance as necessary, then click btn:[Create].

.Verification

Your instance deploys with a cluster Redis with 6 Redis replicas as default. 

[NOTE]
====
You can modify your {HubName} default redis cache PVC volume size, for help with this see, link:https://access.redhat.com/articles/7117186[Modifying the default redis cache PVC volume size automation hub]. 
====