[id="operator-link-components_{context}"]

= Linking your components to the platform gateway  

After installing the {OperatorPlatform} in your namespace you can set up your *{PlatformNameShort}* instance.
Then link all the platform components to a single user interface. 

.Procedure 

. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatform} deployment.
. Select the *Details* tab. 

. On the *{PlatformNameShort}* tile click btn:[Create instance].
. From the *Create {PlatformNameShort}* page enter a name for your instance in the *Name* field.
. Click btn:[YAML view] and paste the following:
+
----
spec:
  controller:
    disabled: false

  eda:
    disabled: false

  hub:
    disabled: false
    storage_type: file
    file_storage_storage_class: nfs-local-rwx
    file_storage_size: 10Gi

----
. Click btn:[Create].

.Verification
Go to your {OperatorPlatform} deployment and click btn:[All instances] to verify if all instances deployed correctly.
You should see the *{PlatformNameShort}* instance and the deployed *AutomationController*, *EDA*, and *AutomationHub* instances here.

Alternatively you can check by the command line, run: `oc get route` 
