:_mod-docs-content-type: PROCEDURE

[id="proc_configuring-controller-ldap-security_{context}"]

= Configuring your controller LDAP security

You can configure your LDAP SSL configuration for {ControllerName} through any of the following options:

* The {ControllerName} user interface.
* The {Gateway} user interface. See the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/access_management_and_authentication/index#controller-set-up-LDAP[Configuring LDAP authentication] section of the _Access management and authentication_ guide for additional steps.
* The following procedure steps.

.Procedure
. Create a secret in your {PlatformNameShort} namespace for the `bundle-ca.crt` file (the filename must be `bundle-ca.crt`):
+
----
$ oc create secret -n aap-namespace generic bundle-ca-secret --from-file=bundle-ca.crt
----
+
. Add the `bundle_cacert_secret` to the {PlatformNameShort} customer resource:
+
----
...
spec:
  bundle_cacert_secret: bundle-ca-secret
...
----
+

.Verification

You can verify the expected certificate by running:
+
----
oc exec -it deployment.apps/aap-gateway - openssl x509 -in /etc/pki/tls/certs/bundle-ca.crt -noout -text
----

