:_newdoc-version: 2.18.5
:_template-generated: 2025-08-06
:_mod-docs-content-type: PROCEDURE

[id="verify-user-migration_{context}"]
= Verify user migration

During the upgrade to AAP 2.6, controller user accounts are converted into platform user accounts. Controller administrators retain their administrative privileges, but they are converted into platform administrator privileges. 

Other controller accounts become platform users, and their existing permissions are mapped over appropriately after an initial password reset. Users with existing accounts associated with other components (like automation hub and Event Driven Ansible) must have their passwords reset by their administrator before they can log in.

Authenticator configurations are automatically migrated. SSO and LDAP accounts do not require any manual migration steps, including password resets, with the exception of accounts that use a certificate from the trust store. See [LINK NEEDED] for more information on migrating authentication configurations that use a custom certificate.

After your upgrade to AAP 2.6 is complete, verify that you can log in to the upgraded platform with your existing controller credentials.

.Prerequisites

* You have a controller account with administrative privileges.

.Procedure

* Log into your upgraded platform instance with your controller credentials.
+

