:_mod-docs-content-type: PROCEDURE

[id="operator-create-crs_{context}"]

= Create {PlatformNameShort} custom resources

[role="_abstract"]

After upgrading to the latest version of {OperatorPlatformNameShort} on {OCPShort}, you can create an {PlatformNameShort} custom resource (CR) that specifies the names of your existing deployments, in the same namespace.

The following example outlines the steps to deploy a new {EDAName} setup after upgrading to the latest version, with existing {ControllerName} and {HubName} deployments already in place.

The link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#appendix-operator-crs_performance-considerations[Appendix] contains more examples of {PlatformNameShort} CRs for different deployments.

.Procedure

. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *Details* tab. 
. On the *{PlatformNameShort}* tile click btn:[Create instance].
. From the *Create {PlatformNameShort}* page enter a name for your instance in the *Name* field.
. Click btn:[YAML view] and paste the following YAML (link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#appendix-operator-crs_performance-considerations[aap-existing-controller-and-hub-new-eda.yml]):
+
----
---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: myaap
spec:
  # Development purposes only
  no_log: false

  controller:
    name: existing-controller #obtain name from controller CR
    disabled: false

  eda:
    disabled: false

  hub:
    name: existing-hub
    disabled: false
----
. Click btn:[Create].
+
[NOTE]
====
You can override the operator’s default image for {ControllerName}, {HubName}, or platform-resource app images by specifying the preferred image on the YAML spec.
This enables upgrading a specific deployment, like a controller, without updating the operator.

The recommended approach however, is to upgrade the operator and use the default image values. 
====
+

.Verification
Navigate to your {OperatorPlatformNameShort} deployment and click btn:[All instances] to verify whether all instances have deployed correctly.
You should see the *{PlatformNameShort}* instance and the deployed *AutomationController*, *EDA*, and *AutomationHub* instances here.

Alternatively, you can verify whether all instances deployed correctly by running `oc get route` in the command line.
