[id="proc-gs-logging-in"]

= Logging in for the first time

Log in to the {PlatformNameShort} as an administrator and enter your subscription information. 
You can then create user profiles and assign roles.

.Procedure

. With the login information provided after your installation completed, open a web browser and log in to {PlatformName} by navigating to its server URL at: https://<AAP_SERVER_NAME>/
. Use the credentials specified during the installation process to login:
** The default username is *admin*.
** The password for *admin* is the value specified during installation.

After your first login, you are prompted to add your subscription manifest. 

== Adding your subscription

.Prerequisite

* You have link:https://docs.redhat.com/en/documentation/red_hat_hybrid_cloud_console/1-latest/html/creating_and_managing_service_accounts/proc-ciam-svc-acct-overview-creating-service-acct#proc-ciam-svc-acct-create-creating-service-acct[created a service account] and saved the client ID and client secret. 

.Procedure

. You can select between uploading a copy of your subscription manifest or entering your service account credentials to find the subscription associated with your profile:
.. To upload a subscription manifest, drag the file to the field beneath *Red Hat subscription manifest* or browse for the file on your local machine.
.. To find your subscription with your service account credentials, click the tab labeled *Service Account / Red Hat Satellite*.
... In the field labeled Client ID / Satellite username, enter the *client ID* you received when you created your service account. 
... In the field labeled Client secret / Satellite password, enter the *client secret* you received when you created your service account. 
Your subscription will appear in the list menu labeled *Subscription*. 
Select your subscription.
. After you have added your subscription, click btn:[Next].
. Check the box indicating that you agree to the *End User License Agreement*. 
. Review your information and click btn:[Finish].

[NOTE]
====
If you enter your client ID and client secret but cannot locate your subscription, you might not have the correct permissions set on your service account. For more information and troubleshooting guidance for service accounts, see link:https://access.redhat.com/articles/7112649[Configure Ansible Automation Platform to authenticate through service account credentials].
====

[TIP]
====

After logging in, review the quick starts section in the navigation panel for useful guidance.

====
