// Module included in the following assemblies:
// assembly-using-builder.adoc

:_mod-docs-content-type: PROCEDURE

[id="updating-ee-image-locations"]

= Updating {ExecEnvShort} image locations for RPM-based installations

[role="_abstract"]
If you installed {PrivateHubName} separately from RPM-based {PlatformNameShort}, you can update your {ExecEnvShort} image locations to point to your {PrivateHubName}.

.Procedure

. Go to the directory that contains `setup.sh`.
. Create `./group_vars/automationcontroller` by running the following command:
+
----
touch ./group_vars/automationcontroller
----
+
. Paste the following content into `./group_vars/automationcontroller`. Adjust the settings to fit your environment:
+
----
# Automation hub registry
registry_username: 'your-automation-hub-user'
registry_password: 'your-automation-hub-password'
registry_url: 'automationhub.example.org'
registry_verify_ssl: False

## Execution environments
control_plane_execution_environment: 'automationhub.example.org/ee-supported-rhel9:latest'

global_job_execution_environments:
  - name: "Default execution environment"
    image: "automationhub.example.org/ee-supported-rhel9:latest"
  - name: "Minimal execution environment"
    image: "automationhub.example.org/ee-minimal-rhel9:latest"
----
+
[NOTE]
====
For information on obtaining `registry_username` and `registry_password`, see link:{URLInstallationGuide}/index#proc-set-registry-username-password[Setting registry_username and registry_password].
====

. Run the `./setup.sh` script:
+
----
$ ./setup.sh
----

.Verification

. Log in to {PlatformNameShort} as a user with system administrator access.
. Go to {MenuInfrastructureExecEnvironments}.
. In the *Image* column, confirm that the {ExecEnvShort} image location has changed from the default value of `<registry url>/ansible-automation-platform-<version>/<image name>:<tag>` to `<automation hub url>/<image name>:<tag>`.
