:_mod-docs-content-type: PROCEDURE

[id="proc-configure-mcp-server-containerized-install_{context}"]

= Deploying an Ansible MCP server on a {ContainerBase}

[role="_abstract"]
As an organization administrator, you can deploy and configure an Ansible MCP server on a {ContainerBase} of {PlatformNameShort} {PlatformVers}. Use the following procedure to deploy and configure the Ansible MCP server.

.Prerequisites

* You have a valid {PlatformNameShort} {PlatformVers} subscription.

.Procedure

. Configure the Ansible MCP server variables in the inventory file:

.. Create an `[ansiblemcp]` group and add a host for the Ansible MCP server.

.. Add the following installation variables to your inventory file under the `[all:vars]` group:

* `mcp_allow_write_operations`: Use to grant read-only or read-write permissions to the external AI tool. 
* `mcp_ignore_certificate_errors`: Use to bypass SSL/TLS certificate validation. 

.. To make your system trust a self-signed custom certificate, add the following required variables to your inventory file:

* `mcp_tls_cert`: Path to TLS certificate 
* `mcp_tls_key`:  Path to TLS key
+
For information about using your own TLS certificates and keys, see link:{URLContainerizedInstall}/advanced-configuration-containerized#using-custom-tls-certificates[Configuring custom TLS certificates]. For information about required and optional variables, see xref:ansible-mcp-server-variables[Appendix: Ansible MCP server variables].
+
[source]
----
# This is the list of inventory file variables required to deploy an Ansible MCP server on a container-based installation.

# This section is for the Ansible MCP server host
# -------------------------------------------------
[ansiblemcp]
aap.example.com

# This section is for Ansible MCP server permissions
# --------------------------------------------------
[all:vars]
mcp_allow_write_operations=false <To enable read-write access, set the "mcp_allow_write_operations" variable to "true">
mcp_ignore_certificate_errors=false
mcp_tls_cert= <path to tls certificate>
mcp_tls_key= <path to tls key>
----

. xref:installing-containerized-aap[Run the `install` playbook to install containerized {PlatformNameShort}].

.Verification

Check the pods after installation is complete. You should see an `ansiblemcp` pod running with the following command:

[source,none]
----
$ podman ps
----

[role="_additional-resources"]
.Next steps

. Obtain the location of the Ansible MCP server:
** The service is exposed on port 8448 of the host, and HTTPS is enabled.
** The example above deploys the MCP server on `aap.example.com`, so the service base URL will be `\https://aap.example.com:8448`.

. xref:proc-create-api-token-ansible-mcp-server_deploying-ansible-mcp-server[Create an API token for the Ansible MCP server].

[role="_additional-resources"]
.Additional resources

* xref:ansible-mcp-server-variables[Appendix: Ansible MCP server variables]