:_mod-docs-content-type: PROCEDURE

[id="proc-gs-auto-op-launch-template"]

= Launch a job template

[role="_abstract"]
{PlatformNameShort} offers push-button deployment of Ansible playbooks. 
You can configure a template to store all the parameters that you would normally pass to the Ansible playbook on the command line. 
In addition to the playbooks, the template passes the inventory, credentials, extra variables, and all options and settings that you can specify on the command line.

.Procedure

. From the navigation panel, select {MenuAETemplates}.
. Select a template to view its details. A default job template is created during your initial setup to help you get started, but you can also create your own. 
. From the *Templates* page, click the launch icon to run your job template. 

.Verification
The *Templates* list view shows job templates that are currently available. The default view is collapsed (Compact), showing the template name, template type, and the timestamp of the last job that ran using that template. You can click the arrow icon next to each entry to expand and view more information. This list is sorted alphabetically by name, but you can sort by other criteria, or search by various template fields and attributes. 

From this screen you can launch, edit, and copy a job template. 

[role="_additional-resources"]
.Additional resources
* link:{URLControllerUserGuide}/controller-job-templates[Job Templates] 
* link:{URLControllerUserGuide}/controller-workflow-job-templates[Workflow job templates]

