:_mod-docs-content-type: PROCEDURE

[id="operator-link-components_{context}"]

= Deploy a new {PlatformNameShort} instance with components 

[role="_abstract"]
After installing the {OperatorPlatformNameShort} in your namespace you can set up your *{PlatformNameShort}* instance.
Then link all the platform components to a single user interface. 

.Procedure 

. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *Details* tab. 

. On the *{PlatformNameShort}* tile click btn:[Create instance].
. From the *Create {PlatformNameShort}* page enter a name for your instance in the *Name* field.
. Click btn:[YAML view] and replace the `spec` section with the following:
+
----
spec:
  database:
    resource_requirements:
      requests:
        cpu: 200m
        memory: 512Mi
    storage_requirements:
      requests:
        storage: 100Gi 

  controller:
    disabled: false

  eda:
    disabled: false

  hub:
    disabled: false
    storage_type: file
    file_storage_storage_class: <read-write-many-storage-class>
    file_storage_size: 10Gi

----
. You must specify your desired value for the `<read-write-many-storage-class>` placeholder.
. Click btn:[Create].

.Verification

*Verify instance deployment (UI):*

. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *All instances* tab. 
. Verify that the *Ansible Automation Platform* instance, *Automation Controller*, *Event-Driven Ansible*, and *Automation Hub* instances are listed.

*Verify pod status (UI):*

. Navigate to menu:Workloads[Pods].
. Switch to the project (namespace) where you deployed the instance.
. Verify that all related pods display a *Running* or *Completed* status.
 
*Verify Platform Route (CLI):*

Run the following command to confirm the URL for accessing the {Gateway}:
----
oc get route
----

