[id="edge-manager-enroll-device-cli"]

= Enrolling devices on the CLI

Complete the following steps:

.Procedure

. List all devices that are currently waiting for approval by running the following command:

+
--
[source,terminal]
----
flightctl get enrollmentrequests
----

See the following example output:

[source,terminal]
----
NAME           APPROVAL  APPROVER  APPROVED LABELS
<device_name>  Pending   <none>    <none>    
----
--
+

[NOTE]
====
The unique device name is generated by the agent and you cannot change it.
The agent chooses a base32-encoded hash of its public key as device name.
====
+

. Approve an enrollment request by specifying the name of the enrollment request. Optionally, you can add labels to the device by using the `--label` or `-l` flags. See the following example:

+
--
[source,terminal]
----
flightctl approve -l region=eu-west-1 -l site=factory-berlin enrollmentrequest/54shovu028bvj6stkovjcvovjgo0r48618khdd5huhdjfn6raskg
----

See the following example output:

[source,terminal]
----
NAME           APPROVAL  APPROVER  APPROVED LABELS
<device_name>  Approved  user      region=eu-west-1,site=factory-berlin
----
--

After you approve the enrollment request, the service issues the management certificate for the device and registers the device in the device inventory.
You can then manage the device.
