:_mod-docs-content-type: PROCEDURE

[id="operator-link-components_{context}"]

= Linking your components to the {Gateway}  

After installing the {OperatorPlatformNameShort} in your namespace you can set up your *{PlatformNameShort}* instance.
Then link all the platform components to a single user interface. 

.Procedure 

. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *Details* tab. 

. On the *{PlatformNameShort}* tile click btn:[Create instance].
. From the *Create {PlatformNameShort}* page enter a name for your instance in the *Name* field.
. Click btn:[YAML view] and paste the following:
+
----
spec:
  database:
    resource_requirements:
      requests:
        cpu: 200m
        memory: 512Mi
    storage_requirements:
      requests:
        storage: 100Gi 

  controller:
    disabled: false

  eda:
    disabled: false

  hub:
    disabled: false
    storage_type: file
    file_storage_storage_class: <read-write-many-storage-class>
    file_storage_size: 10Gi

----
. Click btn:[Create].

.Verification
* Go to your {OperatorPlatformNameShort} deployment and click btn:[All instances] to verify if all instances deployed correctly.
+
You should see the *{PlatformNameShort}* instance and the deployed *AutomationController*, *EDA*, and *AutomationHub* instances here.
+
Alternatively you can check by the command line, run: `oc get route` 

* Verify that all the pods are running successfully, by performing the following steps:

. Navigate to menu:Workloads[Pods].
. Switch to the project named as described in the namespace metadata in the *YAML* configuration view.
. Verify that all pods display either a *Running* or *Completed* status, with no pods displaying an error status.
