:_mod-docs-content-type: PROCEDURE


[id="proc-aap-activate-with-credentials"]

= Activate with credentials

[role="_abstract"]
Activate your {PlatformNameShort} subscription at the first launch by providing either Red Hat service account credentials or your personal Red Hat username and password. This process automatically retrieves and imports the required license, which grants the platform access to Red Hat content and entitlement services.

[NOTE]
====
You are opted in for {Analytics} by default when you activate the platform on first login. This helps Red Hat improve the product by delivering you a much better user experience. You can opt out after activating {PlatformNameShort} by taking the following steps: 

. From the navigation panel, select {MenuSetSystem}.
. Clear the *Gather data for {Analytics}* option.
. Click btn:[Save].
====

.Procedure

. Log in to {PlatformName}.
. Select the *Service Account* tab in the subscription wizard.
. Enter your *Client ID* and *Client secret*.
. Select your subscription from the *Subscription* list.
+
[NOTE]
====
You can also enter your Satellite username and password in the *Satellite* tab if your cluster nodes are registered to Satellite through Subscription Manager.
====
+
. Review the End User License Agreement and select *I agree to the End User License Agreement*.
. Click btn:[Finish].

.Verification

After your subscription has been accepted, subscription details are displayed. A status of _Compliant_ indicates your subscription is in compliance with the number of hosts you have automated within your subscription count. Otherwise, your status shows as _Out of Compliance_, indicating you have exceeded the number of hosts in your subscription.
Other important information displayed include the following:

Hosts automated:: Host count automated by the job, which consumes the license count
Hosts imported:: Host count considering all inventory sources (does not impact hosts remaining)
Hosts remaining:: Total host count minus hosts automated
 