
[id="proc-add-insights-plugin-eda-variable_{context}"]

= Adding a safe plugin variable to {EDAcontroller}

When using plugins such as redhat.insights_eda or other similar plugins to run rulebook activations in {EDAcontroller}, you must add a safe plugin variable to a directory in {PlatformNameShort}. This would ensure connecton between {EDAcontroller} and the source plugin and display port mappings correctly. 

.Procedure
//[J. Self] Need to let the customer know where they are in this process (not in platform UI)
. Create a directory for the safe plugin variable: `mkdir -p ./group_vars/automationedacontroller`
. Create a file within that directory for your new setting (for example, `touch ./group_vars/automationedacontroller/custom.yml`)
. Use the following example to add the `automationedacontroller_safe_plugins` to the file along with a comma-separated list of plugins to enable for {EDAcontroller}: 
+
---
automationedacontroller_safe_plugins: “ansible.eda.webhook, ansible.eda.alertmanager”
