:_mod-docs-content-type: PROCEDURE

[id="controller-set-up-tacacs"]

= Configuring TACACS+ authentication

[role="_abstract"]

Terminal Access Controller Access-Control System Plus (TACACS+) is a protocol that handles remote authentication and related services for networked access control through a centralized server. TACACS+ provides authentication, authorization and accounting (AAA) services, in which you can configure {PlatformNameShort} to use as a source for authentication.

[NOTE]
====
This feature is deprecated and will be removed in a future release.
====

.Procedure

. From the navigation panel, select {MenuAMAuthentication}.
. Click btn:[Create authentication].
. Enter a *Name* for this authentication configuration. 
. Select *TACACS+* from the *Authentication type* list. The *Authentication details* section automatically updates to show the fields relevant to the selected authentication type.
+
//include::snippets/snip-gw-authentication-auto-migrate.adoc[]
+
. Enter the following information:
+
* Hostname of TACACS+ Server: Provide the hostname or IP address of the TACACS+ server with which to authenticate. If you leave this field blank, TACACS+ authentication is disabled.
* TACACS+ Authentication Protocol: The protocol used by the TACACS+ client. The options are ascii or pap.
* Shared secret for authenticating to TACACS+ server: The secret key for TACACS+ authentication server.
. The *TACACS+ client address sending enabled* is disabled by default. To enable client address sending, select the checkbox.
+
include::snippets/snip-gw-authentication-additional-auth-fields.adoc[]
+
include::snippets/snip-gw-authentication-common-checkboxes.adoc[]
+
. Click btn:[Create Authentication Method].

[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-authentication-next-steps.adoc[]