:_mod-docs-content-type: PROCEDURE

[id="change-ssl-hub-ocp_{context}"]

= Change the SSL/TLS certificate and key for {HubName} on {OCPShort}

[role="_abstract"]
The following procedure describes how to change the SSL/TLS certificate and key for your operator-based {PlatformNameShort} installation of {HubName} running on {OCPShort}.

.Procedure

. Copy the signed SSL/TLS certificate and key to a secure location.
. Create a TLS secret within OpenShift:
+
----
oc create secret tls ${AUTOMATION_HUB_INSTANCE}-certs-$(date +%F) --cert=/path/to/ssl.crt --key=/path/to/ssl.key
----
. Modify the {HubName} custom resource to add `route_tls_secret` and the name of the new secret to the spec section.
+
----
oc edit automationhub/${AUTOMATION_HUB_INSTANCE}
----
+
----
...
spec:
  route_tls_secret: automation-hub-certs-2023-04-06
...
----
[NOTE]
====
The name of the TLS secret is arbitrary.
In this example, it is timestamped with the date that the secret is created, to differentiate it from other TLS secrets applied to the {HubName} instance.
====
. Wait a few minutes for the changes to be applied.
. Verify that new SSL/TLS certificate and key have been installed:
+
----
true | openssl s_client -showcerts -connect ${CONTROLLER_FQDN}:443
----

