:_newdoc-version: 2.18.3
:_template-generated: 2024-10-09
:_mod-docs-content-type: PROCEDURE

[id="upgrade-controller-hub-eda-unified-ui_{context}"]
= Use migration path for 2.4 instances with managed databases

[role="_abstract"]
Migrate {PlatformNameShort} 2.4 instances with managed databases to {PlatformVers} by upgrading {ControllerName} and {HubName} before enabling unified UI and {EDAName}. 

.Prerequisites

* An inventory from 2.4 for {ControllerName} and {HubName} and a 2.6 inventory for unified UI ({Gateway}) and {EDAName}. You must run upgrades on 2.4 services (using the inventory file to specify only {ControllerName} and {HubName} VMs) to get them to the initial version of {PlatformNameShort} {PlatformVers} first. When all the services are at the same version, run an upgrade (using a complete inventory file) on all the services to go to the latest version of {PlatformNameShort} {PlatformVers}.

[IMPORTANT]
====
DO NOT upgrade {EDAName} and the unified UI ({Gateway}) to the latest version of {PlatformNameShort} {PlatformVers} without first upgrading the individual services ({ControllerName} and {HubName}) to the initial version of {PlatformNameShort} {PlatformVers}.
====

* Ensure you have upgraded to the latest version of {PlatformNameShort} 2.4 before upgrading your {PlatformName}.

.Procedure

* *For standalone node managed database*

** Convert the database node to an external one, removing it from the inventory. The PostgreSQL node will continue working and will not lose the {PlatformNameShort}-provided setup, but you are responsible for managing its configuration afterward.

* *For collocated managed database*

. Back up
. Restore with standalone managed database node instead of collocated
. Unmanaged standalone database
