:_mod-docs-content-type: PROCEDURE

[id="proc-pulling-the-secret"]

= Pulling the secret for {OCPShort} deployments

[role="_abstract"]
If you are using the default {ExecEnvShort} provided with {ControllerName} to run on remote execution nodes, you must add a pull secret in {ControllerName} that has the credential for pulling the {ExecEnvShort} image.

[NOTE]
====
This does not apply to {PlatformNameShort} on {Azure}.
====

Create a pull secret on the {ControllerName} namespace and configure the `ee_pull_credentials_secret` parameter in the Operator as follows:

.Procedure
. Create a secret using the following command:
+
----
oc create secret generic ee-pull-secret \
     --from-literal=username=<username> \
     --from-literal=password=<password> \
     --from-literal=url=registry.redhat.io
----

. Add `ee_pull_credentials_secret` and `ee-pull-secret` to the specification by editing the deployment specification:
+
----
oc edit automationcontrollers aap-controller-o yaml
----
+
and add the following:
+
----
spec
  ee_pull_credentials_secret=ee-pull-secret
----

. To manage instances from the {ControllerName} UI, you must have System Administrator or System Auditor permissions.
