[id="create-secret-key-secret_{context}"]

= Creating a secret key secret

[role=_abstract]

To migrate your data to {OperatorPlatformNameShort} on {OCPShort}, you must create a Kubernetes secret.
This secret must contain the key retrieved from your source environment to ensure migrated data remains usable.

[IMPORTANT]
====
The `SECRET_KEY` and `SECRET_ENCRYPTION_KEY` serve different purposes. You must use the `SECRET_ENCRYPTION_KEY` for database migration. If you provide the incorrect key, the operator cannot decrypt migrated data.

For instructions on finding your key, see link:{BaseURL}/red_hat_ansible_automation_platform/2.4/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/index#operator-locate-hub-encryption-key_aap-migration[Locate the automation hub encryption key].
====

[cols="33%,33%,33%",options="header"]
|===
| Component | CRD field name | Secret stringData key

| {ControllerNameStart}
| `secret_key_name`
| `secret_key`

| {HubNameStart}
| `db_fields_encryption_secret`
| `database_fields.symmetric.key`

| {EDAName}
| `db_fields_encryption_secret`
| `secret_key`
|===

.Prerequisites

* Access to the {OCPShort} CLI (`oc`).
* The symmetric encryption key retrieved from the source {HubName} instance.


.Procedure

. Locate the old secret keys in the inventory file you used to deploy {PlatformNameShort} in your previous installation.
. Create a YAML file for your secret keys:
+
-----
---
apiVersion: v1
kind: Secret
metadata:
  name: <controller-resourcename>-secret-key
  namespace: <target-namespace>
stringData:
  secret_key: <replaceme-with-controller-secret>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: <eda-resourcename>-secret-key
  namespace: <target-namespace>
stringData:
  secret_key: <replaceme-with-eda-secret>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: <hub-resourcename>-secret-key
  namespace: <target-namespace>
stringData:
  database_fields.symmetric.key: <replace-me-withdb-fields-encryption-key>
type: Opaque

-----
+
[NOTE]
====
If `admin_password_secret` is not provided, the operator looks for a secret named `<resourcename>-admin-password` for the admin password.
If it is not present, the operator generates a password and create a secret from it named `<resourcename>-admin-password`.
====
+
. Apply the secret key YAML to the cluster:
+
-----
oc apply -f <yaml-file>
-----

.Verification

* Verify that the secret exists: 
+
----
oc get secret automation-hub-secret-key -n <target-namespace>
----

