:_mod-docs-content-type: PROCEDURE

[id="preparing-the-managed-nodes-for-containerized-installation"]

= Prepare the managed nodes for containerized installation

[role="_abstract"]
Managed nodes, also referred to as hosts, are the devices that {PlatformNameShort} manages. 
To ensure a consistent and secure setup of containerized {PlatformNameShort}, create a dedicated user on each managed node. {PlatformNameShort} connects as this user to run tasks on the node.

.Procedure

. Log in to the host as the root user.
. Create a new user. Replace `<username>` with the username you want, for example `aap`.
+
----
$ sudo adduser <username>
----
+
. Set a password for the new user. Replace `<username>` with the username you created.
+
----
$ sudo passwd <username>
----
+
. Configure the user to run `sudo` commands.
+
For a secure and maintainable installation, configure `sudo` privileges for the installation user in a dedicated file within the `/etc/sudoers.d/` directory.
+
.. Create a dedicated `sudoers` file for the user:
+
----
$ sudo visudo -f /etc/sudoers.d/<username>
----
+
.. Add the following line to the file, replacing `<username>` with the username you created:
+
----
<username> ALL=(ALL) NOPASSWD: ALL
----
+
.. Save and exit the file.
