:_mod-docs-content-type: PROCEDURE

[id="gw-configure-auth-details"]

= Configuring authentication details

Different authenticator plugins require different types of information. See the respective sections in xref:gw-config-authentication-type[Configuring an authentication type] for the required details.

For all authentication types you can enter a *Name*, *Additional Authenticator Fields* and *Create Objects*. 

.Procedure

. Enter a unique *Name* for the authenticator. The name is required, must be unique across all authenticators, and must not be longer than 512 characters. This becomes the unique identifier generated for the authenticator. 
+
[NOTE]
====
Changing the name does not update the unique identifier of the authenticator. For example, if you create an authenticator with the name “My Authenticator” and later change it to “My LDAP Authenticator” you will not be able to create another authenticator with the name “My Authenticator” because the unique identifier is still in use.
====
+
. Use the *Additional Authenticator Fields* to send arbitrary data back to the libraries behind the authenticators. This is an advanced feature and any values provided in this field are not validated.
+
[NOTE]
====
Values defined in this field override the dedicated fields provided in the UI. For example, if you enter a URL in a dedicated field on this page and then add a URL entry into the Additional Authentication Fields, the URL defined in Additional Authentication Fields overrides the definition in the dedicated field.
====
+
. Enable or disable *Enabled* to specify if the authenticator should be enabled or disabled. If enabled, users are able to login from the authenticator. If disabled, users will not be allowed to login from the authenticator.
. Enable or disable *Create Object* to specify whether the authenticator should create teams and organizations in the system when a user logs in.
+
Enabled:: Teams and organizations defined in the authenticator maps are created and the users added to them.
Disabled:: Organizations and teams defined in the authenticator maps will not be created automatically in the system. However, if they already exist (i.e. created by a superuser), users who trigger the maps are granted access to them.
+
. Enable or disable *Remove Users*. If enabled, any access previously granted to a user is removed when they authenticate from this source. If disabled, permissions are only added or removed from the user based on the results of this authenticator's authenticator mappings.
+
For example, assume a user has been granted the `is_superuser` permission in the system. And that user will log into an authenticator whose maps will not formulate an opinion as to whether or not the user should be a superuser.
If *Remove Users* is enabled, the `is_superuser` permission will be removed from the user, the authenticator maps will not have an opinion as to whether it should be there or not so, after login the user will not have the `is_superuser` permission.
+
If *Remove Users* is disabled, the `is_superuser` permission _will not_ be removed from the user. The authenticator maps will not have an opinion as to whether it should be there or not so after login the user _will_ have the `is_superuser` permission.
+
. Click btn:[Create Authentication Method]. 
. Select the *Mapping* tab.
. Click btn:[Create mapping] and proceed to to xref:gw-define-rules-triggers[Define authentication mapping rules and triggers].