[id="proc-install-aap-operator"]

.Procedure
. Log in to {OCP}.
. Navigate to menu:Operators[OperatorHub].
. Search for the {PlatformName} operator and click btn:[Install].
. Select an *Update Channel*:
+
* *stable-2.x*: installs a namespace-scoped operator, which limits deployments of {HubName} and {ControllerName} instances to the namespace the operator is installed in. This is suitable for most cases. The stable-2.x channel does not require administrator privileges and utilizes fewer resources because it only monitors a single namespace.
* *stable-2.x-cluster-scoped*: deploys {HubName} and {ControllerName} across multiple namespaces in the cluster and requires administrator privileges for all namespaces in the cluster.
. Select *Installation Mode*, *Installed Namespace*, and *Approval Strategy*.
. Click btn:[Install].

The installation process begins. When installation finishes, a modal appears notifying you that the {OperatorPlatformNameShort} is installed in the specified namespace.

.Verification

* Click btn:[View Operator] to view your newly installed {OperatorPlatformNameShort} and verify the following operator custom resources are present:

[cols="a,a,a,a"]
|===
|Automation Controller  | Automation hub |Event-Driven Ansible (EDA) |Ansible Lightspeed

|

* Automation Controller
* Automation Controller Backup
* Automation Controller Restore
* Automation Controller Mesh Ingress

|

* Automation Hub
* Automation Hub Backup
* Automation Hub Restore

|

* EDA
* EDA Backup
* EDA Restore

| 

* Ansible Lightspeed

|===


[IMPORTANT]
====
You can only install a single instance of the {OperatorPlatformNameShort} into a single namespace. 
Installing multiple instances in the same namespace can lead to improper operation for both operator instances. 
====
