:_mod-docs-content-type: PROCEDURE

[id="rpm-troubleshoot-generating-logs"]

= Gathering {PlatformNameShort} logs

[role="_abstract"]
Gather configuration, diagnostic, and troubleshooting data from all nodes in your {PlatformNameShort} environment by running the setup script with the `-s` flag. This crucial procedure generates an sos report, which contains the detailed diagnostic information Red Hat Technical Support engineers require to analyze and resolve service requests efficiently.

.Procedure

. Access the installation program folder with the inventory file and run the installation program setup script the following command:
+
`$ ./setup.sh -s`
+
With this command, you can connect to each node present in the inventory, install the `sos` tool, and generate new logs.
+
[NOTE]
====
If you are running the setup as a non-root user with sudo privileges, you can use the following command:
----
$ ANSIBLE_BECOME_METHOD='sudo'
ANSIBLE_BECOME=True ./setup.sh -s
---- 
====

. _Optional_: If required, change the location of the `sos` report files.
+
The `sos` report files are copied to the `/tmp` folder for the current server. To change the location, specify the new location by using the following command:
+
----
$ ./setup.sh -e 'target_sos_directory=/path/to/files' -s
----
+
Where `target_sos_directory=/path/to/files` is used to specify the destination directory where the `sos` report will be saved. In this case, the `sos` report is stored in the directory `/path/to/files`.

. Gather the files described on the playbook output and share with the support engineer or directly upload the `sos` report to Red Hat. 
+
To create an `sos` report with additional information or directly upload the data to Red Hat, use the following command:
+
----
$ ./setup.sh -e 'case_number=0000000' -e 'clean=true' -e 'upload=true' -s
----
+
.Parameter Reference Table
[%header, cols="a,a,a"]
[%autowidth]
|===
|Parameter |Description |Default value

|`case_number`
| Specifies the support case number that you want.
| -

|`clean`
| Obfuscates sensitive data that might be present on the `sos` report.
| `false`

|`upload`
| Automatically uploads the `sos` report data to Red Hat.
| `false`
|===

.Additional resources
* link:https://access.redhat.com/solutions/3592[KCS article:What is an sos report and how to create one in {RHEL}?] 
