:_mod-docs-content-type: PROCEDURE

[id="gw-keycloak-authentication"]

= Configuring keycloak authentication

You can configure {PlatformNameShort} to integrate Keycloak to manage user authentication.

[NOTE]
====
When using this authenticator some specific setup in your Keycloak instance is required. Refer to the link:https://python-social-auth.readthedocs.io/en/latest/backends/keycloak.html[Python Keycloak reference] for more details.
====

.Procedure

. From the navigation panel, select {MenuAMAuthentication}.
. Click btn:[Create authentication].
. Select *Keycloak* from the *Authentication type* list and click btn:[Next].
. Enter a *Name* for this keycloak configuration. The configuration name is required, must be unique across all authenticators, and must not be longer than 512 characters. 

include::snippets/snip-gw-authentication-auto-migrate.adoc[]

. Enter the location where the user's token can be retrieved in the *Keycloak Access Token URL* field.
. Optional: Enter the redirect location the user is taken to during the login flow in the *Keycloak Provider URL* field. 
. Enter the Client ID from your Keycloak installation in the *Keycloak OIDC Key* field.
. Enter the RS256 public key provided by your Keycloak realm in the *Keycloak Public Key* field. 
. Enter the OIDC secret (Client Secret) from your Keycloak installation in the *Keycloak OIDC Secret* field.
+
include::snippets/snip-gw-authentication-additional-auth-fields.adoc[]
+
include::snippets/snip-gw-authentication-common-checkboxes.adoc[]
+
. Click btn:[Next].

[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-authentication-next-steps.adoc[]

.Troubleshooting
If you receive an `jwt.exceptions.InvalidAudienceError: Audience doesn't match` error, you must re-enable the audience by doing the following:

. From the navigation for your Keycloak configuration, select menu:Client scopes[_YOUR-CLIENT-ID-dedicated_ > Add mapper > Audience].
. Pick a name for the mapper.
. Select the *Client ID* corresponding to your client in `Included Client Audience`. 

