[id="proc-RPM-install-eda-controller"]

= Installing {EDAcontroller} 1.1 and configuring {ControllerName} 4.4 or 4.5

Perform a new {PlatformNameShort} 2.5 RPM-based installation of {EDAcontroller} 1.1 and configure it to work with an existing {PlatformNameShort} 2.4 installation of {ControllerName} 4.4 or 4.5.

.Prerequisites

* An existing RPM-based installation of {PlatformNameShort} 2.4 with {ControllerName} version 4.4 or 4.5.

.Procedure

. Follow the steps provided in link:{BaseURL}/red_hat_ansible_automation_platform/2.5/html-single/rpm_installation/index[Installing on virtual machines] until the section link:{BaseURL}/red_hat_ansible_automation_platform/2.5/html-single/rpm_installation/assembly-platform-install-scenario#assembly-platform-install-scenario[Installing Red Hat Ansible Automation Platform] and ensure you download the {PlatformNameShort} 2.5 version of the RPM-based installer.
. Use the following example to populate the inventory file to deploy a new single instance of {EDAcontroller} 1.1:
+
[subs="+attributes"]
----
# This is the {PlatformNameShort} mixed enterprise installer inventory file
# Consult the docs if you are unsure what to add
# For all optional variables consult the Red Hat documentation:
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation

# This section is for your platform gateway hosts
# -----------------------------------------------------
[automationgateway]
gateway1.example.org
gateway2.example.org
gateway3.example.org

# This section is for your {EDAcontroller} hosts
# -----------------------------------------------------
[automationedacontroller]
eda1.example.org
eda2.example.org
eda3.example.org

[redis]
gateway1.example.org
gateway2.example.org
gateway3.example.org
eda1.example.org
eda2.example.org
eda3.example.org

[all:vars]
# Common variables
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/appendix-inventory-files-vars#ref-general-inventory-variables
# -----------------------------------------------------
registry_username=<your RHN username>
registry_password=<your RHN password>

# Platform gateway
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/appendix-inventory-files-vars#ref-gateway-variables
# -----------------------------------------------------
automationgateway_admin_password=<set your own>
automationgateway_pg_host=<set your own>
automationgateway_pg_database=<set your own>
automationgateway_pg_username=<set your own>
automationgateway_pg_password=<set your own>

# {EDAcontroller}
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/appendix-inventory-files-vars#event-driven-ansible-controller
# -----------------------------------------------------
automationedacontroller_admin_password=<set your own>
automationedacontroller_pg_host=<set your own>
automationedacontroller_pg_database=<set your own>
automationedacontroller_pg_username=<set your own>
automationedacontroller_pg_password=<set your own>
----

+
[NOTE]
====
Keep controller out of the inventory file. 
Ensure that `[automationcontroller]` is an empty group. 								
Only add an {EDAName} 2.5 server. 
Do not add an {EDAName} 2.4 server since there is no upgrade option available
====
+
. Continue with the steps in link:{BaseURL}/red_hat_ansible_automation_platform/2.5/html-single/rpm_installation/assembly-platform-install-scenario#assembly-platform-install-scenario[Installing Red Hat Ansible Automation Platform].
