:_mod-docs-content-type: PROCEDURE



[id="proc-choosing-obtaining-installer_{context}"]


= Choosing and obtaining a {PlatformName} installer

[role="_abstract"]
Choose the {PlatformName} installer you need based on your {RHEL} environment internet connectivity. Review the following scenarios and decide on which {PlatformName} installer meets your needs.

[NOTE]
====
A valid Red Hat customer account is required to access {PlatformName} installer downloads on the Red Hat Customer Portal.
====

Choose the {PlatformName} installer if your {RHEL} environment is connected to the internet. Installing with internet access retrieves the latest required repositories, packages, and dependencies. Choose one of the following ways to set up your {PlatformNameShort} installer.

.Procedure

* *Tarball install*
+ 
. Navigate to the link:{PlatformDownloadUrl}[{PlatformName} download] page.
. In the *Product software* tab, click btn:[Download Now] for the *Ansible Automation Platform <latest-version> Setup*.
. Extract the files:
+
-----
$ tar xvzf ansible-automation-platform-setup-<latest-version>.tar.gz
-----

* *RPM install*

. Install the {PlatformNameShort} Installer Package.
+
v.{PlatformVers} for RHEL 9 for x86-64:
+
----
$ sudo dnf install --enablerepo=ansible-automation-platform-2.6-for-rhel-9-x86_64-rpms ansible-automation-platform-installer
----
+
[NOTE]
====
`dnf install` enables the repo as the repo is disabled by default.
====
+
When you use the RPM installer, the files are placed under the `/opt/ansible-automation-platform/installer` directory.