:_mod-docs-content-type: PROCEDURE

[id="controller-set-up-generic-oidc"]

= Configuring generic OIDC authentication

[role="_abstract"]

OpenID Connect (OIDC) uses the OAuth 2.0 framework. It enables third-party applications to verify the identity and obtain basic end-user information. The main difference between OIDC and SAML is that SAML has a service provider (SP)-to-IdP trust relationship, whereas OIDC establishes the trust with the channel (HTTPS) that is used to obtain the security token. To obtain the credentials needed to set up OIDC with {PlatformNameShort}, see the documentation from the IdP of your choice that has OIDC support.

.Procedure

. From the navigation panel, select {MenuAMAuthentication}.
. Click btn:[Create authentication].
. Enter a *Name* for this authentication configuration. 
. Select *Generic OIDC* from the *Authentication type* list. The *Authentication details* section automatically updates to show the fields relevant to the selected authentication type.
+
//include::snippets/snip-gw-authentication-auto-migrate.adoc[]
+
. Enter the following information:
+
* *OIDC Provider URL*: The URL for your OIDC provider.
* *OIDC Key*: The client ID from your third-party IdP.
* *OIDC Secret*: The client secret from your IdP.
+
. Optional: Select the HTTP method to be used when requesting an access token from the *Access Token Method* list. The default method is *POST*.
. Optionally enter information for the following fields using the tooltip provided for instructions and required format:
+
* *Access Token Method* - The default method is *POST*.
* *Access Token URL*
* *Access Token Method*
* *Authorization URL*
* *Callback URL* - The OIDC *Callback URL* field registers the service as a service provider (SP) with each OIDC provider you have configured. 
Leave this field blank. 
After you save this authentication method, it is auto generated. 
Configure your IdP to allow redirects to this URL as part of the authentication flow.
* *ID Key*
* *ID Token Issuer*
* *JWKS URI*
* *OIDC Public Key*
* *Revoke Token Method* - The default method is *GET*.
* *Revoke Token URL*
* *Response Type*
* *Token Endpoint Auth Method*
* *Userinfo URL*
* *Username Key*
+
. Use the *Verify OIDC Provider Certificate* to enable or disable the OIDC provider SSL/TLS certificate verification.
. Use the *Redirect* State to enable or disable the state parameter in the redirect URI. 
Enable this to prevent Cross Site Request Forgery (CSRF) attacks.
+
include::snippets/snip-gw-authentication-additional-auth-fields.adoc[]
+
include::snippets/snip-gw-authentication-common-checkboxes.adoc[]
+
. Click btn:[Create Authentication Method].

[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-authentication-next-steps.adoc[]

// [ddacosta - removed as no longer true in 2.5.]
// [NOTE]
// ====
// Team and organization mappings for OIDC are currently not supported. The OIDC adapter does authentication only and not authorization. It is only capable of authenticating whether this user is who they say they are. It does not authorize what this user is enabled to do. Configuring generic OIDC creates the UserID appended with an ID or key to differentiate the same user ID originating from two different sources and therefore, considered different users. So you get an ID of just the user name and the second is the username-<random number>.
// ====
