:_mod-docs-content-type: PROCEDURE
[id="ref-controller-user-roles"]

= Adding roles for a user

You can grant users granular access to specific resources such as inventories, projects, or job templates by assigning users roles.

You can view and manage roles that were assigned directly to a user by an administrator in the user's Roles tab.

You can view roles that a user inherited from a team assignment in the *View indirectly assigned roles* link in the page banner. 
You cannot directly manage an indirectly-assigned role. You can only manage indirectly-assigned roles by editing the team's role assignments, or by removing the user from the team [LINK]. 

[NOTE]
====
Users cannot be assigned to an organization by adding roles, nor can you assign users organization roles from this screen. Refer to the steps provided in link:{URLCentralAuth}/gw-managing-access#proc-controller-add-organization-user[Adding a user to an organization] for detailed instructions on assigning a user to an organization.
====

Roles are labeled with their associated {PlatformNameShort} component and function. These components align with the {PlatformNameShort} 

.Procedure
. From the navigation panel, select {MenuAMUsers}.
. From the *Users* list view, click the user to which you want to add roles.
. Select the *Roles* tab to display the set of roles assigned to this user. These provide the ability to read, modify, and administer resources.
. To add new roles, click btn:[Add roles].
+
include::snippets/snip-gw-roles-note-multiple-components.adoc[]
+
. Select a Resource type and click btn:[Next]. 
. Select the resources that will receive new roles and click btn:[Next].
. Select the roles that will be applied to the resources and click btn:[Next].
. Review the settings and click btn:[Finish].
+
The Add roles dialog displays indicating whether the role assignments were successfully applied. Click btn:[Close] to close the dialog.
