:_mod-docs-content-type: PROCEDURE

[id="proc-gs-auto-dev-about-inv"]

= About inventories

[role="_abstract"]
An inventory is a file listing the collection of hosts managed by {PlatformNameShort}. 
Organizations are assigned to inventories, while permissions to launch playbooks against inventories are controlled at the user or team level.

You can find inventories in the UI by navigating to {MenuInfrastructureInventories}. The Inventories window displays a list of the inventories that are currently available. You can sort the inventory list by name and search by inventory type, organization, description, inventory creators or modifiers, or additional criteria.
Use the following procedure to create a new inventory.

.Procedure

. From the navigation panel, select {MenuInfrastructureInventories}. The *Inventories* view displays a list of the inventories currently available. 
. Click btn:[Create inventory], and from the list menu select the type of inventory you want to create. 
. Enter the appropriate details into the following fields: 
* *Name*: Enter a name for the inventory.
* Optional: *Description*: Enter a description.
* *Organization*: Choose among the available organizations. 
* Only applicable to Smart Inventories: *Smart Host Filter*:  Filters are similar to tags in that tags are used to filter certain hosts that contain those names. Therefore, to populate this field, specify a tag that contains the hosts you want, not the hosts themselves. Filters are case-sensitive. For more information, see link:{URLControllerUserGuide}/controller-inventories#ref-controller-smart-host-filter[Smart host filters] in the {TitleControllerUserGuide} guide.
* *Instance groups*: Select the instance group or groups for this inventory to run on. If the list is extensive, use the search to narrow the options. You can select multiple instance groups and sort them in the order that you want them run.
* Optional: *Labels*: Add labels that describe this inventory, so they can be used to group and filter inventories and jobs.
* Only applicable to constructed inventories: *Input inventories*: Specify the source inventories to include in this constructed inventory. Empty groups from input inventories are copied into the constructed inventory.
* Optional and only applicable to constructed inventories: *Cache timeout (seconds)*:Set the length of time you want the cache plugin data to timeout.
* Only applicable to constructed inventories: *Verbosity*: Control the level of output that Ansible produces as the playbook executes related to inventory sources associated with constructed inventories. Select the verbosity from Normal to various Verbose or Debug settings. This only appears in the "details" report view.
** Verbose logging includes the output of all commands. 
** Debug logging is exceedingly verbose and includes information on SSH operations that can be useful in certain support instances. Most users do not need to see debug mode output.
* Only applicable to constructed inventories: *Limit*: Restricts the number of returned hosts for the inventory source associated with the constructed inventory. You can paste a group name into the limit field to only include hosts in that group. For more information, see the *Source variables* setting.
* Only applicable to standard inventories: *Options*: Check the box next to *Prevent instance group fallback* to enable only the instance groups listed in the *Instance groups* field to execute the job. If unchecked, all available instances in the execution pool will be used based on the hierarchy described in link:{URLControllerAdminGuide}/controller-clustering#controller-cluster-job-runs[Control where a job runs] in the {TitleControllerAdminGuide} guide. Click the tooltip for more information.
+
NOTE: Set the `prevent_instance_group_fallback` option for smart inventories through the API. 
+
* *Variables* (*Source variables* for constructed inventories):
** *Variables*: Variable definitions and values to apply to all hosts in this inventory. Enter variables using either JSON or YAML syntax. Use the radio button to toggle between the two.
** *Source variables* for constructed inventories are used to configure the constructed inventory plugin. Source variables create groups under the `groups` data key. The variable accepts Jinja2 template syntax, renders it for every host, makes a `true` or `false` evaluation, and includes the host in the group (from the key of the entry) if the result is `true`. 
. Click btn:[Create inventory].

.Next steps
After creating the new inventory, you can proceed with configuring permissions, groups, hosts, sources, and viewing completed jobs, if applicable to the type of inventory.