:_mod-docs-content-type: PROCEDURE

[id="proc-operator-config-csrf-gateway_{context}"]

= Configuring your CSRF settings for your {Gateway} Operator ingress

[role="_abstract"]

The {OperatorPlatformName} creates Openshift Routes and configures your Cross-site request forgery (CSRF) settings automatically. When using external ingress, you must configure your CSRF on the ingress to allow for cross-site requests. You can configure your {Gateway} operator ingress under *Advanced configuration*.

.Procedure

. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *Ansible Automation Platform* tab.
. For new instances, click btn:[Create AnsibleAutomationPlatform].
.. For existing instances, you can edit the YAML view by clicking the {MoreActionsIcon} icon and then btn:[Edit AnsibleAutomationPlatform].
. Click btn:[Advanced Configuration].
. Under *Ingres annotations*, enter any annotations to add to the ingress. 
. Under *Ingress TLS secret*, click the drop-down list and select a secret from the list.
. Under *YAML view* paste in the following code:
+
----
spec:
  extra_settings:
    - setting: CSRF_TRUSTED_ORIGINS
      value:
        - https://my-aap-domain.com
----
+
. After you have configured your {Gateway}, click btn:[Create] at the bottom of the form view (Or btn:[Save] in the case of editing existing instances). 

.Verification 

{OCP} creates the pods. This may take a few minutes. You can view the progress by navigating to menu:Workloads[Pods] and locating the newly created instance. Verify that the following operator pods provided by the {OperatorPlatformName} installation from {Gateway} are running:

[cols="a,a,a,a,a"]
|===
| Operator manager controllers pods | Automation controller pods |Automation hub pods |Event-Driven Ansible pods |Platform gateway pods

| The operator manager controllers for each of the four operators, include the following:

* automation-controller-operator-controller-manager
* automation-hub-operator-controller-manager
* resource-operator-controller-manager
* aap-gateway-operator-controller-manager 
* ansible-lightspeed-operator-controller-manager
* eda-server-operator-controller-manager

| After deploying {ControllerName}, you can see the addition of the following pods:

* {ControllerNameStart} web 
* {ControllerNameStart} task 
* Mesh ingress 
* {ControllerNameStart} postgres 

| After deploying {HubName}, you can see the addition of the following pods:

* {HubNameStart} web
* {HubNameStart} task
* {HubNameStart} API
* {HubNameStart} worker

| After deploying EDA, you can see the addition of the following pods:

* EDA API 
* EDA Activation 
* EDA worker 
* EDA stream 
* EDA Scheduler

| After deploying {Gateway}, you can see the addition of the following pods:


* {Gateway}
* {Gateway} redis

|===

[NOTE]
====
A missing pod can indicate the need for a pull secret. Pull secrets are required for protected or private image registries. See link:https://docs.openshift.com/container-platform/4.11/openshift_images/managing_images/using-image-pull-secrets.html[Using image pull secrets] for more information. You can diagnose this issue further by running `oc describe pod <pod-name>` to see if there is an ImagePullBackOff error on that pod.
====



