:_mod-docs-content-type: PROCEDURE

[id="proc-configuring-controller-route-options_{context}"]

= Configure {ControllerName} route options

[role="_abstract"]

The {PlatformName} operator installation form allows you to further configure your {ControllerName} operator route options under *Advanced configuration*.

.Procedure
. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *Automation Controller* tab. 
. For new instances, click btn:[Create AutomationController].
.. For existing instances, you can edit the YAML view by clicking the {MoreActionsIcon} icon and then btn:[Edit AutomationController].
. Click btn:[Advanced configuration].
. Under *Ingress type*, click the drop-down menu and select *Route*.
. Under *Route DNS host*, enter a common host name that the route answers to.
. Under *Route TLS termination mechanism*, click the drop-down menu and select *Edge* or *Passthrough*. For most instances *Edge* should be selected.
. Under *Route TLS credential secret*, click the drop-down menu and select a secret from the list.
. Under *Enable persistence for __/var/lib/projects__ directory* select either true or false by moving the slider.
+
[NOTE]
====
After you have configured your route you can customize your hostname by adding `route_host:` to the YAML for that {ControllerName} instance.
====
