:_mod-docs-content-type: PROCEDURE

[id="preparing-the-rhel-host-for-containerized-installation"]

= Preparing the {RHEL} host for containerized installation

[role="_abstract"]
Containerized {PlatformNameShort} runs the component services as Podman based containers on top of a {RHEL} host. Prepare the {RHEL} host to ensure a successful installation. 

.Procedure

. Log in to the {RHEL} host as your non-root user.
+
. Ensure that the hostname of your host uses a fully qualified domain name (FQDN).
.. To check the hostname of your host, run the following command:
+
----
hostname -f
----
+
Example output:
+
----
aap.example.org
----
.. If the hostname is not a FQDN, you can set it with the following command:
+
----
$ sudo hostnamectl set-hostname <your_hostname>
----
+
. Register your {RHEL} host with `subscription-manager`:
+
----
$ sudo subscription-manager register
----
+

. Verify that only the BaseOS and AppStream repositories are enabled on the host:
+
----
$ sudo dnf repolist
----
+
Example output for RHEL 9:
+
----
Updating Subscription Management repositories.
repo id                                                    repo name
rhel-9-for-x86_64-appstream-rpms                           Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
rhel-9-for-x86_64-baseos-rpms                              Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
----
+
Example output for RHEL 10:
+
----
Updating Subscription Management repositories.
repo id                                                    repo name
rhel-10-for-x86_64-appstream-rpms                          Red Hat Enterprise Linux 10 for x86_64 - AppStream (RPMs)
rhel-10-for-x86_64-baseos-rpms                             Red Hat Enterprise Linux 10 for x86_64 - BaseOS (RPMs)
----
** For disconnected installations, follow the steps in link:{URLContainerizedInstall}/aap-containerized-disconnected-installation#obtaining-and-configuring-rpm-dependencies[Obtaining and configuring RPM source dependencies] to access these repositories.

. Ensure the host can resolve host names and IP addresses using DNS. This is essential to ensure services can talk to one another.

. Install `ansible-core`:
+
----
$ sudo dnf install -y ansible-core
----
+
. Optional: Install additional utilities that are useful for troubleshooting purposes, for example `wget`, `git-core`, `rsync`, and `vim`:
+
----
$ sudo dnf install -y wget git-core rsync vim
----

. Optional: To have the installation program automatically pick up and apply your {PlatformNameShort} subscription manifest license, follow the steps in link:{URLContainerizedInstall}/assembly-gateway-licensing#assembly-aap-obtain-manifest-files[Obtaining a manifest file].

[role="_additional-resources"]
.Additional resources
* link:{URLContainerizedInstall}/assembly-gateway-licensing#proc-attaching-subscriptions[Attaching your {PlatformName} Subscription]
* link:{BaseURL}/red_hat_enterprise_linux/9/html/managing_networking_infrastructure_services/assembly_setting-up-an-unbound-dns-server_networking-infrastructure-services[Setting up an unbound DNS server]
* link:{BaseURL}/red_hat_enterprise_linux/9/html/managing_networking_infrastructure_services/assembly_setting-up-and-configuring-a-bind-dns-server_networking-infrastructure-services[Setting up and configuring a BIND DNS server]
//Commenting out as no downstream alternative [AAP-57435]
//* link:https://docs.ansible.com/projects/ansible/latest/[Ansible Core Documentation]
