:_mod-docs-content-type: PROCEDURE

[id="proc-controller-user-permissions"]

= Assign roles to a team

[role="_abstract"]

You can grant a team granular access to specific resources such as inventories, projects, and job templates by assigning the team roles associated with those particular resources.
You can also set permissions at the level of the organization from the Organizations view.

[NOTE]
====
Teams cannot be assigned to an organization through role assignment, nor can teams be assigned organization roles from the Teams view. Refer to the steps provided in link:{URLCentralAuth}/gw-managing-access#proc-gw-add-team-organization[Adding a team to an organization] for detailed instructions on assigning a team to an organization.
====

.Procedure
. From the navigation panel, select {MenuAMTeams}.
. Select the team *Name* to which you want to add roles.
. Select the *Roles* tab and click btn:[Add roles].
+
include::snippets/snip-gw-roles-note-multiple-components.adoc[]
+
. Select a *Resource type* and click btn:[Next]. 
. Select the resources that you want to give the team role-based access to and click btn:[Next].
. Select the roles to apply to the resources and click btn:[Next].
+
[TIP]

====

If you are selecting more than one role in this step, consider link:{URLCentralAuth}/assembly-gw-roles#proc-gw-create-roles[creating a custom role] that includes all the permissions for this resource type to give the team the correct access.
====
+
. Review the settings and click btn:[Finish].
. The *Add roles* dialog displays indicating whether the role assignments were successfully applied. Click btn:[Close] to close the dialog.
