:_mod-docs-content-type: PROCEDURE
[id="updating-containerized-ansible-automation-platform"]

= Upgrading containerized {PlatformNameShort}

[role="_abstract"]
Perform an upgrade of containerized {PlatformNameShort}. 

.Prerequisites

* You have reviewed the release notes for the associated patch release. For more information, see link:{URLReleaseNotes}[{PlatformNameShort} {TitleReleaseNotes}].
* You have a backup of your {PlatformNameShort} deployment. For more information, see link:{URLContainerizedInstall}/maintaining-containerized-aap#backing-up-containerized-ansible-automation-platform[Backing up container-based {PlatformNameShort}].

.Procedure

. Log in to the {RHEL} host as your dedicated non-root user.

. Follow the steps in link:{URLContainerizedInstall}/preparing-containerized-installation#downloading-ansible-automation-platform[Downloading {PlatformNameShort}] to download the latest version of containerized {PlatformNameShort}.

. Copy the downloaded installation program to your {RHEL} Host.

. Edit the `inventory` file to match your required configuration. You can keep the same parameters from your existing {PlatformNameShort} deployment or you can change the parameters to match any modifications to your environment.

. Run the `install` playbook:
+
----
$ ansible-playbook -i inventory ansible.containerized_installer.install
----
+
* If your privilege escalation requires a password to be entered, append `-K` to the command. You will then be prompted for the `BECOME` password.
* You can use increasing verbosity, up to 4 v’s (`-vvvv`) to see the details of the installation process. However it is important to note that this can significantly increase installation time, so it is recommended that you use it only as needed or requested by Red Hat support.
