:_newdoc-version: 2.18.4
:_template-generated: 2025-05-08
:_mod-docs-content-type: PROCEDURE

[id="configure-enforcement-points_{context}"]
= Configuring enforcement points

[role="_abstract"]
After you have set up your {PlatformNameShort} instance to communicate with the OPA server, you can set up enforcement points where you want the policy to be applied. 

.Procedure
* You can associate a policy with a job template, an inventory, or an organization. Enforcement then occurs in the following ways:

Organization:: Jobs launched from a template owned by an organization will fail if the policy is violated. This configuration provides broad control over automation within organizational boundaries.
Inventory:: Jobs that use an inventory associated with a policy fail if the policy is violated. This configuration allows you to control access to specific infrastructure resources. 
Job template:: Jobs launched from a template associated with a policy fail if the job violates the associated policy. This configuration provides granular control over specific automation tasks. 
+
[NOTE]

====

If you do not associate a policy with a resource, policy evaluation will not occur when you run the related job.

====