:_mod-docs-content-type: PROCEDURE

[id="gw-local-authentication"]

= Configure local authentication

[role="_abstract"]

As a platform administrator, you can configure local system authentication. With local authentication, users and their passwords are checked against local system accounts.

[NOTE]
====
A local authenticator is automatically created by the {PlatformNameShort} installation process, and is configured with the specified admin credentials in the inventory file before installation. After successful installation, you can log in to the {PlatformNameShort} using those credentials. 
====

.Procedure

. From the navigation panel, select {MenuAMAuthentication}.
. Click btn:[Create authentication].
. Enter a *Name* for this Local configuration. The configuration name is required, must be unique across all authenticators, and must not be longer than 512 characters.
. Select *Local* from the *Authentication type* list. 
+
//include::snippets/snip-gw-authentication-auto-migrate.adoc[]
+
include::snippets/snip-gw-authentication-additional-auth-fields.adoc[]
+
include::snippets/snip-gw-authentication-common-checkboxes.adoc[]
+
. Click btn:[Next].

[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-authentication-next-steps.adoc[]