:_mod-docs-content-type: PROCEDURE

[id="downloading-ansible-automation-platform"]

= Download {PlatformNameShort}

[role="_abstract"]
Choose the installation program you need based on your {RHEL} environment internet connectivity and download the installation program to your {RHEL} host.

.Prerequisites
* You have logged in to the {RHEL} host as your non-root user.

.Procedure

. Download the latest version of containerized {PlatformNameShort} from the link:{PlatformDownloadUrl}[{PlatformNameShort} download page]. 
.. For online installations: *{PlatformNameShort} {PlatformVers} Containerized Setup*
.. For offline or bundled installations: *{PlatformNameShort} {PlatformVers} Containerized Setup Bundle*

. Copy the installation program `.tar.gz` file and the optional manifest `.zip` file onto your {RHEL} host.
+
Use the `scp` command to securely copy the files. The basic syntax for `scp` is:
+
----
scp [options] <path_to_source_file> <path_to_destination>
----
+
For example, use the following `scp` command to copy the installation program `.tar.gz` file to an AWS EC2 instance with a private key (replace the placeholder `<>` values with your actual information):
+
----
scp -i <path_to_private_key> ansible-automation-platform-containerized-setup-<version_number>.tar.gz ec2-user@<remote_host_ip_or_hostname>:<path_to_destination>
----
+
. Decide where you want the installation program to reside on the file system. This is your installation directory.
.. The installation creates installation-related files under this location and requires at least 15 GB for the initial installation.

. Unpack the installation program `.tar.gz` file into your installation directory, and go to the unpacked directory. 
+
.. To unpack the online installer:
+
----
$ tar xfvz ansible-automation-platform-containerized-setup-<version_number>.tar.gz
----
+
.. To unpack the offline or bundled installer:
+
----
$ tar xfvz ansible-automation-platform-containerized-setup-bundle-<version_number>-<arch_name>.tar.gz
----

[role="_additional-resources"]
.Additional resources

* link:https://man7.org/linux/man-pages/man1/scp.1.html[scp(1) - Linux manual page]
