[id="proc-controller-configure-analytics"]

= Configuring {Analytics}

When you imported your license for the first time, you were automatically opted in for the collection of data that powers {Analytics}, a cloud service that is part of the {PlatformNameShort} subscription.

.Prerequisites

* A service account created with the Analytics Administrator viewer role in console.redhat.com.
For more information, see link:https://docs.redhat.com/en/documentation/red_hat_hybrid_cloud_console/1-latest/html/creating_and_managing_service_accounts/proc-ciam-svc-acct-overview-creating-service-acct#proc-ciam-svc-acct-create-creating-service-acct[Creating a service account].

.Procedure

. From the navigation panel, select menu:{MenuAEAdminSettings}[System].
. Click btn:[Edit].
. Toggle the *Gather data for {Analytics}* switch and enter your Red Hat customer credentials:
+
* *Red Hat Client ID for Analytics*: Enter the client ID you received when you created your service account to send data to {Analytics}.
* *Red Hat Client Secret for Analytics*: Enter the client secret you received when you created your service account to send data to {Analytics}.
* *Red Hat Client ID for Subscriptions*: Enter the client ID you received when you created your service account to retrieve subscription and content information.
* *Red Hat Client Secret for Subscriptions*: Enter the client secret you received when you created your service account to retrieve subscription and content information.
* *Last gathered entries from the data collection service of Automation Analytics*: 
* *Automation Analytics Gather Interval*: Interval (in seconds) between data gathering.
+
. Click btn:[Save].
