:_mod-docs-content-type: PROCEDURE


[id="proc-aap-activate-with-manifest"]

= Activate with a manifest file

[role="_abstract"]

If you have a subscriptions manifest, you can upload the manifest file using the {PlatformName} interface. 

[NOTE]
====
You are opted in for {Analytics} by default when you activate the platform on first login. This helps Red Hat improve the product by delivering you a much better user experience. You can opt out after activating {PlatformNameShort} by taking the following steps: 

. From the navigation panel, select {MenuSetSystem}.
. Clear the *Gather data for {Analytics}* option.
. Click btn:[Save].
====

ifndef::controller-AG[]
.Prerequisites
You must have a Red Hat Subscription Manifest file exported from the Red Hat Customer Portal. For more information, see xref:assembly-aap-obtain-manifest-files[Obtaining a manifest file].

.Procedure

. Log in to {PlatformName}.
.. If you are not immediately taken to the subscription wizard, go to {MenuSetSubscription}.
. Select the *Subscription manifest* tab.
. Click btn:[Browse] and select your manifest file.
. Review the End User License Agreement and select *I agree to the End User License Agreement*.
. Click btn:[Finish].
+
[NOTE]
====
If the btn:[BROWSE] button is disabled on the subscription wizard page, clear the *USERNAME* and *PASSWORD* fields.
====

.Verification

After your subscription has been accepted, subscription details are displayed. A status of _Compliant_ indicates your subscription is in compliance with the number of hosts you have automated within your subscription count. Otherwise, your status shows as _Out of Compliance_, indicating you have exceeded the number of hosts in your subscription.
Other important information displayed include the following:

Hosts automated:: Host count automated by the job, which consumes the subscription count
Hosts imported:: Host count considering all inventory sources (does not impact hosts remaining)
Hosts remaining:: Total host count minus hosts automated

[role="_additional-resources"]
.Next steps
* You can return to the subscription wizard by selecting {MenuSetSubscription} from the navigation panel and clicking btn:[Edit subscription].

endif::controller-AG[]