:_mod-docs-content-type: PROCEDURE

[id="proc-controller-github-enterprise-team-settings"]

= Configuring GitHub enterprise team authentication

[role="_abstract"]

To set up social authentication for a GitHub enterprise team, you must obtain a GitHub Enterprise Organization URL, an Organization API URL, an Organization OAuth2 key and secret for a web application.

To obtain the URLs, see the link:https://docs.github.com/en/enterprise-server@3.1/rest/reference/enterprise-admin[GitHub Enterprise administration documentation].

To obtain the key and secret, you must first register your enterprise organization-owned application at `https://github.com/organizations/<yourorg>/settings/applications`.

The OAuth2 key (Client ID) and secret (Client Secret) are used to supply the required fields in the UI. To register the application, you must supply it with your webpage URL, which is the *Callback URL* shown in the Authenticator details for your authenticator configuration. See xref:gw-display-auth-details[Displaying authenticator details] for instructions on accessing this information.

Each key and secret must belong to a unique application and cannot be shared or reused between different authentication  backends.
The OAuth2key (Client ID) and secret (Client Secret) are used to supply the required fields in the UI.

.Procedure

. From the navigation panel, select {MenuAMAuthentication}.
. Click btn:[Create authentication].
. Enter a *Name* for this authentication configuration. 
. Select *GitHub enterprise team* from the *Authentication type* list. The *Authentication details* section automatically updates to show the fields relevant to the selected authentication type.
+
//include::snippets/snip-gw-authentication-auto-migrate.adoc[]
+
. When the application is registered, GitHub displays the *Client ID* and *Client Secret*:
+
.. Copy and paste the GitHub Client ID into the GitHub OAuth2 Key field. 
.. Copy and paste the GitHub Client Secret into the GitHub OAuth2 Secret field. 
+
. In the *Base URL* field, enter the hostname of the GitHub Enterprise instance, for example, `https://github.orgexample.com`.
. In the *Github OAuth2 Enterprise API URL* field, enter the API URL of the GitHub Enterprise instance, for example, `https://github.example.com/api/v3`.
. Enter the OAuth2 key (Client ID) from your GitHub developer application in the *GitHub OAuth2* team ID field.
+
include::snippets/snip-gw-authentication-additional-auth-fields.adoc[]
+
include::snippets/snip-gw-authentication-common-checkboxes.adoc[]
+
. Click btn:[Create Authentication Method].

include::snippets/snip-gw-authentication-verification.adoc[]

[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-authentication-next-steps.adoc[]
