:_mod-docs-content-type: PROCEDURE

// emurtoug removed this assembly from the Planning guide to avoid duplication of subscription content added to Access management and authentication

[id="proc-attaching-subscriptions"]

= Attach your {PlatformNameShort} subscription

[role="_abstract"]

You *must* have valid subscriptions on all nodes before installing {PlatformName}.

[NOTE]
====
Simple Content Access (SCA) is now the default subscription method for all Red Hat accounts. With SCA, you must register your systems to Red Hat Subscription Management (RHSM) or Satellite to access content. Traditional pool-based subscription attachment commands (such as `subscription-manager attach --pool` or `subscription-manager attach --auto`) are no longer required. For more information, see link:https://access.redhat.com/articles/simple-content-access[Simple Content Access].
====

.Procedure

. Register your system with Red Hat Subscription Management:
+
-----
$ sudo subscription-manager register --username <$INSERT_USERNAME_HERE> --password <$INSERT_PASSWORD_HERE>
-----
+
With Simple Content Access (SCA), registration is the only step required to access {PlatformNameShort} content.
+
[NOTE]
====
For accounts still using legacy subscription pools, you might have to manually attach subscriptions using the commands shown in the troubleshooting section.
====

.Verification

. Refresh the subscription information on your system:
+
-----
$ sudo subscription-manager refresh
-----

. Verify your registration:
+
-----
$ sudo subscription-manager identity
-----
+
This command displays your system identity, name, organization name, and organization ID, confirming successful registration.

.Troubleshooting

* For legacy accounts not using SCA, you might have to manually attach subscriptions:
+
-----
$ sudo subscription-manager list --available --all | grep -A 30 "Ansible Automation Platform"
-----
+
This command displays the subscription details including the Pool ID. Look for the `Pool ID:` line in the output.
+
Once you have identified the correct Pool ID, attach the subscription:
+
-----
$ sudo subscription-manager attach --pool=<pool_id>
-----
+
[NOTE]
====
Do not use MCT4022 as a `pool_id` as it can cause subscription attachment to fail.
====

ifndef::container-install[]
* For legacy accounts not using SCA, if you are unable to locate certain packages that came bundled with the {PlatformNameShort} installer, or if you are seeing a `_Repositories disabled by configuration_` message, use the following steps to identify and enable the required repository:

.. List available repositories:
+
-----
$ sudo subscription-manager repos --list | grep -i ansible-automation-platform
-----

.. Identify the repository name that matches your RHEL version, {PlatformNameShort} version, and architecture (for example, `ansible-automation-platform-{PlatformVers}-for-rhel-9-x86_64-rpms`).

.. Enable the repository:
+
-----
$ sudo subscription-manager repos --enable <repository_name>
-----
endif::container-install[]
