[id="proc-controller-add-organization-user"]

= Adding a user to an organization

You can provide a user with access to an organization by adding them to the organization and managing the roles associated with the user. To add a user to an organization, the user must already exist. For more information, see xref:proc-controller-creating-a-user[Creating a user]. 
To add roles for a user, the role must already exist. See xref:proc-gw-create-roles[Creating a role] for more information.

The following tab selections are available when adding users to an organization. When user accounts from the {ControllerName} organization have been migrated to {PlatformNameShort} 2.5 during the upgrade process, the *Automation Execution* tab shows content based on whether the users were added to the organization prior to migration.  

{PlatformNameShort}:: Reflects all users added to the organization at the platform level. From this tab, you can add users as organization members and, optionally provide specific organization level roles.

Automation Execution:: Reflects users that were added directly to the {ControllerName} organization prior to an upgrade and migration. From this tab, you can only view existing memberships in {ControllerName} and remove those memberships but not you can not add new memberships. 

New user memberships to an organization must be added at the platform level.

.Procedure
. From the navigation panel, select {MenuAMOrganizations}.
. From the *Organizations* list view, select the organization to which you want to add a user. 
. Click the *Users* tab to add users.
. Select the *{PlatformNameShort}* tab and click btn:[Add users] to add user access to the team, or select the *Automation Execution* tab to view or remove user access from the team.
. Select one or more users from the list by clicking the checkbox next to the name to add them as members.
. Click btn:[Next].
. Select the roles you want the selected user to have. Scroll down for a complete list of roles.
+
include::snippets/snip-gw-roles-note-multiple-components.adoc[]

+
. Click btn:[Next] to review the roles settings.
. Click btn:[Finish] to apply the roles to the selected users, and to add them as members. The *Add roles* dialog displays the updated roles assigned for each user.
+
[NOTE]
====
A user with associated roles retains them if they are reassigned to another organization.
====
+
. To remove a particular user from the organization, select *Remove user* from the *More actions {MoreActionsIcon}* list next to the user. This launches a confirmation dialog, asking you to confirm the removal.
. To manage roles for users in an organization, click the *{SettingsIcon}* icon next to the user and select *Manage roles*. 





