:_mod-docs-content-type: PROCEDURE

[id="edge-manager-config-git-cli"]

= Managing the device configuration from a Git repository on the CLI 

[role="_abstract"]

Integrate your device configuration files with standard Git workflows by defining a Repository resource using the CLI. 
This enables the {RedHatEdge} to automatically synchronize configuration file updates from the repository onto the device's file system.

.Procedure

. Create a file, for example `site-settings-repo.yaml`, that has the following definition for a `Repository` resource, named `site-settings`:

+
[source,yaml]
----
apiVersion: flightctl.io/v1alpha1
kind: Repository
metadata:
  name: site-settings
spec:
  type: git
  url: https://github.com/<your_org>/<your_repo>.git
----

. Create the `Repository` resource by running the following command:

+
[source,bash]
----
flightctl apply -f site-settings-repo.yaml
----

. Verify that the resource has been correctly created and is accessible by {RedHatEdge} running the following command:

+
[source,bash]
----
flightctl get repository/site-settings
----
+
See the following example output:

+
[source,bash]
----
NAME           TYPE  REPOSITORY URL                                 ACCESSIBLE
site-settings  git   https://github.com/<your_org>/<your_repo>.git  True
----

. Apply the `example-site` configuration to a device by updating the device specification:

+
[source,yaml]
----
apiVersion: flightctl.io/v1alpha1
kind: Device
metadata:
  name: <device_name>
spec:
[...]
  config:
  - name: example-site
    configType: GitConfigProviderSpec
    gitRef:
      repository: site-settings
      targetRevision: production
      path: /etc/example-site
[...]
----
+
// --- Explanations using Definition List ---

config::
  The example configuration takes all the files from the `example-site` directory from the `production` branch of the `site-settings` repository and places the files in the root directory (`/`).

gitRef:path::
  Ensure that the target path is writeable by creating your directory structure. The root directory (`/`) is not writeable in `bootc` systems.
