[id="create-secret-key-secret_{context}"]

= Creating a secret key secret

[role=_abstract]

To migrate your data to {OperatorPlatformNameShort} on {OCPShort}, you must create a secret key that matches the secret key defined in the inventory file during your initial installation. Otherwise, the migrated data will remain encrypted and unusable after migration.

.Procedure

. Locate the old secret key in the inventory file you used to deploy {PlatformNameShort} in your previous installation.
. Create a yaml file for your secret key:
+
-----
apiVersion: v1
kind: Secret
metadata:
  name: <resourcename>-secret-key
  namespace: <target-namespace>
stringData:
  secret-key: <content of /etc/tower/SECRET_KEY from old controller>
type: Opaque
-----
+
[NOTE]
 If admin_password_secret is not provided, the operator will look for a secret named <resourcename>-admin-password for the admin password. If it is not present, the operator will generate a password and create a Secret from it named <resourcename>-admin-password.

. Apply the secret key yaml to the cluster:
+
-----
oc apply -f <secret-key.yml>
-----
