:_mod-docs-content-type: PROCEDURE

[id="installing-containerized-aap_{context}"]

= Installing containerized {PlatformNameShort}

[role="_abstract"]


You can control the installation of {PlatformNameShort} with inventory files. Inventory files define the hosts and containers used and created, variables for components, and other information needed to customize the installation.

== Example inventory files
Example inventory files are provided in this document that you can copy and change to quickly get started. You can find additional example inventory files in link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/supported_deployment_models_for_ansible_automation_platform[Container supported topologies] in _{TitleTopologies}_.

To use the example inventory files, replace the `< >` placeholders with your specific variables, and update the host names. Refer to the `README.md` file in the installation directory for more information about optional and required variables.

.Inventory file for online installation for containerized growth topology

Use the following example inventory file to perform an online installation for the containerized growth topology:

----
# This is the AAP installer inventory file
# Please consult the docs if you're unsure what to add
# For all optional variables please consult the included README.md

# This section is for your AAP Gateway host(s)
# -----------------------------------------------------
[automationgateway]
aap.example.org

# This section is for your AAP Controller host(s)
# -------------------------------------------------
[automationcontroller]
aap.example.org

# This section is for your AAP Automation Hub host(s)
# -----------------------------------------------------
[automationhub]
aap.example.org

# This section is for your AAP EDA Controller host(s)
# -----------------------------------------------------
[automationeda]
aap.example.org

# This section is for the AAP database
# --------------------------------------
[database]
aap.example.org

[all:vars]

# Common variables
# ----------------
postgresql_admin_username=postgres
postgresql_admin_password=<set your own>

registry_username=<your RHN username>
registry_password=<your RHN password>

redis_mode=standalone

# AAP Gateway
# -----------
gateway_admin_password=<set your own>
gateway_pg_host=aap.example.org
gateway_pg_password=<set your own>

# AAP Controller
# --------------
controller_admin_password=<set your own>
controller_pg_host=aap.example.org
controller_pg_password=<set your own>

# AAP Automation Hub
# ------------------
hub_admin_password=<set your own>
hub_pg_host=aap.example.org
hub_pg_password=<set your own>

# AAP EDA Controller
# ------------------
eda_admin_password=<set your own>
eda_pg_host=aap.example.org
eda_pg_password=<set your own>
----

.Inventory file for online installation for containerized enterprise topology

Use the following example inventory file to perform an online installation for the containerized enterprise topology:

----
# This is the AAP installer inventory file
# Please consult the docs if you're unsure what to add
# For all optional variables please consult the included README.md

# This section is for your AAP Gateway host(s)
# -----------------------------------------------------
[automationgateway]
gateway1.example.org
gateway2.example.org

# This section is for your AAP Controller host(s)
# -------------------------------------------------
[automationcontroller]
controller1.example.org
controller2.example.org

# This section is for your AAP Execution host(s)
# ------------------------------------------------
[execution_nodes]
hop1.example.org receptor_type='hop'
exec1.example.org
exec2.example.org

# This section is for your AAP Automation Hub host(s)
# -----------------------------------------------------
[automationhub]
hub1.example.org
hub2.example.org

# This section is for your AAP EDA Controller host(s)
# -----------------------------------------------------
[automationeda]
eda1.example.org
eda2.example.org

[redis]
gateway1.example.org
gateway2.example.org
hub1.example.org
hub2.example.org
eda1.example.org
eda2.example.org

[all:vars]

# Common variables
# ----------------
registry_username=<your RHN username>
registry_password=<your RHN password>

# AAP Gateway
# -----------
gateway_admin_password=<set your own>
gateway_pg_host=externaldb.example.org
gateway_pg_database=<set your own>
gateway_pg_username=<set your own>
gateway_pg_password=<set your own>

# AAP Controller
# --------------
controller_admin_password=<set your own>
controller_pg_host=externaldb.example.org
controller_pg_database=<set your own>
controller_pg_username=<set your own>
controller_pg_password=<set your own>

# AAP Automation Hub
# ------------------
hub_admin_password=<set your own>
hub_pg_host=externaldb.example.org
hub_pg_database=<set your own>
hub_pg_username=<set your own>
hub_pg_password=<set your own>

# AAP EDA Controller
# ------------------
eda_admin_password=<set your own>
eda_pg_host=externaldb.example.org
eda_pg_database=<set your own>
eda_pg_username=<set your own>
eda_pg_password=<set your own>
----

== Additional information for configuring your inventory file

.Offline or bundled installation

* To perform an offline installation, add the following under the `[all:vars]` group:

----
bundle_install=true
# The bundle directory must include /bundle in the path
bundle_dir=<full path to the bundle directory>
----


.Configuring a HAProxy load balancer

To configure a HAProxy load balancer in front of platform gateway with a custom CA cert, set the following inventory file variables under the `[all:vars]` group:

----
custom_ca_cert=<path_to_cert_crt>
gateway_main_url=<https://load_balancer_url>
----

[NOTE] 
====
HAProxy SSL passthrough mode is not supported with platform gateway.
====

== Running the installation command

Use the following command to install containerized {PlatformNameShort}:

----
ansible-playbook -i inventory ansible.containerized_installer.install
----

* If your privilege escalation requires a password to be entered, append `-K` to the command line. You are then prompted for the `BECOME` password. 
* You can use increasing verbosity, up to 4 v's (`-vvvv`) to see the details of the installation process. However, it is important to note that this can significantly increase installation time, so it is recommended that you use it only as needed or requested by Red Hat support.


