:_mod-docs-content-type: PROCEDURE

[id="proc-gw-users-list-view"]

= Users list view

[role="_abstract"]

The *Users* page displays the existing users for your installation. From here, you can search for a specific user, filter the list of users, or change the sort order for the list.

When user accounts have been migrated to {PlatformNameShort} 2.6 during the upgrade process, these accounts are also displayed in the *Users* list view. You can see whether these users have administrator privileges by editing the account. See link:{URLCentralAuth}/gw-managing-access#gw-editing-a-user[Editing a user] for instructions.

.Procedure

. From the navigation panel, select {MenuAMUsers}.
. In the *Search* bar, enter an appropriate keyword for the user you want to search for and click the arrow icon.
. From the menu bar, you can sort the list of users by using the arrows for  *Username*, *Email*, *First name*, *Last name* or *Last login* to toggle your sorting preference.
. You can view user details by selecting a *Username* from the *Users* list view.
