// Used in
// assemblies/platform/assembly-installing-aap-operator-cli.adoc
// titles/aap-operator-installation/
:_mod-docs-content-type: PROCEDURE

[id="install-cli-aap-operator_{context}"]

= Installing the {OperatorPlatformNameShort} in a namespace

[role="_abstract"]

Use this procedure to subscribe a namespace to an operator.

[IMPORTANT]
====
You cannot deploy {PlatformNameShort} in the default namespace on your OpenShift Cluster. The {PlatformNameShort} namespace is recommended. You can use a custom namespace, but it should run only {PlatformNameShort}.
====

.Prerequisites

* Access to {OCP} using an account with operator installation permissions.
* The {OCPShort} CLI `oc` command is installed on your local system. Refer to link:{BaseURL}/openshift_container_platform/{OCPLatest}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI] in the {OCP} product documentation for further information.

.Procedure

. Create a project for the operator.
+
-----
oc new-project ansible-automation-platform
-----
+
. Create a file called [filename]`sub.yaml`.
. Add the following YAML code to the [filename]`sub.yaml` file.
+
-----
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ansible-automation-platform-operator
  namespace: ansible-automation-platform
spec:
  targetNamespaces:
    - ansible-automation-platform
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform
  namespace: ansible-automation-platform
spec:
  channel: 'stable-2.6'
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
-----
+
This file creates a `Subscription` object called `_ansible-automation-platform_` that subscribes the `ansible-automation-platform` namespace to the `ansible-automation-platform-operator` operator.
+
. Run the [command]`*oc apply*` command to create the objects specified in the [filename]`sub.yaml` file:
+
-----
oc apply -f sub.yaml
-----
+
. Verify the CSV PHASE reports "Succeeded" before proceeding using the [command]`oc get csv -n ansible-automation-platform` command:
+
-----
oc get csv -n ansible-automation-platform

NAME                               DISPLAY                       VERSION              REPLACES                           PHASE
aap-operator.v2.6.0-0.1728520175   Ansible Automation Platform   2.6.0+0.1728520175   aap-operator.v2.6.0-0.1727875185   Succeeded
-----
+
. Create an `AnsibleAutomationPlatform` object called `_example_` in the `ansible-automation-platform` namespace.
+
To change the {PlatformNameShort} and its components from `_example_`, edit the _name_ field in the `metadata:` section and replace example with the name you want to use:
+
-----
oc apply -f - <<EOF
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: example
  namespace: ansible-automation-platform
spec:
  # Platform
  image_pull_policy: IfNotPresent
  # Components
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: false
    ## Modify to contain your RWM storage class name
    storage_type: file
    file_storage_storage_class: <your-read-write-many-storage-class>
    file_storage_size: 10Gi

    ## uncomment if using S3 storage for Content pod
    # storage_type: S3
    # object_storage_s3_secret: example-galaxy-object-storage

    ## uncomment if using Azure storage for Content pod
    # storage_type: azure
    # object_storage_azure_secret: azure-secret-name
  lightspeed:
    disabled: true
EOF
-----

[role="_additional-resources"]
.Additional resources

* link:{BaseURL}/openshift_container_platform/{OCPLatest}/html/operators/user-tasks#olm-installing-operator-from-operatorhub-using-cli_olm-installing-operators-in-namespace[Installing from OperatorHub using the CLI]
