:_mod-docs-content-type: PROCEDURE

[id="edge-manager-oauth-manually"]

= Setting up the OAuth application manually

.Procedure

. From the navigation panel on your {PlatformNameShort} instance, go to menu:{MenuAM}[OAuth Applications].
. Click btn:[Create OAuth application].
. Enter the following details:
** *Name*: Red Hat Edge Manager
** *URL*: The `baseDomain` of your {PlatformNameShort} UI.
** *Authorization grant type*: Select *Authorization code*.
** *Client*: Select *Public*.
** *Redirect URIs*: 
*** The redirect configured for your UI is your `baseDomain` with a /callback route appended, such as `https://your-edge-manager-ip-or-domain/callback`.
*** To provide a redirect for console usage, configure a redirect URI, such as `http://127.0.0.1/callback`.
. Copy the *Client ID* and update *oAuthApplicationClientId* in your configuration file with this value.

[NOTE]
====
URIs must be separated by spaces in the *Redirect URIs* field, not commas or other delimiters.
====

.Additional resources

For more information, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/access_management_and_authentication/gw-token-based-authentication[Configuring access to external applications with token-based authentication]. 
