:_mod-docs-content-type: PROCEDURE

[id="proc-running-setup-script_{context}"]

= Running the {PlatformName} installer setup script

[role="_abstract"]
Run the {Installer} setup script after updating the inventory file with all the required parameters to begin the installation and configuration of the platform.

*RPM installer*

.Procedure

* Run the `setup.sh` script
+
-----
$ sudo ./setup.sh
-----
+
[NOTE]
====
If you are running the setup as a non-root user with `sudo` privileges, you can use the following command:
----
$ ANSIBLE_BECOME_METHOD='sudo'
ANSIBLE_BECOME=True ./setup.sh
----
====
+
Installation of {PlatformName} will begin.

+
.Next steps
If you want to add additional nodes to your {AutomationMesh} after the initial setup, edit the inventory file to add the new node, then rerun the `setup.sh` script.
+
*Containerized installer*
+
To install a containerized Ansible Automation Platform using the installation playbook, use the method described in link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/containerized_installation/installing-containerized-aap[Install containerized Ansible Automation Platform]

//.Additional resources
//Commenting out as no downstream alternative [AAP-57435]
//See link:https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html[Understanding privilege escalation] for additional `setup.sh` script examples.
