:_mod-docs-content-type: PROCEDURE

[id="backing-up-containerized-ansible-automation-platform"]

= Back up containerized {PlatformNameShort}

[role="_abstract"]
Perform a backup of your {ContainerBase} of {PlatformNameShort}.

[NOTE]
====
* When backing up {PlatformNameShort}, use the installation program that matches your currently installed version of {PlatformNameShort}.

* Backup functionality only works with the PostgreSQL versions supported by your current {PlatformNameShort} version. 
For more information, see link:{URLContainerizedInstall}/preparing-containerized-installation#system-requirements[System requirements].

* Backup and restore for content stored in Azure Blob Storage or Amazon S3 must be handled through the vendor portals, as each vendor provides their own backup solutions.
====

.Prerequisites

* You have logged in to the {RHEL} host as your dedicated non-root user.

.Procedure

. Go to the {PlatformName} installation directory on your {RHEL} host.

. To control compression of the backup artifacts before they are sent to the host running the backup operation, you can use the following variables in your inventory file:
.. For control of compression for filesystem related backup files:
+
----
# Global control of compression for filesystem backup files
use_archive_compression=true

# Component-level control of compression for filesystem backup files
#controller_use_archive_compression=true
#eda_use_archive_compression=true
#gateway_use_archive_compression=true 
#hub_use_archive_compression=true
#pcp_use_archive_compression=true
#postgresql_use_archive_compression=true
#receptor_use_archive_compression=true
#redis_use_archive_compression=true
----
+
.. For control of compression for database related backup files:
+
----
# Global control of compression for database backup files
use_db_compression=true

# Component-level control of compression for database backup files
#controller_use_db_compression=true
#eda_use_db_compression=true
#hub_use_db_compression=true
#gateway_use_db_compression=true
----

. Run the `backup` playbook:
+
----
$ ansible-playbook -i <path_to_inventory> ansible.containerized_installer.backup
----
+
The backup process creates archives of the following data:
+
* PostgreSQL databases
* Configuration files
* Data files

.Next steps

To customize the backup process, you can use the following variables in your inventory file:

* Change the backup destination directory from the default `./backups` by using the `backup_dir` variable.
* Exclude paths that contain duplicated data, such as snapshot subdirectories, by using the `hub_data_path_exclude` variable. For example, to exclude a `.snapshots` subdirectory, specify `hub_data_path_exclude=['*/.snapshots/*']` in your inventory file.
** Alternatively, you can use the command-line interface with the `-e` flag to pass this variable at runtime:
+
----
$ ansible-playbook -i inventory ansible.containerized_installer.backup -e hub_data_path_exclude="['*/.snapshots/*']"
----
