[id="edge-manager-k8s-auth"]

= Authorizing with Kubernetes

{RedHatEdge} Kubernetes authorization uses a role-based access control (RBAC) to control authorization for {RedHatEdge} API endpoints. 
You need to change some `helm` configuration values.
For more information, see the *global.auth* section in https://github.com/flightctl/flightctl/blob/main/deploy/helm/flightctl/values.yaml[values.yaml].

.Procedure

Set the following variables:

* Set *global.auth.type* to *k8s*.
* Optionally set *global.auth.caCert*,
*global.auth.insecureSkipTlsVerify*.

When you set these variables, the Kubernetes cluster on which {RedHatEdge} is deployed, is used as auth authority.

If you want to use a different cluster as auth authority, set the following variables also:

* Set *global.auth.k8s.apiUrl* to API URL of the external Kubernetes cluster.
* Set *global.auth.k8s.externalApiToken* to a token which has permission to CREATE `authentication.k8s.io/tokenreview` resource in the external Kubernetes cluster.

If the Kubernetes cluster is an OpenShift cluster, you can also set
*global.auth.k8s.externalOpenShiftApiUrl* which enables interactive login for the CLI (`flightctl login <fctl_url> --web`).


// Not relevant for AAP:
// If deploying on ACM (by global.target: acm), the k8s auth values are automatically calculated.
