:_mod-docs-content-type: PROCEDURE



[id="proc-installing-with-internet_{context}"]


= Installing with internet access

[role="_abstract"]
Choose the {PlatformName} installer if your {RHEL} environment is connected to the internet. Installing with internet access retrieves the latest required repositories, packages, and dependencies. Choose one of the following ways to set up your {PlatformNameShort} installer.

== Tarball install

.Procedure
. Navigate to the link:{PlatformDownloadUrl}[{PlatformName} download] page.
. Click btn:[Download Now] for the *Ansible Automation Platform <latest-version> Setup*.
. Transfer the file to the target server using `scp` or `curl`:
.. Using `scp`: 
... Run the following command, replacing `private_key.pem`, `user`, and `server_ip` with your appropriate values:
-----
$ scp -i private_key.pem aap-bundled-installer.tar.gz user@server_ip: 
-----
.. Using `curl`: 
... If the setup file URL is available, you can download it directly to the target server using `curl`. Replace `<download_url>` with the file URL:
-----
$ curl -0 <download_url>
-----

[NOTE]
====
If the file needs to be extracted after downloading, run the following command:
-----
$ tar xvzf aap-bundled-installer.tar.gz
-----
====

== RPM install
[NOTE]
====
The {PlatformNameShort} RPM installer was deprecated in 2.5 and will be removed in {PlatformNameShort} 2.7. The RPM installer will be supported for RHEL 9 during the lifecycle of {PlatformNameShort} 2.6 to support migrations to existing supported topologies. For more information on upgrade and migration paths, see the link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/{PlatformVers}/html-single/planning_your_upgrade/index#upgrade-support-matrix[Support matrix for upgrade scenarios].
====
.Procedure
. Install {PlatformNameShort} Installer Package:
+
v.{PlatformVers} for RHEL 9 for x86_64
+
----
$ sudo dnf install --enablerepo=ansible-automation-platform-2.6-for-rhel-9-x86_64-rpms ansible-automation-platform-installer
----

[NOTE]
====
`dnf install` enables the repo as the repo is disabled by default.
====

When you use the RPM installer, the files are placed under the `/opt/ansible-automation-platform/installer` directory.
