:_mod-docs-content-type: PROCEDURE

[id="backing-up-containerized-ansible-automation-platform"]

= Backing up containerized {PlatformNameShort}

[role="_abstract"]
Perform a backup of your {ContainerBase} of {PlatformNameShort}.

[NOTE]
====
When backing up {PlatformNameShort}, use the installation program that matches your currently installed version of {PlatformNameShort}.

Backup functionality only works with the PostgreSQL versions supported by your current {PlatformNameShort} version. 
For more information, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/containerized_installation/aap-containerized-installation#system-requirements[System requirements].
====

.Prerequisites

* You have logged in to the {RHEL} host as your dedicated non-root user.

.Procedure

. Go to the {PlatformName} installation directory on your {RHEL} host.

. To control compression of the backup artifacts before they are sent to the host running the backup operation, you can use the following variables in your inventory file:
.. For control of compression for filesystem related backup files:
+
----
# For global control of compression for filesystem related backup files 
use_archive_compression=true

# For component-level control of compression for filesystem related backup files
#controller_use_archive_compression=true
#eda_use_archive_compression=true
#gateway_use_archive_compression=true 
#hub_use_archive_compression=true
#pcp_use_archive_compression=true
#postgresql_use_archive_compression=true
#receptor_use_archive_compression=true
#redis_use_archive_compression=true
----
+
.. For control of compression for database related backup files:
+
----
# For global control of compression for database related backup files 
use_db_compression=true  

# For component-level control of compression for database related backup files
#controller_use_db_compression=true
#eda_use_db_compression=true
#hub_use_db_compression=true
#gateway_use_db_compression=true
----

. Run the `backup` playbook:
+
----
$ ansible-playbook -i <path_to_inventory> ansible.containerized_installer.backup
----
+
This backs up the important data deployed by the containerized installer such as:
+
* PostgreSQL databases
* Configuration files
* Data files

. By default, the backup directory is set to `./backups`. You can change this by using the `backup_dir` variable in your `inventory` file.
