[id="proc-update-aap-container"]

= Updating container-based {PlatformNameShort}

Perform a patch update for a {ContainerBase} of {PlatformNameShort} from 2.5 to 2.5.x.

include::snippets/container-upgrades.adoc[]

.Prerequisites

You have done the following:

* Reviewed the release notes for the associated patch release. For more information, see the link:{URLReleaseNotes}[{PlatformNameShort} {TitleReleaseNotes}].

* Created a backup of your {PlatformNameShort} deployment. For more information, see xref:proc-backup-aap-container[Backing up container-based {PlatformNameShort}].

.Procedure

. Download the latest version of the containerized installer from the link:{PlatformDownloadUrl}[{PlatformNameShort} download].

.. For online installations *{PlatformNameShort} {PlatformVers} Containerized Setup*

.. For offline or bundled installations: *{PlatformNameShort} {PlatformVers} Containerized Setup Bundle*

. Copy the installation program `.tar` file onto your {RHEL} host.

. Decide where you want the installation program to reside on the filesystem. Installation related files will be created under this location and require at least 10 GB for the initial installation.

. Unpack the installation program `.tar` file into your installation directory, and go to the unpacked directory.

.. To unpack the online installer:
+
----
$ tar xfvz ansible-automation-platform-containerized-setup-<version>.tar.gz
----
+
.. To unpack the offline or bundled installer:
+ 
----
$ tar xfvz ansible-automation-platform-containerized-setup-bundle-<version>-<arch name>.tar.gz
----
+
. Edit the `inventory` file to match your required configuration. You can keep the same parameters from your existing {PlatformNameShort} deployment or you can change the parameters to match any modifications to your environment.

. Run the `install` playbook:
+
----
$ ansible-playbook -i inventory ansible.containerized_installer.install
----
+
* If your privilege escalation requires a password to be entered, append `-K` to the command. You will then be prompted for the `BECOME` password.
* You can use increasing verbosity, up to 4 v’s (`-vvvv`) to see the details of the installation process. However it is important to note that this can significantly increase installation time, so it is recommended that you use it only as needed or requested by Red Hat support.

The update begins.