:_mod-docs-content-type: PROCEDURE

[id="proc-gw-add-team-organization"]

= Adding a team to an organization

You can provide team access to an organization by adding roles to the team. To add roles to a team, the team must already exist in the organization. For more information, see xref:proc-controller-creating-a-team[Creating a team].
To add roles for a team, the role must already exist. See xref:proc-gw-create-roles[Creating a role] for more information.

.Procedure

. From the navigation panel, select {MenuAMOrganizations}.
. From the Organizations list view, select the organization to which you want to add team access.
. Click the *Teams* tab. If no teams exist, click btn:[Create team] to create a team and add it to this organization.
. Click btn:[Add roles].
. Select the roles you want the selected team to have. Scroll down for a complete list of roles.
+
include::snippets/snip-gw-roles-note-multiple-components.adoc[]

+
. Click btn:[Next] to review the roles settings.
. Click btn:[Finish] to apply the roles to the selected teams. The Add roles dialog displays the updated roles assigned for each team.
. Click btn:[Close].
+
[NOTE]
====
A team with associated roles retains them if they are reassigned to another organization.
====
+
. To manage roles for teams in an organization, click the *{SettingsIcon}* icon next to the user and select *Manage roles*. 
