:_mod-docs-content-type: PROCEDURE

[id="proc-controller-user-permissions"]

= Adding roles to a team

You can assign permissions to teams, such as edit and administer resources and other elements.
You can set permissions through an inventory, project, job template and other resources, or within the Organizations view.

[NOTE]
====
Teams can not be assigned to an organization by adding roles. Refer to the steps provided in link:{URLCentralAuth}/gw-managing-access#proc-gw-add-team-organization[Adding a team to an organization] for detailed instructions.
====

.Procedure
. From the navigation panel, select {MenuAMTeams}.
. Select the team *Name* to which you want to add roles.
. Select the *Roles* tab and click btn:[Add roles].
+
include::snippets/snip-gw-roles-note-multiple-components.adoc[]

+
. Select a *Resource type* and click btn:[Next]. 
. Select the resources to receive the new roles and click btn:[Next].
. Select the roles to apply to the resources and click btn:[Next].
. Review the settings and click btn:[Finish].
+ 
The Add roles dialog displays indicating whether the role assignments were successfully applied, click btn:[Close] to close the dialog.
