[id="proc-gw-organizations-exec-env_{context}"]

= Working with execution environments

When automation controller is enabled on the platform, you can review any execution environments you have set up and manage their settings within the organization resource.

For more information about execution environments, see link:{BaseURL}/{PlatformVers}/html/using_automation_execution/index#assembly-controller-execution-environments[Execution environments] in _Using automation execution_ guide.


.Procedure

. From the navigation panel, select {MenuAMOrganizations}.
. From the Organizations list view, select the organization to which you want to manage execution environments.
. Select the *Execution Environments* tab.
. If no execution environments are available, click btn:[Create execution environment] to create one. Alternatively, you can create an execution environment from the navigation panel by selecting {MenuInfrastructureExecEnvironments}.
. Click btn:[Create execution environment].
+
[NOTE]
====
After creating a new execution environment, return to Access Management > Organizations and select the organization in which you created the execution environment to update the list on that tab.
====
+
. Select the execution environments to use with your particular organization.
