[id="controller-set-up-SAML"]

= Configuring SAML authentication

SAML allows the exchange of authentication and authorization data between an Identity Provider (IdP) and a Service Provider (SP). {PlatformNameShort} is a SAML SP that can be configured to talk with one or more SAML IdPs in order to authenticate users. Based on groups and attributes optionally provided by the IdP users can be placed into teams and organizations in {PlatformNameShort} based on authenticator maps tied to this authenticator.


.Procedure

. From the navigation panel, select {MenuAMAuthentication}.
. Click btn:[Create authentication].
. Select *SAML* from the *Authentication type* list and click btn:[Next].
. Enter a *Name* for this SAML configuration. 
. Enter the application-defined unique identifier used as the audience of the SAML service provider configuration in the *SAML Service Provider Entity ID* field. This is usually the URL for the service.
. Include the certificate content in the *SAML Service Provider Public Certificate* field.
. Include the private key content in the *SAML Service Provider Private Key*.
. Enter the URL to redirect the user to for login initiation in the *IdP Login URL* field.
. Enter the public cert used for secrets coming from the *IdP in the IdP Public Cert* field.
. Enter the entity ID returned in the assertion in the *Entity ID*. 
.Enter user details in the *Groups*, *User Email*, *Username*, *User Last Name*, *User First Name* and *User Permanent ID* fields.  
. The *SAML Assertion Consumer Service (ACS) URL* field registers the service as a service provider (SP) with each identity provider (IdP) you have configured. 
+
include::snippets/snip-gw-authentication-additional-auth-fields.adoc[]
+
. In the *SAML Service Provider Organization Info* field, provide the URL, display name, and the name of your app.
+
----
{
  "en-US": {
    "url": "http://www.example.com",
    "displayname": "Example",
    "name": "example"
  }
}
----
+
. In the *SAML Service Provider Technical Contact* field, provide the name and email address of the technical contact for your service provider. 
+
----
{
"givenName": "Some User",
"emailAddress": "suser@example.com"
}
----
+
. In the *SAML Service Provider Support Contact* field, provide the name and email address of the support contact for your service provider. 
+
----	
{
"givenName": "Some User",
"emailAddress": "suser@example.com"
}
----
+
. Optional: Provide extra configuration data in the *SAML Service Provider extra configuration data* field. This field is the equivalent to the `SOCIAL_AUTH_SAML_SP_EXTRA` in the API. For more information, see link:https://github.com/SAML-Toolkits/python-saml#settings[OneLogin’s SAML Python Toolkit] to learn about the valid service provider extra (SP_EXTRA) parameters.
. Optional: Provide security settings in the *SAML Security Config* field. This field is the equivalent to the `SOCIAL_AUTH_SAML_SECURITY_CONFIG` field in the API. 
+
----
// Indicates whether the <samlp:AuthnRequest> messages sent by this SP // will be signed. [Metadata of the SP will offer this info] 
"authnRequestsSigned": false,

// Indicates a requirement for the <samlp:Response>, <samlp:LogoutRequest> // and <samlp:LogoutResponse> elements received by this SP to be signed. 
"wantMessagesSigned": false,

// Indicates a requirement for the <saml:Assertion> elements received by // this SP to be signed. [Metadata of the SP will offer this info] 
"wantAssertionsSigned": false,
----
For more information and additional options, see link:https://github.com/SAML-Toolkits/python-saml#settings[OneLogin’s SAML Python Toolkit].
+
. Optional: In the *SAML IDP to extra_data attribute mapping* field, enter values to map  IDP attributes to extra_data attributes. For more information, see link:https://python-social-auth.readthedocs.io/en/latest/backends/saml.html#advanced-settings[advanced SAML settings].
+
include::snippets/snip-gw-authentication-common-checkboxes.adoc[]
+
. Click btn:[Next].

[NOTE]
====
You can configure an HTTPS redirect for SAML in operator-based deployments to simplify log in for your users. For the steps to configure this setting, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#proc-operator-enable-https-redirect[Enabling single sign-on (SSO) for {Gateway} on {OCPShort}].
====



[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-authentication-next-steps.adoc[]
