:_mod-docs-content-type: PROCEDURE

[id="proc-operator-mesh-upgrading-receptors"]

= Upgrade receptors

[role="_abstract"]
A software update addresses any issues or bugs to provide a better experience of working with the technology. Anyone with administrative rights can update the receptor on an execution node. 

Red Hat recommends performing updates to the receptor after any {PlatformNameShort} control plane updates. This ensures you are using the latest version. The best practice is to perform regular updates outside of any updates to the control plane.


.Procedure

. Check the current receptor version:
+
----
receptor --version
----
+
. Update the receptor:
+
----
sudo dnf update ansible-runner receptor -y
----
+
[NOTE]
====
To upgrade all packages (not just the receptor), use `dnf update`, then reboot with `reboot`.
====
+
. Verify the installation. After the update is complete, check the receptor version again to verify the update:
+
----
receptor --version
----
+
. Restart the receptor service:
+
----
sudo systemctl restart receptor
----
+
. Ensure the receptor is working correctly and is properly connected to the controller or other nodes in the system.


