[id="proc-update-aap-container"]

= Updating containerized {PlatformNameShort}

Perform a patch update for a {ContainerBase} of {PlatformNameShort} from 2.5 to 2.5.x.

include::snippets/container-upgrades.adoc[]

.Prerequisites

You have done the following:

* Reviewed the release notes for the associated patch release. For more information, see the link:{URLReleaseNotes}[{PlatformNameShort} {TitleReleaseNotes}].

* Created a backup of your {PlatformNameShort} deployment. For more information, see xref:proc-backup-aap-container[Backing up container-based {PlatformNameShort}].

* Logged in to the {RHEL} host as your dedicated non-root user.

* Followed the steps in link:{URLContainerizedInstall}/aap-containerized-installation#downloading-ansible-automation-platform[Downloading {PlatformNameShort}] to download the latest version of containerized {PlatformNameShort} and copied the installation program to your {RHEL} Host.

.Procedure

. Edit the `inventory` file to match your required configuration. You can keep the same parameters from your existing {PlatformNameShort} deployment or you can change the parameters to match any modifications to your environment.

. Run the `install` playbook:
+
----
$ ansible-playbook -i inventory ansible.containerized_installer.install
----
+
* If your privilege escalation requires a password to be entered, append `-K` to the command. You will then be prompted for the `BECOME` password.
* You can use increasing verbosity, up to 4 v’s (`-vvvv`) to see the details of the installation process. However it is important to note that this can significantly increase installation time, so it is recommended that you use it only as needed or requested by Red Hat support.

The update begins.