:_mod-docs-content-type: PROCEDURE

[id="edge-manager-monitor-device-resources-cli"]

= Monitor device resources on the CLI

[role="_abstract"]

Monitor the resource use of your {RedHatEdge} devices on the CLI by configuring detailed monitors and threshold-based alert rules. 
This enables automatic status reporting, helping you keep stability and troubleshoot performance issues.

.Procedure

* Add resource monitors in the `resources:` section of the device's specification.
+
For example, add the following monitor for your disk:
+
[source,yaml]
----
apiVersion: flightctl.io/v1alpha1
kind: Device
metadata:
  name: <device_name>
spec:
[...]
  resources:
  - monitorType: Disk
    samplingInterval: 5s 
    path: /application_data 
    alertRules:
    - severity: Warning
      duration: 30m
      percentage: 75
      description: Disk space for application data is >75% full for over 30m.
    - severity: Critical
      duration: 10m
      percentage: 90
      description: Disk space for application data is >90% full over 10m.
[...]
----
+
// --- Explanations using Definition List ---

samplingInterval::
  Samples usage every 5 seconds.
path::
  Checks disk usage on the file system that is associated with the `/applications_data` path.
alertRules[severity: Warning]::
  Initiates a warning if the average usage exceeds 75% for more than 30 minutes.
alertRules[severity: Critical]::
  Initiates a critical alert if the average usage exceeds 90% for over 10 minutes.