:_mod-docs-content-type: PROCEDURE

[id="gw-keycloak-authentication"]

= Configuring keycloak authentication

You can configure {PlatformNameShort} to integrate Keycloak to manage user authentication.

.Procedure

. From the navigation panel, select {MenuAMAuthentication}.
. Click btn:[Create authentication].
. Select *Local* from the *Authentication type* list.
. Click btn:[Next]. 
. Enter a *Name* for this keycloak configuration. The configuration name is required, must be unique across all authenticators, and must not be longer than 512 characters. 
. Enter the location where the user's token can be retrieved in the *Keycloak Access Token URL* field.
. Optional: Enter the redirect location the user is taken to during the login flow in the *Keycloak Provider URL* field. 
. Enter the Client ID from your Keycloak installation in the *Keycloak OIDC Key* field.
. Enter the RS256 public key provided by your Keycloak realm in the *Keycloak Public Key* field. 
. Enter the OIDC secret (Client Secret) from your Keycloak installation in the *Keycloak OIDC Secret* field.
include::snippets/snip-gw-authentication-additional-auth-fields.adoc
+
include::snippets/snip-gw-authentication-common-checkboxes.adoc
. Click btn:[Next].

[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-authentication-next-steps.adoc