:_mod-docs-content-type: PROCEDURE

[id="proc-controller-ingress-options_{context}"]

= Configure ingress options for {ControllerName} 

[role="_abstract"]

The {OperatorPlatformNameShort} installation form allows you to further configure your {ControllerName} operator ingress under *Advanced configuration*.

.Procedure

. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *Automation Controller* tab. 
. For new instances, click btn:[Create AutomationController].
.. For existing instances, you can edit the YAML view by clicking the {MoreActionsIcon} icon and then btn:[Edit AutomationController].
. Click btn:[Advanced configuration].
. Under *Ingress type*, click the drop-down menu and select *Ingress*.
. Under *Ingress annotations*, enter any annotations to add to the ingress.
. Under *Ingress TLS secret*, click the drop-down menu and select a secret from the list.

.Verification

After you have configured your {ControllerName} operator, click btn:[Create] at the bottom of the form view. {OCP} creates the pods. This may take a few minutes.

You can view the progress by navigating to menu:Workloads[Pods] and locating the newly created instance.

Verify that the following operator pods provided by the {PlatformNameShort} Operator installation from {ControllerName} are running:
[cols="a,a,a,a", options="header", subs=+attributes]
|===
| Operator manager controllers | {ControllerNameStart} |{HubNameStart} |{EDAName} (EDA)

| The operator manager controllers for each of the three operators, include the following:

* automation-controller-operator-controller-manager
* automation-hub-operator-controller-manager
* resource-operator-controller-manager
* aap-gateway-operator-controller-manager 
* ansible-lightspeed-operator-controller-manager
* eda-server-operator-controller-manager

| After deploying {ControllerName}, you can see the addition of the following pods:

* controller
* controller-postgres
* controller-web
* controller-task

| After deploying {HubName}, you can see the addition of the following pods:

* hub-api
* hub-content
* hub-postgres
* hub-redis
* hub-worker

| After deploying EDA, you can see the addition of the following pods:

* eda-activation-worker
* da-api
* eda-default-worker
* eda-event-stream
* eda-scheduler

|===

[NOTE]
====
A missing pod can indicate the need for a pull secret. Pull secrets are required for protected or private image registries. See link:https://docs.openshift.com/container-platform/4.11/openshift_images/managing_images/using-image-pull-secrets.html[Using image pull secrets] for more information. You can diagnose this issue further by running `oc describe pod <pod-name>` to see if there is an ImagePullBackOff error on that pod.
====
