[id="controller-find-subscription"]

= Finding your subscription with service account credentials

When you log in to {PlatformNameShort} for the first time, you must add your subscription information. 

If you have already added your subscription, you can update your subscription details in the platform by going to {MenuSetSubscription} → btn:[Edit subscription].

.Prerequisite

* You have link:https://docs.redhat.com/en/documentation/red_hat_hybrid_cloud_console/1-latest/html/creating_and_managing_service_accounts/proc-ciam-svc-acct-overview-creating-service-acct#proc-ciam-svc-acct-create-creating-service-acct[created a service account] and saved the client ID and client secret.

.Procedure

. Enter your service account credentials to find the subscription associated with your profile:
.. To find your subscription, click the tab labeled *Service Account / Red Hat Satellite*.
.. In the *Client ID / Satellite username* field enter the client ID you received when you created your service account.
.. In the *Client secret / Satellite password* field enter the client secret you received when you created your service account.
Your subscription appears in the list menu labeled *Subscription*. 
Select your subscription.

. After you have added your subscription, click btn:[Next].
. Check the box indicating that you agree to the *End User License Agreement*.
. Review your information and click *Finish*.

[NOTE]
====
If you enter your client ID and client secret but cannot locate your subscription, you might not have the correct permissions set on your service account. 
For more information and troubleshooting guidance for service accounts, see link:https://access.redhat.com/articles/7112649[Configure Ansible Automation Platform to authenticate through service account credentials].
====
