:_mod-docs-content-type: PROCEDURE

[id="proc-settings-gw-custom-login"]

= Configuring a custom platform log in

//Content divided into multiple procedures to address issue AAP-30592

From the *{GatewayStart} settings* page, you can configure the custom log in options.

.Procedure
. From the navigation panel, select {MenuSetGateway}.
. The *{GatewayStart} settings* page is displayed. 
. To configure the options, click btn:[Edit {Gateway} settings].
. You can configure the following *Custom Login* options:
+
* *Custom login info*: Provide specific information (such as a legal notice or a disclaimer) to a text box in the login modal. For example, you can include a company banner with a statement such as, “This is only to be used for `<COMPANY_NAME>`, etc.”
* *Custom logo* : Provide an image file for setting up a custom logo (must be a data URL with a base64-encoded GIF, PNG, or JPEG image).
+
. Click btn:[Save {Gateway} settings] to save the changes or proceed to configure the other platform options available.
