:_mod-docs-content-type: PROCEDURE

[id="controller-adding-new-schedule-from-resource"]

= Add a new schedule from a resource page

[role="_abstract"]
You can create a new schedule from the *Schedules* tab of a resource page, such as a template, project, or inventory source.

To create a new schedule from a resource page:

.Procedure
. Click the *Schedules* tab of the resource that you are configuring.
This can be a template, project, or inventory source.
. Click btn:[Create schedule]. 
This opens the *Create schedule* window.

. Enter the appropriate details into the following fields:

* *Schedule name*: Enter the name.
* Optional: *Description*: Enter a description.
* *Start date/time*: Enter the date and time to start the schedule.
* *Time zone*: Select the time zone. The *Start date/time* that you enter must be in this time zone.
//* *Repeat frequency*: Appropriate scheduling options display depending on the frequency you select.
+
The *Schedule Details* display when you establish a schedule, enabling you to review the schedule settings and a list of the scheduled occurrences in the selected *Local Time Zone*.
+
[IMPORTANT]
====
Jobs are scheduled in UTC. 
Repeating jobs that run at a specific time of day can move relative to a local time zone when Daylight Saving Time shifts occur. 
The system resolves the local time zone based time to UTC when the schedule is saved. 
To ensure your schedules are correctly created, set your schedules in UTC time.
====
+
. Click btn:[Next].
The *Define rules* page is displayed.
