:_newdoc-version: 2.18.3
:_template-generated: 2024-10-09
:_mod-docs-content-type: PROCEDURE

[id="upgrade-controller-hub-eda-unified-ui-services_{context}"]
= Using Migration path for 2.4 services with 2.5 services

If you installed {PlatformNameShort} 2.5 to use {EDAName} in a supported scenario, you can upgrade your {PlatformNameShort} 2.4 {ControllerName} and {HubName} to {PlatformNameShort} 2.5 by following the procedure in this section.

.Prerequisites

* An inventory from 2.4 for {ControllerName} and {HubName} and a {PlatformVers} inventory for the unified UI ({Gateway}) and {EDAName}. You must merge both inventories into a single {PlatformVers} inventory file before running the upgrade. The {Gateway} host must be included in the inventory for the installation program to run successfully.

[IMPORTANT]
====
Ensure you have upgraded to the latest version of {PlatformNameShort} 2.4 before merging inventories and running the {PlatformVers} upgrade.
====

.Procedure

. Merge 2.4 inventory data into the {PlatformVers} inventory.
+
The example below shows the inventory file for {ControllerName} and {HubName} for 2.4 and the inventory file for {EDAName} and the unified UI ({Gateway}) for {PlatformVers}, respectively, as the starting point, and what the merged inventory looks like.
+
*Inventory files from 2.4*
+
[source,bash]
----
[automationcontroller]
controller-1
controller-2

[automationhub]
hub-1
hub-2

[all:vars]
# Here we have the admin passwd, db credentials, etc.
----
+
*Inventory files from {PlatformVers}*
+
[source,]
----
[automationedacontroller]
eda-1
eda-2

[automationgateway]
gw-1
gw-2

[all:vars]
# Here we have admin passwd, db credentials etc.
----
+
*Merged Inventory*
+
[source,]
----
[automationcontroller]
controller-1
controller-2

[automationhub]
hub-1
hub-2

[automationedacontroller]
eda-1
eda-2

[automationgateway]
gw-1
gw-2

[all:vars]
# Here we have admin passwd, db credentials etc from both inventories above
----

. Run `setup.sh`
+
The installation program upgrades all services to the latest version of {PlatformNameShort} {PlatformVers} and connects them to the unified UI ({Gateway}).

.Verification

* Verify that everything has upgraded to {PlatformVers} and is working properly in one of two ways:
** Perform an SSH to {ControllerName} and {EDAName}.
** In the unified UI, go to menu:Help[About] to verify the RPM versions are at {PlatformVers}.
