:_mod-docs-content-type: PROCEDURE

[id="proc_configuring-controller-ldap-security_{context}"]

= Configuring your controller LDAP security

[role="_abstract"]

You can configure your LDAP SSL configuration for {ControllerName} through any of the following options:

* The {ControllerName} user interface.
* The {Gateway} user interface. See the link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/access_management_and_authentication/index#controller-set-up-LDAP[Configuring LDAP authentication] section of the _Access management and authentication_ guide for additional steps.
* The following procedure steps.

.Procedure
. Create a secret in your {PlatformNameShort} namespace for the `bundle-ca.crt` file (the filename must be `bundle-ca.crt`):
+
----
$ oc create secret -n aap generic bundle-ca-secret --from-file=bundle-ca.crt
----
+
[NOTE]
====
The target filename for this operation must be `bundle-ca.crt` and the secret name should be `bundle-ca-secret`.
====
+
. Add the `bundle_cacert_secret` to the {PlatformNameShort} customer resource:
+
----
...
spec:
  bundle_cacert_secret: bundle-ca-secret
...
----
+

.Verification

You can verify the expected certificate by running:
+
----
oc get deployments -l 'app.kubernetes.io/component=aap-gateway'
----
+
----
oc exec -it deployment.apps/<gateway-deployment-name-from-above> -- openssl x509 -in /etc/pki/tls/certs/ca-bundle.crt -noout -text
----

