:_mod-docs-content-type: PROCEDURE

[id="proc-set-registry-username-password"]

= Create a registry service account

[role="_abstract"]
Create a new registry service account on the Red Hat Customer Portal to generate a named token and username. Use these credentials to set the `registry_username` and `registry_password` variables, which are essential for supporting online non-bundled installations in environments where credentials must be shared, such as deployment systems.

.Procedure
. Go to https://access.redhat.com/terms-based-registry/accounts.
. On the *Registry Service Accounts* page click btn:[New Service Account].
. Enter a name for the account using only the allowed characters.
. Optionally enter a description for the account.
. Click btn:[Create].
. Find the created account in the list by searching for your name in the search field.
. Click the name of the account that you created. 
. Alternatively, if you know the name of your token, you can go directly to the page by entering the URL: 
+
----
https://access.redhat.com/terms-based-registry/token/<name-of-your-token>
----
+
. A *token* page opens, displaying a generated username (different from the account name) and a token. 
+
.. If no token is displayed, click btn:[Regenerate Token]. You can also click this to generate a new username and token.
. Copy the username (for example "1234567|testuser") and use it to set the variable `registry_username`.
. Copy the token and use it to set the variable `registry_password`.
