:_mod-docs-content-type: PROCEDURE

[id="proc-gw-organizations-exec-env_{context}"]

= Working with {ExecEnvShort}s

When {ControllerName} is enabled on the platform, you can review any {ExecEnvShort}s you have set up and manage their settings within the organization resource.

For more information about execution environments, see link:{BaseURL}/{PlatformVers}/html/using_automation_execution/index#assembly-controller-execution-environments[Execution environments] in _Using automation execution_ guide.


.Procedure

. From the navigation panel, select {MenuAMOrganizations}.
. From the Organizations list view, select the organization to which you want to manage {ExecEnvShort}s.
. Select the *Execution Environments* tab.
. If no {ExecEnvShort}s are available, click btn:[Create execution environment] to create one. Alternatively, you can create an {ExecEnvShort} from the navigation panel by selecting {MenuInfrastructureExecEnvironments}.
. Click btn:[Create {ExecEnvShort}].
+
[NOTE]
====
After creating a new {ExecEnvShort}s, return to {MenuAMOrganizations} and select the organization in which you created the {ExecEnvShort} to update the list on that tab.
====
+
. Select the {ExecEnvShort}s to use with your particular organization.
