[id="edge-manager-image-build"]

= The image building process

. Choose a base `bootc` operating system image, such as a Fedora, CentOS, or RHEL image.
. Create a container file that layers the following items onto the base `bootc` image:
+
* The {RedHatEdge} agent and configuration.
* Optional: Any drivers specific to your target deployment environment.
* Optional: Host configuration, for example, certificate authority bundles, and application workloads that are common to all deployments.
+
. Build, publish, and sign a `bootc` operating system image using `podman` and `skopeo`.
. Create an operating system disk image by using `bootc-image-builder`.
. Build, publish, and sign an operating system disk image using `skopeo`.

[NOTE]
====
The operating system disk image has partitions, volumes, the file system, and the initial `bootc` image.
You only need to create the operating system disk image once, during provisioning.
For later device updates, you only need the `bootc` operating system image, which has the files in the file system.
====
