:_mod-docs-content-type: PROCEDURE

[id="proc-controller-inv-source-aap"]

= {PlatformName}

[role="_abstract"]
An inventory that is sourced from {PlatformName} uses the {PlatformName} inventory plugin to gather inventory data from the {PlatformName} platform.

Use the following procedure to configure an {ControllerName}-sourced inventory.

.Procedure
. From the navigation panel, select {MenuInfrastructureInventories}.
. Select the inventory name you want a source to and click the *Sources* tab.
. Click btn:[Create source].
. In the *Create source* page, select *{PlatformName}* from the *Source* list.
. The *Create source* window expands with additional fields.
Enter the following details:

* Optional: *Credential*: Choose from an existing {PlatformName} Credential.
For more information, see xref:controller-credentials[Managing user credentials].
. Optional: You can specify the verbosity, host filter, enabled variables or values, and update options as described in xref:proc-controller-add-source[Adding a source].
. Use the *Source Variables* field to override variables used by the `controller` inventory plugin.
Enter variables by using either JSON or YAML syntax.
Use the radio button to toggle between the two.
For more information about these variables, see link:https://console.redhat.com/ansible/automation-hub/repo/published/ansible/controller/content/inventory/controller[Controller inventory plugin].
This requires your Red Hat Customer login.
