:_mod-docs-content-type: PROCEDURE

[id="gw-setting-timeout-values"]

= Setting timeout values

[role="_abstract"]

Red Hat recommends that you configure your timeout values based on the performance needs of your authentication servers. 
While the installation program provides a way to set timeouts for the {PlatformNameShort} components, a system administrator must still review and adjust the individual authenticator timeouts to align with their specific environment.

.Procedure

* Configure authenticator timeouts: Adjust the timeout setting for each authenticator to a value that aligns with the expected response time of your external server.

** For LDAP, set the `OPT_NETWORK_TIMEOUT` in seconds. 
For example, `OPT_NETWORK_TIMEOUT`: 30 sets an LDAP timeout of 30 seconds. For more information, see link:{URLCentralAuth}/gw-configure-authentication#controller-set-up-LDAP[Configuring LDAP authentication].
** For TACACS+ authentication, if you want to change the timeout you have to do it through the {Gateway} API.
** For RADIUS authentication, the timeout is not changeable and is set to 5 seconds.
