:_mod-docs-content-type: PROCEDURE

[id="proc-controller-github-team-settings"]

= Configuring GitHub team authentication

[role="_abstract"]

To set up social authentication for a GitHub team, you must obtain an OAuth2 key and secret for a web application by using the instructions provided in link:https://docs.github.com/en/apps/using-github-apps/installing-your-own-github-app[registering the new application with GitHub].

The OAuth2 key (Client ID) and secret (Client Secret) are used to supply the required fields in the UI. To register the application, you must supply it with your webpage URL, which is the *Callback URL* shown in the Authenticator details for your authenticator configuration. See xref:gw-display-auth-details[Displaying authenticator details] for instructions on accessing this information.

Each key and secret must belong to a unique application and cannot be shared or reused between different authentication backends. The OAuth2 key (Client ID) and secret (Client Secret) are used to supply the required fields in the UI.

.Procedure

. From the navigation panel, select {MenuAMAuthentication}.
. Click btn:[Create authentication].
. Enter a *Name* for this authentication configuration. 
. Select *GitHub team* from the *Authentication type* list. The *Authentication details* section automatically updates to show the fields relevant to the selected authentication type.
+
//include::snippets/snip-gw-authentication-auto-migrate.adoc[]
+
. When the application is registered, GitHub displays the *Client ID* and *Client Secret*:
+
.. Copy and paste the GitHub Client ID into the GitHub OAuth2 Key field. 
.. Copy and paste the GitHub Client Secret into the GitHub OAuth2 Secret field. 
+
. Copy and paste GitHub’s team ID in the *GitHub OAuth2 Team ID* field.
. Enter the authorization scope for users in the GitHub OAuth2 Scope field. The default is `read:org`. 
+
include::snippets/snip-gw-authentication-additional-auth-fields.adoc[]
+
include::snippets/snip-gw-authentication-common-checkboxes.adoc[]
+
. Click btn:[Create Authentication Method].

include::snippets/snip-gw-authentication-verification.adoc[]

[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-authentication-next-steps.adoc[]
