:_mod-docs-content-type: PROCEDURE

[id="edge-manager-integrate-aap"]

= Integrating with {PlatformNameShort}

To integrate the {RedHatEdge} with your {PlatformNameShort} instance, follow these additional steps.

.Procedure

. Configure the integration settings by editing the configuration file:
+
[literal, options="nowrap" subs="+attributes"]
----
sudo vi /etc/flightctl/service-config.yaml
----
+
. Update the configuration file to integrate with {PlatformNameShort}:
+
[source,yaml]
----
global:
  baseDomain: <your-edge-manager-ip-or-domain> <1>
  auth:
    type: aap <2>
    insecureSkipTlsVerify: false <3>
    aap:
      apiUrl: https://your-aap-instance.example.com <4>
      externalApiUrl: https://your-aap-instance.example.com <5>
      oAuthApplicationClientId: <client-id-from-oauth-app> <6>
	    oAuthToken: <your-oauth-token> <7>
----
+
<1> The domain name or IP for the host, this is automatically set when the RPM is installed but you can override this. 
It is the only field that is mandatory.
<2> Set this to `aap` to enable {PlatformNameShort} authentication.
<3> Set to `false`.
Only set this to `true` to skip TLS certificate verification for the {PlatformNameShort} URLs. 
For production environments, consider configuring a CA certificate (see the Self-signed certificates section).
<4> The internal facing API URL for the running {PlatformNameShort} instance that makes requests against.
You can configure this URL to be an internally accessible URL for the running {PlatformNameShort} instance. 
For example, if there are separate internal or external ingresses.
<5> The externally accessible URL of your running {PlatformNameShort} instance.
<6> The Client ID of the OAuth application configured in {PlatformNameShort} for the {RedHatEdge}. 
If you do not have one yet, you can leave this empty and give an `oAuthToken` to allow the setup to create it.
<7> An OAuth token with write permissions for the "Default" organization in your {PlatformNameShort} instance. 
This is only needed if you want the setup process to automatically create the OAuth application. 
Once created, this token is no longer necessary.

+
. Start the services:
+
[literal, options="nowrap" subs="+attributes"]
----
sudo systemctl start flightctl.target
----
