:_mod-docs-content-type: REFERENCE

[id="ref-guidelines-hosts-groups"]

= Guidelines for hosts and groups

[role="_abstract"]
Follow these configuration guidelines to properly set up databases, {HubName}, {ControllerName}, {EDAcontroller}, and {Gateway} hosts for reliable {PlatformNameShort} installations.

*Databases*
* When using an external database, ensure the `[database]` sections of your inventory file are properly set up.
* To improve performance, do not colocate the database and the {ControllerName} on the same server.

[IMPORTANT]
====
When using an external database with {PlatformNameShort}, you must create and maintain that database. Ensure that you clear your external database when uninstalling the {PlatformNameShort}.
====

*{HubNameStart}*
* If there is an `[automationhub]` group, you must include the variables `automationhub_pg_host` and `automationhub_pg_port`.
* Add {HubNameMain} information in the `[automationhub]` group.
* Do not install {HubNameMain} and {ControllerName} on the same node.
* Provide a reachable IP address or fully qualified domain name (FQDN) for the `[automationhub]` and `[automationcontroller]` hosts to ensure that users can synchronize and install content from {HubNameMain} and {ControllerName} from a different node. 
+
The FQDN must not contain the `_` symbol, as it will not be processed correctly in Skopeo. You may use the `-` symbol, as long as it is not at the start or the end of the host name.
+
Do not use `localhost`.

*{PrivateHubNameStart}*
* Do not install {PrivateHubName} and {ControllerName} on the same node.
* You can use the same PostgreSQL (database) instance, but they must use a different (database) name.
* If you install {PrivateHubName} from an internal address, and have a certificate which only encompasses the external address, it can result in an installation you cannot use as a container registry without certificate issues.

[IMPORTANT]
====
You must separate the installation of {ControllerName} and {HubNameMain} because the `[database]` group does not distinguish between the two if both are installed at the same time. 

If you use one value in `[database]` and both {ControllerName} and {HubNameMain} define it, they would use the same database.
====

*{ControllerNameStart}*
* {ControllerNameStart} does not configure replication or failover for the database that it uses.
* {ControllerNameStart} works with any replication that you have.

*{EDAcontroller}*
* {EDAcontroller} must be installed on a separate server and cannot be installed on the same host as {HubName} and {ControllerName}.

*{GatewayStart}*
* The {Gateway} is the service that handles authentication and authorization for {PlatformNameShort}. It provides a single entry into the platform and serves the platform’s user interface.

*Clustered installations*
* When upgrading an existing cluster, you can also reconfigure your cluster to omit existing instances or instance groups. 
Omitting the instance or the instance group from the inventory file is not enough to remove them from the cluster. 
In addition to omitting instances or instance groups from the inventory file, you must also deprovision instances or instance groups before starting the upgrade. For more information, see xref:ref-deprovisioning[Deprovisioning nodes or groups]. 
Otherwise, omitted instances or instance groups continue to communicate with the cluster, which can cause issues with {ControllerName} services during the upgrade.
* If you are creating a clustered installation setup, you must replace `[localhost]` with the hostname or IP address of all instances. 
Installers for {ControllerName} and {HubName} do not accept `[localhost]`
All nodes and instances must be able to reach any others by using this hostname or address. 
You cannot use the localhost `ansible_connection=local` on one of the nodes. 
Use the same format for the host names of all the nodes.
+
Therefore, this does not work:
+
[options="nowrap" subs="+quotes,attributes"]
----
[automationhub]
localhost ansible_connection=local
hostA
hostB.example.com
172.27.0.4
----
+
Instead, use these formats:
+
[options="nowrap" subs="+quotes,attributes"]
----
[automationhub]
hostA
hostB
hostC
----
+
or
+
[options="nowrap" subs="+quotes,attributes"]
----
[automationhub]
hostA.example.com
hostB.example.com
hostC.example.com
----

