[id="ref-hub-variables"]

= {HubNameMain} variables

[cols="50%,50%",options="header"]
|====
| *Variable* | *Description*
| *`automationhub_admin_password`* | Required passwords must be enclosed in quotes when they are provided in plain text in the inventory file.

Use of special characters for `automationhub_admin_password` is limited. The password can include any printable ASCII character except `/`, `”`, or `@`.
| *`automationhub_api_token`* a| This variable can be used to provide the installer with an existing token.

For example, a regenerated token in Hub UI will invalidate an existing token. Use automationhub_api_token` to use that token in the installer the next time you run the installer.
|*`generate_automationhub_token` | When performing a fresh installation, a new token will automatically be generated by default. If you want the installer to regenerate a new token, set `generate_automationhub_token=true` and the installer will use it in the installation process.

| *`automationhub_auto_sign_collections`* | If a collection signing service is enabled, collections are not signed automatically by default.

Setting this parameter to `true` signs them by default.

Default = `false`.
| *`automationhub_backup_collections`* | _Optional_

{HubNameMain} provides artifacts in `/var/lib/pulp`. {ControllerNameStart} automatically backs up the artifacts by default.

You can also set `automationhub_backup_collections` to false and the backup/restore process does not then backup or restore `/var/lib/pulp`.

Default = `true`.
| *`automationhub_collection_download_count`* | _Optional_

Determines whether download count is displayed on the UI.

Default = `false`.
| *`automationhub_collection_seed_repository`* a| When you run the bundle installer, validated content is uploaded to the `validated` repository, and certified content is uploaded to the `rh-certified` repository.

By default, both certified and validated content are uploaded.

Possible values of this variable are 'certified' or 'validated'.

If you do not want to install content, set `automationhub_seed_collections` to `false` to disable the seeding.

If you only want one type of content, set `automationhub_seed_collections` to `true` and `automationhub_collection_seed_repository` to the type of content you do want to include.
| *`automationhub_collection_signing_service_key`* | If a collection signing service is enabled, you must provide this variable to ensure that collections can be properly signed.

`/absolute/path/to/key/to/sign`
| *`automationhub_collection_signing_service_script`* | If a collection signing service is enabled, you must provide this variable to ensure that collections can be properly signed.

`/absolute/path/to/script/that/signs`
| *`automationhub_create_default_collection_signing_service`* | Set this variable to true to create a collection signing service.

Default = `false`.
| *`automationhub_container_signing_service_key`* | If a container signing service is enabled, you must provide this variable to ensure that containers can be properly signed.

`/absolute/path/to/key/to/sign`
| *`automationhub_container_signing_service_script`* | If a container signing service is enabled, you must provide this variable to ensure that containers can be properly signed.

`/absolute/path/to/script/that/signs`
| *`automationhub_create_default_container_signing_service`* | Set this variable to true to create a container signing service.

Default = `false`.
| *`automationhub_disable_hsts`* | The default installation deploys a TLS enabled {HubNameMain}.
Use this variable if you deploy {HubName} with _HTTP Strict Transport Security_ (HSTS) web-security policy enabled.
This variable disables the HSTS web-security policy mechanism.

Default = `false`.
| *`automationhub_disable_https`* | _Optional_

If {HubNameMain} is deployed with HTTPS enabled.

Default = `false`.
| *`automationhub_enable_api_access_log`* | When set to `true`, this variable creates a log file at `/var/log/galaxy_api_access.log` that logs all user actions made to the platform, including their username and IP address.

Default = `false`.
| *`automationhub_enable_analytics`* | A Boolean indicating whether to enable pulp analytics for the version of pulpcore used in {HubName} in {PlatformNameShort} {PlatformVers}.

To enable pulp analytics, set `automationhub_enable_analytics` to true.

Default = `false`.
| *`automationhub_enable_unauthenticated_collection_access`* | Set this variable to true to enable unauthorized users to view collections.

Default = `false`.
| *`automationhub_enable_unauthenticated_collection_download`* | Set this variable to true to enable unauthorized users to download collections.

Default = `false`.
| *`automationhub_importer_settings`* | _Optional_

Dictionary of setting to pass to galaxy-importer.

At import time, collections can go through a series of checks.

Behavior is driven by `galaxy-importer.cfg` configuration.

Examples are `ansible-doc`, `ansible-lint`, and `flake8`.

This parameter enables you to drive this configuration.
| *`automationhub_pg_database`* | _Required_

The database name.

Default = `automationhub`.
| *`automationhub_pg_host`* | Required if not using an internal database.

The hostname of the remote PostgreSQL database used by {HubName}.

Default = `127.0.0.1`.
| *`automationhub_pg_password`* | The password for the {HubName} PostgreSQL database.

Use of special characters for `automationhub_pg_password` is limited.
The `!`, `#`, `0` and `@` characters are supported. Use of other special characters can cause the setup to fail.
| *`automationhub_pg_port`* | Required if not using an internal database.

Default = 5432.
| *`automationhub_pg_sslmode`* | Required.

Default = `prefer`.
| *`automationhub_pg_username`* | Required

Default = `automationhub`.
| *`automationhub_require_content_approval`* | _Optional_

Value is `true` if {HubName} enforces the approval mechanism before collections are made available.

By default when you upload collections to {HubName}, an administrator must approve it before they are made available to the users.

If you want to disable the content approval flow, set the variable to `false`.

Default = `true`.
| *`automationhub_seed_collections`* | A Boolean that defines whether or not preloading is enabled.

When you run the bundle installer, validated content is uploaded to the `validated` repository, and certified content is uploaded to the `rh-certified` repository.

By default, both certified and validated content are uploaded.

If you do not want to install content, set `automationhub_seed_collections` to `false` to disable the seeding.

If you only want one type of content, set `automationhub_seed_collections` to `true` and `automationhub_collection_seed_repository` to the type of content you do want to include.

Default = `true`.
| *`automationhub_ssl_cert`* | _Optional_

`/path/to/automationhub.cert`
Same as `web_server_ssl_cert` but for {HubName} UI and API.
| *`automationhub_ssl_key`* | _Optional_

`/path/to/automationhub.key`.

Same as `web_server_ssl_key` but for {HubName} UI and API.
| *`automationhub_ssl_validate_certs`* | For {PlatformName} 2.2 and later, this value is no longer used.

Set value to `true` if {HubName} must validate certificates when requesting itself because by default, {PlatformNameShort} deploys with self-signed certificates.

Default = `false`.
| *`automationhub_user_headers`* | List of nginx headers for {HubNameMain}'s web server. 

Each element in the list is provided to the web server's nginx configuration as a separate line. 

Default = empty list
| *`ee_from_hub_only`* | When deployed with {HubName,} the installer pushes {ExecEnvShort} images to {HubName} and configures {ControllerName} to pull images from the {HubName} registry.

To make {HubName} the only registry to pull {ExecEnvShort} images from, set this variable to `true`.

If set to `false`, {ExecEnvShort} images are also taken directly from Red Hat.

Default = `true` when the bundle installer is used.
| *`nginx_hsts_max_age`* | This variable specifies how long, in seconds, the system should be considered as an _HTTP Strict Transport Security_ (HSTS) host. That is, how long HTTPS is used exclusively for communication.

Default = 63072000 seconds, or two years.
| *`pulp_db_fields_key`* | Relative or absolute path to the Fernet symmetric encryption key that you want to import.
The path is on the Ansible management node.
It is used to encrypt certain fields in the database, such as credentials.
If not specified, a new key will be generated.

|====