:_mod-docs-content-type: REFERENCE

[id="ref-upgrade-2.4-to-2.5"]

= Upgrades from {PlatformNameShort} 2.4 to 2.5

[Note]
====
We recommend upgrading directly to 2.6, without using 2.5 as an intermediate step, as the upgrade process is less complex.
====

Upgrades from {PlatforNameShort} 2.4 to 2.5 enables the movement of administrators for each component with their existing component-level admin privileges maintained. 
However, escalation of privileges to {Gateway} administrator is not automatic during the upgrade process. 
This ensures a secure privilege escalation process that can be customized to meet the organization’s specific needs.

Escalation to {Gateway} admin must be manually configured post-upgrade. 
During the upgrade process, admin privileges for individual services are not automatically translated to platform administrator privileges. 
Escalation to {Gateway} admin must be granted by the platform administrator after upgrade and data movement. 
Each service admin retains the original scope of their access until the access is changed.

As a platform administrator, you can escalate a user’s privileges by selecting the {PlatformName} checkbox. Only a platform administrator can escalate privileges.

