[id="ref-gw-access-rules-apps-tokens"]

= Access rules for applications and tokens

Access rules for applications are as follows:

* System administrators can view and manipulate all applications in the system.
//[ddacosta-aap-38726] Org administrators do not have this access in gateway.
//* Organization administrators can view and manipulate all applications belonging to organization members.
* Other users can only view, update, and delete their own applications, but cannot create any new applications.
* Tokens, on the other hand, are resources used to authenticate incoming requests and mask the permissions of the underlying user.

Access rules for tokens are as follows:

* Users can create a token if they are able to view the related application and can also create a personal token for themselves.
* System administrators are able to view and manipulate every token in the system.
//[ddacosta-aap-38726] Org administrators do not have this access in gateway.
//* Organization administrators are able to view and manipulate all tokens belonging to organization members.
* System Auditors can view all tokens and applications.
* Other normal users are only able to view and manipulate their own tokens.

[NOTE]
====
Users can only view the token or refresh the token value at the time of creation.
====