[id="edge-manager-additional-fields"]

= List of additional supported fields

In addition to the metadata fields, each resource has its own unique set of fields that you can select, offering further flexibility in filtering and selection based on resource-specific attributes.

The following table lists the fields supported for filtering for each resource kind:

[width="100%",cols="39%,61%",options="header",]
|===
|Kind |Fields
|*Certificate Signing Request* |`status.certificate`

|*Device*
|`status.summary.status``status.applicationsSummary.status``status.updated.status``status.lastSeen``status.lifecycle.status`

|*Enrollment Request* |`status.approval.approved``status.certificate`

|*Fleet* |`spec.template.spec.os.image`

|*Repository* |`spec.type``spec.url`

|*Resource Sync* |`spec.repository`
|===

.Examples

.Example 1: Excluding a specific device by name

The following command filters out a specific device by its name:

[source,bash]
----
flightctl get devices --field-selector 'metadata.name!=c3tkb18x9fw32fzx5l556n0p0dracwbl4uiojxu19g2'
----

.Example 2: Filter by owner, labels, and creation timestamp

This command retrieves devices owned by `Fleet/pos-fleet`, located in the `us` region, and created in 2024:

[source,bash]
----
flightctl get devices --field-selector 'metadata.owner=Fleet/pos-fleet, metadata.creationTimestamp >= 2024-01-01T00:00:00Z, metadata.creationTimestamp < 2025-01-01T00:00:00Z' -l 'region=us'
----

.Example 3: Filter by Owner, Labels, and Device Status

This command retrieves devices owned by `Fleet/pos-fleet`, located in the `us` region, and with a `status.updated.status` of either `Unknown`
or `OutOfDate`:

[source,bash]
----
flightctl get devices --field-selector 'metadata.owner=Fleet/pos-fleet, status.updated.status in (Unknown, OutOfDate)' -l 'region=us'
----
