:_mod-docs-content-type: REFERENCE

[id="ref-controller-example-workload-reqs"]

= Example workload requirements

[role="_abstract"]
Learn how to calculate workload requirements for {ControllerName} based on a hypothetical workload.

For this example capacity planning exercise, use the following workload requirements: 

*Execution capacity*

The minimum execution capacity required is 60 units to support 10 concurrent jobs.

Derive the total capacity by summing the resource consumed by parallel execution forks and the base resource consumed by each job:

(10 x jobs * 5 x forks) + (10 x jobs * 1 x base task impact of a job) = (execution capacity)

*Control capacity*

* To control 10 concurrent jobs requires at least 10 units of control capacity.

* To calculate the number of events per hour that you need to support 300 managed hosts and 1,000 tasks per hour per host, use the following equation:

** 1000 tasks x 300 managed hosts per hour = 300,000 events per hour at minimum. 

** You must run the job to see exactly how many events it produces, because this is dependent on the specific task and verbosity. For example, a debug task printing “Hello World” produces 6 job events with the verbosity of 1 on one host. With a verbosity of 3, it produces 34 job events on one host. Therefore, you must estimate that the task produces at least 6 events. This would produce closer to 3,000,000 events per hour, or approximately 833 events per second.

*Determining quantity of execution and control nodes needed*

Reference the experimental results in the following table that shows the observed event processing rate of a single control node with 5 execution nodes of equal size (API Capacity column). 
The default “forks” setting of job templates is 5. 

Using this default, the maximum number of jobs a control node can dispatch to execution nodes makes 5 execution nodes of equal CPU and RAM use 100% of their capacity, arriving to the 1:5 ratio of control to execution capacity mentioned before.