[id="ref-controller-variables"]

= {ControllerNameStart} variables

[cols="50%,50%",options="header"]
|====
| *Variable* | *Description*
| *`admin_password`* | The password for an administration user to access the UI when the installation is complet

Passwords must be enclosed in quotes when they are provided in plain text in the inventory file.

Use of special characters for `admin_password` is limited. The password can include any printable ASCII character except `/`, `”`, or `@`.

|*`admin_email`* | The email address used for the admin user for automation controller.

| *`automation_controller_main_url`* | 

| *`nginx_http_port`* | The nginx HTTP server listens for inbound connections.

Default = 80
| *`nginx_https_port`* | The nginx HTTPS server listens for secure connections.

Default = 443
| *`nginx_hsts_max_age`* | This variable specifies how long, in seconds, the system must be considered as an _HTTP Strict Transport Security_ (HSTS) host. That is, how long HTTPS is used exclusively for communication.

Default = 63072000 seconds, or two years.
| *`nginx_user_headers`* | List of nginx headers for the {ControllerName} web server.

Each element in the list is provided to the web server's nginx configuration as a separate line. 

Default = empty list
| *`node_state`* | _Optional_

The status of a node or group of nodes.
Valid options are `active`, `deprovision` to remove a node from a cluster, or `iso_migrate` to migrate a legacy isolated node to an execution node.

Default = `active`.
| *`node_type`* | For `[automationcontroller]` group.

Two valid `node_types` can be assigned for this group.

A `node_type=control` means that the node only runs project and inventory updates, but not regular jobs.

A `node_type=hybrid` can run everything.

Default for this group = `hybrid`

For `[execution_nodes]` group:

Two valid `node_types` can be assigned for this group.

A `node_type=hop` implies that the node forwards jobs to an execution node.

A `node_type=execution` implies that the node can run jobs.

Default for this group = `execution`.
| *`peers`* | _Optional_

The `peers` variable is used to indicate which nodes a specific host or group connects to. Wherever this variable is defined, an outbound connection to the specific host or group is established.

This variable is used to add `tcp-peer` entries in the `receptor.conf` file used for establishing network connections with other nodes.

The peers variable can be a comma-separated list of hosts and groups from the inventory.
This is resolved into a set of hosts that is used to construct the `receptor.conf` file.

| *`pg_database`* | The name of the postgreSQL database.

Default = `awx`.
| *`pg_host`* | The postgreSQL host, which can be an externally managed database.
| *`pg_password`* | The password for the postgreSQL database.

Use of special characters for `pg_password` is limited.
The `!`, `#`, `0` and `@` characters are supported. 
Use of other special characters can cause the setup to fail.

NOTE

You no longer have to provide a `pg_hashed_password` in your inventory file at the time of installation, because PostgreSQL 13 can now store user passwords more securely.

When you supply `pg_password` in the inventory file for the installer, PostgreSQL uses the SCRAM-SHA-256 hash to secure that password as part of the installation process.
| *`pg_port`* | The postgreSQL port to use.

Default = 5432
| *`pg_ssl_mode`* | Choose one of the two available modes: `prefer` and `verify-full`.

Set to `verify-full` for client-side enforced SSL.

Default = `prefer`.
| *`pg_username`* | Your postgreSQL database username.

Default = `awx`.
| *`postgres_ssl_cert`* | Location of the postgreSQL SSL certificate.

`/path/to/pgsql_ssl.cert`
| *`postgres_ssl_key`* | Location of the postgreSQL SSL key.

`/path/to/pgsql_ssl.key`
| *`postgres_use_cert`* | Location of the postgreSQL user certificate.

`/path/to/pgsql.crt`
| *`postgres_use_key`* | Location of the postgreSQL user key.

`/path/to/pgsql.key`
| *`postgres_use_ssl`* | Determines if the connection between {{PlatformNameShort}} and the PostgreSQL database should use SSL. The default for this variable is false which means SSL is not used for PostgreSQL connections. When set to true, the platform connects to PostgreSQL using SSL.
| *`postgres_max_connections`* | Maximum database connections setting to apply if you are using installer-managed postgreSQL.

See link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/automation_controller_administration_guide/index#ref-controller-database-settings[PostgreSQL database configuration] in the {ControllerName} administration guide for help selecting a value.

Default for VM-based installations = 200 for a single node 
and 1024 for a cluster.
| *`receptor_listener_port`* | Port to use for receptor connection.

Default = 27199
| *`supervisor_start_retry_count`* | When specified, it adds `startretries = <value specified>` to the supervisor config file (/`etc/supervisord.d/tower.ini`).

See link:http://supervisord.org/configuration.html#program-x-section-values[program:x Section Values] for more information about `startretries`.

No default value exists.

| *`web_server_ssl_cert`* | _Optional_

`/path/to/webserver.cert`

Same as `automationhub_ssl_cert` but for web server UI and API.
| *`web_server_ssl_key`* | _Optional_

`/path/to/webserver.key`

Same as `automationhub_server_ssl_key` but for web server UI and API.
|====
