:_mod-docs-content-type: REFERENCE

[id="configuring-inventory-file"]
= Configuring the inventory file

[role="_abstract"]
You can control the installation of {PlatformNameShort} with inventory files. Inventory files define the information needed to customize the installation. For example, host details, certificate details, and various component-specific settings. 

Example inventory files are available in this document that you can copy and change to quickly get started.

Additionally, {GrowthTopology} and {EnterpriseTopology} inventory files are available in the following locations:

* In the downloaded installation program package:
** The default inventory file, named `inventory`, is for the {EnterpriseTopology} pattern. 
** To deploy the {GrowthTopology} (all-in-one) pattern, use the `inventory-growth` file instead.
* In link:{URLTopologies}/container-topologies[Container topologies] in _{TitleTopologies}_.

To use the example inventory files, replace the `< >` placeholders with your specific variables, and update the host names. 

Refer to the `README.md` file in the installation directory or link:{URLContainerizedInstall}/appendix-inventory-files-vars[Inventory file variables] for more information about optional and required variables.

== Inventory file for online installation for containerized {GrowthTopology} (all-in-one)

Use the example inventory file to perform an online installation for the containerized {GrowthTopology} (all-in-one):

include::snippets/inventory-cont-a-env-a.adoc[]

* `ansible_connection=local` -  Used for all-in-one installations where the installation program is run on the same node that hosts {PlatformNameShort}. 
** If the installation program is run from a separate node, do not include `ansible_connection=local`. In this case, use an SSH connection instead. 

[role="_additional-resources"]
.Additional resources
* link:{URLTopologies}/container-topologies#infrastructure_topology_5[Container {GrowthTopology}]

== Inventory file for online installation for containerized {EnterpriseTopology}

Use the example inventory file to perform an online installation for the containerized {EnterpriseTopology}:

include::snippets/inventory-cont-b-env-a.adoc[]

[role="_additional-resources"]
.Additional resources
* link:{URLTopologies}/container-topologies#infrastructure_topology_6[Container {EnterpriseTopology}]
* link:{URLPlanningGuide}/ha-redis_planning[Caching and queueing system]


== Performing an offline or bundled installation

To perform an offline installation, add the following under the `[all:vars]` group:

----
bundle_install=true
# The bundle directory must include /bundle in the path
bundle_dir=<full_path_to_the_bundle_directory>
----
