[id="ref-controller-file-directory-structure"]

= Ansible file and directory structure

To ensure reliable and consistent automation, follow these best practices for managing your content:

* Package reusable content, such as roles, modules, and plugins into Ansible Collections.
* Reference all necessary Collections for a project in the project's `requirements.yml` file. 
These dependencies are automatically installed into the Execution Environment (EE) at runtime, but only if they are not already present in the EE image.
* Do not import content from other projects or common file-system locations, such as `/opt`, at runtime. All content must be explicitly defined within the EE.
* Working directory: The playbook directory is used as the current working directory at runtime. 
However, always use the `playbook_dir` variable instead of relying on the current working directory path.

[WARNING]
====
{ControllerNameStart} does not support interactive features.

* Avoid using the `vars_prompt` feature, as {ControllerName} does not permit interactive questions. 
For user input, use link:{URLControllerUserGuide}/controller-job-templates#controller-surveys-in-job-templates[Surveys in job templates].
* Avoid using the `pause` feature without a timeout. 
{ControllerNameStart} does not permit canceling a pause interactively. 
If `pause` is necessary, you must set a timeout.
====
