[id="ref-general-inventory-variables"]

= General variables

[cols="50%,50%,50%",options="header"]
|====
| *RPM variable name* | *Container variable name* | *Description*
| |`bundle_dir` |The path to the bundle directory.

Default = `false`
| |`bundle_install` |Use offline installation. Set to `true` to enable offline installation. 

Default = `false`

| |`ca_tls_cert` | Define a Certification Authority certificate here along with a matching key in `ca_tls_key` when you want the installer to create leaf certificates for each product for you.

| |`ca_tls_key` | Define the key for a Certification Authority certificate here for the matching certificate in `ca_tls_cert` when you want the installer to create leaf certificates for each product for you.

| |`ca_tls_remote` |TLS CA remote files.

Default = `false`
| |`container_compress` |Container compression software.

Default = `gzip`
| |`container_keep_images` |Keep container images.

Default = `false`
| |`container_pull_images` |Pull newer container images.

Default = `true`
| |`custom_ca_cert` | Define a custom Certification Authority certificate here when you have the leaf certificates created for each product and need the certificate trust to be established.

| `enable_insights_collection` | | The default install registers the node to the {InsightsName} for the {PlatformName} Service if the node is registered with Subscription Manager. 

Set to `False` to disable.

Default = `true`
|`nginx_tls_protocols` | | Defines support for `ssl_protocols` in NGINX.

Values available `TLSv1`, `TLSv1.1`, `TLSv1.2`, `TLSv1.3`.

The TLSv1.1 and TLSv1.2 parameters only work when OpenSSL 1.0.1 or higher is used.

The TLSv1.3 parameter only works when OpenSSL 1.1.1 or higher is used.

If `nginx_tls-protocols = ['TLSv1.3']` only TLSv1.3 is enabled. To set more than one protocol use `nginx_tls_protocols = ['TLSv1.2', 'TLSv.1.3']`.

Default = `TLSv1.2`
| `nginx_user_http_config` | | List of NGINX configurations for `/etc/nginx/nginx.conf` under the http section. 

Each element in the list is provided into `http nginx config` as a separate line. 

Default = empty list

| `redis_cluster_ip` | `redis_cluster_ip` | The IPv4 address used by the Redis cluster to identify each host in the cluster.

Redis clusters cannot use hostnames or IPv6 addresses. When defining hosts in the `[redis]` group, use this variable to identify the IPv4 address if the default is not what you want. 

| `redis_mode` | `redis_mode` | The Redis mode to use for your {PlatformNameShort} installation.

Possible values are: `standalone` and `cluster`.

For more information about Redis, see link:{URLPlanningGuide}/ha-redis_planning[Caching and queueing system] in _{TitlePlanningGuide}_.

Default = `cluster`

| |`registry_auth` |Use registry authentication.

Default = `true`

| |`registry_ns_aap` |{PlatformNameShort} registry namespace.

Default = `ansible-automation-platform-25`
| |`registry_ns_rhel` |RHEL registry namespace.

Default = `rhel8`

| `registry_password` |`registry_password` | Required if performing an online non-bundled installation.

The password credential for access to the registry source defined in `registry_url`.

// This content is used in RPM installation
ifdef::aap-install[]
For more information, see link:{URLInstallationGuide}/assembly-platform-install-scenario#proc-set-registry-username-password[Setting registry_username and registry_password].
endif::aap-install[] 
// This content is used in Containerized installation
ifdef::container-install[]
For more information, see link:{URLContainerizedInstall}/assembly-aap-containerized-installation#proc-set-registry-username-password[Setting registry_username and registry_password].
endif::container-install[]

| `registry_verify_ssl` |`registry_tls_verify` |Verify registry TLS.

Default = `true`

| `registry_url` | `registry_url` | URL for the registry source. 

Default = `registry.redhat.io`

| `registry_username` |`registry_username` | Required if performing an online non-bundled installation.

The username credential for access to the registry source defined in `registry_url`.

// This content is used in RPM installation
ifdef::aap-install[]
For more information, see link:{URLInstallationGuide}/assembly-platform-install-scenario#proc-set-registry-username-password[Setting registry_username and registry_password].
endif::aap-install[] 
// This content is used in Containerized installation
ifdef::container-install[]
For more information, see link:{URLContainerizedInstall}/assembly-aap-containerized-installation#proc-set-registry-username-password[Setting registry_username and registry_password].
endif::container-install[]

| `routable_hostname` |`routable_hostname` | This variable is used if the machine running the installer can only route to the target host through a specific URL. For example, if you use short names in your inventory, but the node running the installer can only resolve that host by using a FQDN.

If `routable_hostname` is not set, it should default to `ansible_host`. If you do not set `ansible_host`, `inventory_hostname` is used as a last resort.

This variable is used as a host variable for particular hosts and not under the `[all:vars]` section. 

For further information, see link:https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#assigning-a-variable-to-one-machine-host-variables[Assigning a variable to one machine: host variables].
|====



