:_mod-docs-content-type: PROCEDURE

[id="ref-controller-team-mapping"]

= Team mapping

Team mapping is the mapping of team members (users) from authenticators. 

You can define the options for each team’s membership. For each team, you can specify which users are automatically added as members of the team and also which users can administer the team.

Team mappings can be specified separately for each account authentication.

When Team mapping is positively evaluated, a specified team and its organization are created, if they don’t exist if the related authenticator is allowed to create objects.


.Procedure

. After configuring the authentication details for your authentication type, select *Team* from the *Add authentication mapping* list. 
. Enter a unique rule *Name* to identify the rule.
. Select a *Trigger* from the list. See xref:gw-authenticator-map-triggers[Authenticator map triggers] for more information about map triggers.
. Select *Revoke* remove the user’s access to the selected organization role and deny user access to the system when the trigger conditions are not matched. 
. Select the *Team* and *Organization* to which matching users are added or blocked.
. Select a *Role* to be applied or removed for matching users (for example, *Team Admin* or *Team Member*).
. Click btn:[Next].

[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-mapping-next-steps.adoc[]



