:_mod-docs-content-type: REFERENCE

[id="controller-api-field-lookups"]

= Field lookups

[role="_abstract"]
Field lookups allow you to filter API results based on specific criteria.
You can use field lookups for more advanced queries, by appending the lookup to the field name:

----
?field__lookup=value
----

The following field lookups are supported:

* exact: Exact match (default lookup if not specified, see the following note for more information).
* iexact: Case-insensitive version of exact.
* contains: Field contains value.
* icontains: Case-insensitive version of contains.
* startswith: Field starts with value.
* istartswith: Case-insensitive version of startswith.
* endswith: Field ends with value.
* iendswith: Case-insensitive version of endswith.
* regex: Field matches the given regular expression.
* iregex: Case-insensitive version of regular expression.
* gt: Greater than comparison.
* gte: Greater than or equal to comparison.
* lt: Less than comparison.
* lte: Less than or equal to comparison.
* isnull: Check whether the given field or related object is null; expects a boolean value.
* in: Check whether the given field's value is present in the list provided; expects a list of items.
* You can specify boolean values as `True` or `1` for true, `False` or `0` for false (both case-insensitive).

For example, `?created__gte=2023-01-01` provides a list of items created after 1/1/2023.

You can specify null values as `None` or `Null` (both case-insensitive), though we recommend using the `isnull` lookup to explicitly check for null values.

You can specify lists (for the `in` lookup) as a comma-separated list of values.
Filtering based on the requesting user's level of access by query string parameter:

* `role_level`: Level of role to filter on, such as `admin_role`

[NOTE]
====
Earlier releases of {PlatformNameShort} returned queries with *_exact* results by default. 
As a workaround, set the `limit` to `?limit_exact` for the default filter. 
For example, `/api/controller/v2/jobs/?limit_exact=example.domain.com` results in:

----
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
...
----
====


