:_mod-docs-content-type: REFERENCE

[id="controller-cpu-relative-capacity"]

= CPU relative capacity

[role="_abstract"]
{ControllerName} uses the `cpu_capacity` algorithm to determine the relative CPU capacity of managed nodes. 
This information is used to optimize the distribution of tasks across the available nodes.

Ansible workloads are often processor-bound.
In such cases, you can reduce the simultaneous workload to enable more tasks to run faster and reduce the average time-to-completion of those jobs.

Just as the `mem_capacity` algorithm adjusts the amount of memory required per fork, the `cpu_capacity` algorithm adjusts the amount of processing resources required per fork. 
The baseline value for this is four forks per core. 
The algorithm formula for this is:

----
cpus * fork_per_cpu
----

For example, a 4-core system looks like the following:

----
4 * 4 == 16
----

You can control the value of `fork_per_cpu` by setting the value of `SYSTEM_TASK_FORKS_CPU` which defaults to 4.
