:_mod-docs-content-type: REFERENCE

[id="ref-platform-system-requirements_{context}"]

= {PlatformName} system requirements

[role="_abstract"]
Your system must meet the following minimum system requirements to install and run {PlatformName}. 
A resilient deployment requires 10 virtual machines with a minimum of 16 gigabytes (GB) of RAM and 4 virtual CPUs (vCPU). 
See {LinkTopologies} for more information on topology options.


.Base system

[cols="20%,40%,40%", options="header"]
|====
| Type | Description | Notes 
h| Subscription | Valid {PlatformName} subscription |
h| Operating system  
a|
* {RHEL} 8.10 or later minor versions of {RHEL} 8
* {RHEL} 9.4 or later minor versions of {RHEL} 9 | {PlatformName} are also supported on OpenShift, see {LinkOperatorInstallation} for more information.
h| CPU architecture | x86_64, AArch64, s390x (IBM Z), ppc64le (IBM Power) |
h| Ansible-core | Ansible-core version {CoreUseVers} or later | {PlatformNameShort} uses the system-wide ansible-core package to install the platform, but uses ansible-core {CoreUseVers} for both its control plane and built-in execution environments.
h| Browser | A currently supported version of Mozilla Firefox or Google Chrome. |
h| Database | {PostgresVers} | {PlatformName} {PlatformVers} requires the external (customer supported) databases to have ICU support.
|====

.Virtual machine requirements

[cols="25%,10%,10%,10,45%", options="header"]
|===
| Component             | RAM   | vCPU | Disk IOPS |  Storage

| {GatewayStart}        | 16GB  | 4    | 3000   | 60GB minimum
| Control nodes         | 16GB  | 4    | 3000   | 80GB minimum with at least 20GB available under `/var/lib/awx`
| Execution nodes       | 16GB  | 4    | 3000   | 60GB minimum
| Hop nodes             | 16GB  | 4    | 3000   | 60GB minimum
| {HubNameStart}        | 16GB  | 4    | 3000   | 60GB minimum with at least 40GB allocated to `/var/lib/pulp`
| Database              | 16GB  | 4    | 3000   | 100GB minimum allocated to `/var/lib/pgsql`
| {EDAcontroller}       | 16GB  | 4    | 3000   | 60GB minimum
|===

[NOTE]
====
These are minimum requirements and can be increased for larger workloads in increments of 2x (for example 16GB becomes 32GB and 4 vCPU becomes 8vCPU). See the horizontal scaling guide for more information.
====

== Repository requirements

Enable the following repositories only when installing {PlatformName}:

* RHEL BaseOS

* RHEL AppStream

[NOTE]
====
If you enable repositories besides those mentioned above, the {PlatformName} installation could fail unexpectedly. 
====

The following are necessary for you to work with project updates and collections:

* Ensure that the link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/planning_your_installation/ref-network-ports-protocols_planning#ref-network-ports-protocols_planning[Network ports and protocols] listed in _Table 6.3. Automation Hub_ are available for successful connection and download of collections from {HubName} or {Galaxy} server.

== Additional notes for {PlatformName} requirements

* The {PlatformNameShort} database backups are staged on each node at `/var/backups/automation-platform` through the variable `backup_dir`. You might need to mount a new volume to `/var/backups` or change the staging location with the variable `backup_dir` to prevent issues with disk space before running the `./setup.sh -b` script.

* If performing a bundled {PlatformNameShort} installation, the installation setup.sh script attempts to install ansible-core (and its dependencies) from the bundle for you.

* If you have installed Ansible-core manually, the {PlatformNameShort} installation setup.sh script detects that Ansible has been installed and does not attempt to reinstall it.

[NOTE]
====
You must use Ansible-core, which is installed by using DNF.
Ansible-core version {CoreUseVers} is required for versions {PlatformVers} and later.
====
