:_mod-docs-content-type: REFERENCE

[id="operator-aap-troubleshooting_{context}"]

= Review {Gateway} FAQs

[role="_abstract"]

Manage your {PlatformNameShort} deployment and troubleshoot common issues with these frequently asked questions. Learn about resource management, logging, and error recovery for your components.

If I delete my {PlatformNameShort} deployment will I still have access to {ControllerName}?::
No, {ControllerName}, {HubName}, and {EDAName} are nested within the deployment and are also deleted.

How must I manage parameters when adding or removing them in the {PlatformNameShort} custom resource (CR) hierarchy?::
When _adding_ parameters, you can add it to the {PlatformNameShort} custom resource (CR) only and those parameters will work their way down to the nested CRs.

When _removing_ parameters, you have to remove them both from the {PlatformNameShort} CR _and_ the nested CR, for example, the *Automation Controller* CR.

Something went wrong with my deployment but I'm not sure what, how can I find out?::
You can follow along in the command line while the operator is reconciling, this can be helpful for debugging. 
Alternatively you can click into the deployment instance to see the status conditions being updated as the deployment goes on.

Is it still possible to view individual component logs?::
When troubleshooting you should examine the *{PlatformNameShort}* instance for the main logs and then each individual component (*EDA*, *AutomationHub*, *AutomationController*) for more specific information. 

Where can I view the condition of an instance?::
To display status conditions click into the instance, and look under the *Details* or *Events* tab.
Alternatively, to display the status conditions you can run the get command:
`oc get automationcontroller <instance-name> -o jsonpath=Pipe "| jq"`

Can I track my migration in real time?::
To help track the status of the migration or to understand why migration might have failed you can look at the migration logs as they are running. Use the logs command:
`oc logs fresh-install-controller-migration-4.6.0-jwfm6 -f`

I have configured my SAML but authentication fails with this error: "Unable to complete social auth login" What can I do?::
You must update your {PlatformNameShort} instance to include the `REDIRECT_IS_HTTPS` extra setting. See link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#proc-operator-enable-https-redirect[Enabling single sign-on (SSO) for {Gateway} on {OCPShort}] for help with this. 