:_mod-docs-content-type: REFERENCE

[id="ref-controller-troubleshoot-logging"]

= Troubleshooting logging

[role="_abstract"]
This section provides information to help troubleshoot logging issues in {ControllerName}.

*Logging Aggregation*

If you have sent a message with the test button to your configured logging service through http or https, but did not receive the message, check the `/var/log/tower/rsyslog.err` log file. 
This is where errors are stored if they occurred when authenticating rsyslog with an http or https external logging service. 
Note that if there are no errors, this file does not exist.

*API 4XX Errors*

You can include the API error message for 4XX errors by modifying the log format for those messages. 
Refer to the link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/{PlatformVers}/html/configuring_automation_execution/assembly-controller-logging-aggregation#proc-controller-api-4xx-error-config[API 4XX Error Configuration].

*LDAP*

You can enable logging messages for the LDAP adapter. 
For more information, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/{PlatformVers}/html/configuring_automation_execution/assembly-controller-logging-aggregation#proc-controller-api-4xx-error-config[API 4XX Error Configuration].

*SAML*

You can enable logging messages for the SAML adapter the same way you can enable logging for LDAP. 
//Refer to the xref:controller-enable-logging-LDAP[Enabling logging for LDAP] section for more detail.