:_mod-docs-content-type: REFERENCE

[id="ref-controller-user-roles"]

= Adding roles for a user

You can grant access for users to use, read, or write credentials by assigning roles to them.

[NOTE]
====
Users can not be assigned to an organization by adding roles. Refer to the steps provided in link:{URLCentralAuth}/gw-managing-access#proc-controller-add-organization-user[Adding a user to an organization] for detailed instructions.
====

.Procedure
. From the navigation panel, select {MenuAMUsers}.
. From the *Users* list view, click on the user to which you want to add roles.
. Select the *Roles* tab to display the set of roles assigned to this user. These provide the ability to read, modify, and administer resources.
. To add new roles, click btn:[Add roles].
+
include::snippets/snip-gw-roles-note-multiple-components.adoc[]
+
. Select a Resource type and click btn:[Next]. 
. Select the resources that will receive new roles and click btn:[Next].
. Select the roles that will be applied to the resources and click btn:[Next].
. Review the settings and click btn:[Finish].
+
The Add roles dialog displays indicating whether the role assignments were successfully applied. Click btn:[Close] to close the dialog.
