:_mod-docs-content-type: PROCEDURE

[id="ref-controller-organization-mapping"]

= Organization mapping

You can control which users are placed into which {PlatformNameShort} organizations based on attributes like their username and email address or based on groups provided from an authenticator. 

When organization mapping is positively evaluated, a specified organization is created, if it does not exist if the authenticator tied to the map is allowed to create objects.

.Procedure

. After configuring the authentication details for your authentication type, select *Organization* from the *Add authentication mapping* list. 
. Enter a unique rule *Name* to identify the rule.
. Select a *Trigger* from the list. See xref:gw-authenticator-map-triggers[Authenticator map triggers] for more information about map triggers.
. Select *Revoke* to remove the users access to the selected organization role  when the trigger conditions are not matched.
. Select the *Organization* to which matching users are added or blocked.
. Select a *Role* to be applied or removed for matching users (for example, *Organization Admin* or *Organization Member*).
. Click btn:[Next].

[role="_additional-resources"]
.Next steps
include::snippets/snip-gw-mapping-next-steps.adoc[]


