:_mod-docs-content-type: REFERENCE

[id="ref-optional-gather-collectors"]

= Optional collectors for `gather` command

You can use the following optional collectors for the `gather` command:

* `main_jobhostsummary`
** If present by default, this incrementally collects the `main_jobhostsummary` table from the {ControllerName} database, containing information about jobs runs and managed nodes automated.
* `main_host`
** This collects daily snapshots of the `main_host` table from the {ControllerName} database and has managed nodes/hosts present across {ControllerName} inventories,
* `main_jobevent`
** This incrementally collects the `main_jobevent` table from the {ControllerName} database and contains information about which modules, roles, and ansible collections are being used.
* `main_indirectmanagednodeaudit`
** This incrementally collects the `main_indirectmanagednodeaudit` table from the {ControllerName} database and contains information about indirectly managed nodes,

----
# Example with all optional collectors
export METRICS_UTILITY_OPTIONAL_COLLECTORS="main_host,main_jobevent,main_indirectmanagednodeaudit"
----
