:_mod-docs-content-type: REFERENCE

[id="ref-upgrade-authentication-movement-2.4-to-2.6"]

= Authentication movement

During an upgrade from {PlatformNameShort} 2.4 to 2.6, all authentication provider configurations and their associated user, organization, and team mappings are migrated from the legacy controller to the new {Gateway}.

.Prerequisites

. You have created a local administrator account and verified that you can log in to the new environment using local authentication. The default administrator account from the inventory file can also be used.
. You have enabled the local authenticator in the target environment to ensure a fallback login method is available.
. You have performed a full backup of your existing environment.
+
[WARNING]
====
This is a critical step for data recovery in case any issues occur during the migration process.
====

.Post upgrade

* *Update the callback URLs* in your _Identity Provider_ (IdP) configurations after the migration. This is necessary for OAuth and SSO providers to function correctly with the new platform gateway architecture. For more information, see [Updating callback URLs for OAuth and SSO providers][linkTBD].
* *Reestablish custom certificates for LDAPS* if your LDAP authentication uses custom certificates in the system's trust store. This configuration is not automatically migrated and you must manually reestablish it.

The migration of existing authentication configurations from a Red Hat Ansible Automation Platform 2.4 automation controller to the new 2.6 platform gateway is automated. The following tables show how settings and mappings from the old automation controller schema are transformed to fit the new {Gateway} API schema.

*Authentication type: OIDC*

*General settings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
SOCIAL_AUTH_OIDC_KEY: "client-id"
SOCIAL_AUTH_OIDC_SECRET: “client-secret"
SOCIAL_AUTH_OIDC_OIDC_ENDPOINT: "https://idp.example.com"
SOCIAL_AUTH_OIDC_VERIFY_SSL: true
---- a| 
----
"configuration": {
  "OIDC_ENDPOINT": "https://idp.example.com",
  "KEY": "client-id",
  "SECRET": "client-secret",
  "VERIFY_SSL": true
}
----
|====

*Mappings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
AUTH_LDAP_ORGANIZATION_MAP:
 "LDAP Organization":
     users: true
---- a| 
----

  "name": "Default - Users (users)",
  "map_type": "organization",
  "order": 1,
  "authenticator": -1,
  "triggers": {
    "users": true
  },
  "organization": "Default",
  "team": null,
  "role": "Organization Member",
  "revoke": true
}
----
a| ----
SOCIAL_AUTH_SAML_USER_FLAGS_BY_ATTR:
 is_superuser_attr: "is_superuser"
 is_superuser_value: "true"
---- a| ----
{
  "name": "is_superuser - role",
  "authenticator": -1,
  "revoke": true,
  "map_type": "is_superuser",
  "team": null,
  "organization": null,
  "triggers": {
    "attributes": {
      "is_superuser": {
        "has_or": [
          "true"
        ]
      }
    }
  },
  "order": 2
}
----
|====


*Authentication type: LDAP*

*General settings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----


*Authentication type: Github*
AUTH_LDAP_SERVER_URI: "ldap://ldap.example.com:389"
AUTH_LDAP_BIND_DN: "cn=admin,dc=example,dc=org"
AUTH_LDAP_BIND_PASSWORD: "password"
AUTH_LDAP_START_TLS: false
AUTH_LDAP_USER_SEARCH: [
  "ou=users,dc=example,dc=org", 
  "SCOPE_SUBTREE", "(cn=%(user)s)"
]
AUTH_LDAP_USER_ATTR_MAP: {
  "first_name": "givenName", 
  "last_name": "sn", 
  "email": "mail"
}
---- a| ----
"configuration": {
  "SERVER_URI": "ldap://ldap.example.com:389",
  "BIND_DN": "cn=admin,dc=example,dc=org",
  "BIND_PASSWORD": "password",
  "START_TLS": false,
  "USER_SEARCH": [
    "ou=users,dc=example,dc=org",
    "SCOPE_SUBTREE",
   "(cn=%(user)s)"
  ],
  "USER_ATTR_MAP": {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
  }
}
----
|====

*Mappings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
AUTH_LDAP_ORGANIZATION_MAP:
 "LDAP Organization":
     users: true
     admins:
     - "cn=awx_org_admins,ou=groups,dc=example,dc=org"
---- a| ----
{
  "name": "LDAP Organization - Admins cn=awx_org_admins,ou=groups,dc=example,dc=org",
  "map_type": "organization",
  "order": 1,
  "authenticator": -1,
  "triggers": {
    "groups": {
      "has_or": [
        "cn=awx_org_admins,ou=groups,dc=example,dc=org"
      ]
    }
  },
  "organization": "LDAP Organization",
  "team": null,
  "role": "Organization Admin",
  "revoke": false
}
---- a| ----
AUTH_LDAP_USER_FLAGS_BY_GROUP:
  is_superuser:
    - 'cn=awx_admins,ou=groups,dc=example,dc=org'
---- a| ----
{
  "name": "is_superuser - role",
  "authenticator": -1,
  "revoke": true,
  "map_type": "is_superuser",
  "team": null,
  "organization": null,
  "triggers": {
    "groups": {
   "has_or": [
        "cn=awx_admins,ou=groups,dc=example,dc=org"
      ]
    }
  },
  "order": 2
}
----
|====

*Authentication type: SAML*

*General settings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
SOCIAL_AUTH_SAML_ENABLED_IDPS:
  Keycloak: null
  entity_id: 'https://idp.example.com/auth/realms/awx'
  url: 'https://idp.example.com/auth/realms/awx/protocol/saml'
  x509cert: MIICert...
  attr_username: username
  attr_email: email
SOCIAL_AUTH_SAML_SP_ENTITY_ID: 'https://controller.example.com:8043'
SOCIAL_AUTH_SAML_SP_PUBLIC_CERT: MIICertPublic...
SOCIAL_AUTH_SAML_SP_PRIVATE_KEY: MIIKeyPrivate...
---- a| ----
"configuration": {
  "IDP_URL": "https://idp.example.com/auth/realms/awx/protocol/saml",
  "IDP_X509_CERT": "-----BEGIN CERTIFICATE-----\nMIICert...\n-----END CERTIFICATE-----",
  "IDP_ENTITY_ID": "https://idp.example.com/auth/realms/awx",
  "IDP_ATTR_EMAIL": "email",
  "IDP_ATTR_USERNAME": "username",
  "SP_ENTITY_ID": "https://controller.example.com:8043",
  "SP_PUBLIC_CERT": "MIICertPublic...",
  "SP_PRIVATE_KEY": "MIIKeyPrivate..."
}
----
|====

*Mappings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
SOCIAL_AUTH_SAML_ORGANIZATION_MAP:
 "Default":
    users: true
---- a| ----
{
  "name": "Default - Users (users)",
  "map_type": "organization",
  "order": 1,
  "authenticator": -1,
  "triggers": {
    "users": true
  },
  "organization": "Default",
  "team": null,
  "role": "Organization Member",
  "revoke": true
}
----
a| ----
SOCIAL_AUTH_SAML_USER_FLAGS_BY_ATTR:
 is_superuser_attr: "is_superuser"
 is_superuser_value: "true"
---- a| ----
{
  "name": "is_superuser - role",
  "authenticator": -1,
  "revoke": true,
  "map_type": "is_superuser",
  "team": null,
  "organization": null,
  "triggers": {
    "attributes": {
      "is_superuser": {
        "has_or": [
          "true"
        ]
      }
    }
  },
  "order": 2
}
----
|====

*Authentication type: GitHub*

*General settings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
SOCIAL_AUTH_GITHUB_KEY: client-id
SOCIAL_AUTH_GITHUB_SECRET: client-secret
SOCIAL_AUTH_GITHUB_SCOPE:
  - 'user:email'
  - 'read:org'
---- a| ----
{
  "configuration": {
    "KEY": "client-id",
    "SECRET": "client-secret",
    "SCOPE": [
      "user:email",
      "read:org"
    ]
  }
}
----
|====

*Mappings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
SOCIAL_AUTH_GITHUB_ORGANIZATION_MAP:
 "MyOrg":
     users: true
     admins:
     - "admin-team"
---- a| ----
{
  "name": "MyOrg - Admins admin-team",
  "map_type": "organization",
  "order": 1,
  "authenticator": -1,
  "triggers": {
    "users": {
      "has_or": [
        "admin-team"
      ]
    }
  },
  "organization": "MyOrg",
  "team": null,
  "role": "Organization Admin",
  "revoke": false
}
----
a| ----
SOCIAL_AUTH_GITHUB_TEAM_MAP:
 "Developers":
     organization: "MyOrg"
     users:
     - "dev-team"
---- a| ----
{
  "name": "MyOrg - Developers dev-team",
  "map_type": "team",
  "order": 2,
  "authenticator": -1,
  "triggers": {
    "users": {
      "has_or": [
        "dev-team"
      ]
    }
  },
  "organization": "MyOrg",
  "team": "Developers",
  "role": "Team Member",
  "revoke": false
}
----
|====

*Authentication type: Azure AD*

*General settings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
SOCIAL_AUTH_AZUREAD_OAUTH2_KEY: "application-id"
SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET: "client-secret"
---- a| ----
"configuration": {
  "KEY": "application-id",
  "SECRET": "client-secret",
  "GROUPS_CLAIM": "groups"
}
----
|====

*Mappings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
SOCIAL_AUTH_AZUREAD_OAUTH2_ORGANIZATION_MAP:
 "Azure Organization":
     users: true
---- a| ----
{
  "name": "Azure Organization - Users (users)",
  "map_type": "organization",
  "order": 1,
  "authenticator": -1,
  "triggers": {
    "users": true
  },
  "organization": "Azure Organization",
  "team": null,
  "role": "Organization Member",
  "revoke": false
}
----
a| ----
SOCIAL_AUTH_AZUREAD_OAUTH2_TEAM_MAP:
  "Admin Team":
    organization: "Azure Organization"
    users:
    - "admin@company.com"
---- a| ----
{
  "name": "Azure Organization - Admin Team admin@company.com",
  "map_type": "team",
  "order": 2,
  "authenticator": -1,
  "triggers": {
    "emails": {
      "has_or": [
        "admin@company.com"
      ]
    }
  },
  "organization": "Azure Organization",
  "team": "Admin Team",
  "role": "Team Member",
  "revoke": false
}
----
|====

*Authentication type: RADIUS*

*General settings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
RADIUS_SERVER: "radius.example.com"
RADIUS_PORT: 1812
RADIUS_SECRET: "shared-secret"
---- a| ----
"configuration": {
  "SERVER": "radius.example.com",
  "PORT": 1812,
  "SECRET": "shared-secret"
}
----
|====

*Mappings*

RADIUS authentication does not support user mappings in either {ControllerName} 2.4 or {GatewayStart} 2.6.

*Authentication type: TACAC+*

*General settings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
TACACSPLUS_HOST: "tacacs.example.com"
TACACSPLUS_PORT: 49
TACACSPLUS_SECRET: "shared-secret"
TACACSPLUS_SESSION_TIMEOUT: 5
TACACSPLUS_AUTH_PROTOCOL: "ascii"
TACACSPLUS_REM_ADDR: false
---- a| ----
"configuration": {
  "HOST": "tacacs.example.com",
  "PORT": 49,
  "SECRET": "shared-secret",
  "SESSION_TIMEOUT": 5,
  "AUTH_PROTOCOL": "ascii",
  "REM_ADDR": false
}
----
|====

*Mappings*

TACACS+ authentication does not support user mappings in either {ControllerName} 2.4 or {GatewayStart} 2.6.

*Authentication type: Google OAuth2*

*General settings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "client-id"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "client-secret"
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE: ["profile", "email"]
---- a| ----
{
  "configuration": {
    "KEY": "client-id",
    "SECRET": "client-secret",
    "REDIRECT_STATE": true,
    "SCOPE": [
      "profile",
      "email"
    ]
  }
}
----
|====

*Mappings*

[cols="50%,50%",options="header"]
|====
| {ControllerNameStart} 2.4 | {GatewayStart} 2.6
a| ----
SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP:
 "Google Org":
     users: true
---- a| ----
{
  "name": "Google Org - Users (users)",
  "map_type": "organization",
  "order": 1,
  "authenticator": -1,
  "triggers": {
    "users": true
  },
  "organization": "Google Org",
  "team": null,
  "role": "Organization Member",
  "revoke": false
}
----
a| -----
SOCIAL_AUTH_GOOGLE_OAUTH2_TEAM_MAP:
 "Engineers":
     organization: "Google Org"
     users: true
---- a| ----
{
  "name": "Google Org - Engineers (users)",
  "map_type": "team",
  "order": 2,
  "authenticator": -1,
  "triggers": {
    "users": true
  },
  "organization": "Google Org",
  "team": "Engineers",
  "role": "Team Member",
  "revoke": false
}
----
|====