:_mod-docs-content-type: REFERENCE

[id="controller-backup-restore-considerations"]

= Considerations for backup and restore

[role="_abstract"]
Consider the following points when you backup and restore your system:

Disk space:: Review your disk space requirements to ensure you have enough room to backup configuration files, keys, other relevant files, and the database of the {PlatformNameShort} installation.

System credentials:: Confirm you have the required system credentials when working with a local database or a remote database. 
On local systems, you might need `root` or `sudo` access, depending on how credentials are set up. 
On remote systems, you might need different credentials to grant you access to the remote system you are trying to backup or restore.
+
[NOTE]
====
The {PlatformNameShort} database backups are staged on each node at `/var/backups/automation-platform` through the variable `backup_dir`. You might need to mount a new volume to `/var/backups` or change the staging location with the variable `backup_dir` to prevent issues with disk space before running the `./setup.sh -b` script.
====

Version:: You must always use the most recent minor version of a release to backup or restore your {PlatformNameShort} installation version. 
For example, if the current platform version you are on is 2.0.x, only use the latest 2.0 installer.

File path:: When using `setup.sh` to do a restore from the default restore file path, `/var/lib/awx`, `-r` is still required to do the restore, but it no longer accepts an argument. 
If a non-default restore file path is needed, you must provide this as an extra_var (`root@localhost:~# ./setup.sh -e 'restore_backup_file=/path/to/nondefault/backup.tar.gz' -r`).

Directory:: If the backup file is placed in the same directory as the `setup.sh` installer, the restore playbook automatically locates the restore files. 
In this case, you do not need to use the `restore_backup_file` extra var to specify the location of the backup file.
