:_mod-docs-content-type: REFERENCE

[id="ref-editing-installer-inventory-file_{context}"]


= Editing the {PlatformName} installer inventory file

[role="_abstract"]
You can use the {PlatformName} installer inventory file to specify your installation scenario.


== For an RPM installation

_Procedure_

*RPM installed package*

-----
$ cd /opt/ansible-automation-platform/installer/
-----

*Bundled installer*

-----
$ cd ansible-automation-platform-setup-bundle-<latest-version>
-----

*Online installer*

-----
$ cd ansible-automation-platform-setup-<latest-version>
-----
ifdef::mesh-VM[]
== For online installations

*For online installations*

----
cd <path-to-source-file>/ansible-automation-platform-containerized-setup-<version_number>
----

*For offline or bundled installations*

----
cd <path-to-source-file/ansible-automation-platform-containerized-setup-bundle-<version_number>-<arch_name>
----
endif::mesh-VM[]
. Open the `inventory` file with a text editor.
. Edit the `inventory` file parameters to specify your installation scenario. 
+
For containerized installation, see link:{URLContainerizedInstall}/preparing-containerized-installation#configuring-inventory-file[Configuring the inventory file]
//ifdef::mesh-VM[]
//For further information, see link:{URLInstallationGuide}/assembly-platform-install-scenario#proc-editing-installer-inventory-file_platform-install-scenario[Editing the {PlatformName} installer inventory file]
//endif::mesh-VM[]
ifdef::aap-install[]
You can use one of the supported xref:con-install-scenario-examples[Installation scenario examples] as the basis for your `inventory` file.
endif::aap-install[]

[role="_additional-resources"]
.Additional resources
//This will need updating, but if RPOM install is deprrecated, where will the information
* link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html/rpm_installation/appendix-inventory-files-vars[Inventory file variables]
