:_mod-docs-content-type: REFERENCE

[id="edge-manager-supported-operators"]

= Supported operators

[role="_abstract"]

Learn the operators and corresponding symbols you can use to construct sophisticated field selectors when querying or filtering {RedHatEdge} resources. 
This enables precise and flexible control over resource selection.

[width="100%",cols="24%,17%,59%",options="header",]
|===
|Operator |Symbol |Description
|Exists |`exists` |Checks if a field exists

|DoesNotExist |`!` |Checks if a field does not exist

|Equals |`=` |Checks if a field is equal to a value

|DoubleEquals |`==` |Another form of equality check

|NotEquals |`!=` |Checks if a field is not equal to a value

|GreaterThan |`>` |Checks if a field is greater than a value

|GreaterThanOrEquals |`>=` |Checks if a field is greater than or equal to a value

|LessThan |`<` |Checks if a field is less than a value

|LessThanOrEquals |`<=` |Checks if a field is less than or equal to a value

|In |`in` |Checks if a field is within a list of values

|NotIn |`notin` |Checks if a field is not in a list of values

|Contains |`contains` |Checks if a field has a value

|NotContains |`notcontains` |Checks if a field does not contain a value
|===

== Operators usage by field type

Each field type supports a specific subset of operators:

[width="100%",cols="20,60%,20%",options="header",]
|===
|Field Type |Supported Operators |Value
|*String* |`Equals`: Matches if the field value is an exact match to the specified string. 

`DoubleEquals`: Matches if the field value is an exact match to the specified string (alternative to `Equals`). 

`NotEquals`: Matches if the field value is not an exact match to the specified string. 

`In`: Matches if the field value matches at least one string in the list. 

`NotIn`: Matches if the field value does not match any of the strings in the list. 

`Contains`: Matches if the field value has the specified substring.

`NotContains`: Matches if the field value does not contain the specified substring. 

`Exists`: Matches if the field is present. 

`DoesNotExist`: Matches if the field is not present. |Text
string

|*Timestamp* |`Equals`: Matches if the field value is an exact match to the specified timestamp. 

`DoubleEquals`: Matches if the field value is an exact match to the specified timestamp (alternative to `Equals`).

`NotEquals`: Matches if the field value is not an exact match to the specified timestamp. 

`GreaterThan`: Matches if the field value is after the specified timestamp. 

`GreaterThanOrEquals`: Matches if the field value is after or equal to the specified timestamp. 

`LessThan`: Matches if the field value is before the specified timestamp.

`LessThanOrEquals`: Matches if the field value is before or equal to the specified timestamp. 

`In`: Matches if the field value matches at least one timestamp in the list. 

`NotIn`: Matches if the field value does not match any of the timestamps in the list. 

`Exists`: Matches if the field is present. 

`DoesNotExist`: Matches if the field is not present. |RFC 3339 format

|*Number* |`Equals`: Matches if the field value equals the specified number. 

`DoubleEquals`: Matches if the field value equals the specified number (alternative to `Equals`). 

`NotEquals`: Matches if the field value does not equal to the specified number. 

`GreaterThan`: Matches if the field value is greater than the specified number.

`GreaterThanOrEquals`: Matches if the field value is greater than or equal to the specified number. 

`LessThan`: Matches if the field value is less than the specified number. 

`LessThanOrEquals`: Matches if the field value is less than or equal to the specified number. 

`In`: Matches if the field value equals at least one number in the list. 

`NotIn`: Matches if the field value does not equal any numbers in the list.

`Exists`:Matches if the field is present. 

`DoesNotExist`: Matches if the field is not present. |Number format

|*Boolean* a|`Equals`: Matches if the value is `true` or `false`.

`DoubleEquals`: Matches if the value is `true` or `false` (alternative to `Equals`). 

`NotEquals`: Matches if the value is the opposite of the specified value. 

`In`: Matches if the value (`true` or `false`) is in the list.

[NOTE]
====
The list can only contain `true` or `false`, so this operator is limited in use. 
====

`NotIn`: Matches if the value is not in the list. 

`Exists`: Matches if the field is present. 

`DoesNotExist`: Matches if the field is not present. |Boolean format (`true`, `false`)

|*Array* a|`Contains`: Matches if the array has the specified value.

`NotContains`: Matches if the array does not contain the specified value. `In`: Matches if the array overlaps with the specified values.

`NotIn`: Matches if the array does not overlap with the specified values. `Exists`: Matches if the field is present. 

`DoesNotExist`:Matches if the field is not present.

[NOTE]
====
Using `Array[Index]` treats the element as the type defined for the array elements. For example string, timestamp, number, or boolean.
====
|Array element
|===
