:_mod-docs-content-type: REFERENCE

[id="edge-manager-device-templates"]

= Device templates

[role="_abstract"]

A device template of a fleet has a device specification that is applied to all devices in the fleet when the template is updated.

For example, you can specify in the device template of a fleet that all devices in the fleet must run the `quay.io/flightctl/rhel:9.5` operating system image.

The {RedHatEdge} service then rolls out the target specification to all devices in the fleet, and the {RedHatEdge} agents update each device.

You can change other specification items in the device template and the {RedHatEdge} applies the changes in the same way.

However, sometimes not all of the devices in the fleet need to have the exact same specification. 
The {RedHatEdge} allows templates to contain placeholders that are populated based on the device name or label values.

The syntax of the placeholders matches that of https://pkg.go.dev/text/template[Go templates]. 
However, you can only use simple text and actions.

The use of conditionals or loops in the placeholders is not supported.

You can reference anything from the metadata of a device, such as `{{ .metadata.labels.key }}` or `{{ .metadata.name }}`.

You can also use the following functions in your placeholders:

* The `upper` function changes the value to uppercase. For example, the function is `{{ upper .metadata.name }}`.
* The `lower` function changes the value to lowercase. For example, the function is `{{ lower .metadata.labels.key }}`.
* The `replace` function replaces all occurrences of a substring with another string. 
For example, the function is `{{ replace "old" "new" .metadata.labels.key }}`.
* The `getOrDefault` function returns a default value if accessing a missing label. 
For example, the function is `{{ getOrDefault .metadata.labels "key" "default" }}`.
You can combine the functions in pipelines, for example, a combined function is `{{ getOrDefault .metadata.labels "key" "default" | upper | replace " " "-" }}`.

[NOTE]
====
Ensure you are using proper Go template syntax. For example, `{{ .metadata.labels.target-revision }}` is not valid because of the hyphen. 
Instead, you must refer to the field as `{{ index .metadata.labels "target-revision" }}`.
====

You can use the placeholders in device templates in the following ways:

* You can label devices by deployment stage, for example, stage labels are `stage: testing` and `stage: production`.
Then, you can use the label with the `stage` key as placeholder when referencing the operating system image to use, for example, use `quay.io/myorg/myimage:latest-{{ .metadata.labels.stage }}` or when referencing a configuration folder in a Git repository.
* You can label devices by deployment site, for example, deployment sites are `site: factory-berlin` and `site: factory-madrid`. 
* Then, you can use the label with the `site` key as parameter when referencing the secret with network access credentials in Kubernetes.
The following fields in device templates support placeholders:
+
|===
|Field |Placeholders supported in
|Operating System Image |repository name, image name, image tag
|Git Config Provider |target revision, path
|HTTP Config Provider |URL suffix, path
|Inline Config Provider |content, path
|===
