:_mod-docs-content-type: REFERENCE

[id="ref-ha-hub-reqs"]

= High availability {HubName} requirements

[role="_abstract"]
Before deploying a high availability (HA) {HubName}, ensure that you have a shared storage file system installed in your environment and that you have configured your network storage system, if applicable.

== Required shared storage

Shared storage is required when installing more than one {HubNameStart} with a `file` storage backend. The supported shared storage type for RPM-based installations is Network File System (NFS).

Before you run the {PlatformName} installer, verify that you installed the `/var/lib/pulp` directory across your cluster as part of the shared storage file system installation. 
The {PlatformName} installer returns an error if `/var/lib/pulp` is not detected in one of your nodes, causing your high availability {HubName} setup to fail.

If you receive an error stating `/var/lib/pulp` is not detected in one of your nodes, ensure `/var/lib/pulp` is properly mounted in all servers and re-run the installation program.

== Installing firewalld for HA hub deployment

If you intend to install a HA {HubName} using a network storage on the {HubName} nodes itself, you must first install and use `firewalld` to open the necessary ports as required by your shared storage system before running the {PlatformNameShort} installer.

Install and configure `firewalld` by executing the following commands:

. Install the `firewalld` daemon:
+
-----
$ dnf install firewalld
-----
+
. Add your network storage under <service> using the following command:
+
-----
$ firewall-cmd --permanent --add-service=<service>
-----
[NOTE]
For a list of supported services, use the `*$ firewall-cmd --get-services*` command
+
. Reload to apply the configuration:
+
-----
$ firewall-cmd --reload
-----
