

// [id="ref-platform-system-requirements_{context}"]

= {PlatformName} system requirements

Your system must meet the following minimum system requirements to install and run {PlatformName}.

.Base system

[cols="a,a,a"]
|===
| Requirement | Required | Notes

h| Subscription | Valid {PlatformName} |

h| OS | {RHEL} 8.6 or later 64-bit (x86, ppc64le, s390x, aarch64) |{PlatformName} is also supported on OpenShift, see link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/{PlatformVers}/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/index[Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform] for more information.

h| Ansible | version 2.14 (to install) | {PlatformNameShort} ships with execution environments that contain ansible-core {AnsibleCoreVers}.

h| Python | 3.9 or later |

h| Browser | A currently supported version of Mozilla FireFox or Google Chrome |

h| Database | PostgreSQL version 13 |
|===

The following are necessary for you to work with project updates and collections:

* Ensure that the link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_planning_guide/ref-network-ports-protocols_planning[network ports and protocols] listed in _Table 5.9. Automation Hub_ are available for successful connection and download of collections from {HubName} or {Galaxy} server.
* Disable SSL inspection either when using self-signed certificates or for the Red Hat domains.

[NOTE]
====
The requirements for systems managed by {PlatformNameShort} are the same as for Ansible.
See link:https://docs.ansible.com/ansible/latest/getting_started/index.html[Getting started with Ansible] in the Ansible _User Guide_.
====

.Additional notes for {PlatformName} requirements

* Although {PlatformName} depends on Ansible Playbooks and requires the installation of the latest stable version of Ansible before installing {ControllerName}, manual installations of Ansible are no longer required. Instead, for new installations {PlatformName} can detect whether Ansible is already installed and proceed without reinstalling it; otherwise, {ControllerName} will automatically install the latest release package of Ansible and its dependencies.

[NOTE]
====
You must install Ansible using a package manager such as `dnf`, and the latest stable version of the package manager must be installed for {PlatformName} to work properly.
Ansible version 2.14 is required for versions {PlatformVers} and later.
====
