:_mod-docs-content-type: REFERENCE

[id="event-driven-ansible-system-requirements"]

= {EDAcontroller} system requirements

The {EDAcontroller} is a single-node system capable of handling a variable number of long-running processes (such as rulebook activations) on-demand, depending on the number of CPU cores. 

[NOTE]
====
If you want to use {EDAName} 2.5 with a 2.4 {ControllerName} version, see link:{BaseURL}/red_hat_ansible_automation_platform/2.4/html-single/using_event-driven_ansible_2.5_with_ansible_automation_platform_2.4/index[Using {EDAName} 2.5 with {PlatformNameShort} 2.4].
====   

[cols=2*,options="header"]
|===
| Requirement | Required
| *RAM* | 16 GB
| *CPUs* | 4
| *Local disk* a| 
* Hard drive must be 40 GB minimum with at least 20 GB available under /var.
* Storage volume must be rated for a minimum baseline of 3000 IOPS.
* If the cluster has many large projects or decision environment images, consider doubling the GB in /var to avoid disk space errors.
|===

[IMPORTANT]
====
* If you are running {RHEL} 8 and want to set your memory limits, you must have cgroup v2 enabled before you install {EDAName}. 
For specific instructions, see the Knowledge-Centered Support (KCS) article, link:https://access.redhat.com/solutions/7054905[Ansible Automation Platform Event-Driven Ansible controller for {RHEL} 8 requires cgroupv2].

* When you activate an {EDAName} rulebook under standard conditions, it uses about 250 MB of memory. 
However, the actual memory consumption can vary significantly based on the complexity of your rules and the volume and size of the events processed. 
In scenarios where a large number of events are anticipated or the rulebook complexity is high, conduct a preliminary assessment of resource usage in a staging environment. 
This ensures that your maximum number of activations is based on the capacity of your resources. 

For an example of setting {EDAController} maximumrunning activations, see xref:ref-gateway-controller-hub-eda-ext-db[Single {ControllerName}, single {HubName}, and single {EDAcontroller} node with external (installer managed) database]. 
====