[id="ref-general-inventory-variables"]

= General variables

[cols="50%,50%,50%",options="header"]
|====
| *RPM variable name* | *Container variable name* | *Description*
| `aap_ca_cert_file` |`ca_tls_cert` | Define a Certification Authority certificate along with a matching key when you want the installation program to create leaf certificates for each product for you.

| `aap_ca_cert_files_remote` | `ca_tls_remote` | Denote whether the CA provided certificate files are local to the installation program (`false`) or on the remote component server (`true`).

Default = `false`

| `aap_ca_key_file` | `ca_tls_key` | Define the key for the matching certificate when you want the installation program to create leaf certificates for each product for you.

| `bundle_install` | `bundle_install` | Set to `true` to enable a bundled installation. 

Default = `false`

| `bundle_install_folder` | `bundle_dir`| Specify the path to the bundle directory when performing a bundle install.

Container default = `false`

RPM Default = `/var/lib/ansible-automation-platform-bundle`

| `custom_ca_cert` | `custom_ca_cert` | The path to the custom CA certificate file.

If set, this installs a custom CA certificate to the system truststore.

| `enable_insights_collection` | | The default install registers the node to the {InsightsName} for the {PlatformName} Service if the node is registered with Subscription Manager. 

Set to `false` to disable.

Default = `true`

| `nginx_tls_protocols` | | Defines support for `ssl_protocols` in NGINX.

Values available `TLSv1`, `TLSv1.1`, `TLSv1.2`, `TLSv1.3`.

The `TLSv1.1` and `TLSv1.2` parameters only work when OpenSSL 1.0.1 or higher is used.

The `TLSv1.3` parameter only works when OpenSSL 1.1.1 or higher is used.

If `nginx_tls-protocols = ['TLSv1.3']` only `TLSv1.3` is enabled. To set more than one protocol use `nginx_tls_protocols = ['TLSv1.2', 'TLSv.1.3']`.

Default = `TLSv1.2`

| `nginx_user_http_config` | | List of NGINX configurations for `/etc/nginx/nginx.conf` under the `http` section. 

Each element in the list is provided into `http nginx config` as a separate line. 

Default = {}

| `redis_cluster_ip` | `redis_cluster_ip` | The IPv4 address used by the Redis cluster to identify each host in the cluster.

Redis clusters cannot use hostnames or IPv6 addresses. When defining hosts in the `[redis]` group, use this variable to identify the IPv4 address if the default is not what you want. 

| `redis_mode` | `redis_mode` | The Redis mode to use for your {PlatformNameShort} installation.

Possible values are: `standalone` and `cluster`.

For more information about Redis, see link:{URLPlanningGuide}/ha-redis_planning[Caching and queueing system] in _{TitlePlanningGuide}_.

Default = `cluster`

| `registry_password` | `registry_password` | Required if performing an online non-bundled installation.

The password credential for access to the registry source defined in `registry_url`.

// This content is used in RPM installation
ifdef::aap-install[]
For more information, see link:{URLInstallationGuide}/assembly-platform-install-scenario#proc-set-registry-username-password[Setting registry_username and registry_password].
endif::aap-install[] 
// This content is used in Containerized installation
ifdef::container-install[]
For more information, see link:{URLContainerizedInstall}/aap-containerized-installation#proc-set-registry-username-password[Setting registry_username and registry_password].
endif::container-install[]

| `registry_url` | `registry_url` | URL for the registry source. 

Default = `registry.redhat.io`

| `registry_username` | `registry_username` | Required if performing an online non-bundled installation.

The username credential for access to the registry source defined in `registry_url`.

// This content is used in RPM installation
ifdef::aap-install[]
For more information, see link:{URLInstallationGuide}/assembly-platform-install-scenario#proc-set-registry-username-password[Setting registry_username and registry_password].
endif::aap-install[] 
// This content is used in Containerized installation
ifdef::container-install[]
For more information, see link:{URLContainerizedInstall}/aap-containerized-installation#proc-set-registry-username-password[Setting registry_username and registry_password].
endif::container-install[]

| `registry_verify_ssl` | `registry_tls_verify` | Controls whether SSL/TLS certificate verification should be enabled or disabled when making HTTPS requests.

Default = `true`

| `routable_hostname` |`routable_hostname` | This variable is used if the machine running the installation program can only route to the target host through a specific URL. For example, if you use short names in your inventory, but the node running the installation program can only resolve that host by using a FQDN.

If `routable_hostname` is not set, it should default to `ansible_host`. If you do not set `ansible_host`, `inventory_hostname` is used as a last resort.

This variable is used as a host variable for particular hosts and not under the `[all:vars]` section. 

For further information, see link:https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#assigning-a-variable-to-one-machine-host-variables[Assigning a variable to one machine: host variables].

|| `backup_dir` | The location of the backup directory on the Ansible host. Used when performing backup and restore.

Default = `~/backups`


| | `container_compress` | Container compression software.

Default = `gzip`

| | `container_keep_images` | Keep container images.

Default = `false`

| | `container_pull_images` | Pull newer container images.

Default = `true`

| | `registry_auth` | Use registry authentication.

Default = `true`

| | `registry_ns_aap` | {PlatformNameShort} registry namespace.

Default = `ansible-automation-platform-25`

| | `registry_ns_rhel` | RHEL registry namespace.

Default = `rhel8`

|====



