:_content-type: CONCEPT

[id="lightspeed-key-features-june2024_{context}"]
= 20 June 2024

This release includes several enhancements, additions, and fixes that have been implemented in {LightspeedShortName}.

== New features and enhancements 

* *{LightspeedShortName} on-premise deployment*
+
{LightspeedShortName} is now available for on-premise deployments. This capability provides the {PlatformName} customers more control over their data and supports compliance with enterprise security policies. For example, organizations in sensitive industries with data privacy or air-gapped requirements can use on-premise deployments of both {LightspeedShortName} and {ibmwatsonxcodeassistant} for {LightspeedShortName} on Cloud Pak for Data. {LightspeedShortName} on-premise deployments are supported on {PlatformName} version 2.4.
+
[NOTE]
====
The following capabilities are not yet available on {LightspeedShortName} on-premise deployments:

* Viewing telemetry data on the Admin dashboard
* Generating playbooks and viewing playbook explanations
====

* *Playbook generation and explanations*
+
Using the Ansible VS Code extension, you can create Ansible playbooks using a natural language interface in English. {LightspeedShortName} with {ibmwatsonxcodeassistant} reads the natural language prompts and generates an entire playbook recommendation based on your intent. You can also view the explanations for new or existing playbooks. The playbook explanations describe what the playbook or task within the playbook does and contextualize its impact.

