:_content-type: CONCEPT

[id="lightspeed-key-features-15feb2024_{context}"]
= 15 February 2024

This release includes several enhancements, additions, and fixes that have been implemented in {LightspeedShortName}.

== New features and enhancements 

* *Model customization*
+
Organization administrators can now create and use fine-tuned, custom models that are trained on your organization's existing Ansible content. With this capability, you can tune the models to your organization's automation patterns and improve the code recommendation experience. 
+
You can configure multiple custom models for your organization. For example, you can create a custom model for your corporate IT automation team and a different one for your engineering team's infrastructure. You can also configure a custom model to make it available for all Ansible users or select Ansible users in your organization. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant/2.x_latest/html-single/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant_user_guide/index#configure-custom-models_administering-ansible-lightspeed[Configuring custom models].

* *Streamlined the setup process*
+
Previously, organization administrators had to assign seat licenses to users so that they could access {LightspeedShortName}. With the new subscription plans from {ibmwatsonxcodeassistant}, organization administrators no longer need to manage access to {LightspeedShortName} by assigning or removing seat licenses.