:_content-type: CONCEPT

[role="_abstract"]
= Overview
{LightspeedFullName} is a generative AI service that helps automation teams create, adopt, and maintain Ansible content more efficiently. It uses natural language prompts to generate code recommendations for automation tasks based on Ansible best practices. 

{LightspeedShortName} is the cloud service that enables integration of generative AI into Ansible Automation Platform. This document specifically describes the integration of {LightspeedFullName}.

To use {LightspeedFullName}, your organization must have:

* A trial or paid subscription to {PlatformNameShort} 
* A trial or paid subscription to {ibmwatsonxcodeassistant}


[id="lightspeed-key-features_{context}"]
= 15 February 2024

This release includes several enhancements, additions, and fixes that have been implemented in {LightspeedShortName}.

== New features and enhancements 

* *Custom model creation*
+
Organization administrators can now create and use fine-tuned, custom models that are trained on your organization's existing Ansible content. With this capability, you can tune the models to your organization's automation patterns and improve the code recommendation experience.
+
You can configure multiple custom models for your organization. For example, you can create a custom model for your corporate IT automation team and a different one for your engineering team's infrastructure. You can also configure a custom model to make it available for all Ansible users or select Ansible users in your organization. For more information, see xref:configuring-custom-models_configuring-custom-models[Configuring custom models].

* *Licensing updates*
+ 
Previously, organization administrators had to assign seat licenses to users so that they could access {LightspeedShortName}. With the latest licensing changes, all Ansible users within an organization, that has a trial or paid subscription to both Ansible Automation Platform and {ibmwatsonxcodeassistant}, can access {LightspeedShortName} by default.

[id="lightspeed-key-features_{context}"]
= 25 October 2023

== Components

The following components are available for using {LightspeedShortName}:

* Ansible Extension for VS Code v2.8.108
* {AnsibleCodeBot} Technical Preview

This release includes several enhancements, additions, and fixes that have been implemented in {LightspeedShortName}.

== New features and enhancements 

This release includes the following key features that were implemented in {LightspeedShortName}:

* *Ansible-specific {ibmwatsonxcodeassistant} models*
+
{LightspeedFullName} uses Ansible-specific IBM watsonx Granite models unique to your organization, which are provided, managed, and maintained by IBM.

* *Single tasks and multitask generation*
+
Using natural language prompts, you can generate single task or multiple task recommendations for Ansible task files and playbooks. 

* *Content source matching*
+
For each generated code recommendation, {LightspeedShortName} lists content source matches, including details such as potential source, content author, and relevant licenses. You can use this data to gain insight into potential training data sources used to generate the code recommendations.

* *Post-processing capabilities*
+
{LightspeedShortName} offers post-processing capabilities that augment {ibmwatsonxcodeassistant} and improve the quality and accuracy of code recommendations. 

* *Content modernization*
+
The {AnsibleCodeBot} scans existing content collections, roles, and playbooks through Git repositories, and proactively creates pull requests whenever best practices or quality improvement recommendations are available. The bot automatically submits pull requests to the repository, which proactively alerts the repository owner to a recommended change to their content. {AnsibleCodeBot} is available as a Technical Preview.




