:_mod-docs-content-type: ASSEMBLY

[id="overview-tested-deployment-models"]

= Choose a deployment method and topology

[role="_abstract"]
Red Hat tests {PlatformNameShort} {PlatformVers} with a defined set of topologies to give you opinionated deployment options. 
Deploy all components of {PlatformNameShort} so that all features and capabilities are available for use without the need to take further action.

Red Hat tests the installation of {PlatformNameShort} {PlatformVers} using a defined set of infrastructure topologies or reference architectures. 
Enterprise organizations can use one of the {EnterpriseTopologyPlural} for production deployments. 
This ensures the highest level of uptime, performance, and continued scalability. 
Organizations or deployments that are resource constrained can use a {GrowthTopology}.

You can install {PlatformNameShort} on different infrastructure topologies and environment configurations. 
However, Red Hat does not fully test topologies outside of published reference architectures. 
Red Hat recommends using a tested topology for all new deployments and provides commercially reasonable support for deployments that meet minimum requirements. 

include::topologies/ref-installation-deployment-models.adoc[leveloffset=+1]
