:_mod-docs-content-type: PROCEDURE

// user story:
// Module included in the following assemblies:
// assembly-using-job-explorer.adoc


[id="proc-view-failed-jobs"]

= Example: Reviewing failed jobs

[role="_abstract"]
You can view detailed information about failed jobs across your organization by drilling down on a graph in the *Clusters* view and using the *Job Explorer* to refine results.
Clicking a segment on the graph opens that information in the *Job Explorer*, preserving filters applied in the *Clusters* view.

.Procedure

. From the navigation panel, select {MenuAAClusters}.
. Use the filter lists in the toolbar to apply filters for clusters and time range of your choosing.
. Click a segment on the graph.
+
You are redirected to the *Job Explorer* view, which displays a list of jobs corresponding to that day on the graph.
. To refine the list to show only failed jobs:
.. Select **Status** from the *Filter by* list.
.. Select the **Failed** filter.
+
The *Job Explorer* view updates to show only failed jobs run within the selected time range.

.Next steps
* Add additional context to the view by applying more filters and selecting attributes to sort results.
* Review more information for failed jobs on the {ControllerName} job details page.