:_mod-docs-content-type: <PROCEDURE>
[id="proc-create-remote_{context}"]

= Creating a remote configuration in {HubName}

You can use {PlatformName} to create a remote configuration to an external collection source. Then, you can sync the content from those collections to your custom repositories.

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select {MenuACAdminRemotes}.
. Click btn:[Create Remote].
. Enter a *Name* for the remote configuration.
. Enter the *URL* for the remote server, including the path for the specific repository.
+
[NOTE]
====
To find the remote server URL and repository path, navigate to {MenuACAdminRepositories}, select the btn:[More Actions] icon *{MoreActionsIcon}*, and select btn:[Copy CLI configuration].
====
+
. To sync signed collections only, check the box labeled *Signed collections only*.
. To sync dependencies, check the box labeled *Sync all dependencies*. To turn off dependency syncing, leave this box unchecked.
. Configure the credentials to the remote server by entering a *Token* or *Username* and *Password* required to access the external collection.
+
[NOTE]
====
To generate a token from the navigation panel, select {MenuACAPIToken}, click btn:[Load token] and copy the token that is loaded.
====
+
. To access collections from {Console}, enter the *SSO URL* to sign in to the identity provider (IdP).
. Select or create a *Requirements file* to identify the collections and version ranges to synchronize with your custom repository. For example, to download only the kubernetes and AWS collection versions 5.0.0 or later the requirements file would look like this:
+
-----
Collections:
 	  - name: community.kubernetes
	  - name: community.aws
 		version:”>=5.0.0”
-----
+

. Optional: To configure your remote further, use the options available under *Show advanced options*:
.. If there is a corporate proxy in place for your organization, enter a *Proxy URL*, *Proxy Username* and *Proxy Password*.
.. Enable or disable transport layer security using the *TLS validation* checkbox.
.. If digital certificates are required for authentication, enter a *Client key* and *Client certificate*.
.. If you are using a self-signed SSL certificate for your server, enter the PEM encoded client certificate used for authentication in the *CA certificate* field.
.. To accelerate the speed at which collections in this remote can be downloaded, specify the number of collections that can be downloaded in tandem in the *Download concurrency* field.
.. To limit the number of queries per second on this remote, specify a *Rate Limit*.
+
[NOTE]
====
Some servers can have a specific rate limit set, and if exceeded, synchronization fails.
====
