:_mod-docs-content-type: PROCEDURE
[id="proc-uploading-collections"]

= Uploading collections to a namespace

[role="_abstract"]
Upload internally-developed collections in `tar.gz` file format to your {PrivateHubName} namespace for review and approval by an {HubName} administrator.
When approved, the collection moves to the *Published* content repository where {HubName} users can view and download it.

[NOTE]
====
Format your collection file name as follows: <my_namespace-my_collection-1.0.0.tar.gz>
====

.Prerequisites
* You have a namespace to which you can upload the collection.

[IMPORTANT]

====
Attempting to upload very large collections will result in an error.

Limit collection size to 20 mb when uploading to {Galaxy} or {Console}.
For {PrivateHubName} avoid uploading collections sized 200 mb or more.

In scenarios that require a complete environment with multiple collections and dependencies, use an {ExecEnvShort}. See link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/managing_automation_content/managing-containers-hub#obtain-images[Pulling {ExecEnvShort}s for use in {HubName}] for more information.
====

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select {MenuACNamespaces} and select a namespace.
. Select the *Collections* tab.
. Click btn:[Upload collection].
. Click btn:[Browse] next to the *Collection file* field.
. Select the collection to upload.
. Select one of the following options:
* *Staging repos* 
* *Repositories without pipeline*
. Click btn:[Upload collection].

.Verification
To verify whether the collection uploaded successfully or if it failed, navigate to {MenuACNamespaces} and click the btn:[More Actions] icon *{MoreActionsIcon}*, then select *Imports*. There you will find a summary of tests indicating whether the import was successful.
