// Module included in the following assemblies:
// obtaining-token/master.adoc
[id="proc-set-community-remote_{context}"]
= Configuring the community remote repository and syncing {Galaxy} collections

You can edit the *community* remote repository to synchronize chosen collections from {Galaxy} to your {PrivateHubName}.
By default, your {PrivateHubName} community repository directs to `galaxy.ansible.com/api/`.

.Prerequisites

* You have *Modify Ansible repo content* permissions.
For more information on permissions, see link:{LinkCentralAuth}.
* You have a `requirements.yml` file that identifies those collections to synchronize from {Galaxy} as in the following example:
+
.Requirements.yml example
-----
collections:
  # Install a collection from Ansible Galaxy.
  - name: community.aws
    version: 5.2.0
    source: https://galaxy.ansible.com
-----

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select {MenuACAdminRemotes}.
. In the *Details* tab in the *Community* remote, click btn:[Edit remote].
. In the *YAML requirements* field, paste the contents of your `requirements.yml` file.
. Click btn:[Save remote].
+
You can now synchronize collections identified in your `requirements.yml` file from {Galaxy} to your {PrivateHubName}.

. From the navigation panel, select {MenuACAdminRepositories}. Next to the *community* repository, click the btn:[More Actions] icon *{MoreActionsIcon}* and select *Sync repository* to sync collections between {Galaxy} and {HubNameMain}.
. On the modal that appears, you can toggle the following options:
* *Mirror*: Select if you want your repository content to mirror the remote repository's content.
* *Optimize*: Select if you want to sync only when no changes are reported by the remote server.
. Click btn:[Sync] to complete the sync.

.Verification
The *Sync status* column updates to notify you whether the {Galaxy} collections synchronization to your {HubNameMain} is successful.

* Navigate to {MenuACCollections} and select *Community* to confirm successful synchronization.


