:_mod-docs-content-type: PROCEDURE
[id="proc-set-community-remote"]
ifndef::operationG[]
= Configuring the community remote repository to sync {Galaxy} collections

[role="_abstract"]
You can edit the *community* remote repository to synchronize chosen collections from {Galaxy} to your {PrivateHubName}.
By default, your {PrivateHubName} community repository directs to `galaxy.ansible.com/api/`.
endif::operationG[]
ifdef::operationG[]
= Configuring Proxy settings on {HubName}

If your private automation hub is behind a network proxy, you can configure proxy settings on the remote to sync content located outside of your local network.
endif::operationG[]

.Prerequisites

* You have *Modify Ansible repo content* permissions.
For more information on permissions, see {LinkCentralAuth}.
* You have a `requirements.yml` file that identifies those collections to synchronize from {Galaxy} as in the following example:
+
*Requirements.yml example*
-----
collections:
  # Install a collection from Ansible Galaxy.
  - name: community.aws
    version: 5.2.0
    source: https://galaxy.ansible.com
-----

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select {MenuACAdminRemotes}.
. In the *Details* tab in the *Community* remote, click btn:[Edit remote].
. In the *YAML requirements* field, paste the contents of your `requirements.yml` file.
. Click btn:[Save remote].

.Result
You can now synchronize collections identified in your `requirements.yml` file from {Galaxy} to your {PrivateHubName}. 

.Next steps
See link:{URLHubManagingContent}/managing-cert-valid-content#assembly-synclists[Synchronizing Ansible content collections in {HubName}] for syncing steps.




