:_mod-docs-content-type: PROCEDURE
[id="proc-create-content-developers"]

= Creating a content development team

[role="_abstract"]
Create a new team in {PlatformNameShort} to support content curation and development in your organization. This team can contribute internally-developed collections for publication in {PrivateHubName}.

To help content developers create a namespace and upload their internally developed collections to {PrivateHubName}, you must first create a team and assign the required permissions.

.Prerequisites

* You have administrative permissions in {PlatformNameShort} and can create teams.

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select {MenuAMTeams} and click btn:[Create team].
. Enter *Content Engineering* as a *Name* for the team.
. Select an *Organization* for the team. 
. Click btn:[Create team]. The team Details page opens.
. Select the *Roles* tab and then select the *Automation Content* tab.
. Click btn:[Add roles].
. Select *Namespace* from the *Resource type* list and click btn:[Next].
. Select the namespaces that will receive the new roles and click btn:[Next].
. Select the roles to apply to the selected namespaces and click btn:[Next].
. Review your selections and click btn:[Finish].
. Click btn:[Close] to complete the process.

.Next steps
The new team is created with the permissions that you assigned. You can now add users to the team in the *Users* tab. See link:{URLCentralAuth}/gw-managing-access#proc-gw-team-add-user[Assigning users to a team] for further steps.

.Additional resources
* link:{URLCentralAuth}/gw-managing-access#assembly-controller-teams_gw-manage-rbac[Teams]