// Module included in the following assemblies:
// obtaining-token/master.adoc
[id="proc-create-synclist"]

= Syncing {CertifiedName}

You can sync curated {CertifiedCon} in {HubNameMain} on {Console}.
//[ddacosta]This needs to be checked. I don't see a Repositories selection in the console verion. I think the way I've rewritten is correct.
// [hherbly] Looks like there is no synclist info in console or the test instance; commenting out this info for 2.5
// Your synclist repository is located on the {HubName} navigation panel under {MenuACAdminRepositories}, which is updated whenever you manage content within {CertifiedName}.

//All {CertifiedName} are included by default in your initial organization synclist.

[NOTE]
====
When syncing content, keep in mind that {HubName} does not check other repositories for dependencies. To avoid an error, turn off dependency downloading by editing your remote settings. See link:{URLHubManagingContent}/managing-collections-hub#proc-create-remote_remote-management[Creating a remote configuration in {HubName}] for more information.
====

.Prerequisites

* You have a valid {PlatformNameShort} subscription.
* You have organization administrator permissions for {Console}.
* The following domain names are part of either the firewall or the proxy's allowlist.
They are required for successful connection and download of collections from {HubName} or Galaxy server:
** `galaxy.ansible.com`
** `cloud.redhat.com`
** `{Console}`
** `sso.redhat.com`
* {HubNameMain} resources are stored in Amazon Simple Storage.
The following domain names must be in the allow list:
** `automation-hub-prd.s3.us-east-2.amazonaws.com`
** `ansible-galaxy.s3.amazonaws.com`
* SSL inspection is disabled either when using self signed certificates or for the Red Hat domains.

.Procedure

. Log in to `{Console}`.
. Navigate to menu:Automation Hub[Collections].
. Set the *Sync* toggle switch on each collection to exclude or include it on your synclist.
+
[NOTE]
====
You will only see the *Sync* toggle switch if you have administrator permissions.
====
+
. To initiate the remote repository synchronization, navigate to your {PlatformNameShort} and select {MenuACAdminRepositories}.
. In the row containing the repository you want to sync, click the btn:[More Actions] icon *{MoreActionsIcon}* and select *Sync repository* to initiate the remote repository synchronization to your {PrivateHubName}. 
. Optional: If your remote repository is already configured, update the collections content that you made available to local users by manually synchronizing Red Hat {CertifiedName} to your {PrivateHubName}.
