:_mod-docs-content-type: PROCEDURE
[id="proc-uploading-collections"]

= Uploading collections to your namespaces

[role="_abstract"]
You can upload internally developed collections in `tar.gz` file format to your {PrivateHubName} namespace for review and approval by an {HubName} administrator.
When approved, the collection moves to the *Published* content repository where {HubName} users can view and download it.

[NOTE]
====
Format your collection file name as follows: <my_namespace-my_collection-1.0.0.tar.gz>
====

.Prerequisites
* You have a namespace to which you can upload the collection.

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select {MenuACNamespaces} and select a namespace.
. Select the *Collections* tab.
. Click btn:[Upload collection].
. Click btn:[Browse] next to the *Collection file* field.
. Select the collection to upload.
. Select one of the following options:
* *Staging repos* 
* *Repositories without pipeline*
. Click btn:[Upload collection].

.Verification
To verify whether the collection uploaded successfully or if it failed, navigate to {MenuACNamespaces} and click the btn:[More Actions] icon *{MoreActionsIcon}*, then select *Imports*. There you will find a summary of tests indicating whether the import was successful.
