:_newdoc-version: 2.16.0
:_template-generated: 2024-02-16
:_mod-docs-content-type: PROCEDURE

[id="configure-proxy-remote_{context}"]
ifdef::manage-hub[]
= Configuring proxy settings
endif::[]
ifndef::manage-hub[]
= Configuring proxy settings on {HubName}
endif::[]

[role="_abstract"]
If your {PrivateHubName} is behind a network proxy, you can configure proxy settings on the remote to sync content located outside of your local network.

.Prerequisites

* You have valid *Modify Ansible repo content* permissions.
For more information on permissions, see {LinkCentralAuth}
* You have a proxy URL and credentials from your local network administrator.

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select {MenuACAdminRemotes}.
. In either the *rh-certified* or *Community* remote, click the btn:[More Actions] icon *{MoreActionsIcon}* and select *Edit remote*.
. Expand the *Show advanced options* drop-down menu.
. Enter your proxy URL, proxy username, and proxy password in the appropriate fields.
. Click btn:[Save remote].
