:_mod-docs-content-type: PROCEDURE
[id="proc-import-collection"]

= Importing an automation content collection in {HubName}

[role="_abstract"]
As an automation content creator, you can import a collection to use in a custom repository. To use a collection in your custom repository, you must first import the collection into your namespace so the {HubName} administrator can approve it.

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select {MenuACNamespaces}. The *Namespaces* page displays all of the namespaces available.
. Select the namespace to which you want to add your collection.
. Select the *Collections* tab.
. Click btn:[Upload Collection].
. Enter or browse to select a collection file.
. Select the repository pipeline to add the collection. The choices are *Staging repos* and *Repositories without pipeline*.
. Click btn:[Upload collection].
+
The *Imports* screen displays a summary of tests and notifies you if the collection upload is successful or has failed. To find your imports, on your namespace click the btn:[More Actions] icon *{MoreActionsIcon}* and select *Imports*.
+
[NOTE]
====
If the collection is not approved, it is not displayed in the published repository.
====

[role="_additional-resources"]
.Additional resources
* link:{URLHubManagingContent}/managing-collections-hub#con-approval-pipeline[Approval pipeline for custom repositories in {HubName}]