:_mod-docs-content-type: PROCEDURE
[id="proc-create-namespace"]

= Creating a namespace

[role="_abstract"]
You can create a namespace to organize collections that your content developers upload to {HubName}.
When creating a namespace, you can assign a team in {HubName} as owners of that namespace.

[TIP]

====

By default, namespaces used on {Galaxy} are also used on {HubName} by the Ansible partner team. 
For any queries and clarifications contact ansiblepartners@redhat.com.
====

.Prerequisites

* You have *Add Namespaces* and *Upload to Namespaces* permissions.

.Procedure

. Log in to your {PlatformNameShort}.
. From the navigation panel, select {MenuACNamespaces}.
. Click btn:[Create namespace] and enter a *Name* for your namespace.
. Optional: enter a description, company, logo URL, resources, or useful links in the appropriate fields.
. Click btn:[Create namespace].
. Select the *Team Access* tab and click btn:[Add roles] to assign roles to your namespace.
. Select the team to which you want to grant a role, then click btn:[Next].
. Select the roles you want to apply to the selected team, and then click btn:[Next].
. Review your selections and click btn:[Finish].
. Click btn:[Close] to complete the process.

.Next steps
Your content developers can now upload collections to your new namespace and allow users in teams assigned as owners to upload collections.
