:_content-type: PROCEDURE

[id="ppah-online-offline-install_{context}"]
= Online and offline installation

There are two ways to run the containerized installer:

* Online: The container images will be pulled from a registry.
* Offline: The container images will be imported from a tarball.

This workflow is controlled via the `bundle_install` variable.

== Online installation

Online installation is the default install scenario (`bundle_install: false`) and pulls the container images from `registry.redhat.io`, which requires authentication.

.Procedure

. Provide the registry username and password for authentication.
----
registry_username: foo@ansible.com
registry_password: bar
...
----
. Optional: as an alternative, you can use the internal registry (without authentication) as in the following example: 
----
registry_auth: false
registry_url: registry-proxy.engineering.redhat.com
registry_ns_aap: rh-osbs
registry_ns_rhel: rh-osbs
registry_tls_verify: false
controller_image: 'ansible-automation-platform-23-controller-rhel8:latest'
ee_29_image: 'ansible-automation-platform-23-ee-29-rhel8:latest'
ee_minimal_image: 'ansible-automation-platform-23-ee-minimal-rhel8:latest'
ee_supported_image: 'ansible-automation-platform-23-ee-supported-rhel8:latest'
hub_image: 'ansible-automation-platform-23-hub-rhel8:latest'
hub_web_image: 'ansible-automation-platform-23-hub-web-rhel8:latest'
postgresql_image: 'rhel8-postgresql-13:latest'
redis_image: 'rhel8-redis-6:latest'
...
----

== Offline installation

.Procedure

. Set `bundle_install: true` in in your Ansible configuration and `bundle_dir`` with the path to the bundle directory without the images subdirectory:
----
$ ansible-playbook -i </path/to/inventory> ansible.containerized_installer.install -e bundle_install=true -e bundle_dir=$(pwd)/bundle
----