:_mod-docs-content-type: PROCEDURE
[id="proc-using-content-signing-services-in-pah"]

= Sign content in {PrivateHubName}

[role="_abstract"]
After you have configured content signing on your {PrivateHubName}, you can manually sign a new collection or replace an existing signature with a new one.
When users download a specific collection, this signature indicates that the collection is for them and has not been modified after certification.

You can use content signing on {PrivateHubName} in the following scenarios:

* Your system does not have automatic signing configured and you must use a manual signing process to sign collections.
* The current signatures on the automatically configured collections are corrupted and need new signatures.
* You need additional signatures for previously signed content.
* You want to rotate signatures on your collections.

.Procedure

. Log in to {PlatformNameShort}.
. From the navigation panel, select {MenuACAdminCollectionApproval}.
The Approval dashboard opens and displays a list of collections.

. Click the thumbs up icon next to the collection you want to approve. On the modal that appears, check the box confirming that you want to approve the collection, and click btn:[Approve and sign collections].

.Verification
* Navigate to {MenuACCollections} to verify that the collections you signed and approved are displayed. 
