:_mod-docs-content-type: PROCEDURE
[id="adding-an-execution-environment"]

= Adding and signing an {ExecEnvShort}

[role="_abstract"]
{ExecEnvNameStart} are container images that make it possible to incorporate system-level dependencies and collection-based content. Each {ExecEnvShort} allows you to have a customized image to run jobs, and each of them contain only what you need when running the job.

.Procedure
. From the navigation panel, select {MenuACExecEnvironments}.

. Click btn:[Create execution environment] and enter the relevant information in the fields that appear.

.. The *Name* field displays the name of the {ExecEnvShort} on your local registry.

.. The *Upstream name* field is the name of the image on the remote server.

.. Under *Registry*, select the name of the registry from the drop-down menu.

.. Optional: Enter tags in the *Add tag(s) to include* field.
If the field is blank, all the tags are passed.
You must specify which repository-specific tags to pass.

.. Optional: Enter tags to exclude in the *Add tag(s) to exclude* field. 

. Click btn:[Create {ExecEnvShort}]. You should see your new {ExecEnvShort} in the list that appears.

. Sync and sign your new {ExecEnvNameSing}.

.. Click the btn:[More Actions] icon *{MoreActionsIcon}* and select *Sync execution environment*.

.. Click the btn:[More Actions] icon *{MoreActionsIcon}* and select *Sign execution environment*.

. Click on your new {ExecEnvShort}. On the Details page, find the *Signed* label to determine that your {ExecEnvShort} has been signed.
