# Shared tasks that convert RST to Asciidoc.
# Ensure the target_dir variable is set in the playbook that imports this.
- name: find rst files
  ansible.builtin.find:
    paths: "{{ target_dir }}"
    patterns: "*.rst"
    recurse: true
    file_type: file
  register: rst_files
- name: convert rst to adoc
  ansible.builtin.shell:
    cmd: while read i; do pandoc -f rst -t asciidoc "$i" -o "${i%.*}.adoc"; done
    stdin: "{{ item.path }}"
  loop: "{{ rst_files.files }}"
- name: rm converted rst files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ rst_files.files }}"
