Upgrading to Ansible Automation Platform ===================

Automation Hub acts as a content provider for automation controller,
which requires both an automation controller deployment and an
Automation Hub deployment running alongside each other. The Ansible
Automation Platform installer contains both of these. This section
covers each component of the upgrading process:

Note

All upgrades should be no more than two major versions behind what you
are currently upgrading to. For example, in order to upgrade to
automation controller 4.0, you must first be on version 3.8.x; i.e.,
there is no direct upgrade path from version 3.7.x or earlier. Refer to
the https://access.redhat.com/articles/4098921[recommended upgrade path
article] on the Red Hat customer portal.

In order to run automation controller 4.0, you must also have Ansible
2.10.

[[upgrade_planning]]
== Upgrade Planning

This section covers changes that you should keep in mind as you attempt
to upgrade your automation controller instance.

* Even if you already have a valid license from a previous version, you
must still provide your credentials or a subscriptions manifest again
upon upgrading to the latest automation controller. See
`import_subscription` in the Automation Controller User Guide.
* If you need to upgrade Red Hat Enterprise Linux and automation
controller, you will need to do a backup and restore of your controller
data (from the automation controller). Refer to `ag_backup_restore` in
the Automation Controller Administration Guide for further detail.
* Clustered upgrades require special attention to instance and instance
groups prior to starting the upgrade. See
https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/single-machine-scenario#editing_the_red_hat_ansible_automation_platform_installer_inventory_file[Editing
the Red Hat Ansible Automation Platform installer inventory file] and
`ag_clustering` for details.

== Obtaining the Installer

Refer to
https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html-single/red_hat_ansible_automation_platform_installation_guide/index#choosing_and_obtaining_a_red_hat_ansible_automation_platform_installer[Choosing
and obtaining a Red Hat Ansible Automation Platform installer] on the
https://access.redhat.com/[Red Hat Customer Portal] for detail. Be sure
to use your Red Hat customer login to access the full content.

== Setting up the Inventory File

See
https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/single-machine-scenario#editing_the_red_hat_ansible_automation_platform_installer_inventory_file[Editing
the Red Hat Ansible Automation Platform installer inventory file] for
information.

== Running the Setup Playbook

include::setup-playbook.adoc[]
