:_mod-docs-content-type: PROCEDURE

[id="aap-controller-yaml-backup"]

= Using YAML to back up the {ControllerNameStart} deployment

See the following procedure for how to back up a deployment of the {ControllerName} using YAML. 

.Prerequisites

* You must be authenticated with an OpenShift cluster.
* You have installed {OperatorPlatformNameShort} on the cluster.
* You have deployed {ControllerName} using the {OperatorPlatformNameShort}.

.Procedure

. Create a file named "backup-automation-controller.yml" with the following contents:
+
----
---
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationControllerBackup
metadata:
  name: AutomationControllerBackup-2024-07-15
  namespace: my-namespace
spec:
  deployment_name: controller
----
+

[NOTE]
====
The "deployment_name" above is the name of the {ControllerName} deployment you intend to backup from. 
The namespace above is the one containing the {ControllerName} deployment you intend to back up.
====

. Use the `oc apply` command to create the backup object in your cluster:

`$ oc apply -f backup-automation-controller.yml`
