:_mod-docs-content-type: PROCEDURE

[id="aap-controller-restore"]

= Recovering the {ControllerNameStart} deployment

[role=_abstract]
Use this procedure to restore a previous controller deployment from an AutomationControllerBackup. The deployment name you provide will be the name of the new AutomationController custom resource that will be created.

[NOTE]
====
The name specified for the new AutomationController custom resource must not match an existing deployment. 

If the backup custom resource being restored is a backup of a currently running AutomationController custom resource the recovery process will fail. See xref:aap-troubleshoot-backup-recover[Troubleshooting] for steps to resolve the issue.
====

.Prerequisites

* You must be authenticated with an OpenShift cluster.
* You have deployed  {ControllerName} on the cluster.
* An AutomationControllerBackup is available on a PVC in your cluster.

.Procedure
. Log in to {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *Automation Controller Restore* tab.
. Click btn:[Create AutomationControllerRestore].
. Enter a *Name* for the recovery deployment.
. Enter a *New Deployment name* for the restored deployment.
+
[NOTE]
====
This must be different from the original deployment name.
====
+
. Select the *Backup source to restore from*. *Backup CR* is recommended.
. Enter the *Backup Name* of the AutomationControllerBackup object.
. Click btn:[Create].
+
A new deployment is created and your backup is restored to it. This can take approximately 5 to 15 minutes depending on the size of your database.


.Verification
. Log in to Red Hat {OCP}.
. Navigate to menu:Operators[Installed Operators].
. Select your {OperatorPlatformNameShort} deployment.
. Select the *AutomationControllerRestore* tab.
. Select the restore resource you want to verify.
. Scroll to *Conditions* and check that the *Successful* status is `True`.
+
[NOTE]
====
If *Successful* is `False`, the recovery has failed. Check the {ControllerName} operator logs for the error to fix the issue.
====
