:_mod-docs-content-type: PROCEDURE

[id="using-postinstall_{context}"]

= Using the postinstall feature of containerized {PlatformNameShort}

[role="_abstract"]

You can use the optional postinstall feature of containerized {PlatformNameShort} to define and load the configuration during the initial installation. This uses a configuration-as-code approach, where you simply define your configuration to be loaded as YAML files. 

.Prerequisites
* An {PlatformNameShort} license for this feature that is on the local filesystem so it can be automatically loaded from the inventory file.


.Procedure
. The postinstall feature is disabled by default. To enable the postinstall feature, add the following variables in your inventory file:
+
----
controller_postinstall=true
----
+
. To load your {ControllerName} license as part of the postinstall process, set the following variables in your inventory file:
+
----
controller_license_file=<full_path_to_your_manifest_zip_file>
controller_postinstall_dir=<full_path_to_your_postinstall_directory>
----
+
. You can pull your configuration-as-code from a Git based repository. To do this, set the following variables to dictate where you pull the content from and where to store it for upload to the {PlatformNameShort} controller:
+
----
controller_postinstall_repo_url=<url_to_your_config-as-code_git_repository>
controller_postinstall_dir=<full_path_to_your_config-as-code_directory>
controller_postinstall_repo_ref=main
----
+
. The `controller_postinstall_repo_url` variable defines the postinstall repository URL which must include authentication information.

+
----
http(s)://<host>/<repo>.git (public repository without HTTP(S) authentication)
http(s)://<user>:<password>@<host>:<repo>.git (private repository with HTTP(S) authentication)
git@<host>:<repo>.git (public or private repository with SSH authentication)
----
+

[NOTE]
====
When using SSH based authentication, the installer does not configure anything for you, so you must configure everything on the installer node.
====

Definition files that are used by {Builder} to create {ExecEnvNameSing} images use the link:https://console.redhat.com/ansible/automation-hub/namespaces/infra/[infra certified collections]. The link:https://console.redhat.com/ansible/automation-hub/repo/validated/infra/controller_configuration/[controller_configuration] collection is preinstalled as part of the installation and uses the installation controller credentials you supply in the inventory file for access into the {PlatformNameShort} controller. You need to give the YAML configuration files. 

You can set up {PlatformNameShort} configuration attributes such as credentials, LDAP settings, users and teams, organizations, projects, inventories and hosts, job and workflow templates.

The following example shows a sample `your-config.yml` file defining and loading controller job templates. The example demonstrates a simple change to the  example provided with an {PlatformNameShort} installation.

----
/full_path_to_your_configuration_as_code/
├── controller
    	└── job_templates.yml
----

----
controller_templates:
 - name: Demo Job Template
   execution_environment: Default execution environment
   instance_groups:
 	- default
   inventory: Demo Inventory
----
