:_mod-docs-content-type: PROCEDURE



[id="proc-migrate-LDAP-users"]

= Migrating LDAP users without account linking

 
[role="_abstract"]

If a user is unable to link their accounts because there is no linking option for their {HubName} account, you must immediately configure the auto-migrate feature on all legacy password authenticators to target the new gateway LDAP authenticator.

Then, when a user logs in, the {Gateway} will automatically migrate the user to the LDAP authenticator if a matching UID is found.

.Prerequisites

* Verify that all legacy accounts are properly linked and merged before proceeding with auto-migration.

* Verify that there are no UID collisions or ensure they are manually migrated before proceeding with auto-migration.

.Procedure

. Log in to the {PlatformNameShort} UI.
. Set up a new LDAP authentication method in the {Gateway} following the steps in link:{URLCentralAuth}/gw-configure-authentication#controller-set-up-LDAP[Configuring LDAP authentication]. This will be the configuration that you will migrate your previous LDAP users to.
+
[NOTE]
====
{PlatformNameShort} 2.4 LDAP configurations are renamed during the upgrade process and are displayed in the *Authentication Methods* list view prefixed to indicate that it is a legacy configuration, for example,  `<controller/hub/eda>: legacy_password`. The *Authentication type* is listed as *Legacy password*. These configurations can not be modified.
====
+
. Select the legacy LDAP authenticator from the *Auto migrate users from* list. This is the legacy authenticator you want to use for migrating users to your {Gateway} LDAP authenticator.

Once you set up the auto migrate functionality, you should be able to login with LDAP in the {Gateway} and any matching accounts from the legacy 2.4 LDAP authenticator will automatically be linked.

