//Michelle - Archiving this module as it's now broken down into other modularized files
:_newdoc-version: 2.15.1
:_template-generated: 2024-01-12

:_mod-docs-content-type: REFERENCE

[id="using-custom-tls-certificates_{context}"]
= Using custom TLS certificates

By default, the installation program creates a self-signed Certificate Authority (CA) and uses it to generate self-signed TLS certificates for all {PlatformNameShort} services.

To use your own TLS certificates and keys to replace some or all of the self-signed certificates generated during installation, you can set specific variables in your inventory file. 

*Option 1: Use a custom CA to generate all TLS certificates*

To use a custom Certificate Authority (CA) to generate TLS certificates for all {PlatformNameShort} services, set the following variables in your inventory file:

----
ca_tls_cert=<path_to_ca_tls_certificate>
ca_tls_key=<path_to_ca_tls_key>
----

Use this method when you want {PlatformNameShort} to generate all of the certificates, but you want them signed by a custom CA rather than the default self-signed certificates.

*Option 2: Provide custom TLS certificates for each service*

To manually provide TLS certificates for each individual service (for example {ControllerName}, {HubName}, {EDAName}), set the following variables in your inventory file:

[source,yaml,subs="+attributes"]
----
# {GatewayStart}
gateway_tls_cert=<path_to_tls_certificate>
gateway_tls_key=<path_to_tls_key>
gateway_pg_tls_cert=<path_to_tls_certificate>
gateway_pg_tls_key=<path_to_tls_key>
gateway_redis_tls_cert=<path_to_tls_certificate>
gateway_redis_tls_key=<path_to_tls_key>

# {ControllerNameStart}
controller_tls_cert=<path_to_tls_certificate>
controller_tls_key=<path_to_tls_key>
controller_pg_tls_cert=<path_to_tls_certificate>
controller_pg_tls_key=<path_to_tls_key>

# {HubNameStart}
hub_tls_cert=<path_to_tls_certificate>
hub_tls_key=<path_to_tls_key>
hub_pg_tls_cert=<path_to_tls_certificate>
hub_pg_tls_key=<path_to_tls_key>

# {EDAName}
eda_tls_cert=<path_to_tls_certificate>
eda_tls_key=<path_to_tls_key>
eda_pg_tls_cert=<path_to_tls_certificate>
eda_pg_tls_key=<path_to_tls_key>
eda_redis_tls_cert=<path_to_tls_certificate>
eda_redis_tls_key=<path_to_tls_key>

# PostgreSQL
postgresql_tls_cert=<path_to_tls_certificate>
postgresql_tls_key=<path_to_tls_key>

# Receptor
receptor_tls_cert=<path_to_tls_certificate>
receptor_tls_key=<path_to_tls_key>
----

Use this method if your organization manages TLS certificates outside of {PlatformNameShort} and requires manual provisioning.

*Providing a custom CA certificate*

If any of the TLS certificates you manually provide are signed by a custom CA, you must specify the path to the CA certificate file by using the following variable in your inventory file:

----
custom_ca_cert=<path_to_custom_ca_certificate>
----

This is necessary for {PlatformNameShort} to trust the connections secured by these certificates, such as when configuring LDAPS (LDAP with TLS enabled) authentication.

If you have more than one CA certificate (for example a root CA and one or more intermediate certificates), combine them into a single file.  

Ensure the certificates are concatenated in the correct order, starting with the root CA followed by any intermediate CAs. 

Provide the absolute path to this combined certificate file by using the `custom_ca_cert` variable.
