:_mod-docs-content-type: REFERENCE

[[aap-2.6-fixed-issues]]

= Fixed issues
This section provides information about fixed issues in {PlatformNameShort} 2.6.

== {PlatformNameShort}

[NOTE]

====
{PlatformNameShort} 2.6 also includes the fixes from the latest 2.5 patch release. For more information see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/release_notes/patch_releases#aap-25-20250923[{PlatformNameShort}] patch release September 23, 2025.
====

{PlatformNameShort}

* The `SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL` configuration parameter now functions as expected, allowing social auth logins to set the platform gateway username to the user's email when enabled.(AAP-49736)


RPM-based {PlatformNameShort}

* Fixed an issue where installer managed CA certificates were discovered but not used by the installer.(AAP-53335)

Ansible {SelfServiceShort} 2.1.1

* Fixed an issue where credential selection dropdowns did not include the credential type, making it difficult to select the correct credential.
