// For each release of AAP, make a copy of this file and rename it to aap-rn-xx.adoc where xx is the release number; for example, 24 for the 2.4 release.
// Save the renamed copy of this file to the release-notes/topics directory topic files for the release notes reside.
//Only include release note types that have updates for a given release. For example, if there are no Technology previews for the release, remove that section from this file.

[id="new-features"]
= New features and enhancements

== General availability of {AAPchatbot}

The {AAPchatbot} is now generally available on {PlatformNameShort} {PlatformVers} on {OCPShort}. It is an intuitive chat interface embedded within the {PlatformNameShort}, utilizing generative artificial intelligence (AI) to answer questions about the {PlatformNameShort}.

The chat experience in the {AAPchatbot} interacts with users in their natural language prompts in English, and uses large language models (LLMs) to generate quick, accurate, and personalized responses. These responses empower users to work more efficiently, thereby improving productivity and the overall quality of their work.

To access and use the {AAPchatbot}, you need:
* {PlatformNameShort} {:PlatformVers} on {OCPShort}
* An LLM service that is hosted on either {RHELAI} or {OCPAI}

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html-single/installing_on_openshift_container_platform/index#deploying-chatbot-operator[Deploying the Ansible Lightspeed intelligent assistant on {OCPShort}] in Installing on {OCPShort}.

== General availability of Ansible self-service automation portal

Ansible self-service automation portal is now generally available as part of the {PlatformNameShort} subscription. The new self-service automation portal empowers platform admins to provide a streamlined “point-and-click” Ansible automation experience to a broader set of users within the organization. Users who aren’t Ansible experts now have a dedicated self-service portal from which they can launch a range of automation jobs.
* Installation options: Deploy self-service automation portal as a separate installation on {OCP} using a Helm chart. A documented method to install self-service automation portal on {RHEL} 10 is planned for Technology Preview release.
* Syncs existing automation content: Extend the reach and impact of your automation job templates, while maintaining full control and compliance. 
* Seamless Integration: Uses your existing {PlatformNameShort} configuration—same logins, same security controls, same automation logic.
* Simplified Interface: A distinct, user-friendly web interface designed for business users, not automation experts.
* Guided Workflows: Step-by-step forms that walk users through automation requests without technical complexity - automatically generated from your existing job templates.
* Smart Forms: Real-time field validation, conditional and dynamic forms, and dropdown fields for {PlatformNameShort} artifacts, such as {PlatformNameShort} inventories.


== {AutomationDashboardName}

{AutomationDashboardName} is a utility that can be connected to one or more {PlatformNameShort} deployments to visualize automation usage data, determine timesavings, track ROI, and drive increased visibility into automation strategy, resource allocation, and prioritization of automation projects.
* Deployed securely, on-premise: Simplified deployment as a self-contained, on-premise utility that runs on a dedicated RHEL 9 x86 and ARM host. 
* Easy Integration: Integrates into {PlatformNameShort} 2.4, 2.5 and {PlatformVers} instances with OAuth2 token for read-only access to pull data. 
* Automated data sync: Once configured, the dashboard automatically syncs and visualizes data from connected {PlatformNameShort} instances. 
* Flexible Reporting: Dashboard allows to generate and share customized PDF reports and export raw CSV data for flexible ingestion into BI tools. 


== Configuration as Code
The link:https://console.redhat.com/ansible/automation-hub/repo/published/ansible/platform/[ansible.platform] collection now provides unified, platform-wide Role-Based Access Control (RBAC) management across {PlatformNameShort} components. New or enhanced modules include `Organization`, `Team`, `User`, `Role definitions`, `Role Assignments` (team/user). Additionally:

* You can declare the RBAC state as code and apply idempotently across services.
* Ansible collections now use a standard global environment variable prefix across components. {ControllerNameStart}, {HubNameStart}, and {EDAName} all use a new standard of “AAP_” instead of "COMPONENT_". For example, `aap_hostname`. See link:https://console.redhat.com/ansible/automation-hub/repo/published/ansible/platform/docs/[the documentation] in {HubNameStart} for more information. 

== Service accounts 
* Service accounts, created in link:https://console.redhat.com/[console.redhat.com], can now be used to manage subscriptions in {PlatformNameShort}. Manifest files and basic authentication may still be used for this purpose as well.
* Service accounts are now required in order to send data to automation analytics. 


== {EDAName} (Automation decisions)
{EDAName} includes several key enhancements in the {PlatformNameShort} {PlatformVers} release that improve performance, simplify operations, and expand the platform's capabilities across security, networking, and event processing.

* *External secret management*: {EDAName} now supports external secret management systems, achieving parity with {ControllerNameStart}. This includes support for HashiCorp Vault, CyberArk, Microsoft Azure Key Vault, and AWS Secrets Manager.
* *Editable project URLs*: You can now edit the source control URL for existing {EDAName} projects, providing greater flexibility to adapt to repository changes.
* *Improved job auditing*: A new label is automatically added to jobs triggered by {EDAName}, along with support for custom labels. This allows for more efficient tracing and auditing of event-triggered automations.
* *Kafka enhancements*: The Kafka source plugin now supports multiple topics and allows the use of regular expressions and wildcards. Additionally, it now supports GSSAPI for enhanced authentication.
* *New event filter*: A new filter plugin, `event_splitter`, is available to handle and process nested events more effectively.
* *Rulebook concurrency key*: Rulebooks now support a concurrency key, enabling you to group events by resource to ensure they are processed sequentially.


== Installation updates

=== Containerized installation
Updated system requirements for containerized installation of {PlatformNameShort} include: 

* The {RHEL} 9.2 operating system requirement was updated to 9.4 or later minor versions of {RHEL} 9.
* {PostgresVers} 16 and 17 are now supported for customer provided (external) databases. 
+
[NOTE]
====
External databases using PostgreSQL 16 or 17 must rely on external backup and restore processes. Backup and restore functionality is dependent on utilities provided with PostgreSQL 15.
====

For more information see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/containerized_installation/aap-containerized-installation#system-requirements[System requirements] in _Containerized installation_.


=== Operator installation
Updated system requirements for {OperatorPlatformNameShort} on {OCP} include:
The {RHEL} 9.2 operating system requirement was updated to 9.4 or later minor versions of {RHEL} 9.
PostgreSQL 16 and 17 are now supported for customer-provided (external) databases. 
+
[NOTE]
====
External databases using PostgreSQL 16 or 17 must rely on external backup and restore processes. Backup and restore functionality is dependent on utilities provided with PostgreSQL 15.
====

For more information about the {OperatorPlatformNameShort} system requirements, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/tested_deployment_models/ocp-topologies[Operator topologies] in _Tested deployment models_. 


=== RPM installation
Updated system requirements for RPM installation of {PlatformNameShort} {PlatformVers} include:
 
* {PlatformNameShort} RPM installer was deprecated in 2.5 and will be removed in {PlatformNameShort} 2.7. The RPM installer will be supported for RHEL 9 during the lifecycle of {PlatformNameShort} {PlatformVers} to support migrations to existing supported topologies. See the support matrix for more information on upgrade and migration paths.
* {RHEL} 9.2 operating system requirement was updated to 9.4 or later minor versions of {RHEL} 9. {RHEL} 8 is no longer supported. 
* {RHEL} 10 is not supported for RPM installations. See Support matrix for more information on supported upgrade and migration paths.
* PostgreSQL 16 and 17 are now supported for customer-provided (external) databases. 
+
[NOTE]
====
External databases using PostgreSQL 16 or 17 must rely on external backup and restore processes. Backup and restore functionality is dependent on utilities provided with PostgreSQL 15.
====

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/rpm_installation/platform-system-requirements[System requirements] in _RPM installation_.


== Upgrade paths

The following table outlines the supported upgrade paths for {PlatformNameShort} {PlatformVers}.

[NOTE]
====
The RPM-based upgrade paths are deprecated and will be removed in {PlatformNameShort} 2.7.
====

[cols="1,2a"]
|===
|Starting Deployment |Upgrade Deployment

|2.4 RPM single automation controller node
|2.6 RPM growth

|2.4 RPM single node automation controller and automation hub
|2.6 RPM growth

|2.4 RPM multi node automation controller
|2.6 RPM enterprise

|2.4 RPM multi node automation controller and automation hub
|2.6 RPM enterprise

|2.5 RPM growth
|2.6 RPM growth

|2.5 RPM enterprise
|2.6 RPM enterprise

|2.5 Container growth
|2.6 Container growth

|2.5 Container enterprise
|2.6 Container enterprise

|2.4 Operator single automation controller node
|2.6 Operator growth

|2.4 Operator single node automation controller and automation hub
|2.6 Operator growth

|2.4 Operator multi node automation controller
|2.6 Operator enterprise

|2.4 Operator multi node automation controller and automation hub
|2.6 Operator enterprise

|2.5 Operator growth
|2.6 Operator growth

|2.5 Operator enterprise
|2.6 Operator enterprise
|===

*Additional resources*
* link:https://docs.google.com/document/d/14AzkjXpzQlNY9HPmsrHuJ4YRsiHp2cjtFtdZaHUMQXw/edit?tab=t.752cqa45zgnb#heading=h.t333hshr9hqn[Support matrix for upgrade scenarios]
* link:https://docs.google.com/document/d/14AzkjXpzQlNY9HPmsrHuJ4YRsiHp2cjtFtdZaHUMQXw/edit?tab=t.o5vdwgbtqb96#heading=h.931kjylbtwz9[Infrastructure changes by deployment type]
* link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_upgrade_and_migration/index[RPM upgrade and migration]
* link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/containerized_installation/aap-containerized-installation#updating-containerized-ansible-automation-platform[Updating containerized Ansible Automation Platform]
* link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/installing_on_openshift_container_platform/index#operator-upgrade_licensing-gw[Upgrading Red Hat Ansible Automation Platform Operator on Red Hat OpenShift Container Platform]

== Migration paths

The following table outlines the supported migration paths for {PlatformNameShort} {PlatformVers}. Migration involves transitioning between deployment types, such as from an RPM to a containerized installation. This process is exclusively supported between identical versions (for example, 2.6 to 2.6).

[cols="1,2a"]
|===
|Source environment |Target environment

|RPM-based {PlatformNameShort}
|Container-based {PlatformNameShort} platform

|RPM-based {PlatformNameShort}
|{OCPShort}

|RPM-based {PlatformNameShort}
|Managed {PlatformNameShort}

|Container-based {PlatformNameShort}
|{OCPShort}

|Container-based {PlatformNameShort}
|Managed {PlatformNameShort}
|===

*Additional resources*
* link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/ansible_automation_platform_migration/index[Ansible Automation Platform migration]


== Overview of upgrade improvements

{PlatformNameShort} {PlatformVers} includes changes that significantly improve the upgrade experience when moving from {PlatformNameShort} 2.4 to {PlatformVers}. 

[NOTE]
====
You must be on the latest version of 2.4 or 2.5 before you upgrade to {PlatformVers}.
====

[cols="1,2,2"]
|===
|Scenario |Changes |Additional information

|Upgrading from 2.5 to {PlatformVers}
|Upgrading from 2.5 to {PlatformVers} does not involve changes to the platform infrastructure requirements, architecture, or services. The improvements described in the 2.4 to {PlatformVers} upgrade path are also present in the 2.5 to {PlatformVers} upgrade path; however, the platform gateway service is already in place in 2.5.
+
If you upgraded from 2.4 to 2.5, you must migrate your authentication methods and users before upgrading to {PlatformVers} as that legacy authenticator functionality was removed.
+
Any users that were created during the 2.4 to 2.5 upgrade that were not fully migrated will be removed from the system when upgrading to {PlatformVers}. The users that have previously merged their user records while on 2.5 will remain to function as is for {PlatformVers}.
+
Any 2.4 Controller users that have not successfully logged into 2.5 since upgrading from 2.4, will be unable to log into platform-gateway after a {PlatformVers} upgrade. The user will be backwards compatible for direct Automation Execution access but unable to access the full platform. Please ensure all users planning to leverage {PlatformVers} have successfully logged into 2.5 prior to upgrading.
+
[NOTE]
====
Upgrades from the latest 2.5 version to {PlatformVers} are supported with all deployment types: RPM, containerized, and {OCPShort} deployments.
====
+
|See the upgrade document for your deployment type:
* link:https://docs.google.com/document/d/193r5akjbJzKbr6eId80DxpbV8ecSmY6wwSmWoC-mrAM/edit?tab=t.46pbcughs3i5[Containerized]
* link:https://docs.google.com/document/d/1q81ZeYJZtYY7-Y5iAcP-yROBWK_W5WPNjoH63xSQMhQ/edit?tab=t.vaz1y0ja9s8u[RPM]
* link:https://docs.google.com/document/d/1_P7iQFd2ausj2FDlvfKPIdxMVmhY__osm020tvdWywE/edit?tab=t.0[{OCPShort}]

|Upgrading from 2.4 to {PlatformVers}
|{PlatformNameShort} supports upgrading directly from the latest 2.4 version to {PlatformVers}. Directly upgrading to {PlatformVers} is the recommended upgrade path from 2.4, as a number of improvements in {PlatformVers} simplify and improve the upgrade experience.
+
[NOTE]
====
You can upgrade directly from the latest 2.4 version to {PlatformVers} with RPM and {OCPShort} deployments. However, upgrading {EDAName} 2.4 or from the 2.4 containerized deployment is not supported, as both features were Tech Preview in 2.4. 
====
|See the upgrade document for your deployment type:
* link:https://docs.google.com/document/d/1q81ZeYJZtYY7-Y5iAcP-yROBWK_W5WPNjoH63xSQMhQ/edit?tab=t.vaz1y0ja9s8u#heading=h.5y1sxp6xe6on[RPM]
* link:https://docs.google.com/document/d/1_P7iQFd2ausj2FDlvfKPIdxMVmhY__osm020tvdWywE/edit?tab=t.0[{OCPShort}]

|Upgrading from 2.4 to {PlatformVers}
|{PlatformNameShort} RPM deployments require additional infrastructure compared with 2.4, due to the addition of the platform gateway service. Infrastructure needs vary depending on factors such as whether you implement a growth or an enterprise deployment. 
+
[NOTE]
====
Additional infrastructure requirements apply only when upgrading RPM deployments.
====
|See link:https://docs.google.com/document/d/14AzkjXpzQlNY9HPmsrHuJ4YRsiHp2cjtFtdZaHUMQXw/edit?tab=t.o5vdwgbtqb96[Infrastructure changes] for details about infrastructure and inventory file changes in various upgrade scenarios.

|Upgrading from 2.4 to {PlatformVers}
|Enterprise authentication configuration and mappings (for example, SAML, LDAP, OIDC) move from automation controller 2.4 to platform gateway {PlatformVers} as part of the upgrade process. You do not need to manually reconfigure these authentication methods after you upgrade.
+
[NOTE]
====
Authentication upgrade improvements apply to RPM and {OCPShort} deployments. Upgrades from the 2.4 containerized deployment Tech Preview release are not supported. Additionally, upgrading {EDAName} 2.4 is not supported.
====
|See link:https://docs.google.com/document/d/1CH5HSx5Qf1mFbJEsSPg3uAP2beib-C2mUR1UkLOHzSM/edit?tab=t.0[Access management and authentication] for information about authentication options in general.

|Upgrading from 2.4 to {PlatformVers}
|All automation controller Identity Access Management (IAM) data moves from automation controller 2.4 to the platform gateway in {PlatformVers} as part of the upgrade process. With automation controller 2.4 as the default source of IAM data for the platform gateway in {PlatformVers}, users retain their memberships and are assigned appropriate platform-level roles in {PlatformVers}. 
+
As part of the upgrade process:
* Users, teams, organizations, their memberships, and common roles in 2.4 move from automation controller 2.4 to the platform gateway in {PlatformVers}.
* Administrators in automation controller 2.4 become platform gateway administrators in {PlatformVers}.
* Controller admins in 2.4 become platform gateway admins in {PlatformVers}.
+
The more organizations, teams, and users being migrated during an upgrade, the longer the upgrade takes. As an example, upgrading and migrating 4,000 users, 400 teams, and 40 organizations may take close to two hours.
+
[NOTE]
====
Identity access management changes apply to RPM and {OCPShort} deployments. Upgrades from the 2.4 containerized deployment Tech Preview release are not supported. 
====
|See link:https://docs.google.com/document/d/1H_X2InQz_uqdG1Gh4fwjeDr01iMEn31Njsb0mOdzM6E/edit?tab=t.0#heading=h.vgwhaqyr0dyl[Data movement during upgrade] for more information. 

|Upgrading from 2.4 to {PlatformVers}
|Some APIs are being deprecated in {PlatformVers}.
|See link:https://docs.google.com/document/d/14AzkjXpzQlNY9HPmsrHuJ4YRsiHp2cjtFtdZaHUMQXw/edit?tab=t.j1bmvnq8zfsq#heading=h.3xd478hxdjua[API changes] for more information.
|===

== Platform UI

{PlatformNameShort} {PlatformVers} was delivered with the goal to simplify the UI, improve the relationship between user interface elements, and maintain the association between users, organizations, teams, and roles.

Within the Platform UI, the role based access controls (RBAC) have been centralized to give administrators control of users across the entire platform. The centralized RBAC has introduced additional APIs and expanded the scope of those APIs to allow the assignment of roles across any of the platform resources. The details of these changes are reflected within the link:https://docs.google.com/document/d/14AzkjXpzQlNY9HPmsrHuJ4YRsiHp2cjtFtdZaHUMQXw/edit?tab=t.j1bmvnq8zfsq#heading=h.3xd478hxdjua[API changes]. 

The UI has also been updated to the latest version of Patternfly, which brings significant updates and refinements aiming to enhance user experience, performance, and developer efficiency.


= Technology Preview

=== Ansible Lightspeed intelligent assistant integration with MCP

Ansible Lightspeed intelligent assistant integration with the Model Context Protocol (MCP) server is now available as a Technology Preview release. This integration enhances the user experience by delivering relevant, dynamically sourced data results to your queries. For information about how to access and use the Ansible Lightspeed intelligent assistant, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/installing_on_openshift_container_platform/deploying-chatbot-operator[Deploying the Ansible Lightspeed intelligent assistant on {OCPShort}] guide.


= Removed features

Removed features are those that were deprecated in earlier releases. They are now removed from the {PlatformNameShort} 2.5, and will no longer be supported. 

[cols="1,2a"]
|===
|Component |Feature

|{EDAcontroller}
|Removal of `max_running_activations setting in eda-controller`

|{GatewayStart}
|Legacy Authenticators that were added during an upgrade from 2.4 to 2.5 will no longer be present
|===



//Not sure if I should comment out/delete the rest of this documentation in this file. 




== Installation changes
Starting with {PlatformNameShort} 2.5, three different on-premise deployment models are fully tested. In addition to the existing RPM-based installer and operator, support for the containerized installer is being added. 

As the platform moves toward a container-first model, the RPM-based installer will be removed in a future release, and a deprecation warning is being issued with the release of {PlatformNameShort} 2.5. While the RPM installer will still be supported for {PlatformNameShort} 2.5 until it is removed, the investment will focus on the {ContainerBase} for RHEL deployments and the {OperatorBase} for OpenShift deployments. Upgrades from 2.4 containerized {PlatformNameShort} Technology Preview to 2.5 containerized {PlatformNameShort} are unsupported. 

== Deployment topologies
Red Hat tests {PlatformNameShort} 2.5 with a defined set of topologies to give you opinionated deployment options. Deploy all components of {PlatformNameShort} so that all features and capabilities are available for use without the need to take further action.

It is possible to install {PlatformNameShort} on different infrastructure topologies and with different environment configurations. Red Hat does not fully test topologies outside of published reference architectures. Red Hat recommends using a tested topology for all new deployments and provides commercially reasonable support for deployments that meet minimum requirements.  

At the time of the {PlatformNameShort} 2.5 GA release, a limited set of topologies are fully tested. Red Hat will regularly add new topologies to iteratively expand the scope of fully tested deployment options. As new topologies roll out, we will include them in the release notes. 

The following table shows the tested topologies for {PlatformNameShort} 2.5:

[%autowidth]
|===
| Mode | Infrastructure | Description | Tested topologies

|RPM | Virtual Machines/Bare Metal | The RPM installer deploys the {PlatformNameShort} on {RHEL} using RPMs to install the platform on host machines. Customers manage the product and infrastructure lifecycle.
a| 
* RPM {GrowthTopology}
* RPM {EnterpriseTopology}

|Containers | Virtual Machines/Bare Metal | The containerized installer deploys the {PlatformNameShort} on {RHEL} by using Podman that runs the platform in containers on host machines. Customers manage the product and infrastructure lifecycle.
a| 
* Container {GrowthTopology}
* Container {EnterpriseTopology}

|Operator | Red Hat OpenShift | The operator uses Red Hat OpenShift operators to deploy the {PlatformNameShort} within Red Hat OpenShift. Customers manage the product and infrastructure lifecycle.
a| 
* Operator {GrowthTopology}
* Operator {EnterpriseTopology}
|===

For more information, see {LinkTopologies}. 

== Unified UI
In versions before 2.5, the {PlatformNameShort} was split into three primary services: {ControllerName}, {HubName}, and {EDAcontroller}. Each service included standalone user interfaces, separate deployment configurations, and separate authentication schemas.

In {PlatformNameShort} 2.5, the {Gateway} is provided as a service that handles authentication and authorization for the {PlatformNameShort}. With the {Gateway}, all services that make up the {PlatformNameShort} are consolidated into a single unified UI. The unified UI provides a single entry into the {PlatformNameShort} and serves the platform user interface to authenticate and access all of the {PlatformNameShort} services from a single location.

=== Terminology changes

The Unified UI highlights the functional benefits provided by each underlying service. New UI terminology aligns to earlier names as follows:

* *Automation execution* provides functionality from the *{ControllerName}* service
* *Automation decisions* provides functionality from the *{EDAName}* service
* *Automation content* provides functionality from the *{HubName}* service

== {EDAName} functionality (Automation decisions)
With {PlatformNameShort} 2.5, {EDAName} functionality has been enhanced with the following features:

* Enterprise single-sign on and role-based access control are available through a new {PlatformNameShort} UI, which enables a single point of authentication and access to all functional components as follows: 
** Automation Execution ({ControllerName})
** Automation Decision ({EDAName})
** Automation Content ({HubName})
** Automation Analytics
** Access Management
** {LightspeedShortName}

* Simplified event routing capabilities introduce event streams. Event streams are an easy way to connect your sources to your rulebooks. This new capability lets you create a single endpoint to receive alerts from an event source and then use the events in multiple rulebooks. This simplifies rulebook activation setup, reduces maintenance demands, and helps lower risk by eliminating the need for additional ports to be open to external traffic. 

* {EDAName} in the {PlatformNameShort} 2.5 now supports horizontal scaling, allowing you to install multiple {EDAName} nodes to handle increased event volume. 

* Migration to the new platform-wide {PlatformName} credential type replaces the legacy controller token for enabling rulebook activations to call jobs in the {ControllerName}.

* {EDAName} now has the ability to manage credentials that can be added to rulebook activations. These credentials can be used in rulebooks to authenticate to event sources. In addition, you can now attach vault credentials to rulebook activations so that you can use vaulted variables in rulebooks. Encrypted credentials and vaulted variables enable enterprises to secure the use of {EDAName} within their environment.

* New modules are added to the *ansible.eda* collection to enable users to automate the configuration of the {EDAcontroller} using Ansible playbooks.

[id="eda-2.5-with-automation-controller-2.4"]
== {EDAName} 2.5 with {ControllerName} 2.4
You can use a newly installed version of {EDAName} from {PlatformNameShort} 2.5 with some existing versions of the {ControllerName}. A hybrid configuration is supported with the following versions:

* 2.4 {PlatformNameShort} version of {ControllerName} (4.4 or 4.5)
* 2.5 {PlatformNameShort} version of {EDAName} (1.1)

You can only use new installations of {EDAName} in this configuration. RPM-based hybrid deployments are fully supported by Red Hat. For details on setting up this configuration, see the chapter *Installing {EDAController} 1.1 and configuring {ControllerName} 4.4 or 4.5* in the link:{BaseURL}/red_hat_ansible_automation_platform/2.4/html/using_event-driven_ansible_2.5_with_ansible_automation_platform_2.4[Using Event-Driven Ansible 2.5 with Ansible Automation Platform 2.4] guide.

A hybrid configuration means you can install a new {EDAName} service and configure rulebook activations to execute job templates on a 2.4 version of the {ControllerName}.

== {LightspeedShortName} on-premise deployment 
{LightspeedFullName} is a generative AI service that helps automation teams create, adopt, and maintain Ansible content more efficiently; it is now available as an on-premise deployment on the {PlatformNameShort} 2.5. 

The on-premise deployment provides the {PlatformNameShort} customers more control over their data and supports compliance with enterprise security policies. For example, organizations in sensitive industries with data privacy or air-gapped requirements can use on-premise deployments of both {LightspeedShortName} and {ibmwatsonxcodeassistant} for {LightspeedShortName} on Cloud Pak for Data. {LightspeedShortName} on-premise deployments are supported on {PlatformNameShort} 2.5. For more information, see the chapter link:https://docs.redhat.com/en/documentation/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant/2.x_latest/html-single/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant_user_guide/index#configuring-lightspeed-onpremise_set-up-lightspeed[Setting up {LightspeedShortName} on-premise deployment] in the _{LightspeedFullName} User Guide_.

== {AAPRHDH}
The {AAPRHDH} deliver an Ansible-first {RHDH} user experience that simplifies creating Ansible content, such as playbooks and collections, for Ansible users of all skill levels. The Ansible plug-ins provide curated content and features to accelerate Ansible learner onboarding and streamline Ansible use case adoption across your organization. 

The Ansible plug-ins provide the following capabilities:

* A customized home page and navigation tailored to Ansible users
* Curated Ansible learning paths to help users new to Ansible
* Software templates for creating Ansible playbooks and collection projects that follow best practices
* Links to supported development environments and tools with opinionated configurations

For more information, see _{LinkPluginRHDHInstall}_. 
//For more information, see the link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/installing_ansible_plug-ins_for_red_hat_developer_hub/rhdh-intro_aap-plugin-rhdh-installing#rhdh-about-plugins_rhdh-intro[{AAPRHDH}] documentation. 


== {ToolsName}
{ToolsName} is a suite of tools provided with the {PlatformNameShort} to help automation creators create, test, and deploy playbook projects, execution environments, and collections on Linux, MacOS, and Windows platforms. Consolidating core Ansible tools into a single package simplifies tool management and promotes recommended practices in the automation content creation experience.

{ToolsName} are distributed in an RPM package for RHEL systems, and in a supported container distribution that can be used on Linux, Mac, and Windows OS.

{ToolsName} comprise the following tools:

* ansible-builder
* ansible-core
* ansible-lint
* ansible-navigator
* ansible-sign
* Molecule
* ansible-creator
* ansible-dev-environment
* pytest-ansible
* tox-ansible

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/developing_ansible_automation_content/index[Developing Ansible automation content]. 

== {SaaSonAWS}

{SaaSonAWS} is a deployment of the {PlatformNameShort} control plane purchased through AWS Marketplace. Red{nbsp}Hat manages the service so that customer teams can focus on automation.

For more information, see link:{BaseURL}/ansible_on_clouds/2.x/html-single/red_hat_ansible_automation_platform_service_on_aws/index[{SaaSonAWS}].

== Enhancements

* Added the ability to provide `mounts.conf` or copy from a local or remote source when installing Podman. (AAP-16214)

* Updated the inventory file to include the SSL key and certificate parameters for provided SSL web certificates. (AAP-13728)

* Added an {PlatformNameShort} operator-version label on Kubernetes resources created by the operator. (AAP-31058)

* Added installation variables to support PostgreSQL certificate authentication for user-provided databases. (AAP-1095)

* Updated NGINX to version 1.22. (AAP-15128)

* Added a new configuration endpoint for the REST API. (AAP-13639)

* Allowed adjustment of *RuntimeDirectorySize* for Podman environments at the time of installation. (AAP-11597)

* Added support for the *SAFE_PLUGINS_FOR_PORT_FORWARD* setting for *eda-server* to the installation program. (AAP-21503)

* Aligned inventory content to tested topologies and added comments for easier access to groups and variables when custom configurations are required. (AAP-30242)

* The variable *`automationedacontroller_allowed_hostnames`* is no longer needed and is no longer supported for {EDAName} installations. (AAP-24421)

* The *eda-server* now opens the ports for a rulebook with a source plugin that requires inbound connections only if that plugin is allowed in the settings. (AAP-17416)

* The {EDAName} settings are now moved to a dedicated YAML file. (AAP-13276)

* Starting with {PlatformNameShort} 2.5, customers using the controller collection (`ansible.controller`) have the platform collection (`ansible.platform`) as a single point of entry, and must use the platform collection to seed organizations, users, and teams. (AAP-31517)

* Users are opted in for {Analytics} by default when activating {ControllerName} on first time log in. (ANSTRAT-875)

////
THE FOLLOWING IS THE SNIPPET FOR TECH. PREVIEW. ADD THIS SNIPPET IF THERE ARE ANY TECH. PREVIEW FEATURES FOR THE RELEASE. AAP 2.5 HAD NO TECH. PREVIEW FEATURES.
== Technology Preview

include::../snippets/technology-preview.adoc[]

The following are Technology Preview features: 

* Starting with {PlatformNameShort} 2.4, the Platform Resource Operator can be used to create the following resources in {ControllerName} by applying YAML to your OpenShift cluster:
** Inventories
** Projects
** Instance Groups
** Credentials
** Schedules
** Workflow Job Templates
** Launch Workflows

You can now configure the Controller Access Token for each resource with the `connection_secret` parameter, rather than the `tower_auth_secret` parameter. This change is compatible with earlier versions, but the `tower_auth_secret` parameter is now deprecated and will be removed in a future release.

[role="_additional-resources"]
.Additional resources

* For the most recent list of Technology Preview features, see link:https://access.redhat.com/articles/ansible-automation-platform-preview-features[Ansible Automation Platform - Preview Features].
////
