:_mod-docs-content-type: REFERENCE

[[aap-2.6-known-issues]]

= Known issues
This section provides information about known issues in {PlatformNameShort} 2.6.

* For role based authentication mappings, the role list includes all roles within the platform. Only the role assignments of Org Admin, Org Member, Team Admin, Team Member, and Platform Auditor are supported at this time. The list will be limited to only those that can be applied at a platform level in a subsequent release.

* If you have an existing deployment of {LightspeedShortName} on {PlatformNameShort} 2.5, upgrading to {PlatformNameShort} 2.6 will cause your {LightspeedShortName} deployment to fail. To avoid this failure, do not upgrade to {PlatformNameShort} 2.6 until a forthcoming patch is released on October 22, 2025. However, new deployments of {LightspeedShortName} will work correctly on {PlatformNameShort} 2.6.(AAP-54064)
+
For more information, see link:https://access.redhat.com/articles/7132132[Ansible Lightspeed upgrade fails when upgrading Ansible Automation Platform 2.5 to 2.6].

