[[aap-2.5-fixed-issues]]
= Fixed issues

This section provides information about fixed issues in {PlatformNameShort} 2.5.

== {PlatformNameShort}

* The installer now ensures semanage command is available when SELinux is enabled. (AAP-24396)

* The installer can now update certificates without attempting to start the nginx service for previously installed environments. (AAP-19948)

* {EDAName} installation now fails when the pre-existing {ControllerName} is older than version 4.4.0. (AAP-18572)

* {EDAName} can now successfully install on its own with a controller URL when the controller is not in the inventory. (AAP-16483)

* Postgres tasks that create users in FIPS environments now use *scram-sha-256*. (AAP-16456)

* The installer now successfully generates a new `SECRET_KEY` for controller. (AAP-15513)

* Ensure all backup and restore staged files and directories are cleaned up before running a backup or restore. You must also mark the files for deletion after a backup or restore. (AAP-14986)

* Postgres certificates are now temporarily copied when checking the Postgres version for SSL mode verify-full. (AAP-14732)

* The setup script now warns if the provided log path does not have write permissions, and fails if default path does not have write permissions. (AAP-14135)

* The linger configuration is now correctly set by the root user for the {EDAName} user. (AAP-13744)

* Subject alternative names for component hosts will now only be checked for signing certificates when HTTPS is enabled. (AAP-7737)

* The UI for creating and editing an organization now validates the *Max hosts* value. This value must be an integer and have a value between 0 and 214748364. (AAP-23270)

* Installations that do not include the {ControllerName} but have an external database will no longer install an unused internal Postgres server. (AAP-29798)

* Added default port values for all `pg_port` variables in the installer. (AAP-18484)

* *XDG_RUNTIME_DIR* is now defined when applying {EDAName} linger settings for Podman. (AAP-18341)*

* Fixed an issue where the restore process failed to stop *pulpcore-worker* services on RHEL 9. (AAP-12829)

* Fixed Postgres *sslmode* for verify-full that affected external Postgres and Postgres signed for 127.0.0.1 for internally managed Postgres. (AAP-7107)

* Fixed support for {HubName} content signing. (AAP-9739)

* Fixed conditional code statements to align with changes from ansible-core issue #82295. (AAP-19053)

* Resolved an issue where providing the database installation with a custom port broke the installation of Postgres. (AAP-30636) 

== {HubNameStart}

* {HubNameStart} now uses system crypto-policies in nginx. (AAP-17775)

== {EDAName}

* Fixed a bug where the Swagger API docs URL returned 404 error with trailing slash. (AAP-27417)

* Fixed a bug where logs contained stack trace errors inappropriately. (AAP-23605)

* Fixed a bug where the API returned error 500 instead of error 400 when a foreign key ID did not exist. (AAP-23105)

* Fix a bug where the Git hash of a project could be empty. (AAP-21641)

* Fixed a bug where an activation could fail at the start time due to authentication errors with Podman. (AAP-21067)

* Fixed a bug where a project could not get imported if it contained a malformed rulebook. (AAP-20868)

* Added *EDA_CSRF_TRUSTED_ORIGINS*, which can be set by user input or defined based on the allowed hostnames provided or determined by the installer as a default. (AAP-19319)

* Redirected all {EDAName} traffic to `/eda/` following UI changes that require the redirect. (AAP-18989)

* Fixed target database for Event-Driven automation restore from backup. (AAP-17918)

* Fixed the {ControllerName} URL check when installing {EDAName} without a controller. (AAP-17249)

* Fixed a bug when the membership operator failed in a condition applied to a previously saved event. (AAP-16663)

* Fixed {EDAName} nginx configuration for custom HTTPS port. (AAP-16000)

* Instead of the target service only, all {EDAName} services are enabled after installation is completed. The {EDAName} services will always start after the setup is complete. (AAP-15889)

== {OperatorPlatformNameShort}

* Fixed Django REST Framework (DRF) browsable views. (AAP-25508)

== {AAPRHDH}

The following updates were introduced in {AAPRHDH} 1.2:

* Improvements in error handling and logging for collection and playbook project scaffolder.
* Updates to the `backstage-rhaap-backend` plugin for compatibility with {RHDHShort} 1.4.


== Ansible self-service automation portal version 2.1.1

* Fixed an issue where credential selection dropdowns did not include the credential type, making it difficult to select the correct credential.
