[id="async-24-20250730"]

= {PlatformNameShort} patch release July 30, 2025

The following enhancements and bug fixes have been implemented in this release of {PlatformNameShort}.

[cols="1a,3a", options="header"]
|===
| Release date | Component versions

| July 30, 2025  | 
* {ControllerNameStart} 4.5.24
* {EDAcontroller} 1.0.7
* {HubNameStart} 4.9.4
* {LightspeedShortName} 2.4.250225
* {PlatformNameShort}-collection installer (online) 2.4-13
* {PlatformNameShort}-collection installer (bundle) 2.4-13
* Receptor 1.5.7
|===

CSV Versions in this release:

* Namespace-scoped Bundle: aap-operator.v2.4.0-0.1753232084 

* Cluster-scoped Bundle: aap-operator.v2.4.0-0.1753232791


== General

* The `redhat.rhel_system_roles` collection has been updated to 1.95.7.(AAP-49917)

* The `ansible.windows` collection has been updated to 2.8.0.(AAP-48369)


== {PlatformNameShort}

=== Bug Fixes

* Fixed an issue where the {HubName} resource was failing during a {OperatorPlatformName} update due to a wrong task file reference in `upgrade_postgres.yml`.(AAP-49103)


== RPM-based {PlatformNameShort}

=== Bug Fixes

* Fixed an issue where the certified collections in the bundle installer did not match what is included in the execution environment image.(AAP-48368)
