[id="async-24-20250827"]

= {PlatformNameShort} patch release August 27, 2025

The following enhancements and bug fixes have been implemented in this release of {PlatformNameShort}.

[cols="1a,3a", options="header"]
|===
| Release date | Component versions

| August 27, 2025  | 
* {ControllerNameStart} 4.5.25
* {EDAcontroller} 1.0.7
* {HubNameStart} 4.9.5
* {LightspeedShortName} 2.4.250225
* {PlatformNameShort}-collection installer (online) 2.4-13
* {PlatformNameShort}-collection installer (bundle) 2.4-13.2
* Receptor 1.5.7
|===

CSV Versions in this release:

* Namespace-scoped Bundle: aap-operator.v2.4.0-0.1755833431

* Cluster-scoped Bundle: aap-operator.v2.4.0-0.1755833968


== General

* The `ansible.controller` collection has been updated to 4.5.25.(AAP-51876)



== {PlatformNameShort}

=== Bug Fixes

* Fixed an issue to use `scram-sha-256 password` encryption to enable FIPS for operator deployments.(AAP-49371)

* Fixed the scale-down process when upgrading from *PostgreSQL* 13 to 15.(AAP-49103)

* Fixed an issue to resolve `public_base_url` undefined variable error when the 2.4 {OperatorPlatformNameShort} is installed in another namespace on the same cluster as a 2.5 {OperatorPlatformNameShort} install.(AAP-46486)


== {ControllerNameStart}

=== Bug Fixes

* Fixed an optimization issue on the jobs list page to reduce the number of API calls.(AAP-50102)

== Event-Driven Ansible

=== Bug Fixes

* Fixed an issue with the *PostgreSQL* password encryption when upgrading from PG13 to PG15 on FIPS.(AAP-50453)
