[id="async-24-20260325"]

= {PlatformNameShort} patch release March 25, 2026

The following enhancements and bug fixes have been implemented in this release of {PlatformNameShort}.


[cols="1a,3a", options="header"]

|====

| Release Date | Component versions

| March 26, 2026 
a|

* {ControllerNameStart} 4.5.32
* {HubNameStart} 4.9.7
* {EDAcontroller} 1.0.11
* {LightspeedShortName} 2.4.260325
* {PlatformNameShort}-collection installer (bundle): 2.4-16
* {PlatformNameShort}-collection installer (online): 2.4-16
* Receptor 1.6.3

|====

The following enhancements and bug fixes have been implemented in this release of {PlatformNameShort}.

CSV versions in this release:

* Namespace-scoped bundle: aap-operator.v2.4.0-0.1774577278
* Cluster-scoped bundle: aap-operator.v2.4.0-0.1774582128


== Features

=== Controller

* This change updates receptorctl version to 1.6.4. AAP-66805

== Enhancements

=== General

* This enhancement upgrades the Django dependency so that all components move from Django 4.2 to Django 5.2 and aligns with the platform-wide framework baseline. This update helps all components receive the latest security fixes and long-term support guarantees from the Django framework. AAP-60390 AAP-59871
