[[platform-introduction]]
= Overview of {PlatformName}

{PlatformName} simplifies the development and operation of automation workloads for managing enterprise application infrastructure life cycles. {PlatformNameShort} works across multiple IT domains, including operations, networking, security, and development, as well as across diverse hybrid environments. Simple to adopt, use, and understand, {PlatformNameShort} provides the tools needed to rapidly implement enterprise-wide automation, no matter where you are in your automation journey.

== Automation for the enterprise

Red Hat Ansible's latest evolution is engineered for your success, designed to make your automation journey more accessible, transparent, and intelligent. We understand that efficient, controlled, and scalable IT operations are crucial for the future, and this release directly addresses how to unlock the full potential of your automation practices. Shaped by invaluable input from customers and users worldwide, this update represents a significant stride towards empowering transformative, end-to-end automation.

* *Accessible automation* with more deployment flexibility, streamlined migration paths, and self-service capabilities for your entire organization.
* *Transparent operations* through new levels of visibility, control, and auditability for all your automation processes.
* *Intelligent platform experience* powered by integrated AI capabilities, enabling smarter decisions and optimized performance for your enterprise.

== Platform services in 2.6 

These are the major service versions in {PlatformNameShort} {PlatformVers}. For more current information, see the entire life cycle page at https://access.redhat.com/support/policy/updates/ansible-automation-platform. 

[%header, %autowidth]
|===
| {PlatformNameShort} version | {GatewayStart} (unified UI) version | {ControllerNameStart} (automation execution) version | {HubNameStart} (automation content) version | {EDAcontroller} (automation decisions) version | Ansible-core version 

|2.6.20250924 | 2.6.20250924 | 4.7.0 | 4.11.0 | 1.2.0 | 2.16

|===
