:_mod-docs-content-type: REFERENCE

[[platform-introduction]]
= Overview of {PlatformName}

{PlatformName} simplifies the development and operation of automation workloads for managing enterprise application infrastructure lifecycles. {PlatformNameShort} works across multiple IT domains, including operations, networking, security, and development, as well as across diverse hybrid environments. Simple to adopt, use, and understand, {PlatformNameShort} provides the tools needed to rapidly implement enterprise-wide automation, no matter where you are in your automation journey.

[[whats-included]]
== What is included in the {PlatformNameShort}

[%header, %autowidth]
|===
| {PlatformNameShort} | {ControllerNameStart} | {HubNameStart} | {EDAcontroller} | {InsightsShort} | {GatewayStart} +
(Unified UI)

|2.5 | 4.6.0
a|
* 4.10.0
* hosted service|
1.1.0
| hosted service
| 1.1

|===

== {PlatformName} life cycle

Red Hat provides different levels of maintenance for each {PlatformNameShort} release. For more information, see link:https://access.redhat.com/support/policy/updates/ansible-automation-platform[{PlatformName} Life Cycle].

