[[tech-preview]]
= Technology preview


== Technology Preview

include::../snippets/technology-preview.adoc[]

The following are Technology Preview features: 

* Starting with {PlatformNameShort} 2.4, the Platform Resource Operator can be used to create the following resources in {ControllerName} by applying YAML to your OpenShift cluster:
** Inventories
** Projects
** Instance Groups
** Credentials
** Schedules
** Workflow Job Templates
** Launch Workflows

You can now configure the Controller Access Token for each resource with the `connection_secret` parameter, rather than the `tower_auth_secret` parameter. This change is compatible with earlier versions, but the `tower_auth_secret` parameter is now deprecated and will be removed in a future release.

[role="_additional-resources"]
.Additional resources

* For the most recent list of Technology Preview features, see link:https://access.redhat.com/articles/ansible-automation-platform-preview-features[Ansible Automation Platform - Preview Features].

* For information about execution node enhancements on OpenShift deployments, see link:https://docs.ansible.com/automation-controller/latest/html/administration/instances.html[Managing Capacity With Instances].
