:_mod-docs-content-type: REFERENCE

[[tech-preview]]
= Technology preview

== Ansible Lightspeed intelligent assistant integration with MCP

Ansible Lightspeed intelligent assistant integration with the Model Context Protocol (MCP) server is now available as a Technology Preview release. This integration enhances the user experience by delivering relevant, dynamically sourced data results to your queries. For information about how to access and use the Ansible Lightspeed intelligent assistant, see link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.6/html/installing_on_openshift_container_platform/deploying-chatbot-operator[Deploying the Ansible Lightspeed intelligent assistant on {OCPShort}].

== {AnsibleWorkspaces}

A supported {AnsibleWorkspaceSing} container image is now available as a Technology Preview release.
The container image is used with {DevSpacesFull} to create an in-browser instance of {VSCode} with the Ansible extension installed, so that you can use {ToolsName} to develop automation content.

For information about installing and using {AnsibleDevSpaces}, see {LinkAnsibleWorkspaces}.


== ansible-core 2.19
[NOTE]
====
Ansible Automation Platform 2.6 does not include ansible-core 2.19 by default, but it is compatible with 2.19. See link:https://access.redhat.com/support/policy/updates/ansible-automation-platform[Red Hat {PlatformNameShort} Life Cycle] for more information about compatibility.
====

This link:https://access.redhat.com/articles/7128367[technical preview] includes an overhaul of the templating system and a new feature labeled Data Tagging. These changes enable reporting of numerous problematic behaviors that went undetected in previous releases, with wide-ranging positive effects on security, performance, and user experience.

Backward compatibility has been preserved where practical, but some breaking changes were necessary. This guide describes some common problem scenarios with example content, error messages, and suggested solutions.

We recommend you test your playbooks and roles in a staging environment with this release to determine where you may need to make changes.

For further information see the link:https://docs.ansible.com/projects/ansible-core/devel/porting_guides/porting_guide_core_2.19.html#id3[Ansible Porting Guide].


== Execution environment builder

Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production.


* {SelfServiceShortStart} includes a guided user experience for creating {ExecEnvShort} definition files. Users can start from scratch or begin with Red Hat opinionated templates, then download the generated definition file or push to a new or existing Git repository.
