:_mod-docs-content-type: REFERENCE

[[tech-preview]]
= Technology preview


== Technology Preview

include::../snippets/technology-preview.adoc[]

// The following are Technology Preview features: 

// * Starting with {PlatformNameShort} 2.4, the Platform Resource Operator can be used to create the following resources in {ControllerName} by applying YAML to your OpenShift cluster:
// ** Inventories
// ** Projects
// ** Instance Groups
// ** Credentials
// ** Schedules
// ** Workflow Job Templates
// ** Launch Workflows

// You can now configure the Controller Access Token for each resource with the `connection_secret` parameter, rather than the `tower_auth_secret` parameter. This change is compatible with earlier versions, but the `tower_auth_secret` parameter is now deprecated and will be removed in a future release.

=== Ansible self-service automation portal version 2.1.1

==== Execution environment builder (Technology Preview)

* Self-service automation portal includes a guided user experience for creating {ExecEnvShort} definition files. Users can start from scratch or begin with Red Hat opinionated templates, then download the generated definition file or push to a new or existing Git repository.


=== Ansible-core 2.19

This link:https://access.redhat.com/articles/7128367[technical preview] includes an overhaul of the templating system and a new feature labeled Data Tagging. These changes enable reporting of numerous problematic behaviors that went undetected in previous releases, with wide-ranging positive effects on security, performance, and user experience.

Backward compatibility has been preserved where practical, but some breaking changes were necessary. This guide describes some common problem scenarios with example content, error messages, and suggested solutions.

We recommend you test your playbooks and roles in a staging environment with this release to determine where you may need to make changes.

For further information see the link:https://ansible.readthedocs.io/projects/ansible-core/devel/porting_guides/porting_guide_core_2.19.html#id3[Ansible Porting Guide].



=== {AnsibleWorkspaces}

A supported {AnsibleWorkspaceSing} container image is now available as a Technology Preview release.
The container image is used with {DevSpacesFull} to create an in-browser instance of {VSCode} with the Ansible extension installed, so that you can use {ToolsName} to develop automation content.

For information about installing and using {AnsibleDevSpaces}, see {LinkAnsibleWorkspaces}.


=== Availability of {AAPchatbot}

The {AAPchatbot} is now available on {PlatformNameShort} 2.5 on {OCP} as a Technology Preview release. It is an intuitive chat interface embedded within the {PlatformNameShort}, utilizing generative artificial intelligence (AI) to answer questions about the {PlatformNameShort}.

The chat experience in the {AAPchatbot} interacts with users in their natural language prompts in English, and utilizes large language models (LLMs) to generate quick, accurate, and personalized responses. These responses empower {PlatformNameShort} users to work more efficiently, thereby improving productivity and the overall quality of their work.

To access and use the {AAPchatbot}, you need:

* Installation of {PlatformNameShort} 2.5 on {OCP}.

* Deployment of an LLM served by Red Hat AI platforms.

For more information, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/installing_on_openshift_container_platform/index#deploying-chatbot-operator[Deploying the {AAPchatbot} on {OCPShort}] in _{TitleOperatorInstallation}_ guide.

[role="_additional-resources"]
.Additional resources

* For the most recent list of Technology Preview features, see link:https://access.redhat.com/articles/ansible-automation-platform-preview-features[{PlatformNameShort} - Preview Features].

* For information about execution node enhancements on OpenShift deployments, see link:https://docs.ansible.com/automation-controller/latest/html/administration/instances.html[Managing Capacity With Instances].


=== Managing AI infrastructure using {PlatformName}

It is now possible to access a practical approach to managing and automating AI infrastructure using {PlatformName}. Please refer to the link:https://access.redhat.com/articles/7117333[AI + Ansible Solution Guides].
