:_mod-docs-content-type: CONCEPT

// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="con-rhel-host-planning_{context}"]

= {RHEL} host planning

[role="_abstract"]

The security of {PlatformNameShort} relies in part on the configuration of the underlying {RHEL} servers. 

For this reason, the underlying {RHEL} hosts for each {PlatformNameShort} component must be installed and configured in accordance with the link:{BaseURL}/red_hat_enterprise_linux/8/html-single/security_hardening/index[Security hardening for {RHEL} 8] or link:{BaseURL}/red_hat_enterprise_linux/9/html-single/security_hardening/index[Security hardening for {RHEL} 9] (depending on which operating system is used). 
In addition, install and configure any security profile requirements (_Center for Internet Security_ (CIS), STIG, _Health Insurance Portability and Accountability Act_ (HIPAA), and so on) used by your organization.
This document recommends {RHEL} 9 for all new deployments. 
When using the container-based installation method, {RHEL} 9 is required.

//Note that applying certain security controls from the STIG or other security profiles may conflict with {PlatformNameShort} support requirements. 
//Some examples are listed in the xref:con-controller-stig-considerations_{context}[{ControllerNameStart} STIG considerations] section, although this is not an exhaustive list. To maintain a supported configuration, be sure to discuss any such conflicts with your security auditors so the {PlatformNameShort} requirements are understood and approved.
