:_mod-docs-content-type: CONCEPT

// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="con-rhel-host-planning_{context}"]

= {RHEL} host planning

[role="_abstract"]

The security of {PlatformNameShort} relies in part on the configuration of the underlying {RHEL} servers. 

For this reason, the underlying {RHEL} hosts for each {PlatformNameShort} component must be installed and configured in accordance with link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html-single/security_hardening/index[Security hardening for {RHEL} 8], link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/security_hardening/index[Security hardening for {RHEL} 9], or link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10/html-single/security_hardening/index[Security hardening for {RHEL} 10] depending on which operating system is used. 
Also apply any security profiles (_Center for Internet Security_ (CIS), DISA STIG for RHEL, _Health Insurance Portability and Accountability Act_ (HIPAA), and so on) required by your organization.
{RHEL} hardening and compliance requirements must be applied for all new before {PlatformNameShort} is installed. 

{RHEL} 9 or higher is recommended for all new deployments When using the container-based installation method, {RHEL} 9 or higher is required. 

The RPM installation method is no longer available for {RHEL} 10.

//Note that applying certain security controls from the STIG or other security profiles may conflict with {PlatformNameShort} support requirements. 
//Some examples are listed in the xref:con-controller-stig-considerations_{context}[{ControllerNameStart} STIG considerations] section, although this is not an exhaustive list. To maintain a supported configuration, be sure to discuss any such conflicts with your security auditors so the {PlatformNameShort} requirements are understood and approved.
