:_mod-docs-content-type: CONCEPT

// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="con-aap-additional-software_{context}"]

= {PlatformNameShort} and additional software

[role="_abstract"]

When installing the {PlatformNameShort} components on {RHEL} servers, the {RHEL} servers should be dedicated to that use alone. 
Additional server capabilities must not be installed in addition to {PlatformNameShort}, as this is an unsupported configuration and might affect the security and performance of the {PlatformNameShort} software.

Similarly, when {PlatformNameShort} is deployed on a {RHEL} host, it installs software such as the nginx web server, the Pulp software repository, and the PostgreSQL database server (unless a user-provided external database is used). 
This software should not be modified or used in a more generic fashion (for example, do not use nginx to serve additional website content or PostgreSQL to host additional databases) as this is an unsupported configuration and might affect the security and performance of {PlatformNameShort}. 
The configuration of this software is managed by the {PlatformNameShort} {Installer}, and any manual changes might be undone when performing upgrades.