:_mod-docs-content-type: PROCEDURE

[id="proc-ssh-auth-for-service-account"]

= Require SSH key authentication for service account

The service account must not be permitted to use password authentication with SSH connections to the managed node. 

Use the following procedure to configure the SSH daemon: 

.Procedure
. Create the file `/etc/sshd/sshd_config.d/60-ansible.conf`, and include the following content:
+
----
# sshd config applied to the ansible service account
Match User ansible
	PasswordAuthentication no
Match all
----
. Verify that the file uses the proper syntax:
+
`sudo sshd -t`
. Restart the SSH daemon
+
`sudo systemctl restart sshd.service`

Given that password authentication is prohibited, at least one SSH public key must be appended to the service account’s authorized_keys file (typically located at `/home/ansible/.ssh/authorized_keys`). 

These public keys must correspond with the private keys used to establish Machine credentials in {PlatformNameShort}, as these credentials facilitate connections to the RHEL managed nodes.

This guide advocates for a single service account for connections to managed RHEL nodes, but this does not mean using a single SSH key across all nodes is required. 
In larger organizations, individual teams managing RHEL servers can generate their own machine credentials within {PlatformNameShort}. 
Teams can then add the corresponding keys to the authorized keys file on their specific RHEL servers. This approach ensures consistent access to managed nodes organization-wide by using a common service account, while enabling each team to independently manage the credentials for their assigned nodes.
