:_mod-docs-content-type: PROCEDURE

// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="proc-namespaces_{context}"]

= User namespaces

[role="_abstract"]

A compliance profile might require that the kernel setting `user.max_user_namespaces` is set to "0", to prevent the launch of Linux containers. 
The DISA STIG, for example, specifically requires this control but only if Linux containers are not required. Because {PlatformNameShort} can be installed and operated in containers and also uses containers as part of its {ExecEnvShort} capability, Linux containers are required and this control must be disabled. 

To check the `user.max_user_namespaces` kernel setting, complete the following steps on each {PlatformNameShort} component in the installation inventory.

.Procedure

. Log in to your {ControllerName} at the command line.
. Run the command `sudo sysctl user.max_user_namespaces`.
. If the output indicates that the value is zero, look at the contents of the file `/etc/sysctl.conf` and all files under `/etc/sysctl.d/`, edit the file containing the `user.max_user_namespaces` setting, and set the value to "65535".
. To apply this new value, run the command `sudo sysctl -p <file>`, where `<file>` is the file just modified.
. Re-run the command `sudo sysctl user.max_user_namespaces` and verify that the value is now set to "65535".