:_mod-docs-content-type: PROCEDURE

// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="proc-sensitive-variables-install-inventory_{context}"]

= Secure sensitive variables with ansible vault

[role="_abstract"]
By securing sensitive values in the installation inventory file with Ansible Vault, both RPM-based and containerized {PlatformNameShort} installations benefit from improved security, password hygiene, and maintainability. 

.Procedure

. Navigate to the install directory by using the following command:
+
`cd /path/to/ansible-automation-platform-setup-bundle-2.5-<version>`
. Create a vault file by using the following command:
+
`ansible-vault create vault.yml`
. When prompted, enter a vault password
This password is required to access or modify the vault and is required for day-two operations such as backups and reconfigurations. 
+
[IMPORTANT]
====
Passwords with special characters must be in double quotes.
====
. Store the vault password securely, in accordance with your organizations security policy, for example, using a password manager or vault service.
. Add your sensitive variables to the vault and ensure they are not also defined in the inventory file.
+
To edit your vault file use:
+
`ansible-vault edit <file>`


