:_mod-docs-content-type: PROCEDURE

// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="proc-disaster-recovery-operations_{context}"]

= Disaster recovery and operational continuity

[role="_abstract"]

Taking regular backups of {PlatformNameShort} is a critical part of disaster recovery planning. Both backups and restores are performed using the {Installer}, so these actions should be performed from the dedicated installation host described earlier in this document. Refer to the link:{URLControllerAdminGuide}/controller-backup-and-restore[Back up and restore] section of the {TitleControllerAdminGuide} documentation for further details on how to perform these operations.

An important aspect of backups is that they contain a copy of the database as well as the secret key used to decrypt credentials stored in the database, so the backup files should be stored in a secure encrypted location. This means that access to endpoint credentials are protected properly. Access to backups should be limited only to {PlatformNameShort} administrators who have root shell access to {ControllerName} and the dedicated installation host.

The two main reasons an {PlatformNameShort} administrator needs to back up their {PlatformNameShort} environment are:

* To save a copy of the data from your {PlatformNameShort} environment, so you can restore it if needed.
* To use the backup to restore the environment into a different set of servers if you're creating a new {PlatformNameShort} cluster or preparing for an upgrade.

In all cases, the recommended and safest process is to always use the same versions of PostgreSQL and {PlatformNameShort} to back up and restore the environment.

Using some redundancy on the system is highly recommended. If the secrets system is down, the {ControllerName} cannot fetch the information and can fail in a way that would be recoverable once the service is restored. If you believe the SECRET_KEY {ControllerName} generated for you has been compromised and has to be regenerated, you can run a tool from the {Installer} that behaves much like the {ControllerName} backup and restore tool.

To generate a new secret key, perform the following steps: 

.Procedure
. Backup your {PlatformNameShort} database before you do anything else! See the link:{URLControllerAdminGuide}/controller-backup-and-restore[Back up and restore] section of the {TitleControllerAdminGuide} guide,
. Using the inventory from your install (same inventory with which you run backups/restores), run `setup.sh -k`.

.Result
A backup copy of the previous key is saved in `/etc/tower/`.
