:_mod-docs-content-type: PROCEDURE

// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="proc-implement-security-for-admin"]

= Implementing security control for system administrators

[role="_abstract"]
{ControllerNameStart} must generate the appropriate log records. 
{ControllerNameStart}'s web server must log all details related to user sessions in support of troubleshooting, debugging, and forensic analysis. 
Without a data logging feature, the organization loses an important auditing and analysis tool for event investigations.

Use the following procedure to implement the security control as a System Administrator for each {ControllerName} host:

.Procedure
. From the navigation panel, select {MenuSetSystem}. The System Settings page is displayed.
. Click btn:[Edit].
. Set the following:

* *Enable Activity Stream* = On
* *Enable Activity Stream for Inventory Sync* = On
* *Organization Admins Can Manage Users and Teams* = On
* *All Users Visible to Organization Admins* = On
. Click btn:[Save].





