:_mod-docs-content-type: PROCEDURE

[id="proc-rotate-database-secret-key"]

= Rotate the datatbase secret key

[role="_abstract"]
Using some redundancy on the system is highly recommended. If the secrets system is down, the {ControllerName} cannot fetch the information and can fail in a way that would be recoverable once the service is restored. 

If you believe the SECRET_KEY {ControllerName} generated for you has been compromised and has to be regenerated, you can run a tool from the {Installer} that behaves much like the {ControllerName} backup and restore tool.

To generate a new secret key, perform the following steps: 

.Procedure
. Backup your {PlatformNameShort} database. 
For more information on backing up your database, see link:{URLControllerAdminGuide}/controller-backup-and-restore[Back up and restore].
. Using the inventory from your install (same inventory with which you run backups/restores), run `setup.sh -k`.

.Result
A backup copy of the previous key is saved in `/etc/tower/`.
