:_mod-docs-content-type: REFERENCE

// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="ref-initial-configuration_{context}"]

= Recommended security practices for access controls

[role="_abstract"]

Granting access to certain parts of the system exposes security vulnerabilities. 
Apply the following practices to help secure access:

* Minimize access to system administrative accounts. 
There is a difference between the user interface (web interface) and access to the operating system that the {ControllerName} is running on. 
A system administrator or super user can access, edit, and disrupt any system application. 
Anyone with root access to {ControllerName} has the potential ability to decrypt those credentials, and so minimizing access to system administrative accounts is crucial for maintaining a secure system.
* Minimize local system access. {ControllerNameStart} should not require local user access except for administrative purposes. 
Non-administrator users should not have access to the {ControllerName} system.
* Enforce separation of duties. 
Different components of automation might need to access a system at different levels. 
Use different keys or credentials for each component so that the effect of any one key or credential vulnerability is minimized.
* Restrict {ControllerName} to the minimum set of users possible for low-level {ControllerName} configuration and disaster recovery only. In an {ControllerName} context, any {ControllerName} ‘system administrator’ or ‘superuser’ account can edit, change, and update any inventory or automation definition in {ControllerName}.