// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="ref-sensitive-variables-install-inventory_{context}"]

= Using an Ansible vault to secure sensitive variables

[role="_abstract"]

The installation inventory file for {PlatformNameShort }contains a number of sensitive variables, such as default administrative and database passwords. 
By default, these are stored in plain text. 
To enhance security and comply with organizational policies, encrypt these variables using an Ansible vault file. 

To create an Ansible vault file, go to the installer directory 

`cd /path/to/ansible-automation-platform-setup-bundle-2.5-<version>`

and create a vault file

`ansible-vault create vault.yml`

You are prompted for a password for the vault file. 
This password is required for day-two operations and backups. 
Store it securely, as per your organizations security policy, for example, using a password manager.

When you have set up and secured your Ansible vault, add your sensitive variables, for example:Add the sensitive variables to the vault, for example:

//Added containerized variables RPM/containerized:

----
admin_password/controller_admin_password: <secure_controller_password>
pg_password/controller_pg_password: <secure_db_password>
automationhub_admin_password/hub_admin_password: <secure_hub_password>
automationhub_pg_password/hub_pg_password: <secure_hub_db_password>
automationedacontroller_admin_password/eda_admin_password: <secure_eda_password>
automationedacontroller_pg_password/eda_pg_password: <secure_eda_db_password>
-/gateway_admin_password: <secure_gateway_password>
-/gateway_pg_password:<secure_gateway_db_password>
----

Ensure these variables are not duplicated in the plaintext installation inventory file.
