// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="ref-sensitive-variables-install-inventory_{context}"]

= Securing sensitive variables with ansible vault

The installation inventory file for {PlatformNameShort} contains a number of sensitive variables, such as default administrative and database passwords. 
By default, these are stored in plain text. 
To enhance security and comply with organizational policies, encrypt these variables using an Ansible vault file. 

To create an Ansible vault file, go to the installation directory 

`cd /path/to/ansible-automation-platform-setup-bundle-2.5-<version>`

and create a vault file

`ansible-vault create vault.yml`

You are prompted for a password for the vault file. 
This password is required for day-two operations and backups. 
Store it securely, in accordance with your organizations security policy, for example, using a password manager.

When you have set up and secured your Ansible vault, add your sensitive variables to the vault. Ensure they are not also defined in the inventory file.

You can edit the vault file using:

`ansible-vault edit <file>`

[NOTE]
====
Passwords with special characters must be in double quotes.
====
