// Module included in the following assemblies:
// downstream/assemblies/assembly-hardening-aap.adoc

[id="ref-sudo-nopasswd_{context}"]

= Sudo and NOPASSWD

A compliance profile might require that all users with sudo privileges must provide a password (that is, the `NOPASSWD` directive must not be used in a sudoers file). 
The {PlatformNameShort} installer runs many tasks as a privileged user, and by default expects to be able to elevate privileges without a password. 
To provide a password to the installer for elevating privileges, append the following options when launching the installer script: 

`./setup.sh <setup options> -- –-ask-become-pass`.

For the container-based installer: 

`ansible-playbook ansible.containerized_installer.install --ask-become-pass`

When the installer is run, you are prompted for the user's password to elevate privileges.

[NOTE]
====
Using the --ask-become-pass option also applies when running the installer for day-two operations such as backup and restore.
====


