name: Ansible Lint
on:
  push:
    branches:
      - main
      - aap-2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "bin/"
