
name: Build HTML preview artifact

on:
  push:
    branches:
      - 'main'
      - 'aap-2.2'
      - 'aap-2.3'
      - 'aap-clouds-latest'

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        repository: ansible/aap-docs
        ref: main
    
    - name: config docs-bot
      run: |
        git config --global user.email "docs-bot@redhat.com"
        git config --global user.name "docs-bot"

    - uses: oraNod/asciidocjs-action@v1.3
      with:
        docs_path: titles/**/
    
    - name: commit
      run: |
        git add titles/**/*.html
        git diff-index --quiet HEAD || git commit -m "Build HTML preview"
    
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DOCS_BOT_PAT }}
        branch: main