ifdef::context[:parent-context: {context}]

[id="assembly-gcp-release-notes-24"]

= Release notes for Ansible on Clouds 2.4

:context: release-notes-24

This release includes a number of enhancements, additions, and fixes that have been implemented for {AAPonGCP}.

include::topics/ref-gcp-release-notes-2-4-20231024-00.adoc[leveloffset=+1]
include::topics/ref-gcp-release-notes-2-4-20230630-00.adoc[leveloffset=+1]
include::topics/ref-gcp-release-notes-2-3-20230221-00.adoc[leveloffset=+1]
include::topics/ref-gcp-release-notes-2-2-20230215-00.adoc[leveloffset=+1]

[NOTE]
====
Automation Mesh and Event Driven Automation are not yet supported by the self-managed Ansible on Cloud offerings at this time.
====

[discrete]
== Enhancements

//The release version {ImageRef} of {AAPonGCP} includes the following enhancements:

* Support for {PlatformNameShort} 2.4 has been added.
* Added internal encryption to the web servers.
** Addition of custom certificates is now supported.
* Support has been added for custom tagging and labelling.
** Support has been added to GCP to add or remove tag support for resources owned by the deployment.
* {AAPonGCP} now has operational playbooks to add and remove extension nodes.
* There are improvements to backup and restore functionality.
** Support has been added for taking multiple backups.
** An operational playbook has been added to list available backups.
** An operational playbook has been added to delete a selected backup.
** The capability to restore an existing VPC has been added.
* Operational functionality to check the current version has been added.
** Operational playbooks now check to ensure that the {PlatformNameShort} environment they are operating upon is at the same version before beginning their operation.


[discrete]
== Deprecated and removed features

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {PlatformNameShort} and continues to be supported; however, it will be removed in a future release of this product and is not recommended for new deployments.
The following is a list of major functionality deprecated and removed within {PlatformNameShort} 2.4:

* On-premise component Automation Services Catalog is now removed from {PlatformNameShort} 2.4 onwards.
* With the {PlatformNameShort} 2.4 release, the Execution Environment container image for Ansible 2.9 (ee-29-rhel-8) is no longer loaded into the {ControllerName} configuration by default.
* The process of deploying the application using a new VPC has been deprecated, and the functionality will be removed from {AAPonGCP} in a future release.

[discrete]
== Additional Release Notes related to Ansible Automation Platform

* Check out latest features in link:https://access.redhat.com/login?redirectTo=https%3A%2F%2Faccess.redhat.com%2Fdocumentation%2Fen-us%2Fred_hat_enterprise_linux%2F9[Red Hat Enterprise Linux 9]
* Read more about latest link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_release_notes/index?extIdCarryOver=true&intcmp=7013a0000026H45AAE&sc_cid=7013a000003SeN0AAK[Ansible Automation Platform features]
