ifdef::context[:parent-context: {context}]

[id="assembly-intro-to-aap-on-aws"]
= Introduction to {PlatformNameShort} on {AWS}

:context: aap-aws-intro

{PlatformName} on {AWS} is an offering that you can deploy from the AWS Marketplace portal. 
{PlatformNameShort} on {AWS} provides access to a library of Ansible content collections, and it is integrated with key AWS services, so you can start automating the deployment, configuration, and management of infrastructure and applications quickly.

To use this guide, you must have a working knowledge of the following aspects of Amazon Web Services:

* Deploying solutions from the AWS Marketplace
* _Elastic Compute Cloud_ (EC2) instances
* _Elastic Block Store_ (EBS) volumes
* _Elastic File Storage_ (EFS)
* AWS _Virtual Private Clouds_ (VPCs)
** Subnets
** Route Tables
** Security Groups
** Load Balancers
* Network Design
* Hub-and-spoke networking designs
* VPC Peering
* _Class Inter-Domain Routing_ (CIDR) blocks
* Transit routing
* AWS Lambda
* AWS CloudWatch
* SSH

include::topics/con-aws-application-architecture.adoc[leveloffset+=1]