ifdef::context[:parent-context: {context}]

[id="assembly-gcp-upgrade"]

:context: gcp-upgrade

= Upgrading your deployment

You can upgrade your existing {AAPonGCP} deployment to the newer version. 
The upgrade process covers upgrading of {HubName} and {ControllerName}. 
The upgrade process takes roughly the same amount of time as a {AAPonGCP} deployment install. 

Use the following procedure to ensure a smooth upgrade process.

[NOTE]
=====
{AAPonGCP} supports sequential upgrades. 
All upgrades should be no more than one major version behind the version you are currently upgrading to. 
For example, to upgrade to {PlatformNameShort} from {GCPMarket} to 2.3.20230221-00, you must be on version 2.2.20230215-00.
=====

.Prerequisites
* Docker must be installed to run the upgrade playbook.
* The upgrade process requires several volumes to be mounted. 
Prepare a fresh directory to be used for this process.

The following procedures form the upgrade process:

. Backup your {PlatformNameShort} 2.2 stack.
.. Pull the `ansible-on-clouds-ops` 2.2 container image
.. Prepare the environment
.. Run the `ansible-on-clouds-ops` 2.2 container to backup the stack

. Upgrade {PlatformNameShort}.
.. Pull the `ansible-on-clouds-ops` 2.3 container image
.. Generate data files by running the `ansible-on-clouds-ops` container
.. Update the data file
.. Run the `ansible-on-clouds-ops` 2.3 container to upgrade your {AAPonGCP} deployment

. (Optional) Restore the stack from backup.
.. Pull the ansible-on-clouds-ops 2.2 container image
.. Prepare the environment
.. Run the `ansible-on-clouds-ops` 2.2 container to restore the stack

:concept: backup
include::topics/con-gcp-upgrade-backup-process.adoc[leveloffset=+1]
:concept: upgrade
include::topics/con-gcp-upgrade-upgrading.adoc[leveloffset=+1]
:concept: restore
include::topics/con-gcp-upgrade-restore-from-stack.adoc[leveloffset=+1]
