ifdef::context[:parent-context: {context}]

[id="assembly-aap-aws-backup-and-restore"]
= Backup and Restore Process for {AAPonAWS}

:context: aap-aws-backup-restore

To backup and restore your {PlatformNameShort} deployment, it is vital to ensure automatic backups have been set for EFS and that these backups are accessible for restoration.

When you create an {PlatformNameShort} deployment, automatic Amazon _Elastic File System_ (EFS) backups are set by default. 
However, it is prudent to check that those backups can be restored before a disaster scenario.

In addition, it is also extremely important that regular manual snapshots of the Amazon Relational Database Service (RDS) are taken to ensure a deployment can be restored as close as possible to its previous working state. 

//Context set before these topics as there's a shared procedure. Applying a context to that procedure
//makes it possible to resuse the procedure within an assembly.
:context: backup
include::topics/con-aap-aws-backup-process.adoc[leveloffset=+1]
:context: restore
include::topics/con-aap-aws-restore-process.adoc[leveloffset=+1]



