:_mod-docs-content-type: CONCEPT

[id="con-gcp-customize-monitoring-logging"]

= Customizing monitoring and logging

Metrics are provided by link:https://docs.ansible.com/automation-controller/latest/html/administration/metrics.html[Ansible], link:https://github.com/containers/prometheus-podman-exporter[Podman] and link:https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent[Google Ops Agent].
The Google Ops Agent and Podman are installed on {ControllerName} and {HubName} VM instances, however Ansible metrics are only installed on {HubName} instances.

A configurable process (collector) runs on each {ControllerName} VM instance and {HubName} VM instance to export the collected Ansible and Podman metrics to {GCP} Monitoring.
As the Google Ops Agent is part of the Google Cloud solution, it has its own configuration file.

The Google Ops Agent is also responsible for the logging configuration.

The service APIs `monitoring.googleapis.com` and `logging.googleapis.com` must be respectively enabled for the monitoring and logging capabilities.

.Configuration

Configuration files are located on a disk shared by each {ControllerName} and {HubName}.
Modify the file `/aap/bootstrap/config_file_templates/<controller|hub>/monitoring.yml` to configure all exporters and agents.

include::ref-gcp-ansible-podman-config.adoc[leveloffset=+1]
include::ref-gcp-configure-google-cloud-ops-agent.adoc[leveloffset=+1]
