:_mod-docs-content-type: PROCEDURE

[id="proc-aws-deploy-new-vpc"]

= Deploying an application with a new VPC

[NOTE]
====
The process of deploying the application using a new VPC has been deprecated, and the functionality will be removed from {AAPonAWS} in a future release.
====

[NOTE]
====
The following procedure assumes that you have a marketplace offer. 
The instructions are a continuation from xref:proc-aws-marketplace[{Market}].
Complete the procedure in that section before continuing with this section.
====

This procedure creates a new VPC network and deploys the application in the created VPC.

.Procedure
. For Step 1, on the *Create stack* page, click btn:[Next].
. For Step 2, on the *Specify stack details* page
.. In the *Stack name* field, enter a unique stack name.
.. In the *EC2 KeyPair* field, select your previously created EC2 keypair.
.. In the *Select VPC* field, select *New*.
.. In the *New Network Configuration* section, fill the following fields
** In the *VPC CIDR Range*, enter the CIDR range to use for the new VPC. Example: 192.168.0.0/16
** In the *Public Subnet 1 CIDR Range*, enter the CIDR range to use for the first public subnet, for example, 192.168.0.0/24
** In the *Public Subnet 2 CIDR Range*, enter the CIDR range to use for the second public subnet, for example, 192.168.1.0/24
** In the *Private Subnet 1 CIDR Range*, enter the CIDR range to use for the first private subnet, for example, 192.168.2.0/24
** In the *Private Subnet 2 CIDR Range*, enter the CIDR range to use for the second private subnet, for example, 192.168.3.0/24
+
[IMPORTANT]
====
It is crucial to ensure the CIDR ranges provided for your subnets are within your VPC CIDR range and do not overlap with each other to avoid CIDR collisions.
 
You can look at the default subnet CIDR ranges as a point of reference.
====
+
.. Ignore the fields under the *Existing network configuration* section.
. Click btn:[Next] to move to Step 3.
. For Step 3, on the *Configure stack options* page, no changes are necessary. 
* All configurations are optional or have the correct default values.
. Click btn:[Next] to move to Step 4.
. For Step 4, on the *Review* page, scroll to the bottom. 
* In the *Capabilities* section, check to acknowledge that CloudFormation can create IAM resources.
. Click btn:[Submit].
. The application begins provisioning.
* It can take some time for the infrastructure and application to fully provision.

If you want to modify your CIDR ranges post deployment, your current deployment must be deleted, then follow the instructions in xref:proc-aws-deploy-existing-vpc[Deploying an application with an existing VPC].