:_mod-docs-content-type: PROCEDURE

[id="proc-aws-generate-backup-data-file"]

= Generating the backup data file

The following commands create a directory, and populate it with an empty data template that, when completed, will be used during the backup.

.Procedure
. Create a folder to hold the configuration
+
[literal, options="nowrap" subs="+attributes"]
----
$ mkdir command_generator_data
----
. Populate the `command_generator_data` folder with the configuration file template.
This creates the `backup.yml` file within the `command-generator_data` directory.
+
[NOTE]
====
On Linux, any file or directory created by the command generator is owned by `root:root` by default.
To change the ownership of the files and directories, you can run the `sudo chmod` command after the files are created. For more information, read xref:con-tech-note-linux-files-owned-by-root[Command generator - Linux files owned by root].
====
+
[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE \
  command_generator_vars aws_backup_stack \
  --output-data-file /data/backup.yml
----

. After running these commands, a `$(pwd)/command_generator_data/backup.yml` template file is created.
This template file resembles the following:
+
[literal, options="nowrap" subs="+attributes"]
----
aws_backup_stack:
  ansible_config_path:
  cloud_credentials_path:
  deployment_name:
  extra_vars:
    aws_backup_iam_role_arn:
    aws_backup_vault_name: Default
    aws_region:
    aws_s3_bucket:
    aws_ssm_bucket_name:
    backup_prefix: aoc-backup
----
