:_mod-docs-content-type: PROCEDURE

[id="proc-gcp-set-monitoring-logging-yml"]

= Updating the data file

If you do not require a parameter, remove that parameter from the configuration file.

.Procedure
* Edit the `command_generator_data/logging-monitoring.yml` file and set the following parameters:

* `ansible_config_path` is used by default as the standard configuration for the `ansible-on-cloud offering` but if you have extra requirements in your environment you can specify your own. 
* `cloud_credentials_path` is the absolute path toward your credentials. 
This must be an absolute path.
* `deployment_name` is the name of the deployment.
* `components` (Optional) the type of component on which you want to carry out the setup. 
The default is [ “controller”, “hub” ] which means that the logging monitoring will be enabled on both {controllerName} and {HubName}.
* `monitoring_enabled` (Optional) is set to `true` to enable the monitoring, `false` otherwise. Default = `false`.
* `logging_enabled` (Optional) is set to `true` to enable the logging, `false` otherwise. Default = `false`.
* `default_collector_interval` (Optional) is the frequency at which the monitoring data must be sent to Google Cloud. 
Default = 59s.
+
[NOTE]
==== 
The Google cost of this service depends on that periodicity and so the higher the value of the collector interval, the less it will cost.
====
+ 
Do not set values less than 59 seconds.
+
[NOTE]
====
If monitoring and logging is disabled, the value of 'default_collector_interval' is automatically set to `0`.
====

After populating the data file, it should resemble the following.

The following values are provided as examples:

[NOTE]
====
The optional parameters described in the section are ommitted in the data file example below. The playbook uses the default value for any optional parameter that is ommitted from the data file. If you want to override a default value for an optional parameter, then it must be included in the data file and assigned a value.
====

[literal, options="nowrap" subs="+attributes"]
----
gcp_setup_logging_monitoring:
  cloud_credentials_path: ~/secrets/GCP-secrets.json
  deployment_name: AnsibleAutomationPlatform
  extra_vars:
----
