:_mod-docs-content-type: PROCEDURE

[id="proc-aws-generate-upgrade-data-file_{context}"]

= Generating the data file

The commands in this section create a directory and populate it with an empty data template that, when populated, is used during the upgrade.

.Procedure

. Run the following commands to generate the required data file.
+
[literal, options="nowrap" subs="+attributes"]
----
# Create a folder to hold the configuration files
$ mkdir command_generator_data
----
. Populate the `command_generator_data` folder with the configuration file template.
+
[NOTE]
====
On Linux, any file or directory created by the command generator is owned by `root:root` by default.
To change the ownership of the files and directories, you can run the `sudo chmod` command after the files are created. For more information, read xref:con-tech-note-linux-files-owned-by-root[Command generator - Linux files owned by root].
====
+
[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE \
command_generator_vars aws_upgrade \
--output-data-file /data/extra_vars.yml
----

. After running these commands, a `command_generator_data/extra_vars.yml` template file is created.
This template file resembles the following:
+
[literal, options="nowrap" subs="+attributes"]
----
aws_upgrade:
  ansible_config_path:
  cloud_credentials_path:
  deployment_name:
  extra_vars:
    aws_backup_taken:
    aws_region:
    aws_ssm_bucket_name:
    seller_name:
----
