:_mod-docs-content-type: PROCEDURE

[id="proc-aws-marketplace"]

= {Market}

.Public Offer
{AAPonAWS} can be obtained directly from the {Market}.
Follow these steps to purchase and deploy the public offer.

.Procedure

. In the AWS Console, navigate to menu:AWS Marketplace Subscriptions[].
. In the navigation bar, click btn:[Discover Products].

. Click the listing for *{PlatformName} 2 - Up to 100 Managed Nodes*.
. Click btn:[Continue to Subscribe].
. Click btn:[Continue to Configuration].
. Select the appropriate fulfillment options.
* Note that some selectors can have only one option.
. In the *Fulfillment option* field, ensure *Ansible Platform CloudFormations Topology* is selected.
. In the *Software version* field, select the latest available version from the list.
. In the *Region* field, select the region with your EC2 key pair. 
The CloudFormation stack deploys in the same region.
. Click btn:[Continue to Launch].
. In the *Choose Action* field, select *Launch CloudFormation*.
. Click btn:[Launch].
* This opens the CloudFormation create stack page, which is already preconfigured.
. Next, follow the instructions in xref:proc-aws-application-deploy[Application deployment] for detailed guidance about how to configure the deployment using this form.

.Private Offer
If you have worked with Red Hat Sales to enable a private offer of {AAPonAWS}, follow these steps to accept your offer and deploy the solution.

.Procedure
. Visit your Private Offer with the URL link provided by your Red Hat Sales representative.
. Click btn:[Accept Terms] to subscribe to the AMI Private Offer named {AAPonAWS}.
. After accepting the offer terms, click btn:[Continue to Configuration].
. Select the appropriate fulfillment options.
* Note that some selectors can have only one option.
. In the *Fulfillment option* field, ensure *Ansible Platform CloudFormations Topology* is selected.
. In the *Software version* field, select the latest available version from the list.
. In the *Region* field, select the region with your EC2 key pair. 
The CloudFormation stack deploys in the same region.
. Click btn:[Continue to Launch].
. In the *Choose Action* field, select *Launch CloudFormation*.
. Click btn:[Launch].
* This opens the CloudFormation create stack page, which is already preconfigured.
. Next, follow the instructions in xref:proc-aws-application-deploy[Application deployment] for detailed guidance about how to configure the deployment using this form.

[NOTE]
====
If you are accepting terms for the {PlatformNameShort} foundation offer, then accept the discount rate for three virtual machines.  All {PlatformNameShort} foundation deployments use three VMs.  

If you are accepting terms for {PlatformNameShort} extension nodes, then assign the number of virtual machines arranged with your Red Hat Sales representative.  The number of VMs will directly correlate to the number of licensed managed active nodes that you have purchased.

After subscribing, the offer is also listed in your {Market} Subscriptions. 
====
