:_mod-docs-content-type: PROCEDURE

[id="proc-gcp-deploying-extension-nodes"]

= Deploying an extension node

You configure extension nodes after you have purchased and launched an extension from the public or private offer.

.Procedure
. In the *Deployment name* field, enter a sufficiently short name as described in xref:con-gcp-application-deploy[Application deployment].
. For the *Service Account*, select the service account used with your {PlatformName} with up to 100 Managed Nodes deployment.
. In the *Region* field, select the region where you want the application deployed.
. In the *Zone* field, select a zone in the *Region* you selected when deploying your foundational offer. 
This field is only used to filter the Network list.
. In the *Main Deployment Name* field, enter the foundation deployment name for which you are deploying an extension.
+
[NOTE]
====
*Main Deployment Name* is a required field. 
====
+
. In the *Networking* section, expand the default option. 
. In the *Network* field, select the existing foundation network ending with `-aap-net`. 
. In the *Subnetwork* field, select the existing foundation subnetwork ending with `-aap-subnet`. 
+
[IMPORTANT]
====
Do not select the subnet ending with `-aap-proxy-subnet`.
====
+
[NOTE]
====
In case of an error stating `Make sure all fields are correct to continue` and `You must select a Network`. Reselect the values from the menu and click btn:[Done].
====
+
. Ensure *Extend {PlatformNameShort} deployment in selected VPC* is checked.
. Click btn:[DEPLOY]. 
. The Deployment Manager displays the running deployment.

The extension begins provisioning.  

It can take some time for the infrastructure and extension to fully provision.