:_mod-docs-content-type: PROCEDURE

[id="proc-aap-pull-command-container-image"]

= Pulling the ansible-on-clouds-ops container image

Pull the Docker image for the Ansible on Clouds operational container with the same tag version as your deployment. If you are unsure of the version you have deployed, see xref:ref-aap-using-playbooks[Command Generator] and playbook *gcp_get_aoc_version* for more information on finding the currention of Ansible on Clouds deployment.

[NOTE]
====
Before Pulling the docker image, ensure you are logged in to {Registry} using docker. Use the following command to login to {Registry}.

[literal, options="nowrap" subs="+attributes"]
----
$ docker login {Registry}
----
For more information about registry login, see link:https://access.redhat.com/RegistryAuthentication[Registry Authentication]
====

For example, if your foundation deployment version is {ImageRef}-00, you must pull the operational image with tag {ImageRef}.

Use the following commands:

[literal, options="nowrap" subs="+attributes"]
----
$ export IMAGE={Registry}/ansible-on-clouds/{OpImageName}
$ docker pull $IMAGE --platform=linux/amd64
----

[NOTE]
====
If your foundation deployment version is not {ImageRef}-00, refer to the tables on the link:https://access.redhat.com/documentation/en-us/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_from_gcp_release_notes/assembly-gcp-release-notes-24[Released versions] page for a matching deployment version, in the column *Ansible on Clouds version*, and find the corresponding operational image to use, in the column *Ansible-on-clouds-ops container image*, for the IMAGE environment variable.
====
