:_mod-docs-content-type: PROCEDURE

[id="proc-aws-deploy-existing-vpc"]

= Deploying an application with an existing VPC

[NOTE]
====
The following procedure assumes that you have a marketplace offer. 
The instructions are a continuation from xref:proc-aws-marketplace[{Market}].
Complete the procedure in that section before continuing with this section.
====

The following procedure uses an existing VPC network to deploy an application.

.Procedure
. For Step 1, on the *Create stack* page, click btn:[Next].
. For Step 2, on the *Specify stack details* page
.. In the *Stack name* field, enter a unique stack name.
.. In the *EC2 KeyPair* field, select your previously created EC2 keypair.
.. In the *Select VPC* field, select *Existing*.
.. Ignore the fields under the *New network configuration* section.
.. In the *Existing network configuration* section, fill the following fields
** In the *Which VPC ID should this be deployed to?* field, enter the VpcId of your existing Virtual Private Cloud (VPC), for example, vpc-01234567890abcdef
** In the *Existing VPC CIDR Range*, enter the CIDR Range of your existing Virtual Private Cloud (VPC), for example, 192.168.0.0/16
** In the *Existing Private Subnet 1 ID*, enter the ID of your first existing private subnet, for example, subnet-077dd9969c32371f7
** In the *Existing Private Subnet 2 ID*, enter the ID of your second existing private subnet, for example, subnet-077dd9969c32371f7
+
Note that copying and pasting these from the AWS console introduces hidden characters, and can cause the entries to fail.
+
. Click btn:[Next] to move to Step 3.
. For Step 3, on the *Configure stack options* page, no changes are necessary.
* All configurations are optional or have the correct default values.
. Click btn:[Next] to move to Step 4.
. For Step 4, on the *Review* page, scroll to the bottom. 
* In the *Capabilities* section, check to acknowledge that CloudFormation can create IAM resources.
. Click btn:[Submit].
. The application begins provisioning.
* It can take some time for the infrastructure and application to fully provision.
