:_mod-docs-content-type: PROCEDURE

[id="proc-gcp-secure-communication-SSL"]

= Securing internal communication with SSL

{AAPonGCP} is deployed with two _internal_ application load balancers, one each in front of the hub and controller instances. 
These internal load balancers must be configured with SSL certificates after deployment completes.

[NOTE]
====
Securing traffic through these internal load balancers is different than securing traffic through external load balancers in previous steps. 
This process ensures HTTP traffic is encrypted even when the traffic is localized to private GCP VPCs.
The same procedure can be followed for both the {ControllerName} and {HubName} load balancers.
====

To modify both the {ControllerName} and {HubName} load balancers, which have the name format `<DEPLOYMENT_NAME>-aap-<cntrlr/hub>-int-lb`.

.Procedure
. Generate the {ControllerName} or {HubName} certificate with the following command:
+
[literal, options="nowrap" subs="+attributes"]
----
$ openssl req -x509 -nodes -newkey rsa:2048 -keyout key.pem -out cert.pem -sha256 -days 365
----
. In the GCP console, navigate to the link:https://console.cloud.google.com/net-services/loadbalancing/list/loadBalancers[*Load Balancing*] page.
. In the search bar, enter the name of your deployment to filter down to your load balancers.
. Click `<DEPLOYMENT_NAME>-aap-<cntrlr/hub>-int-lb`.
. Click btn:[Edit]. 
. Click btn:[Frontend configuration].
. Click btn:[ADD FRONTEND IP AND PORT].
Use the following values:
.. *Protocol*: HTTPS (includes HTTP/2).
.. *Subnetwork*: Select the available aap-subnet.
.. *Port*: 443
.. *IP Address*: `<DEPLOYMENT_NAME>-aap<cntrlr/hub>-intl-lb-ip`
. If you have already added your certificate, select it.
.. If you have not added your certificate, click btn:[CREATE A NEW CERTIFICATE].
.. Provide a name for your certificate.
.. Using your previously generated certificate, copy `cert.pem` contents and paste it under *Certificate*.
.. Using your previously generated certificate key, copy `key.pem` contents and paste it under *Private Key*.
.. Click btn:[Create].
. Click btn:[Done].
. Optional: To delete the HTTP Frontend configuration.
.. Open the Load balancer instance.
.. Click btn:[Frontend Configuration]
The configurations appear on the left side of the UI.
.. Scroll to the configuration you want to delete.
.. Click the trashcan icon to delete the configuration.
. Click btn:[Update], and confirm the update.
