:_mod-docs-content-type: PROCEDURE

[id="proc-gcp-pull-backup-container-image"]

= Pulling the ansible-on-clouds-ops 2.2 container image

.Procedure
* Pull the `ansible-on-clouds-ops 2.2` container image with the same tag version as the foundation deployment.

+
[NOTE]
====
Before pulling the docker image, ensure you are logged in to {Registry} using docker. Use the following command to login to {Registry}.

[literal, options="nowrap" subs="+attributes"]
----
$ docker login {Registry}
----
For more information about registry login, see link:https://access.redhat.com/RegistryAuthentication[Registry Authentication]
====
+
[literal, options="nowrap" subs="+attributes"]
----
$ export IMAGE={Registry}/ansible-on-clouds/ansible-on-clouds-ops-rhel8:2.2.20230215
$ docker pull $IMAGE --platform=linux/amd64
----

For EMEA regions (Europe, Middle East, Africa) run the following command instead:

[literal, options="nowrap" subs="+attributes"]
----
$ export IMAGE={Registry}/ansible-on-clouds/ansible-on-clouds-ops-emea-rhel8:2.2.20230215
$ docker pull $IMAGE --platform=linux/amd64
----

[NOTE]
====
If your foundation deployment version is not {ImageRef}-00, refer to the tables on the link:{BaseURL}/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_from_gcp_release_notes/assembly-gcp-release-notes-24[Released versions] page for a matching deployment version, in the column *Ansible on Clouds version*, and find the corresponding operational image to use, in the column *Ansible-on-clouds-ops container image*, for the IMAGE environment variable.
====
