:_mod-docs-content-type: PROCEDURE

[id="proc-gcp-application-deploy"]

= Application deployment

Now that you have launched the public or private offer, you can begin configuration before deploying the application.

[IMPORTANT]
====
A temporary yet necessary constraint has been placed on the length of deployment names.
This is due to GCP's naming scheme for internal components that make up an {PlatformNameShort} deployment.
Component names based on this naming scheme can get too long and often break naming constraints imposed by other services, creating deployment errors.

The length of the name of your deployment, plus the length of your GCP project name must be less than 35 characters and the length of the deployment name must be less than 30 characters.

The calculation below will help you find the maximum length of the name of an {PlatformNameShort} deployment in your project.

length of deployment name < = (minimum between 30 and 35) - length(gcp project name)
====

.Procedure
. In the *Deployment* page, click the btn:[Service Usage API] link below the *Confirm Service Usage API is enabled* checkbox.
. In the *API/Service Details* tab, ensure that the API is enabled, then return to the *Deployment* page.
. Check the *Confirm Service Usage API is enabled* checkbox.
. Select or create a *Service Account*.
+
For further information see xref:con-gcp-service-account[Your service account].

. In the *Region* field, select the region where you want the application deployed.
. In the *Zone* field, select the zone where you want the Filestore deployed.
The zone must be in the *Region* you selected.
. In the *Observability* section, you can enable logging and metrics to be sent to Cloud Logging and Cloud Monitoring.
See link:https://cloud.google.com/stackdriver/pricing[Operations Suite Pricing] for the financial cost of enabling these services.
See xref:assembly-gcp-monitoring-logging[Monitoring and logging] for more information on configuring this feature.
. The *Networking* section provides defaults for all of the network ranges used in the deployment.
If you want to modify these values, see xref:ref-gcp-networking-options[Networking Options]
. Click btn:[DEPLOY].
+
The Deployment Manager displays the running deployment.


The application begins provisioning.
It can take some time for the infrastructure and application to fully provision.

[NOTE]
====
You will see a warning on the deployment

[options="nowrap" subs="+quotes,attributes"]
----
This deployment has resources from the Runtime Configurator service, which is in Beta.
----

This warning is expected and is not a cause for concern.
====


To retrieve the administration password:

.Procedure
. Select the main menu from the top left.
. Select *Security*. If you do not see *Security*, select *View All Products*.
. Select *Secret Manager*.
. Filter with the name of the deployment.
The secret name format is `<DeploymentName>-aap-admin`.
. Click on the secret name of the deployment
. Click the btn:[More Actions] icon *{MoreActionsIcon}* on the line of the deployment.
. Select *View secret value*.
The administration password is displayed.
