:_mod-docs-content-type: PROCEDURE

[id="proc-aws-run-restore-playbook"]

= Running the restore playbook

The following procedure runs the restore playbook as a container.

.Procedure
. To run the restore, run the command generator.
+
[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE command_generator aws_restore_stack --data-file /data/restore.yml
----
+
This generates the restore CLI command  
+
[literal, options="nowrap" subs="+attributes"]
----
----------------------------------------------
docker run --rm --env PLATFORM=AWS -v ~/.aws/credentials:/home/runner/.aws/credentials:ro --env ANSIBLE_CONFIG=../aws-ansible.cfg \
--env DEPLOYMENT_NAME=AnsibleAutomationPlatform --env GENERATE_INVENTORY=true --env CHECK_GENERATED_INVENTORY=false  \
$IMAGE redhat.ansible_on_clouds.aws_restore_stack -e 'aws_foundation_stack_name=AnsibleAutomationPlatform \
aws_backup_name=ansible-automation-platform-bucket-20230706T163309 aws_region=us-east-1 \
aws_s3_bucket=ansible-automation-platform-bucket aws_ssm_bucket_name=aap-ssm-bucket'
===============================================
----
. Run the generated command to trigger the restore.
+
[literal, options="nowrap" subs="+attributes"]
----
$ docker run --rm --env PLATFORM=AWS -v ~/.aws/credentials:/home/runner/.aws/credentials:ro --env ANSIBLE_CONFIG=../aws-ansible.cfg \
--env DEPLOYMENT_NAME=AnsibleAutomationPlatform --env GENERATE_INVENTORY=true --env CHECK_GENERATED_INVENTORY=false  \
$IMAGE redhat.ansible_on_clouds.aws_restore_stack -e 'aws_foundation_stack_name=AnsibleAutomationPlatform \
aws_backup_name=ansible-automation-platform-bucket-20230706T163309 aws_region=us-east-1 \
aws_s3_bucket=ansible-automation-platform-bucket aws_ssm_bucket_name=aap-ssm-bucket'

----
. The playbook can take some time to create a restored deployment.
When you have run the playbook successfully, a restored deployment is available in AWS CloudFormation matching the name provided for it in the `restore.yml` file.

[NOTE]
====
A restored deployment contains the same VPC networking setup as the original backed up deployment. If a backed up deployment was deployed within an existing VPC, its restored deployment is also deployed into that VPC. If a backed up deployment was deployed with a new VPC, its restored deployment is also deployed with a new VPC.  
====
