:_mod-docs-content-type: PROCEDURE

= Pulling the ansible-on-clouds-ops container image

.Procedure
* Pull the docker image for the `ansible-on-clouds-ops` container with the same tag as the foundation deployment.
If you are unsure of the version you have deployed, see xref:ref-aap-using-playbooks[Command Generator] and playbook *gcp_get_aoc_version* for more information on finding the current version of Ansible on Clouds deployment.
+
[NOTE]
====
Before pulling the docker image, ensure you are logged in to {Registry} using docker. Use the following command to login to {Registry}. 

[literal, options="nowrap" subs="+attributes"]
----
$ docker login {Registry}
----
For more information about registry login, see link:https://access.redhat.com/RegistryAuthentication[Registry Authentication]
====
+
[literal, options="nowrap" subs="+attributes"]
----
$ export IMAGE={Registry}/ansible-on-clouds/{OpImageName}
$ docker pull $IMAGE --platform=linux/amd64
----

[NOTE]
====
If your foundation deployment version is not {ImageRef}-00, refer to the tables on the link:{BaseURL}/ansible_on_clouds/2.x/html/red_hat_ansible_automation_platform_from_gcp_release_notes/assembly-gcp-release-notes-24[Released versions] page for a matching deployment version, in the *Ansible on Clouds version* column. Find the corresponding operational image to use, in the *Ansible-on-clouds-ops container image* column, for the IMAGE environment variable.
====
