:_mod-docs-content-type: PROCEDURE

[id="proc-aws-generate-remove-data-files"]

= Generating data files by running the ansible-on-clouds-ops container

The following commands generate the required data file.
These commands create a directory, and  an empty data template that, when populated, is used during the upgrade.

.Procedure
. Create a folder to hold the configuration files.
+
[options="nowrap" subs="+attributes"]
----
$ mkdir command_generator_data
----
. Populate the `$(pwd)/command_generator_data` folder with the configuration file template.
+
[NOTE]
====
On Linux, any file or directory created by the command generator is owned by `root:root` by default.
To change the ownership of the files and directories, you can run the `sudo chmod` command after the files are created. For more information, read xref:con-tech-note-linux-files-owned-by-root[Command generator - Linux files owned by root].
====
+
[options="nowrap" subs="+attributes"]
----
$ docker run --rm -v $(pwd)/command_generator_data:/data $IMAGE \
command_generator_vars aws_remove_extension_nodes \
--output-data-file /data/extra_vars.yml
----

. When you have run these commands, a `command_generator_data/extra_vars.yml` template file is created.
This template file resembles the following:
+
[options="nowrap" subs="+attributes"]
----

aws_remove_extension_nodes:
  ansible_config_path:
  cloud_credentials_path:
  deployment_name:
  extra_vars:
    aws_autoscaling_group_name:
    aws_launch_template_name:
    aws_region:
    aws_ssm_bucket_name:
----
