:_mod-docs-content-type: REFERENCE

[id="ref-aws-additional-configs-update-admin-password"]

= Changing the default {PlatformNameShort} Administrator password

The default Administrator password for {PlatformNameShort} is generated randomly when {AAPonAWS} is deployed. 
Follow these steps to change the Administrator password for both {ControllerName} and {HubName}:

.Procedure
. Navigate to the AWS Secrets Manager console.
.. Locate and open the secret for the CloudFormation Stack with the name `*<stack_name>*-aap-admin-secret`.
.. Select *Retrieve secret value* to view the secret value.
.. Select *Edit* and provide an updated password value.
.. Click btn:[Save].
. Change the running {PlatformNameShort} EC2 instances to use the new Administrator password.
.. Navigate to the AWS EC2 Instances console.
.. Identify and Terminate one {ControllerName} instance and one {HubName} instance for the CloudFormation Stack.
.. Wait for the {ControllerName} and {HubName} Auto Scaling Groups to create new EC2 instances.
. The new Administrator can be used when the new {ControllerName} and {HubName} EC2 instances reach a _Running_ instance state.
