:_mod-docs-content-type: REFERENCE

[id="ref-aws-getting-extension-node-subscription"]

= Getting an Extension Node Subscription

.Public Offer
{AAPonAWS} can be obtained directly from the {Market}.
Follow these steps to purchase an extension node subscription.

.Procedure

. In the AWS Console, navigate to menu:AWS Marketplace Subscriptions[].
. In the navigation bar, click btn:[Discover Products].
. Click one of the listings for *{PlatformName} 2 Extension - Up to 100|200|400 Managed Nodes*. Whichever is suitable for your workload needs.
. Click btn:[Continue to Subscribe].
. Read terms, if you agree to them, click btn:[Accept Terms].
. You should shortly be subscribed to an extnesion node offer.

.Private Offer
If you have worked with Red Hat Sales to enable a private offer of {AAPonAWS}, follow these steps to accept your offer.

.Procedure
. Visit your Private Offer with the URL link provided by your Red Hat Sales representative.
. Click btn:[Accept Terms] to subscribe to the AMI Private Offer named {AAPonAWS}.

[NOTE]
====
If you are accepting terms for {PlatformNameShort} extension nodes, then assign the number of virtual machines arranged with your Red Hat Sales representative.  The number of VMs directly correlates to the number of licensed managed active nodes that you have purchased.

After subscribing, the offer is also listed in your {Market} Subscriptions. 
====
