:_mod-docs-content-type: REFERENCE

[id="ref-gcp-networking-options"]

= Networking options

The network topology of {AAPonGCP} includes several configurable network segments that can be changed to fit into your organization's network requirements.

The deployment creates a new VPC and subnet that are not accessible from the public internet, or by using an existing VPC network. 
You must provide access to the application as described in xref:assembly-gcp-networking-access[Networking and Application Access]. 

Consider your existing network configurations when specifying the following network ranges below. 
Ensure that each range does not overlap with any other specified here, and does not overlap with existing ranges in your network. 
Each range should exist within a private network class.

.*Application Subnet Range*
The network CIDR defining the subnet range used by the custom VPC deployed by the offering. 
Must be a minimum `/24` segment and must be in the private network range (192.168 or 10.0).  

Default: 192.168.240.0/24

.*Cloud SQL Peering Network Range*  
The network CIDR defines the network segment used to peer the GCP CloudSQL network with the application subnet deployed by the offering.  
Must be a `/24` segment.  
The `/24` segment range is a requirement of GCP CloudSQL network peering configuration. 

Default: 192.168.241.0/24

.*Filestore Peering Network Range*  
{AAPonGCP} uses GCP Filestore service to share configuration files between multiple {ControllerName} and {HubName} VMs provisioned as part of the deployment. 
This network CIDR range defines the peer network that is used by the offering to peer between the GCP Filestore network and the custom VPC application subnet of the offering.
Must be a minimum `/29` segment.  

Default: 192.168.243.0/29

.*Load Balancer Proxy Subnet Range*  
{AAPonGCP} is deployed using GCP’s native cloud capabilities to provide a scalable and reliable installation. 
As part of the {AAPonGCP} deployment topology two load balancers are deployed in front of the {HubName} and {ControllerName} VMs. 
All traffic is directed at these load balancers and is proxied to the available backend VMs. 
The deployment takes advantage of GCP’s native load balancing support enabling the customer to add additional ports (https) to the load balancers to capture and forward requests onto the backend VMs.
This also provides request balancing and session tracking for better reliability.  
As part of the load balancer deployment, GCP requires creation of a special proxy network where GCP natively handles the redirection of requests to the backend VMs. 
This special proxy network is not used within {AAPonGCP} for any other purpose than GCP’s load balancer’s proxy network requirement.  
A `/24` segment is required. 

Default: 192.168.242.0/24

.*Controller Internal Load Balancer IP Address*  
This is the static IP Address assigned to the {Controllername} Load Balancer.  
This address must be within the Application Subnet Range segment. 

Default: 192.168.240.20

.*Hub Internal Load Balancer IP Address*  
This is the static IP Address assigned to the {Hubname} Load Balancer. 
This address must be within the Application Subnet Range segment.  

Default: 192.168.240.21
